/** 报表管理初始数据 - 统计报表配置数据 */
export const dataList = () => [
  {
    reportCode: 'RPT-FJ-202412-001',
    reportName: '福州市道路养护月度统计报表',
    timeRange: '2024-12-01 - 2024-12-31',
    customFilterFields: '处置类型,核查结果,指派运维员',
    customStatisticsIndicators: '预警处置总时长,指标恢复值,归档文件数',
    createTime: '2024-12-31 18:00:00',
    createPerson: '张明（FJHC001）',
    lastModifyTime: '2024-12-31 18:30:00',
    lastModifyPerson: '张明（FJHC001）',
    reportStatus: '已生成',
    reportType: '月度统计',
    remark: '包含福州市所有道路养护数据汇总',
  },
  {
    reportCode: 'RPT-FJ-202412-002',
    reportName: '厦门市道路养护季度统计报表',
    timeRange: '2024-10-01 - 2024-12-31',
    customFilterFields: '处置路段,核查结果,处置类型',
    customStatisticsIndicators: '坑洼修补数量,裂缝填补长度,交通疏导次数',
    createTime: '2024-12-31 16:00:00',
    createPerson: '李丽（FJHC002）',
    lastModifyTime: '2024-12-31 17:15:00',
    lastModifyPerson: '李丽（FJHC002）',
    reportStatus: '已生成',
    reportType: '季度统计',
    remark: '厦门市第四季度道路养护数据分析',
  },
  {
    reportCode: 'RPT-FJ-202412-003',
    reportName: '泉州市道路养护年度统计报表',
    timeRange: '2024-01-01 - 2024-12-31',
    customFilterFields: '处置类型,核查员,工单完成时间',
    customStatisticsIndicators: '平均处置时长,合格率,总归档文件数',
    createTime: '2024-12-31 14:00:00',
    createPerson: '王强（FJHC003）',
    lastModifyTime: '2024-12-31 15:20:00',
    lastModifyPerson: '王强（FJHC003）',
    reportStatus: '生成中',
    reportType: '年度统计',
    remark: '泉州市2024年度道路养护综合统计',
  },
  {
    reportCode: 'RPT-FJ-202412-004',
    reportName: '漳州市道路养护月度统计报表',
    timeRange: '2024-12-01 - 2024-12-31',
    customFilterFields: '核查结果,指派运维员,处置路段',
    customStatisticsIndicators: '预警处置总时长,指标恢复值,核查合格率',
    createTime: '2024-12-31 11:30:00',
    createPerson: '陈杰（FJHC004）',
    lastModifyTime: '2024-12-31 13:45:00',
    lastModifyPerson: '陈杰（FJHC004）',
    reportStatus: '已生成',
    reportType: '月度统计',
    remark: '漳州市12月份道路养护数据统计',
  },
  {
    reportCode: 'RPT-FJ-202412-005',
    reportName: '莆田市道路养护季度统计报表',
    timeRange: '2024-10-01 - 2024-12-31',
    customFilterFields: '处置类型,核查结果,归档时间',
    customStatisticsIndicators: '坑洼修补数量,裂缝填补长度,交通疏导次数',
    createTime: '2024-12-30 15:00:00',
    createPerson: '赵伟（FJHC005）',
    lastModifyTime: '2024-12-30 16:30:00',
    lastModifyPerson: '赵伟（FJHC005）',
    reportStatus: '已生成',
    reportType: '季度统计',
    remark: '莆田市第四季度道路养护分析',
  },
  {
    reportCode: 'RPT-FJ-202412-006',
    reportName: '宁德市道路养护月度统计报表',
    timeRange: '2024-12-01 - 2024-12-31',
    customFilterFields: '处置路段,核查员,指派运维员',
    customStatisticsIndicators: '预警处置总时长,指标恢复值,归档文件数',
    createTime: '2024-12-30 10:00:00',
    createPerson: '孙丽（FJHC006）',
    lastModifyTime: '2024-12-30 11:20:00',
    lastModifyPerson: '孙丽（FJHC006）',
    reportStatus: '生成失败',
    reportType: '月度统计',
    remark: '数据异常，请重新配置统计条件',
  },
  {
    reportCode: 'RPT-FJ-202412-007',
    reportName: '龙岩市道路养护年度统计报表',
    timeRange: '2024-01-01 - 2024-12-31',
    customFilterFields: '处置类型,核查结果,工单完成时间',
    customStatisticsIndicators: '平均处置时长,合格率,总归档文件数',
    createTime: '2024-12-29 09:00:00',
    createPerson: '周明（FJHC007）',
    lastModifyTime: '2024-12-29 10:30:00',
    lastModifyPerson: '周明（FJHC007）',
    reportStatus: '已生成',
    reportType: '年度统计',
    remark: '龙岩市2024年度道路养护综合统计',
  },
  {
    reportCode: 'RPT-FJ-202412-008',
    reportName: '三明市道路养护季度统计报表',
    timeRange: '2024-10-01 - 2024-12-31',
    customFilterFields: '处置路段,核查结果,处置类型',
    customStatisticsIndicators: '坑洼修补数量,裂缝填补长度,交通疏导次数',
    createTime: '2024-12-28 14:00:00',
    createPerson: '吴杰（FJHC008）',
    lastModifyTime: '2024-12-28 15:45:00',
    lastModifyPerson: '吴杰（FJHC008）',
    reportStatus: '已生成',
    reportType: '季度统计',
    remark: '三明市第四季度道路养护分析',
  },
  {
    reportCode: 'RPT-FJ-202412-009',
    reportName: '南平市道路养护月度统计报表',
    timeRange: '2024-12-01 - 2024-12-31',
    customFilterFields: '处置类型,核查员,指派运维员',
    customStatisticsIndicators: '预警处置总时长,指标恢复值,归档文件数',
    createTime: '2024-12-27 16:00:00',
    createPerson: '郑浩（FJHC009）',
    lastModifyTime: '2024-12-27 17:30:00',
    lastModifyPerson: '郑浩（FJHC009）',
    reportStatus: '已生成',
    reportType: '月度统计',
    remark: '南平市12月份道路养护数据统计',
  },
  {
    reportCode: 'RPT-FJ-202412-010',
    reportName: '平潭综合实验区道路养护季度统计报表',
    timeRange: '2024-10-01 - 2024-12-31',
    customFilterFields: '处置路段,核查结果,处置类型',
    customStatisticsIndicators: '平均处置时长,合格率,总归档文件数',
    createTime: '2024-12-26 13:00:00',
    createPerson: '黄鑫（FJHC010）',
    lastModifyTime: '2024-12-26 14:20:00',
    lastModifyPerson: '黄鑫（FJHC010）',
    reportStatus: '已生成',
    reportType: '季度统计',
    remark: '平潭综合实验区第四季度道路养护分析',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 报表管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'reportCode',
      label: '报表编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入报表编号（如：RPT-FJ-202412-001）',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'reportName',
      label: '报表名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入报表名称（如：福州市道路养护月度统计报表）',
        maxLength: 100,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'timeRange',
      label: '统计时间范围',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择统计时间范围',
        type: 'daterange',
        format: 'YYYY-MM-DD',
        valueFormat: 'YYYY-MM-DD',
        rangeSeparator: ' - ',
      },
      rules: 'required',
    },
    {
      fieldName: 'customFilterFields',
      label: '自定义筛选字段',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择自定义筛选字段',
        mode: 'multiple',
        allowClear: true,
        filterOption: true,
        options: [
          { label: '处置类型', value: '处置类型' },
          { label: '核查结果', value: '核查结果' },
          { label: '指派运维员', value: '指派运维员' },
          { label: '处置路段', value: '处置路段' },
          { label: '核查员', value: '核查员' },
          { label: '工单完成时间', value: '工单完成时间' },
          { label: '归档时间', value: '归档时间' },
        ],
        showSearch: true,
        maxTagCount: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'customStatisticsIndicators',
      label: '自定义统计指标',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择自定义统计指标',
        mode: 'multiple',
        allowClear: true,
        filterOption: true,
        options: [
          { label: '预警处置总时长', value: '预警处置总时长' },
          { label: '指标恢复值', value: '指标恢复值' },
          { label: '归档文件数', value: '归档文件数' },
          { label: '坑洼修补数量', value: '坑洼修补数量' },
          { label: '裂缝填补长度', value: '裂缝填补长度' },
          { label: '交通疏导次数', value: '交通疏导次数' },
          { label: '平均处置时长', value: '平均处置时长' },
          { label: '合格率', value: '合格率' },
          { label: '总归档文件数', value: '总归档文件数' },
        ],
        showSearch: true,
        maxTagCount: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'reportType',
      label: '报表类型',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '月度统计', value: '月度统计' },
          { label: '季度统计', value: '季度统计' },
          { label: '年度统计', value: '年度统计' },
          { label: '自定义统计', value: '自定义统计' },
        ],
        placeholder: '请选择报表类型',
        showSearch: true,
      },
      rules: 'required',
    },
    {
      fieldName: 'remark',
      label: '备注说明',
      component: 'Input',
      componentProps: {
        placeholder: '请输入备注说明',
        maxlength: 500,
        type: 'textarea',
        rows: 4,
      },
      labelWidth: '120',
    },
  ];
}

/** 表格字段 - 报表管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'reportCode',
      title: '报表编号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'reportName',
      title: '报表名称',
      minWidth: 220,
      sortable: true,
    },
    {
      field: 'timeRange',
      title: '统计时间范围',
      minWidth: 220,
      sortable: true,
    },
    {
      field: 'customFilterFields',
      title: '自定义筛选字段',
      minWidth: 250,
      sortable: false,
    },
    {
      field: 'customStatisticsIndicators',
      title: '自定义统计指标',
      minWidth: 250,
      sortable: false,
    },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'createPerson',
      title: '创建人',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'lastModifyTime',
      title: '最后修改时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'lastModifyPerson',
      title: '最后修改人',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'reportStatus',
      title: '报表状态',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'reportType',
      title: '报表类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'remark',
      title: '备注',
      minWidth: 200,
      sortable: false,
    },
    {
      title: '操作',
      width: 150,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
