/** 表格初始数据 - 企业风险报告管理数据 */
export const dataList = () => [
  {
    reportNumber: 'RPT-QZ-LZ-202406-001',
    filterConditions: '区域：鲤城区；时间：2024-06；企业类型：燃气供应',
    generationTime: '2024-06-30 16:30:25',
    involvedCompanyCount: 42,
    riskLevelDistribution: '低风险:28,中风险:10,高风险:4',
    averageViolationCount: 2.1,
    averageRectificationRate: 88.5,
    highRiskPoints: '设备维护,操作规范',
    reportGenerator: '陈铭（工号：FJYW001）',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-002',
    filterConditions: '区域：丰泽区；时间：2024-06；企业类型：燃气供应',
    generationTime: '2024-06-30 15:45:18',
    involvedCompanyCount: 56,
    riskLevelDistribution: '低风险:38,中风险:14,高风险:4',
    averageViolationCount: 1.9,
    averageRectificationRate: 91.2,
    highRiskPoints: '操作规范,安全管理',
    reportGenerator: '林晓婷（工号：FJYW002）',
  },
  {
    reportNumber: 'RPT-QZ-LC-202406-003',
    filterConditions: '区域：洛江区；时间：2024-06；企业类型：管道运输',
    generationTime: '2024-06-30 14:20:33',
    involvedCompanyCount: 28,
    riskLevelDistribution: '低风险:20,中风险:6,高风险:2',
    averageViolationCount: 1.6,
    averageRectificationRate: 93.8,
    highRiskPoints: '设备维护',
    reportGenerator: '王志远（工号：FJYW003）',
  },
  {
    reportNumber: 'RPT-QZ-QG-202406-004',
    filterConditions: '区域：泉港区；时间：2024-06；企业类型：燃气储存',
    generationTime: '2024-06-30 13:15:42',
    involvedCompanyCount: 18,
    riskLevelDistribution: '低风险:12,中风险:4,高风险:2',
    averageViolationCount: 1.4,
    averageRectificationRate: 95.6,
    highRiskPoints: '安全管理',
    reportGenerator: '黄丽萍（工号：FJYW004）',
  },
  {
    reportNumber: 'RPT-QZ-JJ-202406-005',
    filterConditions: '区域：晋江市；时间：2024-06；企业类型：燃气加气',
    generationTime: '2024-06-30 12:30:56',
    involvedCompanyCount: 35,
    riskLevelDistribution: '低风险:22,中风险:10,高风险:3',
    averageViolationCount: 2.3,
    averageRectificationRate: 86.7,
    highRiskPoints: '设备维护,操作规范,安全管理',
    reportGenerator: '郑建明（工号：FJYW005）',
  },
  {
    reportNumber: 'RPT-QZ-NAN-202406-006',
    filterConditions: '区域：南安市；时间：2024-06；企业类型：燃气供应',
    generationTime: '2024-06-30 11:15:28',
    involvedCompanyCount: 32,
    riskLevelDistribution: '低风险:20,中风险:8,高风险:4',
    averageViolationCount: 2.0,
    averageRectificationRate: 89.3,
    highRiskPoints: '操作规范,设备维护',
    reportGenerator: '吴永辉（工号：FJYW006）',
  },
  {
    reportNumber: 'RPT-QZ-HS-202406-007',
    filterConditions: '区域：惠安县；时间：2024-06；企业类型：燃气供应',
    generationTime: '2024-06-30 10:30:42',
    involvedCompanyCount: 24,
    riskLevelDistribution: '低风险:18,中风险:5,高风险:1',
    averageViolationCount: 1.3,
    averageRectificationRate: 94.5,
    highRiskPoints: '操作规范',
    reportGenerator: '张志强（工号：FJYW007）',
  },
  {
    reportNumber: 'RPT-QZ-AN-202406-008',
    filterConditions: '区域：安溪县；时间：2024-06；企业类型：燃气供应',
    generationTime: '2024-06-30 09:45:15',
    involvedCompanyCount: 20,
    riskLevelDistribution: '低风险:16,中风险:3,高风险:1',
    averageViolationCount: 1.1,
    averageRectificationRate: 96.2,
    highRiskPoints: '安全管理',
    reportGenerator: '李芳（工号：FJYW008）',
  },
  {
    reportNumber: 'RPT-QZ-YC-202406-009',
    filterConditions: '区域：永春县；时间：2024-06；企业类型：管道运输',
    generationTime: '2024-06-30 09:00:33',
    involvedCompanyCount: 16,
    riskLevelDistribution: '低风险:12,中风险:3,高风险:1',
    averageViolationCount: 1.2,
    averageRectificationRate: 95.8,
    highRiskPoints: '设备维护',
    reportGenerator: '刘建国（工号：FJYW009）',
  },
  {
    reportNumber: 'RPT-QZ-DH-202406-010',
    filterConditions: '区域：德化县；时间：2024-06；企业类型：燃气加气',
    generationTime: '2024-06-30 08:30:56',
    involvedCompanyCount: 12,
    riskLevelDistribution: '低风险:10,中风险:2,高风险:0',
    averageViolationCount: 0.8,
    averageRectificationRate: 98.5,
    highRiskPoints: '无',
    reportGenerator: '蔡伟明（工号：FJYW010）',
  },
];


/** 新增/修改的表单/列表的搜索表单 - 企业风险报告管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'reportNumber',
      label: '报表编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入报表编号',
        maxLength: 50,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'filterConditions',
      label: '筛选条件',
      component: 'Input',
      componentProps: {
        type: 'textarea',
        placeholder: '请输入筛选条件（如：区域、时间、企业类型等）',
        rows: 3,
        maxlength: 200,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'generationTime',
      label: '生成时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择生成时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'involvedCompanyCount',
      label: '涉及企业数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入涉及企业数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'riskLevelDistribution',
      label: '整体风险等级分布',
      component: 'Input',
      componentProps: {
        placeholder: '请输入风险等级分布（如：低风险:98,中风险:42,高风险:16）',
        maxlength: 100,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'averageViolationCount',
      label: '平均违规频次',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入平均违规频次',
        min: 0,
        precision: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'averageRectificationRate',
      label: '平均整改完成率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入平均整改完成率（单位：%）',
        min: 0,
        max: 100,
        precision: 2,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'highRiskPoints',
      label: '高频风险点',
      component: 'Input',
      componentProps: {
        placeholder: '请输入高频风险点（如：设备维护,操作规范,安全管理）',
        maxlength: 100,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'reportGenerator',
      label: '报表生成人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入报表生成人姓名/工号',
        maxLength: 50,
      },
      labelWidth: '130',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 企业风险报告管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'reportNumber',
      title: '报表编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'reportNumber' },
    },
    {
      field: 'filterConditions',
      title: '筛选条件',
      minWidth: 250,
      sortable: false,
    },
    {
      field: 'generationTime',
      title: '生成时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'involvedCompanyCount',
      title: '涉及企业数量',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'riskLevelDistribution',
      title: '整体风险等级分布',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'averageViolationCount',
      title: '平均违规频次',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'averageRectificationRate',
      title: '平均整改完成率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'highRiskPoints',
      title: '高频风险点',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'reportGenerator',
      title: '报表生成人',
      minWidth: 150,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
