/** 表格初始数据 - 改造为垃圾清运月度统计考核数据 */
export const dataList = () => [
  {
    monthNo: '2024-06',
    monthTotalClearVolume: 2850.5,
    monthTotalViolationCases: 12,
    monthEnterpriseRank: 3,
    monthSpotCheckCoverage: 92.5,
    monthRectificationRate: 88.5,
    momChangeRate: 3.2,
    yoyChangeRate: 5.8,
  },
  {
    monthNo: '2024-05',
    monthTotalClearVolume: 2760.3,
    monthTotalViolationCases: 15,
    monthEnterpriseRank: 4,
    monthSpotCheckCoverage: 90.0,
    monthRectificationRate: 85.0,
    momChangeRate: -1.5,
    yoyChangeRate: 2.3,
  },
  {
    monthNo: '2024-04',
    monthTotalClearVolume: 2802.8,
    monthTotalViolationCases: 10,
    monthEnterpriseRank: 2,
    monthSpotCheckCoverage: 94.0,
    monthRectificationRate: 91.0,
    momChangeRate: 2.8,
    yoyChangeRate: 6.1,
  },
  {
    monthNo: '2024-03',
    monthTotalClearVolume: 2725.4,
    monthTotalViolationCases: 18,
    monthEnterpriseRank: 5,
    monthSpotCheckCoverage: 88.5,
    monthRectificationRate: 82.0,
    momChangeRate: 4.5,
    yoyChangeRate: 1.7,
  },
  {
    monthNo: '2024-02',
    monthTotalClearVolume: 2608.9,
    monthTotalViolationCases: 22,
    monthEnterpriseRank: 6,
    monthSpotCheckCoverage: 85.0,
    monthRectificationRate: 79.5,
    momChangeRate: -2.1,
    yoyChangeRate: -1.2,
  },
  {
    monthNo: '2024-01',
    monthTotalClearVolume: 2665.7,
    monthTotalViolationCases: 14,
    monthEnterpriseRank: 3,
    monthSpotCheckCoverage: 91.0,
    monthRectificationRate: 87.0,
    momChangeRate: 1.8,
    yoyChangeRate: 3.5,
  },
  {
    monthNo: '2023-12',
    monthTotalClearVolume: 2618.2,
    monthTotalViolationCases: 13,
    monthEnterpriseRank: 4,
    monthSpotCheckCoverage: 92.0,
    monthRectificationRate: 86.5,
    momChangeRate: 2.5,
    yoyChangeRate: 4.0,
  },
  {
    monthNo: '2023-11',
    monthTotalClearVolume: 2555.6,
    monthTotalViolationCases: 16,
    monthEnterpriseRank: 5,
    monthSpotCheckCoverage: 89.5,
    monthRectificationRate: 84.0,
    momChangeRate: -0.8,
    yoyChangeRate: 2.9,
  },
  {
    monthNo: '2023-10',
    monthTotalClearVolume: 2575.9,
    monthTotalViolationCases: 11,
    monthEnterpriseRank: 2,
    monthSpotCheckCoverage: 93.5,
    monthRectificationRate: 90.0,
    momChangeRate: 3.0,
    yoyChangeRate: 5.2,
  },
  {
    monthNo: '2023-09',
    monthTotalClearVolume: 2500.3,
    monthTotalViolationCases: 19,
    monthEnterpriseRank: 7,
    monthSpotCheckCoverage: 87.0,
    monthRectificationRate: 81.5,
    momChangeRate: -1.2,
    yoyChangeRate: 1.5,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为垃圾清运月度统计考核表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'monthNo',
      label: '统计月份',
      component: 'Input',
      componentProps: {
        placeholder: '请输入统计月份（如：2024-06）',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'monthTotalClearVolume',
      label: '月累计清运量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入月累计清运量（单位：吨）',
        min: 0,
        precision: 1,
        addonAfter: '吨',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthTotalViolationCases',
      label: '月违规案件总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入月违规案件总量',
        min: 0,
        precision: 0,
        addonAfter: '件',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthEnterpriseRank',
      label: '月清运企业考核排名',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入企业考核排名',
        min: 1,
        precision: 0,
        addonAfter: '名',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthSpotCheckCoverage',
      label: '月卡点检查覆盖率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入卡点检查覆盖率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthRectificationRate',
      label: '月乱倾倒点位整改率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入乱倾倒点位整改率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate',
      label: '环比增长率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比增长率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate',
      label: '同比增长率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比增长率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为垃圾清运月度统计考核表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'monthNo',
      title: '统计月份',
      minWidth: 120,
      sortable: true,
      slots: { default: 'monthNo' },
    },
    {
      field: 'monthTotalClearVolume',
      title: '月累计清运量(吨)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'monthTotalViolationCases',
      title: '月违规案件总量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monthEnterpriseRank',
      title: '月清运企业考核排名',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'monthSpotCheckCoverage',
      title: '月卡点检查覆盖率(%)',
      minWidth: 170,
      sortable: true,
    },
    {
      field: 'monthRectificationRate',
      title: '月乱倾倒点位整改率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate',
      title: '环比增长率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'yoyChangeRate',
      title: '同比增长率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
