/** 对账明细管理表格列配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: '记录编号',
      minWidth: 100,
      sortable: true,
      slots: { default: 'id' },
    },
    {
      field: 'billNo',
      title: '关联单据',
      minWidth: 160,
      sortable: true,
      slots: { default: 'billNo' },
    }, 
    {
      field: 'merchantName',
      title: '所属商户',
      minWidth: 160,
      sortable: true,
      slots: { default: 'merchantName' },
    },
    {
      field: 'orderNo',
      title: '订单编号',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'sysAmount',
      title: '系统金额',
      minWidth: 140,
      sortable: true,
      customRender: ({ text }) => text ? `¥${text.toFixed(2)}` : '¥0.00',
    },
    {
      field: 'merchantAmount',
      title: '商户上报金额',
      minWidth: 160,
      sortable: true,
      customRender: ({ text }) => text ? `¥${text.toFixed(2)}` : '¥0.00',
    },
    {
      field: 'diffAmount',
      title: '差异金额',
      minWidth: 120,
      sortable: true,
      customRender: ({ text }) => text ? `¥${text.toFixed(2)}` : '¥0.00',
    },
    {
      field: 'matchResult',
      title: '对账结果',
      minWidth: 120,
      sortable: true,
      slots: { default: 'matchResult' },
    },
    {
      field: 'diffReason',
      title: '异常原因',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'checkerName',
      title: '核查人',
      minWidth: 120,
      sortable: true,
      slots: { default: 'checkerName' },
    },
    {
      field: 'checkTime',
      title: '核查时间',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'reconcileTime',
      title: '对账时间',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'status',
      title: '记录状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'status' },
    },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      title: '操作',
      width: 150,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}