/** 表格初始数据 - 窨井盖设施监测季报数据 */
export const dataList = () => [
  {
    areaName: '福州市鼓楼区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 1500,
    quarterTotalHiddenTroubleCount: 180,
    quarterDisposalCompleteCount: 160,
    deviceQuarterOnlineRate: 97.5,
    quarterMajorHiddenTroubleCount: 25,
    quarterHiddenTroubleDisposalRate: 88.89,
    quarterMajorHiddenTroubleDisposalRate: 92,
    momHiddenTroubleChangeRate: 10,
    areaRiskLevel: '中',
    quarterAvgDisposalDuration: 8.5,
  },
  {
    areaName: '厦门市思明区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 2000,
    quarterTotalHiddenTroubleCount: 90,
    quarterDisposalCompleteCount: 90,
    deviceQuarterOnlineRate: 99.2,
    quarterMajorHiddenTroubleCount: 5,
    quarterHiddenTroubleDisposalRate: 100,
    quarterMajorHiddenTroubleDisposalRate: 100,
    momHiddenTroubleChangeRate: -5,
    areaRiskLevel: '低',
    quarterAvgDisposalDuration: 4.2,
  },
  {
    areaName: '泉州市丰泽区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 1800,
    quarterTotalHiddenTroubleCount: 270,
    quarterDisposalCompleteCount: 195,
    deviceQuarterOnlineRate: 85.3,
    quarterMajorHiddenTroubleCount: 45,
    quarterHiddenTroubleDisposalRate: 72.22,
    quarterMajorHiddenTroubleDisposalRate: 80,
    momHiddenTroubleChangeRate: 25,
    areaRiskLevel: '高',
    quarterAvgDisposalDuration: 15.6,
  },
  {
    areaName: '漳州市芗城区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 1200,
    quarterTotalHiddenTroubleCount: 45,
    quarterDisposalCompleteCount: 45,
    deviceQuarterOnlineRate: 99,
    quarterMajorHiddenTroubleCount: 2,
    quarterHiddenTroubleDisposalRate: 100,
    quarterMajorHiddenTroubleDisposalRate: 100,
    momHiddenTroubleChangeRate: -15,
    areaRiskLevel: '低',
    quarterAvgDisposalDuration: 3.8,
  },
  {
    areaName: '莆田市城厢区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 1600,
    quarterTotalHiddenTroubleCount: 225,
    quarterDisposalCompleteCount: 165,
    deviceQuarterOnlineRate: 78.6,
    quarterMajorHiddenTroubleCount: 35,
    quarterHiddenTroubleDisposalRate: 73.33,
    quarterMajorHiddenTroubleDisposalRate: 77.14,
    momHiddenTroubleChangeRate: 20,
    areaRiskLevel: '高',
    quarterAvgDisposalDuration: 12.5,
  },
  {
    areaName: '宁德市蕉城区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 1400,
    quarterTotalHiddenTroubleCount: 75,
    quarterDisposalCompleteCount: 69,
    deviceQuarterOnlineRate: 97.8,
    quarterMajorHiddenTroubleCount: 8,
    quarterHiddenTroubleDisposalRate: 92,
    quarterMajorHiddenTroubleDisposalRate: 100,
    momHiddenTroubleChangeRate: 5,
    areaRiskLevel: '中',
    quarterAvgDisposalDuration: 6.2,
  },
  {
    areaName: '龙岩市新罗区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 1700,
    quarterTotalHiddenTroubleCount: 180,
    quarterDisposalCompleteCount: 135,
    deviceQuarterOnlineRate: 96.5,
    quarterMajorHiddenTroubleCount: 20,
    quarterHiddenTroubleDisposalRate: 75,
    quarterMajorHiddenTroubleDisposalRate: 85,
    momHiddenTroubleChangeRate: 15,
    areaRiskLevel: '中',
    quarterAvgDisposalDuration: 9.8,
  },
  {
    areaName: '三明市梅列区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 1300,
    quarterTotalHiddenTroubleCount: 30,
    quarterDisposalCompleteCount: 30,
    deviceQuarterOnlineRate: 98.9,
    quarterMajorHiddenTroubleCount: 1,
    quarterHiddenTroubleDisposalRate: 100,
    quarterMajorHiddenTroubleDisposalRate: 100,
    momHiddenTroubleChangeRate: -10,
    areaRiskLevel: '低',
    quarterAvgDisposalDuration: 4.5,
  },
  {
    areaName: '南平市延平区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 1500,
    quarterTotalHiddenTroubleCount: 135,
    quarterDisposalCompleteCount: 105,
    deviceQuarterOnlineRate: 88.7,
    quarterMajorHiddenTroubleCount: 15,
    quarterHiddenTroubleDisposalRate: 77.78,
    quarterMajorHiddenTroubleDisposalRate: 93.33,
    momHiddenTroubleChangeRate: 12,
    areaRiskLevel: '中',
    quarterAvgDisposalDuration: 14.2,
  },
  {
    areaName: '平潭综合实验区',
    quarterStatisticsPeriod: '2024年第2季度',
    manholeTotalCount: 1100,
    quarterTotalHiddenTroubleCount: 36,
    quarterDisposalCompleteCount: 36,
    deviceQuarterOnlineRate: 99.5,
    quarterMajorHiddenTroubleCount: 0,
    quarterHiddenTroubleDisposalRate: 100,
    quarterMajorHiddenTroubleDisposalRate: 100,
    momHiddenTroubleChangeRate: -8,
    areaRiskLevel: '低',
    quarterAvgDisposalDuration: 5.1,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施监测季报表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'quarterStatisticsPeriod',
      label: '季统计时段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入季统计时段（如：2024年第2季度）',
        maxlength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 季统计时段为必填项
    },
  ];
}

/** 表格字段 - 窨井盖设施监测季报表格列 */
export function useGridColumns() {
  return [
    {
      field: 'areaName',
      title: '所属区域',
      minWidth: 180,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'quarterStatisticsPeriod',
      title: '季统计时段',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'manholeTotalCount',
      title: '窨井盖总数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'quarterTotalHiddenTroubleCount',
      title: '季累计隐患数',
      minWidth: 140,
      sortable: true,
      slots: { default: 'quarterTotalHiddenTroubleCount' },
    },
    {
      field: 'quarterDisposalCompleteCount',
      title: '季处置完成数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deviceQuarterOnlineRate',
      title: '设备季在线率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'quarterMajorHiddenTroubleCount',
      title: '季重大隐患数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'quarterHiddenTroubleDisposalRate',
      title: '季隐患处置完成率(%)',
      minWidth: 180,
      sortable: true,
      slots: { default: 'quarterHiddenTroubleDisposalRate' },
    },
    {
      field: 'quarterMajorHiddenTroubleDisposalRate',
      title: '季重大隐患处置率(%)',
      minWidth: 180,
      sortable: true,
      slots: { default: 'quarterMajorHiddenTroubleDisposalRate' },
    },
    {
      field: 'momHiddenTroubleChangeRate',
      title: '环比隐患变化率(%)',
      minWidth: 160,
      sortable: true,
      slots: { default: 'momHiddenTroubleChangeRate' },
    },
    {
      field: 'areaRiskLevel',
      title: '区域风险等级',
      minWidth: 140,
      sortable: true,
      slots: { default: 'areaRiskLevel' },
    },
    {
      field: 'quarterAvgDisposalDuration',
      title: '季平均处置时长(小时)',
      minWidth: 160,
      sortable: true,
    },
    {
      title: '操作',
      width: 240,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
