/** 表格初始数据 - 改造为巡检管理数据（新字段适配） */
export const dataList = () => {
  return [
    {
      id: '2',
      inspectorName: '王小明', // 巡检员姓名
      belongArea: '龙文区-碧湖街道', // 所属片区
      relatedBerthPoints: 'B00201、B00202、B00203、碧湖公园入口泊位群', // 关联泊位点
      responsiblePeriod: '08:00-18:00（周一至周五）', // 负责时段
      contactPhone: '13800138000', // 联系电话
      relatedStatus: '已关联', // 关联状态
      effectiveTime: '2026-01-01 00:00:00', // 生效时间
      operator: '张管理员', // 操作人
    },
    {
      id: '3',
      inspectorName: '李华',
      belongArea: '龙海区-石码街道',
      relatedBerthPoints: 'B00204、B00205、B00206、石码便民停车场泊位',
      responsiblePeriod: '09:00-19:00（周一至周日）',
      contactPhone: '13900139000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '李主管',
    },
    {
      id: '4',
      inspectorName: '张伟',
      belongArea: '龙海区-海澄镇',
      relatedBerthPoints: 'B00207、B00208、闽齐社区停车场泊位群',
      responsiblePeriod: '08:00-17:30（周一至周五）',
      contactPhone: '13700137000',
      relatedStatus: '待关联',
      effectiveTime: '2026-01-10 00:00:00',
      operator: '张管理员',
    },
    {
      id: '5',
      inspectorName: '陈晨',
      belongArea: '芗城区-巷口街道',
      relatedBerthPoints: 'B00209、B00210、江滨路生态停车场泊位',
      responsiblePeriod: '07:30-18:30（周一至周日）',
      contactPhone: '13600136000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '陈师傅',
    },
    {
      id: '6',
      inspectorName: '刘洋',
      belongArea: '龙文区-蓝田街道',
      relatedBerthPoints: 'B00211、B00212、万达商圈周边路侧泊位',
      responsiblePeriod: '10:00-20:00（周一至周日）',
      contactPhone: '13500135000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '刘经理',
    },
    {
      id: '7',
      inspectorName: '黄涛',
      belongArea: '长泰区-武安镇',
      relatedBerthPoints: 'B00213、B00214、武安镇公共停车场泊位',
      responsiblePeriod: '08:00-17:00（周一至周五）',
      contactPhone: '13400134000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '黄管理员',
    },
    {
      id: '8',
      inspectorName: '郑凯',
      belongArea: '漳浦县-绥安镇',
      relatedBerthPoints: 'B00215、B00216、绥安镇便民停车场泊位群',
      responsiblePeriod: '09:00-18:00（周一至周六）',
      contactPhone: '13300133000',
      relatedStatus: '关联失效',
      effectiveTime: '2025-12-01 00:00:00',
      operator: '郑师傅',
    },
    {
      id: '9',
      inspectorName: '吴杰',
      belongArea: '芗城区-巷口街道',
      relatedBerthPoints: 'B00217、B00218、巷口街道沿线路侧泊位',
      responsiblePeriod: '07:00-17:00（周一至周五）',
      contactPhone: '13200132000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '吴主管',
    },
    {
      id: '10',
      inspectorName: '林强',
      belongArea: '龙文区-蓝田街道',
      relatedBerthPoints: 'B00219、B00220、蓝田街道路侧泊位群',
      responsiblePeriod: '08:30-19:30（周一至周日）',
      contactPhone: '13100131000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '林师傅',
    },
    {
      id: '11',
      inspectorName: '赵阳',
      belongArea: '龙文区-步文街道',
      relatedBerthPoints: 'B00221、B00222、步文街道停车场泊位',
      responsiblePeriod: '09:30-19:30（周一至周日）',
      contactPhone: '13000130000',
      relatedStatus: '待关联',
      effectiveTime: '2026-01-15 00:00:00',
      operator: '赵经理',
    },
    {
      id: '12',
      inspectorName: '孙丽',
      belongArea: '芗城区-东铺头街道',
      relatedBerthPoints: 'B00223、B00224、东铺头街道专用停车场泊位',
      responsiblePeriod: '08:00-18:00（周一至周五）',
      contactPhone: '12900129000',
      relatedStatus: '关联失效',
      effectiveTime: '2025-11-30 00:00:00',
      operator: '孙管理员',
    },
    {
      id: '13',
      inspectorName: '周敏',
      belongArea: '芗城区-西桥街道',
      relatedBerthPoints: 'B00225、B00226、西桥街道专用停车场泊位群',
      responsiblePeriod: '08:00-17:30（周一至周六）',
      contactPhone: '12800128000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '周师傅',
    },
    {
      id: '14',
      inspectorName: '马丽',
      belongArea: '龙海区-石码街道',
      relatedBerthPoints: 'B00227、B00228、石码街道改造停车场泊位',
      responsiblePeriod: '10:00-20:00（周一至周日）',
      contactPhone: '12700127000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '马主管',
    },
    {
      id: '15',
      inspectorName: '朱峰',
      belongArea: '长泰区-武安镇',
      relatedBerthPoints: 'B00229、B00230、武安镇汇总停车场泊位群',
      responsiblePeriod: '08:00-18:00（周一至周五）',
      contactPhone: '12600126000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '朱管理员',
    },
    {
      id: '16',
      inspectorName: '韩磊',
      belongArea: '漳浦县-绥安镇',
      relatedBerthPoints: 'B00231、B00232、绥安镇核心区域停车场泊位',
      responsiblePeriod: '09:00-19:00（周一至周日）',
      contactPhone: '12500125000',
      relatedStatus: '待关联',
      effectiveTime: '2026-01-20 00:00:00',
      operator: '韩师傅',
    },
    {
      id: '17',
      inspectorName: '秦芳',
      belongArea: '云霄县-云陵镇',
      relatedBerthPoints: 'B00233、B00234、云陵镇专用停车场泊位',
      responsiblePeriod: '08:30-18:30（周一至周五）',
      contactPhone: '12400124000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '秦主管',
    },
    {
      id: '18',
      inspectorName: '许燕',
      belongArea: '诏安县-南诏镇',
      relatedBerthPoints: 'B00235、B00236、南诏镇整改停车场泊位群',
      responsiblePeriod: '07:30-17:30（周一至周六）',
      contactPhone: '12300123000',
      relatedStatus: '关联失效',
      effectiveTime: '2025-12-15 00:00:00',
      operator: '许管理员',
    },
    {
      id: '19',
      inspectorName: '邓佳',
      belongArea: '平和县-小溪镇',
      relatedBerthPoints: 'B00237、B00238、小溪镇公共停车场泊位',
      responsiblePeriod: '08:00-19:00（周一至周日）',
      contactPhone: '12200122000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '邓师傅',
    },
    {
      id: '24',
      inspectorName: '彭伟',
      belongArea: '龙文区-蓝田街道',
      relatedBerthPoints: 'B00239、B00240、蓝田街道二期停车场泊位',
      responsiblePeriod: '08:00-18:00（周一至周日）',
      contactPhone: '12100121000',
      relatedStatus: '已关联',
      effectiveTime: '2026-01-01 00:00:00',
      operator: '彭管理员',
    },
    {
      id: '25',
      inspectorName: '彭伟',
      belongArea: '龙文区-蓝田街道',
      relatedBerthPoints: 'B00241、B00242、蓝田街道三期停车场泊位群',
      responsiblePeriod: '09:00-19:00（周一至周五）',
      contactPhone: '12100121000',
      relatedStatus: '待关联',
      effectiveTime: '2026-01-25 00:00:00',
      operator: '彭管理员',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 - 改造为巡检管理表单（新字段适配） */
export function useFormSchema() {
  return [
    {
      fieldName: 'id',
      label: '巡检记录ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入巡检记录ID',
      },
      labelWidth: '100',
      rules: 'required',
    },
    {
      fieldName: 'inspectorName',
      label: '巡检员姓名',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入巡检员姓名',
      },
      rules: 'required',
    },
    {
      fieldName: 'belongArea',
      label: '所属片区',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入所属片区（如：龙文区-碧湖街道）',
      },
      rules: 'required',
    },
    {
      fieldName: 'relatedBerthPoints',
      label: '关联泊位点',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入关联泊位点（如：B00201、B00202、碧湖公园泊位群）',
        type: 'textarea',
        rows: 3
      },
      rules: 'required',
    },
    {
      fieldName: 'responsiblePeriod',
      label: '负责时段',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入负责时段（如：08:00-18:00（周一至周五））',
      },
      rules: 'required',
    },
    {
      fieldName: 'contactPhone',
      label: '联系电话',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入巡检员联系电话',
        type: 'tel'
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '已关联', value: '已关联' },
          { label: '待关联', value: '待关联' },
          { label: '关联失效', value: '关联失效' }
        ],
        placeholder: '请选择关联状态',
        showSearch: true,
      },
      fieldName: 'relatedStatus',
      label: '关联状态',
      rules: 'required',
    },
    {
      fieldName: 'effectiveTime',
      label: '生效时间',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        placeholder: '请选择生效时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'operator',
      label: '操作人',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入操作人姓名',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为巡检管理表格列（新字段适配） */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: '巡检记录ID',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'inspectorName',
      title: '巡检员姓名',
      minWidth: 120,
      sortable: true,
      slots: { default: 'inspectorName' },
    },
    {
      field: 'belongArea',
      title: '所属片区',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'relatedBerthPoints',
      title: '关联泊位点',
      minWidth: 280,
      sortable: false,
    },
    {
      field: 'responsiblePeriod',
      title: '负责时段',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'contactPhone',
      title: '联系电话',
      minWidth: 130,
      sortable: false,
    },
    {
      field: 'relatedStatus',
      title: '关联状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'effectiveTime',
      title: '生效时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'operator',
      title: '操作人',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 - 改造为巡检管理文案（新字段适配） */
export const textObj = {
  editText: '编辑巡检记录',
  addText: '新增巡检记录',
  excelName: '巡检记录列表',
  excelAllName: '全市巡检记录数据.xlsx',
  total: '巡检记录数量20;已关联14条;待关联4条;关联失效2条',
};