/** 表格初始数据 - 改造为巡检管理数据 */
export const dataList = () => {
  return [
    {
      id: '2',
      inspectorName: '王小明', // 巡检员姓名
      inspectionPeriod: '08:00-10:00', // 巡检时段
      belongArea: '龙文区-碧湖街道', // 所属片区
      inspectionTrack: '碧湖公园入口→江滨路沿线→碧湖街道办事处→返回停车场', // 巡检轨迹
      relatedOperationRecord: '整改违停车辆3辆、登记故障泊位2个、上报设备异常1起', // 关联操作记录
      trackDuration: '1小时58分钟', // 轨迹时长
      trackCompletion: '100%', // 轨迹完成度
      recordTime: '2026-01-10 10:05:00', // 记录时间
    },
    {
      id: '3',
      inspectorName: '李华',
      inspectionPeriod: '10:00-12:00',
      belongArea: '龙海区-石码街道',
      inspectionTrack: '石码镇便民停车场→中山路沿线→闽江路社区→专用停车场',
      relatedOperationRecord: '登记正常泊位50个、更新停车场信息1条、协助车主寻车2次',
      trackDuration: '1小时50分钟',
      trackCompletion: '100%',
      recordTime: '2026-01-08 12:10:00',
    },
    {
      id: '4',
      inspectorName: '张伟',
      inspectionPeriod: '14:00-16:00',
      belongArea: '龙海区-海澄镇',
      inspectionTrack: '闽齐社区入口→社区停车场→海澄镇政府周边→社区出口',
      relatedOperationRecord: '整改杂物堆放1处、登记运营状态正常、更新联系电话1个',
      trackDuration: '1小时45分钟',
      trackCompletion: '95%',
      recordTime: '2026-01-15 16:50:00',
    },
    {
      id: '5',
      inspectorName: '陈晨',
      inspectionPeriod: '09:00-11:00',
      belongArea: '芗城区-巷口街道',
      inspectionTrack: '江滨路生态停车场→巷口街道沿线→东铺头路口→返回停车场',
      relatedOperationRecord: '上报收费设备故障1台、登记泊位总数200个、记录营业时间更新',
      trackDuration: '2小时05分钟',
      trackCompletion: '100%',
      recordTime: '2026-01-12 11:15:00',
    },
    {
      id: '6',
      inspectorName: '刘洋',
      inspectionPeriod: '15:00-17:00',
      belongArea: '龙文区-蓝田街道',
      inspectionTrack: '万达商圈入口→万达停车场→蓝田街道办事处→商圈出口',
      relatedOperationRecord: '整改违停车辆5辆、登记运营状态正常、协助维护秩序3次',
      trackDuration: '1小时55分钟',
      trackCompletion: '100%',
      recordTime: '2026-01-14 17:10:00',
    },
    {
      id: '7',
      inspectorName: '黄涛',
      inspectionPeriod: '08:30-10:30',
      belongArea: '长泰区-武安镇',
      inspectionTrack: '武安镇公共停车场→武安镇政府周边→便民停车场→返回起点',
      relatedOperationRecord: '登记泊位总数100个、更新联系电话2个、记录无异常情况',
      trackDuration: '1小时40分钟',
      trackCompletion: '90%',
      recordTime: '2026-01-09 10:35:00',
    },
    {
      id: '8',
      inspectorName: '郑凯',
      inspectionPeriod: '13:00-15:00',
      belongArea: '漳浦县-绥安镇',
      inspectionTrack: '绥安镇便民停车场→绥安镇政府→核心区域停车场→返回停车场',
      relatedOperationRecord: '整改杂物堆放2处、登记运营状态正常、上报路面破损1处',
      trackDuration: '1小时50分钟',
      trackCompletion: '98%',
      recordTime: '2026-01-05 15:05:00',
    },
    {
      id: '9',
      inspectorName: '吴杰',
      inspectionPeriod: '07:30-09:30',
      belongArea: '芗城区-巷口街道',
      inspectionTrack: '巷口街道停车场→江滨路沿线→东铺头街道→返回停车场',
      relatedOperationRecord: '登记收费标准更新、整改违停车辆2辆、记录无设备异常',
      trackDuration: '2小时00分钟',
      trackCompletion: '100%',
      recordTime: '2026-01-03 09:35:00',
    },
    {
      id: '10',
      inspectorName: '林强',
      inspectionPeriod: '16:00-18:00',
      belongArea: '龙文区-蓝田街道',
      inspectionTrack: '蓝田街道路侧泊位→梧桥中路→蓝田街道办事处→返回泊位区',
      relatedOperationRecord: '登记泊位总数150个、整改违停车辆4辆、上报路灯故障1起',
      trackDuration: '1小时58分钟',
      trackCompletion: '100%',
      recordTime: '2026-01-07 18:10:00',
    },
    {
      id: '11',
      inspectorName: '赵阳',
      inspectionPeriod: '09:30-11:30',
      belongArea: '龙文区-步文街道',
      inspectionTrack: '步文街道停车场→步文政府周边→便民停车场→返回起点',
      relatedOperationRecord: '更新运营状态信息、登记泊位总数180个、协助车主寻车1次',
      trackDuration: '1小时52分钟',
      trackCompletion: '99%',
      recordTime: '2026-01-16 11:35:00',
    },
    {
      id: '12',
      inspectorName: '孙丽',
      inspectionPeriod: '14:30-16:30',
      belongArea: '芗城区-东铺头街道',
      inspectionTrack: '东铺头街道停车场→中山路沿线→西桥街道→返回停车场',
      relatedOperationRecord: '整改杂物堆放1处、登记联系电话更新、上报设备故障1台',
      trackDuration: '1小时48分钟',
      trackCompletion: '95%',
      recordTime: '2026-01-11 16:40:00',
    },
    {
      id: '13',
      inspectorName: '周敏',
      inspectionPeriod: '10:30-12:30',
      belongArea: '芗城区-西桥街道',
      inspectionTrack: '西桥街道专用停车场→西桥政府周边→江滨路→返回停车场',
      relatedOperationRecord: '登记收费标准正常、整改违停车辆1辆、记录无异常情况',
      trackDuration: '1小时55分钟',
      trackCompletion: '100%',
      recordTime: '2026-01-06 12:35:00',
    },
    {
      id: '14',
      inspectorName: '马丽',
      inspectionPeriod: '11:00-13:00',
      belongArea: '龙海区-石码街道',
      inspectionTrack: '石码街道改造停车场→石码中山路→改造区域出口→返回停车场',
      relatedOperationRecord: '登记改造进度、上报施工杂物1处、更新运营状态信息',
      trackDuration: '1小时50分钟',
      trackCompletion: '98%',
      recordTime: '2026-01-01 13:05:00',
    },
    {
      id: '15',
      inspectorName: '朱峰',
      inspectionPeriod: '17:00-19:00',
      belongArea: '长泰区-武安镇',
      inspectionTrack: '武安镇汇总停车场→武安镇政府→便民停车场→返回汇总点',
      relatedOperationRecord: '登记泊位总数300个、更新收费标准2条、记录无异常情况',
      trackDuration: '2小时02分钟',
      trackCompletion: '100%',
      recordTime: '2026-01-13 19:10:00',
    },
    {
      id: '16',
      inspectorName: '韩磊',
      inspectionPeriod: '13:30-15:30',
      belongArea: '漳浦县-绥安镇',
      inspectionTrack: '绥安镇核心停车场→绥安政府周边→核心区域出口→返回停车场',
      relatedOperationRecord: '整改违停车辆3辆、登记运营状态正常、上报路面破损1处',
      trackDuration: '1小时49分钟',
      trackCompletion: '97%',
      recordTime: '2026-01-15 15:35:00',
    },
    {
      id: '17',
      inspectorName: '秦芳',
      inspectionPeriod: '08:00-10:00',
      belongArea: '云霄县-云陵镇',
      inspectionTrack: '云陵镇专用停车场→云陵政府周边→江滨路→返回停车场',
      relatedOperationRecord: '登记泊位总数80个、更新联系电话1个、记录无异常情况',
      trackDuration: '1小时45分钟',
      trackCompletion: '100%',
      recordTime: '2026-01-04 10:05:00',
    },
    {
      id: '18',
      inspectorName: '许燕',
      inspectionPeriod: '15:00-17:00',
      belongArea: '诏安县-南诏镇',
      inspectionTrack: '南诏镇整改停车场→南诏政府周边→整改区域出口→返回停车场',
      relatedOperationRecord: '登记整改进度、上报杂物堆放2处、更新运营状态信息',
      trackDuration: '1小时58分钟',
      trackCompletion: '96%',
      recordTime: '2025-12-28 17:05:00',
    },
    {
      id: '19',
      inspectorName: '邓佳',
      inspectionPeriod: '16:30-18:30',
      belongArea: '平和县-小溪镇',
      inspectionTrack: '小溪镇停车场→小溪政府周边→便民停车场→返回起点',
      relatedOperationRecord: '整改违停车辆2辆、登记收费标准正常、上报设备异常1起',
      trackDuration: '1小时52分钟',
      trackCompletion: '100%',
      recordTime: '2026-01-14 18:35:00',
    },
    {
      id: '24',
      inspectorName: '彭伟',
      inspectionPeriod: '07:30-09:30',
      belongArea: '龙文区-蓝田街道',
      inspectionTrack: '蓝田街道二期停车场→梧桥中路→二期出口→返回停车场',
      relatedOperationRecord: '登记泊位总数120个、整改违停车辆1辆、记录无异常情况',
      trackDuration: '1小时48分钟',
      trackCompletion: '99%',
      recordTime: '2026-01-16 09:35:00',
    },
    {
      id: '25',
      inspectorName: '彭伟',
      inspectionPeriod: '08:00-10:00',
      belongArea: '龙文区-蓝田街道',
      inspectionTrack: '蓝田街道三期停车场→梧桥中路次入口→三期出口→返回停车场',
      relatedOperationRecord: '登记泊位总数80个、更新联系电话1个、上报路灯故障1起',
      trackDuration: '1小时50分钟',
      trackCompletion: '98%',
      recordTime: '2026-01-16 10:05:00',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 - 改造为巡检管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'id',
      label: '巡检记录ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入巡检记录ID',
      },
      labelWidth: '100',
      rules: 'required',
    },
    {
      fieldName: 'inspectorName',
      label: '巡检员姓名',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入巡检员姓名',
      },
      rules: 'required',
    },
    {
      fieldName: 'inspectionPeriod',
      label: '巡检时段',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入巡检时段（如：08:00-10:00）',
      },
      rules: 'required',
    },
    {
      fieldName: 'belongArea',
      label: '所属片区',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入所属片区（如：龙文区-碧湖街道）',
      },
      rules: 'required',
    },
    {
      fieldName: 'inspectionTrack',
      label: '巡检轨迹',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入巡检轨迹（如：碧湖公园入口→江滨路沿线）',
        type: 'textarea',
        rows: 3
      },
      rules: 'required',
    },
    {
      fieldName: 'relatedOperationRecord',
      label: '关联操作记录',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入关联操作记录（如：整改违停车辆3辆、登记故障泊位2个）',
        type: 'textarea',
        rows: 3
      },
      rules: 'required',
    },
    {
      fieldName: 'trackDuration',
      label: '轨迹时长',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入轨迹时长（如：1小时58分钟）',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '100%', value: '100%' },
          { label: '99%', value: '99%' },
          { label: '98%', value: '98%' },
          { label: '95%', value: '95%' },
          { label: '90%', value: '90%' },
          { label: '低于90%', value: '低于90%' },
        ],
        placeholder: '请选择轨迹完成度',
        showSearch: true,
      },
      fieldName: 'trackCompletion',
      label: '轨迹完成度',
      rules: 'required',
    },
    {
      fieldName: 'recordTime',
      label: '记录时间',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        placeholder: '请选择记录时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为巡检管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: '巡检记录ID',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'inspectorName',
      title: '巡检员姓名',
      minWidth: 120,
      sortable: true,
      slots: { default: 'inspectorName' },
    },
    {
      field: 'inspectionPeriod',
      title: '巡检时段',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'belongArea',
      title: '所属片区',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'inspectionTrack',
      title: '巡检轨迹',
      minWidth: 280,
      sortable: false,
    },
    {
      field: 'relatedOperationRecord',
      title: '关联操作记录',
      minWidth: 280,
      sortable: false,
    },
    {
      field: 'trackDuration',
      title: '轨迹时长',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'trackCompletion',
      title: '轨迹完成度',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'recordTime',
      title: '记录时间',
      minWidth: 200,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 - 改造为巡检管理文案 */
export const textObj = {
  editText: '编辑巡检记录',
  addText: '新增巡检记录',
  excelName: '巡检记录列表',
  excelAllName: '全市巡检记录数据.xlsx',
  total: '巡检记录数量20;完成度100%共12条;95%-99%共8条',
};