/** 交易运营报表表格列配置 */
export function useGridColumns() {
  return [
    {
      field: 'id',
      title: '报表记录ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'reportCycle',
      title: '报表周期',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'statTime',
      title: '统计时段',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'cycleOrderCount',
      title: '周期订单数',
      minWidth: 120,
      sortable: true,
      customRender: ({ text }) => text || 0,
    },
    {
      field: 'cycleRevenue',
      title: '周期营收(元)',
      minWidth: 140,
      sortable: true,
      customRender: ({ text }) => (text || 0).toFixed(2),
    },
    {
      field: 'payRate',
      title: '支付率(%)',
      minWidth: 120,
      sortable: true,
      customRender: ({ text }) => (text || 0).toFixed(2),
    },
    {
      field: 'chargeQuantity',
      title: '充电量(度)',
      minWidth: 120,
      sortable: true,
      customRender: ({ text }) => (text || 0).toFixed(2),
    },
    {
      field: 'lendCount',
      title: '借出量(次)',
      minWidth: 120,
      sortable: true,
      customRender: ({ text }) => text || 0,
    },
    {
      field: 'refundAmount',
      title: '退款金额(元)',
      minWidth: 140,
      sortable: true,
      customRender: ({ text }) => (text || 0).toFixed(2),
    },
    {
      field: 'waitHandleAbnormalCount',
      title: '待处置异常数',
      minWidth: 140,
      sortable: true,
      customRender: ({ text }) => text || 0,
    },
    {
      field: 'collectCompleteRate',
      title: '追缴完成率(%)',
      minWidth: 140,
      sortable: true,
      customRender: ({ text }) => (text || 0).toFixed(2),
    },
    {
      field: 'checkCompleteRate',
      title: '审核完成率(%)',
      minWidth: 140,
      sortable: true,
      customRender: ({ text }) => (text || 0).toFixed(2),
    },
    {
      field: 'checkAccuracyRate',
      title: '核算准确率(%)',
      minWidth: 140,
      sortable: true,
      customRender: ({ text }) => (text || 0).toFixed(2),
    },
    {
      field: 'generateStatus',
      title: '报表生成状态',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'createTime',
      title: '报表生成时间',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'operator',
      title: '操作人',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'yearOnYear',
      title: '同比',
      minWidth: 100,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'chainRatio',
      title: '环比',
      minWidth: 100,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'exportCount',
      title: '报表导出次数',
      minWidth: 140,
      sortable: true,
      customRender: ({ text }) => text || 0,
    },
    {
      title: '操作',
      width: 100,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
