/** 表格初始数据*/
export const dataList = () => {
  return [
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440001',
      reservation_no: 'RES202310150001',
      user_id: 'USER001',
      car_number: '闽A12345',
      charge_pile_id: 'DEVICE001',
      reserve_date: '2023-10-15',
      start_time: '09:00',
      end_time: '11:00',
      status: '已使用',
      actual_charge_time: '120',
      charge_amount: '25.5',
      charge_fee: '45.90',
      create_time: '2023-10-14 14:30:00',
      update_time: '2023-10-15 11:05:00',
      remark: '正常完成充电',
    },
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440002',
      reservation_no: 'RES202310150002',
      user_id: 'USER002',
      car_number: '闽B67890',
      charge_pile_id: 'DEVICE002',
      reserve_date: '2023-10-15',
      start_time: '10:30',
      end_time: '12:30',
      status: '待使用',
      actual_charge_time: '',
      charge_amount: '',
      charge_fee: '',
      create_time: '2023-10-14 16:20:00',
      update_time: '2023-10-14 16:20:00',
      remark: '提前预约',
    },
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440003',
      reservation_no: 'RES202310150003',
      user_id: 'USER003',
      car_number: '闽C34567',
      charge_pile_id: 'DEVICE003',
      reserve_date: '2023-10-15',
      start_time: '14:00',
      end_time: '16:00',
      status: '已取消',
      actual_charge_time: '',
      charge_amount: '',
      charge_fee: '',
      create_time: '2023-10-14 09:15:00',
      update_time: '2023-10-14 15:30:00',
      remark: '用户临时取消',
    },
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440004',
      reservation_no: 'RES202310160001',
      user_id: 'USER004',
      car_number: '闽D89012',
      charge_pile_id: 'DEVICE001',
      reserve_date: '2023-10-16',
      start_time: '08:00',
      end_time: '10:00',
      status: '已使用',
      actual_charge_time: '110',
      charge_amount: '23.8',
      charge_fee: '42.84',
      create_time: '2023-10-15 10:45:00',
      update_time: '2023-10-16 10:10:00',
      remark: '提前结束充电',
    },
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440005',
      reservation_no: 'RES202310160002',
      user_id: 'USER005',
      car_number: '闽E56789',
      charge_pile_id: 'DEVICE004',
      reserve_date: '2023-10-16',
      start_time: '13:30',
      end_time: '15:30',
      status: '待使用',
      actual_charge_time: '',
      charge_amount: '',
      charge_fee: '',
      create_time: '2023-10-15 14:20:00',
      update_time: '2023-10-15 14:20:00',
      remark: '',
    },
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440006',
      reservation_no: 'RES202310170001',
      user_id: 'USER006',
      car_number: '闽F123AB',
      charge_pile_id: 'DEVICE005',
      reserve_date: '2023-10-17',
      start_time: '09:30',
      end_time: '11:30',
      status: '已过期',
      actual_charge_time: '',
      charge_amount: '',
      charge_fee: '',
      create_time: '2023-10-16 11:10:00',
      update_time: '2023-10-17 12:00:00',
      remark: '未按时使用',
    },
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440007',
      reservation_no: 'RES202310170002',
      user_id: 'USER007',
      car_number: '闽G456CD',
      charge_pile_id: 'DEVICE002',
      reserve_date: '2023-10-17',
      start_time: '15:00',
      end_time: '17:00',
      status: '已使用',
      actual_charge_time: '130',
      charge_amount: '28.3',
      charge_fee: '50.94',
      create_time: '2023-10-16 13:40:00',
      update_time: '2023-10-17 17:15:00',
      remark: '超时15分钟',
    },
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440008',
      reservation_no: 'RES202310180001',
      user_id: 'USER008',
      car_number: '闽H789EF',
      charge_pile_id: 'DEVICE003',
      reserve_date: '2023-10-18',
      start_time: '10:00',
      end_time: '12:00',
      status: '已取消',
      actual_charge_time: '',
      charge_amount: '',
      charge_fee: '',
      create_time: '2023-10-17 09:25:00',
      update_time: '2023-10-17 20:15:00',
      remark: '设备故障，系统自动取消',
    },
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440009',
      reservation_no: 'RES202310180002',
      user_id: 'USER009',
      car_number: '闽J012GH',
      charge_pile_id: 'DEVICE006',
      reserve_date: '2023-10-18',
      start_time: '14:30',
      end_time: '16:30',
      status: '待使用',
      actual_charge_time: '',
      charge_amount: '',
      charge_fee: '',
      create_time: '2023-10-17 15:30:00',
      update_time: '2023-10-17 15:30:00',
      remark: '',
    },
    {
      charge_reserve_id: '550e8400-e29b-41d4-a716-446655440010',
      reservation_no: 'RES202310190001',
      user_id: 'USER010',
      car_number: '闽K345IJ',
      charge_pile_id: 'DEVICE001',
      reserve_date: '2023-10-19',
      start_time: '08:30',
      end_time: '10:30',
      status: '待使用',
      actual_charge_time: '',
      charge_amount: '',
      charge_fee: '',
      create_time: '2023-10-18 10:20:00',
      update_time: '2023-10-18 10:20:00',
      remark: '会员预约',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'charge_reserve_id',
      label: '预约记录ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入预约记录ID',
      },
    },
    {
      fieldName: 'reservation_no',
      label: '预约编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入预约编号',
      },
    },
    {
      fieldName: 'user_id',
      label: '用户ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入用户ID',
      },
      rules: 'required',
    },
    {
      fieldName: 'car_number',
      label: '车牌号码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入车牌号码',
      },
      rules: 'required',
    },
    {
      fieldName: 'charge_pile_id',
      label: '充电桩ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入充电桩ID',
      },
      rules: 'required',
    },
    {
      fieldName: 'reserve_date',
      label: '预约日期',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择预约日期',
        format: 'YYYY-MM-DD',
      },
      rules: 'required',
    },
    {
      fieldName: 'start_time',
      label: '开始时间',
      component: 'TimePicker',
      componentProps: {
        placeholder: '请选择开始时间',
        format: 'HH:mm',
      },
      rules: 'required',
    },
    {
      fieldName: 'end_time',
      label: '结束时间',
      component: 'TimePicker',
      componentProps: {
        placeholder: '请选择结束时间',
        format: 'HH:mm',
      },
      rules: 'required',
    },
    {
      fieldName: 'status',
      label: '状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择状态',
        options: [
          { label: '待使用', value: '待使用' },
          { label: '已使用', value: '已使用' },
          { label: '已取消', value: '已取消' },
          { label: '已过期', value: '已过期' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'actual_charge_time',
      label: '实际充电时长(分钟)',
      labelWidth: '2000px',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入实际充电时长',
        min: 0,
        precision: 0,
      },
    },
    {
      fieldName: 'charge_amount',
      label: '充电度数',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入充电度数',
        min: 0,
        precision: 1,
        step: 0.1,
      },
    },
    {
      fieldName: 'charge_fee',
      label: '充电费用',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入充电费用',
        min: 0,
        precision: 2,
      },
    },
    {
      fieldName: 'create_time',
      label: '创建时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择创建时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'update_time',
      label: '更新时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择更新时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Input',
      componentProps: {
        placeholder: '请输入备注',
        type: 'textarea',
        rows: 3,
      },
    },
  ];
}

/** 表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'charge_pile_id',
      title: '充电桩ID',
      minWidth: 140,
      sortable: true,
      slots: { default: 'chargePileId' }, // 添加插槽用于自定义渲染
    },
    {
      field: 'reservation_no',
      title: '预约编号',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'user_id',
      title: '用户ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'car_number',
      title: '车牌号码',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'reserve_date',
      title: '预约日期',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'start_time',
      title: '开始时间',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'end_time',
      title: '结束时间',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'status',
      title: '状态',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'actual_charge_time',
      title: '充电时长(分钟)',
      minWidth: 130,
      sortable: true,
      formatter: ({ cellValue }) => (cellValue ? `${cellValue}分钟` : '-'),
    },
    {
      field: 'charge_amount',
      title: '充电度数',
      minWidth: 100,
      sortable: true,
      formatter: ({ cellValue }) => (cellValue ? `${cellValue}度` : '-'),
    },
    {
      field: 'charge_fee',
      title: '充电费用',
      minWidth: 100,
      sortable: true,
      formatter: ({ cellValue }) => (cellValue ? `¥${cellValue}` : '-'),
    },
    {
      field: 'create_time',
      title: '创建时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'update_time',
      title: '更新时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'remark',
      title: '备注',
      minWidth: 200,
      showOverflow: true,
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑充电预约',
  addText: '新增充电预约',
  excelName: '充电预约列表',
  excelAllName: '充电预约数据.xlsx',
  total: '预约记录数量: 10; 待使用: 3; 已使用: 3; 已取消: 2; 已过期: 1',
};
