/** 表格初始数据 - 窨井盖设施监测自定义报表数据 */
export const dataList = () => [
  {
    id: 1,
    dimensionName: '区域',
    dimensionValue: '福州市鼓楼区',
    coreIndex1: 1500,
    coreIndex2: 120,
    coreIndex3: 108,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '鼓楼区窨井盖设施半年统计',
    indexComparisonDifference: -15,
    indexComparisonChangeRate: -10.71,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已生成',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
  {
    id: 2,
    dimensionName: '责任单位',
    dimensionValue: '福州市鼓楼区市政管理处',
    coreIndex1: 1500,
    coreIndex2: 120,
    coreIndex3: 108,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '鼓楼区市政管理处半年统计',
    indexComparisonDifference: -12,
    indexComparisonChangeRate: -8.57,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已生成',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
  {
    id: 3,
    dimensionName: '井盖类型',
    dimensionValue: '雨水井盖',
    coreIndex1: 800,
    coreIndex2: 85,
    coreIndex3: 78,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '雨水井盖半年统计',
    indexComparisonDifference: 5,
    indexComparisonChangeRate: 6.25,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已导出',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
  {
    id: 4,
    dimensionName: '隐患等级',
    dimensionValue: '一般隐患',
    coreIndex1: 1500,
    coreIndex2: 95,
    coreIndex3: 88,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '一般隐患半年统计',
    indexComparisonDifference: -8,
    indexComparisonChangeRate: -7.77,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已生成',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
  {
    id: 5,
    dimensionName: '区域',
    dimensionValue: '厦门市思明区',
    coreIndex1: 2000,
    coreIndex2: 60,
    coreIndex3: 60,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '思明区窨井盖设施半年统计',
    indexComparisonDifference: -20,
    indexComparisonChangeRate: -25,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已保存',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
  {
    id: 6,
    dimensionName: '区域',
    dimensionValue: '泉州市丰泽区',
    coreIndex1: 1800,
    coreIndex2: 180,
    coreIndex3: 130,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '丰泽区窨井盖设施半年统计',
    indexComparisonDifference: 35,
    indexComparisonChangeRate: 24.31,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已生成',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
  {
    id: 7,
    dimensionName: '责任单位',
    dimensionValue: '厦门市思明区市政管理处',
    coreIndex1: 2000,
    coreIndex2: 60,
    coreIndex3: 60,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '思明区市政管理处半年统计',
    indexComparisonDifference: -18,
    indexComparisonChangeRate: -23.08,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已导出',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
  {
    id: 8,
    dimensionName: '井盖类型',
    dimensionValue: '污水井盖',
    coreIndex1: 700,
    coreIndex2: 35,
    coreIndex3: 32,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '污水井盖半年统计',
    indexComparisonDifference: -5,
    indexComparisonChangeRate: -12.5,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已生成',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
  {
    id: 9,
    dimensionName: '隐患等级',
    dimensionValue: '较大隐患',
    coreIndex1: 1500,
    coreIndex2: 20,
    coreIndex3: 18,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '较大隐患半年统计',
    indexComparisonDifference: 2,
    indexComparisonChangeRate: 11.11,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已保存',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
  {
    id: 10,
    dimensionName: '隐患等级',
    dimensionValue: '重大隐患',
    coreIndex1: 1500,
    coreIndex2: 5,
    coreIndex3: 5,
    statisticsTimeRange: '2024-01-01 ~ 2024-06-30',
    reportName: '重大隐患半年统计',
    indexComparisonDifference: 0,
    indexComparisonChangeRate: 0,
    reportGenerateTime: '2024-07-01 00:00:00',
    reportStatus: '已生成',
    dataUpdateTime: '2024-07-01 00:00:00',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施监测自定义报表表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'reportName',
      label: '报表名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入报表名称',
        maxlength: 100,
      },
      labelWidth: '120',
      rules: 'required', // 报表名称为必填项
    },
    {
      fieldName: 'statisticsTimeRange',
      label: '统计时间范围',
      component: 'Input',
      componentProps: {
        placeholder: '请输入统计时间范围（如：2024-01-01 ~ 2024-06-30）',
        maxlength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 统计时间范围为必填项
    },
    {
      fieldName: 'dimensionName',
      label: '统计维度',
      component: 'Select',
      componentProps: {
        placeholder: '请选择统计维度',
        options: [
          { label: '区域', value: '区域' },
          { label: '责任单位', value: '责任单位' },
          { label: '井盖类型', value: '井盖类型' },
          { label: '隐患等级', value: '隐患等级' },
        ],
      },
      labelWidth: '120',
      rules: 'required', // 统计维度为必填项
    },
    {
      fieldName: 'dimensionValue',
      label: '统计维度值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入统计维度值',
        maxlength: 100,
      },
      labelWidth: '120',
      rules: 'required', // 统计维度值为必填项
    },
    {
      fieldName: 'coreIndex1',
      label: '核心指标1',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入核心指标1（如：井盖总数）',
        min: 0,
        precision: 0,
      },
      rules: 'required', // 核心指标1为必填项
    },
    {
      fieldName: 'coreIndex2',
      label: '核心指标2',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入核心指标2（如：隐患数）',
        min: 0,
        precision: 0,
      },
      rules: 'required', // 核心指标2为必填项
    },
    {
      fieldName: 'coreIndex3',
      label: '核心指标3',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入核心指标3（如：处置数）',
        min: 0,
        precision: 0,
      },
      rules: 'required', // 核心指标3为必填项
    },
    {
      fieldName: 'indexComparisonDifference',
      label: '指标对比差值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入指标对比差值',
        precision: 2,
      },
    },
    {
      fieldName: 'indexComparisonChangeRate',
      label: '指标对比变化率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入指标对比变化率（单位：%）',
        precision: 2,
        addonAfter: '%',
      },
    },
  ];
}

/** 表格字段 - 窨井盖设施监测自定义报表表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'dimensionName',
      title: '统计维度名称',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'dimensionValue',
      title: '统计维度值',
      minWidth: 180,
      sortable: true,
      slots: { default: 'dimensionValue' },
    },
    {
      field: 'coreIndex1',
      title: '核心指标1统计值',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'coreIndex2',
      title: '核心指标2统计值',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'coreIndex3',
      title: '核心指标3统计值',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'statisticsTimeRange',
      title: '统计时段',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'reportName',
      title: '报表名称',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'indexComparisonDifference',
      title: '指标对比差值',
      minWidth: 120,
      sortable: true,
      slots: { default: 'indexComparisonDifference' },
    },
    {
      field: 'indexComparisonChangeRate',
      title: '指标对比变化率(%)',
      minWidth: 140,
      sortable: true,
      slots: { default: 'indexComparisonChangeRate' },
    },
    {
      field: 'reportGenerateTime',
      title: '报表生成时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'reportStatus',
      title: '报表状态',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'dataUpdateTime',
      title: '数据更新时间',
      minWidth: 180,
      sortable: true,
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
