/** 表格初始数据 - 改造为停车管理多维度综合分析数据 */
export const dataList = () => [
  {
    timeRange: '2025年第一季度',
    areaName: '鼓楼区',
    parkingLotName: '鼓楼公共停车场',
    berthType: '路内泊位',
    vehicleType: '小型客车',
    controlTimeSlot: '早高峰',
    complaintType: '违停投诉',
    complaintCount: 156,
    parkingCount: 12450,
    avgUsageRate: 78.5,
    avgTurnoverRate: 3.2,
    momChangeRate_ComplaintCount: -5.2,
    momChangeRate_ParkingCount: 2.3,
    momChangeRate_AvgUsageRate: 1.5,
    momChangeRate_AvgTurnoverRate: -0.3,
    yoyChangeRate_ComplaintCount: -8.7,
    yoyChangeRate_ParkingCount: 4.8,
    yoyChangeRate_AvgUsageRate: 3.2,
    yoyChangeRate_AvgTurnoverRate: 0.5,
    detailByRegion: '鼓楼区: 156件；台江区: 98件；仓山区: 112件',
    detailByParkingLot: '鼓楼公共停车场: 78.5%；五一广场停车场: 82.1%；东街口停车场: 91.5%',
    detailByBerthType: '路内泊位: 3.5次/天；路外泊位: 2.8次/天；专用泊位: 2.1次/天',
    detailByVehicleType: '小型客车: 68%；大型客车: 12%；货车: 15%；新能源车: 5%',
    detailByControlTimeSlot: '早高峰: 156件；午间: 98件；晚高峰: 132件；夜间: 87件',
    detailByComplaintType: '违停投诉: 156件；收费投诉: 43件；设施投诉: 28件；服务投诉: 19件',
    detailByAnalysis: '同比: 投诉量下降8.7%，停车量增长4.8%；环比: 投诉量下降5.2%，停车量增长2.3%',
  },
  {
    timeRange: '2025年第一季度',
    areaName: '台江区',
    parkingLotName: '中亭街停车场',
    berthType: '路外泊位',
    vehicleType: '小型客车',
    controlTimeSlot: '午间',
    complaintType: '收费投诉',
    complaintCount: 98,
    parkingCount: 11280,
    avgUsageRate: 74.2,
    avgTurnoverRate: 3.5,
    momChangeRate_ComplaintCount: -3.8,
    momChangeRate_ParkingCount: 1.9,
    momChangeRate_AvgUsageRate: 0.8,
    momChangeRate_AvgTurnoverRate: 0.6,
    yoyChangeRate_ComplaintCount: -6.2,
    yoyChangeRate_ParkingCount: 3.7,
    yoyChangeRate_AvgUsageRate: 2.5,
    yoyChangeRate_AvgTurnoverRate: 1.2,
    detailByRegion: '台江区: 98件；仓山区: 112件；晋安区: 76件',
    detailByParkingLot: '中亭街停车场: 71.3%；万象城停车场: 68.9%；茶亭停车场: 77.5%',
    detailByBerthType: '路内泊位: 3.8次/天；路外泊位: 3.0次/天；专用泊位: 2.4次/天',
    detailByVehicleType: '小型客车: 72%；大型客车: 8%；货车: 12%；新能源车: 8%',
    detailByControlTimeSlot: '早高峰: 65件；午间: 98件；晚高峰: 82件；夜间: 43件',
    detailByComplaintType: '违停投诉: 58件；收费投诉: 98件；设施投诉: 32件；服务投诉: 21件',
    detailByAnalysis: '同比: 投诉量下降6.2%，停车量增长3.7%；环比: 收费投诉下降3.8%',
  },
  {
    timeRange: '2025年第一季度',
    areaName: '仓山区',
    parkingLotName: '金山停车场',
    berthType: '专用泊位',
    vehicleType: '新能源车',
    controlTimeSlot: '晚高峰',
    complaintType: '设施投诉',
    complaintCount: 112,
    parkingCount: 11890,
    avgUsageRate: 72.8,
    avgTurnoverRate: 3.1,
    momChangeRate_ComplaintCount: 2.5,
    momChangeRate_ParkingCount: 3.2,
    momChangeRate_AvgUsageRate: 1.2,
    momChangeRate_AvgTurnoverRate: -0.2,
    yoyChangeRate_ComplaintCount: -4.5,
    yoyChangeRate_ParkingCount: 5.1,
    yoyChangeRate_AvgUsageRate: 3.8,
    yoyChangeRate_AvgTurnoverRate: 0.5,
    detailByRegion: '仓山区: 112件；晋安区: 76件；马尾区: 45件',
    detailByParkingLot: '金山停车场: 69.4%；奥体中心停车场: 73.2%；仓山万达停车场: 81.7%',
    detailByBerthType: '路内泊位: 3.3次/天；路外泊位: 2.7次/天；专用泊位: 2.2次/天',
    detailByVehicleType: '小型客车: 58%；大型客车: 10%；货车: 18%；新能源车: 14%',
    detailByControlTimeSlot: '早高峰: 76件；午间: 54件；晚高峰: 112件；夜间: 68件',
    detailByComplaintType: '违停投诉: 45件；收费投诉: 32件；设施投诉: 112件；服务投诉: 28件',
    detailByAnalysis: '同比: 设施投诉下降4.5%，停车量增长5.1%；环比: 投诉量上升2.5%',
  },
  {
    timeRange: '2025年第一季度',
    areaName: '晋安区',
    parkingLotName: '东二环停车场',
    berthType: '路内泊位',
    vehicleType: '货车',
    controlTimeSlot: '夜间',
    complaintType: '服务投诉',
    complaintCount: 76,
    parkingCount: 9870,
    avgUsageRate: 70.5,
    avgTurnoverRate: 2.9,
    momChangeRate_ComplaintCount: -1.2,
    momChangeRate_ParkingCount: 2.8,
    momChangeRate_AvgUsageRate: 0.5,
    momChangeRate_AvgTurnoverRate: -0.5,
    yoyChangeRate_ComplaintCount: -3.9,
    yoyChangeRate_ParkingCount: 4.6,
    yoyChangeRate_AvgUsageRate: 2.8,
    yoyChangeRate_AvgTurnoverRate: 0.3,
    detailByRegion: '晋安区: 76件；马尾区: 45件；长乐区: 32件',
    detailByParkingLot: '东二环停车场: 66.8%；鼓山停车场: 70.1%；火车站停车场: 79.4%',
    detailByBerthType: '路内泊位: 3.1次/天；路外泊位: 2.5次/天；专用泊位: 2.0次/天',
    detailByVehicleType: '小型客车: 45%；大型客车: 15%；货车: 32%；新能源车: 8%',
    detailByControlTimeSlot: '早高峰: 32件；午间: 28件；晚高峰: 45件；夜间: 76件',
    detailByComplaintType: '违停投诉: 28件；收费投诉: 15件；设施投诉: 12件；服务投诉: 76件',
    detailByAnalysis: '同比: 服务投诉下降3.9%；环比: 投诉量下降1.2%，夜间管控需加强',
  },
  {
    timeRange: '2025年第一季度',
    areaName: '马尾区',
    parkingLotName: '马尾造船厂停车场',
    berthType: '路外泊位',
    vehicleType: '大型客车',
    controlTimeSlot: '早高峰',
    complaintType: '违停投诉',
    complaintCount: 45,
    parkingCount: 6540,
    avgUsageRate: 68.3,
    avgTurnoverRate: 2.7,
    momChangeRate_ComplaintCount: 7.5,
    momChangeRate_ParkingCount: 4.2,
    momChangeRate_AvgUsageRate: 1.8,
    momChangeRate_AvgTurnoverRate: 1.1,
    yoyChangeRate_ComplaintCount: -2.1,
    yoyChangeRate_ParkingCount: 6.3,
    yoyChangeRate_AvgUsageRate: 4.5,
    yoyChangeRate_AvgTurnoverRate: 1.9,
    detailByRegion: '马尾区: 45件；长乐区: 32件；福清市: 28件',
    detailByParkingLot: '马尾造船厂停车场: 63.5%；自贸区停车场: 66.2%；江滨停车场: 72.8%',
    detailByBerthType: '路内泊位: 2.9次/天；路外泊位: 2.3次/天；专用泊位: 1.9次/天',
    detailByVehicleType: '小型客车: 38%；大型客车: 42%；货车: 15%；新能源车: 5%',
    detailByControlTimeSlot: '早高峰: 45件；午间: 28件；晚高峰: 32件；夜间: 18件',
    detailByComplaintType: '违停投诉: 45件；收费投诉: 12件；设施投诉: 8件；服务投诉: 5件',
    detailByAnalysis: '同比: 违停投诉下降2.1%；环比: 投诉量上升7.5%，早高峰违停问题突出',
  },
  {
    timeRange: '2025年第一季度',
    areaName: '长乐区',
    parkingLotName: '长乐机场停车场',
    berthType: '专用泊位',
    vehicleType: '小型客车',
    controlTimeSlot: '午间',
    complaintType: '收费投诉',
    complaintCount: 32,
    parkingCount: 4320,
    avgUsageRate: 65.7,
    avgTurnoverRate: 2.5,
    momChangeRate_ComplaintCount: 4.9,
    momChangeRate_ParkingCount: 3.5,
    momChangeRate_AvgUsageRate: 1.2,
    momChangeRate_AvgTurnoverRate: 0.8,
    yoyChangeRate_ComplaintCount: -1.5,
    yoyChangeRate_ParkingCount: 5.8,
    yoyChangeRate_AvgUsageRate: 3.9,
    yoyChangeRate_AvgTurnoverRate: 1.5,
    detailByRegion: '长乐区: 32件；福清市: 28件；连江县: 25件',
    detailByParkingLot: '长乐机场停车场: 70.2%；滨海新城停车场: 64.8%；首占停车场: 61.3%',
    detailByBerthType: '路内泊位: 2.7次/天；路外泊位: 2.1次/天；专用泊位: 1.8次/天',
    detailByVehicleType: '小型客车: 82%；大型客车: 12%；货车: 3%；新能源车: 3%',
    detailByControlTimeSlot: '早高峰: 18件；午间: 32件；晚高峰: 24件；夜间: 12件',
    detailByComplaintType: '违停投诉: 8件；收费投诉: 32件；设施投诉: 6件；服务投诉: 4件',
    detailByAnalysis: '同比: 收费投诉下降1.5%；环比: 投诉量上升4.9%，午间收费问题需关注',
  },
  {
    timeRange: '2025年第一季度',
    areaName: '福清市',
    parkingLotName: '福清万达停车场',
    berthType: '路内泊位',
    vehicleType: '新能源车',
    controlTimeSlot: '晚高峰',
    complaintType: '设施投诉',
    complaintCount: 28,
    parkingCount: 3850,
    avgUsageRate: 63.2,
    avgTurnoverRate: 2.3,
    momChangeRate_ComplaintCount: -2.4,
    momChangeRate_ParkingCount: 1.9,
    momChangeRate_AvgUsageRate: 0.6,
    momChangeRate_AvgTurnoverRate: -0.4,
    yoyChangeRate_ComplaintCount: -0.8,
    yoyChangeRate_ParkingCount: 4.7,
    yoyChangeRate_AvgUsageRate: 3.2,
    yoyChangeRate_AvgTurnoverRate: 1.1,
    detailByRegion: '福清市: 28件；连江县: 25件；罗源县: 18件',
    detailByParkingLot: '福清万达停车场: 65.4%；龙田停车场: 60.8%；宏路停车场: 58.3%',
    detailByBerthType: '路内泊位: 2.5次/天；路外泊位: 2.0次/天；专用泊位: 1.7次/天',
    detailByVehicleType: '小型客车: 48%；大型客车: 8%；货车: 22%；新能源车: 22%',
    detailByControlTimeSlot: '早高峰: 15件；午间: 12件；晚高峰: 28件；夜间: 16件',
    detailByComplaintType: '违停投诉: 8件；收费投诉: 6件；设施投诉: 28件；服务投诉: 4件',
    detailByAnalysis: '同比: 设施投诉下降0.8%；环比: 投诉量下降2.4%，设施状况改善',
  },
  {
    timeRange: '2025年第一季度',
    areaName: '连江县',
    parkingLotName: '连江动车站停车场',
    berthType: '路外泊位',
    vehicleType: '货车',
    controlTimeSlot: '夜间',
    complaintType: '违停投诉',
    complaintCount: 25,
    parkingCount: 2980,
    avgUsageRate: 61.5,
    avgTurnoverRate: 2.1,
    momChangeRate_ComplaintCount: 6.2,
    momChangeRate_ParkingCount: 3.8,
    momChangeRate_AvgUsageRate: 1.5,
    momChangeRate_AvgTurnoverRate: 0.9,
    yoyChangeRate_ComplaintCount: 1.2,
    yoyChangeRate_ParkingCount: 5.2,
    yoyChangeRate_AvgUsageRate: 4.1,
    yoyChangeRate_AvgTurnoverRate: 1.8,
    detailByRegion: '连江县: 25件；罗源县: 18件；闽侯县: 22件',
    detailByParkingLot: '连江动车站停车场: 59.7%；贵安停车场: 62.4%；黄岐停车场: 56.8%',
    detailByBerthType: '路内泊位: 2.3次/天；路外泊位: 1.9次/天；专用泊位: 1.6次/天',
    detailByVehicleType: '小型客车: 35%；大型客车: 18%；货车: 42%；新能源车: 5%',
    detailByControlTimeSlot: '早高峰: 12件；午间: 8件；晚高峰: 15件；夜间: 25件',
    detailByComplaintType: '违停投诉: 25件；收费投诉: 8件；设施投诉: 5件；服务投诉: 3件',
    detailByAnalysis: '同比: 违停投诉上升1.2%；环比: 投诉量上升6.2%，夜间货车违停问题需整治',
  },
  {
    timeRange: '2025年第一季度',
    areaName: '罗源县',
    parkingLotName: '罗源湾停车场',
    berthType: '专用泊位',
    vehicleType: '小型客车',
    controlTimeSlot: '早高峰',
    complaintType: '服务投诉',
    complaintCount: 18,
    parkingCount: 2150,
    avgUsageRate: 58.9,
    avgTurnoverRate: 1.9,
    momChangeRate_ComplaintCount: 3.7,
    momChangeRate_ParkingCount: 2.5,
    momChangeRate_AvgUsageRate: 0.9,
    momChangeRate_AvgTurnoverRate: 0.3,
    yoyChangeRate_ComplaintCount: -0.5,
    yoyChangeRate_ParkingCount: 4.1,
    yoyChangeRate_AvgUsageRate: 3.3,
    yoyChangeRate_AvgTurnoverRate: 1.2,
    detailByRegion: '罗源县: 18件；永泰县: 15件；闽清县: 12件',
    detailByParkingLot: '罗源湾停车场: 58.2%；滨海停车场: 56.5%；中心停车场: 60.1%',
    detailByBerthType: '路内泊位: 2.1次/天；路外泊位: 1.7次/天；专用泊位: 1.5次/天',
    detailByVehicleType: '小型客车: 68%；大型客车: 12%；货车: 15%；新能源车: 5%',
    detailByControlTimeSlot: '早高峰: 18件；午间: 12件；晚高峰: 15件；夜间: 8件',
    detailByComplaintType: '违停投诉: 5件；收费投诉: 4件；设施投诉: 3件；服务投诉: 18件',
    detailByAnalysis: '同比: 服务投诉下降0.5%；环比: 投诉量上升3.7%，早高峰服务质量需提升',
  },
  {
    timeRange: '2025年第一季度',
    areaName: '闽侯县',
    parkingLotName: '大学城停车场',
    berthType: '路内泊位',
    vehicleType: '新能源车',
    controlTimeSlot: '晚高峰',
    complaintType: '收费投诉',
    complaintCount: 22,
    parkingCount: 1650,
    avgUsageRate: 56.2,
    avgTurnoverRate: 1.8,
    momChangeRate_ComplaintCount: 2.8,
    momChangeRate_ParkingCount: 2.1,
    momChangeRate_AvgUsageRate: 0.7,
    momChangeRate_AvgTurnoverRate: 0.2,
    yoyChangeRate_ComplaintCount: 0.3,
    yoyChangeRate_ParkingCount: 3.8,
    yoyChangeRate_AvgUsageRate: 2.9,
    yoyChangeRate_AvgTurnoverRate: 1.0,
    detailByRegion: '闽侯县: 22件；永泰县: 15件；闽清县: 12件',
    detailByParkingLot: '大学城停车场: 60.2%；上街停车场: 57.5%；甘蔗停车场: 55.1%',
    detailByBerthType: '路内泊位: 2.0次/天；路外泊位: 1.6次/天；专用泊位: 1.4次/天',
    detailByVehicleType: '小型客车: 52%；大型客车: 8%；货车: 20%；新能源车: 20%',
    detailByControlTimeSlot: '早高峰: 14件；午间: 10件；晚高峰: 22件；夜间: 12件',
    detailByComplaintType: '违停投诉: 6件；收费投诉: 22件；设施投诉: 4件；服务投诉: 2件',
    detailByAnalysis: '同比: 收费投诉微增0.3%；环比: 投诉量上升2.8%，晚高峰收费问题需关注',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为停车管理多维度综合分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'timeRange',
      label: '时间范围',
      component: 'Input',
      componentProps: {
        placeholder: '请输入时间范围（如：2025年第一季度）',
      },
      labelWidth: '150',
      rules: 'required',
    },
    {
      fieldName: 'areaName',
      label: '区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '150',
      rules: 'required',
    },
    {
      fieldName: 'parkingLotName',
      label: '停车场',
      component: 'Input',
      componentProps: {
        placeholder: '请输入停车场名称',
      },
      labelWidth: '150',
      rules: 'required',
    },
    {
      fieldName: 'berthType',
      label: '泊位类型',
      component: 'Input',
      componentProps: {
        placeholder: '请输入泊位类型（路内泊位/路外泊位/专用泊位）',
      },
      labelWidth: '150',
      rules: 'required',
    },
    {
      fieldName: 'vehicleType',
      label: '车辆类型',
      component: 'Input',
      componentProps: {
        placeholder: '请输入车辆类型（小型客车/大型客车/货车/新能源车）',
      },
      labelWidth: '150',
      rules: 'required',
    },
    {
      fieldName: 'controlTimeSlot',
      label: '管控时段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管控时段（早高峰/午间/晚高峰/夜间）',
      },
      labelWidth: '150',
      rules: 'required',
    },
    {
      fieldName: 'complaintType',
      label: '投诉类型',
      component: 'Input',
      componentProps: {
        placeholder: '请输入投诉类型（违停投诉/收费投诉/设施投诉/服务投诉）',
      },
      labelWidth: '150',
      rules: 'required',
    },
    {
      fieldName: 'complaintCount',
      label: '投诉数量',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入投诉数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'parkingCount',
      label: '停车数量',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入停车数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'avgUsageRate',
      label: '平均使用率(%)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入平均使用率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'avgTurnoverRate',
      label: '平均周转率(次/天)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入平均周转率',
        min: 0,
        precision: 1,
        addonAfter: '次/天',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_ComplaintCount',
      label: '投诉数量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_ParkingCount',
      label: '停车数量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_AvgUsageRate',
      label: '平均使用率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_AvgTurnoverRate',
      label: '平均周转率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_ComplaintCount',
      label: '投诉数量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_ParkingCount',
      label: '停车数量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_AvgUsageRate',
      label: '平均使用率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_AvgTurnoverRate',
      label: '平均周转率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRegion',
      label: '按区域拆分明细',
      component: 'Input',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入按区域拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByParkingLot',
      label: '按停车场拆分明细',
      component: 'Input',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入按停车场拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByBerthType',
      label: '按泊位类型拆分明细',
      component: 'Input',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入按泊位类型拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByVehicleType',
      label: '按车辆类型拆分明细',
      component: 'Input',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入按车辆类型拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByControlTimeSlot',
      label: '按管控时段拆分明细',
      component: 'Input',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入按管控时段拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByComplaintType',
      label: '按投诉类型拆分明细',
      component: 'Input',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入按投诉类型拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByAnalysis',
      label: '同比/环比分析结果',
      component: 'Input',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入同比/环比分析结果',
        maxlength: 400,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为停车管理多维度综合分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'timeRange',
      title: '时间范围',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'areaName',
      title: '区域',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'parkingLotName',
      title: '停车场',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'berthType',
      title: '泊位类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'vehicleType',
      title: '车辆类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'controlTimeSlot',
      title: '管控时段',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'complaintType',
      title: '投诉类型',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'complaintCount',
      title: '投诉数量',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'parkingCount',
      title: '停车数量',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'avgUsageRate',
      title: '平均使用率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'avgTurnoverRate',
      title: '平均周转率(次/天)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_ComplaintCount',
      title: '投诉数量环比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'momChangeRate_ParkingCount',
      title: '停车数量环比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'momChangeRate_AvgUsageRate',
      title: '使用率环比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'momChangeRate_AvgTurnoverRate',
      title: '周转率环比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_ComplaintCount',
      title: '投诉数量同比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_ParkingCount',
      title: '停车数量同比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_AvgUsageRate',
      title: '使用率同比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_AvgTurnoverRate',
      title: '周转率同比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'detailByRegion',
      title: '按区域拆分明细',
      minWidth: 260,
      sortable: false,
    },
    {
      field: 'detailByParkingLot',
      title: '按停车场拆分明细',
      minWidth: 280,
      sortable: false,
    },
    {
      field: 'detailByBerthType',
      title: '按泊位类型拆分明细',
      minWidth: 260,
      sortable: false,
    },
    {
      field: 'detailByVehicleType',
      title: '按车辆类型拆分明细',
      minWidth: 260,
      sortable: false,
    },
    {
      field: 'detailByControlTimeSlot',
      title: '按管控时段拆分明细',
      minWidth: 260,
      sortable: false,
    },
    {
      field: 'detailByComplaintType',
      title: '按投诉类型拆分明细',
      minWidth: 260,
      sortable: false,
    },
    {
      field: 'detailByAnalysis',
      title: '同比/环比分析结果',
      minWidth: 320,
      sortable: false,
    },
  ];
}
