/** 表格初始数据 - 改造为道路监测统计分析数据 */
export const dataList = () => [
  {
    roadSectionName: '全省道路监测总计（2024-01-01）',
    potholeCountAvg: 8.2,
    crackLengthAvg: 12.5,
    roadSurfaceTempRange: '8.5~15.8℃',
    trafficFlowPeak: 1950,
    trafficFlowValley: 450,
    warningTriggerCount: 48,
    workOrderCreateCount: 48,
    disposalCompleteCount: 42,
    verificationPassRate: 87.5,
    deviceOnlineRate: 92.8,
    potholeCountMomChangeRate: 6.8,
    crackLengthMomChangeRate: 4.2,
    avgDisposalDuration: 24.5,
    normalMonitorRoadCount: 128,
    indexOverStandardDistribution:
      '坑洼数量: 22次；裂缝长度: 18次；温度: 0次；流量: 8次',
    dataStatisticsPeriod: '2024-01-01',
  },
  {
    roadSectionName: '全省道路监测总计（2024-01-02）',
    potholeCountAvg: 7.8,
    crackLengthAvg: 11.8,
    roadSurfaceTempRange: '10.2~18.5℃',
    trafficFlowPeak: 2050,
    trafficFlowValley: 480,
    warningTriggerCount: 45,
    workOrderCreateCount: 45,
    disposalCompleteCount: 39,
    verificationPassRate: 86.7,
    deviceOnlineRate: 93.5,
    potholeCountMomChangeRate: -4.9,
    crackLengthMomChangeRate: -5.6,
    avgDisposalDuration: 23.8,
    normalMonitorRoadCount: 130,
    indexOverStandardDistribution:
      '坑洼数量: 20次；裂缝长度: 16次；温度: 0次；流量: 9次',
    dataStatisticsPeriod: '2024-02-01',
  },
  {
    roadSectionName: '全省道路监测总计（2024-01-03）',
    potholeCountAvg: 7.1,
    crackLengthAvg: 10.5,
    roadSurfaceTempRange: '12.8~22.5℃',
    trafficFlowPeak: 2100,
    trafficFlowValley: 520,
    warningTriggerCount: 41,
    workOrderCreateCount: 41,
    disposalCompleteCount: 37,
    verificationPassRate: 90.2,
    deviceOnlineRate: 94.1,
    potholeCountMomChangeRate: -8.9,
    crackLengthMomChangeRate: -11,
    avgDisposalDuration: 22.6,
    normalMonitorRoadCount: 131,
    indexOverStandardDistribution:
      '坑洼数量: 18次；裂缝长度: 14次；温度: 0次；流量: 9次',
    dataStatisticsPeriod: '2024-03-01',
  },
  {
    roadSectionName: '全省道路监测总计（2024-01-04）',
    potholeCountAvg: 6.5,
    crackLengthAvg: 9.8,
    roadSurfaceTempRange: '16.5~25.8℃',
    trafficFlowPeak: 2150,
    trafficFlowValley: 580,
    warningTriggerCount: 38,
    workOrderCreateCount: 38,
    disposalCompleteCount: 35,
    verificationPassRate: 92.1,
    deviceOnlineRate: 94.8,
    potholeCountMomChangeRate: -8.4,
    crackLengthMomChangeRate: -6.7,
    avgDisposalDuration: 21.9,
    normalMonitorRoadCount: 132,
    indexOverStandardDistribution:
      '坑洼数量: 16次；裂缝长度: 13次；温度: 1次；流量: 8次',
    dataStatisticsPeriod: '2024-04-01',
  },
  {
    roadSectionName: '全省道路监测总计（2024-01-05）',
    potholeCountAvg: 5.9,
    crackLengthAvg: 9.2,
    roadSurfaceTempRange: '20.3~28.9℃',
    trafficFlowPeak: 2180,
    trafficFlowValley: 600,
    warningTriggerCount: 36,
    workOrderCreateCount: 36,
    disposalCompleteCount: 32,
    verificationPassRate: 88.9,
    deviceOnlineRate: 95.2,
    potholeCountMomChangeRate: -9.2,
    crackLengthMomChangeRate: -6.1,
    avgDisposalDuration: 21.5,
    normalMonitorRoadCount: 132,
    indexOverStandardDistribution:
      '坑洼数量: 15次；裂缝长度: 12次；温度: 2次；流量: 7次',
    dataStatisticsPeriod: '2024-05-01',
  },
  {
    roadSectionName: '全省道路监测总计（2024-01-06）',
    potholeCountAvg: 5.5,
    crackLengthAvg: 9,
    roadSurfaceTempRange: '23.5~33.8℃',
    trafficFlowPeak: 2200,
    trafficFlowValley: 320,
    warningTriggerCount: 34,
    workOrderCreateCount: 34,
    disposalCompleteCount: 29,
    verificationPassRate: 91.4,
    deviceOnlineRate: 94.2,
    potholeCountMomChangeRate: 7.3,
    crackLengthMomChangeRate: 5.7,
    avgDisposalDuration: 21.1,
    normalMonitorRoadCount: 133,
    indexOverStandardDistribution:
      '坑洼数量: 14次；裂缝长度: 11次；温度: 4次；流量: 4次',
    dataStatisticsPeriod: '2024-06-01',
  },
  {
    roadSectionName: '全省道路监测总计（2024-01-07）',
    potholeCountAvg: 5.2,
    crackLengthAvg: 8.8,
    roadSurfaceTempRange: '26.8~36.5℃',
    trafficFlowPeak: 2190,
    trafficFlowValley: 350,
    warningTriggerCount: 32,
    workOrderCreateCount: 32,
    disposalCompleteCount: 28,
    verificationPassRate: 93.8,
    deviceOnlineRate: 93.5,
    potholeCountMomChangeRate: -5.5,
    crackLengthMomChangeRate: -2.2,
    avgDisposalDuration: 20.8,
    normalMonitorRoadCount: 134,
    indexOverStandardDistribution:
      '坑洼数量: 12次；裂缝长度: 10次；温度: 8次；流量: 2次',
    dataStatisticsPeriod: '2024-07-01',
  },
  {
    roadSectionName: '全省道路监测总计（2024-01-08）',
    potholeCountAvg: 5,
    crackLengthAvg: 8.5,
    roadSurfaceTempRange: '28.5~38.2℃',
    trafficFlowPeak: 2180,
    trafficFlowValley: 380,
    warningTriggerCount: 30,
    workOrderCreateCount: 30,
    disposalCompleteCount: 27,
    verificationPassRate: 95,
    deviceOnlineRate: 92.8,
    potholeCountMomChangeRate: -3.8,
    crackLengthMomChangeRate: -3.4,
    avgDisposalDuration: 20.5,
    normalMonitorRoadCount: 135,
    indexOverStandardDistribution:
      '坑洼数量: 10次；裂缝长度: 9次；温度: 10次；流量: 1次',
    dataStatisticsPeriod: '2024-08-01',
  },
  {
    roadSectionName: '全省道路监测总计（2024-01-09）',
    potholeCountAvg: 5.3,
    crackLengthAvg: 8.7,
    roadSurfaceTempRange: '24.2~32.5℃',
    trafficFlowPeak: 2170,
    trafficFlowValley: 420,
    warningTriggerCount: 31,
    workOrderCreateCount: 31,
    disposalCompleteCount: 28,
    verificationPassRate: 94.6,
    deviceOnlineRate: 94,
    potholeCountMomChangeRate: 6,
    crackLengthMomChangeRate: 2.4,
    avgDisposalDuration: 20.9,
    normalMonitorRoadCount: 135,
    indexOverStandardDistribution:
      '坑洼数量: 11次；裂缝长度: 9次；温度: 6次；流量: 5次',
    dataStatisticsPeriod: '2024-09-01',
  },
  {
    roadSectionName: '全省道路监测总计（2024-01-10）',
    potholeCountAvg: 5.8,
    crackLengthAvg: 9.3,
    roadSurfaceTempRange: '18.5~28.8℃',
    trafficFlowPeak: 2160,
    trafficFlowValley: 450,
    warningTriggerCount: 33,
    workOrderCreateCount: 33,
    disposalCompleteCount: 30,
    verificationPassRate: 92.7,
    deviceOnlineRate: 94.5,
    potholeCountMomChangeRate: 9.4,
    crackLengthMomChangeRate: 6.9,
    avgDisposalDuration: 21.3,
    normalMonitorRoadCount: 134,
    indexOverStandardDistribution:
      '坑洼数量: 13次；裂缝长度: 10次；温度: 2次；流量: 8次',
    dataStatisticsPeriod: '2024-10-01',
  },
];
/** 新增/修改的表单/列表的搜索表单 - 改造为道路监测统计总计表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'roadSectionName',
      label: '统计名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入统计名称（如：全省道路监测总计（2024-06））',
      },
      labelWidth: '120',
      rules: 'required', // 统计名称为必填项
    },
    {
      fieldName: 'potholeCountAvg',
      label: '坑洼数量均值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入坑洼数量均值',
        min: 0,
        precision: 1, // 保留1位小数，贴合统计均值场景
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthAvg',
      label: '裂缝长度均值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入裂缝长度均值（单位：米）',
        min: 0,
        precision: 1,
        addonAfter: '米',
      },
      rules: 'required',
    },
    {
      fieldName: 'roadSurfaceTempRange',
      label: '路面温度极值范围',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入路面温度极值范围（如：23.5~33.8℃）',
        maxlength: 50,
      },
      rules: 'required',
    },
    {
      fieldName: 'trafficFlowPeak',
      label: '交通流量峰值最大值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入交通流量峰值最大值（单位：辆/小时）',
        min: 0,
        precision: 0,
        addonAfter: '辆/小时',
      },
      rules: 'required',
    },
    {
      fieldName: 'trafficFlowValley',
      label: '交通流量谷值最小值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入交通流量谷值最小值（单位：辆/小时）',
        min: 0,
        precision: 0,
        addonAfter: '辆/小时',
      },
      rules: 'required',
    },
    {
      fieldName: 'warningTriggerCount',
      label: '预警触发总次数',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入预警触发总次数',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'workOrderCreateCount',
      label: '工单创建总数',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入工单创建总数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'disposalCompleteCount',
      label: '处置完成总数',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入处置完成总数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'verificationPassRate',
      label: '整体核查通过率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入整体核查通过率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceOnlineRate',
      label: '设备平均在线率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入设备平均在线率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountMomChangeRate',
      label: '坑洼数量月均环比变化率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入坑洼数量月均环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthMomChangeRate',
      label: '裂缝长度月均环比变化率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入裂缝长度月均环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'avgDisposalDuration',
      label: '平均处置时长',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入平均处置时长（单位：小时）',
        min: 0,
        precision: 1,
        addonAfter: '小时',
      },
      rules: 'required',
    },
    {
      fieldName: 'normalMonitorRoadCount',
      label: '正常监测路段总数',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入正常监测路段总数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'indexOverStandardDistribution',
      label: '超标指标总分布',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder:
          '请输入超标指标总分布（如：坑洼数量:14次；裂缝长度:11次；温度:4次；流量:4次）',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'dataStatisticsPeriod',
      label: '数据统计日期',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入数据统计日期（如：2024-06-01）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为道路监测统计总计表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'roadSectionName',
      title: '统计名称',
      minWidth: 280,
      sortable: true,
      slots: { default: 'roadSectionName' },
    },
    {
      field: 'potholeCountAvg',
      title: '坑洼数量均值',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'crackLengthAvg',
      title: '裂缝长度均值(米)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'roadSurfaceTempRange',
      title: '路面温度极值范围',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'trafficFlowPeak',
      title: '交通流量峰值最大值(辆/小时)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'trafficFlowValley',
      title: '交通流量谷值最小值(辆/小时)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'warningTriggerCount',
      title: '预警触发总次数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'workOrderCreateCount',
      title: '工单创建总数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'disposalCompleteCount',
      title: '处置完成总数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'verificationPassRate',
      title: '整体核查通过率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deviceOnlineRate',
      title: '设备平均在线率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'potholeCountMomChangeRate',
      title: '坑洼数量月均环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'crackLengthMomChangeRate',
      title: '裂缝长度月均环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'avgDisposalDuration',
      title: '平均处置时长(小时)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'normalMonitorRoadCount',
      title: '正常监测路段总数',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'indexOverStandardDistribution',
      title: '超标指标总分布',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'dataStatisticsPeriod',
      title: '数据统计日期',
      minWidth: 180,
      sortable: true, // 总计数据按日期排序更实用
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
