/** 表格初始数据 - 改造为停车管理年度统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    yearIllegalParkingDisposal: 12450,
    yearPublicParkingTotal: 45,
    yearBerthTotal: 8560,
    yearSmartParkingCoverage: 94.5,
    yearParkingManagementRank: 1,
    yoyChangeRate_IllegalParkingDisposal: -4.8,
    yoyChangeRate_PublicParkingTotal: 8.5,
    yoyChangeRate_BerthTotal: 12.3,
    yoyChangeRate_SmartParkingCoverage: 5.2,
    yoyChangeRate_ManagementRank: 0,
    detailByRegion: '鼓楼区: 12450件；台江区: 11280件；仓山区: 11890件；晋安区: 9870件',
    detailByYearTrend: '一季度: 3120件；二季度: 2980件；三季度: 3150件；四季度: 3200件；同比增长: -4.8%',
    detailByParkingType: '公共停车场: 28个；配建停车场: 12个；路内停车位: 5个；立体停车场: 3个',
    detailByAssessmentDimension: '设施完善度: 95.2分；管理效率: 93.8分；市民满意度: 92.5分；创新应用: 91.6分；综合排名: 第1名',
    detailByAnalysis: '同比: 处置量下降4.8%，泊位总数增长12.3%，智慧停车覆盖率达94.5%，年度排名保持第1',
  },
  {
    areaName: '台江区',
    yearIllegalParkingDisposal: 11280,
    yearPublicParkingTotal: 38,
    yearBerthTotal: 7230,
    yearSmartParkingCoverage: 92.8,
    yearParkingManagementRank: 3,
    yoyChangeRate_IllegalParkingDisposal: -3.2,
    yoyChangeRate_PublicParkingTotal: 6.8,
    yoyChangeRate_BerthTotal: 9.5,
    yoyChangeRate_SmartParkingCoverage: 4.6,
    yoyChangeRate_ManagementRank: -1,
    detailByRegion: '台江区: 11280件；仓山区: 11890件；晋安区: 9870件；马尾区: 6540件',
    detailByYearTrend: '一季度: 2850件；二季度: 2760件；三季度: 2890件；四季度: 2780件；同比增长: -3.2%',
    detailByParkingType: '公共停车场: 23个；配建停车场: 10个；路内停车位: 4个；立体停车场: 2个',
    detailByAssessmentDimension: '设施完善度: 92.5分；管理效率: 91.8分；市民满意度: 90.7分；创新应用: 90.2分；综合排名: 第3名',
    detailByAnalysis: '同比: 处置量下降3.2%，停车场总数增长6.8%，智慧停车覆盖率达92.8%，排名上升1位',
  },
  {
    areaName: '仓山区',
    yearIllegalParkingDisposal: 11890,
    yearPublicParkingTotal: 42,
    yearBerthTotal: 7980,
    yearSmartParkingCoverage: 93.6,
    yearParkingManagementRank: 2,
    yoyChangeRate_IllegalParkingDisposal: -4.2,
    yoyChangeRate_PublicParkingTotal: 9.2,
    yoyChangeRate_BerthTotal: 14.1,
    yoyChangeRate_SmartParkingCoverage: 5.8,
    yoyChangeRate_ManagementRank: 1,
    detailByRegion: '仓山区: 11890件；晋安区: 9870件；马尾区: 6540件；长乐区: 4320件',
    detailByYearTrend: '一季度: 2980件；二季度: 2890件；三季度: 3020件；四季度: 3000件；同比增长: -4.2%',
    detailByParkingType: '公共停车场: 26个；配建停车场: 11个；路内停车位: 4个；立体停车场: 3个',
    detailByAssessmentDimension: '设施完善度: 94.1分；管理效率: 92.9分；市民满意度: 91.8分；创新应用: 92.3分；综合排名: 第2名',
    detailByAnalysis: '同比: 泊位总数增长14.1%，智慧停车覆盖率达93.6%，排名上升至第2',
  },
  {
    areaName: '晋安区',
    yearIllegalParkingDisposal: 9870,
    yearPublicParkingTotal: 35,
    yearBerthTotal: 6540,
    yearSmartParkingCoverage: 91.2,
    yearParkingManagementRank: 4,
    yoyChangeRate_IllegalParkingDisposal: -2.5,
    yoyChangeRate_PublicParkingTotal: 5.6,
    yoyChangeRate_BerthTotal: 8.7,
    yoyChangeRate_SmartParkingCoverage: 3.9,
    yoyChangeRate_ManagementRank: 0,
    detailByRegion: '晋安区: 9870件；马尾区: 6540件；长乐区: 4320件；福清市: 3850件',
    detailByYearTrend: '一季度: 2510件；二季度: 2430件；三季度: 2560件；四季度: 2370件；同比增长: -2.5%',
    detailByParkingType: '公共停车场: 21个；配建停车场: 9个；路内停车位: 4个；立体停车场: 2个',
    detailByAssessmentDimension: '设施完善度: 90.8分；管理效率: 90.2分；市民满意度: 89.5分；创新应用: 88.9分；综合排名: 第4名',
    detailByAnalysis: '同比: 处置量下降2.5%，停车场建设稳步推进，智慧停车覆盖率提升3.9%',
  },
  {
    areaName: '马尾区',
    yearIllegalParkingDisposal: 6540,
    yearPublicParkingTotal: 28,
    yearBerthTotal: 4320,
    yearSmartParkingCoverage: 88.5,
    yearParkingManagementRank: 6,
    yoyChangeRate_IllegalParkingDisposal: 2.8,
    yoyChangeRate_PublicParkingTotal: 7.3,
    yoyChangeRate_BerthTotal: 10.2,
    yoyChangeRate_SmartParkingCoverage: 4.2,
    yoyChangeRate_ManagementRank: -1,
    detailByRegion: '马尾区: 6540件；长乐区: 4320件；福清市: 3850件；连江县: 2980件',
    detailByYearTrend: '一季度: 1620件；二季度: 1580件；三季度: 1710件；四季度: 1630件；同比增长: 2.8%',
    detailByParkingType: '公共停车场: 17个；配建停车场: 7个；路内停车位: 3个；立体停车场: 2个',
    detailByAssessmentDimension: '设施完善度: 87.6分；管理效率: 86.9分；市民满意度: 86.2分；创新应用: 85.8分；综合排名: 第6名',
    detailByAnalysis: '同比: 处置量上升2.8%，需加强管控；泊位总数增长10.2%，智慧停车覆盖率88.5%',
  },
  {
    areaName: '长乐区',
    yearIllegalParkingDisposal: 4320,
    yearPublicParkingTotal: 23,
    yearBerthTotal: 3210,
    yearSmartParkingCoverage: 86.3,
    yearParkingManagementRank: 8,
    yoyChangeRate_IllegalParkingDisposal: 2.1,
    yoyChangeRate_PublicParkingTotal: 6.5,
    yoyChangeRate_BerthTotal: 8.9,
    yoyChangeRate_SmartParkingCoverage: 3.8,
    yoyChangeRate_ManagementRank: 0,
    detailByRegion: '长乐区: 4320件；福清市: 3850件；连江县: 2980件；罗源县: 2150件',
    detailByYearTrend: '一季度: 1080件；二季度: 1050件；三季度: 1120件；四季度: 1070件；同比增长: 2.1%',
    detailByParkingType: '公共停车场: 14个；配建停车场: 6个；路内停车位: 2个；立体停车场: 2个',
    detailByAssessmentDimension: '设施完善度: 85.8分；管理效率: 85.1分；市民满意度: 84.5分；创新应用: 83.9分；综合排名: 第8名',
    detailByAnalysis: '同比: 停车场建设增长6.5%，智慧停车覆盖率86.3%，排名保持第8',
  },
  {
    areaName: '福清市',
    yearIllegalParkingDisposal: 3850,
    yearPublicParkingTotal: 21,
    yearBerthTotal: 2980,
    yearSmartParkingCoverage: 85.2,
    yearParkingManagementRank: 9,
    yoyChangeRate_IllegalParkingDisposal: 1.5,
    yoyChangeRate_PublicParkingTotal: 5.8,
    yoyChangeRate_BerthTotal: 7.6,
    yoyChangeRate_SmartParkingCoverage: 3.2,
    yoyChangeRate_ManagementRank: -1,
    detailByRegion: '福清市: 3850件；连江县: 2980件；罗源县: 2150件；永泰县: 1680件',
    detailByYearTrend: '一季度: 980件；二季度: 950件；三季度: 1010件；四季度: 910件；同比增长: 1.5%',
    detailByParkingType: '公共停车场: 13个；配建停车场: 5个；路内停车位: 2个；立体停车场: 1个',
    detailByAssessmentDimension: '设施完善度: 84.6分；管理效率: 83.9分；市民满意度: 83.2分；创新应用: 82.5分；综合排名: 第9名',
    detailByAnalysis: '同比: 处置量微增1.5%，泊位新增7.6%，智慧停车平台覆盖率85.2%',
  },
  {
    areaName: '连江县',
    yearIllegalParkingDisposal: 2980,
    yearPublicParkingTotal: 18,
    yearBerthTotal: 2350,
    yearSmartParkingCoverage: 83.6,
    yearParkingManagementRank: 10,
    yoyChangeRate_IllegalParkingDisposal: 0.8,
    yoyChangeRate_PublicParkingTotal: 4.9,
    yoyChangeRate_BerthTotal: 6.8,
    yoyChangeRate_SmartParkingCoverage: 2.9,
    yoyChangeRate_ManagementRank: 0,
    detailByRegion: '连江县: 2980件；罗源县: 2150件；永泰县: 1680件；闽清县: 1250件',
    detailByYearTrend: '一季度: 750件；二季度: 730件；三季度: 780件；四季度: 720件；同比增长: 0.8%',
    detailByParkingType: '公共停车场: 11个；配建停车场: 4个；路内停车位: 2个；立体停车场: 1个',
    detailByAssessmentDimension: '设施完善度: 83.1分；管理效率: 82.5分；市民满意度: 81.8分；创新应用: 81.2分；综合排名: 第10名',
    detailByAnalysis: '同比: 停车场总数增长4.9%，泊位新增6.8%，智慧停车覆盖率达83.6%',
  },
  {
    areaName: '罗源县',
    yearIllegalParkingDisposal: 2150,
    yearPublicParkingTotal: 15,
    yearBerthTotal: 1820,
    yearSmartParkingCoverage: 81.5,
    yearParkingManagementRank: 11,
    yoyChangeRate_IllegalParkingDisposal: 0.3,
    yoyChangeRate_PublicParkingTotal: 4.2,
    yoyChangeRate_BerthTotal: 5.9,
    yoyChangeRate_SmartParkingCoverage: 2.4,
    yoyChangeRate_ManagementRank: 1,
    detailByRegion: '罗源县: 2150件；永泰县: 1680件；闽清县: 1250件；闽侯县: 1650件',
    detailByYearTrend: '一季度: 540件；二季度: 520件；三季度: 570件；四季度: 520件；同比增长: 0.3%',
    detailByParkingType: '公共停车场: 9个；配建停车场: 3个；路内停车位: 2个；立体停车场: 1个',
    detailByAssessmentDimension: '设施完善度: 81.2分；管理效率: 80.6分；市民满意度: 79.9分；创新应用: 79.3分；综合排名: 第11名',
    detailByAnalysis: '同比: 处置量基本持平，泊位新增5.9%，智慧停车平台覆盖率81.5%，排名上升1位',
  },
  {
    areaName: '永泰县',
    yearIllegalParkingDisposal: 1680,
    yearPublicParkingTotal: 12,
    yearBerthTotal: 1450,
    yearSmartParkingCoverage: 79.8,
    yearParkingManagementRank: 12,
    yoyChangeRate_IllegalParkingDisposal: -0.5,
    yoyChangeRate_PublicParkingTotal: 3.8,
    yoyChangeRate_BerthTotal: 5.1,
    yoyChangeRate_SmartParkingCoverage: 2.1,
    yoyChangeRate_ManagementRank: 0,
    detailByRegion: '永泰县: 1680件；闽清县: 1250件；闽侯县: 1650件；鼓楼区: 12450件',
    detailByYearTrend: '一季度: 430件；二季度: 410件；三季度: 450件；四季度: 390件；同比增长: -0.5%',
    detailByParkingType: '公共停车场: 7个；配建停车场: 3个；路内停车位: 1个；立体停车场: 1个',
    detailByAssessmentDimension: '设施完善度: 79.3分；管理效率: 78.6分；市民满意度: 78.0分；创新应用: 77.4分；综合排名: 第12名',
    detailByAnalysis: '同比: 处置量下降0.5%，停车场建设稳步增长，智慧停车覆盖率达79.8%',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为停车管理年度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '180',
      rules: 'required',
    },
    {
      fieldName: 'yearIllegalParkingDisposal',
      label: '年度违停案件处置总量',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入年度违停案件处置总量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'yearPublicParkingTotal',
      label: '年度公共停车场总数量',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入年度公共停车场总数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'yearBerthTotal',
      label: '年度泊位总数量',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入年度泊位总数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'yearSmartParkingCoverage',
      label: '年度智慧停车平台覆盖率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入年度智慧停车平台覆盖率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearParkingManagementRank',
      label: '年度停车管理工作考核排名',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入年度停车管理工作考核排名',
        min: 1,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_IllegalParkingDisposal',
      label: '违停案件处置总量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_PublicParkingTotal',
      label: '公共停车场总数量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_BerthTotal',
      label: '泊位总数量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_SmartParkingCoverage',
      label: '智慧停车平台覆盖率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_ManagementRank',
      label: '考核排名同比变化(位次)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入排名同比变化（正数为上升，负数为下降）',
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRegion',
      label: '按区域拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按区域拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByYearTrend',
      label: '按年度趋势拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按季度/月度趋势拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByParkingType',
      label: '按停车场类型拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按停车场类型拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByAssessmentDimension',
      label: '按考核维度拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按考核维度拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByAnalysis',
      label: '同比分析结果',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比分析结果',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为停车管理年度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'yearIllegalParkingDisposal',
      title: '年度违停案件处置总量',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yearPublicParkingTotal',
      title: '年度公共停车场总数量',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yearBerthTotal',
      title: '年度泊位总数量',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearSmartParkingCoverage',
      title: '年度智慧停车平台覆盖率(%)',
      minWidth: 220,
      sortable: true,
    },
    {
      field: 'yearParkingManagementRank',
      title: '年度停车管理工作考核排名',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_IllegalParkingDisposal',
      title: '违停案件处置总量同比(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_PublicParkingTotal',
      title: '公共停车场总数量同比(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_BerthTotal',
      title: '泊位总数量同比(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_SmartParkingCoverage',
      title: '智慧停车平台覆盖率同比(%)',
      minWidth: 220,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_ManagementRank',
      title: '考核排名同比变化(位次)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'detailByRegion',
      title: '按区域拆分明细',
      minWidth: 280,
      sortable: false,
    },
    {
      field: 'detailByYearTrend',
      title: '按年度趋势拆分明细',
      minWidth: 280,
      sortable: false,
    },
    {
      field: 'detailByParkingType',
      title: '按停车场类型拆分明细',
      minWidth: 280,
      sortable: false,
    },
    {
      field: 'detailByAssessmentDimension',
      title: '按考核维度拆分明细',
      minWidth: 320,
      sortable: false,
    },
    {
      field: 'detailByAnalysis',
      title: '同比分析结果',
      minWidth: 300,
      sortable: false,
    },
  ];
}
