/** 表格初始数据 - 道路预警归档月度统计 */
export const dataList = () => [
  {
    statisticsMonth: '2025-02',
    monthlyTotalArchiveCount: 128,
    monthlyViolationCount: 23,
    monthlyApprovalRate: 82.03,
    keyAreaViolationRate: 34.78,
    monthOverMonthGrowth: -5.2,
    yearOverYearGrowth: 12.3,
  },
  {
    statisticsMonth: '2025-01',
    monthlyTotalArchiveCount: 135,
    monthlyViolationCount: 27,
    monthlyApprovalRate: 80.0,
    keyAreaViolationRate: 40.74,
    monthOverMonthGrowth: 3.8,
    yearOverYearGrowth: 15.1,
  },
  {
    statisticsMonth: '2024-12',
    monthlyTotalArchiveCount: 130,
    monthlyViolationCount: 25,
    monthlyApprovalRate: 80.77,
    keyAreaViolationRate: 36.0,
    monthOverMonthGrowth: 1.2,
    yearOverYearGrowth: 10.5,
  },
  {
    statisticsMonth: '2024-11',
    monthlyTotalArchiveCount: 128,
    monthlyViolationCount: 24,
    monthlyApprovalRate: 81.25,
    keyAreaViolationRate: 33.33,
    monthOverMonthGrowth: -2.1,
    yearOverYearGrowth: 9.8,
  },
  {
    statisticsMonth: '2024-10',
    monthlyTotalArchiveCount: 131,
    monthlyViolationCount: 26,
    monthlyApprovalRate: 80.15,
    keyAreaViolationRate: 38.46,
    monthOverMonthGrowth: 4.5,
    yearOverYearGrowth: 11.2,
  },
  {
    statisticsMonth: '2024-09',
    monthlyTotalArchiveCount: 125,
    monthlyViolationCount: 22,
    monthlyApprovalRate: 82.4,
    keyAreaViolationRate: 31.82,
    monthOverMonthGrowth: -1.3,
    yearOverYearGrowth: 8.6,
  },
  {
    statisticsMonth: '2024-08',
    monthlyTotalArchiveCount: 127,
    monthlyViolationCount: 23,
    monthlyApprovalRate: 81.89,
    keyAreaViolationRate: 34.78,
    monthOverMonthGrowth: 2.4,
    yearOverYearGrowth: 10.1,
  },
  {
    statisticsMonth: '2024-07',
    monthlyTotalArchiveCount: 124,
    monthlyViolationCount: 21,
    monthlyApprovalRate: 83.06,
    keyAreaViolationRate: 33.33,
    monthOverMonthGrowth: 3.1,
    yearOverYearGrowth: 9.3,
  },
  {
    statisticsMonth: '2024-06',
    monthlyTotalArchiveCount: 120,
    monthlyViolationCount: 20,
    monthlyApprovalRate: 83.33,
    keyAreaViolationRate: 30.0,
    monthOverMonthGrowth: 5.0,
    yearOverYearGrowth: 8.9,
  },
  {
    statisticsMonth: '2024-05',
    monthlyTotalArchiveCount: 114,
    monthlyViolationCount: 19,
    monthlyApprovalRate: 83.33,
    keyAreaViolationRate: 31.58,
    monthOverMonthGrowth: 4.2,
    yearOverYearGrowth: 7.5,
  },
  {
    statisticsMonth: '2024-04',
    monthlyTotalArchiveCount: 109,
    monthlyViolationCount: 18,
    monthlyApprovalRate: 83.49,
    keyAreaViolationRate: 27.78,
    monthOverMonthGrowth: 2.8,
    yearOverYearGrowth: 6.9,
  },
  {
    statisticsMonth: '2024-03',
    monthlyTotalArchiveCount: 106,
    monthlyViolationCount: 17,
    monthlyApprovalRate: 83.96,
    keyAreaViolationRate: 29.41,
    monthOverMonthGrowth: 3.5,
    yearOverYearGrowth: 6.2,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 道路预警归档月度统计表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'statisticsMonth',
      label: '统计月份',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择统计月份',
        type: 'month', // 月份选择器
        format: 'YYYY-MM',
        valueFormat: 'YYYY-MM',
      },
      labelWidth: '100',
      rules: 'required',
    },
    {
      fieldName: 'monthlyTotalArchiveCount',
      label: '月累计备案总量',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入月累计备案总量',
        min: 0,
        precision: 0,
        addonAfter: '件',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyViolationCount',
      label: '月违规处置总量',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入月违规处置总量',
        min: 0,
        precision: 0,
        addonAfter: '件',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyApprovalRate',
      label: '月审批通过率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入月审批通过率',
        min: 0,
        max: 100,
        precision: 2,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'keyAreaViolationRate',
      label: '重点区域违规占比',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入重点区域违规占比',
        min: 0,
        max: 100,
        precision: 2,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthOverMonthGrowth',
      label: '环比增长率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入环比增长率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOverYearGrowth',
      label: '同比增长率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入同比增长率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 道路预警归档月度统计表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'statisticsMonth',
      title: '统计月份',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monthlyTotalArchiveCount',
      title: '月累计备案总量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monthlyViolationCount',
      title: '月违规处置总量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monthlyApprovalRate',
      title: '月审批通过率',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'keyAreaViolationRate',
      title: '重点区域违规占比',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'monthOverMonthGrowth',
      title: '环比增长率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'yearOverYearGrowth',
      title: '同比增长率',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
