/** 表格初始数据 - 机动车违停与道路停车管理周度统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    illegalMotorVehicleParkingCount: 245,
    illegalNonMotorVehicleParkingCount: 189,
    publicParkingLotUtilizationRate: 78.5,
    roadParkingSpaceTurnoverRate: 65.2,
    illegalParkingRectificationCompletedCount: 210,
    momChangeRate_IllegalMotorVehicle: 3.2,
    momChangeRate_IllegalNonMotorVehicle: 2.8,
    momChangeRate_PublicParkingUtilization: 1.5,
    momChangeRate_RoadParkingTurnover: 2.1,
    momChangeRate_RectificationCompleted: 4.5,
    detailByArea: '鼓楼区: 245处；台江区: 167处；仓山区: 198处',
    detailByRoadGrade: '主干道: 156处；次干道: 189处；支路: 98处',
    detailByVehicleType: '机动车: 245辆；非机动车: 189辆',
    detailByControlPeriod: '高峰时段: 167处；平峰时段: 189处；夜间时段: 78处',
    detailByArea_Mom: '鼓楼区: 3.2%；台江区: 2.1%；仓山区: 4.5%',
    detailByRoadGrade_Mom: '主干道: 2.8%；次干道: 3.1%；支路: 1.9%',
    detailByVehicleType_Mom: '机动车: 3.5%；非机动车: 2.3%',
    detailByControlPeriod_Mom: '高峰时段: 4.2%；平峰时段: 2.8%；夜间时段: 1.5%',
  },
  {
    areaName: '台江区',
    illegalMotorVehicleParkingCount: 167,
    illegalNonMotorVehicleParkingCount: 142,
    publicParkingLotUtilizationRate: 72.3,
    roadParkingSpaceTurnoverRate: 58.9,
    illegalParkingRectificationCompletedCount: 152,
    momChangeRate_IllegalMotorVehicle: 2.1,
    momChangeRate_IllegalNonMotorVehicle: 1.9,
    momChangeRate_PublicParkingUtilization: 0.8,
    momChangeRate_RoadParkingTurnover: 1.2,
    momChangeRate_RectificationCompleted: 3.1,
    detailByArea: '台江区: 167处；鼓楼区: 245处；仓山区: 198处',
    detailByRoadGrade: '主干道: 102处；次干道: 128处；支路: 78处',
    detailByVehicleType: '机动车: 167辆；非机动车: 142辆',
    detailByControlPeriod: '高峰时段: 112处；平峰时段: 128处；夜间时段: 52处',
    detailByArea_Mom: '台江区: 2.1%；鼓楼区: 3.2%；仓山区: 4.5%',
    detailByRoadGrade_Mom: '主干道: 1.8%；次干道: 2.3%；支路: 1.2%',
    detailByVehicleType_Mom: '机动车: 2.5%；非机动车: 1.8%',
    detailByControlPeriod_Mom: '高峰时段: 3.1%；平峰时段: 2.1%；夜间时段: 1.2%',
  },
  {
    areaName: '仓山区',
    illegalMotorVehicleParkingCount: 198,
    illegalNonMotorVehicleParkingCount: 165,
    publicParkingLotUtilizationRate: 75.8,
    roadParkingSpaceTurnoverRate: 62.4,
    illegalParkingRectificationCompletedCount: 178,
    momChangeRate_IllegalMotorVehicle: 4.5,
    momChangeRate_IllegalNonMotorVehicle: 3.8,
    momChangeRate_PublicParkingUtilization: 2.1,
    momChangeRate_RoadParkingTurnover: 3.5,
    momChangeRate_RectificationCompleted: 5.2,
    detailByArea: '仓山区: 198处；晋安区: 134处；马尾区: 98处',
    detailByRoadGrade: '主干道: 128处；次干道: 142处；支路: 85处',
    detailByVehicleType: '机动车: 198辆；非机动车: 165辆',
    detailByControlPeriod: '高峰时段: 134处；平峰时段: 142处；夜间时段: 65处',
    detailByArea_Mom: '仓山区: 4.5%；晋安区: 2.8%；马尾区: 3.2%',
    detailByRoadGrade_Mom: '主干道: 3.8%；次干道: 4.2%；支路: 2.9%',
    detailByVehicleType_Mom: '机动车: 4.8%；非机动车: 3.5%',
    detailByControlPeriod_Mom: '高峰时段: 5.1%；平峰时段: 3.8%；夜间时段: 2.5%',
  },
  {
    areaName: '晋安区',
    illegalMotorVehicleParkingCount: 134,
    illegalNonMotorVehicleParkingCount: 112,
    publicParkingLotUtilizationRate: 68.9,
    roadParkingSpaceTurnoverRate: 55.6,
    illegalParkingRectificationCompletedCount: 124,
    momChangeRate_IllegalMotorVehicle: -1.2,
    momChangeRate_IllegalNonMotorVehicle: -0.8,
    momChangeRate_PublicParkingUtilization: -0.5,
    momChangeRate_RoadParkingTurnover: -0.3,
    momChangeRate_RectificationCompleted: 1.8,
    detailByArea: '晋安区: 134处；仓山区: 198处；台江区: 167处',
    detailByRoadGrade: '主干道: 89处；次干道: 98处；支路: 62处',
    detailByVehicleType: '机动车: 134辆；非机动车: 112辆',
    detailByControlPeriod: '高峰时段: 98处；平峰时段: 102处；夜间时段: 42处',
    detailByArea_Mom: '晋安区: -1.2%；仓山区: 4.5%；台江区: 2.1%',
    detailByRoadGrade_Mom: '主干道: -0.8%；次干道: -0.5%；支路: -0.3%',
    detailByVehicleType_Mom: '机动车: -1.5%；非机动车: -1.2%',
    detailByControlPeriod_Mom: '高峰时段: -0.8%；平峰时段: -0.5%；夜间时段: -0.3%',
  },
  {
    areaName: '马尾区',
    illegalMotorVehicleParkingCount: 98,
    illegalNonMotorVehicleParkingCount: 87,
    publicParkingLotUtilizationRate: 62.1,
    roadParkingSpaceTurnoverRate: 48.9,
    illegalParkingRectificationCompletedCount: 89,
    momChangeRate_IllegalMotorVehicle: 12.5,
    momChangeRate_IllegalNonMotorVehicle: 10.2,
    momChangeRate_PublicParkingUtilization: 8.7,
    momChangeRate_RoadParkingTurnover: 6.8,
    momChangeRate_RectificationCompleted: 11.5,
    detailByArea: '马尾区: 98处；长乐区: 65处；福清市: 45处',
    detailByRoadGrade: '主干道: 62处；次干道: 72处；支路: 41处',
    detailByVehicleType: '机动车: 98辆；非机动车: 87辆',
    detailByControlPeriod: '高峰时段: 72处；平峰时段: 78处；夜间时段: 35处',
    detailByArea_Mom: '马尾区: 12.5%；长乐区: 8.9%；福清市: 6.2%',
    detailByRoadGrade_Mom: '主干道: 10.2%；次干道: 11.8%；支路: 8.5%',
    detailByVehicleType_Mom: '机动车: 12.8%；非机动车: 9.5%',
    detailByControlPeriod_Mom: '高峰时段: 11.2%；平峰时段: 9.8%；夜间时段: 7.5%',
  },
  {
    areaName: '长乐区',
    illegalMotorVehicleParkingCount: 65,
    illegalNonMotorVehicleParkingCount: 58,
    publicParkingLotUtilizationRate: 58.7,
    roadParkingSpaceTurnoverRate: 45.2,
    illegalParkingRectificationCompletedCount: 62,
    momChangeRate_IllegalMotorVehicle: 5.6,
    momChangeRate_IllegalNonMotorVehicle: 4.3,
    momChangeRate_PublicParkingUtilization: 3.2,
    momChangeRate_RoadParkingTurnover: 2.8,
    momChangeRate_RectificationCompleted: 4.3,
    detailByArea: '长乐区: 65处；马尾区: 98处；连江县: 45处',
    detailByRoadGrade: '主干道: 42处；次干道: 48处；支路: 32处',
    detailByVehicleType: '机动车: 65辆；非机动车: 58辆',
    detailByControlPeriod: '高峰时段: 48处；平峰时段: 52处；夜间时段: 22处',
    detailByArea_Mom: '长乐区: 5.6%；马尾区: 12.5%；连江县: 3.8%',
    detailByRoadGrade_Mom: '主干道: 4.8%；次干道: 5.2%；支路: 3.5%',
    detailByVehicleType_Mom: '机动车: 5.8%；非机动车: 4.5%',
    detailByControlPeriod_Mom: '高峰时段: 5.2%；平峰时段: 4.8%；夜间时段: 3.2%',
  },
  {
    areaName: '福清市',
    illegalMotorVehicleParkingCount: 45,
    illegalNonMotorVehicleParkingCount: 42,
    publicParkingLotUtilizationRate: 55.3,
    roadParkingSpaceTurnoverRate: 42.1,
    illegalParkingRectificationCompletedCount: 41,
    momChangeRate_IllegalMotorVehicle: -1.8,
    momChangeRate_IllegalNonMotorVehicle: -1.5,
    momChangeRate_PublicParkingUtilization: -1.2,
    momChangeRate_RoadParkingTurnover: -0.9,
    momChangeRate_RectificationCompleted: 2.1,
    detailByArea: '福清市: 45处；长乐区: 65处；闽侯县: 32处',
    detailByRoadGrade: '主干道: 28处；次干道: 32处；支路: 21处',
    detailByVehicleType: '机动车: 45辆；非机动车: 42辆',
    detailByControlPeriod: '高峰时段: 32处；平峰时段: 35处；夜间时段: 15处',
    detailByArea_Mom: '福清市: -1.8%；长乐区: 5.6%；闽侯县: 2.8%',
    detailByRoadGrade_Mom: '主干道: -1.5%；次干道: -1.2%；支路: -0.8%',
    detailByVehicleType_Mom: '机动车: -1.8%；非机动车: -1.5%',
    detailByControlPeriod_Mom: '高峰时段: -1.2%；平峰时段: -1.0%；夜间时段: -0.5%',
  },
  {
    areaName: '连江县',
    illegalMotorVehicleParkingCount: 42,
    illegalNonMotorVehicleParkingCount: 38,
    publicParkingLotUtilizationRate: 52.8,
    roadParkingSpaceTurnoverRate: 40.5,
    illegalParkingRectificationCompletedCount: 39,
    momChangeRate_IllegalMotorVehicle: 8.3,
    momChangeRate_IllegalNonMotorVehicle: 6.7,
    momChangeRate_PublicParkingUtilization: 5.2,
    momChangeRate_RoadParkingTurnover: 4.8,
    momChangeRate_RectificationCompleted: 6.9,
    detailByArea: '连江县: 42处；福清市: 45处；闽侯县: 28处',
    detailByRoadGrade: '主干道: 26处；次干道: 30处；支路: 18处',
    detailByVehicleType: '机动车: 42辆；非机动车: 38辆',
    detailByControlPeriod: '高峰时段: 28处；平峰时段: 30处；夜间时段: 15处',
    detailByArea_Mom: '连江县: 8.3%；福清市: -1.8%；闽侯县: 1.8%',
    detailByRoadGrade_Mom: '主干道: 6.8%；次干道: 7.2%；支路: 5.5%',
    detailByVehicleType_Mom: '机动车: 8.5%；非机动车: 7.2%',
    detailByControlPeriod_Mom: '高峰时段: 7.8%；平峰时段: 6.5%；夜间时段: 5.2%',
  },
  {
    areaName: '闽侯县',
    illegalMotorVehicleParkingCount: 28,
    illegalNonMotorVehicleParkingCount: 25,
    publicParkingLotUtilizationRate: 48.9,
    roadParkingSpaceTurnoverRate: 36.8,
    illegalParkingRectificationCompletedCount: 26,
    momChangeRate_IllegalMotorVehicle: 3.4,
    momChangeRate_IllegalNonMotorVehicle: 2.8,
    momChangeRate_PublicParkingUtilization: 2.1,
    momChangeRate_RoadParkingTurnover: 1.5,
    momChangeRate_RectificationCompleted: 2.8,
    detailByArea: '闽侯县: 28处；连江县: 42处；罗源县: 22处',
    detailByRoadGrade: '主干道: 18处；次干道: 22处；支路: 15处',
    detailByVehicleType: '机动车: 28辆；非机动车: 25辆',
    detailByControlPeriod: '高峰时段: 20处；平峰时段: 22处；夜间时段: 12处',
    detailByArea_Mom: '闽侯县: 3.4%；连江县: 8.3%；罗源县: 1.5%',
    detailByRoadGrade_Mom: '主干道: 2.8%；次干道: 3.2%；支路: 2.5%',
    detailByVehicleType_Mom: '机动车: 3.5%；非机动车: 2.8%',
    detailByControlPeriod_Mom: '高峰时段: 3.2%；平峰时段: 2.8%；夜间时段: 2.1%',
  },
  {
    areaName: '罗源县',
    illegalMotorVehicleParkingCount: 22,
    illegalNonMotorVehicleParkingCount: 19,
    publicParkingLotUtilizationRate: 45.6,
    roadParkingSpaceTurnoverRate: 33.2,
    illegalParkingRectificationCompletedCount: 20,
    momChangeRate_IllegalMotorVehicle: 6.7,
    momChangeRate_IllegalNonMotorVehicle: 5.9,
    momChangeRate_PublicParkingUtilization: 4.8,
    momChangeRate_RoadParkingTurnover: 4.2,
    momChangeRate_RectificationCompleted: 5.3,
    detailByArea: '罗源县: 22处；闽侯县: 28处；永泰县: 18处',
    detailByRoadGrade: '主干道: 14处；次干道: 18处；支路: 12处',
    detailByVehicleType: '机动车: 22辆；非机动车: 19辆',
    detailByControlPeriod: '高峰时段: 16处；平峰时段: 18处；夜间时段: 8处',
    detailByArea_Mom: '罗源县: 6.7%；闽侯县: 3.4%；永泰县: 1.2%',
    detailByRoadGrade_Mom: '主干道: 5.9%；次干道: 6.2%；支路: 4.8%',
    detailByVehicleType_Mom: '机动车: 6.8%；非机动车: 5.5%',
    detailByControlPeriod_Mom: '高峰时段: 6.5%；平峰时段: 5.2%；夜间时段: 4.2%',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 机动车违停与道路停车管理周度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'illegalMotorVehicleParkingCount',
      label: '机动车违停数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入机动车违停数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'illegalNonMotorVehicleParkingCount',
      label: '非机动车乱停放数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入非机动车乱停放数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'publicParkingLotUtilizationRate',
      label: '公共停车场使用率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入公共停车场使用率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'roadParkingSpaceTurnoverRate',
      label: '道路停车泊位周转率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入道路停车泊位周转率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'illegalParkingRectificationCompletedCount',
      label: '违停整改完成数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违停整改完成数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_IllegalMotorVehicle',
      label: '机动车违停数量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入机动车违停数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_IllegalNonMotorVehicle',
      label: '非机动车乱停放数量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入非机动车乱停放数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_PublicParkingUtilization',
      label: '公共停车场使用率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入公共停车场使用率环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_RoadParkingTurnover',
      label: '道路停车泊位周转率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入道路停车泊位周转率环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_RectificationCompleted',
      label: '违停整改完成数量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违停整改完成数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByArea',
      label: '按区域拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按区域拆分的明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRoadGrade',
      label: '按道路等级拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按道路等级拆分的明细数据（主干道、次干道、支路）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByVehicleType',
      label: '按车辆类型拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按车辆类型拆分的明细数据（机动车、非机动车）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByControlPeriod',
      label: '按管控时段拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按管控时段拆分的明细数据（高峰时段、平峰时段、夜间时段）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByArea_Mom',
      label: '按区域环比分析结果',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按区域拆分的环比分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRoadGrade_Mom',
      label: '按道路等级环比分析结果',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按道路等级拆分的环比分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByVehicleType_Mom',
      label: '按车辆类型环比分析结果',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按车辆类型拆分的环比分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByControlPeriod_Mom',
      label: '按管控时段环比分析结果',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按管控时段拆分的环比分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 机动车违停与道路停车管理周度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'illegalMotorVehicleParkingCount',
      title: '机动车违停数量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'illegalNonMotorVehicleParkingCount',
      title: '非机动车乱停放数量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'publicParkingLotUtilizationRate',
      title: '公共停车场使用率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'roadParkingSpaceTurnoverRate',
      title: '道路停车泊位周转率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'illegalParkingRectificationCompletedCount',
      title: '违停整改完成数量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_IllegalMotorVehicle',
      title: '机动车违停环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_IllegalNonMotorVehicle',
      title: '非机动车乱停放环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_PublicParkingUtilization',
      title: '公共停车场使用率环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_RoadParkingTurnover',
      title: '道路停车泊位周转率环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_RectificationCompleted',
      title: '违停整改完成数量环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'detailByArea',
      title: '按区域拆分明细',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByRoadGrade',
      title: '按道路等级拆分明细',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByVehicleType',
      title: '按车辆类型拆分明细',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByControlPeriod',
      title: '按管控时段拆分明细',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByArea_Mom',
      title: '按区域环比分析结果',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByRoadGrade_Mom',
      title: '按道路等级环比分析结果',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByVehicleType_Mom',
      title: '按车辆类型环比分析结果',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByControlPeriod_Mom',
      title: '按管控时段环比分析结果',
      minWidth: 180,
      sortable: false,
    },
  ];
}
