/** 表格初始数据 - 上半年乱贴乱画管理统计分析数据 */
export const dataList = () => [
  {
    region: '鼓楼区',
    totalIllegalPostingPointsH1: 1250,
    cleanupCompletionRateH1: 89.5,
    illegalNumberDispositionTotalH1: 320,
    crossDepartmentCollaborationCountH1: 45,
    newControlModelEffectivenessH1: 76.8,
    totalIllegalPostingPointsH1YoY: 1180,
    totalIllegalPostingPointsH1YoYRate: 5.9,
    cleanupCompletionRateH1YoY: 85.2,
    cleanupCompletionRateH1YoYRate: 4.3,
    illegalNumberDispositionTotalH1YoY: 290,
    illegalNumberDispositionTotalH1YoYRate: 10.3,
    crossDepartmentCollaborationCountH1YoY: 38,
    crossDepartmentCollaborationCountH1YoYRate: 18.4,
    newControlModelEffectivenessH1YoY: 71.2,
    newControlModelEffectivenessH1YoYRate: 7.9,
    detailByArea: '核心商圈: 450处；居民区: 320处；学校周边: 280处；交通枢纽: 200处',
    detailByCollaboratingDepartments: '城管局: 680次；公安: 280次；社区: 180次；环卫: 120次',
    detailByControlModes: '人工巡查: 680处；智能识别: 320处；市民举报: 250处',
    detailByPointTypes: '小广告: 890处；涂鸦: 280处；违规标语: 80处',
  },
  {
    region: '台江区',
    totalIllegalPostingPointsH1: 980,
    cleanupCompletionRateH1: 92.3,
    illegalNumberDispositionTotalH1: 245,
    crossDepartmentCollaborationCountH1: 32,
    newControlModelEffectivenessH1: 82.1,
    totalIllegalPostingPointsH1YoY: 920,
    totalIllegalPostingPointsH1YoYRate: 6.5,
    cleanupCompletionRateH1YoY: 88.7,
    cleanupCompletionRateH1YoYRate: 3.6,
    illegalNumberDispositionTotalH1YoY: 220,
    illegalNumberDispositionTotalH1YoYRate: 11.4,
    crossDepartmentCollaborationCountH1YoY: 28,
    crossDepartmentCollaborationCountH1YoYRate: 14.3,
    newControlModelEffectivenessH1YoY: 78.5,
    newControlModelEffectivenessH1YoYRate: 4.6,
    detailByArea: '核心商圈: 380处；居民区: 290处；学校周边: 180处；交通枢纽: 130处',
    detailByCollaboratingDepartments: '城管局: 520次；公安: 210次；社区: 140次；环卫: 110次',
    detailByControlModes: '人工巡查: 520处；智能识别: 280处；市民举报: 180处',
    detailByPointTypes: '小广告: 720处；涂鸦: 180处；违规标语: 80处',
  },
  {
    region: '仓山区',
    totalIllegalPostingPointsH1: 1120,
    cleanupCompletionRateH1: 87.8,
    illegalNumberDispositionTotalH1: 285,
    crossDepartmentCollaborationCountH1: 41,
    newControlModelEffectivenessH1: 79.4,
    totalIllegalPostingPointsH1YoY: 1050,
    totalIllegalPostingPointsH1YoYRate: 6.7,
    cleanupCompletionRateH1YoY: 84.1,
    cleanupCompletionRateH1YoYRate: 4.7,
    illegalNumberDispositionTotalH1YoY: 260,
    illegalNumberDispositionTotalH1YoYRate: 9.6,
    crossDepartmentCollaborationCountH1YoY: 35,
    crossDepartmentCollaborationCountH1YoYRate: 17.1,
    newControlModelEffectivenessH1YoY: 75.8,
    newControlModelEffectivenessH1YoYRate: 3.6,
    detailByArea: '核心商圈: 420处；居民区: 350处；学校周边: 220处；交通枢纽: 130处',
    detailByCollaboratingDepartments: '城管局: 610次；公安: 245次；社区: 165次；环卫: 100次',
    detailByControlModes: '人工巡查: 610处；智能识别: 310处；市民举报: 200处',
    detailByPointTypes: '小广告: 810处；涂鸦: 240处；违规标语: 70处',
  },
  {
    region: '晋安区',
    totalIllegalPostingPointsH1: 890,
    cleanupCompletionRateH1: 94.2,
    illegalNumberDispositionTotalH1: 200,
    crossDepartmentCollaborationCountH1: 28,
    newControlModelEffectivenessH1: 85.6,
    totalIllegalPostingPointsH1YoY: 850,
    totalIllegalPostingPointsH1YoYRate: 4.7,
    cleanupCompletionRateH1YoY: 91.5,
    cleanupCompletionRateH1YoYRate: 2.7,
    illegalNumberDispositionTotalH1YoY: 185,
    illegalNumberDispositionTotalH1YoYRate: 8.1,
    crossDepartmentCollaborationCountH1YoY: 25,
    crossDepartmentCollaborationCountH1YoYRate: 12.0,
    newControlModelEffectivenessH1YoY: 82.1,
    newControlModelEffectivenessH1YoYRate: 3.5,
    detailByArea: '核心商圈: 320处；居民区: 280处；学校周边: 160处；交通枢纽: 130处',
    detailByCollaboratingDepartments: '城管局: 480次；公安: 180次；社区: 120次；环卫: 120次',
    detailByControlModes: '人工巡查: 480处；智能识别: 240处；市民举报: 170处',
    detailByPointTypes: '小广告: 650处；涂鸦: 180处；违规标语: 60处',
  },
  {
    region: '马尾区',
    totalIllegalPostingPointsH1: 680,
    cleanupCompletionRateH1: 91.7,
    illegalNumberDispositionTotalH1: 165,
    crossDepartmentCollaborationCountH1: 22,
    newControlModelEffectivenessH1: 80.3,
    totalIllegalPostingPointsH1YoY: 650,
    totalIllegalPostingPointsH1YoYRate: 4.6,
    cleanupCompletionRateH1YoY: 89.2,
    cleanupCompletionRateH1YoYRate: 2.5,
    illegalNumberDispositionTotalH1YoY: 155,
    illegalNumberDispositionTotalH1YoYRate: 6.5,
    crossDepartmentCollaborationCountH1YoY: 20,
    crossDepartmentCollaborationCountH1YoYRate: 10.0,
    newControlModelEffectivenessH1YoY: 77.8,
    newControlModelEffectivenessH1YoYRate: 2.5,
    detailByArea: '核心商圈: 240处；居民区: 220处；学校周边: 120处；交通枢纽: 100处',
    detailByCollaboratingDepartments: '城管局: 380次；公安: 140次；社区: 80次；环卫: 80次',
    detailByControlModes: '人工巡查: 380处；智能识别: 180处；市民举报: 120处',
    detailByPointTypes: '小广告: 480处；涂鸦: 140处；违规标语: 60处',
  },
  {
    region: '长乐区',
    totalIllegalPostingPointsH1: 750,
    cleanupCompletionRateH1: 88.9,
    illegalNumberDispositionTotalH1: 180,
    crossDepartmentCollaborationCountH1: 26,
    newControlModelEffectivenessH1: 78.9,
    totalIllegalPostingPointsH1YoY: 720,
    totalIllegalPostingPointsH1YoYRate: 4.2,
    cleanupCompletionRateH1YoY: 86.4,
    cleanupCompletionRateH1YoYRate: 2.5,
    illegalNumberDispositionTotalH1YoY: 165,
    illegalNumberDispositionTotalH1YoYRate: 9.1,
    crossDepartmentCollaborationCountH1YoY: 23,
    crossDepartmentCollaborationCountH1YoYRate: 13.0,
    newControlModelEffectivenessH1YoY: 76.4,
    newControlModelEffectivenessH1YoYRate: 2.5,
    detailByArea: '核心商圈: 280处；居民区: 240处；学校周边: 140处；交通枢纽: 90处',
    detailByCollaboratingDepartments: '城管局: 450次；公安: 165次；社区: 90次；环卫: 75次',
    detailByControlModes: '人工巡查: 450处；智能识别: 200处；市民举报: 100处',
    detailByPointTypes: '小广告: 540处；涂鸦: 150处；违规标语: 60处',
  },
  {
    region: '福清市',
    totalIllegalPostingPointsH1: 1080,
    cleanupCompletionRateH1: 86.4,
    illegalNumberDispositionTotalH1: 260,
    crossDepartmentCollaborationCountH1: 38,
    newControlModelEffectivenessH1: 75.2,
    totalIllegalPostingPointsH1YoY: 1020,
    totalIllegalPostingPointsH1YoYRate: 5.9,
    cleanupCompletionRateH1YoY: 83.1,
    cleanupCompletionRateH1YoYRate: 3.3,
    illegalNumberDispositionTotalH1YoY: 240,
    illegalNumberDispositionTotalH1YoYRate: 8.3,
    crossDepartmentCollaborationCountH1YoY: 34,
    crossDepartmentCollaborationCountH1YoYRate: 11.8,
    newControlModelEffectivenessH1YoY: 72.8,
    newControlModelEffectivenessH1YoYRate: 2.4,
    detailByArea: '核心商圈: 400处；居民区: 320处；学校周边: 200处；交通枢纽: 160处',
    detailByCollaboratingDepartments: '城管局: 620次；公安: 220次；社区: 140次；环卫: 120次',
    detailByControlModes: '人工巡查: 620处；智能识别: 300处；市民举报: 160处',
    detailByPointTypes: '小广告: 760处；涂鸦: 240处；违规标语: 80处',
  },
  {
    region: '闽侯县',
    totalIllegalPostingPointsH1: 520,
    cleanupCompletionRateH1: 93.1,
    illegalNumberDispositionTotalH1: 130,
    crossDepartmentCollaborationCountH1: 18,
    newControlModelEffectivenessH1: 83.7,
    totalIllegalPostingPointsH1YoY: 500,
    totalIllegalPostingPointsH1YoYRate: 4.0,
    cleanupCompletionRateH1YoY: 90.5,
    cleanupCompletionRateH1YoYRate: 2.6,
    illegalNumberDispositionTotalH1YoY: 120,
    illegalNumberDispositionTotalH1YoYRate: 8.3,
    crossDepartmentCollaborationCountH1YoY: 16,
    crossDepartmentCollaborationCountH1YoYRate: 12.5,
    newControlModelEffectivenessH1YoY: 81.2,
    newControlModelEffectivenessH1YoYRate: 2.5,
    detailByArea: '核心商圈: 180处；居民区: 160处；学校周边: 100处；交通枢纽: 80处',
    detailByCollaboratingDepartments: '城管局: 320次；公安: 120次；社区: 80次；环卫: 80次',
    detailByControlModes: '人工巡查: 320处；智能识别: 150处；市民举报: 50处',
    detailByPointTypes: '小广告: 380处；涂鸦: 100处；违规标语: 40处',
  },
  {
    region: '连江县',
    totalIllegalPostingPointsH1: 480,
    cleanupCompletionRateH1: 90.8,
    illegalNumberDispositionTotalH1: 145,
    crossDepartmentCollaborationCountH1: 21,
    newControlModelEffectivenessH1: 81.5,
    totalIllegalPostingPointsH1YoY: 460,
    totalIllegalPostingPointsH1YoYRate: 4.3,
    cleanupCompletionRateH1YoY: 88.2,
    cleanupCompletionRateH1YoYRate: 2.6,
    illegalNumberDispositionTotalH1YoY: 135,
    illegalNumberDispositionTotalH1YoYRate: 7.4,
    crossDepartmentCollaborationCountH1YoY: 19,
    crossDepartmentCollaborationCountH1YoYRate: 10.5,
    newControlModelEffectivenessH1YoY: 79.1,
    newControlModelEffectivenessH1YoYRate: 2.4,
    detailByArea: '核心商圈: 160处；居民区: 150处；学校周边: 90处；交通枢纽: 80处',
    detailByCollaboratingDepartments: '城管局: 280次；公安: 110次；社区: 70次；环卫: 60次',
    detailByControlModes: '人工巡查: 280处；智能识别: 140处；市民举报: 60处',
    detailByPointTypes: '小广告: 340处；涂鸦: 90处；违规标语: 50处',
  },
  {
    region: '闽清县',
    totalIllegalPostingPointsH1: 320,
    cleanupCompletionRateH1: 95.6,
    illegalNumberDispositionTotalH1: 95,
    crossDepartmentCollaborationCountH1: 14,
    newControlModelEffectivenessH1: 86.8,
    totalIllegalPostingPointsH1YoY: 300,
    totalIllegalPostingPointsH1YoYRate: 6.7,
    cleanupCompletionRateH1YoY: 93.1,
    cleanupCompletionRateH1YoYRate: 2.5,
    illegalNumberDispositionTotalH1YoY: 88,
    illegalNumberDispositionTotalH1YoYRate: 7.9,
    crossDepartmentCollaborationCountH1YoY: 12,
    crossDepartmentCollaborationCountH1YoYRate: 16.7,
    newControlModelEffectivenessH1YoY: 84.3,
    newControlModelEffectivenessH1YoYRate: 2.5,
    detailByArea: '核心商圈: 120处；居民区: 100处；学校周边: 60处；交通枢纽: 40处',
    detailByCollaboratingDepartments: '城管局: 200次；公安: 80次；社区: 50次；环卫: 50次',
    detailByControlModes: '人工巡查: 200处；智能识别: 80处；市民举报: 40处',
    detailByPointTypes: '小广告: 240处；涂鸦: 60处；违规标语: 20处',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 上半年乱贴乱画管理统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'region',
      label: '区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'totalIllegalPostingPointsH1',
      label: '上半年乱贴乱画点位总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年乱贴乱画点位总量',
        min: 0,
        precision: 0,
        addonAfter: '处',
      },
      rules: 'required',
    },
    {
      fieldName: 'cleanupCompletionRateH1',
      label: '上半年清理完成率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年清理完成率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'illegalNumberDispositionTotalH1',
      label: '上半年非法号码处置总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年非法号码处置总量',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'crossDepartmentCollaborationCountH1',
      label: '上半年跨部门协作次数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年跨部门协作次数',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'newControlModelEffectivenessH1',
      label: '上半年乱贴乱画管控新模式成效',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年乱贴乱画管控新模式成效（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'totalIllegalPostingPointsH1YoY',
      label: '上半年乱贴乱画点位总量同比',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年乱贴乱画点位总量同比',
        min: 0,
        precision: 0,
        addonAfter: '处',
      },
      rules: 'required',
    },
    {
      fieldName: 'totalIllegalPostingPointsH1YoYRate',
      label: '上半年乱贴乱画点位总量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年乱贴乱画点位总量同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'cleanupCompletionRateH1YoY',
      label: '上半年清理完成率同比',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年清理完成率同比',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'cleanupCompletionRateH1YoYRate',
      label: '上半年清理完成率同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年清理完成率同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'illegalNumberDispositionTotalH1YoY',
      label: '上半年非法号码处置总量同比',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年非法号码处置总量同比',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'illegalNumberDispositionTotalH1YoYRate',
      label: '上半年非法号码处置总量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年非法号码处置总量同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crossDepartmentCollaborationCountH1YoY',
      label: '上半年跨部门协作次数同比',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年跨部门协作次数同比',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'crossDepartmentCollaborationCountH1YoYRate',
      label: '上半年跨部门协作次数同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年跨部门协作次数同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'newControlModelEffectivenessH1YoY',
      label: '上半年乱贴乱画管控新模式成效同比',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年乱贴乱画管控新模式成效同比',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'newControlModelEffectivenessH1YoYRate',
      label: '上半年乱贴乱画管控新模式成效同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入上半年乱贴乱画管控新模式成效同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByArea',
      label: '按区域拆分的半年明细数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按区域拆分的半年明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByCollaboratingDepartments',
      label: '按协作部门拆分的半年明细数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按协作部门拆分的半年明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByControlModes',
      label: '按管控模式拆分的半年明细数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按管控模式拆分的半年明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByPointTypes',
      label: '按点位类型拆分的半年明细数据及同比分析结果',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按点位类型拆分的半年明细数据及同比分析结果',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 上半年乱贴乱画管理统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'region',
      title: '区域',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'totalIllegalPostingPointsH1',
      title: '上半年乱贴乱画点位总量(处)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'cleanupCompletionRateH1',
      title: '上半年清理完成率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'illegalNumberDispositionTotalH1',
      title: '上半年非法号码处置总量(次)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'crossDepartmentCollaborationCountH1',
      title: '上半年跨部门协作次数(次)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'newControlModelEffectivenessH1',
      title: '上半年乱贴乱画管控新模式成效(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'totalIllegalPostingPointsH1YoY',
      title: '上半年乱贴乱画点位总量同比(处)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'totalIllegalPostingPointsH1YoYRate',
      title: '上半年乱贴乱画点位总量同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'cleanupCompletionRateH1YoY',
      title: '上半年清理完成率同比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'cleanupCompletionRateH1YoYRate',
      title: '上半年清理完成率同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'illegalNumberDispositionTotalH1YoY',
      title: '上半年非法号码处置总量同比(次)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'illegalNumberDispositionTotalH1YoYRate',
      title: '上半年非法号码处置总量同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'crossDepartmentCollaborationCountH1YoY',
      title: '上半年跨部门协作次数同比(次)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'crossDepartmentCollaborationCountH1YoYRate',
      title: '上半年跨部门协作次数同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'newControlModelEffectivenessH1YoY',
      title: '上半年乱贴乱画管控新模式成效同比(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'newControlModelEffectivenessH1YoYRate',
      title: '上半年乱贴乱画管控新模式成效同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'detailByArea',
      title: '按区域拆分的半年明细数据',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByCollaboratingDepartments',
      title: '按协作部门拆分的半年明细数据',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByControlModes',
      title: '按管控模式拆分的半年明细数据',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByPointTypes',
      title: '按点位类型拆分的半年明细数据及同比分析结果',
      minWidth: 200,
      sortable: false,
    },
  ];
}
