/** 表格初始数据*/
export const dataList = () => {
  return [
    {
      name: '漳州万达广场停车场',
      type: '商业停车场',
      address: '芗城区建元东路2号',
      parkTotal: 850,
      useTotal: 628,
      status: '运营中',
      pricing:
        '白天（8:00-22:00）：8元/小时，首小时5元；夜间（22:00-8:00）：10元/次',
      businesstime: '00:00-24:00',
      businessname: '漳州万达商业管理有限公司',
      phonename: '陈经理',
      phone: '13859688888',
      division: '漳州市芗城区',
    },
    {
      name: '漳州动车站停车场',
      type: '公共停车场',
      address: '龙海区颜厝镇漳州站',
      parkTotal: 1200,
      useTotal: 956,
      status: '运营中',
      pricing: '30分钟内免费，30分钟-12小时：20元/次，12小时-24小时：30元/次',
      businesstime: '00:00-24:00',
      businessname: '漳州铁路运营管理有限公司',
      phonename: '林主管',
      phone: '13959699999',
      division: '漳州市龙海区',
    },
    {
      name: '碧湖生态园停车场',
      type: '公共停车场',
      address: '龙文区湖滨路碧湖生态园内',
      parkTotal: 400,
      useTotal: 289,
      status: '运营中',
      pricing: '2小时内免费，2小时后5元/小时，单日封顶30元',
      businesstime: '06:00-22:00',
      businessname: '漳州城市园林管理有限公司',
      phonename: '黄管理员',
      phone: '13759677777',
      division: '漳州市龙文区',
    },
    {
      name: '古城历史文化街区停车场',
      type: '文旅停车场',
      address: '芗城区延安南路漳州古城内',
      parkTotal: 300,
      useTotal: 278,
      status: '运营中',
      pricing: '1小时内免费，1小时后6元/小时，节假日8元/小时',
      businesstime: '08:00-23:00',
      businessname: '漳州古城文旅发展有限公司',
      phonename: '郑负责人',
      phone: '13659666666',
      division: '漳州市芗城区',
    },
    {
      name: '漳州台商投资区角美万达广场停车场',
      type: '商业停车场',
      address: '台商投资区角美镇锦江大道',
      parkTotal: 700,
      useTotal: 489,
      status: '运营中',
      pricing: '首2小时免费，2小时后7元/小时，单日封顶40元',
      businesstime: '00:00-24:00',
      businessname: '漳州角美万达商管有限公司',
      phonename: '吴经理',
      phone: '13559655555',
      division: '漳州市台商投资区',
    },
    {
      name: '荣昌花园小区停车场',
      type: '小区停车场',
      address: '芗城区丹霞路123号',
      parkTotal: 500,
      useTotal: 480,
      status: '运营中',
      pricing: '月卡：200元/月，临时停车：3元/小时，单日封顶20元',
      businesstime: '00:00-24:00',
      businessname: '漳州荣昌物业管理有限公司',
      phonename: '张物业',
      phone: '13459644444',
      division: '漳州市芗城区',
    },
    {
      name: '漳州高新区软件园停车场',
      type: '办公停车场',
      address: '高新区圆山大道88号',
      parkTotal: 600,
      useTotal: 320,
      status: '运营中',
      pricing: '内部员工：免费，外来车辆：5元/小时',
      businesstime: '07:00-23:00',
      businessname: '漳州高新软件园运营有限公司',
      phonename: '李主管',
      phone: '13359633333',
      division: '漳州市高新区',
    },
    {
      name: '东山岛风动石景区停车场',
      type: '文旅停车场',
      address: '东山县铜陵镇风动石景区门口',
      parkTotal: 350,
      useTotal: 305,
      status: '运营中',
      pricing: '10元/次（不限时），节假日15元/次',
      businesstime: '07:00-18:00',
      businessname: '东山岛文旅发展有限公司',
      phonename: '王经理',
      phone: '13259622222',
      division: '漳州市东山县',
    },
    {
      name: '漳州第一医院停车场',
      type: '医疗停车场',
      address: '芗城区胜利西路59号',
      parkTotal: 450,
      useTotal: 420,
      status: '运营中',
      pricing: '30分钟内免费，30分钟后4元/小时，单日封顶30元',
      businesstime: '00:00-24:00',
      businessname: '漳州第一医院后勤管理处',
      phonename: '刘主任',
      phone: '13159611111',
      division: '漳州市芗城区',
    },
    {
      name: '长泰天柱山欢乐大世界停车场',
      type: '文旅停车场',
      address: '长泰区马洋溪生态旅游区',
      parkTotal: 1000,
      useTotal: 850,
      status: '运营中',
      pricing: '免费停车（凭景区门票）',
      businesstime: '09:00-21:00',
      businessname: '长泰天柱山旅游开发有限公司',
      phonename: '杨负责人',
      phone: '13059600000',
      division: '漳州市长泰区',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'name',
      label: '停车场名称',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入停车场名称',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '公共', value: '公共' },
          { label: '路侧', value: '路侧' },
          { label: '专用', value: '专用' },
        ],
        placeholder: '请选择',
        showSearch: true,
      },
      defaultValue: '公共',
      fieldName: 'type',
      label: '车场类型',
    },
    {
      fieldName: 'address',
      label: '所属区域',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入所属区域',
      },
    },
    {
      fieldName: 'parkTotal',
      label: '总车位数',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入总车位数',
      },
      rules: 'required',
    },
    {
      fieldName: 'useTotal',
      label: '可用车位数',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入可用车位数',
      },
      rules: 'required',
    },
    {
      fieldName: 'status',
      label: '状态',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入状态',
      },
      rules: 'required',
    },
    {
      fieldName: 'pricing',
      label: '收费标准',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入收费标准',
      },
    },
    {
      fieldName: 'businesstime',
      label: '营业时间',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入营业时间',
      },
    },
    {
      fieldName: 'businessname',
      label: '运营商户',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入运营商户',
      },
    },
    {
      fieldName: 'phonename',
      label: '联系人',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入联系人',
      },
    },
    {
      fieldName: 'phone',
      label: '联系电话',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入联系电话',
      },
    },
    {
      fieldName: 'division',
      label: '所属行政区划',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入所属行政区划',
      },
    },
    {
      fieldName: 'status',
      label: '运营状态',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '启用', value: '启用' },
          { label: '禁用', value: '禁用' },
          { label: '暂停运营', value: '暂停运营' },
          { label: '维修中', value: '维修中' },
        ],
        placeholder: '请输入运营状态',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },

    {
      field: 'name',
      title: '停车场名称',
      minWidth: 200,
      sortable: true
    },
    {
      field: 'type',
      title: '车场类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'address',
      title: '所属区域',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'parkTotal',
      title: '总车位数',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'useTotal',
      title: '可用车位数',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'status',
      title: '状态',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'pricing',
      title: '收费标准',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'businesstime',
      title: '营业时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'businessname',
      title: '运营商户',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'phonename',
      title: '联系人',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'phone',
      title: '联系电话',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'division',
      title: '所属行政区划',
      minWidth: 200,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑停车场',
  addText: '新增停车场',
  excelName: '停车场列表',
  excelAllName: '全市停车场数据.xlsx',
  total: '停车场数量10;车位总数:1211;车场车位7',
};
