/** 表格初始数据 - 改造为道路监测半年统计分析数据 */
export const dataList = () => [
  {
    roadSectionName: '福州市鼓楼区杨桥东路（东街口-五一广场）',
    areaName: '福州市鼓楼区',
    potholeCountHalfYearAvg: 5.8,
    crackLengthHalfYearAvg: 9.6,
    halfYearTotalWarningCount: 145,
    halfYearWorkOrderCount: 118,
    halfYearDisposalEfficiencyScore: 91.5,
    deviceHalfYearOperationRate: 96.8,
    potholeCountMomChangeRate: 6.5,
    potholeCountYoYChangeRate: 10.2,
    crackLengthMomChangeRate: -3.8,
    crackLengthYoYChangeRate: 4.5,
    areaFacilityHealthRank: 3,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis:
      '坑洼超标: 68%, 裂缝超标: 22%, 温度异常: 7%, 流量异常: 3%',
    facilityOptimizationSuggestion:
      '1. 杨桥东路东街口段坑洼集中区域建议Q3进行局部铣刨重铺；2. 优化五一广场段监测设备采集频率至3分钟/次；3. 每半月增加一次人工巡检频次。',
  },
  {
    roadSectionName: '厦门市思明区鹭江道（轮渡码头-中山路）',
    areaName: '厦门市思明区',
    potholeCountHalfYearAvg: 2.1,
    crackLengthHalfYearAvg: 3.4,
    halfYearTotalWarningCount: 72,
    halfYearWorkOrderCount: 58,
    halfYearDisposalEfficiencyScore: 98.8,
    deviceHalfYearOperationRate: 99.2,
    potholeCountMomChangeRate: -6.2,
    potholeCountYoYChangeRate: -8.5,
    crackLengthMomChangeRate: 1.8,
    crackLengthYoYChangeRate: -2.5,
    areaFacilityHealthRank: 1,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis:
      '坑洼超标: 38%, 裂缝超标: 32%, 温度异常: 25%, 流量异常: 5%',
    facilityOptimizationSuggestion:
      '1. 鹭江道轮渡码头段建议增加路面温度监测点；2. 中山路接口处裂缝建议采用灌缝工艺处理；3. 保持现有运维频次，每季度进行一次全面检测。',
  },
  {
    roadSectionName: '泉州市丰泽区刺桐路（湖心街-泉秀街）',
    areaName: '泉州市丰泽区',
    potholeCountHalfYearAvg: 12.1,
    crackLengthHalfYearAvg: 18.5,
    halfYearTotalWarningCount: 298,
    halfYearWorkOrderCount: 245,
    halfYearDisposalEfficiencyScore: 74.2,
    deviceHalfYearOperationRate: 85.5,
    potholeCountMomChangeRate: 22.8,
    potholeCountYoYChangeRate: 28.5,
    crackLengthMomChangeRate: 18.2,
    crackLengthYoYChangeRate: 20.8,
    areaFacilityHealthRank: 9,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis:
      '坑洼超标: 78%, 裂缝超标: 18%, 温度异常: 3%, 流量异常: 1%',
    facilityOptimizationSuggestion:
      '1. 刺桐路湖心街至泉秀街段建议Q3进行大面积路面修复；2. 更换老化监测设备，提升在线率；3. 增加运维人员配置，缩短工单处置时长。',
  },
  {
    roadSectionName: '漳州市芗城区胜利路（延安北路-新华西路）',
    areaName: '漳州市芗城区',
    potholeCountHalfYearAvg: 0.5,
    crackLengthHalfYearAvg: 1.3,
    halfYearTotalWarningCount: 0,
    halfYearWorkOrderCount: 0,
    halfYearDisposalEfficiencyScore: 100,
    deviceHalfYearOperationRate: 98.9,
    potholeCountMomChangeRate: -11.5,
    potholeCountYoYChangeRate: -15.8,
    crackLengthMomChangeRate: -9.2,
    crackLengthYoYChangeRate: -10.5,
    areaFacilityHealthRank: 2,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis: '无预警工单数据',
    facilityOptimizationSuggestion:
      '1. 保持现有养护标准，每季度进行一次预防性养护；2. 胜利路全段监测设备运行良好，建议延续现有采集频率；3. 可作为标杆路段进行管理经验推广。',
  },
  {
    roadSectionName: '莆田市城厢区荔城南大道（凤凰山-万达广场）',
    areaName: '莆田市城厢区',
    potholeCountHalfYearAvg: 8.2,
    crackLengthHalfYearAvg: 14.8,
    halfYearTotalWarningCount: 205,
    halfYearWorkOrderCount: 172,
    halfYearDisposalEfficiencyScore: 82.8,
    deviceHalfYearOperationRate: 77.8,
    potholeCountMomChangeRate: 11.5,
    potholeCountYoYChangeRate: 17.2,
    crackLengthMomChangeRate: 9.8,
    crackLengthYoYChangeRate: 14.5,
    areaFacilityHealthRank: 7,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis:
      '坑洼超标: 72%, 裂缝超标: 23%, 温度异常: 4%, 流量异常: 1%',
    facilityOptimizationSuggestion:
      '1. 荔城南大道万达广场段建议Q3进行坑洼集中修复；2. 更换离线率较高的监测设备（FJ-PT-202406-005）；3. 优化工单派单流程，提升处置效率。',
  },
  {
    roadSectionName: '宁德市蕉城区闽东中路（市政府-万达广场）',
    areaName: '宁德市蕉城区',
    potholeCountHalfYearAvg: 5.2,
    crackLengthHalfYearAvg: 8.1,
    halfYearTotalWarningCount: 95,
    halfYearWorkOrderCount: 78,
    halfYearDisposalEfficiencyScore: 93.8,
    deviceHalfYearOperationRate: 96.5,
    potholeCountMomChangeRate: 4.8,
    potholeCountYoYChangeRate: 8.2,
    crackLengthMomChangeRate: -2.5,
    crackLengthYoYChangeRate: 1.8,
    areaFacilityHealthRank: 4,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis:
      '坑洼超标: 62%, 裂缝超标: 28%, 温度异常: 8%, 流量异常: 2%',
    facilityOptimizationSuggestion:
      '1. 闽东中路市政府段裂缝建议采用密封胶处理；2. 保持现有监测频率，每月进行一次数据复盘；3. 运维人员配置充足，可支援周边路段应急处置。',
  },
  {
    roadSectionName: '龙岩市新罗区龙川路（中山路-登高西路）',
    areaName: '龙岩市新罗区',
    potholeCountHalfYearAvg: 10.1,
    crackLengthHalfYearAvg: 15.2,
    halfYearTotalWarningCount: 238,
    halfYearWorkOrderCount: 205,
    halfYearDisposalEfficiencyScore: 87.5,
    deviceHalfYearOperationRate: 96.2,
    potholeCountMomChangeRate: 18.5,
    potholeCountYoYChangeRate: 24.2,
    crackLengthMomChangeRate: 12.8,
    crackLengthYoYChangeRate: 17.5,
    areaFacilityHealthRank: 6,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis:
      '坑洼超标: 70%, 裂缝超标: 26%, 温度异常: 3%, 流量异常: 1%',
    facilityOptimizationSuggestion:
      '1. 龙川路登高西路接口处建议进行路面补强处理；2. 人工巡检发现的隐患点优先纳入Q3养护计划；3. 优化监测数据与工单系统的联动机制。',
  },
  {
    roadSectionName: '三明市梅列区列东街（东新四路-东新六路）',
    areaName: '三明市梅列区',
    potholeCountHalfYearAvg: 4.5,
    crackLengthHalfYearAvg: 6.8,
    halfYearTotalWarningCount: 52,
    halfYearWorkOrderCount: 42,
    halfYearDisposalEfficiencyScore: 98.5,
    deviceHalfYearOperationRate: 98,
    potholeCountMomChangeRate: -5.2,
    potholeCountYoYChangeRate: -7.8,
    crackLengthMomChangeRate: -6.5,
    crackLengthYoYChangeRate: -8.8,
    areaFacilityHealthRank: 5,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis:
      '坑洼超标: 56%, 裂缝超标: 34%, 温度异常: 8%, 流量异常: 2%',
    facilityOptimizationSuggestion:
      '1. 列东街东新六路段建议进行预防性灌缝处理；2. 保持现有运维标准，每两月进行一次设备校准；3. 处置效率表现优异，可作为区域标杆推广。',
  },
  {
    roadSectionName: '南平市延平区八一路（江滨路-中山路）',
    areaName: '南平市延平区',
    potholeCountHalfYearAvg: 7.5,
    crackLengthHalfYearAvg: 11.5,
    halfYearTotalWarningCount: 178,
    halfYearWorkOrderCount: 148,
    halfYearDisposalEfficiencyScore: 77.8,
    deviceHalfYearOperationRate: 87.2,
    potholeCountMomChangeRate: 9.8,
    potholeCountYoYChangeRate: 15.5,
    crackLengthMomChangeRate: 7.5,
    crackLengthYoYChangeRate: 11.2,
    areaFacilityHealthRank: 8,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis:
      '坑洼超标: 75%, 裂缝超标: 20%, 温度异常: 4%, 流量异常: 1%',
    facilityOptimizationSuggestion:
      '1. 八一路中山路接口处建议Q3进行路面大修；2. 修复异常监测设备（FJ-NP-202406-009），提升数据准确性；3. 增加运维人员培训，提升处置达标率。',
  },
  {
    roadSectionName: '平潭综合实验区金井大道（管委会-龙凤头沙滩）',
    areaName: '平潭综合实验区',
    potholeCountHalfYearAvg: 1.2,
    crackLengthHalfYearAvg: 3.1,
    halfYearTotalWarningCount: 88,
    halfYearWorkOrderCount: 68,
    halfYearDisposalEfficiencyScore: 98.2,
    deviceHalfYearOperationRate: 99.6,
    potholeCountMomChangeRate: -3.5,
    potholeCountYoYChangeRate: -6.2,
    crackLengthMomChangeRate: 3.8,
    crackLengthYoYChangeRate: 1.5,
    areaFacilityHealthRank: 10,
    halfYearStatisticsPeriod: '2024-H1（2024-01-01 ~ 2024-06-30）',
    warningWorkOrderCategoryAnalysis:
      '坑洼超标: 42%, 裂缝超标: 28%, 温度异常: 25%, 流量异常: 5%',
    facilityOptimizationSuggestion:
      '1. 金井大道龙凤头沙滩段建议增加抗高温路面材料使用；2. 旅游旺季前增加巡检频次至每周一次；3. 设备运行状态极佳，建议延续现有管理策略。',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为道路监测半年统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'roadSectionName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
      },
      labelWidth: '180',
      rules: 'required', // 路段名称为必填项
    },
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称（如：福州市鼓楼区）',
      },
      labelWidth: '180',
      rules: 'required',
    },
    {
      fieldName: 'potholeCountHalfYearAvg',
      label: '坑洼数量半年均值',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入坑洼数量半年均值',
        min: 0,
        precision: 1, // 保留1位小数，贴合半年均值统计场景
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthHalfYearAvg',
      label: '裂缝长度半年均值',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入裂缝长度半年均值（单位：米）',
        min: 0,
        precision: 1,
        addonAfter: '米',
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearTotalWarningCount',
      label: '半年累计预警数',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入半年累计预警数',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearWorkOrderCount',
      label: '半年工单量',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入半年工单量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearDisposalEfficiencyScore',
      label: '半年处置效能综合评分',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入半年处置效能综合评分（单位：分）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '分',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceHalfYearOperationRate',
      label: '设备半年运行率',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入设备半年运行率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountMomChangeRate',
      label: '坑洼数量环比变化率',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入坑洼数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountYoYChangeRate',
      label: '坑洼数量同比变化率',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入坑洼数量同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthMomChangeRate',
      label: '裂缝长度环比变化率',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入裂缝长度环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthYoYChangeRate',
      label: '裂缝长度同比变化率',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入裂缝长度同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'areaFacilityHealthRank',
      label: '区域设施健康度排名',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入区域设施健康度排名',
        min: 1,
        precision: 0,
        addonAfter: '名',
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearStatisticsPeriod',
      label: '半年统计时段',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder:
          '请输入半年统计时段（如：2024-H1（2024-01-01 ~ 2024-06-30））',
        maxlength: 80,
      },
      rules: 'required',
    },
    {
      fieldName: 'warningWorkOrderCategoryAnalysis',
      label: '预警工单分类分析',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder:
          '请输入预警工单分类分析（如：坑洼超标: 68%, 裂缝超标: 22%, 温度异常: 7%, 流量异常: 3%）',
        maxlength: 200,
      },
      rules: 'required',
    },
    {
      fieldName: 'facilityOptimizationSuggestion',
      label: '设施优化建议',
      component: 'Input',
      componentProps: {
        type: 'textarea',
        placeholder:
          '请输入设施优化建议（如：1. 杨桥东路东街口段坑洼集中区域建议Q3进行局部铣刨重铺；2. 优化五一广场段监测设备采集频率至3分钟/次；3. 每半月增加一次人工巡检频次。）',
        rows: 4,
        maxlength: 500,
      },
      labelWidth: '180',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为道路监测半年统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'roadSectionName',
      title: '路段名称',
      minWidth: 240,
      sortable: true,
      slots: { default: 'roadSectionName' }, // 自定义slot适配路段名称渲染
    },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'potholeCountHalfYearAvg',
      title: '坑洼数量半年均值',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'crackLengthHalfYearAvg',
      title: '裂缝长度半年均值(米)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'halfYearTotalWarningCount',
      title: '半年累计预警数',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'halfYearWorkOrderCount',
      title: '半年工单量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'halfYearDisposalEfficiencyScore',
      title: '半年处置效能综合评分(分)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'deviceHalfYearOperationRate',
      title: '设备半年运行率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'potholeCountMomChangeRate',
      title: '坑洼数量环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'potholeCountYoYChangeRate',
      title: '坑洼数量同比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'crackLengthMomChangeRate',
      title: '裂缝长度环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'crackLengthYoYChangeRate',
      title: '裂缝长度同比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'areaFacilityHealthRank',
      title: '区域设施健康度排名',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'halfYearStatisticsPeriod',
      title: '半年统计时段',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'warningWorkOrderCategoryAnalysis',
      title: '预警工单分类分析',
      minWidth: 280,
      sortable: false, // 文本描述类字段无需排序
    },
    {
      field: 'facilityOptimizationSuggestion',
      title: '设施优化建议',
      minWidth: 350,
      sortable: false, // 文本描述类字段无需排序
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
