/** 表格初始数据 - 季度违停案件及停车管理统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    quarterlyIllegalParkingCases: 1250,
    quarterlyPublicParkingSupplyDemandAnalysis: 78.5,
    quarterlyParkingSpaceOptimizationAdjustment: 45,
    quarterlySmartParkingUsageRate: 68.2,
    quarterlyCrossDepartmentParkingManagementCollaboration: 23,
    momChangeRate_IllegalCases: 5.8,
    momChangeRate_SupplyDemand: 3.2,
    momChangeRate_Optimization: 8.9,
    momChangeRate_SmartUsage: 12.5,
    momChangeRate_Collaboration: 15.3,
    yoyChangeRate_IllegalCases: 12.3,
    yoyChangeRate_SupplyDemand: 8.7,
    yoyChangeRate_Optimization: 18.9,
    yoyChangeRate_SmartUsage: 22.1,
    yoyChangeRate_Collaboration: 25.4,
    detailByRegion: '鼓楼区: 1250起；台江区: 890起；仓山区: 1020起',
    detailByParkingType: '路内泊位: 680个；路外停车场: 420个；立体停车场: 150个',
    detailByOptimizationPoints: '商业区: 25个；住宅区: 15个；医院周边: 5个',
    detailByCollaborationDepartments: '交警部门: 12次；城管部门: 8次；社区: 3次',
    detailByRegion_YoY: '同比增长：鼓楼区+15.2%，台江区+8.9%，仓山区+12.1%',
    detailByParkingType_YoY: '同比增长：路内泊位+18.5%，路外停车场+12.3%，立体停车场+25.6%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+22.1%，住宅区+15.8%，医院周边+30.2%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+28.9%，城管部门+18.6%，社区+35.4%',
    detailByRegion_MoM: '环比增长：鼓楼区+5.8%，台江区+3.2%，仓山区+8.9%',
    detailByParkingType_MoM: '环比增长：路内泊位+12.5%，路外停车场+15.3%，立体停车场+18.7%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+25.1%，住宅区+18.9%，医院周边+22.4%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+30.2%，城管部门+25.8%，社区+35.6%',
  },
  {
    areaName: '台江区',
    quarterlyIllegalParkingCases: 890,
    quarterlyPublicParkingSupplyDemandAnalysis: 82.3,
    quarterlyParkingSpaceOptimizationAdjustment: 38,
    quarterlySmartParkingUsageRate: 71.5,
    quarterlyCrossDepartmentParkingManagementCollaboration: 18,
    momChangeRate_IllegalCases: 2.3,
    momChangeRate_SupplyDemand: 4.1,
    momChangeRate_Optimization: 6.5,
    momChangeRate_SmartUsage: 8.9,
    momChangeRate_Collaboration: 12.8,
    yoyChangeRate_IllegalCases: 8.9,
    yoyChangeRate_SupplyDemand: 12.3,
    yoyChangeRate_Optimization: 15.6,
    yoyChangeRate_SmartUsage: 18.9,
    yoyChangeRate_Collaboration: 20.1,
    detailByRegion: '台江区: 890起；鼓楼区: 1250起；仓山区: 1020起',
    detailByParkingType: '路内泊位: 450个；路外停车场: 320个；立体停车场: 120个',
    detailByOptimizationPoints: '商业区: 18个；住宅区: 12个；学校周边: 8个',
    detailByCollaborationDepartments: '交警部门: 10次；城管部门: 6次；社区: 2次',
    detailByRegion_YoY: '同比增长：台江区+8.9%，鼓楼区+12.3%，仓山区+15.6%',
    detailByParkingType_YoY: '同比增长：路内泊位+15.2%，路外停车场+18.9%，立体停车场+22.4%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+18.6%，住宅区+22.1%，学校周边+28.9%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+18.9%，城管部门+25.4%，社区+30.2%',
    detailByRegion_MoM: '环比增长：台江区+2.3%，鼓楼区+4.1%，仓山区+6.5%',
    detailByParkingType_MoM: '环比增长：路内泊位+8.9%，路外停车场+12.3%，立体停车场+15.6%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+18.9%，住宅区+22.4%，学校周边+25.8%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+20.1%，城管部门+25.6%，社区+28.9%',
  },
  {
    areaName: '仓山区',
    quarterlyIllegalParkingCases: 1020,
    quarterlyPublicParkingSupplyDemandAnalysis: 76.8,
    quarterlyParkingSpaceOptimizationAdjustment: 42,
    quarterlySmartParkingUsageRate: 65.9,
    quarterlyCrossDepartmentParkingManagementCollaboration: 20,
    momChangeRate_IllegalCases: 8.9,
    momChangeRate_SupplyDemand: 5.4,
    momChangeRate_Optimization: 5.4,
    momChangeRate_SmartUsage: 10.2,
    momChangeRate_Collaboration: 9.8,
    yoyChangeRate_IllegalCases: 15.6,
    yoyChangeRate_SupplyDemand: 18.9,
    yoyChangeRate_Optimization: 22.1,
    yoyChangeRate_SmartUsage: 25.4,
    yoyChangeRate_Collaboration: 28.7,
    detailByRegion: '仓山区: 1020起；晋安区: 680起；马尾区: 440起',
    detailByParkingType: '路内泊位: 520个；路外停车场: 380个；立体停车场: 120个',
    detailByOptimizationPoints: '商业区: 22个；住宅区: 15个；地铁站周边: 5个',
    detailByCollaborationDepartments: '交警部门: 11次；城管部门: 7次；社区: 2次',
    detailByRegion_YoY: '同比增长：仓山区+15.6%，晋安区+12.8%，马尾区+18.9%',
    detailByParkingType_YoY: '同比增长：路内泊位+20.1%，路外停车场+18.6%，立体停车场+25.8%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+25.4%，住宅区+28.9%，地铁站周边+32.1%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+25.4%，城管部门+28.9%，社区+35.6%',
    detailByRegion_MoM: '环比增长：仓山区+8.9%，晋安区+6.5%，马尾区+5.2%',
    detailByParkingType_MoM: '环比增长：路内泊位+10.2%，路外停车场+12.8%，立体停车场+15.4%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+18.9%，住宅区+22.1%，地铁站周边+25.6%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+22.4%，城管部门+25.8%，社区+28.9%',
  },
  {
    areaName: '晋安区',
    quarterlyIllegalParkingCases: 680,
    quarterlyPublicParkingSupplyDemandAnalysis: 85.2,
    quarterlyParkingSpaceOptimizationAdjustment: 25,
    quarterlySmartParkingUsageRate: 73.1,
    quarterlyCrossDepartmentParkingManagementCollaboration: 15,
    momChangeRate_IllegalCases: -2.1,
    momChangeRate_SupplyDemand: 3.8,
    momChangeRate_Optimization: 3.8,
    momChangeRate_SmartUsage: 1.9,
    momChangeRate_Collaboration: 1.9,
    yoyChangeRate_IllegalCases: 12.8,
    yoyChangeRate_SupplyDemand: 15.4,
    yoyChangeRate_Optimization: 18.6,
    yoyChangeRate_SmartUsage: 20.2,
    yoyChangeRate_Collaboration: 22.8,
    detailByRegion: '晋安区: 680起；仓山区: 1020起；台江区: 890起',
    detailByParkingType: '路内泊位: 380个；路外停车场: 250个；立体停车场: 50个',
    detailByOptimizationPoints: '商业区: 15个；住宅区: 8个；学校周边: 2个',
    detailByCollaborationDepartments: '交警部门: 8次；城管部门: 5次；社区: 2次',
    detailByRegion_YoY: '同比增长：晋安区+12.8%，仓山区+18.6%，台江区+20.2%',
    detailByParkingType_YoY: '同比增长：路内泊位+18.9%，路外停车场+15.4%，立体停车场+22.8%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+20.1%，住宅区+25.4%，学校周边+28.9%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+22.4%，城管部门+25.8%，社区+28.9%',
    detailByRegion_MoM: '环比增长：晋安区-2.1%，仓山区+3.8%，台江区+3.8%',
    detailByParkingType_MoM: '环比增长：路内泊位+1.9%，路外停车场+1.9%，立体停车场+1.9%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+1.9%，住宅区+1.9%，学校周边+1.9%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+1.9%，城管部门+1.9%，社区+1.9%',
  },
  {
    areaName: '马尾区',
    quarterlyIllegalParkingCases: 440,
    quarterlyPublicParkingSupplyDemandAnalysis: 79.6,
    quarterlyParkingSpaceOptimizationAdjustment: 18,
    quarterlySmartParkingUsageRate: 69.3,
    quarterlyCrossDepartmentParkingManagementCollaboration: 12,
    momChangeRate_IllegalCases: 12.5,
    momChangeRate_SupplyDemand: 10.2,
    momChangeRate_Optimization: 10.2,
    momChangeRate_SmartUsage: 8.7,
    momChangeRate_Collaboration: 8.7,
    yoyChangeRate_IllegalCases: 18.9,
    yoyChangeRate_SupplyDemand: 22.1,
    yoyChangeRate_Optimization: 25.4,
    yoyChangeRate_SmartUsage: 28.7,
    yoyChangeRate_Collaboration: 32.1,
    detailByRegion: '马尾区: 440起；长乐区: 320起；福清市: 280起',
    detailByParkingType: '路内泊位: 250个；路外停车场: 150个；立体停车场: 40个',
    detailByOptimizationPoints: '商业区: 12个；住宅区: 6个；港口周边: 0个',
    detailByCollaborationDepartments: '交警部门: 7次；城管部门: 3次；社区: 2次',
    detailByRegion_YoY: '同比增长：马尾区+18.9%，长乐区+15.6%，福清市+22.1%',
    detailByParkingType_YoY: '同比增长：路内泊位+22.4%，路外停车场+18.9%，立体停车场+25.8%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+25.6%，住宅区+28.9%，港口周边+30.2%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+25.4%，城管部门+28.9%，社区+35.6%',
    detailByRegion_MoM: '环比增长：马尾区+12.5%，长乐区+10.2%，福清市+8.7%',
    detailByParkingType_MoM: '环比增长：路内泊位+8.7%，路外停车场+10.2%，立体停车场+12.8%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+18.9%，住宅区+22.1%，港口周边+25.6%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+22.4%，城管部门+25.8%，社区+28.9%',
  },
  {
    areaName: '长乐区',
    quarterlyIllegalParkingCases: 320,
    quarterlyPublicParkingSupplyDemandAnalysis: 81.3,
    quarterlyParkingSpaceOptimizationAdjustment: 15,
    quarterlySmartParkingUsageRate: 70.8,
    quarterlyCrossDepartmentParkingManagementCollaboration: 10,
    momChangeRate_IllegalCases: 5.6,
    momChangeRate_SupplyDemand: 4.3,
    momChangeRate_Optimization: 4.3,
    momChangeRate_SmartUsage: 3.2,
    momChangeRate_Collaboration: 3.2,
    yoyChangeRate_IllegalCases: 15.6,
    yoyChangeRate_SupplyDemand: 18.9,
    yoyChangeRate_Optimization: 22.1,
    yoyChangeRate_SmartUsage: 25.4,
    yoyChangeRate_Collaboration: 28.7,
    detailByRegion: '长乐区: 320起；马尾区: 440起；连江县: 250起',
    detailByParkingType: '路内泊位: 180个；路外停车场: 120个；立体停车场: 20个',
    detailByOptimizationPoints: '商业区: 9个；住宅区: 4个；市场周边: 2个',
    detailByCollaborationDepartments: '交警部门: 6次；城管部门: 2次；社区: 2次',
    detailByRegion_YoY: '同比增长：长乐区+15.6%，马尾区+18.9%，连江县+22.1%',
    detailByParkingType_YoY: '同比增长：路内泊位+18.9%，路外停车场+15.4%，立体停车场+22.8%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+20.1%，住宅区+25.4%，市场周边+28.9%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+22.4%，城管部门+25.8%，社区+28.9%',
    detailByRegion_MoM: '环比增长：长乐区+5.6%，马尾区+4.3%，连江县+3.2%',
    detailByParkingType_MoM: '环比增长：路内泊位+3.2%，路外停车场+4.3%，立体停车场+5.6%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+4.3%，住宅区+5.6%，市场周边+6.9%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+5.6%，城管部门+6.9%，社区+8.2%',
  },
  {
    areaName: '福清市',
    quarterlyIllegalParkingCases: 280,
    quarterlyPublicParkingSupplyDemandAnalysis: 83.1,
    quarterlyParkingSpaceOptimizationAdjustment: 12,
    quarterlySmartParkingUsageRate: 72.4,
    quarterlyCrossDepartmentParkingManagementCollaboration: 9,
    momChangeRate_IllegalCases: -1.8,
    momChangeRate_SupplyDemand: 2.1,
    momChangeRate_Optimization: 1.5,
    momChangeRate_SmartUsage: 1.5,
    momChangeRate_Collaboration: 1.5,
    yoyChangeRate_IllegalCases: 12.1,
    yoyChangeRate_SupplyDemand: 15.4,
    yoyChangeRate_Optimization: 18.6,
    yoyChangeRate_SmartUsage: 20.2,
    yoyChangeRate_Collaboration: 22.8,
    detailByRegion: '福清市: 280起；长乐区: 320起；闽侯县: 220起',
    detailByParkingType: '路内泊位: 160个；路外停车场: 90个；立体停车场: 30个',
    detailByOptimizationPoints: '商业区: 8个；住宅区: 3个；景区周边: 1个',
    detailByCollaborationDepartments: '交警部门: 5次；城管部门: 2次；社区: 2次',
    detailByRegion_YoY: '同比增长：福清市+12.1%，长乐区+15.4%，闽侯县+18.6%',
    detailByParkingType_YoY: '同比增长：路内泊位+15.4%，路外停车场+18.6%，立体停车场+22.8%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+18.6%，住宅区+22.8%，景区周边+25.1%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+20.1%，城管部门+22.4%，社区+25.6%',
    detailByRegion_MoM: '环比增长：福清市-1.8%，长乐区+2.1%，闽侯县+1.5%',
    detailByParkingType_MoM: '环比增长：路内泊位+1.5%，路外停车场+1.5%，立体停车场+1.5%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+1.5%，住宅区+1.5%，景区周边+1.5%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+1.5%，城管部门+1.5%，社区+1.5%',
  },
  {
    areaName: '连江县',
    quarterlyIllegalParkingCases: 250,
    quarterlyPublicParkingSupplyDemandAnalysis: 77.9,
    quarterlyParkingSpaceOptimizationAdjustment: 14,
    quarterlySmartParkingUsageRate: 68.7,
    quarterlyCrossDepartmentParkingManagementCollaboration: 8,
    momChangeRate_IllegalCases: 8.3,
    momChangeRate_SupplyDemand: 6.7,
    momChangeRate_Optimization: 5.2,
    momChangeRate_SmartUsage: 4.8,
    momChangeRate_Collaboration: 5.2,
    yoyChangeRate_IllegalCases: 18.9,
    yoyChangeRate_SupplyDemand: 22.1,
    yoyChangeRate_Optimization: 25.4,
    yoyChangeRate_SmartUsage: 28.7,
    yoyChangeRate_Collaboration: 32.1,
    detailByRegion: '连江县: 250起；福清市: 280起；闽侯县: 220起',
    detailByParkingType: '路内泊位: 140个；路外停车场: 80个；立体停车场: 30个',
    detailByOptimizationPoints: '商业区: 7个；住宅区: 4个；码头周边: 3个',
    detailByCollaborationDepartments: '交警部门: 4次；城管部门: 2次；社区: 2次',
    detailByRegion_YoY: '同比增长：连江县+18.9%，福清市+22.1%，闽侯县+25.4%',
    detailByParkingType_YoY: '同比增长：路内泊位+22.1%，路外停车场+18.9%，立体停车场+25.4%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+22.4%，住宅区+25.8%，码头周边+28.9%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+22.8%，城管部门+25.6%，社区+28.9%',
    detailByRegion_MoM: '环比增长：连江县+8.3%，福清市+6.7%，闽侯县+5.2%',
    detailByParkingType_MoM: '环比增长：路内泊位+4.8%，路外停车场+5.2%，立体停车场+6.9%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+5.2%，住宅区+6.9%，码头周边+8.2%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+5.2%，城管部门+6.9%，社区+8.2%',
  },
  {
    areaName: '闽侯县',
    quarterlyIllegalParkingCases: 220,
    quarterlyPublicParkingSupplyDemandAnalysis: 80.4,
    quarterlyParkingSpaceOptimizationAdjustment: 12,
    quarterlySmartParkingUsageRate: 71.2,
    quarterlyCrossDepartmentParkingManagementCollaboration: 7,
    momChangeRate_IllegalCases: 3.4,
    momChangeRate_SupplyDemand: 2.8,
    momChangeRate_Optimization: 2.1,
    momChangeRate_SmartUsage: 2.1,
    momChangeRate_Collaboration: 2.1,
    yoyChangeRate_IllegalCases: 15.4,
    yoyChangeRate_SupplyDemand: 18.6,
    yoyChangeRate_Optimization: 20.2,
    yoyChangeRate_SmartUsage: 22.8,
    yoyChangeRate_Collaboration: 25.4,
    detailByRegion: '闽侯县: 220起；连江县: 250起；罗源县: 180起',
    detailByParkingType: '路内泊位: 120个；路外停车场: 70个；立体停车场: 30个',
    detailByOptimizationPoints: '商业区: 6个；住宅区: 3个；工业园周边: 3个',
    detailByCollaborationDepartments: '交警部门: 4次；城管部门: 2次；社区: 1次',
    detailByRegion_YoY: '同比增长：闽侯县+15.4%，连江县+18.6%，罗源县+20.2%',
    detailByParkingType_YoY: '同比增长：路内泊位+18.6%，路外停车场+20.2%，立体停车场+22.8%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+20.2%，住宅区+22.8%，工业园周边+25.4%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+22.8%，城管部门+25.4%，社区+28.9%',
    detailByRegion_MoM: '环比增长：闽侯县+3.4%，连江县+2.8%，罗源县+2.1%',
    detailByParkingType_MoM: '环比增长：路内泊位+2.1%，路外停车场+2.1%，立体停车场+2.1%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+2.1%，住宅区+2.1%，工业园周边+2.1%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+2.1%，城管部门+2.1%，社区+2.1%',
  },
  {
    areaName: '罗源县',
    quarterlyIllegalParkingCases: 180,
    quarterlyPublicParkingSupplyDemandAnalysis: 75.2,
    quarterlyParkingSpaceOptimizationAdjustment: 10,
    quarterlySmartParkingUsageRate: 66.8,
    quarterlyCrossDepartmentParkingManagementCollaboration: 6,
    momChangeRate_IllegalCases: 6.7,
    momChangeRate_SupplyDemand: 5.9,
    momChangeRate_Optimization: 4.8,
    momChangeRate_SmartUsage: 4.8,
    momChangeRate_Collaboration: 4.8,
    yoyChangeRate_IllegalCases: 12.1,
    yoyChangeRate_SupplyDemand: 15.4,
    yoyChangeRate_Optimization: 18.6,
    yoyChangeRate_SmartUsage: 20.2,
    yoyChangeRate_Collaboration: 25.4,
    detailByRegion: '罗源县: 180起；闽侯县: 220起；永泰县: 150起',
    detailByParkingType: '路内泊位: 100个；路外停车场: 50个；立体停车场: 30个',
    detailByOptimizationPoints: '商业区: 5个；住宅区: 3个；景区周边: 2个',
    detailByCollaborationDepartments: '交警部门: 3次；城管部门: 2次；社区: 1次',
    detailByRegion_YoY: '同比增长：罗源县+12.1%，闽侯县+15.4%，永泰县+18.6%',
    detailByParkingType_YoY: '同比增长：路内泊位+15.4%，路外停车场+18.6%，立体停车场+22.8%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+18.6%，住宅区+22.8%，景区周边+25.1%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+20.1%，城管部门+22.4%，社区+25.6%',
    detailByRegion_MoM: '环比增长：罗源县+6.7%，闽侯县+5.9%，永泰县+4.8%',
    detailByParkingType_MoM: '环比增长：路内泊位+4.8%，路外停车场+4.8%，立体停车场+4.8%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+4.8%，住宅区+4.8%，景区周边+4.8%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+4.8%，城管部门+4.8%，社区+4.8%',
  },
  {
    areaName: '永泰县',
    quarterlyIllegalParkingCases: 150,
    quarterlyPublicParkingSupplyDemandAnalysis: 73.8,
    quarterlyParkingSpaceOptimizationAdjustment: 8,
    quarterlySmartParkingUsageRate: 64.5,
    quarterlyCrossDepartmentParkingManagementCollaboration: 5,
    momChangeRate_IllegalCases: 4.2,
    momChangeRate_SupplyDemand: 3.4,
    momChangeRate_Optimization: 2.7,
    momChangeRate_SmartUsage: 2.3,
    momChangeRate_Collaboration: 2.3,
    yoyChangeRate_IllegalCases: 10.8,
    yoyChangeRate_SupplyDemand: 13.2,
    yoyChangeRate_Optimization: 15.9,
    yoyChangeRate_SmartUsage: 17.3,
    yoyChangeRate_Collaboration: 19.7,
    detailByRegion: '永泰县: 150起；罗源县: 180起；平潭区: 120起',
    detailByParkingType: '路内泊位: 80个；路外停车场: 40个；立体停车场: 30个',
    detailByOptimizationPoints: '商业区: 4个；住宅区: 2个；景点周边: 2个',
    detailByCollaborationDepartments: '交警部门: 3次；城管部门: 1次；社区: 1次',
    detailByRegion_YoY: '同比增长：永泰县+10.8%，罗源县+13.2%，平潭区+15.9%',
    detailByParkingType_YoY: '同比增长：路内泊位+13.2%，路外停车场+15.9%，立体停车场+18.6%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+15.9%，住宅区+18.6%，景点周边+21.3%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+18.6%，城管部门+20.1%，社区+22.4%',
    detailByRegion_MoM: '环比增长：永泰县+4.2%，罗源县+3.4%，平潭区+2.7%',
    detailByParkingType_MoM: '环比增长：路内泊位+2.7%，路外停车场+2.7%，立体停车场+2.7%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+2.7%，住宅区+2.7%，景点周边+2.7%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+2.7%，城管部门+2.7%，社区+2.7%',
  },
  {
    areaName: '平潭区',
    quarterlyIllegalParkingCases: 120,
    quarterlyPublicParkingSupplyDemandAnalysis: 71.5,
    quarterlyParkingSpaceOptimizationAdjustment: 6,
    quarterlySmartParkingUsageRate: 62.3,
    quarterlyCrossDepartmentParkingManagementCollaboration: 4,
    momChangeRate_IllegalCases: 2.8,
    momChangeRate_SupplyDemand: 1.9,
    momChangeRate_Optimization: 1.4,
    momChangeRate_SmartUsage: 1.1,
    momChangeRate_Collaboration: 1.1,
    yoyChangeRate_IllegalCases: 8.5,
    yoyChangeRate_SupplyDemand: 10.8,
    yoyChangeRate_Optimization: 13.2,
    yoyChangeRate_SmartUsage: 14.7,
    yoyChangeRate_Collaboration: 16.2,
    detailByRegion: '平潭区: 120起；永泰县: 150起；莆田区: 90起',
    detailByParkingType: '路内泊位: 60个；路外停车场: 30个；立体停车场: 30个',
    detailByOptimizationPoints: '商业区: 3个；住宅区: 1个；机场周边: 2个',
    detailByCollaborationDepartments: '交警部门: 2次；城管部门: 1次；社区: 1次',
    detailByRegion_YoY: '同比增长：平潭区+8.5%，永泰县+10.8%，莆田区+12.1%',
    detailByParkingType_YoY: '同比增长：路内泊位+10.8%，路外停车场+12.1%，立体停车场+14.7%',
    detailByOptimizationPoints_YoY: '同比增长：商业区+12.1%，住宅区+14.7%，机场周边+16.2%',
    detailByCollaborationDepartments_YoY: '同比增长：交警部门+14.7%，城管部门+16.2%，社区+18.6%',
    detailByRegion_MoM: '环比增长：平潭区+2.8%，永泰县+1.9%，莆田区+1.4%',
    detailByParkingType_MoM: '环比增长：路内泊位+1.4%，路外停车场+1.4%，立体停车场+1.4%',
    detailByOptimizationPoints_MoM: '环比增长：商业区+1.4%，住宅区+1.4%，机场周边+1.4%',
    detailByCollaborationDepartments_MoM: '环比增长：交警部门+1.4%，城管部门+1.4%，社区+1.4%',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 季度违停案件及停车管理统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'quarterlyIllegalParkingCases',
      label: '季度违停案件总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度违停案件总量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterlyPublicParkingSupplyDemandAnalysis',
      label: '季度公共停车场供需平衡分析(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度公共停车场供需平衡分析(单位：%)',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterlyParkingSpaceOptimizationAdjustment',
      label: '季度泊位优化调整数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度泊位优化调整数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterlySmartParkingUsageRate',
      label: '季度智慧停车使用率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度智慧停车使用率(单位：%)',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterlyCrossDepartmentParkingManagementCollaboration',
      label: '季度跨部门停车管理协作次数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度跨部门停车管理协作次数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_IllegalCases',
      label: '违停案件总量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违停案件总量环比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_SupplyDemand',
      label: '供需平衡分析环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入供需平衡分析环比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_Optimization',
      label: '泊位优化调整数量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入泊位优化调整数量环比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_SmartUsage',
      label: '智慧停车使用率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入智慧停车使用率环比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_Collaboration',
      label: '跨部门协作次数环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入跨部门协作次数环比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_IllegalCases',
      label: '违停案件总量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违停案件总量同比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_SupplyDemand',
      label: '供需平衡分析同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入供需平衡分析同比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_Optimization',
      label: '泊位优化调整数量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入泊位优化调整数量同比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_SmartUsage',
      label: '智慧停车使用率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入智慧停车使用率同比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_Collaboration',
      label: '跨部门协作次数同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入跨部门协作次数同比变化率(单位：%)',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRegion',
      label: '按区域拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按区域拆分的季度违停案件及管理数据',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByParkingType',
      label: '按停车场类型拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按停车场类型拆分的季度数据（路内泊位、路外停车场、立体停车场）',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByOptimizationPoints',
      label: '按泊位优化点位拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按泊位优化点位拆分的季度数据（商业区、住宅区、特殊区域）',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByCollaborationDepartments',
      label: '按协作部门拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按协作部门拆分的季度数据',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRegion_YoY',
      label: '区域数据同比增长分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入各区域数据同比增长分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByParkingType_YoY',
      label: '停车场类型数据同比增长分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入各停车场类型数据同比增长分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByOptimizationPoints_YoY',
      label: '泊位优化点位数据同比增长分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入各泊位优化点位数据同比增长分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByCollaborationDepartments_YoY',
      label: '协作部门数据同比增长分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入各协作部门数据同比增长分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRegion_MoM',
      label: '区域数据环比增长分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入各区域数据环比增长分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByParkingType_MoM',
      label: '停车场类型数据环比增长分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入各停车场类型数据环比增长分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByOptimizationPoints_MoM',
      label: '泊位优化点位数据环比增长分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入各泊位优化点位数据环比增长分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByCollaborationDepartments_MoM',
      label: '协作部门数据环比增长分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入各协作部门数据环比增长分析结果',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 季度违停案件及停车管理统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'quarterlyIllegalParkingCases',
      title: '季度违停案件总量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'quarterlyPublicParkingSupplyDemandAnalysis',
      title: '季度公共停车场供需平衡分析(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'quarterlyParkingSpaceOptimizationAdjustment',
      title: '季度泊位优化调整数量',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'quarterlySmartParkingUsageRate',
      title: '季度智慧停车使用率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'quarterlyCrossDepartmentParkingManagementCollaboration',
      title: '季度跨部门停车管理协作次数',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'momChangeRate_IllegalCases',
      title: '违停案件总量环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'momChangeRate_SupplyDemand',
      title: '供需平衡分析环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'momChangeRate_Optimization',
      title: '泊位优化调整数量环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'momChangeRate_SmartUsage',
      title: '智慧停车使用率环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'momChangeRate_Collaboration',
      title: '跨部门协作次数环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_IllegalCases',
      title: '违停案件总量同比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_SupplyDemand',
      title: '供需平衡分析同比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_Optimization',
      title: '泊位优化调整数量同比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_SmartUsage',
      title: '智慧停车使用率同比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_Collaboration',
      title: '跨部门协作次数同比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'detailByRegion',
      title: '按区域拆分明细',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'detailByParkingType',
      title: '按停车场类型拆分明细',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'detailByOptimizationPoints',
      title: '按泊位优化点位拆分明细',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'detailByCollaborationDepartments',
      title: '按协作部门拆分明细',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByRegion_YoY',
      title: '区域同比增长分析',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByParkingType_YoY',
      title: '停车场类型同比增长分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByOptimizationPoints_YoY',
      title: '泊位优化点位同比增长分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByCollaborationDepartments_YoY',
      title: '协作部门同比增长分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByRegion_MoM',
      title: '区域环比增长分析',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailByParkingType_MoM',
      title: '停车场类型环比增长分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByOptimizationPoints_MoM',
      title: '泊位优化点位环比增长分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByCollaborationDepartments_MoM',
      title: '协作部门环比增长分析',
      minWidth: 200,
      sortable: false,
    },
  ];
}

