/** 表格初始数据 - 改造为停车管理周度统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    weeklyIllegalParkingCount: 245,
    weeklyPublicParkingAvgUsageRate: 78.5,
    weeklyBerthTurnoverRate: 3.2,
    weeklyNonMotorVehicleParkingRate: 92.3,
    weeklyKeyAreaViolationControlRate: 88.6,
    momChangeRate_IllegalParkingCount: 5.2,
    momChangeRate_PublicParkingUsage: 2.1,
    momChangeRate_BerthTurnover: -0.3,
    momChangeRate_NonMotorVehicleParking: 1.5,
    momChangeRate_KeyAreaControl: -1.2,
    yoyChangeRate_IllegalParkingCount: -8.5,
    yoyChangeRate_PublicParkingUsage: 4.3,
    yoyChangeRate_BerthTurnover: 0.8,
    yoyChangeRate_NonMotorVehicleParking: 3.2,
    yoyChangeRate_KeyAreaControl: -2.7,
    detailByRegion: '鼓楼区: 245起；台江区: 198起；仓山区: 176起',
    detailByParkingLot: '鼓楼公共停车场: 65.2%；五一广场停车场: 82.1%；东街口停车场: 91.5%',
    detailByBerthType: '路内泊位: 3.5次/天；路外泊位: 2.8次/天；专用泊位: 2.1次/天',
    detailByTimeSlot: '早高峰: 91.2%；午间: 94.5%；晚高峰: 89.7%；夜间: 90.3%',
    detailByAnalysis: '同比: -8.5%；环比: +5.2%；重点区域管控率下降1.2%',
  },
  {
    areaName: '台江区',
    weeklyIllegalParkingCount: 198,
    weeklyPublicParkingAvgUsageRate: 74.2,
    weeklyBerthTurnoverRate: 3.5,
    weeklyNonMotorVehicleParkingRate: 90.8,
    weeklyKeyAreaViolationControlRate: 85.4,
    momChangeRate_IllegalParkingCount: 3.8,
    momChangeRate_PublicParkingUsage: 1.5,
    momChangeRate_BerthTurnover: 0.6,
    momChangeRate_NonMotorVehicleParking: 2.3,
    momChangeRate_KeyAreaControl: -0.9,
    yoyChangeRate_IllegalParkingCount: -6.2,
    yoyChangeRate_PublicParkingUsage: 3.7,
    yoyChangeRate_BerthTurnover: 1.2,
    yoyChangeRate_NonMotorVehicleParking: 4.1,
    yoyChangeRate_KeyAreaControl: -1.8,
    detailByRegion: '台江区: 198起；仓山区: 176起；晋安区: 152起',
    detailByParkingLot: '中亭街停车场: 71.3%；万象城停车场: 68.9%；茶亭停车场: 77.5%',
    detailByBerthType: '路内泊位: 3.8次/天；路外泊位: 3.0次/天；专用泊位: 2.4次/天',
    detailByTimeSlot: '早高峰: 89.5%；午间: 92.1%；晚高峰: 88.3%；夜间: 89.7%',
    detailByAnalysis: '同比: -6.2%；环比: +3.8%；非机动车规范停放率提升2.3%',
  },
  {
    areaName: '仓山区',
    weeklyIllegalParkingCount: 176,
    weeklyPublicParkingAvgUsageRate: 72.8,
    weeklyBerthTurnoverRate: 3.1,
    weeklyNonMotorVehicleParkingRate: 91.5,
    weeklyKeyAreaViolationControlRate: 86.9,
    momChangeRate_IllegalParkingCount: 2.5,
    momChangeRate_PublicParkingUsage: 3.2,
    momChangeRate_BerthTurnover: -0.2,
    momChangeRate_NonMotorVehicleParking: 1.8,
    momChangeRate_KeyAreaControl: 0.5,
    yoyChangeRate_IllegalParkingCount: -7.8,
    yoyChangeRate_PublicParkingUsage: 5.1,
    yoyChangeRate_BerthTurnover: 0.5,
    yoyChangeRate_NonMotorVehicleParking: 3.9,
    yoyChangeRate_KeyAreaControl: -1.4,
    detailByRegion: '仓山区: 176起；晋安区: 152起；马尾区: 98起',
    detailByParkingLot: '金山停车场: 69.4%；奥体中心停车场: 73.2%；仓山万达停车场: 81.7%',
    detailByBerthType: '路内泊位: 3.3次/天；路外泊位: 2.7次/天；专用泊位: 2.2次/天',
    detailByTimeSlot: '早高峰: 90.3%；午间: 93.0%；晚高峰: 89.1%；夜间: 90.5%',
    detailByAnalysis: '同比: -7.8%；环比: +2.5%；公共停车场使用率上升3.2%',
  },
  {
    areaName: '晋安区',
    weeklyIllegalParkingCount: 152,
    weeklyPublicParkingAvgUsageRate: 70.5,
    weeklyBerthTurnoverRate: 2.9,
    weeklyNonMotorVehicleParkingRate: 89.7,
    weeklyKeyAreaViolationControlRate: 84.2,
    momChangeRate_IllegalParkingCount: -1.2,
    momChangeRate_PublicParkingUsage: 2.8,
    momChangeRate_BerthTurnover: -0.5,
    momChangeRate_NonMotorVehicleParking: 0.9,
    momChangeRate_KeyAreaControl: -1.5,
    yoyChangeRate_IllegalParkingCount: -5.4,
    yoyChangeRate_PublicParkingUsage: 4.6,
    yoyChangeRate_BerthTurnover: 0.3,
    yoyChangeRate_NonMotorVehicleParking: 2.8,
    yoyChangeRate_KeyAreaControl: -2.3,
    detailByRegion: '晋安区: 152起；马尾区: 98起；长乐区: 67起',
    detailByParkingLot: '东二环停车场: 66.8%；鼓山停车场: 70.1%；火车站停车场: 79.4%',
    detailByBerthType: '路内泊位: 3.1次/天；路外泊位: 2.5次/天；专用泊位: 2.0次/天',
    detailByTimeSlot: '早高峰: 88.7%；午间: 91.2%；晚高峰: 87.5%；夜间: 89.0%',
    detailByAnalysis: '同比: -5.4%；环比: -1.2%；重点区域管控率下降1.5%',
  },
  {
    areaName: '马尾区',
    weeklyIllegalParkingCount: 98,
    weeklyPublicParkingAvgUsageRate: 68.3,
    weeklyBerthTurnoverRate: 2.7,
    weeklyNonMotorVehicleParkingRate: 88.4,
    weeklyKeyAreaViolationControlRate: 82.7,
    momChangeRate_IllegalParkingCount: 7.5,
    momChangeRate_PublicParkingUsage: 4.2,
    momChangeRate_BerthTurnover: 1.1,
    momChangeRate_NonMotorVehicleParking: 2.7,
    momChangeRate_KeyAreaControl: 1.8,
    yoyChangeRate_IllegalParkingCount: -3.9,
    yoyChangeRate_PublicParkingUsage: 6.3,
    yoyChangeRate_BerthTurnover: 1.9,
    yoyChangeRate_NonMotorVehicleParking: 5.2,
    yoyChangeRate_KeyAreaControl: -0.7,
    detailByRegion: '马尾区: 98起；长乐区: 67起；福清市: 52起',
    detailByParkingLot: '马尾造船厂停车场: 63.5%；自贸区停车场: 66.2%；江滨停车场: 72.8%',
    detailByBerthType: '路内泊位: 2.9次/天；路外泊位: 2.3次/天；专用泊位: 1.9次/天',
    detailByTimeSlot: '早高峰: 87.2%；午间: 89.8%；晚高峰: 86.1%；夜间: 88.3%',
    detailByAnalysis: '同比: -3.9%；环比: +7.5%；违停案件总量上升明显',
  },
  {
    areaName: '长乐区',
    weeklyIllegalParkingCount: 67,
    weeklyPublicParkingAvgUsageRate: 65.7,
    weeklyBerthTurnoverRate: 2.5,
    weeklyNonMotorVehicleParkingRate: 87.6,
    weeklyKeyAreaViolationControlRate: 81.3,
    momChangeRate_IllegalParkingCount: 4.9,
    momChangeRate_PublicParkingUsage: 3.5,
    momChangeRate_BerthTurnover: 0.8,
    momChangeRate_NonMotorVehicleParking: 1.6,
    momChangeRate_KeyAreaControl: 1.2,
    yoyChangeRate_IllegalParkingCount: -2.7,
    yoyChangeRate_PublicParkingUsage: 5.8,
    yoyChangeRate_BerthTurnover: 1.5,
    yoyChangeRate_NonMotorVehicleParking: 4.3,
    yoyChangeRate_KeyAreaControl: -0.5,
    detailByRegion: '长乐区: 67起；福清市: 52起；连江县: 41起',
    detailByParkingLot: '长乐机场停车场: 70.2%；滨海新城停车场: 64.8%；首占停车场: 61.3%',
    detailByBerthType: '路内泊位: 2.7次/天；路外泊位: 2.1次/天；专用泊位: 1.8次/天',
    detailByTimeSlot: '早高峰: 86.5%；午间: 88.9%；晚高峰: 85.3%；夜间: 87.4%',
    detailByAnalysis: '同比: -2.7%；环比: +4.9%；泊位周转率小幅提升',
  },
  {
    areaName: '福清市',
    weeklyIllegalParkingCount: 52,
    weeklyPublicParkingAvgUsageRate: 63.2,
    weeklyBerthTurnoverRate: 2.3,
    weeklyNonMotorVehicleParkingRate: 86.9,
    weeklyKeyAreaViolationControlRate: 79.8,
    momChangeRate_IllegalParkingCount: -2.4,
    momChangeRate_PublicParkingUsage: 1.9,
    momChangeRate_BerthTurnover: -0.4,
    momChangeRate_NonMotorVehicleParking: 0.8,
    momChangeRate_KeyAreaControl: -1.1,
    yoyChangeRate_IllegalParkingCount: -1.5,
    yoyChangeRate_PublicParkingUsage: 4.7,
    yoyChangeRate_BerthTurnover: 1.1,
    yoyChangeRate_NonMotorVehicleParking: 3.6,
    yoyChangeRate_KeyAreaControl: -1.9,
    detailByRegion: '福清市: 52起；连江县: 41起；罗源县: 29起',
    detailByParkingLot: '福清万达停车场: 65.4%；龙田停车场: 60.8%；宏路停车场: 58.3%',
    detailByBerthType: '路内泊位: 2.5次/天；路外泊位: 2.0次/天；专用泊位: 1.7次/天',
    detailByTimeSlot: '早高峰: 85.8%；午间: 87.6%；晚高峰: 84.2%；夜间: 86.5%',
    detailByAnalysis: '同比: -1.5%；环比: -2.4%；非机动车规范停放率稳定',
  },
  {
    areaName: '连江县',
    weeklyIllegalParkingCount: 41,
    weeklyPublicParkingAvgUsageRate: 61.5,
    weeklyBerthTurnoverRate: 2.1,
    weeklyNonMotorVehicleParkingRate: 85.7,
    weeklyKeyAreaViolationControlRate: 78.4,
    momChangeRate_IllegalParkingCount: 6.2,
    momChangeRate_PublicParkingUsage: 3.8,
    momChangeRate_BerthTurnover: 0.9,
    momChangeRate_NonMotorVehicleParking: 2.1,
    momChangeRate_KeyAreaControl: 1.5,
    yoyChangeRate_IllegalParkingCount: -0.8,
    yoyChangeRate_PublicParkingUsage: 5.2,
    yoyChangeRate_BerthTurnover: 1.8,
    yoyChangeRate_NonMotorVehicleParking: 4.5,
    yoyChangeRate_KeyAreaControl: -0.3,
    detailByRegion: '连江县: 41起；罗源县: 29起；闽侯县: 23起',
    detailByParkingLot: '连江动车站停车场: 59.7%；贵安停车场: 62.4%；黄岐停车场: 56.8%',
    detailByBerthType: '路内泊位: 2.3次/天；路外泊位: 1.9次/天；专用泊位: 1.6次/天',
    detailByTimeSlot: '早高峰: 84.6%；午间: 86.3%；晚高峰: 83.5%；夜间: 85.2%',
    detailByAnalysis: '同比: -0.8%；环比: +6.2%；公共停车场使用率上升',
  },
  {
    areaName: '闽侯县',
    weeklyIllegalParkingCount: 23,
    weeklyPublicParkingAvgUsageRate: 58.9,
    weeklyBerthTurnoverRate: 1.9,
    weeklyNonMotorVehicleParkingRate: 84.3,
    weeklyKeyAreaViolationControlRate: 76.9,
    momChangeRate_IllegalParkingCount: 3.7,
    momChangeRate_PublicParkingUsage: 2.5,
    momChangeRate_BerthTurnover: 0.3,
    momChangeRate_NonMotorVehicleParking: 1.4,
    momChangeRate_KeyAreaControl: 0.9,
    yoyChangeRate_IllegalParkingCount: 0.5,
    yoyChangeRate_PublicParkingUsage: 4.1,
    yoyChangeRate_BerthTurnover: 1.2,
    yoyChangeRate_NonMotorVehicleParking: 3.3,
    yoyChangeRate_KeyAreaControl: -0.8,
    detailByRegion: '闽侯县: 23起；永泰县: 18起；闽清县: 14起',
    detailByParkingLot: '大学城停车场: 60.2%；上街停车场: 57.5%；甘蔗停车场: 55.1%',
    detailByBerthType: '路内泊位: 2.1次/天；路外泊位: 1.7次/天；专用泊位: 1.5次/天',
    detailByTimeSlot: '早高峰: 83.9%；午间: 85.1%；晚高峰: 82.7%；夜间: 84.0%',
    detailByAnalysis: '同比: +0.5%；环比: +3.7%；违停案件总量略有增加',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为停车管理周度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '180',
      rules: 'required',
    },
    {
      fieldName: 'weeklyIllegalParkingCount',
      label: '周违停案件总量',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入周违停案件总量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyPublicParkingAvgUsageRate',
      label: '周公共停车场平均使用率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入周公共停车场平均使用率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyBerthTurnoverRate',
      label: '周泊位周转率(次/天)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入周泊位周转率',
        min: 0,
        precision: 1,
        addonAfter: '次/天',
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyNonMotorVehicleParkingRate',
      label: '周非机动车规范停放率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入周非机动车规范停放率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyKeyAreaViolationControlRate',
      label: '周重点区域违停管控率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入周重点区域违停管控率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_IllegalParkingCount',
      label: '违停案件总量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_PublicParkingUsage',
      label: '公共停车场使用率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_BerthTurnover',
      label: '泊位周转率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_NonMotorVehicleParking',
      label: '非机动车规范停放率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_KeyAreaControl',
      label: '重点区域违停管控率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_IllegalParkingCount',
      label: '违停案件总量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_PublicParkingUsage',
      label: '公共停车场使用率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_BerthTurnover',
      label: '泊位周转率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_NonMotorVehicleParking',
      label: '非机动车规范停放率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_KeyAreaControl',
      label: '重点区域违停管控率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRegion',
      label: '按区域拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按区域拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByParkingLot',
      label: '按停车场拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按停车场拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByBerthType',
      label: '按泊位类型拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按泊位类型拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByTimeSlot',
      label: '按管控时段拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按管控时段拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByAnalysis',
      label: '同比/环比分析结果',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比/环比分析结果',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为停车管理周度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'weeklyIllegalParkingCount',
      title: '周违停案件总量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'weeklyPublicParkingAvgUsageRate',
      title: '周公共停车场平均使用率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'weeklyBerthTurnoverRate',
      title: '周泊位周转率(次/天)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'weeklyNonMotorVehicleParkingRate',
      title: '周非机动车规范停放率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'weeklyKeyAreaViolationControlRate',
      title: '周重点区域违停管控率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'momChangeRate_IllegalParkingCount',
      title: '违停案件总量环比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_PublicParkingUsage',
      title: '公共停车场使用率环比(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate_BerthTurnover',
      title: '泊位周转率环比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_NonMotorVehicleParking',
      title: '非机动车规范停放率环比(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'momChangeRate_KeyAreaControl',
      title: '重点区域违停管控率环比(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_IllegalParkingCount',
      title: '违停案件总量同比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_PublicParkingUsage',
      title: '公共停车场使用率同比(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_BerthTurnover',
      title: '泊位周转率同比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_NonMotorVehicleParking',
      title: '非机动车规范停放率同比(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_KeyAreaControl',
      title: '重点区域违停管控率同比(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'detailByRegion',
      title: '按区域拆分明细',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'detailByParkingLot',
      title: '按停车场拆分明细',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'detailByBerthType',
      title: '按泊位类型拆分明细',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'detailByTimeSlot',
      title: '按管控时段拆分明细',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'detailByAnalysis',
      title: '同比/环比分析结果',
      minWidth: 240,
      sortable: false,
    },
  ];
}
