export const pageConfig = {
  apiName: 'StationInfo',
  title: '场站信息',
  exportName: '场站信息数据.xlsx',
  nameField: 'name',
  primaryField: 'stationNo',
  toolbar: ['create', 'import', 'export'],
  rowActionMap: {
    未生效: ['enable', 'edit', 'detail'],
    已生效: ['disable', 'edit', 'detail'],
    已禁用: ['enable', 'detail'],
  },
  chart: {
    cards: [
      ['totalStation', '总场站数'],
      ['enableStation', '正常运营数', '已生效'],
      ['disableStation', '已禁用场站数', '已禁用'],
      ['spaceTotal', '总车位数'],
    ],
    bar: ['barData', 'name', 'stationCount', '各类型场站数量'],
    map: true,
  },
};

export const searchFields = [
  { field: 'name', label: '场站名称', type: 'input', required: false },
  {
    field: 'areaId',
    label: '所属区域',
    type: 'select',
    options: [],
    required: false,
    apiSource: 'AreaInfo',
  },
  {
    field: 'type',
    label: '场站类型',
    type: 'select',
    options: ['路内', '路外'],
    required: false,
  },
  {
    field: 'operateType',
    label: '运营类型',
    type: 'select',
    options: ['自营', '代运营'],
    required: false,
  },
  {
    field: 'serviceType',
    label: '服务类型',
    type: 'select',
    options: ['停车', '充电', '充停一体'],
    required: false,
  },
  {
    field: 'status',
    label: '状态',
    type: 'select',
    options: ['未生效', '已生效', '已禁用'],
    required: false,
  },
];

export const formFields = [
  { field: 'stationNo', label: '场站编号', type: 'input', required: true },
  { field: 'name', label: '场站名称', type: 'input', required: true },
  {
    field: 'areaId',
    label: '所属区域',
    type: 'select',
    options: [],
    required: true,
    apiSource: 'AreaInfo',
  },
  {
    field: 'type',
    label: '场站类型',
    type: 'select',
    options: ['路内', '路外'],
    required: true,
  },
  { field: 'address', label: '详细地址', type: 'input', required: true },
  { field: 'lat', label: '纬度', type: 'number', required: false },
  { field: 'lng', label: '经度', type: 'number', required: false },
  { field: 'spaceTotal', label: '总车位数', type: 'number', required: true },
  { field: 'userId', label: '负责人', type: 'number', required: false },
  { field: 'phone', label: '联系电话', type: 'input', required: false },
  {
    field: 'operateType',
    label: '运营类型',
    type: 'select',
    options: ['自营', '代运营'],
    required: true,
  },
  {
    field: 'serviceType',
    label: '服务类型',
    type: 'select',
    options: ['停车', '充电', '充停一体'],
    required: true,
  },
  { field: 'feeStandard', label: '收费标准', type: 'input', required: false },
  {
    field: 'linkDebt',
    label: '联动追缴',
    type: 'select',
    options: ['是', '否'],
    required: true,
  },
  { field: 'remark', label: '备注', type: 'textarea', required: false },
  { field: 'reserve1', label: '备用字段1', type: 'input', required: false },
  { field: 'reserve2', label: '备用字段2', type: 'input', required: false },
];

export const tableColumns = [
  { field: 'stationNo', label: '场站编号', minWidth: 140, drillType: 'detail' },
  { field: 'name', label: '场站名称', minWidth: 180, drillType: 'filter' },
  {
    field: 'areaId',
    label: '所属区域',
    minWidth: 140,
    drillType: 'dialog',
    drillLabel: '所属区域详情',
  },
  { field: 'type', label: '场站类型', minWidth: 120, drillType: 'filter' },
  { field: 'address', label: '详细地址', minWidth: 220 },
  {
    field: 'spaceTotal',
    label: '总车位数',
    minWidth: 140,
    drillType: 'dialog',
    drillLabel: '该场站车位列表',
  },
  { field: 'userId', label: '负责人', minWidth: 140, drillType: 'filter' },
  { field: 'phone', label: '联系电话', minWidth: 150 },
  {
    field: 'operateType',
    label: '运营类型',
    minWidth: 120,
    drillType: 'filter',
  },
  {
    field: 'serviceType',
    label: '服务类型',
    minWidth: 120,
    drillType: 'filter',
  },
  { field: 'feeStandard', label: '收费标准', minWidth: 150 },
  { field: 'linkDebt', label: '联动追缴', minWidth: 120, drillType: 'filter' },
  { field: 'deviceCount', label: '设备数', minWidth: 100 },
  { field: 'spaceCount', label: '车位数', minWidth: 100 },
  { field: 'status', label: '状态', minWidth: 120, drillType: 'filter' },
  { field: 'remark', label: '备注', minWidth: 150 },
  { field: 'creator', label: '创建者', minWidth: 120, drillType: 'filter' },
  {
    field: 'createTime',
    label: '创建时间',
    minWidth: 180,
    formatter: 'formatDateTime',
  },
  { field: 'updater', label: '更新者', minWidth: 120, drillType: 'filter' },
  {
    field: 'updateTime',
    label: '更新时间',
    minWidth: 180,
    formatter: 'formatDateTime',
  },
];

export const detailFields = [
  { key: 'stationNo', label: '场站编号', section: '基础信息' },
  { key: 'name', label: '场站名称', section: '基础信息' },
  { key: 'areaId', label: '所属区域ID', section: '基础信息' },
  { key: 'type', label: '场站类型', section: '基础信息' },
  { key: 'status', label: '状态', section: '基础信息' },
  { key: 'address', label: '详细地址', section: '区位信息' },
  { key: 'lat', label: '纬度', section: '区位信息' },
  { key: 'lng', label: '经度', section: '区位信息' },
  { key: 'spaceTotal', label: '总车位数', section: '运营配置' },
  { key: 'userId', label: '负责人', section: '运营配置' },
  { key: 'phone', label: '联系电话', section: '运营配置' },
  { key: 'operateType', label: '运营类型', section: '运营配置' },
  { key: 'serviceType', label: '服务类型', section: '运营配置' },
  { key: 'feeStandard', label: '收费标准', section: '运营配置' },
  { key: 'linkDebt', label: '联动追缴', section: '运营配置' },
  { key: 'deviceCount', label: '设备数', section: '运营配置' },
  { key: 'spaceCount', label: '车位数', section: '运营配置' },
  { key: 'remark', label: '备注', section: '运营配置' },
  { key: 'creator', label: '创建者', section: '审计信息' },
  { key: 'createTime', label: '创建时间', section: '审计信息' },
  { key: 'updater', label: '更新者', section: '审计信息' },
  { key: 'updateTime', label: '更新时间', section: '审计信息' },
];
