/** 表格初始数据 - 季度乱贴乱画治理统计分析数据 */
export const dataList = () => [
  {
    regionName: '鼓楼区',
    quarterIllegalPostingCleanupTotal: 1560,
    quarterIllegalNumberDisposalRate: 94.5,
    quarterKeyAreaSpecialCleanupCount: 45,
    quarterAntiStickingFacilityInstallationCount: 120,
    quarterIllegalPostingComplaintHandlingRate: 89.2,
    momChangeRate_IllegalPostingCleanupTotal: 12.8,
    yoyChangeRate_IllegalPostingCleanupTotal: 18.5,
    momChangeRate_IllegalNumberDisposalRate: 3.2,
    yoyChangeRate_IllegalNumberDisposalRate: 5.8,
    momChangeRate_KeyAreaSpecialCleanupCount: 15.6,
    yoyChangeRate_KeyAreaSpecialCleanupCount: 22.3,
    momChangeRate_AntiStickingFacilityInstallationCount: 8.9,
    yoyChangeRate_AntiStickingFacilityInstallationCount: 12.1,
    momChangeRate_IllegalPostingComplaintHandlingRate: -2.1,
    yoyChangeRate_IllegalPostingComplaintHandlingRate: 3.4,
    quarterDetailByRegion: '鼓楼区: 1560次；台江区: 1240次；仓山区: 980次',
    quarterDetailByCleanupType: '主干道专项: 890次；背街小巷: 450次；商业区: 220次',
    quarterDetailByFacilityLocation: '交通枢纽: 45个；商业中心: 35个；居民区: 40个',
    quarterDetailByComplaintType: '市民投诉: 320件；巡查发现: 1240件；上级督办: 0件',
    quarterComparisonByRegion: '环比: +12.8%；同比: +18.5%',
    quarterComparisonByCleanupType: '环比: +15.6%；同比: +22.3%',
    quarterComparisonByFacilityLocation: '环比: +8.9%；同比: +12.1%',
    quarterComparisonByComplaintType: '环比: -2.1%；同比: +3.4%',
    quarterStatisticsPeriod: '2024-Q2 (4月-6月)',
  },
  {
    regionName: '台江区',
    quarterIllegalPostingCleanupTotal: 1240,
    quarterIllegalNumberDisposalRate: 92.3,
    quarterKeyAreaSpecialCleanupCount: 38,
    quarterAntiStickingFacilityInstallationCount: 95,
    quarterIllegalPostingComplaintHandlingRate: 87.6,
    momChangeRate_IllegalPostingCleanupTotal: 8.5,
    yoyChangeRate_IllegalPostingCleanupTotal: 15.2,
    momChangeRate_IllegalNumberDisposalRate: 2.8,
    yoyChangeRate_IllegalNumberDisposalRate: 4.2,
    momChangeRate_KeyAreaSpecialCleanupCount: 12.4,
    yoyChangeRate_KeyAreaSpecialCleanupCount: 18.9,
    momChangeRate_AntiStickingFacilityInstallationCount: 6.7,
    yoyChangeRate_AntiStickingFacilityInstallationCount: 9.8,
    momChangeRate_IllegalPostingComplaintHandlingRate: -1.5,
    yoyChangeRate_IllegalPostingComplaintHandlingRate: 2.8,
    quarterDetailByRegion: '鼓楼区: 1560次；台江区: 1240次；仓山区: 980次',
    quarterDetailByCleanupType: '主干道专项: 680次；背街小巷: 380次；商业区: 180次',
    quarterDetailByFacilityLocation: '交通枢纽: 32个；商业中心: 28个；居民区: 35个',
    quarterDetailByComplaintType: '市民投诉: 280件；巡查发现: 960件；上级督办: 0件',
    quarterComparisonByRegion: '环比: +8.5%；同比: +15.2%',
    quarterComparisonByCleanupType: '环比: +12.4%；同比: +18.9%',
    quarterComparisonByFacilityLocation: '环比: +6.7%；同比: +9.8%',
    quarterComparisonByComplaintType: '环比: -1.5%；同比: +2.8%',
    quarterStatisticsPeriod: '2024-Q2 (4月-6月)',
  },
  {
    regionName: '仓山区',
    quarterIllegalPostingCleanupTotal: 980,
    quarterIllegalNumberDisposalRate: 89.7,
    quarterKeyAreaSpecialCleanupCount: 29,
    quarterAntiStickingFacilityInstallationCount: 76,
    quarterIllegalPostingComplaintHandlingRate: 85.3,
    momChangeRate_IllegalPostingCleanupTotal: 5.2,
    yoyChangeRate_IllegalPostingCleanupTotal: 12.8,
    momChangeRate_IllegalNumberDisposalRate: 1.9,
    yoyChangeRate_IllegalNumberDisposalRate: 3.1,
    momChangeRate_KeyAreaSpecialCleanupCount: 9.8,
    yoyChangeRate_KeyAreaSpecialCleanupCount: 15.4,
    momChangeRate_AntiStickingFacilityInstallationCount: 4.5,
    yoyChangeRate_AntiStickingFacilityInstallationCount: 7.2,
    momChangeRate_IllegalPostingComplaintHandlingRate: -0.8,
    yoyChangeRate_IllegalPostingComplaintHandlingRate: 2.1,
    quarterDetailByRegion: '鼓楼区: 1560次；台江区: 1240次；仓山区: 980次',
    quarterDetailByCleanupType: '主干道专项: 520次；背街小巷: 290次；商业区: 170次',
    quarterDetailByFacilityLocation: '交通枢纽: 25个；商业中心: 22个；居民区: 29个',
    quarterDetailByComplaintType: '市民投诉: 240件；巡查发现: 740件；上级督办: 0件',
    quarterComparisonByRegion: '环比: +5.2%；同比: +12.8%',
    quarterComparisonByCleanupType: '环比: +9.8%；同比: +15.4%',
    quarterComparisonByFacilityLocation: '环比: +4.5%；同比: +7.2%',
    quarterComparisonByComplaintType: '环比: -0.8%；同比: +2.1%',
    quarterStatisticsPeriod: '2024-Q2 (4月-6月)',
  },
  {
    regionName: '晋安区',
    quarterIllegalPostingCleanupTotal: 860,
    quarterIllegalNumberDisposalRate: 87.9,
    quarterKeyAreaSpecialCleanupCount: 25,
    quarterAntiStickingFacilityInstallationCount: 65,
    quarterIllegalPostingComplaintHandlingRate: 83.1,
    momChangeRate_IllegalPostingCleanupTotal: 3.8,
    yoyChangeRate_IllegalPostingCleanupTotal: 10.5,
    momChangeRate_IllegalNumberDisposalRate: 1.2,
    yoyChangeRate_IllegalNumberDisposalRate: 2.5,
    momChangeRate_KeyAreaSpecialCleanupCount: 7.2,
    yoyChangeRate_KeyAreaSpecialCleanupCount: 12.8,
    momChangeRate_AntiStickingFacilityInstallationCount: 3.2,
    yoyChangeRate_AntiStickingFacilityInstallationCount: 5.8,
    momChangeRate_IllegalPostingComplaintHandlingRate: -0.3,
    yoyChangeRate_IllegalPostingComplaintHandlingRate: 1.6,
    quarterDetailByRegion: '晋安区: 860次；马尾区: 420次；长乐区: 380次',
    quarterDetailByCleanupType: '主干道专项: 450次；背街小巷: 240次；商业区: 170次',
    quarterDetailByFacilityLocation: '交通枢纽: 20个；商业中心: 18个；居民区: 27个',
    quarterDetailByComplaintType: '市民投诉: 190件；巡查发现: 670件；上级督办: 0件',
    quarterComparisonByRegion: '环比: +3.8%；同比: +10.5%',
    quarterComparisonByCleanupType: '环比: +7.2%；同比: +12.8%',
    quarterComparisonByFacilityLocation: '环比: +3.2%；同比: +5.8%',
    quarterComparisonByComplaintType: '环比: -0.3%；同比: +1.6%',
    quarterStatisticsPeriod: '2024-Q2 (4月-6月)',
  },
  {
    regionName: '马尾区',
    quarterIllegalPostingCleanupTotal: 420,
    quarterIllegalNumberDisposalRate: 85.4,
    quarterKeyAreaSpecialCleanupCount: 18,
    quarterAntiStickingFacilityInstallationCount: 42,
    quarterIllegalPostingComplaintHandlingRate: 80.7,
    momChangeRate_IllegalPostingCleanupTotal: 2.1,
    yoyChangeRate_IllegalPostingCleanupTotal: 8.3,
    momChangeRate_IllegalNumberDisposalRate: 0.8,
    yoyChangeRate_IllegalNumberDisposalRate: 1.9,
    momChangeRate_KeyAreaSpecialCleanupCount: 5.4,
    yoyChangeRate_KeyAreaSpecialCleanupCount: 10.2,
    momChangeRate_AntiStickingFacilityInstallationCount: 2.1,
    yoyChangeRate_AntiStickingFacilityInstallationCount: 4.1,
    momChangeRate_IllegalPostingComplaintHandlingRate: 0.1,
    yoyChangeRate_IllegalPostingComplaintHandlingRate: 1.2,
    quarterDetailByRegion: '晋安区: 860次；马尾区: 420次；长乐区: 380次',
    quarterDetailByCleanupType: '主干道专项: 280次；背街小巷: 100次；商业区: 40次',
    quarterDetailByFacilityLocation: '交通枢纽: 12个；商业中心: 10个；居民区: 20个',
    quarterDetailByComplaintType: '市民投诉: 120件；巡查发现: 300件；上级督办: 0件',
    quarterComparisonByRegion: '环比: +2.1%；同比: +8.3%',
    quarterComparisonByCleanupType: '环比: +5.4%；同比: +10.2%',
    quarterComparisonByFacilityLocation: '环比: +2.1%；同比: +4.1%',
    quarterComparisonByComplaintType: '环比: +0.1%；同比: +1.2%',
    quarterStatisticsPeriod: '2024-Q2 (4月-6月)',
  },
  {
    regionName: '长乐区',
    quarterIllegalPostingCleanupTotal: 380,
    quarterIllegalNumberDisposalRate: 83.2,
    quarterKeyAreaSpecialCleanupCount: 15,
    quarterAntiStickingFacilityInstallationCount: 35,
    quarterIllegalPostingComplaintHandlingRate: 78.9,
    momChangeRate_IllegalPostingCleanupTotal: 1.5,
    yoyChangeRate_IllegalPostingCleanupTotal: 6.7,
    momChangeRate_IllegalNumberDisposalRate: 0.5,
    yoyChangeRate_IllegalNumberDisposalRate: 1.3,
    momChangeRate_KeyAreaSpecialCleanupCount: 4.2,
    yoyChangeRate_KeyAreaSpecialCleanupCount: 8.5,
    momChangeRate_AntiStickingFacilityInstallationCount: 1.8,
    yoyChangeRate_AntiStickingFacilityInstallationCount: 3.2,
    momChangeRate_IllegalPostingComplaintHandlingRate: 0.3,
    yoyChangeRate_IllegalPostingComplaintHandlingRate: 0.9,
    quarterDetailByRegion: '晋安区: 860次；马尾区: 420次；长乐区: 380次',
    quarterDetailByCleanupType: '主干道专项: 220次；背街小巷: 80次；商业区: 80次',
    quarterDetailByFacilityLocation: '交通枢纽: 8个；商业中心: 7个；居民区: 20个',
    quarterDetailByComplaintType: '市民投诉: 100件；巡查发现: 280件；上级督办: 0件',
    quarterComparisonByRegion: '环比: +1.5%；同比: +6.7%',
    quarterComparisonByCleanupType: '环比: +4.2%；同比: +8.5%',
    quarterComparisonByFacilityLocation: '环比: +1.8%；同比: +3.2%',
    quarterComparisonByComplaintType: '环比: +0.3%；同比: +0.9%',
    quarterStatisticsPeriod: '2024-Q2 (4月-6月)',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 季度乱贴乱画治理统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'regionName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'quarterIllegalPostingCleanupTotal',
      label: '季度乱贴乱画处置总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度乱贴乱画处置总量',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterIllegalNumberDisposalRate',
      label: '季度非法号码处置率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度非法号码处置率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterKeyAreaSpecialCleanupCount',
      label: '季度重点区域专项清理次数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度重点区域专项清理次数',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterAntiStickingFacilityInstallationCount',
      label: '季度防粘贴设施安装数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度防粘贴设施安装数量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterIllegalPostingComplaintHandlingRate',
      label: '季度乱贴乱画投诉处理率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度乱贴乱画投诉处理率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_IllegalPostingCleanupTotal',
      label: '处置总量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入处置总量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_IllegalPostingCleanupTotal',
      label: '处置总量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入处置总量同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_IllegalNumberDisposalRate',
      label: '非法号码处置率环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入非法号码处置率环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_IllegalNumberDisposalRate',
      label: '非法号码处置率同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入非法号码处置率同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_KeyAreaSpecialCleanupCount',
      label: '专项清理次数环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入专项清理次数环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_KeyAreaSpecialCleanupCount',
      label: '专项清理次数同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入专项清理次数同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_AntiStickingFacilityInstallationCount',
      label: '防粘贴设施安装数量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入防粘贴设施安装数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_AntiStickingFacilityInstallationCount',
      label: '防粘贴设施安装数量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入防粘贴设施安装数量同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_IllegalPostingComplaintHandlingRate',
      label: '投诉处理率环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入投诉处理率环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_IllegalPostingComplaintHandlingRate',
      label: '投诉处理率同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入投诉处理率同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterDetailByRegion',
      label: '按区域拆分季度明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按区域拆分的季度明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterDetailByCleanupType',
      label: '按专项清理类型拆分季度明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按专项清理类型拆分的季度明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterDetailByFacilityLocation',
      label: '按防粘贴设施点位拆分季度明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按防粘贴设施点位拆分的季度明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterDetailByComplaintType',
      label: '按投诉类型拆分季度明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按投诉类型拆分的季度明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterComparisonByRegion',
      label: '区域维度同比环比分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入区域维度的同比环比分析结果',
        maxlength: 100,
        type: 'textarea',
        rows: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterComparisonByCleanupType',
      label: '专项清理类型同比环比分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入专项清理类型的同比环比分析结果',
        maxlength: 100,
        type: 'textarea',
        rows: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterComparisonByFacilityLocation',
      label: '防粘贴设施点位同比环比分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入防粘贴设施点位的同比环比分析结果',
        maxlength: 100,
        type: 'textarea',
        rows: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterComparisonByComplaintType',
      label: '投诉类型同比环比分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入投诉类型的同比环比分析结果',
        maxlength: 100,
        type: 'textarea',
        rows: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterStatisticsPeriod',
      label: '季度统计时段',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度统计时段（如：2024-Q2 (4月-6月)）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 季度乱贴乱画治理统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'regionName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'quarterIllegalPostingCleanupTotal',
      title: '季度乱贴乱画处置总量(次)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'quarterIllegalNumberDisposalRate',
      title: '季度非法号码处置率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'quarterKeyAreaSpecialCleanupCount',
      title: '季度重点区域专项清理次数(次)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'quarterAntiStickingFacilityInstallationCount',
      title: '季度防粘贴设施安装数量(个)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'quarterIllegalPostingComplaintHandlingRate',
      title: '季度乱贴乱画投诉处理率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate_IllegalPostingCleanupTotal',
      title: '处置总量环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_IllegalPostingCleanupTotal',
      title: '处置总量同比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_IllegalNumberDisposalRate',
      title: '非法号码处置率环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_IllegalNumberDisposalRate',
      title: '非法号码处置率同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate_KeyAreaSpecialCleanupCount',
      title: '专项清理次数环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_KeyAreaSpecialCleanupCount',
      title: '专项清理次数同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate_AntiStickingFacilityInstallationCount',
      title: '防粘贴设施安装数量环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_AntiStickingFacilityInstallationCount',
      title: '防粘贴设施安装数量同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate_IllegalPostingComplaintHandlingRate',
      title: '投诉处理率环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_IllegalPostingComplaintHandlingRate',
      title: '投诉处理率同比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'quarterDetailByRegion',
      title: '按区域拆分明细',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'quarterDetailByCleanupType',
      title: '按清理类型拆分明细',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'quarterDetailByFacilityLocation',
      title: '按设施点位拆分明细',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'quarterDetailByComplaintType',
      title: '按投诉类型拆分明细',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'quarterComparisonByRegion',
      title: '区域同比环比分析',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'quarterComparisonByCleanupType',
      title: '清理类型同比环比分析',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'quarterComparisonByFacilityLocation',
      title: '设施点位同比环比分析',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'quarterComparisonByComplaintType',
      title: '投诉类型同比环比分析',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'quarterStatisticsPeriod',
      title: '季度统计时段',
      minWidth: 160,
      sortable: false,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
