/** 备件入库表格初始数据 - 按指定字段生成 */
export const dataList = () => {
  return [
    {
      inNo: 'IN20250101001',
      partName: '道闸电机',
      partCode: 'PART-001',
      inQuantity: 10,
      inPrice: 500,
      totalAmount: 5000,
      supplierName: '漳州市机电设备有限公司',
      inTime: '2025-01-01 09:00:00',
      operator: '张三',
      inId: 'INID001',
      statusName: '已审核',
      auditor: '李四',
      auditTime: '2025-01-01 10:00:00',
      stockUpdateResult: '成功',
    },
    {
      inNo: 'IN20250102002',
      partName: '车牌识别摄像头',
      partCode: 'PART-002',
      inQuantity: 5,
      inPrice: 1200,
      totalAmount: 6000,
      supplierName: '厦门市安防科技有限公司',
      inTime: '2025-01-02 14:30:00',
      operator: '王五',
      inId: 'INID002',
      statusName: '待审核',
      auditor: '',
      auditTime: '',
      stockUpdateResult: '待处理',
    },
    {
      inNo: 'IN20250103003',
      partName: '地磁传感器',
      partCode: 'PART-003',
      inQuantity: 20,
      inPrice: 80,
      totalAmount: 1600,
      supplierName: '泉州市电子元件有限公司',
      inTime: '2025-01-03 10:15:00',
      operator: '赵六',
      inId: 'INID003',
      statusName: '已审核',
      auditor: '孙七',
      auditTime: '2025-01-03 11:00:00',
      stockUpdateResult: '成功',
    },
    {
      inNo: 'IN20250104004',
      partName: '道闸杆',
      partCode: 'PART-004',
      inQuantity: 8,
      inPrice: 200,
      totalAmount: 1600,
      supplierName: '漳州市机电设备有限公司',
      inTime: '2025-01-04 15:45:00',
      operator: '周八',
      inId: 'INID004',
      statusName: '已审核',
      auditor: '吴九',
      auditTime: '2025-01-04 16:30:00',
      stockUpdateResult: '成功',
    },
    {
      inNo: 'IN20250105005',
      partName: '收费终端主板',
      partCode: 'PART-005',
      inQuantity: 3,
      inPrice: 800,
      totalAmount: 2400,
      supplierName: '福州市计算机配件有限公司',
      inTime: '2025-01-05 09:30:00',
      operator: '郑十',
      inId: 'INID005',
      statusName: '已拒绝',
      auditor: '张三',
      auditTime: '2025-01-05 10:15:00',
      stockUpdateResult: '失败',
    },
    {
      inNo: 'IN20250106006',
      partName: '诱导屏LED灯',
      partCode: 'PART-006',
      inQuantity: 50,
      inPrice: 15,
      totalAmount: 750,
      supplierName: '深圳市光电科技有限公司',
      inTime: '2025-01-06 13:20:00',
      operator: '李四',
      inId: 'INID006',
      statusName: '已审核',
      auditor: '王五',
      auditTime: '2025-01-06 14:00:00',
      stockUpdateResult: '成功',
    },
    {
      inNo: 'IN20250107007',
      partName: '道闸控制板',
      partCode: 'PART-007',
      inQuantity: 6,
      inPrice: 350,
      totalAmount: 2100,
      supplierName: '漳州市机电设备有限公司',
      inTime: '2025-01-07 11:00:00',
      operator: '赵六',
      inId: 'INID007',
      statusName: '待审核',
      auditor: '',
      auditTime: '',
      stockUpdateResult: '待处理',
    },
    {
      inNo: 'IN20250108008',
      partName: '车牌识别算法模块',
      partCode: 'PART-008',
      inQuantity: 2,
      inPrice: 2000,
      totalAmount: 4000,
      supplierName: '杭州市人工智能科技有限公司',
      inTime: '2025-01-08 10:45:00',
      operator: '孙七',
      inId: 'INID008',
      statusName: '已审核',
      auditor: '周八',
      auditTime: '2025-01-08 11:30:00',
      stockUpdateResult: '成功',
    },
    {
      inNo: 'IN20250109009',
      partName: '地磁检测器电池',
      partCode: 'PART-009',
      inQuantity: 30,
      inPrice: 25,
      totalAmount: 750,
      supplierName: '泉州市电子元件有限公司',
      inTime: '2025-01-09 16:00:00',
      operator: '吴九',
      inId: 'INID009',
      statusName: '已审核',
      auditor: '郑十',
      auditTime: '2025-01-09 16:45:00',
      stockUpdateResult: '成功',
    },
    {
      inNo: 'IN20250110010',
      partName: '收费终端触摸屏',
      partCode: 'PART-010',
      inQuantity: 4,
      inPrice: 600,
      totalAmount: 2400,
      supplierName: '福州市计算机配件有限公司',
      inTime: '2025-01-10 09:15:00',
      operator: '张三',
      inId: 'INID010',
      statusName: '待审核',
      auditor: '',
      auditTime: '',
      stockUpdateResult: '待处理',
    },
    {
      inNo: 'IN20250111011',
      partName: '道闸减速机',
      partCode: 'PART-011',
      inQuantity: 3,
      inPrice: 450,
      totalAmount: 1350,
      supplierName: '漳州市机电设备有限公司',
      inTime: '2025-01-11 14:50:00',
      operator: '李四',
      inId: 'INID011',
      statusName: '已审核',
      auditor: '王五',
      auditTime: '2025-01-11 15:30:00',
      stockUpdateResult: '成功',
    },
    {
      inNo: 'IN20250112012',
      partName: '车牌识别相机护罩',
      partCode: 'PART-012',
      inQuantity: 10,
      inPrice: 80,
      totalAmount: 800,
      supplierName: '厦门市安防科技有限公司',
      inTime: '2025-01-12 11:20:00',
      operator: '王五',
      inId: 'INID012',
      statusName: '已审核',
      auditor: '赵六',
      auditTime: '2025-01-12 12:00:00',
      stockUpdateResult: '成功',
    },
    {
      inNo: 'IN20250113013',
      partName: '诱导屏控制卡',
      partCode: 'PART-013',
      inQuantity: 8,
      inPrice: 280,
      totalAmount: 2240,
      supplierName: '深圳市光电科技有限公司',
      inTime: '2025-01-13 10:00:00',
      operator: '赵六',
      inId: 'INID013',
      statusName: '已拒绝',
      auditor: '孙七',
      auditTime: '2025-01-13 10:45:00',
      stockUpdateResult: '失败',
    },
    {
      inNo: 'IN20250114014',
      partName: '地磁检测器外壳',
      partCode: 'PART-014',
      inQuantity: 15,
      inPrice: 40,
      totalAmount: 600,
      supplierName: '泉州市电子元件有限公司',
      inTime: '2025-01-14 15:10:00',
      operator: '孙七',
      inId: 'INID014',
      statusName: '已审核',
      auditor: '周八',
      auditTime: '2025-01-14 15:50:00',
      stockUpdateResult: '成功',
    },
    {
      inNo: 'IN20250115015',
      partName: '收费终端打印机',
      partCode: 'PART-015',
      inQuantity: 5,
      inPrice: 320,
      totalAmount: 1600,
      supplierName: '福州市计算机配件有限公司',
      inTime: '2025-01-15 09:45:00',
      operator: '周八',
      inId: 'INID015',
      statusName: '待审核',
      auditor: '',
      auditTime: '',
      stockUpdateResult: '待处理',
    },
  ];
};

/** 备件入库表单配置（包含所有指定字段） */
export function useFormSchema() {
  return [
    {
      fieldName: 'inId',
      label: '入库ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入入库ID',
      },
      rules: 'required',
    },
    {
      fieldName: 'inNo',
      label: '入库单号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入入库单号',
      },
      rules: 'required',
    },
    {
      fieldName: 'partName',
      label: '备件名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入备件名称',
      },
      rules: 'required',
    },
    {
      fieldName: 'partCode',
      label: '备件编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入备件编码',
      },
      rules: 'required',
    },
    {
      fieldName: 'inQuantity',
      label: '入库数量',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入入库数量',
        min: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'inPrice',
      label: '入库单价',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入入库单价',
        min: 0,
        step: 0.01,
      },
      rules: 'required',
    },
    {
      fieldName: 'totalAmount',
      label: '总金额',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入总金额',
        min: 0,
        step: 0.01,
      },
      rules: 'required',
    },
    {
      fieldName: 'supplierName',
      label: '供应商',
      component: 'Input',
      componentProps: {
        placeholder: '请输入供应商',
      },
      rules: 'required',
    },
    {
      fieldName: 'inTime',
      label: '入库时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择入库时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'operator',
      label: '操作人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入操作人',
      },
      rules: 'required',
    },
    {
      fieldName: 'statusName',
      label: '状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择状态',
        options: [
          { label: '待审核', value: '待审核' },
          { label: '已审核', value: '已审核' },
          { label: '已拒绝', value: '已拒绝' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'auditor',
      label: '审核人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入审核人',
      },
    },
    {
      fieldName: 'auditTime',
      label: '审核时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择审核时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      fieldName: 'stockUpdateResult',
      label: '库存更新结果',
      component: 'Select',
      componentProps: {
        placeholder: '请选择库存更新结果',
        options: [
          { label: '成功', value: '成功' },
          { label: '失败', value: '失败' },
          { label: '待处理', value: '待处理' },
        ],
      },
    },
  ];
}

/** 备件入库表格列配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'inId',
      title: '入库ID',
      minWidth: 100,
      sortable: true,
      slots: { default: 'inId' },
    },
    {
      field: 'inNo',
      title: '入库单号',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'partName',
      title: '备件名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'partCode',
      title: '备件编码',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'inQuantity',
      title: '入库数量',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'inPrice',
      title: '入库单价',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'totalAmount',
      title: '总金额',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'supplierName',
      title: '供应商',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'inTime',
      title: '入库时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'operator',
      title: '操作人',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'statusName',
      title: '状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'statusName' },
    },
    {
      field: 'auditor',
      title: '审核人',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'auditTime',
      title: '审核时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'stockUpdateResult',
      title: '库存更新结果',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 100,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

export const textObj = {
  editText: '编辑备件入库',
  addText: '新增备件入库',
  excelName: '备件入库列表',
  excelAllName: '备件入库数据.xlsx',
  total: ' 总计: 入库单数15; 已审核8; 待审核5; 已拒绝2',
};

/** 详情抽屉字段配置 */
export const detailFields = [
  { key: 'inId', label: '入库ID' },
  { key: 'inNo', label: '入库单号' },
  { key: 'partName', label: '备件名称' },
  { key: 'partCode', label: '备件编码' },
  { key: 'inQuantity', label: '入库数量' },
  { key: 'inPrice', label: '入库单价' },
  { key: 'totalAmount', label: '总金额' },
  { key: 'supplierName', label: '供应商' },
  { key: 'inTime', label: '入库时间' },
  { key: 'operator', label: '操作人' },
  { key: 'statusName', label: '状态' },
  { key: 'auditor', label: '审核人' },
  { key: 'auditTime', label: '审核时间' },
  { key: 'stockUpdateResult', label: '库存更新结果' },
];
