/** 渣土清运违规统计初始数据 - 支持环比、同比分析 */
export const dataList = () => [
  {
    timeRange: '2025年第1周',
    area: '鼓楼区',
    transportCompany: '福州市渣土运输公司',
    wasteType: '建筑渣土',
    violationType: '未密闭运输',
    checkPoint: '二环路卡点',
    disposalSite: '红庙岭消纳场',
    violationCount: 12,
    clearedCount: 10,
    fineAmount: 2400,
    momChangeRate_violationCount: 5.2,
    momChangeRate_clearedCount: 3.1,
    momChangeRate_fineAmount: 7.5,
    yoyChangeRate_violationCount: 8.3,
    yoyChangeRate_clearedCount: 6.2,
    yoyChangeRate_fineAmount: 9.1,
  },
  {
    timeRange: '2025年第1周',
    area: '台江区',
    transportCompany: '台江清运有限公司',
    wasteType: '装修渣土',
    violationType: '沿途遗撒',
    checkPoint: '鳌峰路卡点',
    disposalSite: '义序消纳场',
    violationCount: 8,
    clearedCount: 7,
    fineAmount: 1600,
    momChangeRate_violationCount: -2.4,
    momChangeRate_clearedCount: -1.5,
    momChangeRate_fineAmount: 3.2,
    yoyChangeRate_violationCount: 1.2,
    yoyChangeRate_clearedCount: 0.8,
    yoyChangeRate_fineAmount: 2.5,
  },
  {
    timeRange: '2025年第1周',
    area: '仓山区',
    transportCompany: '仓山环境运输公司',
    wasteType: '工程渣土',
    violationType: '未按规定路线行驶',
    checkPoint: '三环路卡点',
    disposalSite: '城门消纳场',
    violationCount: 15,
    clearedCount: 13,
    fineAmount: 3000,
    momChangeRate_violationCount: 8.7,
    momChangeRate_clearedCount: 9.2,
    momChangeRate_fineAmount: 10.5,
    yoyChangeRate_violationCount: 12.3,
    yoyChangeRate_clearedCount: 11.4,
    yoyChangeRate_fineAmount: 13.2,
  },
  {
    timeRange: '2025年第1周',
    area: '晋安区',
    transportCompany: '晋安渣土清运公司',
    wasteType: '建筑渣土',
    violationType: '未密闭运输',
    checkPoint: '福飞路卡点',
    disposalSite: '新店消纳场',
    violationCount: 10,
    clearedCount: 9,
    fineAmount: 2000,
    momChangeRate_violationCount: -1.5,
    momChangeRate_clearedCount: -2.0,
    momChangeRate_fineAmount: -0.5,
    yoyChangeRate_violationCount: 3.2,
    yoyChangeRate_clearedCount: 2.8,
    yoyChangeRate_fineAmount: 4.1,
  },
  {
    timeRange: '2025年第1周',
    area: '马尾区',
    transportCompany: '马尾区运输有限公司',
    wasteType: '装修渣土',
    violationType: '沿途遗撒',
    checkPoint: '江滨路卡点',
    disposalSite: '琅岐消纳场',
    violationCount: 5,
    clearedCount: 4,
    fineAmount: 1000,
    momChangeRate_violationCount: 15.2,
    momChangeRate_clearedCount: 12.5,
    momChangeRate_fineAmount: 18.3,
    yoyChangeRate_violationCount: 10.8,
    yoyChangeRate_clearedCount: 9.2,
    yoyChangeRate_fineAmount: 12.4,
  },
  {
    timeRange: '2025年第2周',
    area: '鼓楼区',
    transportCompany: '福州市渣土运输公司',
    wasteType: '建筑渣土',
    violationType: '未密闭运输',
    checkPoint: '二环路卡点',
    disposalSite: '红庙岭消纳场',
    violationCount: 10,
    clearedCount: 9,
    fineAmount: 2000,
    momChangeRate_violationCount: -16.7,
    momChangeRate_clearedCount: -10.0,
    momChangeRate_fineAmount: -16.7,
    yoyChangeRate_violationCount: 5.1,
    yoyChangeRate_clearedCount: 4.2,
    yoyChangeRate_fineAmount: 6.3,
  },
  {
    timeRange: '2025年第2周',
    area: '台江区',
    transportCompany: '台江清运有限公司',
    wasteType: '装修渣土',
    violationType: '未按规定路线行驶',
    checkPoint: '鳌峰路卡点',
    disposalSite: '义序消纳场',
    violationCount: 7,
    clearedCount: 6,
    fineAmount: 1400,
    momChangeRate_violationCount: -12.5,
    momChangeRate_clearedCount: -14.3,
    momChangeRate_fineAmount: -12.5,
    yoyChangeRate_violationCount: 2.3,
    yoyChangeRate_clearedCount: 1.9,
    yoyChangeRate_fineAmount: 3.1,
  },
  {
    timeRange: '2025年第2周',
    area: '仓山区',
    transportCompany: '仓山环境运输公司',
    wasteType: '工程渣土',
    violationType: '未密闭运输',
    checkPoint: '三环路卡点',
    disposalSite: '城门消纳场',
    violationCount: 18,
    clearedCount: 16,
    fineAmount: 3600,
    momChangeRate_violationCount: 20.0,
    momChangeRate_clearedCount: 23.1,
    momChangeRate_fineAmount: 20.0,
    yoyChangeRate_violationCount: 13.5,
    yoyChangeRate_clearedCount: 12.8,
    yoyChangeRate_fineAmount: 14.2,
  },
  {
    timeRange: '2025年第2周',
    area: '晋安区',
    transportCompany: '晋安渣土清运公司',
    wasteType: '建筑渣土',
    violationType: '沿途遗撒',
    checkPoint: '福飞路卡点',
    disposalSite: '新店消纳场',
    violationCount: 12,
    clearedCount: 10,
    fineAmount: 2400,
    momChangeRate_violationCount: 20.0,
    momChangeRate_clearedCount: 11.1,
    momChangeRate_fineAmount: 20.0,
    yoyChangeRate_violationCount: 4.5,
    yoyChangeRate_clearedCount: 3.9,
    yoyChangeRate_fineAmount: 5.2,
  },
  {
    timeRange: '2025年第2周',
    area: '马尾区',
    transportCompany: '马尾区运输有限公司',
    wasteType: '装修渣土',
    violationType: '未密闭运输',
    checkPoint: '江滨路卡点',
    disposalSite: '琅岐消纳场',
    violationCount: 6,
    clearedCount: 5,
    fineAmount: 1200,
    momChangeRate_violationCount: 20.0,
    momChangeRate_clearedCount: 25.0,
    momChangeRate_fineAmount: 20.0,
    yoyChangeRate_violationCount: 11.2,
    yoyChangeRate_clearedCount: 10.5,
    yoyChangeRate_fineAmount: 12.0,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 渣土清运违规统计表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'timeRange',
      label: '时间范围',
      component: 'Input',
      componentProps: {
        placeholder: '请输入时间范围（如：2025年第1周）',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'area',
      label: '区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'transportCompany',
      label: '清运企业',
      component: 'Input',
      componentProps: {
        placeholder: '请输入清运企业名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'wasteType',
      label: '渣土类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择渣土类型',
        options: [
          { label: '建筑渣土', value: '建筑渣土' },
          { label: '装修渣土', value: '装修渣土' },
          { label: '工程渣土', value: '工程渣土' },
        ],
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'violationType',
      label: '违规类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择违规类型',
        options: [
          { label: '未密闭运输', value: '未密闭运输' },
          { label: '沿途遗撒', value: '沿途遗撒' },
          { label: '未按规定路线行驶', value: '未按规定路线行驶' },
        ],
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'checkPoint',
      label: '卡点',
      component: 'Input',
      componentProps: {
        placeholder: '请输入卡点名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'disposalSite',
      label: '消纳场',
      component: 'Input',
      componentProps: {
        placeholder: '请输入消纳场名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'violationCount',
      label: '违规数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违规数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'clearedCount',
      label: '处理数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入处理数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'fineAmount',
      label: '罚款金额（元）',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入罚款金额',
        min: 0,
        precision: 0,
        addonAfter: '元',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_violationCount',
      label: '违规数量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比变化率（%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_clearedCount',
      label: '处理数量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比变化率（%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_fineAmount',
      label: '罚款金额环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比变化率（%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_violationCount',
      label: '违规数量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_clearedCount',
      label: '处理数量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_fineAmount',
      label: '罚款金额同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 渣土清运违规统计表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'timeRange',
      title: '时间范围',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'area',
      title: '区域',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'transportCompany',
      title: '清运企业',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'wasteType',
      title: '渣土类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'violationType',
      title: '违规类型',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'checkPoint',
      title: '卡点',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'disposalSite',
      title: '消纳场',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'violationCount',
      title: '违规数量',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'clearedCount',
      title: '处理数量',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'fineAmount',
      title: '罚款金额(元)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'momChangeRate_violationCount',
      title: '违规数量环比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_clearedCount',
      title: '处理数量环比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_fineAmount',
      title: '罚款金额环比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_violationCount',
      title: '违规数量同比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_clearedCount',
      title: '处理数量同比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_fineAmount',
      title: '罚款金额同比(%)',
      minWidth: 160,
      sortable: true,
    },
  ];
}
