/** 表格初始数据 - 窨井盖设施监测半年报数据 */
export const dataList = () => [
  {
    areaName: '福州市鼓楼区',
    deptName: '福州市鼓楼区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 1500,
    halfYearTotalHiddenTroubleCount: 360,
    halfYearDisposalCompleteCount: 320,
    deviceHalfYearOnlineRate: 97.2,
    halfYearRepeatHiddenTroubleCount: 60,
    halfYearHiddenTroubleDisposalRate: 88.89,
    halfYearRepeatHiddenTroubleRate: 16.67,
    yoyHiddenTroubleChangeRate: 10,
    operationEfficiencyImprovementRate: 5.2,
    halfYearAvgDisposalDuration: 8.5,
  },
  {
    areaName: '厦门市思明区',
    deptName: '厦门市思明区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 2000,
    halfYearTotalHiddenTroubleCount: 180,
    halfYearDisposalCompleteCount: 180,
    deviceHalfYearOnlineRate: 99.1,
    halfYearRepeatHiddenTroubleCount: 18,
    halfYearHiddenTroubleDisposalRate: 100,
    halfYearRepeatHiddenTroubleRate: 10,
    yoyHiddenTroubleChangeRate: -5,
    operationEfficiencyImprovementRate: 12.8,
    halfYearAvgDisposalDuration: 4.2,
  },
  {
    areaName: '泉州市丰泽区',
    deptName: '泉州市丰泽区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 1800,
    halfYearTotalHiddenTroubleCount: 540,
    halfYearDisposalCompleteCount: 390,
    deviceHalfYearOnlineRate: 85.8,
    halfYearRepeatHiddenTroubleCount: 135,
    halfYearHiddenTroubleDisposalRate: 72.22,
    halfYearRepeatHiddenTroubleRate: 25,
    yoyHiddenTroubleChangeRate: 25,
    operationEfficiencyImprovementRate: -3.5,
    halfYearAvgDisposalDuration: 15.6,
  },
  {
    areaName: '漳州市芗城区',
    deptName: '漳州市芗城区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 1200,
    halfYearTotalHiddenTroubleCount: 90,
    halfYearDisposalCompleteCount: 90,
    deviceHalfYearOnlineRate: 98.9,
    halfYearRepeatHiddenTroubleCount: 6,
    halfYearHiddenTroubleDisposalRate: 100,
    halfYearRepeatHiddenTroubleRate: 6.67,
    yoyHiddenTroubleChangeRate: -15,
    operationEfficiencyImprovementRate: 15.3,
    halfYearAvgDisposalDuration: 3.8,
  },
  {
    areaName: '莆田市城厢区',
    deptName: '莆田市城厢区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 1600,
    halfYearTotalHiddenTroubleCount: 450,
    halfYearDisposalCompleteCount: 330,
    deviceHalfYearOnlineRate: 78.2,
    halfYearRepeatHiddenTroubleCount: 90,
    halfYearHiddenTroubleDisposalRate: 73.33,
    halfYearRepeatHiddenTroubleRate: 20,
    yoyHiddenTroubleChangeRate: 20,
    operationEfficiencyImprovementRate: 1.8,
    halfYearAvgDisposalDuration: 12.5,
  },
  {
    areaName: '宁德市蕉城区',
    deptName: '宁德市蕉城区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 1400,
    halfYearTotalHiddenTroubleCount: 150,
    halfYearDisposalCompleteCount: 138,
    deviceHalfYearOnlineRate: 97.5,
    halfYearRepeatHiddenTroubleCount: 24,
    halfYearHiddenTroubleDisposalRate: 92,
    halfYearRepeatHiddenTroubleRate: 16,
    yoyHiddenTroubleChangeRate: 5,
    operationEfficiencyImprovementRate: 8.7,
    halfYearAvgDisposalDuration: 6.2,
  },
  {
    areaName: '龙岩市新罗区',
    deptName: '龙岩市新罗区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 1700,
    halfYearTotalHiddenTroubleCount: 360,
    halfYearDisposalCompleteCount: 270,
    deviceHalfYearOnlineRate: 96.8,
    halfYearRepeatHiddenTroubleCount: 72,
    halfYearHiddenTroubleDisposalRate: 75,
    halfYearRepeatHiddenTroubleRate: 20,
    yoyHiddenTroubleChangeRate: 15,
    operationEfficiencyImprovementRate: 4.2,
    halfYearAvgDisposalDuration: 9.8,
  },
  {
    areaName: '三明市梅列区',
    deptName: '三明市梅列区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 1300,
    halfYearTotalHiddenTroubleCount: 60,
    halfYearDisposalCompleteCount: 60,
    deviceHalfYearOnlineRate: 98.8,
    halfYearRepeatHiddenTroubleCount: 6,
    halfYearHiddenTroubleDisposalRate: 100,
    halfYearRepeatHiddenTroubleRate: 10,
    yoyHiddenTroubleChangeRate: -10,
    operationEfficiencyImprovementRate: 10.5,
    halfYearAvgDisposalDuration: 4.5,
  },
  {
    areaName: '南平市延平区',
    deptName: '南平市延平区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 1500,
    halfYearTotalHiddenTroubleCount: 270,
    halfYearDisposalCompleteCount: 210,
    deviceHalfYearOnlineRate: 88.5,
    halfYearRepeatHiddenTroubleCount: 54,
    halfYearHiddenTroubleDisposalRate: 77.78,
    halfYearRepeatHiddenTroubleRate: 20,
    yoyHiddenTroubleChangeRate: 12,
    operationEfficiencyImprovementRate: 2.1,
    halfYearAvgDisposalDuration: 14.2,
  },
  {
    areaName: '平潭综合实验区',
    deptName: '平潭综合实验区市政管理处',
    halfYearStatisticsPeriod: '2024年上半年',
    manholeTotalCount: 1100,
    halfYearTotalHiddenTroubleCount: 72,
    halfYearDisposalCompleteCount: 72,
    deviceHalfYearOnlineRate: 99.4,
    halfYearRepeatHiddenTroubleCount: 12,
    halfYearHiddenTroubleDisposalRate: 100,
    halfYearRepeatHiddenTroubleRate: 16.67,
    yoyHiddenTroubleChangeRate: -8,
    operationEfficiencyImprovementRate: 9.6,
    halfYearAvgDisposalDuration: 5.1,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施监测半年报表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'deptName',
      label: '责任单位',
      component: 'Input',
      componentProps: {
        placeholder: '请输入责任单位',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'halfYearStatisticsPeriod',
      label: '半年统计时段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入半年统计时段（如：2024年上半年）',
        maxlength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 半年统计时段为必填项
    },
  ];
}

/** 表格字段 - 窨井盖设施监测半年报表格列 */
export function useGridColumns() {
  return [
    {
      field: 'areaName',
      title: '所属区域',
      minWidth: 180,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'deptName',
      title: '责任单位',
      minWidth: 180,
      sortable: true,
      slots: { default: 'deptName' },
    },
    {
      field: 'halfYearStatisticsPeriod',
      title: '半年统计时段',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'manholeTotalCount',
      title: '窨井盖总数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'halfYearTotalHiddenTroubleCount',
      title: '半年累计隐患数',
      minWidth: 140,
      sortable: true,
      slots: { default: 'halfYearTotalHiddenTroubleCount' },
    },
    {
      field: 'halfYearDisposalCompleteCount',
      title: '半年处置完成数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deviceHalfYearOnlineRate',
      title: '设备半年在线率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'halfYearRepeatHiddenTroubleCount',
      title: '半年重复隐患数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'halfYearHiddenTroubleDisposalRate',
      title: '半年隐患处置完成率(%)',
      minWidth: 180,
      sortable: true,
      slots: { default: 'halfYearHiddenTroubleDisposalRate' },
    },
    {
      field: 'halfYearRepeatHiddenTroubleRate',
      title: '半年重复隐患率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyHiddenTroubleChangeRate',
      title: '同比隐患变化率(%)',
      minWidth: 160,
      sortable: true,
      slots: { default: 'yoyHiddenTroubleChangeRate' },
    },
    {
      field: 'operationEfficiencyImprovementRate',
      title: '运维效能提升率(%)',
      minWidth: 160,
      sortable: true,
      slots: { default: 'operationEfficiencyImprovementRate' },
    },
    {
      field: 'halfYearAvgDisposalDuration',
      title: '半年平均处置时长(小时)',
      minWidth: 160,
      sortable: true,
    },
    {
      title: '操作',
      width: 240,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
