/** 表格初始数据 */
export const dataList = () => {
  return [
    {
      invoice_id: '110e8400-e29b-41d4-a716-446655440000',
      invoice_no: 'INV202310120001',
      order_id: 'ORDER001',
      order_type: '临停',
      user_id: 'USER001',
      invoice_type: '普通发票',
      title: '张三',
      taxpayer_id: '',
      amount: '50.00',
      invoice_content: '停车费',
      status: '已开具',
      issue_time: '2023-10-12 10:30:00',
      pdf_url: 'https://minio.example.com/invoices/INV202310120001.pdf',
      create_time: '2023-10-12 09:28:00',
      update_time: '2023-10-12 10:30:00',
      remark: '正常开具',
    },
    {
      invoice_id: '6ba7b819-9dad-11d1-80b4-00c04fd430c8',
      invoice_no: 'INV202310120002',
      order_id: 'ORDER002',
      order_type: '期卡',
      user_id: 'USER002',
      invoice_type: '增值税电子普通发票',
      title: 'XX科技有限公司',
      taxpayer_id: '91310101MA1FL1234',
      amount: '300.00',
      invoice_content: '月卡费用',
      status: '已开具',
      issue_time: '2023-10-12 11:15:00',
      pdf_url: 'https://minio.example.com/invoices/INV202310120002.pdf',
      create_time: '2023-10-12 10:10:00',
      update_time: '2023-10-12 11:15:00',
      remark: '企业发票',
    },
    {
      invoice_id: '6ba7b820-9dad-11d1-80b4-00c04fd430c8',
      invoice_no: 'INV202310120003',
      order_id: 'ORDER003',
      order_type: '充值',
      user_id: 'USER003',
      invoice_type: '普通发票',
      title: '李四',
      taxpayer_id: '',
      amount: '200.00',
      invoice_content: '钱包充值',
      status: '待开具',
      issue_time: '',
      pdf_url: '',
      create_time: '2023-10-12 10:58:00',
      update_time: '2023-10-12 10:58:00',
      remark: '待申请开具',
    },
    {
      invoice_id: '6ba7b821-9dad-11d1-80b4-00c04fd430c8',
      invoice_no: 'INV202310120004',
      order_id: 'ORDER004',
      order_type: '逃费追缴',
      user_id: '',
      invoice_type: '普通发票',
      title: '王五',
      taxpayer_id: '',
      amount: '80.00',
      invoice_content: '补缴费用',
      status: '已开具',
      issue_time: '2023-10-12 15:20:00',
      pdf_url: 'https://minio.example.com/invoices/INV202310120004.pdf',
      create_time: '2023-10-12 14:18:00',
      update_time: '2023-10-12 15:20:00',
      remark: '追缴成功开具',
    },
    {
      invoice_id: '6ba7b822-9dad-11d1-80b4-00c04fd430c8',
      invoice_no: 'INV202310120005',
      order_id: 'ORDER005',
      order_type: '欠费追缴',
      user_id: 'USER005',
      invoice_type: '增值税电子普通发票',
      title: 'YY有限公司',
      taxpayer_id: '91310101MA1FL5678',
      amount: '120.00',
      invoice_content: '代付费用',
      status: '已红冲',
      issue_time: '2023-10-12 17:45:00',
      pdf_url: 'https://minio.example.com/invoices/INV202310120005.pdf',
      create_time: '2023-10-12 16:40:00',
      update_time: '2023-10-12 18:30:00',
      remark: '发票红冲',
    },
    {
      invoice_id: '6ba7b823-9dad-11d1-80b4-00c04fd430c8',
      invoice_no: 'INV202310130001',
      order_id: 'ORDER006',
      order_type: '临停',
      user_id: 'USER006',
      invoice_type: '普通发票',
      title: '赵六',
      taxpayer_id: '',
      amount: '30.00',
      invoice_content: '停车费',
      status: '已作废',
      issue_time: '2023-10-13 09:30:00',
      pdf_url: 'https://minio.example.com/invoices/INV202310130001.pdf',
      create_time: '2023-10-13 08:25:00',
      update_time: '2023-10-13 10:00:00',
      remark: '作废发票',
    },
    {
      invoice_id: '6ba7b824-9dad-11d1-80b4-00c04fd430c8',
      invoice_no: 'INV202310130002',
      order_id: 'ORDER007',
      order_type: '期卡',
      user_id: 'USER007',
      invoice_type: '增值税电子普通发票',
      title: 'ZZ科技有限公司',
      taxpayer_id: '91310101MA1FL9012',
      amount: '500.00',
      invoice_content: '月卡费用',
      status: '已开具',
      issue_time: '2023-10-13 11:00:00',
      pdf_url: 'https://minio.example.com/invoices/INV202310130002.pdf',
      create_time: '2023-10-13 09:55:00',
      update_time: '2023-10-13 11:00:00',
      remark: '正常开具',
    },
    {
      invoice_id: '6ba7b825-9dad-11d1-80b4-00c04fd430c8',
      invoice_no: 'INV202310130003',
      order_id: 'ORDER008',
      order_type: '充值',
      user_id: 'USER008',
      invoice_type: '普通发票',
      title: '孙七',
      taxpayer_id: '',
      amount: '100.00',
      invoice_content: '充值费用',
      status: '待开具',
      issue_time: '',
      pdf_url: '',
      create_time: '2023-10-13 12:25:00',
      update_time: '2023-10-13 12:25:00',
      remark: '待申请',
    },
    {
      invoice_id: '6ba7b826-9dad-11d1-80b4-00c04fd430c8',
      invoice_no: 'INV202310130004',
      order_id: 'ORDER009',
      order_type: '逃费追缴',
      user_id: '',
      invoice_type: '普通发票',
      title: '周八',
      taxpayer_id: '',
      amount: '150.00',
      invoice_content: '追缴费用',
      status: '已开具',
      issue_time: '2023-10-13 16:10:00',
      pdf_url: 'https://minio.example.com/invoices/INV202310130004.pdf',
      create_time: '2023-10-13 15:05:00',
      update_time: '2023-10-13 16:10:00',
      remark: '追缴开具',
    },
    {
      invoice_id: '6ba7b827-9dad-11d1-80b4-00c04fd430c8',
      invoice_no: 'INV202310130005',
      order_id: 'ORDER010',
      order_type: '欠费追缴',
      user_id: 'USER010',
      invoice_type: '增值税电子普通发票',
      title: 'AA有限公司',
      taxpayer_id: '91310101MA1FL3456',
      amount: '200.00',
      invoice_content: '代付费用',
      status: '已开具',
      issue_time: '2023-10-13 18:30:00',
      pdf_url: 'https://minio.example.com/invoices/INV202310130005.pdf',
      create_time: '2023-10-13 17:25:00',
      update_time: '2023-10-13 18:30:00',
      remark: '企业代付开具',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'invoice_id',
      label: '发票ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入发票ID',
      },
    },
    {
      fieldName: 'invoice_no',
      label: '发票号码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入发票号码',
      },
    },
    {
      fieldName: 'order_id',
      label: '关联订单ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联订单ID',
      },
    },
    {
      fieldName: 'order_type',
      label: '订单类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择订单类型',
        options: [
          { label: '临停', value: '临停' },
          { label: '期卡', value: '期卡' },
          { label: '充值', value: '充值' },
          { label: '逃费追缴', value: '逃费追缴' },
          { label: '欠费追缴', value: '欠费追缴' },
        ],
      },
    },
    {
      fieldName: 'user_id',
      label: '关联用户ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联用户ID',
      },
    },
    {
      fieldName: 'invoice_type',
      label: '发票类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择发票类型',
        options: [
          { label: '普通发票', value: '普通发票' },
          { label: '增值税电子普通发票', value: '增值税电子普通发票' },
        ],
      },
    },
    {
      fieldName: 'title',
      label: '发票抬头',
      component: 'Input',
      componentProps: {
        placeholder: '请输入发票抬头',
      },
    },
    {
      fieldName: 'taxpayer_id',
      label: '纳税人识别号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入纳税人识别号（可为空）',
      },
    },
    {
      fieldName: 'amount',
      label: '发票金额',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入发票金额',
        min: 0,
        precision: 2,
      },
    },
    {
      fieldName: 'invoice_content',
      label: '发票内容',
      component: 'Input',
      componentProps: {
        placeholder: '请输入发票内容',
      },
    },
    {
      fieldName: 'status',
      label: '发票状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择发票状态',
        options: [
          { label: '待开具', value: '待开具' },
          { label: '已开具', value: '已开具' },
          { label: '已红冲', value: '已红冲' },
          { label: '已作废', value: '已作废' },
        ],
      },
    },
    {
      fieldName: 'issue_time',
      label: '开具时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择开具时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'pdf_url',
      label: '发票PDF地址',
      component: 'Input',
      componentProps: {
        placeholder: '请输入发票PDF地址（MinIO）',
      },
    },
    {
      fieldName: 'create_time',
      label: '创建时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择创建时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'update_time',
      label: '更新时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择更新时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Input',
      componentProps: {
        placeholder: '请输入备注',
        type: 'textarea',
        rows: 3,
      },
    },
  ];
}

/** 表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'invoice_no',
      title: '发票号码',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'order_type',
      title: '订单类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'user_id',
      title: '用户ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'invoice_type',
      title: '发票类型',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'title',
      title: '发票抬头',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'taxpayer_id',
      title: '纳税人识别号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'amount',
      title: '发票金额',
      minWidth: 100,
      sortable: true,
      formatter: ({ cellValue }) => `¥${cellValue}`,
    },
    {
      field: 'invoice_content',
      title: '发票内容',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'status',
      title: '发票状态',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'issue_time',
      title: '开具时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'pdf_url',
      title: 'PDF地址',
      minWidth: 200,
      showOverflow: true,
    },
    {
      field: 'create_time',
      title: '创建时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'update_time',
      title: '更新时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'remark',
      title: '备注',
      minWidth: 200,
      showOverflow: true,
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑发票',
  addText: '新增发票',
  excelName: '发票列表',
  excelAllName: '发票数据.xlsx',
  total: '发票数量: 10; 总金额: ¥1,730.00; 已开具: 7; 待开具: 2',
};
