/** 表格初始数据 - 改造为占道施工交通影响周度统计分析数据 */
export const dataList = () => [
  {
    timeRange: '2024-06-17 ~ 2024-06-23',
    region: '福州市鼓楼区',
    roadSection: '杨桥东路（东街口-五一广场）',
    roadOccupationType: '道路施工',
    controlTimePeriod: '工作日 07:00-09:00, 17:00-19:00',
    diversionPoint: '东街口地铁站B出口',
    complaintType: '交通拥堵, 噪音污染',
    weeklyAverageAffectedVehicles: 1250.5,
    weeklyAverageDelayTime: 8.5,
    weeklyTotalComplaints: 23,
    weeklyComplaintResolutionRate: 87.2,
    weeklyWorkOrderCompletionRate: 91.5,
    weeklyWorkOrderOvertimeRate: 12.8,
    equipmentOnlineRate: 96.8,
    weeklyComplianceRate: 85.5,
    weeklyAverageTrafficFlow: 3250,
    vehicleFlowChangeRate: 15.2,
    occupationArea: 180,
    affectedLanes: 2,
    peakHourCongestionIndex: 7.8,
    offPeakHourCongestionIndex: 4.2,
    momAffectedVehiclesChangeRate: 18.5,
    momDelayTimeChangeRate: -3.2,
    momComplaintsChangeRate: 22.1,
    momWorkOrderRateChangeRate: 5.8,
    yoyAffectedVehiclesChangeRate: 25.8,
    yoyDelayTimeChangeRate: 12.5,
    yoyComplaintsChangeRate: 30.2,
    yoyWorkOrderRateChangeRate: 8.9,
    complaintTypeDistribution: '交通拥堵: 15次；噪音污染: 6次；安全隐患: 2次',
    controlMeasureEffectiveness: 76.5,
    alternativeRouteUtilizationRate: 62.3,
    publicNotificationCoverage: 89.2,
    emergencyResponseTime: 15.8,
    constructionProgressCompletion: 78.5,
    safetyIncidentCount: 1,
    safetyIncidentRate: 0.3,
    environmentalImpactScore: 65,
    weeklyStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  }
];

/** 新增/修改的表单/列表的搜索表单 - 改造为占道施工交通影响周度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'timeRange',
      label: '时间范围',
      component: 'Input',
      componentProps: {
        placeholder: '请输入时间范围（如：2024-06-17 ~ 2024-06-23）',
        maxlength: 50,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'region',
      label: '区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域',
        maxlength: 50,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'roadSection',
      label: '路段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段',
        maxlength: 100,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'roadOccupationType',
      label: '占道类型',
      component: 'Input',
      componentProps: {
        placeholder: '请输入占道类型（如：道路施工、管线施工等）',
        maxlength: 50,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'controlTimePeriod',
      label: '管控时段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管控时段（如：工作日 07:00-09:00, 17:00-19:00）',
        maxlength: 100,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'diversionPoint',
      label: '疏导点',
      component: 'Input',
      componentProps: {
        placeholder: '请输入疏导点',
        maxlength: 100,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'complaintType',
      label: '投诉类型',
      component: 'Input',
      componentProps: {
        placeholder: '请输入投诉类型（如：交通拥堵, 噪音污染）',
        maxlength: 100,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'weeklyAverageAffectedVehicles',
      label: '周均影响车辆数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周均影响车辆数',
        min: 0,
        precision: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyAverageDelayTime',
      label: '周均延误时间(分钟)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周均延误时间',
        min: 0,
        precision: 1,
        addonAfter: '分钟',
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyTotalComplaints',
      label: '周投诉总数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周投诉总数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyComplaintResolutionRate',
      label: '投诉解决率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入投诉解决率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyWorkOrderCompletionRate',
      label: '工单完成率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入工单完成率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyWorkOrderOvertimeRate',
      label: '工单超时率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入工单超时率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'equipmentOnlineRate',
      label: '设备在线率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入设备在线率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyComplianceRate',
      label: '周达标率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周达标率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyAverageTrafficFlow',
      label: '周均车流量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周均车流量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'vehicleFlowChangeRate',
      label: '车流量变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入车流量变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'occupationArea',
      label: '占道面积(平方米)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入占道面积',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'affectedLanes',
      label: '影响车道数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入影响车道数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'peakHourCongestionIndex',
      label: '高峰拥堵指数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入高峰拥堵指数',
        min: 0,
        precision: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'offPeakHourCongestionIndex',
      label: '平峰拥堵指数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入平峰拥堵指数',
        min: 0,
        precision: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'momAffectedVehiclesChangeRate',
      label: '影响车辆数环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入影响车辆数环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momDelayTimeChangeRate',
      label: '延误时间环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入延误时间环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momComplaintsChangeRate',
      label: '投诉数环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入投诉数环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momWorkOrderRateChangeRate',
      label: '工单率环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入工单率环比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyAffectedVehiclesChangeRate',
      label: '影响车辆数同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入影响车辆数同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyDelayTimeChangeRate',
      label: '延误时间同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入延误时间同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyComplaintsChangeRate',
      label: '投诉数同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入投诉数同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyWorkOrderRateChangeRate',
      label: '工单率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入工单率同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'complaintTypeDistribution',
      label: '投诉类型分布',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入投诉类型分布（如：交通拥堵:15次；噪音污染:6次）',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'controlMeasureEffectiveness',
      label: '管控措施有效性(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入管控措施有效性',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'alternativeRouteUtilizationRate',
      label: '替代路线利用率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入替代路线利用率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'publicNotificationCoverage',
      label: '公众通知覆盖率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入公众通知覆盖率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'emergencyResponseTime',
      label: '应急响应时间(分钟)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入应急响应时间',
        min: 0,
        precision: 1,
        addonAfter: '分钟',
      },
      rules: 'required',
    },
    {
      fieldName: 'constructionProgressCompletion',
      label: '施工进度完成率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入施工进度完成率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'safetyIncidentCount',
      label: '安全事故数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入安全事故数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'safetyIncidentRate',
      label: '安全事故率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入安全事故率',
        min: 0,
        precision: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'environmentalImpactScore',
      label: '环境影响评分',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环境影响评分',
        min: 0,
        max: 100,
        precision: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'weeklyStatisticsPeriod',
      label: '周统计时段',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周统计时段',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为占道施工交通影响周度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'timeRange',
      title: '时间范围',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'region',
      title: '区域',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'roadSection',
      title: '路段',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'roadOccupationType',
      title: '占道类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'controlTimePeriod',
      title: '管控时段',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'diversionPoint',
      title: '疏导点',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'complaintType',
      title: '投诉类型',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'weeklyAverageAffectedVehicles',
      title: '周均影响车辆数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'weeklyAverageDelayTime',
      title: '周均延误时间(分钟)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'weeklyTotalComplaints',
      title: '周投诉总数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'weeklyComplaintResolutionRate',
      title: '投诉解决率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'weeklyWorkOrderCompletionRate',
      title: '工单完成率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'weeklyWorkOrderOvertimeRate',
      title: '工单超时率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'equipmentOnlineRate',
      title: '设备在线率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'weeklyComplianceRate',
      title: '周达标率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'weeklyAverageTrafficFlow',
      title: '周均车流量',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'vehicleFlowChangeRate',
      title: '车流量变化率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'occupationArea',
      title: '占道面积(平方米)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'affectedLanes',
      title: '影响车道数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'peakHourCongestionIndex',
      title: '高峰拥堵指数',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'offPeakHourCongestionIndex',
      title: '平峰拥堵指数',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'momAffectedVehiclesChangeRate',
      title: '影响车辆数环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momDelayTimeChangeRate',
      title: '延误时间环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momComplaintsChangeRate',
      title: '投诉数环比变化率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'momWorkOrderRateChangeRate',
      title: '工单率环比变化率(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'yoyAffectedVehiclesChangeRate',
      title: '影响车辆数同比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyDelayTimeChangeRate',
      title: '延误时间同比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyComplaintsChangeRate',
      title: '投诉数同比变化率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'yoyWorkOrderRateChangeRate',
      title: '工单率同比变化率(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'complaintTypeDistribution',
      title: '投诉类型分布',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'controlMeasureEffectiveness',
      title: '管控措施有效性(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'alternativeRouteUtilizationRate',
      title: '替代路线利用率(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'publicNotificationCoverage',
      title: '公众通知覆盖率(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'emergencyResponseTime',
      title: '应急响应时间(分钟)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'constructionProgressCompletion',
      title: '施工进度完成率(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'safetyIncidentCount',
      title: '安全事故数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'safetyIncidentRate',
      title: '安全事故率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'environmentalImpactScore',
      title: '环境影响评分',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'weeklyStatisticsPeriod',
      title: '周统计时段',
      minWidth: 140,
      sortable: false,
    },
  ];
}
