// data.js
/** 泊位利用率报表 - 初始数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "statCycle": "日",
      "startDate": "2026-02-05",
      "endDate": "2026-02-05",
      "areaName": "天河区",
      "parkType": "商业停车场",
      "spaceType": "标准泊位",
      "totalAvailableHours": 10800,
      "totalOccupiedHours": 7680,
      "utilizationRate": "71.11%",
      "peakHourUtilization": "85.50%",
      "avgUtilization": "71.11%",
      "lowHourUtilization": "45.20%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 2,
      "statCycle": "日",
      "startDate": "2026-02-05",
      "endDate": "2026-02-05",
      "areaName": "越秀区",
      "parkType": "路侧停车",
      "spaceType": "临时泊位",
      "totalAvailableHours": 6720,
      "totalOccupiedHours": 5040,
      "utilizationRate": "75.00%",
      "peakHourUtilization": "88.30%",
      "avgUtilization": "75.00%",
      "lowHourUtilization": "50.10%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 3,
      "statCycle": "日",
      "startDate": "2026-02-05",
      "endDate": "2026-02-05",
      "areaName": "海珠区",
      "parkType": "商业停车场",
      "spaceType": "充电泊位",
      "totalAvailableHours": 9120,
      "totalOccupiedHours": 6960,
      "utilizationRate": "76.32%",
      "peakHourUtilization": "90.10%",
      "avgUtilization": "76.32%",
      "lowHourUtilization": "52.80%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 4,
      "statCycle": "日",
      "startDate": "2026-02-05",
      "endDate": "2026-02-05",
      "areaName": "白云区",
      "parkType": "小区停车场",
      "spaceType": "标准泊位",
      "totalAvailableHours": 7680,
      "totalOccupiedHours": 5760,
      "utilizationRate": "75.00%",
      "peakHourUtilization": "87.60%",
      "avgUtilization": "75.00%",
      "lowHourUtilization": "48.90%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 5,
      "statCycle": "日",
      "startDate": "2026-02-05",
      "endDate": "2026-02-05",
      "areaName": "黄埔区",
      "parkType": "商业停车场",
      "spaceType": "无障碍泊位",
      "totalAvailableHours": 4320,
      "totalOccupiedHours": 3240,
      "utilizationRate": "75.00%",
      "peakHourUtilization": "86.70%",
      "avgUtilization": "75.00%",
      "lowHourUtilization": "49.50%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 6,
      "statCycle": "周",
      "startDate": "2026-01-29",
      "endDate": "2026-02-04",
      "areaName": "天河区",
      "parkType": "商业停车场",
      "spaceType": "标准泊位",
      "totalAvailableHours": 75600,
      "totalOccupiedHours": 52080,
      "utilizationRate": "68.89%",
      "peakHourUtilization": "83.20%",
      "avgUtilization": "68.89%",
      "lowHourUtilization": "42.10%",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 7,
      "statCycle": "周",
      "startDate": "2026-01-29",
      "endDate": "2026-02-04",
      "areaName": "越秀区",
      "parkType": "路侧停车",
      "spaceType": "临时泊位",
      "totalAvailableHours": 47040,
      "totalOccupiedHours": 34400,
      "utilizationRate": "73.21%",
      "peakHourUtilization": "85.80%",
      "avgUtilization": "73.21%",
      "lowHourUtilization": "46.50%",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 8,
      "statCycle": "月",
      "startDate": "2026-02-01",
      "endDate": "2026-02-29",
      "areaName": "天河区",
      "parkType": "商业停车场",
      "spaceType": "充电泊位",
      "totalAvailableHours": 48000,
      "totalOccupiedHours": 36000,
      "utilizationRate": "75.00%",
      "peakHourUtilization": "89.50%",
      "avgUtilization": "75.00%",
      "lowHourUtilization": "51.20%",
      "updateTime": "2026-02-03 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 9,
      "statCycle": "月",
      "startDate": "2026-02-01",
      "endDate": "2026-02-29",
      "areaName": "海珠区",
      "parkType": "商业停车场",
      "spaceType": "标准泊位",
      "totalAvailableHours": 91200,
      "totalOccupiedHours": 68400,
      "utilizationRate": "75.00%",
      "peakHourUtilization": "88.90%",
      "avgUtilization": "75.00%",
      "lowHourUtilization": "50.80%",
      "updateTime": "2026-02-03 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 10,
      "statCycle": "周",
      "startDate": "2026-01-22",
      "endDate": "2026-01-28",
      "areaName": "天河区",
      "parkType": "商业停车场",
      "spaceType": "标准泊位",
      "totalAvailableHours": 75600,
      "totalOccupiedHours": 54600,
      "utilizationRate": "72.22%",
      "peakHourUtilization": "84.60%",
      "avgUtilization": "72.22%",
      "lowHourUtilization": "44.30%",
      "updateTime": "2026-02-02 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 11,
      "statCycle": "月",
      "startDate": "2026-01-01",
      "endDate": "2026-01-31",
      "areaName": "荔湾区",
      "parkType": "路侧停车",
      "spaceType": "临时泊位",
      "totalAvailableHours": 52800,
      "totalOccupiedHours": 39600,
      "utilizationRate": "75.00%",
      "peakHourUtilization": "87.40%",
      "avgUtilization": "75.00%",
      "lowHourUtilization": "47.90%",
      "updateTime": "2026-02-01 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 12,
      "statCycle": "月",
      "startDate": "2026-01-01",
      "endDate": "2026-01-31",
      "areaName": "番禺区",
      "parkType": "小区停车场",
      "spaceType": "标准泊位",
      "totalAvailableHours": 67200,
      "totalOccupiedHours": 50400,
      "utilizationRate": "75.00%",
      "peakHourUtilization": "86.80%",
      "avgUtilization": "75.00%",
      "lowHourUtilization": "49.20%",
      "updateTime": "2026-02-01 18:30",
      "operator": "系统自动生成"
    }
  ];
};

/** 搜索表单配置 */
export function useFormSchema() {
  return [
    {
      fieldName: 'statCycle',
      label: '统计周期',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '日', value: '日' },
          { label: '周', value: '周' },
          { label: '月', value: '月' },
        ],
        placeholder: '请选择统计周期',
      },
      rules: 'required',
    },
    {
      fieldName: 'dateRange',
      label: '时间范围',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'daterange',
        startPlaceholder: '开始日期',
        endPlaceholder: '结束日期',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
      },
      fieldName: 'areaName',
      label: '行政区域',
    },
    {
      fieldName: 'parkType',
      label: '车场类型',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '商业停车场', value: '商业停车场' },
          { label: '路侧停车', value: '路侧停车' },
          { label: '小区停车场', value: '小区停车场' },
          { label: '景区停车场', value: '景区停车场' },
        ],
        placeholder: '请选择车场类型',
      },
    },
    {
      fieldName: 'spaceType',
      label: '泊位类型',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '标准泊位', value: '标准泊位' },
          { label: '临时泊位', value: '临时泊位' },
          { label: '充电泊位', value: '充电泊位' },
          { label: '无障碍泊位', value: '无障碍泊位' },
          { label: '货车泊位', value: '货车泊位' },
        ],
        placeholder: '请选择泊位类型',
      },
    },
  ];
}

/** 表格字段配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'statCycle',
      title: '统计周期',
      minWidth: 100,
      sortable: true,
      slots: { default: 'statCycle' },
    },
    {
      field: 'dateRange',
      title: '时间范围',
      minWidth: 180,
      sortable: true,
      slots: { default: 'dateRange' },
    },
    {
      field: 'areaName',
      title: '行政区域',
      minWidth: 100,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'parkType',
      title: '车场类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'spaceType',
      title: '泊位类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'totalAvailableHours',
      title: '总可用时长(小时)',
      minWidth: 150,
      sortable: true,
      slots: { default: 'totalAvailableHours' },
    },
    {
      field: 'totalOccupiedHours',
      title: '总占用时长(小时)',
      minWidth: 150,
      sortable: true,
      slots: { default: 'totalOccupiedHours' },
    },
    {
      field: 'utilizationRate',
      title: '利用率',
      minWidth: 100,
      sortable: true,
      slots: { default: 'utilizationRate' },
    },
    {
      field: 'peakHourUtilization',
      title: '高峰时段利用率',
      minWidth: 140,
      sortable: true,
      slots: { default: 'peakHourUtilization' },
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑报表',
  addText: '新增报表',
  excelName: '泊位利用率报表',
  excelAllName: '泊位利用率报表.xlsx',
  total: '报表总数: 12; 日统计数据: 5; 周统计数据: 3; 月统计数据: 4;',
};
