/** 表格初始数据 - 改造为占道经营年度统计分析数据 */
export const dataList = () => [
  {
    annualIllegalBusinessDisposalTotal: 1568,
    annualGuidancePointOperationTotal: 45,
    annualKeyAreaControlComplianceRate: 92.5,
    annualLawEnforcementEffectivenessRanking: 3,
    annualManagementInnovationEffectiveness: 85.2,
    yearOnYearDisposalTotalRate: 5.8,
    yearOnYearGuidancePointRate: 12.3,
    yearOnYearControlComplianceRate: 2.1,
    yearOnYearEffectivenessRankingChange: -1,
    yearOnYearInnovationEffectivenessRate: 15.6,
    regionalBreakdown: '鼓楼区: 456件；台江区: 389件；仓山区: 324件；晋安区: 289件；马尾区: 210件',
    monthlyTrend: '1月: 112件；2月: 98件；3月: 134件；4月: 145件；5月: 156件；6月: 167件；7月: 178件；8月: 165件；9月: 154件；10月: 143件；11月: 132件；12月: 122件',
    lawEnforcementTeamBreakdown: '一大队: 456件；二大队: 389件；三大队: 324件；四大队: 289件；五大队: 110件',
    innovationMeasuresBreakdown: '智能监控: 85.2%；网格管理: 78.9%；快速响应: 82.1%；联合执法: 79.5%',
    yearStatisticsPeriod: '2023-01-01 ~ 2023-12-31',
  },
  {
    annualIllegalBusinessDisposalTotal: 1489,
    annualGuidancePointOperationTotal: 40,
    annualKeyAreaControlComplianceRate: 90.4,
    annualLawEnforcementEffectivenessRanking: 2,
    annualManagementInnovationEffectiveness: 78.9,
    yearOnYearDisposalTotalRate: 8.2,
    yearOnYearGuidancePointRate: 15.6,
    yearOnYearControlComplianceRate: 3.2,
    yearOnYearEffectivenessRankingChange: 1,
    yearOnYearInnovationEffectivenessRate: 18.3,
    regionalBreakdown: '思明区: 423件；湖里区: 365件；集美区: 312件；海沧区: 245件；同安区: 144件',
    monthlyTrend: '1月: 105件；2月: 92件；3月: 128件；4月: 138件；5月: 148件；6月: 159件；7月: 169件；8月: 158件；9月: 147件；10月: 136件；11月: 125件；12月: 117件',
    lawEnforcementTeamBreakdown: 'A队: 423件；B队: 365件；C队: 312件；D队: 245件；E队: 110件',
    innovationMeasuresBreakdown: '视频巡查: 82.3%；定点管理: 75.6%；应急处理: 79.8%；协同管理: 76.2%',
    yearStatisticsPeriod: '2022-01-01 ~ 2022-12-31',
  },
  {
    annualIllegalBusinessDisposalTotal: 1372,
    annualGuidancePointOperationTotal: 35,
    annualKeyAreaControlComplianceRate: 87.3,
    annualLawEnforcementEffectivenessRanking: 4,
    annualManagementInnovationEffectiveness: 72.4,
    yearOnYearDisposalTotalRate: 12.1,
    yearOnYearGuidancePointRate: 18.9,
    yearOnYearControlComplianceRate: 4.5,
    yearOnYearEffectivenessRankingChange: -2,
    yearOnYearInnovationEffectivenessRate: 22.1,
    regionalBreakdown: '鲤城区: 389件；丰泽区: 334件；洛江区: 287件；泉港区: 213件；石狮市: 149件',
    monthlyTrend: '1月: 98件；2月: 85件；3月: 119件；4月: 129件；5月: 139件；6月: 149件；7月: 159件；8月: 148件；9月: 137件；10月: 126件；11月: 115件；12月: 105件',
    lawEnforcementTeamBreakdown: '一中队: 389件；二中队: 334件；三中队: 287件；四中队: 213件；五中队: 110件',
    innovationMeasuresBreakdown: '电子监管: 78.9%；区域划分: 72.1%；快速处置: 75.3%；联合行动: 70.8%',
    yearStatisticsPeriod: '2021-01-01 ~ 2021-12-31',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为占道经营年度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'annualIllegalBusinessDisposalTotal',
      label: '年度占道经营案件处置总量',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入年度占道经营案件处置总量',
        min: 0,
        precision: 0,
        addonAfter: '件',
      },
      rules: 'required',
    },
    {
      fieldName: 'annualGuidancePointOperationTotal',
      label: '年度疏导点运营总数',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入年度疏导点运营总数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'annualKeyAreaControlComplianceRate',
      label: '年度重点区域管控达标率',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入年度重点区域管控达标率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'annualLawEnforcementEffectivenessRanking',
      label: '年度执法队伍工作成效排名',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入年度执法队伍工作成效排名',
        min: 1,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'annualManagementInnovationEffectiveness',
      label: '年度占道经营管理创新举措成效',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入年度占道经营管理创新举措成效',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearDisposalTotalRate',
      label: '处置总量同比变化率',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入处置总量同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearGuidancePointRate',
      label: '疏导点运营数同比变化率',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入疏导点运营数同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearControlComplianceRate',
      label: '重点区域管控达标率同比变化率',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入重点区域管控达标率同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearEffectivenessRankingChange',
      label: '执法成效排名同比变化',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入执法成效排名同比变化',
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearInnovationEffectivenessRate',
      label: '创新举措成效同比变化率',
      component: 'InputNumber',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入创新举措成效同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'regionalBreakdown',
      label: '按区域拆分年度明细数据',
      component: 'Input',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入按区域拆分的年度明细数据及同比分析结果',
        maxlength: 500,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyTrend',
      label: '月度趋势分析',
      component: 'Input',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入月度趋势分析数据',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'lawEnforcementTeamBreakdown',
      label: '按执法队伍拆分年度明细数据',
      component: 'Input',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入按执法队伍拆分的年度明细数据及同比分析结果',
        maxlength: 400,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'innovationMeasuresBreakdown',
      label: '按创新举措拆分年度明细数据',
      component: 'Input',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入按创新举措拆分的年度明细数据及同比分析结果',
        maxlength: 400,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'yearStatisticsPeriod',
      label: '年度统计时段',
      component: 'Input',
      labelWidth: '200',
      componentProps: {
        placeholder: '请输入年度统计时段（如：2023-01-01 ~ 2023-12-31）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为占道经营年度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'annualIllegalBusinessDisposalTotal',
      title: '年度占道经营案件处置总量(件)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'annualGuidancePointOperationTotal',
      title: '年度疏导点运营总数(个)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'annualKeyAreaControlComplianceRate',
      title: '年度重点区域管控达标率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'annualLawEnforcementEffectivenessRanking',
      title: '年度执法队伍工作成效排名',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'annualManagementInnovationEffectiveness',
      title: '年度管理创新举措成效(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearOnYearDisposalTotalRate',
      title: '处置总量同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearOnYearGuidancePointRate',
      title: '疏导点运营数同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearOnYearControlComplianceRate',
      title: '重点区域管控达标率同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearOnYearEffectivenessRankingChange',
      title: '执法成效排名同比变化',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearOnYearInnovationEffectivenessRate',
      title: '创新举措成效同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'regionalBreakdown',
      title: '按区域拆分明细及同比分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'monthlyTrend',
      title: '月度趋势分析',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'lawEnforcementTeamBreakdown',
      title: '按执法队伍拆分明细及同比分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'innovationMeasuresBreakdown',
      title: '按创新举措拆分明细及同比分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'yearStatisticsPeriod',
      title: '年度统计时段',
      minWidth: 180,
      sortable: false,
    },
  ];
}
