/** 新增/修改的表单/列表的搜索表单 - 改造为道路预警管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'remainTime',
      label: '预警剩余时间',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入预警剩余时间（小时，可小数）',
        min: 0,
        precision: 1,
        addonAfter: '小时',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'id',
      label: '主键ID',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入主键ID',
        min: 0,
        precision: 0,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'warnNo',
      label: '预警编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入预警编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'facilityId',
      label: '设施ID',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入关联设施表ID',
        min: 0,
        precision: 0,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'facilityName',
      label: '预警路段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入预警路段',
        maxLength: 100,
      },
      labelWidth: '120',
      rules: 'required',
      isSearch: true,
    },
    {
      fieldName: 'facilityCode',
      label: '设施唯一编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入设施唯一编码',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'workOrderId',
      label: '工单ID',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入关联工单ID',
        min: 0,
        precision: 0,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'workOrderCode',
      label: '工单唯一编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入工单唯一编码',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'deviceId',
      label: '监测设备ID',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入关联监测设备ID',
        min: 0,
        precision: 0,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'deviceCode',
      label: '监测设备唯一编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测设备唯一编码',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'monitorId',
      label: '监测实时数据ID',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入关联监测实时数据ID',
        min: 0,
        precision: 0,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'monitorCode',
      label: '监测实时数据唯一编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测实时数据唯一编码',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '待处置', value: '待处置' },
          { label: '有效待派单', value: '有效待派单' },
          { label: '已派单', value: '已派单' },
          { label: '超时', value: '超时' },
          { label: '无效已归档', value: '无效已归档' },
        ],
        placeholder: '请选择预警状态',
        showSearch: true,
      },
      fieldName: 'status',
      label: '预警状态',
      rules: 'required',
      isSearch: true,
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未派单', value: 1 },
          { label: '已派单', value: 2 },
        ],
        placeholder: '请选择派单状态',
        showSearch: true,
      },
      fieldName: 'asignStatus',
      label: '派单状态',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [{ label: '道路', value: 2 }],
        placeholder: '请选择所属设施类型',
        showSearch: true,
      },
      fieldName: 'facilityType',
      label: '所属设施类型',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '坑洼数量超标', value: 1 },
          { label: '裂缝长度超标', value: 2 },
          { label: '路面温度超标', value: 3 },
          { label: '交通流量超标', value: 4 },
        ],
        placeholder: '请选择预警类型',
        showSearch: true,
      },
      fieldName: 'type',
      label: '预警类型',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [{ label: '自动/人工', value: 2 }],
        placeholder: '请选择预警方式',
        showSearch: true,
      },
      fieldName: 'level',
      label: '预警方式',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '一般/1-较重', value: 1 },
          { label: '严重/2-严重', value: 2 },
          { label: '严重/3-严重', value: 3 },
          { label: '紧急/4-紧急', value: 4 },
        ],
        placeholder: '请选择预警等级',
        showSearch: true,
      },
      fieldName: 'triggerTime',
      label: '预警等级',
      rules: 'required',
    },
    {
      fieldName: 'dealLimit',
      label: '预警处置时限',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入预警处置时限（单位：小时）',
        min: 0,
        precision: 0,
        addonAfter: '小时',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'overIndex',
      label: '超标指标',
      component: 'Input',
      componentProps: {
        placeholder: '请输入超标指标名称（如：坑洼数量、裂缝长度等）',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
      isSearch: true,
    },
    {
      fieldName: 'overValue',
      label: '超标数值',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入实际超标数值',
        min: 0,
        precision: 2,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'thresholdValue',
      label: '超标阈值数值',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入阈值',
        min: 0,
        precision: 2,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'confirmOpinion',
      label: '确认意见',
      component: 'Input',
      componentProps: {
        placeholder: '请输入确认意见',
        maxLength: 200,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'invalidReason',
      label: '无效原因',
      component: 'Input',
      componentProps: {
        placeholder: '请输入无效原因（如设备故障/数据波动/人为误触等）',
        maxLength: 200,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'suggest',
      label: '处理建议',
      component: 'Input',
      componentProps: {
        placeholder: '请输入系统或人工给出的处置建议',
        maxLength: 300,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'createTime',
      label: '创建时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择记录创建时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'extCommon1',
      label: '通用扩展字段1',
      component: 'Input',
      componentProps: {
        placeholder: '请输入通用扩展字段1',
        maxLength: 200,
      },
      labelWidth: '120',
    },
    {
      fieldName: 'extCommon2',
      label: '通用扩展字段2',
      component: 'Input',
      componentProps: {
        placeholder: '请输入通用扩展字段2',
        maxLength: 200,
      },
      labelWidth: '120',
    },
    {
      fieldName: 'extCommon3',
      label: '通用扩展字段3',
      component: 'Input',
      componentProps: {
        placeholder: '请输入通用扩展字段3',
        maxLength: 200,
      },
      labelWidth: '120',
    },
    {
      fieldName: 'extCommon4',
      label: '通用扩展字段4',
      component: 'Input',
      componentProps: {
        placeholder: '请输入通用扩展字段4',
        maxLength: 200,
      },
      labelWidth: '120',
    },
    {
      fieldName: 'startUpdateTime',
      label: '起始时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择起始时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
      isSearch: true,
    },
    {
      fieldName: 'endUpdateTime',
      label: '结束时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择结束时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
      isSearch: true,
    },
  ];
}
/** 表格字段 - 改造为道路预警管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'warnNo',
      title: '预警编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'warnNo' },
    },
    {
      field: 'facilityName',
      title: '预警路段',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'overIndex',
      title: '超标指标名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'overValue',
      title: '超标数值',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'thresholdValue',
      title: '闽值标准',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'triggerTime',
      title: '预警触发时间',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'status',
      title: '预警状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'deviceCode',
      title: '监测设备编号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'dealLimit',
      title: '预警处置时限(小时)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'remainTime',
      title: '剩余处置时间',
      minWidth: 140,
      sortable: true,
    },
     {
      field: 'monitorId',
      title: '关联检测数据id',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'assignStatus',
      title: '派单状态',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 160,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
