/** 表格初始数据 */
export const dataList = () => {
  return [
    {
      complaint_id: '220e8400-e29b-41d4-a716-446655440000',
      complaint_no: 'CP202310120001',
      complainant_id: 'USER001',
      complainant_phone: '13800138001',
      complaint_type: '服务投诉',
      related_asset_id: '',
      related_order_id: 'ORDER001',
      complaint_content: '工作人员服务态度差，处理问题不积极',
      complaint_time: '2023-10-12 09:30:00',
      status: '已办结',
      process_content: '已联系工作人员进行批评教育，并向投诉人道歉',
      process_by: 'ADMIN001',
      process_time: '2023-10-12 14:30:00',
      satisfaction: '满意',
      feedback_time: '2023-10-12 15:00:00',
      create_time: '2023-10-12 09:25:00',
      update_time: '2023-10-12 15:00:00',
      remark: '投诉人表示接受处理结果',
    },
    {
      complaint_id: '6ba7b828-9dad-11d1-80b4-00c04fd430c8',
      complaint_no: 'CP202310120002',
      complainant_id: 'USER002',
      complainant_phone: '13800138002',
      complaint_type: '设备故障',
      related_asset_id: 'ASSET001',
      related_order_id: '',
      complaint_content: '停车场出口道闸无法正常抬起，导致车辆堵塞',
      complaint_time: '2023-10-12 10:15:00',
      status: '已办结',
      process_content: '维修人员已到场检修，更换道闸控制器，恢复正常使用',
      process_by: 'ADMIN002',
      process_time: '2023-10-12 11:30:00',
      satisfaction: '非常满意',
      feedback_time: '2023-10-12 12:00:00',
      create_time: '2023-10-12 10:10:00',
      update_time: '2023-10-12 12:00:00',
      remark: '响应迅速，处理及时',
    },
    {
      complaint_id: '6ba7b829-9dad-11d1-80b4-00c04fd430c8',
      complaint_no: 'CP202310120003',
      complainant_id: 'USER003',
      complainant_phone: '13800138003',
      complaint_type: '收费争议',
      related_asset_id: '',
      related_order_id: 'ORDER003',
      complaint_content: '系统多收取停车费用，计费时间与实际不符',
      complaint_time: '2023-10-12 11:00:00',
      status: '已办结',
      process_content: '经核实，系统存在计费错误，已退还多收费用',
      process_by: 'ADMIN003',
      process_time: '2023-10-12 12:30:00',
      satisfaction: '满意',
      feedback_time: '2023-10-12 13:00:00',
      create_time: '2023-10-12 10:58:00',
      update_time: '2023-10-12 13:00:00',
      remark: '已退款处理',
    },
    {
      complaint_id: '6ba7b830-9dad-11d1-80b4-00c04fd430c8',
      complaint_no: 'CP202310120004',
      complainant_id: 'USER004',
      complainant_phone: '13800138004',
      complaint_type: '其他',
      related_asset_id: '',
      related_order_id: '',
      complaint_content: '停车场内标识不清晰，容易迷路',
      complaint_time: '2023-10-12 14:20:00',
      status: '处理中',
      process_content: '已安排人员对标识进行检查和优化',
      process_by: 'ADMIN004',
      process_time: '2023-10-12 15:20:00',
      satisfaction: '',
      feedback_time: '',
      create_time: '2023-10-12 14:18:00',
      update_time: '2023-10-12 15:20:00',
      remark: '需在一周内完成标识更新',
    },
    {
      complaint_id: '6ba7b831-9dad-11d1-80b4-00c04fd430c8',
      complaint_no: 'CP202310120005',
      complainant_id: 'USER005',
      complainant_phone: '13800138005',
      complaint_type: '设备故障',
      related_asset_id: 'ASSET002',
      related_order_id: 'ORDER005',
      complaint_content: '充电桩无法正常充电，显示故障代码E001',
      complaint_time: '2023-10-12 16:45:00',
      status: '待处理',
      process_content: '',
      process_by: '',
      process_time: '',
      satisfaction: '',
      feedback_time: '',
      create_time: '2023-10-12 16:40:00',
      update_time: '2023-10-12 16:40:00',
      remark: '紧急程度：中等',
    },
    {
      complaint_id: '6ba7b832-9dad-11d1-80b4-00c04fd430c8',
      complaint_no: 'CP202310130001',
      complainant_id: 'USER006',
      complainant_phone: '13800138006',
      complaint_type: '服务投诉',
      related_asset_id: '',
      related_order_id: 'ORDER006',
      complaint_content: '客服电话长时间无人接听',
      complaint_time: '2023-10-13 08:30:00',
      status: '已驳回',
      process_content:
        '经查询通话记录，当时客服正在处理其他紧急事务，并未出现无人接听情况',
      process_by: 'ADMIN005',
      process_time: '2023-10-13 09:30:00',
      satisfaction: '不满意',
      feedback_time: '2023-10-13 10:00:00',
      create_time: '2023-10-13 08:25:00',
      update_time: '2023-10-13 10:00:00',
      remark: '投诉人坚持认为电话未接通',
    },
    {
      complaint_id: '6ba7b833-9dad-11d1-80b4-00c04fd430c8',
      complaint_no: 'CP202310130002',
      complainant_id: 'USER007',
      complainant_phone: '13800138007',
      complaint_type: '收费争议',
      related_asset_id: '',
      related_order_id: 'ORDER007',
      complaint_content: '月卡续费价格突然上涨，未提前通知',
      complaint_time: '2023-10-13 10:00:00',
      status: '已办结',
      process_content: '价格调整已提前在官网和APP公告，符合规定',
      process_by: 'ADMIN006',
      process_time: '2023-10-13 11:00:00',
      satisfaction: '一般',
      feedback_time: '2023-10-13 11:30:00',
      create_time: '2023-10-13 09:55:00',
      update_time: '2023-10-13 11:30:00',
      remark: '建议加强通知渠道',
    },
    {
      complaint_id: '6ba7b834-9dad-11d1-80b4-00c04fd430c8',
      complaint_no: 'CP202310130003',
      complainant_id: 'USER008',
      complainant_phone: '13800138008',
      complaint_type: '设备故障',
      related_asset_id: 'ASSET003',
      related_order_id: '',
      complaint_content: '停车场入口摄像头无法识别车牌',
      complaint_time: '2023-10-13 12:30:00',
      status: '处理中',
      process_content: '技术人员已到场检查，发现摄像头镜头污损',
      process_by: 'ADMIN007',
      process_time: '2023-10-13 13:30:00',
      satisfaction: '',
      feedback_time: '',
      create_time: '2023-10-13 12:25:00',
      update_time: '2023-10-13 13:30:00',
      remark: '需更换摄像头镜头',
    },
    {
      complaint_id: '6ba7b835-9dad-11d1-80b4-00c04fd430c8',
      complaint_no: 'CP202310130004',
      complainant_id: 'USER009',
      complainant_phone: '13800138009',
      complaint_type: '其他',
      related_asset_id: '',
      related_order_id: 'ORDER009',
      complaint_content: '建议增加残疾人停车位',
      complaint_time: '2023-10-13 15:10:00',
      status: '已办结',
      process_content: '已记录建议，将在下一季度停车场改造时考虑增加',
      process_by: 'ADMIN008',
      process_time: '2023-10-13 16:10:00',
      satisfaction: '非常满意',
      feedback_time: '2023-10-13 16:30:00',
      create_time: '2023-10-13 15:05:00',
      update_time: '2023-10-13 16:30:00',
      remark: '建设性建议',
    },
    {
      complaint_id: '6ba7b836-9dad-11d1-80b4-00c04fd430c8',
      complaint_no: 'CP202310130005',
      complainant_id: 'USER010',
      complainant_phone: '13800138010',
      complaint_type: '服务投诉',
      related_asset_id: '',
      related_order_id: 'ORDER010',
      complaint_content: '清洁人员打扫时溅水到车辆上',
      complaint_time: '2023-10-13 17:30:00',
      status: '待处理',
      process_content: '',
      process_by: '',
      process_time: '',
      satisfaction: '',
      feedback_time: '',
      create_time: '2023-10-13 17:25:00',
      update_time: '2023-10-13 17:25:00',
      remark: '需在24小时内处理',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'complaint_id',
      label: '投诉ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入投诉ID',
      },
    },
    {
      fieldName: 'complaint_no',
      label: '投诉编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入投诉编号',
      },
    },
    {
      fieldName: 'complainant_id',
      label: '投诉人ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入投诉人ID',
      },
    },
    {
      fieldName: 'complainant_phone',
      label: '投诉人电话',
      component: 'Input',
      componentProps: {
        placeholder: '请输入投诉人电话',
      },
    },
    {
      fieldName: 'complaint_type',
      label: '投诉类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择投诉类型',
        options: [
          { label: '服务投诉', value: '服务投诉' },
          { label: '设备故障', value: '设备故障' },
          { label: '收费争议', value: '收费争议' },
          { label: '其他', value: '其他' },
        ],
      },
    },
    {
      fieldName: 'related_asset_id',
      label: '关联资产ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联资产ID（可为空）',
      },
    },
    {
      fieldName: 'related_order_id',
      label: '关联订单ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联订单ID（可为空）',
      },
    },
    {
      fieldName: 'complaint_content',
      label: '投诉内容',
      component: 'Input',
      componentProps: {
        placeholder: '请输入投诉内容',
        type: 'textarea',
        rows: 3,
      },
    },
    {
      fieldName: 'complaint_time',
      label: '投诉时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择投诉时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'status',
      label: '处理状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择处理状态',
        options: [
          { label: '待处理', value: '待处理' },
          { label: '处理中', value: '处理中' },
          { label: '已办结', value: '已办结' },
          { label: '已驳回', value: '已驳回' },
        ],
      },
    },
    {
      fieldName: 'process_content',
      label: '处理内容',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处理内容',
        type: 'textarea',
        rows: 3,
      },
    },
    {
      fieldName: 'process_by',
      label: '处理人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处理人ID',
      },
    },
    {
      fieldName: 'process_time',
      label: '处理时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择处理时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'satisfaction',
      label: '满意度',
      component: 'Select',
      componentProps: {
        placeholder: '请选择满意度（可为空）',
        options: [
          { label: '非常满意', value: '非常满意' },
          { label: '满意', value: '满意' },
          { label: '一般', value: '一般' },
          { label: '不满意', value: '不满意' },
          { label: '非常不满意', value: '非常不满意' },
        ],
      },
    },
    {
      fieldName: 'feedback_time',
      label: '反馈时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择反馈时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'create_time',
      label: '创建时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择创建时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'update_time',
      label: '更新时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择更新时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Input',
      componentProps: {
        placeholder: '请输入备注',
        type: 'textarea',
        rows: 3,
      },
    },
  ];
}

/** 表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'complaint_no',
      title: '投诉编号',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'complainant_id',
      title: '投诉人ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'complainant_phone',
      title: '投诉人电话',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'complaint_type',
      title: '投诉类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'related_asset_id',
      title: '关联资产',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'related_order_id',
      title: '关联订单',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'complaint_content',
      title: '投诉内容',
      minWidth: 200,
      showOverflow: true,
    },
    {
      field: 'complaint_time',
      title: '投诉时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'status',
      title: '处理状态',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'process_content',
      title: '处理内容',
      minWidth: 180,
      showOverflow: true,
    },
    {
      field: 'process_by',
      title: '处理人',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'process_time',
      title: '处理时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'satisfaction',
      title: '满意度',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'feedback_time',
      title: '反馈时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'create_time',
      title: '创建时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'update_time',
      title: '更新时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'remark',
      title: '备注',
      minWidth: 150,
      showOverflow: true,
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑投诉记录',
  addText: '新增投诉记录',
  excelName: '投诉管理列表',
  excelAllName: '投诉管理数据.xlsx',
  total: '投诉数量: 10; 待处理: 2; 处理中: 2; 已办结: 5; 已驳回: 1',
};
