/** 表格初始数据 - 供热管网监测数据 */
export const dataList = () => [
  {
    id: '1',
    heatArea: '福州市鼓楼区供热管网',
    tempDifference: 15.5,
    pipePressure: 2.5,
    pipeFlow: 120,
    seasonType: '冬季',
    deviceCode: 'DEV-HT-202406-001',
    deviceStatus: '在线',
    staffName: '张三（工号：FJHT001）',
    collectFrequency: '5分钟',
    monitorStatus: '运行中',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 3,
    updateTime: '2024-06-15 14:30:00',
    seasonSwitch: '开启',
    warnStatus: '正常',
  },
  {
    id: '2',
    heatArea: '厦门市思明区供热管网',
    tempDifference: 14.8,
    pipePressure: 2.3,
    pipeFlow: 110,
    seasonType: '冬季',
    deviceCode: 'DEV-HT-202406-002',
    deviceStatus: '在线',
    staffName: '李四（工号：FJHT002）',
    collectFrequency: '10分钟',
    monitorStatus: '运行中',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 5,
    updateTime: '2024-06-15 14:25:00',
    seasonSwitch: '开启',
    warnStatus: '正常',
  },
  {
    id: '3',
    heatArea: '泉州市丰泽区供热管网',
    tempDifference: 8.2,
    pipePressure: 1.8,
    pipeFlow: 80,
    seasonType: '夏季',
    deviceCode: 'DEV-HT-202406-003',
    deviceStatus: '在线',
    staffName: '王五（工号：FJHT003）',
    collectFrequency: '1分钟',
    monitorStatus: '运行中',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 2,
    updateTime: '2024-06-15 14:32:00',
    seasonSwitch: '关闭',
    warnStatus: '异常',
  },
  {
    id: '4',
    heatArea: '漳州市芗城区供热管网',
    tempDifference: 16.5,
    pipePressure: 2.6,
    pipeFlow: 130,
    seasonType: '冬季',
    deviceCode: 'DEV-HT-202406-004',
    deviceStatus: '在线',
    staffName: '赵六（工号：FJHT004）',
    collectFrequency: '30分钟',
    monitorStatus: '运行中',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 4,
    updateTime: '2024-06-15 14:20:00',
    seasonSwitch: '开启',
    warnStatus: '正常',
  },
  {
    id: '5',
    heatArea: '莆田市城厢区供热管网',
    tempDifference: 15.9,
    pipePressure: 2.4,
    pipeFlow: 125,
    seasonType: '冬季',
    deviceCode: 'DEV-HT-202406-005',
    deviceStatus: '离线',
    staffName: '孙七（工号：FJHT005）',
    collectFrequency: '1小时',
    monitorStatus: '已停止',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 6,
    updateTime: '2024-06-15 13:45:00',
    seasonSwitch: '开启',
    warnStatus: '正常',
  },
  {
    id: '6',
    heatArea: '宁德市蕉城区供热管网',
    tempDifference: 13.8,
    pipePressure: 2.2,
    pipeFlow: 105,
    seasonType: '冬季',
    deviceCode: 'DEV-HT-202406-006',
    deviceStatus: '在线',
    staffName: '周八（工号：FJHT006）',
    collectFrequency: '5分钟',
    monitorStatus: '运行中',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 3,
    updateTime: '2024-06-15 14:28:00',
    seasonSwitch: '开启',
    warnStatus: '正常',
  },
  {
    id: '7',
    heatArea: '龙岩市新罗区供热管网',
    tempDifference: 7.5,
    pipePressure: 1.7,
    pipeFlow: 75,
    seasonType: '夏季',
    deviceCode: 'DEV-HT-202406-007',
    deviceStatus: '在线',
    staffName: '吴九（工号：FJHT007）',
    collectFrequency: '10分钟',
    monitorStatus: '运行中',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 4,
    updateTime: '2024-06-15 14:31:00',
    seasonSwitch: '关闭',
    warnStatus: '异常',
  },
  {
    id: '8',
    heatArea: '三明市梅列区供热管网',
    tempDifference: 14.2,
    pipePressure: 2.3,
    pipeFlow: 115,
    seasonType: '冬季',
    deviceCode: 'DEV-HT-202406-008',
    deviceStatus: '在线',
    staffName: '郑十（工号：FJHT008）',
    collectFrequency: '30分钟',
    monitorStatus: '运行中',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 5,
    updateTime: '2024-06-15 14:15:00',
    seasonSwitch: '开启',
    warnStatus: '正常',
  },
  {
    id: '9',
    heatArea: '南平市延平区供热管网',
    tempDifference: 15.7,
    pipePressure: 2.4,
    pipeFlow: 122,
    seasonType: '冬季',
    deviceCode: 'DEV-HT-202406-009',
    deviceStatus: '异常',
    staffName: '王十一（工号：FJHT009）',
    collectFrequency: '1分钟',
    monitorStatus: '已停止',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 2,
    updateTime: '2024-06-15 13:50:00',
    seasonSwitch: '开启',
    warnStatus: '正常',
  },
  {
    id: '10',
    heatArea: '平潭综合实验区供热管网',
    tempDifference: 16.3,
    pipePressure: 2.5,
    pipeFlow: 128,
    seasonType: '冬季',
    deviceCode: 'DEV-HT-202406-010',
    deviceStatus: '在线',
    staffName: '李十二（工号：FJHT010）',
    collectFrequency: '1小时',
    monitorStatus: '运行中',
    winterTempDiffThreshold: '10-20℃',
    nonWinterTempDiffThreshold: '5-10℃',
    pipePressureThreshold: '2.0-3.0MPa',
    pipeFlowThreshold: '100-150m³/h',
    syncDuration: 6,
    updateTime: '2024-06-15 14:00:00',
    seasonSwitch: '开启',
    warnStatus: '正常',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 供热管网监测配置表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'heatArea',
      label: '供热区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入供热区域',
        maxLength: 100,
      },
      labelWidth: '100',
      rules: 'required', // 供热区域为必填项
    },
    {
      fieldName: 'deviceCode',
      label: '监测设备编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测设备编号',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 监测设备编号为必填项
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '1分钟', value: '1分钟' },
          { label: '5分钟', value: '5分钟' },
          { label: '10分钟', value: '10分钟' },
          { label: '30分钟', value: '30分钟' },
          { label: '1小时', value: '1小时' },
          { label: '24小时', value: '24小时' },
        ],
        placeholder: '请选择数据采集频率',
        showSearch: true,
      },
      fieldName: 'collectFrequency',
      label: '数据采集频率',
      rules: 'required', // 数据采集频率为必填项
    },
    {
      fieldName: 'winterTempDiffThreshold',
      label: '冬季温差阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入冬季温差阈值（如：10-20℃）',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 冬季温差阈值为必填项
    },
    {
      fieldName: 'nonWinterTempDiffThreshold',
      label: '非冬季温差阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入非冬季温差阈值（如：5-10℃）',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 非冬季温差阈值为必填项
    },
    {
      fieldName: 'pipePressureThreshold',
      label: '管网压力阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管网压力阈值（如：2.0-3.0MPa）',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 管网压力阈值为必填项
    },
    {
      fieldName: 'pipeFlowThreshold',
      label: '管网流量阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管网流量阈值（如：100-150m³/h）',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 管网流量阈值为必填项
    },
    {
      fieldName: 'staffName',
      label: '负责检修员',
      component: 'Input',
      componentProps: {
        placeholder: '请输入负责检修员姓名/工号',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 负责检修员为必填项
    },
  ];
}

/** 筛选表单schema - 供热管网监测筛选表单 */
export function useFilterFormSchema() {
  return [
    {
      fieldName: 'heatArea',
      label: '供热区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入供热区域',
        maxLength: 100,
      },
      labelWidth: '100',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '冬季', value: '冬季' },
          { label: '夏季', value: '夏季' },
          { label: '春季', value: '春季' },
          { label: '秋季', value: '秋季' },
        ],
        placeholder: '请选择季节类型',
        showSearch: true,
      },
      fieldName: 'seasonType',
      label: '季节类型',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceStatus',
      label: '设备在线状态',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '运行中', value: '运行中' },
          { label: '已停止', value: '已停止' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择监测状态',
        showSearch: true,
      },
      fieldName: 'monitorStatus',
      label: '监测状态',
    },
  ];
}

/** 表格字段 - 供热管网监测表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'heatArea',
      title: '供热区域',
      minWidth: 200,
      sortable: true,
      slots: { default: 'heatArea' },
    },
    {
      field: 'tempDifference',
      title: '供回水温差(℃)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'pipePressure',
      title: '管网压力(MPa)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'pipeFlow',
      title: '管网流量(m³/h)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'seasonType',
      title: '季节类型',
      minWidth: 100,
      sortable: true,
      slots: { default: 'seasonType' },
    },
    {
      field: 'deviceCode',
      title: '监测设备编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'deviceCode' },
    },
    {
      field: 'deviceStatus',
      title: '设备在线状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'deviceStatus' },
    },
    {
      field: 'staffName',
      title: '负责检修员',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'collectFrequency',
      title: '数据采集频率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monitorStatus',
      title: '监测状态',
      minWidth: 180,
      sortable: true,
      slots: { default: 'monitorStatus' },
    },
    {
      field: 'winterTempDiffThreshold',
      title: '冬季温差阈值',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'nonWinterTempDiffThreshold',
      title: '非冬季温差阈值',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'pipePressureThreshold',
      title: '管网压力阈值',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'pipeFlowThreshold',
      title: '管网流量阈值',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'syncDuration',
      title: '数据同步时长(秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'updateTime',
      title: '最近更新时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'seasonSwitch',
      title: '季节阈值开关',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'warnStatus',
      title: '预警触发标识',
      minWidth: 120,
      sortable: true,
      slots: { default: 'warnStatus' },
    },
    {
      title: '操作',
      width: 120,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
