// data.js
/** 设备运行报表 - 初始数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "statDate": "2026-02-05",
      "areaName": "天河区",
      "deviceType": "摄像头",
      "status": "在线",
      "totalDevice": 450,
      "onlineDevice": 420,
      "normalDevice": 410,
      "offlineDevice": 30,
      "faultDevice": 10,
      "onlineRate": "93.33%",
      "normalRate": "91.11%",
      "faultRate": "2.22%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 2,
      "statDate": "2026-02-05",
      "areaName": "越秀区",
      "deviceType": "道闸",
      "status": "在线",
      "totalDevice": 280,
      "onlineDevice": 260,
      "normalDevice": 255,
      "offlineDevice": 20,
      "faultDevice": 5,
      "onlineRate": "92.86%",
      "normalRate": "91.07%",
      "faultRate": "1.79%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 3,
      "statDate": "2026-02-05",
      "areaName": "海珠区",
      "deviceType": "地磁",
      "status": "在线",
      "totalDevice": 380,
      "onlineDevice": 355,
      "normalDevice": 350,
      "offlineDevice": 25,
      "faultDevice": 5,
      "onlineRate": "93.42%",
      "normalRate": "92.11%",
      "faultRate": "1.32%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 4,
      "statDate": "2026-02-05",
      "areaName": "白云区",
      "deviceType": "充电桩",
      "status": "在线",
      "totalDevice": 320,
      "onlineDevice": 300,
      "normalDevice": 295,
      "offlineDevice": 20,
      "faultDevice": 5,
      "onlineRate": "93.75%",
      "normalRate": "92.19%",
      "faultRate": "1.56%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 5,
      "statDate": "2026-02-05",
      "areaName": "黄埔区",
      "deviceType": "显示屏",
      "status": "在线",
      "totalDevice": 180,
      "onlineDevice": 170,
      "normalDevice": 168,
      "offlineDevice": 10,
      "faultDevice": 2,
      "onlineRate": "94.44%",
      "normalRate": "93.33%",
      "faultRate": "1.11%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 6,
      "statDate": "2026-02-04",
      "areaName": "天河区",
      "deviceType": "摄像头",
      "status": "在线",
      "totalDevice": 450,
      "onlineDevice": 415,
      "normalDevice": 405,
      "offlineDevice": 35,
      "faultDevice": 10,
      "onlineRate": "92.22%",
      "normalRate": "90.00%",
      "faultRate": "2.22%",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 7,
      "statDate": "2026-02-04",
      "areaName": "越秀区",
      "deviceType": "道闸",
      "status": "在线",
      "totalDevice": 280,
      "onlineDevice": 255,
      "normalDevice": 250,
      "offlineDevice": 25,
      "faultDevice": 5,
      "onlineRate": "91.07%",
      "normalRate": "89.29%",
      "faultRate": "1.79%",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 8,
      "statDate": "2026-02-03",
      "areaName": "天河区",
      "deviceType": "地磁",
      "status": "在线",
      "totalDevice": 200,
      "onlineDevice": 185,
      "normalDevice": 180,
      "offlineDevice": 15,
      "faultDevice": 5,
      "onlineRate": "92.50%",
      "normalRate": "90.00%",
      "faultRate": "2.50%",
      "updateTime": "2026-02-03 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 9,
      "statDate": "2026-02-03",
      "areaName": "海珠区",
      "deviceType": "充电桩",
      "status": "在线",
      "totalDevice": 380,
      "onlineDevice": 360,
      "normalDevice": 355,
      "offlineDevice": 20,
      "faultDevice": 5,
      "onlineRate": "94.74%",
      "normalRate": "93.42%",
      "faultRate": "1.32%",
      "updateTime": "2026-02-03 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 10,
      "statDate": "2026-02-02",
      "areaName": "天河区",
      "deviceType": "摄像头",
      "status": "在线",
      "totalDevice": 450,
      "onlineDevice": 425,
      "normalDevice": 415,
      "offlineDevice": 25,
      "faultDevice": 10,
      "onlineRate": "94.44%",
      "normalRate": "92.22%",
      "faultRate": "2.22%",
      "updateTime": "2026-02-02 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 11,
      "statDate": "2026-02-01",
      "areaName": "荔湾区",
      "deviceType": "道闸",
      "status": "在线",
      "totalDevice": 220,
      "onlineDevice": 205,
      "normalDevice": 200,
      "offlineDevice": 15,
      "faultDevice": 5,
      "onlineRate": "93.18%",
      "normalRate": "90.91%",
      "faultRate": "2.27%",
      "updateTime": "2026-02-01 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 12,
      "statDate": "2026-02-01",
      "areaName": "番禺区",
      "deviceType": "显示屏",
      "status": "在线",
      "totalDevice": 280,
      "onlineDevice": 265,
      "normalDevice": 260,
      "offlineDevice": 15,
      "faultDevice": 5,
      "onlineRate": "94.64%",
      "normalRate": "92.86%",
      "faultRate": "1.79%",
      "updateTime": "2026-02-01 18:30",
      "operator": "系统自动生成"
    }
  ];
};

/** 搜索表单配置 */
export function useFormSchema() {
  return [
    {
      fieldName: 'statDate',
      label: '统计日期',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'date',
        placeholder: '请选择统计日期',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceType',
      label: '设备类型',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '摄像头', value: '摄像头' },
          { label: '道闸', value: '道闸' },
          { label: '地磁', value: '地磁' },
          { label: '充电桩', value: '充电桩' },
          { label: '显示屏', value: '显示屏' },
          { label: '监控主机', value: '监控主机' },
          { label: '服务器', value: '服务器' },
        ],
        placeholder: '请选择设备类型',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
      },
      fieldName: 'areaName',
      label: '行政区域',
    },
    {
      fieldName: 'status',
      label: '运行状态',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '故障', value: '故障' },
          { label: '维护中', value: '维护中' },
          { label: '待机', value: '待机' },
        ],
        placeholder: '请选择运行状态',
      },
    },
  ];
}

/** 表格字段配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'statDate',
      title: '统计日期',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'areaName',
      title: '行政区域',
      minWidth: 100,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'deviceType',
      title: '设备类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'deviceType' },
    },
    {
      field: 'status',
      title: '运行状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'status' },
    },
    {
      field: 'totalDevice',
      title: '总设备数',
      minWidth: 100,
      sortable: true,
      slots: { default: 'totalDevice' },
    },
    {
      field: 'onlineDevice',
      title: '在线设备数',
      minWidth: 120,
      sortable: true,
      slots: { default: 'onlineDevice' },
    },
    {
      field: 'normalDevice',
      title: '正常运行数',
      minWidth: 120,
      sortable: true,
      slots: { default: 'normalDevice' },
    },
    {
      field: 'offlineDevice',
      title: '离线数',
      minWidth: 100,
      sortable: true,
      slots: { default: 'offlineDevice' },
    },
    {
      field: 'faultDevice',
      title: '故障数',
      minWidth: 100,
      sortable: true,
      slots: { default: 'faultDevice' },
    },
    {
      field: 'onlineRate',
      title: '在线率',
      minWidth: 100,
      sortable: true,
      slots: { default: 'onlineRate' },
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑报表',
  addText: '新增报表',
  excelName: '设备运行报表',
  excelAllName: '设备运行报表.xlsx',
  total: '报表总数: 12; 今日数据: 5; 本周数据: 10;',
};
