/** 表格初始数据 - 改造为道路监测季度统计分析数据 */
export const dataList = () => [
  {
    roadSectionName: '福州市鼓楼区杨桥东路（东街口-五一广场）',
    areaName: '福州市鼓楼区',
    potholeCountQuarterAvg: 5.6,
    crackLengthQuarterAvg: 9.4,
    quarterTotalWarningCount: 72,
    quarterWorkOrderCount: 58,
    quarterDisposalEfficiency: 92.8,
    quarterDisposalComplianceRate: 90.5,
    deviceQuarterOnlineRate: 97.2,
    potholeCountMomChangeRate: 7.8,
    potholeCountYoYChangeRate: 12.5,
    crackLengthMomChangeRate: -4.2,
    crackLengthYoYChangeRate: 5.8,
    areaFacilityHealthRank: 3,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio:
      '坑洼超标: 65%, 裂缝超标: 25%, 温度异常: 8%, 流量异常: 2%',
  },
  {
    roadSectionName: '厦门市思明区鹭江道（轮渡码头-中山路）',
    areaName: '厦门市思明区',
    potholeCountQuarterAvg: 2.3,
    crackLengthQuarterAvg: 3.6,
    quarterTotalWarningCount: 35,
    quarterWorkOrderCount: 28,
    quarterDisposalEfficiency: 98.5,
    quarterDisposalComplianceRate: 98.2,
    deviceQuarterOnlineRate: 99.1,
    potholeCountMomChangeRate: -5.5,
    potholeCountYoYChangeRate: -9,
    crackLengthMomChangeRate: 2.1,
    crackLengthYoYChangeRate: -2,
    areaFacilityHealthRank: 1,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio:
      '坑洼超标: 40%, 裂缝超标: 35%, 温度异常: 20%, 流量异常: 5%',
  },
  {
    roadSectionName: '泉州市丰泽区刺桐路（湖心街-泉秀街）',
    areaName: '泉州市丰泽区',
    potholeCountQuarterAvg: 11.8,
    crackLengthQuarterAvg: 18.1,
    quarterTotalWarningCount: 145,
    quarterWorkOrderCount: 120,
    quarterDisposalEfficiency: 75.2,
    quarterDisposalComplianceRate: 74,
    deviceQuarterOnlineRate: 86.8,
    potholeCountMomChangeRate: 24.5,
    potholeCountYoYChangeRate: 30.8,
    crackLengthMomChangeRate: 19.5,
    crackLengthYoYChangeRate: 22.5,
    areaFacilityHealthRank: 9,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio:
      '坑洼超标: 75%, 裂缝超标: 20%, 温度异常: 3%, 流量异常: 2%',
  },
  {
    roadSectionName: '漳州市芗城区胜利路（延安北路-新华西路）',
    areaName: '漳州市芗城区',
    potholeCountQuarterAvg: 0.4,
    crackLengthQuarterAvg: 1.4,
    quarterTotalWarningCount: 0,
    quarterWorkOrderCount: 0,
    quarterDisposalEfficiency: 100,
    quarterDisposalComplianceRate: 100,
    deviceQuarterOnlineRate: 98.8,
    potholeCountMomChangeRate: -10.5,
    potholeCountYoYChangeRate: -16,
    crackLengthMomChangeRate: -8.5,
    crackLengthYoYChangeRate: -11.5,
    areaFacilityHealthRank: 2,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio: '无预警数据',
  },
  {
    roadSectionName: '莆田市城厢区荔城南大道（凤凰山-万达广场）',
    areaName: '莆田市城厢区',
    potholeCountQuarterAvg: 8,
    crackLengthQuarterAvg: 14.5,
    quarterTotalWarningCount: 98,
    quarterWorkOrderCount: 85,
    quarterDisposalEfficiency: 83.5,
    quarterDisposalComplianceRate: 81.5,
    deviceQuarterOnlineRate: 78.5,
    potholeCountMomChangeRate: 12,
    potholeCountYoYChangeRate: 18.5,
    crackLengthMomChangeRate: 10.8,
    crackLengthYoYChangeRate: 15.5,
    areaFacilityHealthRank: 7,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio:
      '坑洼超标: 70%, 裂缝超标: 25%, 温度异常: 3%, 流量异常: 2%',
  },
  {
    roadSectionName: '宁德市蕉城区闽东中路（市政府-万达广场）',
    areaName: '宁德市蕉城区',
    potholeCountQuarterAvg: 5.1,
    crackLengthQuarterAvg: 8,
    quarterTotalWarningCount: 46,
    quarterWorkOrderCount: 38,
    quarterDisposalEfficiency: 94.2,
    quarterDisposalComplianceRate: 94,
    deviceQuarterOnlineRate: 97,
    potholeCountMomChangeRate: 5.2,
    potholeCountYoYChangeRate: 8.8,
    crackLengthMomChangeRate: -2,
    crackLengthYoYChangeRate: 2.2,
    areaFacilityHealthRank: 4,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio:
      '坑洼超标: 60%, 裂缝超标: 30%, 温度异常: 8%, 流量异常: 2%',
  },
  {
    roadSectionName: '龙岩市新罗区龙川路（中山路-登高西路）',
    areaName: '龙岩市新罗区',
    potholeCountQuarterAvg: 9.8,
    crackLengthQuarterAvg: 14.8,
    quarterTotalWarningCount: 115,
    quarterWorkOrderCount: 98,
    quarterDisposalEfficiency: 88,
    quarterDisposalComplianceRate: 87,
    deviceQuarterOnlineRate: 96.5,
    potholeCountMomChangeRate: 19,
    potholeCountYoYChangeRate: 25.5,
    crackLengthMomChangeRate: 13.2,
    crackLengthYoYChangeRate: 18.8,
    areaFacilityHealthRank: 6,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio:
      '坑洼超标: 68%, 裂缝超标: 28%, 温度异常: 3%, 流量异常: 1%',
  },
  {
    roadSectionName: '三明市梅列区列东街（东新四路-东新六路）',
    areaName: '三明市梅列区',
    potholeCountQuarterAvg: 4.3,
    crackLengthQuarterAvg: 6.6,
    quarterTotalWarningCount: 25,
    quarterWorkOrderCount: 20,
    quarterDisposalEfficiency: 98.8,
    quarterDisposalComplianceRate: 98.5,
    deviceQuarterOnlineRate: 98.2,
    potholeCountMomChangeRate: -4.8,
    potholeCountYoYChangeRate: -7.5,
    crackLengthMomChangeRate: -5.8,
    crackLengthYoYChangeRate: -9,
    areaFacilityHealthRank: 5,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio:
      '坑洼超标: 55%, 裂缝超标: 35%, 温度异常: 8%, 流量异常: 2%',
  },
  {
    roadSectionName: '南平市延平区八一路（江滨路-中山路）',
    areaName: '南平市延平区',
    potholeCountQuarterAvg: 7.3,
    crackLengthQuarterAvg: 11,
    quarterTotalWarningCount: 85,
    quarterWorkOrderCount: 72,
    quarterDisposalEfficiency: 78.5,
    quarterDisposalComplianceRate: 77.5,
    deviceQuarterOnlineRate: 88.5,
    potholeCountMomChangeRate: 10.5,
    potholeCountYoYChangeRate: 16,
    crackLengthMomChangeRate: 8,
    crackLengthYoYChangeRate: 11.8,
    areaFacilityHealthRank: 8,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio:
      '坑洼超标: 72%, 裂缝超标: 22%, 温度异常: 4%, 流量异常: 2%',
  },
  {
    roadSectionName: '平潭综合实验区金井大道（管委会-龙凤头沙滩）',
    areaName: '平潭综合实验区',
    potholeCountQuarterAvg: 1.1,
    crackLengthQuarterAvg: 3,
    quarterTotalWarningCount: 42,
    quarterWorkOrderCount: 32,
    quarterDisposalEfficiency: 98.6,
    quarterDisposalComplianceRate: 98,
    deviceQuarterOnlineRate: 99.5,
    potholeCountMomChangeRate: -3.2,
    potholeCountYoYChangeRate: -6.5,
    crackLengthMomChangeRate: 4.2,
    crackLengthYoYChangeRate: 1.8,
    areaFacilityHealthRank: 10,
    quarterStatisticsPeriod: '2024-Q2（2024-04-01 ~ 2024-06-30）',
    warningTypeDistributionRatio:
      '坑洼超标: 45%, 裂缝超标: 30%, 温度异常: 20%, 流量异常: 5%',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为道路监测季度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'roadSectionName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
      },
      labelWidth: '160',
      rules: 'required', // 路段名称为必填项
    },
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称（如：福州市鼓楼区）',
      },
      labelWidth: '160',
      rules: 'required',
    },
    {
      fieldName: 'potholeCountQuarterAvg',
      label: '坑洼数量季度均值',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入坑洼数量季度均值',
        min: 0,
        precision: 1, // 保留1位小数，贴合季度均值统计场景
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthQuarterAvg',
      label: '裂缝长度季度均值',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入裂缝长度季度均值（单位：米）',
        min: 0,
        precision: 1,
        addonAfter: '米',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterTotalWarningCount',
      label: '季度累计预警数',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入季度累计预警数',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterWorkOrderCount',
      label: '季度工单量',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入季度工单量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterDisposalEfficiency',
      label: '季度处置效率',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入季度处置效率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterDisposalComplianceRate',
      label: '季度处置达标率',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入季度处置达标率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceQuarterOnlineRate',
      label: '设备季度在线率',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入设备季度在线率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountMomChangeRate',
      label: '坑洼数量环比变化率',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入坑洼数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountYoYChangeRate',
      label: '坑洼数量同比变化率',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入坑洼数量同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthMomChangeRate',
      label: '裂缝长度环比变化率',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入裂缝长度环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthYoYChangeRate',
      label: '裂缝长度同比变化率',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入裂缝长度同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'areaFacilityHealthRank',
      label: '区域设施健康度排名',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入区域设施健康度排名',
        min: 1,
        precision: 0,
        addonAfter: '名',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterStatisticsPeriod',
      label: '季度统计时段',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder:
          '请输入季度统计时段（如：2024-Q2（2024-04-01 ~ 2024-06-30））',
        maxlength: 80,
      },
      rules: 'required',
    },
    {
      fieldName: 'warningTypeDistributionRatio',
      label: '预警类型分布占比',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder:
          '请输入预警类型分布占比（如：坑洼超标: 65%, 裂缝超标: 25%, 温度异常: 8%, 流量异常: 2%）',
        maxlength: 200,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为道路监测季度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'roadSectionName',
      title: '路段名称',
      minWidth: 240,
      sortable: true,
      slots: { default: 'roadSectionName' }, // 自定义slot适配路段名称渲染
    },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'potholeCountQuarterAvg',
      title: '坑洼数量季度均值',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'crackLengthQuarterAvg',
      title: '裂缝长度季度均值(米)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'quarterTotalWarningCount',
      title: '季度累计预警数',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'quarterWorkOrderCount',
      title: '季度工单量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'quarterDisposalEfficiency',
      title: '季度处置效率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'quarterDisposalComplianceRate',
      title: '季度处置达标率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'deviceQuarterOnlineRate',
      title: '设备季度在线率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'potholeCountMomChangeRate',
      title: '坑洼数量环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'potholeCountYoYChangeRate',
      title: '坑洼数量同比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'crackLengthMomChangeRate',
      title: '裂缝长度环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'crackLengthYoYChangeRate',
      title: '裂缝长度同比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'areaFacilityHealthRank',
      title: '区域设施健康度排名',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'quarterStatisticsPeriod',
      title: '季度统计时段',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'warningTypeDistributionRatio',
      title: '预警类型分布占比',
      minWidth: 280,
      sortable: false, // 文本描述类字段无需排序
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
