/** 表格初始数据 - 改造为桥梁监测管理数据 */
export const dataList = () => [
  {
    bridgeName: '福州市闽江大桥',
    monitorPosition: '主桥左侧支座',
    bearingDisplacement: 0.8,
    vibrationFrequency: 2.5,
    strainValue: 125.6,
    monitorDeviceCode: 'FJ-FZ-B-202406-001',
    deviceOnlineStatus: '在线',
    maintenancePerson: '陈铭（工号：FJYW001）',
    dataCollectionFreq: '5分钟',
    dataSyncDuration: 3,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:30:25',
    warningLevelThreshold: 'Ⅱ级',
  },
  {
    bridgeName: '厦门市集美大桥',
    monitorPosition: '引桥右侧支座',
    bearingDisplacement: 0.3,
    vibrationFrequency: 1.8,
    strainValue: 89.2,
    monitorDeviceCode: 'FJ-XM-B-202406-002',
    deviceOnlineStatus: '在线',
    maintenancePerson: '林晓婷（工号：FJYW002）',
    dataCollectionFreq: '10分钟',
    dataSyncDuration: 5,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:28:42',
    warningLevelThreshold: 'Ⅰ级',
  },
  {
    bridgeName: '泉州市晋江大桥',
    monitorPosition: '主桥中跨支座',
    bearingDisplacement: 2.5,
    vibrationFrequency: 5.8,
    strainValue: 210.5,
    monitorDeviceCode: 'FJ-QZ-B-202406-003',
    deviceOnlineStatus: '异常',
    maintenancePerson: '王志远（工号：FJYW003）',
    dataCollectionFreq: '1分钟',
    dataSyncDuration: 2,
    monitorStatus: '数据异常',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:10:18',
    warningLevelThreshold: 'Ⅲ级',
  },
  {
    bridgeName: '漳州市九龙江大桥',
    monitorPosition: '副桥左侧支座',
    bearingDisplacement: 0.1,
    vibrationFrequency: 1.2,
    strainValue: 65.8,
    monitorDeviceCode: 'FJ-ZZ-B-202406-004',
    deviceOnlineStatus: '在线',
    maintenancePerson: '黄丽萍（工号：FJYW004）',
    dataCollectionFreq: '30分钟',
    dataSyncDuration: 4,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:25:36',
    warningLevelThreshold: 'Ⅰ级',
  },
  {
    bridgeName: '莆田市木兰溪大桥',
    monitorPosition: '主桥右侧支座',
    bearingDisplacement: 1.8,
    vibrationFrequency: 4.2,
    strainValue: 185.3,
    monitorDeviceCode: 'FJ-PT-B-202406-005',
    deviceOnlineStatus: '离线',
    maintenancePerson: '郑建明（工号：FJYW005）',
    dataCollectionFreq: '1小时',
    dataSyncDuration: 6,
    monitorStatus: '设备故障',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 14:50:08',
    warningLevelThreshold: 'Ⅱ级',
  },
  {
    bridgeName: '宁德市东湖大桥',
    monitorPosition: '引桥左侧支座',
    bearingDisplacement: 0.6,
    vibrationFrequency: 2.1,
    strainValue: 110.7,
    monitorDeviceCode: 'FJ-ND-B-202406-006',
    deviceOnlineStatus: '在线',
    maintenancePerson: '吴永辉（工号：FJYW006）',
    dataCollectionFreq: '5分钟',
    dataSyncDuration: 3,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:32:15',
    warningLevelThreshold: 'Ⅰ级',
  },
  {
    bridgeName: '龙岩市龙津河大桥',
    monitorPosition: '主桥边跨支座',
    bearingDisplacement: 2,
    vibrationFrequency: 3.8,
    strainValue: 195.8,
    monitorDeviceCode: 'FJ-LY-B-202406-007',
    deviceOnlineStatus: '在线',
    maintenancePerson: '张志强（工号：FJYW007）',
    dataCollectionFreq: '10分钟',
    dataSyncDuration: 4,
    monitorStatus: '人工巡检中',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:18:49',
    warningLevelThreshold: 'Ⅱ级',
  },
  {
    bridgeName: '三明市沙溪大桥',
    monitorPosition: '副桥右侧支座',
    bearingDisplacement: 0.4,
    vibrationFrequency: 1.5,
    strainValue: 95.4,
    monitorDeviceCode: 'FJ-SM-B-202406-008',
    deviceOnlineStatus: '在线',
    maintenancePerson: '李芳（工号：FJYW008）',
    dataCollectionFreq: '30分钟',
    dataSyncDuration: 5,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:22:05',
    warningLevelThreshold: 'Ⅰ级',
  },
  {
    bridgeName: '南平市建溪大桥',
    monitorPosition: '主桥中支座',
    bearingDisplacement: 1.5,
    vibrationFrequency: 4.5,
    strainValue: 175.9,
    monitorDeviceCode: 'FJ-NP-B-202406-009',
    deviceOnlineStatus: '异常',
    maintenancePerson: '刘建国（工号：FJYW009）',
    dataCollectionFreq: '1分钟',
    dataSyncDuration: 2,
    monitorStatus: '暂停监测',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:05:33',
    warningLevelThreshold: 'Ⅱ级',
  },
  {
    bridgeName: '平潭综合实验区海峡大桥',
    monitorPosition: '引桥中支座',
    bearingDisplacement: 0.2,
    vibrationFrequency: 1.9,
    strainValue: 80.6,
    monitorDeviceCode: 'FJ-PTTH-B-202406-010',
    deviceOnlineStatus: '在线',
    maintenancePerson: '蔡伟明（工号：FJYW010）',
    dataCollectionFreq: '1小时',
    dataSyncDuration: 6,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '支座位移≤2mm；振动频率1~5Hz；应变值≤200με；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:15:20',
    warningLevelThreshold: 'Ⅰ级',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为桥梁监测管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'bridgeName',
      label: '桥梁名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入桥梁名称',
      },
      labelWidth: '120',
      rules: 'required', // 桥梁名称为必填项
    },
    {
      fieldName: 'monitorPosition',
      label: '监测部位',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测部位（如：主桥左侧支座）',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'bearingDisplacement',
      label: '支座位移',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入支座位移（单位：mm）',
        min: 0,
        precision: 1, // 保留1位小数，贴合位移计量场景
        addonAfter: 'mm',
      },
      rules: 'required',
    },
    {
      fieldName: 'vibrationFrequency',
      label: '振动频率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入振动频率（单位：Hz）',
        min: 0,
        precision: 1,
        addonAfter: 'Hz',
      },
      rules: 'required',
    },
    {
      fieldName: 'strainValue',
      label: '应变值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入应变值（单位：με）',
        min: 0,
        precision: 1,
        addonAfter: 'με',
      },
      rules: 'required',
    },
    {
      fieldName: 'monitorDeviceCode',
      label: '监测设备编号',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入监测设备编号',
        maxLength: 50,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceOnlineStatus',
      label: '设备在线状态',
      rules: 'required',
    },
    {
      fieldName: 'maintenancePerson',
      label: '负责养护员',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入负责养护员姓名/工号',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '1分钟', value: '1分钟' },
          { label: '5分钟', value: '5分钟' },
          { label: '10分钟', value: '10分钟' },
          { label: '30分钟', value: '30分钟' },
          { label: '1小时', value: '1小时' },
          { label: '24小时', value: '24小时' },
        ],
        placeholder: '请选择数据采集频率',
        showSearch: true,
      },
      fieldName: 'dataCollectionFreq',
      label: '数据采集频率',
      rules: 'required',
    },
    {
      fieldName: 'dataSyncDuration',
      label: '数据同步时长',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入数据同步时长（单位：秒）',
        min: 1,
        precision: 0,
        addonAfter: '秒',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '正常监测', value: '正常监测' },
          { label: '暂停监测', value: '暂停监测' },
          { label: '数据异常', value: '数据异常' },
          { label: '设备故障', value: '设备故障' },
          { label: '人工巡检中', value: '人工巡检中' },
        ],
        placeholder: '请选择监测状态',
        showSearch: true,
      },
      fieldName: 'monitorStatus',
      label: '监测状态',
      rules: 'required',
    },
    {
      fieldName: 'indexThresholdRange',
      label: '指标阈值范围',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder:
          '请输入指标阈值范围（如：支座位移≤2mm；振动频率1~5Hz；应变值≤200με）',
        maxlength: 200,
      },
      rules: 'required',
    },
    {
      fieldName: 'latestDataUpdateTime',
      label: '最近数据更新时间',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入最近数据更新时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: 'Ⅰ级', value: 'Ⅰ级' },
          { label: 'Ⅱ级', value: 'Ⅱ级' },
          { label: 'Ⅲ级', value: 'Ⅲ级' },
        ],
        placeholder: '请选择预警等级阈值',
        showSearch: true,
      },
      fieldName: 'warningLevelThreshold',
      label: '预警等级阈值',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为桥梁监测管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'bridgeName',
      title: '桥梁名称',
      minWidth: 180,
      sortable: true,
      slots: { default: 'bridgeName' },
    },
    {
      field: 'monitorPosition',
      title: '监测部位',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'bearingDisplacement',
      title: '支座位移(mm)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'vibrationFrequency',
      title: '振动频率(Hz)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'strainValue',
      title: '应变值(με)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monitorDeviceCode',
      title: '监测设备编号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'deviceOnlineStatus',
      title: '设备在线状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'maintenancePerson',
      title: '负责养护员',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'dataCollectionFreq',
      title: '数据采集频率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'dataSyncDuration',
      title: '数据同步时长(秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monitorStatus',
      title: '监测状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'indexThresholdRange',
      title: '指标阈值范围',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'latestDataUpdateTime',
      title: '最近数据更新时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'warningLevelThreshold',
      title: '预警等级阈值',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
