/** 表格初始数据 - 渣土运输季度统计数据分析 */
export const dataList = () => [
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 28500,
    quarterlyViolationDisposalRate: 94.5,
    quarterlyComplianceRank: 'A类 第3名',
    quarterlyCheckpointEffect: '设卡45次，检查车辆320辆，违规23起',
    quarterlyLandfillUsage: 12500,
    quarterOnQuarterGrowthRate: 5.8,
    yearOnYearGrowthRate: 12.3,
  },
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 26300,
    quarterlyViolationDisposalRate: 92.8,
    quarterlyComplianceRank: 'A类 第5名',
    quarterlyCheckpointEffect: '设卡38次，检查车辆295辆，违规18起',
    quarterlyLandfillUsage: 11800,
    quarterOnQuarterGrowthRate: 3.2,
    yearOnYearGrowthRate: 9.7,
  },
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 31200,
    quarterlyViolationDisposalRate: 97.2,
    quarterlyComplianceRank: 'A类 第1名',
    quarterlyCheckpointEffect: '设卡52次，检查车辆410辆，违规12起',
    quarterlyLandfillUsage: 14300,
    quarterOnQuarterGrowthRate: 8.5,
    yearOnYearGrowthRate: 18.4,
  },
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 22400,
    quarterlyViolationDisposalRate: 89.5,
    quarterlyComplianceRank: 'B类 第2名',
    quarterlyCheckpointEffect: '设卡32次，检查车辆250辆，违规28起',
    quarterlyLandfillUsage: 10200,
    quarterOnQuarterGrowthRate: -2.1,
    yearOnYearGrowthRate: 4.2,
  },
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 24100,
    quarterlyViolationDisposalRate: 91.2,
    quarterlyComplianceRank: 'B类 第1名',
    quarterlyCheckpointEffect: '设卡35次，检查车辆278辆，违规20起',
    quarterlyLandfillUsage: 11200,
    quarterOnQuarterGrowthRate: 1.5,
    yearOnYearGrowthRate: 6.8,
  },
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 19800,
    quarterlyViolationDisposalRate: 87.6,
    quarterlyComplianceRank: 'C类 第3名',
    quarterlyCheckpointEffect: '设卡28次，检查车辆210辆，违规31起',
    quarterlyLandfillUsage: 8900,
    quarterOnQuarterGrowthRate: -5.5,
    yearOnYearGrowthRate: -2.1,
  },
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 17600,
    quarterlyViolationDisposalRate: 85.3,
    quarterlyComplianceRank: 'C类 第5名',
    quarterlyCheckpointEffect: '设卡22次，检查车辆185辆，违规35起',
    quarterlyLandfillUsage: 7800,
    quarterOnQuarterGrowthRate: -7.8,
    yearOnYearGrowthRate: -5.6,
  },
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 26900,
    quarterlyViolationDisposalRate: 95.1,
    quarterlyComplianceRank: 'A类 第4名',
    quarterlyCheckpointEffect: '设卡48次，检查车辆355辆，违规15起',
    quarterlyLandfillUsage: 12800,
    quarterOnQuarterGrowthRate: 6.2,
    yearOnYearGrowthRate: 14.5,
  },
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 20500,
    quarterlyViolationDisposalRate: 88.9,
    quarterlyComplianceRank: 'B类 第3名',
    quarterlyCheckpointEffect: '设卡30次，检查车辆230辆，违规25起',
    quarterlyLandfillUsage: 9500,
    quarterOnQuarterGrowthRate: -3.4,
    yearOnYearGrowthRate: 2.3,
  },
  {
    statisticalQuarter: '2024年第一季度',
    quarterlyClearTotal: 15200,
    quarterlyViolationDisposalRate: 82.7,
    quarterlyComplianceRank: 'C类 第7名',
    quarterlyCheckpointEffect: '设卡18次，检查车辆150辆，违规42起',
    quarterlyLandfillUsage: 6800,
    quarterOnQuarterGrowthRate: -10.2,
    yearOnYearGrowthRate: -12.8,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 渣土运输季度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'statisticalQuarter',
      label: '统计季度',
      component: 'Input',
      componentProps: {
        placeholder: '请输入统计季度（如：2024年第一季度）',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'quarterlyClearTotal',
      label: '季度清运总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度清运总量（单位：吨）',
        min: 0,
        precision: 0,
        addonAfter: '吨',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterlyViolationDisposalRate',
      label: '季度违规案件处置率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入季度违规案件处置率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterlyComplianceRank',
      label: '季度清运企业合规率排名',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入企业合规率排名（如：A类 第3名）',
        maxlength: 50,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterlyCheckpointEffect',
      label: '季度卡点执法成效',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入卡点执法成效（如：设卡45次，检查车辆320辆，违规23起）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterlyLandfillUsage',
      label: '季度渣土消纳场使用量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入渣土消纳场使用量（单位：吨）',
        min: 0,
        precision: 0,
        addonAfter: '吨',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterOnQuarterGrowthRate',
      label: '环比增长率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比增长率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearGrowthRate',
      label: '同比增长率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比增长率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 渣土运输季度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'statisticalQuarter',
      title: '统计季度',
      minWidth: 150,
      sortable: true,
      slots: { default: 'statisticalQuarter' },
    },
    {
      field: 'quarterlyClearTotal',
      title: '季度清运总量(吨)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'quarterlyViolationDisposalRate',
      title: '季度违规案件处置率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'quarterlyComplianceRank',
      title: '季度清运企业合规率排名',
      minWidth: 190,
      sortable: true,
    },
    {
      field: 'quarterlyCheckpointEffect',
      title: '季度卡点执法成效',
      minWidth: 280,
      sortable: false,
    },
    {
      field: 'quarterlyLandfillUsage',
      title: '季度渣土消纳场使用量(吨)',
      minWidth: 210,
      sortable: true,
    },
    {
      field: 'quarterOnQuarterGrowthRate',
      title: '环比增长率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'yearOnYearGrowthRate',
      title: '同比增长率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
