/** 表格初始数据 - 户外广告安全排查季度统计 */
export const dataList = () => [
  {
    statisticsQuarter: '2024年第一季度',
    quarterRecordTotal: 158,
    quarterViolationTotal: 12,
    quarterRectificationRate: 92.41,
    quarterRepeatViolationArea: 3,
    advertisingFacilitySafetyRate: 98.20,
    quarterGrowthRate: 5.3,
    yearOverYearGrowthRate: 2.1,
  },
  {
    statisticsQuarter: '2023年第四季度',
    quarterRecordTotal: 150,
    quarterViolationTotal: 14,
    quarterRectificationRate: 90.67,
    quarterRepeatViolationArea: 4,
    advertisingFacilitySafetyRate: 97.50,
    quarterGrowthRate: 4.8,
    yearOverYearGrowthRate: 1.5,
  },
  {
    statisticsQuarter: '2023年第三季度',
    quarterRecordTotal: 143,
    quarterViolationTotal: 13,
    quarterRectificationRate: 90.91,
    quarterRepeatViolationArea: 3,
    advertisingFacilitySafetyRate: 97.80,
    quarterGrowthRate: 4.2,
    yearOverYearGrowthRate: 1.8,
  },
  {
    statisticsQuarter: '2023年第二季度',
    quarterRecordTotal: 137,
    quarterViolationTotal: 15,
    quarterRectificationRate: 89.05,
    quarterRepeatViolationArea: 5,
    advertisingFacilitySafetyRate: 97.00,
    quarterGrowthRate: 3.9,
    yearOverYearGrowthRate: 2.3,
  },
  {
    statisticsQuarter: '2023年第一季度',
    quarterRecordTotal: 132,
    quarterViolationTotal: 16,
    quarterRectificationRate: 87.88,
    quarterRepeatViolationArea: 4,
    advertisingFacilitySafetyRate: 96.80,
    quarterGrowthRate: 4.0,
    yearOverYearGrowthRate: 2.5,
  },
  {
    statisticsQuarter: '2022年第四季度',
    quarterRecordTotal: 127,
    quarterViolationTotal: 14,
    quarterRectificationRate: 88.98,
    quarterRepeatViolationArea: 3,
    advertisingFacilitySafetyRate: 96.50,
    quarterGrowthRate: 3.5,
    yearOverYearGrowthRate: 0,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 户外广告安全排查季度统计表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'statisticsQuarter',
      label: '统计季度',
      component: 'Select',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '2024年第一季度', value: '2024年第一季度' },
          { label: '2023年第四季度', value: '2023年第四季度' },
          { label: '2023年第三季度', value: '2023年第三季度' },
          { label: '2023年第二季度', value: '2023年第二季度' },
          { label: '2023年第一季度', value: '2023年第一季度' },
          { label: '2022年第四季度', value: '2022年第四季度' },
        ],
        placeholder: '请选择统计季度',
        showSearch: true,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'quarterRecordTotal',
      label: '季度备案总量',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入季度备案总量',
        min: 0,
        precision: 0,
        addonAfter: '件',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterViolationTotal',
      label: '季度违规总量',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入季度违规总量',
        min: 0,
        precision: 0,
        addonAfter: '件',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterRectificationRate',
      label: '季度整改合格率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入季度整改合格率',
        min: 0,
        max: 100,
        precision: 2,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterRepeatViolationArea',
      label: '季度重复违规区域数量',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入重复违规区域数量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'advertisingFacilitySafetyRate',
      label: '广告设施安全排查合格率',
      component: 'InputNumber',
      labelWidth: '150',
      componentProps: {
        placeholder: '请输入安全排查合格率',
        min: 0,
        max: 100,
        precision: 2,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'quarterGrowthRate',
      label: '环比增长率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入环比增长率',
        min: -100,
        max: 1000,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOverYearGrowthRate',
      label: '同比增长率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入同比增长率',
        min: -100,
        max: 1000,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 户外广告安全排查季度统计表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'statisticsQuarter',
      title: '统计季度',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'quarterRecordTotal',
      title: '季度备案总量',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'quarterViolationTotal',
      title: '季度违规总量',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'quarterRectificationRate',
      title: '季度整改合格率(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'quarterRepeatViolationArea',
      title: '季度重复违规区域数量',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'advertisingFacilitySafetyRate',
      title: '广告设施安全排查合格率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'quarterGrowthRate',
      title: '环比增长率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'yearOverYearGrowthRate',
      title: '同比增长率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
