// 模拟公共机构环境管理数据
export const dataList = () => {
  return [
    // ---------- 全部（机构基础信息）id1-id3 ----------
    {
      id: '1',
      toiletName: '第一中学',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '07:00-21:00',
      stallCount: 30, // 班级数，仅作示意
      status: '正常运营',
      manager: '张校长',
      // 全部特有字段
      cleaningRate: 98.5,
      problemRate: 96.0,
      wasteVolume: 1200,
      inspectionPassRate: 100,
      // 机构类型
      institutionType: '学校',
    },
    {
      id: '2',
      toiletName: '市人民医院',
      location: '龙文区迎宾路88号',
      area: '龙文区-碧湖街道',
      openHours: '00:00-24:00',
      stallCount: 500, // 床位数
      status: '正常运营',
      manager: '李院长',
      cleaningRate: 95.0,
      problemRate: 92.5,
      wasteVolume: 3500,
      inspectionPassRate: 98,
      institutionType: '医院',
    },
    {
      id: '3',
      toiletName: '行政服务中心',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '08:30-17:30',
      stallCount: 80, // 办事窗口数
      status: '部分停机',
      manager: '王主任',
      cleaningRate: 88.0,
      problemRate: 85.0,
      wasteVolume: 800,
      inspectionPassRate: 90,
      institutionType: '机关单位',
    },

    // ---------- 保洁待执行 id4-id6 ----------
    {
      id: '4',
      toiletName: '第一中学',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '07:00-21:00',
      status: '保洁待执行',
      manager: '张校长',
      // 保洁待执行特有字段
      cleaningFrequency: '每日两次',
      cleaningTime: '07:00-09:00,18:00-20:00',
      cleaningContent: '教室地面、走廊、卫生间清洁',
      cleaner: '李阿姨、王阿姨',
      cleaningStandard: '一级标准',
      responsibilityArea: '教学楼A、B栋',
      createBy: 'admin',
      createTime: '2026-03-01 08:00:00',
      updateTime: '2026-03-01 08:00:00',
      isEffective: true,
    },
    {
      id: '5',
      toiletName: '市人民医院',
      location: '龙文区迎宾路88号',
      area: '龙文区-碧湖街道',
      openHours: '00:00-24:00',
      status: '保洁待执行',
      manager: '李院长',
      cleaningFrequency: '每日四次',
      cleaningTime: '06:00-08:00,12:00-14:00,18:00-20:00,22:00-24:00',
      cleaningContent: '门诊大厅、病房、手术室专项清洁',
      cleaner: '专业保洁组',
      cleaningStandard: '特级标准',
      responsibilityArea: '门诊楼、住院部',
      createBy: 'admin',
      createTime: '2026-03-01 09:30:00',
      updateTime: '2026-03-01 09:30:00',
      isEffective: true,
    },
    {
      id: '6',
      toiletName: '行政服务中心',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '08:30-17:30',
      status: '保洁待执行',
      manager: '王主任',
      cleaningFrequency: '每日一次',
      cleaningTime: '08:30-10:30',
      cleaningContent: '办公区、办事大厅清洁',
      cleaner: '赵姐',
      cleaningStandard: '二级标准',
      responsibilityArea: '一层大厅、二层办公区',
      createBy: 'admin',
      createTime: '2026-03-01 10:00:00',
      updateTime: '2026-03-01 10:00:00',
      isEffective: true,
    },

    // ---------- 问题待处置 id7-id9 ----------
    {
      id: '7',
      toiletName: '第一中学',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '07:00-21:00',
      status: '问题待处置',
      manager: '张校长',
      // 问题待处置特有字段
      complaintId: 'PB20250301001', // 问题编号
      complaintType: '卫生差', // 问题类型
      complaintContent: '教学楼B栋三楼卫生间积水严重，异味重',
      complaintName: '陈老师',
      complaintTime: '2026-03-01 09:15:00',
      phone: '138****5678',
      dispatchStatus: '待派单',
      handler: null,
      isTimeout: false,
      // 额外字段（用于位置）
      problemLocation: '教学楼B栋三楼卫生间',
    },
    {
      id: '8',
      toiletName: '市人民医院',
      location: '龙文区迎宾路88号',
      area: '龙文区-碧湖街道',
      openHours: '00:00-24:00',
      status: '问题待处置',
      manager: '李院长',
      complaintId: 'PB20250301002',
      complaintType: '设施损坏',
      complaintContent: '门诊部饮水机漏水',
      complaintName: '患者家属',
      complaintTime: '2026-03-01 10:30:00',
      phone: '139****1234',
      dispatchStatus: '已派单',
      handler: '后勤科',
      isTimeout: false,
      problemLocation: '门诊部一楼大厅',
    },
    {
      id: '9',
      toiletName: '行政服务中心',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '08:30-17:30',
      status: '问题待处置',
      manager: '王主任',
      complaintId: 'PB20250301003',
      complaintType: '垃圾堆积',
      complaintContent: '后门垃圾桶满溢，未及时清运',
      complaintName: '环卫工人',
      complaintTime: '2026-03-01 11:00:00',
      phone: '137****9876',
      dispatchStatus: '待派单',
      handler: null,
      isTimeout: true,
      problemLocation: '后门垃圾点',
    },

    // ---------- 核查待验收 id10-id12 ----------
    {
      id: '10',
      toiletName: '第一中学',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '07:00-21:00',
      status: '核查待验收',
      manager: '张校长',
      // 核查待验收特有字段（复用 repairId 等）
      repairId: 'INSP20250301001', // 核查编号
      facilityType: '保洁任务', // 关联任务类型
      damageDesc: '教学楼A栋保洁完成，待核查', // 任务描述
      reportBy: '李阿姨',
      reportTime: '2026-03-01 14:00:00',
      photoUrl: 'http://example.com/inspect1.jpg',
      repairBy: null,
      repairStatus: '待核查', // 核查状态
      expectedCompleteTime: '2026-03-02 12:00:00',
      // 额外字段
      taskId: 'TASK001',
      taskType: '保洁',
      reportResult: '已完成',
    },
    {
      id: '11',
      toiletName: '市人民医院',
      location: '龙文区迎宾路88号',
      area: '龙文区-碧湖街道',
      openHours: '00:00-24:00',
      status: '核查待验收',
      manager: '李院长',
      repairId: 'INSP20250301002',
      facilityType: '问题处置',
      damageDesc: '门诊部饮水机已修复，待核查',
      reportBy: '后勤科',
      reportTime: '2026-03-01 15:20:00',
      photoUrl: 'http://example.com/inspect2.jpg',
      repairBy: '核查组',
      repairStatus: '核查中',
      expectedCompleteTime: '2026-03-01 18:00:00',
      taskId: 'TASK002',
      taskType: '维修',
      reportResult: '已修复',
    },
    {
      id: '12',
      toiletName: '行政服务中心',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '08:30-17:30',
      status: '核查待验收',
      manager: '王主任',
      repairId: 'INSP20250301003',
      facilityType: '垃圾清运',
      damageDesc: '后门垃圾已清运，待核查',
      reportBy: '赵姐',
      reportTime: '2026-03-01 16:10:00',
      photoUrl: 'http://example.com/inspect3.jpg',
      repairBy: null,
      repairStatus: '待核查',
      expectedCompleteTime: '2026-03-02 10:00:00',
      taskId: 'TASK003',
      taskType: '清运',
      reportResult: '已清运',
    },

    // ---------- 已完成 id13-id15 ----------
    {
      id: '13',
      toiletName: '第一中学',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '07:00-21:00',
      status: '已完成',
      manager: '张校长',
      // 已完成特有字段
      taskType: '保洁',
      completeTime: '2026-03-01 11:30:00',
      handler: '李阿姨',
      handleResult: '合格',
      proofUrl: 'http://example.com/proof_clean1.jpg',
      handleDuration: '2.5小时',
      cleaningQualifiedRate: 100,
      problemCompleteRate: null,
      inspectionPassRate: null,
      statPeriod: '2026-03-01',
    },
    {
      id: '14',
      toiletName: '市人民医院',
      location: '龙文区迎宾路88号',
      area: '龙文区-碧湖街道',
      openHours: '00:00-24:00',
      status: '已完成',
      manager: '李院长',
      taskType: '问题处置',
      completeTime: '2026-03-01 16:00:00',
      handler: '后勤科',
      handleResult: '已办结',
      proofUrl: 'http://example.com/proof_problem2.jpg',
      handleDuration: '5小时',
      cleaningQualifiedRate: null,
      problemCompleteRate: 100,
      inspectionPassRate: null,
      statPeriod: '2026-03-01',
    },
    {
      id: '15',
      toiletName: '行政服务中心',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '08:30-17:30',
      status: '已完成',
      manager: '王主任',
      taskType: '核查',
      completeTime: '2026-03-01 17:20:00',
      handler: '核查组',
      handleResult: '达标',
      proofUrl: 'http://example.com/proof_inspect3.jpg',
      handleDuration: '1小时',
      cleaningQualifiedRate: null,
      problemCompleteRate: null,
      inspectionPassRate: 100,
      statPeriod: '2026-03-01',
    },
  ];
};
