/** 表格初始数据 - 窨井盖设施监测数据 */
export const dataList = () => [
  {
    id: '1',
    coverNo: 'MH-202406-001',
    roadName: '福州市鼓楼区杨桥东路（东街口-五一广场）',
    openStatus: '关闭',
    tiltAngle: 2.5,
    vibrationData: 0.8,
    deviceCode: 'DEV-MH-202406-001',
    deviceStatus: '在线',
    staffName: '陈铭（工号：FJYW001）',
    collectFrequency: '5分钟',
    monitorStatus: '运行中',
    tiltAngleThreshold: '0-5度',
    syncDuration: 3,
    updateTime: '2024-06-15 14:30:00',
    riskLevel: '低风险',
    abnormalVibrationFlag: '否',
  },
  {
    id: '2',
    coverNo: 'MH-202406-002',
    roadName: '厦门市思明区鹭江道（轮渡码头-中山路）',
    openStatus: '关闭',
    tiltAngle: 1.2,
    vibrationData: 0.5,
    deviceCode: 'DEV-MH-202406-002',
    deviceStatus: '在线',
    staffName: '林晓婷（工号：FJYW002）',
    collectFrequency: '10分钟',
    monitorStatus: '运行中',
    tiltAngleThreshold: '0-5度',
    syncDuration: 5,
    updateTime: '2024-06-15 14:25:00',
    riskLevel: '低风险',
    abnormalVibrationFlag: '否',
  },
  {
    id: '3',
    coverNo: 'MH-202406-003',
    roadName: '泉州市丰泽区刺桐路（湖心街-泉秀街）',
    openStatus: '开启',
    tiltAngle: 15.8,
    vibrationData: 2.5,
    deviceCode: 'DEV-MH-202406-003',
    deviceStatus: '在线',
    staffName: '王志远（工号：FJYW003）',
    collectFrequency: '1分钟',
    monitorStatus: '运行中',
    tiltAngleThreshold: '0-5度',
    syncDuration: 2,
    updateTime: '2024-06-15 14:32:00',
    riskLevel: '高风险',
    abnormalVibrationFlag: '是',
  },
  {
    id: '4',
    coverNo: 'MH-202406-004',
    roadName: '漳州市芗城区胜利路（延安北路-新华西路）',
    openStatus: '关闭',
    tiltAngle: 0.8,
    vibrationData: 0.3,
    deviceCode: 'DEV-MH-202406-004',
    deviceStatus: '在线',
    staffName: '黄丽萍（工号：FJYW004）',
    collectFrequency: '30分钟',
    monitorStatus: '运行中',
    tiltAngleThreshold: '0-5度',
    syncDuration: 4,
    updateTime: '2024-06-15 14:20:00',
    riskLevel: '低风险',
    abnormalVibrationFlag: '否',
  },
  {
    id: '5',
    coverNo: 'MH-202406-005',
    roadName: '莆田市城厢区荔城南大道（凤凰山-万达广场）',
    openStatus: '关闭',
    tiltAngle: 3.2,
    vibrationData: 1.2,
    deviceCode: 'DEV-MH-202406-005',
    deviceStatus: '离线',
    staffName: '郑建明（工号：FJYW005）',
    collectFrequency: '1小时',
    monitorStatus: '已停止',
    tiltAngleThreshold: '0-5度',
    syncDuration: 6,
    updateTime: '2024-06-15 13:45:00',
    riskLevel: '中风险',
    abnormalVibrationFlag: '否',
  },
  {
    id: '6',
    coverNo: 'MH-202406-006',
    roadName: '宁德市蕉城区闽东中路（市政府-万达广场）',
    openStatus: '关闭',
    tiltAngle: 1.5,
    vibrationData: 0.6,
    deviceCode: 'DEV-MH-202406-006',
    deviceStatus: '在线',
    staffName: '吴永辉（工号：FJYW006）',
    collectFrequency: '5分钟',
    monitorStatus: '运行中',
    tiltAngleThreshold: '0-5度',
    syncDuration: 3,
    updateTime: '2024-06-15 14:28:00',
    riskLevel: '低风险',
    abnormalVibrationFlag: '否',
  },
  {
    id: '7',
    coverNo: 'MH-202406-007',
    roadName: '龙岩市新罗区龙川路（中山路-登高西路）',
    openStatus: '开启',
    tiltAngle: 8.5,
    vibrationData: 1.8,
    deviceCode: 'DEV-MH-202406-007',
    deviceStatus: '在线',
    staffName: '张志强（工号：FJYW007）',
    collectFrequency: '10分钟',
    monitorStatus: '运行中',
    tiltAngleThreshold: '0-5度',
    syncDuration: 4,
    updateTime: '2024-06-15 14:31:00',
    riskLevel: '中风险',
    abnormalVibrationFlag: '是',
  },
  {
    id: '8',
    coverNo: 'MH-202406-008',
    roadName: '三明市梅列区列东街（东新四路-东新六路）',
    openStatus: '关闭',
    tiltAngle: 0.9,
    vibrationData: 0.4,
    deviceCode: 'DEV-MH-202406-008',
    deviceStatus: '在线',
    staffName: '李芳（工号：FJYW008）',
    collectFrequency: '30分钟',
    monitorStatus: '运行中',
    tiltAngleThreshold: '0-5度',
    syncDuration: 5,
    updateTime: '2024-06-15 14:15:00',
    riskLevel: '低风险',
    abnormalVibrationFlag: '否',
  },
  {
    id: '9',
    coverNo: 'MH-202406-009',
    roadName: '南平市延平区八一路（江滨路-中山路）',
    openStatus: '关闭',
    tiltAngle: 4.2,
    vibrationData: 0.7,
    deviceCode: 'DEV-MH-202406-009',
    deviceStatus: '异常',
    staffName: '刘建国（工号：FJYW009）',
    collectFrequency: '1分钟',
    monitorStatus: '已停止',
    tiltAngleThreshold: '0-5度',
    syncDuration: 2,
    updateTime: '2024-06-15 13:50:00',
    riskLevel: '低风险',
    abnormalVibrationFlag: '否',
  },
  {
    id: '10',
    coverNo: 'MH-202406-010',
    roadName: '平潭综合实验区金井大道（管委会-龙凤头沙滩）',
    openStatus: '关闭',
    tiltAngle: 1.1,
    vibrationData: 0.5,
    deviceCode: 'DEV-MH-202406-010',
    deviceStatus: '在线',
    staffName: '蔡伟明（工号：FJYW010）',
    collectFrequency: '1小时',
    monitorStatus: '运行中',
    tiltAngleThreshold: '0-5度',
    syncDuration: 6,
    updateTime: '2024-06-15 14:00:00',
    riskLevel: '低风险',
    abnormalVibrationFlag: '否',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施监测配置表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'coverNo',
      label: '井盖编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入井盖编号',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 井盖编号为必填项
    },
    {
      fieldName: 'roadName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
        maxLength: 100,
      },
      labelWidth: '100',
      rules: 'required', // 路段名称为必填项
    },
    {
      fieldName: 'deviceCode',
      label: '监测设备编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测设备编号',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 监测设备编号为必填项
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '1分钟', value: '1分钟' },
          { label: '5分钟', value: '5分钟' },
          { label: '10分钟', value: '10分钟' },
          { label: '30分钟', value: '30分钟' },
          { label: '1小时', value: '1小时' },
          { label: '24小时', value: '24小时' },
        ],
        placeholder: '请选择数据采集频率',
        showSearch: true,
      },
      fieldName: 'collectFrequency',
      label: '数据采集频率',
      rules: 'required', // 数据采集频率为必填项
    },
    {
      fieldName: 'tiltAngleThreshold',
      label: '倾斜角度阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入倾斜角度阈值（如：0-5度）',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 倾斜角度阈值为必填项
    },
    {
      fieldName: 'staffName',
      label: '负责运维员',
      component: 'Input',
      componentProps: {
        placeholder: '请输入负责运维员姓名/工号',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 负责运维员为必填项
    },
  ];
}

/** 筛选表单schema - 窨井盖设施监测筛选表单 */
export function useFilterFormSchema() {
  return [
    {
      fieldName: 'coverNo',
      label: '井盖编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入井盖编号',
        maxLength: 50,
      },
      labelWidth: '100',
    },
    {
      fieldName: 'roadName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
        maxLength: 100,
      },
      labelWidth: '100',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '关闭', value: '关闭' },
          { label: '开启', value: '开启' },
        ],
        placeholder: '请选择开合状态',
        showSearch: true,
      },
      fieldName: 'openStatus',
      label: '开合状态',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceStatus',
      label: '设备在线状态',
    },
  ];
}

/** 表格字段 - 窨井盖设施监测表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'coverNo',
      title: '井盖编号',
      minWidth: 150,
      sortable: true,
      slots: { default: 'coverNo' },
    },
    {
      field: 'roadName',
      title: '路段名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'roadName' },
    },
    {
      field: 'openStatus',
      title: '开合状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'openStatus' },
    },
    {
      field: 'tiltAngle',
      title: '倾斜角度(度)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'vibrationData',
      title: '振动数据',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'deviceCode',
      title: '监测设备编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'deviceCode' },
    },
    {
      field: 'deviceStatus',
      title: '设备在线状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'deviceStatus' },
    },
    {
      field: 'staffName',
      title: '负责运维员',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'collectFrequency',
      title: '数据采集频率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monitorStatus',
      title: '监测状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'monitorStatus' },
    },
    {
      field: 'tiltAngleThreshold',
      title: '指标阈值范围',
      minWidth: 150,
      sortable: false,
    },
    {
      field: 'syncDuration',
      title: '数据同步时长(秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'updateTime',
      title: '最近更新时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'riskLevel',
      title: '安全风险等级',
      minWidth: 120,
      sortable: true,
      slots: { default: 'riskLevel' },
    },
    {
      field: 'abnormalVibrationFlag',
      title: '异常振动标识',
      minWidth: 120,
      sortable: true,
      slots: { default: 'abnormalVibrationFlag' },
    },
    {
      title: '操作',
      width: 200,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
