/** 表格初始数据 - 改造为道路乱贴乱画周度统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    totalIllegalPostingPoints: 156,
    cleanedAdvertisementCount: 142,
    illegalNumberVerificationCount: 89,
    illegalPostingOccurrenceRate: 3.2,
    cleanerWorkload: 28.5,
    momChangeRate_TotalPoints: 5.8,
    momChangeRate_CleanedCount: 7.2,
    momChangeRate_VerificationCount: 3.1,
    momChangeRate_OccurrenceRate: -1.2,
    momChangeRate_Workload: 4.5,
    detailByRegion: '鼓楼区: 156处；台江区: 98处；仓山区: 112处',
    detailByPointType: '墙面: 89处；灯杆: 45处；楼道: 22处',
    detailByContentType: '商业广告: 67处；服务信息: 43处；其他: 46处',
    detailByResponsibleUnit: '城管局: 98处；社区: 45处；物业: 13处',
  },
  {
    areaName: '台江区',
    totalIllegalPostingPoints: 98,
    cleanedAdvertisementCount: 87,
    illegalNumberVerificationCount: 56,
    illegalPostingOccurrenceRate: 2.8,
    cleanerWorkload: 18.3,
    momChangeRate_TotalPoints: 2.3,
    momChangeRate_CleanedCount: 4.1,
    momChangeRate_VerificationCount: 2.8,
    momChangeRate_OccurrenceRate: -0.8,
    momChangeRate_Workload: 3.2,
    detailByRegion: '台江区: 98处；鼓楼区: 156处；仓山区: 112处',
    detailByPointType: '墙面: 52处；灯杆: 28处；楼道: 18处',
    detailByContentType: '商业广告: 42处；服务信息: 28处；其他: 28处',
    detailByResponsibleUnit: '城管局: 56处；社区: 32处；物业: 10处',
  },
  {
    areaName: '仓山区',
    totalIllegalPostingPoints: 112,
    cleanedAdvertisementCount: 95,
    illegalNumberVerificationCount: 67,
    illegalPostingOccurrenceRate: 3.1,
    cleanerWorkload: 22.1,
    momChangeRate_TotalPoints: 8.9,
    momChangeRate_CleanedCount: 6.5,
    momChangeRate_VerificationCount: 5.4,
    momChangeRate_OccurrenceRate: 1.5,
    momChangeRate_Workload: 7.8,
    detailByRegion: '仓山区: 112处；晋安区: 76处；马尾区: 45处',
    detailByPointType: '墙面: 68处；灯杆: 32处；楼道: 12处',
    detailByContentType: '商业广告: 51处；服务信息: 31处；其他: 30处',
    detailByResponsibleUnit: '城管局: 68处；社区: 27处；物业: 7处',
  },
  {
    areaName: '晋安区',
    totalIllegalPostingPoints: 76,
    cleanedAdvertisementCount: 68,
    illegalNumberVerificationCount: 43,
    illegalPostingOccurrenceRate: 2.5,
    cleanerWorkload: 15.2,
    momChangeRate_TotalPoints: -2.1,
    momChangeRate_CleanedCount: 3.8,
    momChangeRate_VerificationCount: 1.9,
    momChangeRate_OccurrenceRate: -1.3,
    momChangeRate_Workload: 2.1,
    detailByRegion: '晋安区: 76处；仓山区: 112处；台江区: 98处',
    detailByPointType: '墙面: 42处；灯杆: 21处；楼道: 13处',
    detailByContentType: '商业广告: 32处；服务信息: 24处；其他: 20处',
    detailByResponsibleUnit: '城管局: 45处；社区: 21处；物业: 2处',
  },
  {
    areaName: '马尾区',
    totalIllegalPostingPoints: 45,
    cleanedAdvertisementCount: 41,
    illegalNumberVerificationCount: 28,
    illegalPostingOccurrenceRate: 1.8,
    cleanerWorkload: 9.8,
    momChangeRate_TotalPoints: 12.5,
    momChangeRate_CleanedCount: 10.2,
    momChangeRate_VerificationCount: 8.7,
    momChangeRate_OccurrenceRate: 2.1,
    momChangeRate_Workload: 11.5,
    detailByRegion: '马尾区: 45处；长乐区: 32处；福清市: 28处',
    detailByPointType: '墙面: 25处；灯杆: 12处；楼道: 8处',
    detailByContentType: '商业广告: 18处；服务信息: 15处；其他: 12处',
    detailByResponsibleUnit: '城管局: 28处；社区: 12处；物业: 1处',
  },
  {
    areaName: '长乐区',
    totalIllegalPostingPoints: 32,
    cleanedAdvertisementCount: 29,
    illegalNumberVerificationCount: 18,
    illegalPostingOccurrenceRate: 1.5,
    cleanerWorkload: 7.2,
    momChangeRate_TotalPoints: 5.6,
    momChangeRate_CleanedCount: 4.3,
    momChangeRate_VerificationCount: 3.2,
    momChangeRate_OccurrenceRate: 0.9,
    momChangeRate_Workload: 4.8,
    detailByRegion: '长乐区: 32处；马尾区: 45处；连江县: 25处',
    detailByPointType: '墙面: 18处；灯杆: 8处；楼道: 6处',
    detailByContentType: '商业广告: 14处；服务信息: 11处；其他: 7处',
    detailByResponsibleUnit: '城管局: 19处；社区: 9处；物业: 1处',
  },
  {
    areaName: '福清市',
    totalIllegalPostingPoints: 28,
    cleanedAdvertisementCount: 25,
    illegalNumberVerificationCount: 16,
    illegalPostingOccurrenceRate: 1.3,
    cleanerWorkload: 6.5,
    momChangeRate_TotalPoints: -1.8,
    momChangeRate_CleanedCount: 2.1,
    momChangeRate_VerificationCount: 1.5,
    momChangeRate_OccurrenceRate: -0.6,
    momChangeRate_Workload: 1.2,
    detailByRegion: '福清市: 28处；长乐区: 32处；闽侯县: 22处',
    detailByPointType: '墙面: 16处；灯杆: 7处；楼道: 5处',
    detailByContentType: '商业广告: 12处；服务信息: 9处；其他: 7处',
    detailByResponsibleUnit: '城管局: 18处；社区: 6处；物业: 1处',
  },
  {
    areaName: '连江县',
    totalIllegalPostingPoints: 25,
    cleanedAdvertisementCount: 22,
    illegalNumberVerificationCount: 14,
    illegalPostingOccurrenceRate: 1.4,
    cleanerWorkload: 5.8,
    momChangeRate_TotalPoints: 8.3,
    momChangeRate_CleanedCount: 6.7,
    momChangeRate_VerificationCount: 5.2,
    momChangeRate_OccurrenceRate: 1.1,
    momChangeRate_Workload: 6.9,
    detailByRegion: '连江县: 25处；福清市: 28处；闽侯县: 22处',
    detailByPointType: '墙面: 14处；灯杆: 6处；楼道: 5处',
    detailByContentType: '商业广告: 11处；服务信息: 8处；其他: 6处',
    detailByResponsibleUnit: '城管局: 15处；社区: 5处；物业: 2处',
  },
  {
    areaName: '闽侯县',
    totalIllegalPostingPoints: 22,
    cleanedAdvertisementCount: 19,
    illegalNumberVerificationCount: 12,
    illegalPostingOccurrenceRate: 1.2,
    cleanerWorkload: 5.1,
    momChangeRate_TotalPoints: 3.4,
    momChangeRate_CleanedCount: 2.8,
    momChangeRate_VerificationCount: 2.1,
    momChangeRate_OccurrenceRate: 0.7,
    momChangeRate_Workload: 3.5,
    detailByRegion: '闽侯县: 22处；连江县: 25处；罗源县: 18处',
    detailByPointType: '墙面: 12处；灯杆: 5处；楼道: 5处',
    detailByContentType: '商业广告: 9处；服务信息: 7处；其他: 6处',
    detailByResponsibleUnit: '城管局: 13处；社区: 4处；物业: 2处',
  },
  {
    areaName: '罗源县',
    totalIllegalPostingPoints: 18,
    cleanedAdvertisementCount: 16,
    illegalNumberVerificationCount: 10,
    illegalPostingOccurrenceRate: 1.1,
    cleanerWorkload: 4.2,
    momChangeRate_TotalPoints: 6.7,
    momChangeRate_CleanedCount: 5.9,
    momChangeRate_VerificationCount: 4.8,
    momChangeRate_OccurrenceRate: 0.5,
    momChangeRate_Workload: 5.3,
    detailByRegion: '罗源县: 18处；闽侯县: 22处；永泰县: 15处',
    detailByPointType: '墙面: 10处；灯杆: 4处；楼道: 4处',
    detailByContentType: '商业广告: 7处；服务信息: 6处；其他: 5处',
    detailByResponsibleUnit: '城管局: 10处；社区: 4处；物业: 1处',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为道路乱贴乱画周度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'totalIllegalPostingPoints',
      label: '乱贴乱画点位数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入乱贴乱画点位数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'cleanedAdvertisementCount',
      label: '小广告清理完成数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入小广告清理完成数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'illegalNumberVerificationCount',
      label: '非法小广告号码核查数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入非法小广告号码核查数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'illegalPostingOccurrenceRate',
      label: '重点区域乱贴乱画发生率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入重点区域乱贴乱画发生率（单位：%）',
        min: 0,
        max: 10,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'cleanerWorkload',
      label: '清理人员工作量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入清理人员工作量（单位：人天）',
        min: 0,
        precision: 1,
        addonAfter: '人天',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_TotalPoints',
      label: '乱贴乱画点位数量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入乱贴乱画点位数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_CleanedCount',
      label: '小广告清理完成数量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入小广告清理完成数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_VerificationCount',
      label: '非法小广告号码核查数量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入非法小广告号码核查数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_OccurrenceRate',
      label: '乱贴乱画发生率环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入乱贴乱画发生率环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_Workload',
      label: '清理人员工作量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入清理人员工作量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRegion',
      label: '按区域拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按区域拆分的明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByPointType',
      label: '按点位类型拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按点位类型拆分的明细数据（墙面、灯杆、楼道）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByContentType',
      label: '按广告内容类型拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按广告内容类型拆分的明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByResponsibleUnit',
      label: '按清理责任单位拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按清理责任单位拆分的明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为道路乱贴乱画周度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'totalIllegalPostingPoints',
      title: '乱贴乱画点位数量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'cleanedAdvertisementCount',
      title: '小广告清理完成数量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'illegalNumberVerificationCount',
      title: '非法小广告号码核查数量',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'illegalPostingOccurrenceRate',
      title: '重点区域乱贴乱画发生率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'cleanerWorkload',
      title: '清理人员工作量(人天)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_TotalPoints',
      title: '点位数量环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'momChangeRate_CleanedCount',
      title: '清理完成数量环比变化率(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'momChangeRate_VerificationCount',
      title: '核查数量环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_OccurrenceRate',
      title: '发生率环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_Workload',
      title: '工作量环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'detailByRegion',
      title: '按区域拆分明细',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByPointType',
      title: '按点位类型拆分明细',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByContentType',
      title: '按广告内容类型拆分明细',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByResponsibleUnit',
      title: '按责任单位拆分明细',
      minWidth: 200,
      sortable: false,
    },
  ];
}
