/** 商户表静态数据 */
export const merchantList = [
  {
    merchantId: 'merchant001',
    merchantName: '张三商贸有限公司',
    merchantCode: 'MC00001',
    contactPerson: '张三',
    contactPhone: '13800138001',
    address: '北京市朝阳区建国路88号',
    businessScope: '销售日用品、电子产品、服装鞋帽、办公用品',
    status: '正常',
    settlementRatio: 0.1,
    createTime: '2024-01-01 10:00:00',
    updateTime: '2024-01-02 14:30:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '测试商户1',
  },
  {
    merchantId: 'merchant002',
    merchantName: '李四科技有限公司',
    merchantCode: 'MC00002',
    contactPerson: '李四',
    contactPhone: '13800138002',
    address: '上海市浦东新区张江高科技园区',
    businessScope: '技术开发、技术转让、技术咨询、技术服务',
    status: '正常',
    settlementRatio: 0.15,
    createTime: '2024-01-02 11:30:00',
    updateTime: '2024-01-03 09:45:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '测试商户2',
  },
  {
    merchantId: 'merchant003',
    merchantName: '王五贸易有限公司',
    merchantCode: 'MC00003',
    contactPerson: '王五',
    contactPhone: '13800138003',
    address: '广州市天河区天河路385号',
    businessScope: '货物进出口、技术进出口、代理进出口',
    status: '停业',
    settlementRatio: 0.12,
    createTime: '2024-01-03 14:20:00',
    updateTime: '2024-01-04 10:15:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '测试商户3',
  },
  {
    merchantId: 'merchant004',
    merchantName: '赵六实业有限公司',
    merchantCode: 'MC00004',
    contactPerson: '赵六',
    contactPhone: '13800138004',
    address: '深圳市南山区科技园南区',
    businessScope: '兴办实业、国内商业、物资供销业',
    status: '注销',
    settlementRatio: 0.08,
    createTime: '2024-01-04 09:15:00',
    updateTime: '2024-01-05 15:20:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '测试商户4',
  },
  {
    merchantId: 'merchant005',
    merchantName: '孙七政务服务中心',
    merchantCode: 'MC00005',
    contactPerson: '孙七',
    contactPhone: '13800138005',
    address: '北京市西城区政务服务中心',
    businessScope: '政务服务、公共管理',
    status: '正常',
    settlementRatio: 0,
    createTime: '2024-01-05 16:45:00',
    updateTime: '2024-01-06 13:10:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '政府机构',
  },
  {
    merchantId: 'merchant006',
    merchantName: '周八零售有限公司',
    merchantCode: 'MC00006',
    contactPerson: '周八',
    contactPhone: '13800138006',
    address: '成都市锦江区春熙路',
    businessScope: '零售、餐饮、娱乐',
    status: '正常',
    settlementRatio: 0.09,
    createTime: '2024-01-06 10:30:00',
    updateTime: '2024-01-07 14:50:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '零售连锁',
  },
  {
    merchantId: 'merchant007',
    merchantName: '吴九制造有限公司',
    merchantCode: 'MC00007',
    contactPerson: '吴九',
    contactPhone: '13800138007',
    address: '武汉市洪山区光谷制造园',
    businessScope: '机械设备制造、加工、销售',
    status: '正常',
    settlementRatio: 0.11,
    createTime: '2024-01-07 14:20:00',
    updateTime: '2024-01-08 09:15:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '制造企业',
  },
  {
    merchantId: 'merchant008',
    merchantName: '郑十城市管理局',
    merchantCode: 'MC00008',
    contactPerson: '郑十',
    contactPhone: '13800138008',
    address: '南京市鼓楼区城市管理局',
    businessScope: '城市管理、公共服务',
    status: '正常',
    settlementRatio: 0,
    createTime: '2024-01-08 09:45:00',
    updateTime: '2024-01-09 15:20:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '政府机构',
  },
  {
    merchantId: 'merchant009',
    merchantName: '冯十一餐饮有限公司',
    merchantCode: 'MC00009',
    contactPerson: '冯十一',
    contactPhone: '13800138009',
    address: '杭州市西湖区餐饮街',
    businessScope: '餐饮服务、食品销售',
    status: '正常',
    settlementRatio: 0.13,
    createTime: '2024-01-09 13:10:00',
    updateTime: '2024-01-10 10:30:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '餐饮连锁',
  },
  {
    merchantId: 'merchant010',
    merchantName: '陈十二物流有限公司',
    merchantCode: 'MC00010',
    contactPerson: '陈十二',
    contactPhone: '13800138010',
    address: '重庆市渝北区物流园',
    businessScope: '物流运输、仓储服务',
    status: '正常',
    settlementRatio: 0.07,
    createTime: '2024-01-10 11:20:00',
    updateTime: '2024-01-11 09:15:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '物流企业',
  },
  {
    merchantId: 'merchant011',
    merchantName: '褚十三交通管理局',
    merchantCode: 'MC00011',
    contactPerson: '褚十三',
    contactPhone: '13800138011',
    address: '天津市河东区交通管理局',
    businessScope: '交通管理、公共安全',
    status: '正常',
    settlementRatio: 0,
    createTime: '2024-01-11 15:45:00',
    updateTime: '2024-01-12 13:10:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '政府机构',
  },
  {
    merchantId: 'merchant012',
    merchantName: '卫十四教育咨询有限公司',
    merchantCode: 'MC00012',
    contactPerson: '卫十四',
    contactPhone: '13800138012',
    address: '深圳市南山区教育科技园',
    businessScope: '教育咨询、培训服务',
    status: '正常',
    settlementRatio: 0.14,
    createTime: '2024-01-12 10:30:00',
    updateTime: '2024-01-13 14:50:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '教育机构',
  },
  {
    merchantId: 'merchant013',
    merchantName: '蒋十五建筑有限公司',
    merchantCode: 'MC00013',
    contactPerson: '蒋十五',
    contactPhone: '13800138013',
    address: '西安市雁塔区建筑产业园',
    businessScope: '建筑工程、装修装饰',
    status: '正常',
    settlementRatio: 0.1,
    createTime: '2024-01-13 14:20:00',
    updateTime: '2024-01-14 09:15:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '建筑企业',
  },
  {
    merchantId: 'merchant014',
    merchantName: '沈十六环境保护局',
    merchantCode: 'MC00014',
    contactPerson: '沈十六',
    contactPhone: '13800138014',
    address: '广州市天河区环保局',
    businessScope: '环境保护、污染治理',
    status: '正常',
    settlementRatio: 0,
    createTime: '2024-01-14 09:45:00',
    updateTime: '2024-01-15 15:20:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '政府机构',
  },
  {
    merchantId: 'merchant015',
    merchantName: '韩十七医疗科技有限公司',
    merchantCode: 'MC00015',
    contactPerson: '韩十七',
    contactPhone: '13800138015',
    address: '北京市海淀区医疗科技园',
    businessScope: '医疗技术、医疗器械',
    status: '正常',
    settlementRatio: 0.16,
    createTime: '2024-01-15 13:10:00',
    updateTime: '2024-01-16 10:30:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '医疗科技',
  },
  {
    merchantId: 'merchant016',
    merchantName: '杨十八文化传媒有限公司',
    merchantCode: 'MC00016',
    contactPerson: '杨十八',
    contactPhone: '13800138016',
    address: '上海市静安区文化传媒园',
    businessScope: '文化传媒、广告策划',
    status: '正常',
    settlementRatio: 0.12,
    createTime: '2024-01-16 11:20:00',
    updateTime: '2024-01-17 09:15:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '文化传媒',
  },
  {
    merchantId: 'merchant017',
    merchantName: '朱十九市场监督管理局',
    merchantCode: 'MC00017',
    contactPerson: '朱十九',
    contactPhone: '13800138017',
    address: '深圳市市场监督管理局',
    businessScope: '市场监管、质量监督',
    status: '正常',
    settlementRatio: 0,
    createTime: '2024-01-17 15:45:00',
    updateTime: '2024-01-18 13:10:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '政府机构',
  },
  {
    merchantId: 'merchant018',
    merchantName: '秦二十旅游咨询有限公司',
    merchantCode: 'MC00018',
    contactPerson: '秦二十',
    contactPhone: '13800138018',
    address: '昆明市官渡区旅游产业园',
    businessScope: '旅游咨询、旅行社服务',
    status: '正常',
    settlementRatio: 0.09,
    createTime: '2024-01-18 10:30:00',
    updateTime: '2024-01-19 14:50:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '旅游企业',
  },
  {
    merchantId: 'merchant019',
    merchantName: '尤二十一电子商务有限公司',
    merchantCode: 'MC00019',
    contactPerson: '尤二十一',
    contactPhone: '13800138019',
    address: '杭州市余杭区电商产业园',
    businessScope: '电子商务、网络销售',
    status: '正常',
    settlementRatio: 0.11,
    createTime: '2024-01-19 14:20:00',
    updateTime: '2024-01-20 09:15:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '电商企业',
  },
  {
    merchantId: 'merchant020',
    merchantName: '许二十二自然资源局',
    merchantCode: 'MC00020',
    contactPerson: '许二十二',
    contactPhone: '13800138020',
    address: '北京市海淀区自然资源局',
    businessScope: '自然资源管理、规划',
    status: '正常',
    settlementRatio: 0,
    createTime: '2024-01-20 09:45:00',
    updateTime: '2024-01-21 15:20:00',
    createBy: 'admin',
    updateBy: 'admin',
    remark: '政府机构',
  },
];

/** 商户权限列表数据 */
export const permissionList = [
  {
    id: 'perm001',
    merchantId: 'merchant001',
    merchantName: '张三商贸有限公司',
    permCode: 'order:view',
    permName: '订单查看',
    effectiveTime: '2024-01-01 00:00:00',
    expireTime: '2025-01-01 00:00:00',
    status: '有效',
    changeBy: 'admin',
    changeTime: '2024-01-01 10:00:00',
    changeReason: '初始分配',
  },
  {
    id: 'perm002',
    merchantId: 'merchant001',
    merchantName: '张三商贸有限公司',
    permCode: 'order:export',
    permName: '订单导出',
    effectiveTime: '2024-01-01 00:00:00',
    expireTime: '2025-01-01 00:00:00',
    status: '有效',
    changeBy: 'admin',
    changeTime: '2024-01-01 10:00:00',
    changeReason: '初始分配',
  },
  {
    id: 'perm003',
    merchantId: 'merchant002',
    merchantName: '李四科技有限公司',
    permCode: 'charge:adjust',
    permName: '收费调整',
    effectiveTime: '2024-01-02 00:00:00',
    expireTime: '2025-01-02 00:00:00',
    status: '有效',
    changeBy: 'admin',
    changeTime: '2024-01-02 11:30:00',
    changeReason: '初始分配',
  },
  {
    id: 'perm004',
    merchantId: 'merchant003',
    merchantName: '王五贸易有限公司',
    permCode: 'report:view',
    permName: '报表查看',
    effectiveTime: '2024-01-03 00:00:00',
    expireTime: '2024-06-03 00:00:00',
    status: '过期',
    changeBy: 'admin',
    changeTime: '2024-01-03 14:20:00',
    changeReason: '临时权限',
  },
];

/** 结算单列表数据 */
export const settlementList = [
  {
    id: 'settle001',
    merchantId: 'merchant001',
    merchantName: '张三商贸有限公司',
    settleCycle: '2024-01',
    totalIncome: 10_000,
    deductAmount: 1000,
    actualPay: 9000,
    settleRatio: 0.1,
    settleThreshold: 100,
    payStatus: '已支付',
    payTime: '2024-02-05 14:30:00',
    payVoucher: 'http://example.com/voucher/settle001.pdf',
    createTime: '2024-02-01 00:00:00',
  },
  {
    id: 'settle002',
    merchantId: 'merchant002',
    merchantName: '李四科技有限公司',
    settleCycle: '2024-01',
    totalIncome: 15_000,
    deductAmount: 2250,
    actualPay: 12_750,
    settleRatio: 0.15,
    settleThreshold: 100,
    payStatus: '已支付',
    payTime: '2024-02-05 15:00:00',
    payVoucher: 'http://example.com/voucher/settle002.pdf',
    createTime: '2024-02-01 00:00:00',
  },
  {
    id: 'settle003',
    merchantId: 'merchant001',
    merchantName: '张三商贸有限公司',
    settleCycle: '2024-02',
    totalIncome: 12_000,
    deductAmount: 1200,
    actualPay: 10_800,
    settleRatio: 0.1,
    settleThreshold: 100,
    payStatus: '待支付',
    payTime: null,
    payVoucher: null,
    createTime: '2024-03-01 00:00:00',
  },
];

/** 新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'merchantId',
      label: '商户ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入商户ID',
      },
      rules: 'required',
    },
    {
      fieldName: 'merchantName',
      label: '商户名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入商户名称',
      },
      rules: 'required',
    },
    {
      fieldName: 'merchantCode',
      label: '商户编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入商户编码',
      },
      rules: 'required',
    },
    {
      fieldName: 'contactPerson',
      label: '联系人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入联系人',
      },
      rules: 'required',
    },
    {
      fieldName: 'contactPhone',
      label: '联系电话',
      component: 'Input',
      componentProps: {
        placeholder: '请输入联系电话',
      },
      rules: 'required',
    },
    {
      fieldName: 'address',
      label: '商户地址',
      component: 'Input',
      componentProps: {
        placeholder: '请输入商户地址',
      },
      rules: 'required',
    },
    {
      fieldName: 'businessScope',
      label: '经营范围',
      component: 'Input',
      componentProps: {
        placeholder: '请输入经营范围',
        type: 'textarea',
        rows: 3,
      },
    },
    {
      fieldName: 'status',
      label: '状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择状态',
        options: [
          { label: '正常', value: '正常' },
          { label: '停业', value: '停业' },
          { label: '注销', value: '注销' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'settlementRatio',
      label: '默认分账比例',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入分账比例',
        min: 0,
        max: 1,
        step: 0.01,
        precision: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Input',
      componentProps: {
        placeholder: '请输入备注',
        type: 'textarea',
        rows: 3,
      },
    },
  ];
}

/** 表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'merchantId',
      title: '商户ID',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'merchantName',
      title: '商户名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'merchantName' },
    },
    {
      field: 'merchantCode',
      title: '商户编码',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'contactPerson',
      title: '联系人',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'contactPhone',
      title: '联系电话',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'address',
      title: '商户地址',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'businessScope',
      title: '经营范围',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'status',
      title: '状态',
      minWidth: 150,
      sortable: true,
      slots: { default: 'status' },
    },
    {
      field: 'settlementRatio',
      title: '分账比例',
      minWidth: 120,
      sortable: true,
      slots: { default: 'settlementRatio' },
    },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 180,
      sortable: true,
    },
    {
      title: '操作',
      width: 240,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑商户',
  addText: '新增商户',
  excelName: '商户列表',
  excelAllName: '商户数据.xlsx',
  total: '商户数量20',
};

/** 详情抽屉字段配置 */
export const merchantDetailFields = [
  { key: 'merchantId', label: '商户ID' },
  { key: 'merchantName', label: '商户名称' },
  { key: 'merchantCode', label: '商户编码' },
  { key: 'contactPerson', label: '联系人' },
  { key: 'contactPhone', label: '联系电话' },
  { key: 'address', label: '商户地址' },
  { key: 'businessScope', label: '经营范围' },
  {
    key: 'status',
    label: '状态',
    type: 'tag',
    tagType: (value) => {
      if (value === '正常') {
        return 'success';
      } else if (value === '停业') {
        return 'warning';
      } else {
        return 'danger';
      }
    },
  },
  {
    key: 'settlementRatio',
    label: '分账比例',
    formatter: (value) => `${(value * 100).toFixed(2)}%`,
  },
  { key: 'createTime', label: '创建时间' },
  { key: 'updateTime', label: '更新时间' },
  { key: 'createBy', label: '创建人' },
  { key: 'updateBy', label: '更新人' },
  { key: 'remark', label: '备注' },
];
