// data.js
/** 表格初始数据 - 工单数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "workorderNo": "WO-20260120-001",
      "workorderType": "设备故障",
      "source": "巡查上报",
      "emergencyDegree": "紧急",
      "location": "A区机房",
      "submitTime": "2026-01-20 09:30",
      "deadline": "2026-01-23 18:00",
      "workorderId": "WO001",
      "relatedResource": "服务器-001",
      "submitBy": "张三",
      "status": "待处理",
      "description": "服务器01号机柜温度异常报警，传感器显示温度达到45°C，超过警戒线40°C。",
      "currentProgress": "待处理",
      "receiveTime": "",
      "expectedFinishTime": "",
      "updateTime": "2026-01-20 09:30",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "initiator": "系统自动生成",
      "remindCount": 0,
      "latestDynamic": "工单已创建",
      "operator": "系统",
      "createTime": "2026-01-20 09:00",
      "operationLog": "工单创建",
      "disposalProgress": "待处理",
      "receiveStatus": "未认领",
      "disposalContent": "",
      "disposalDuration": "",
      "evaluateStatus": "",
      "satisfaction": "",
      "reviewOpinion": ""
    },
    {
      "id": 2,
      "workorderNo": "WO-20260121-002",
      "workorderType": "网络问题",
      "source": "用户投诉",
      "emergencyDegree": "高",
      "location": "B区办公区",
      "submitTime": "2026-01-21 14:00",
      "deadline": "2026-01-25 17:00",
      "workorderId": "WO002",
      "relatedResource": "交换机-02",
      "submitBy": "王五",
      "status": "处理中",
      "description": "B区办公网络间歇性中断，影响市场部15名员工正常工作。",
      "currentProgress": "50%",
      "receiveTime": "2026-01-21 15:00",
      "expectedFinishTime": "2026-01-24 18:00",
      "updateTime": "2026-01-22 10:30",
      "delayStatus": "正常",
      "cooperators": "赵六,钱七",
      "finishTime": "",
      "acceptResult": "",
      "executor": "李四",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "initiator": "用户提交",
      "remindCount": 0,
      "latestDynamic": "已检查线路连接，发现交换机端口异常",
      "operator": "李四",
      "createTime": "2026-01-21 13:30",
      "operationLog": "工单认领",
      "disposalProgress": "诊断中",
      "receiveStatus": "已认领",
      "disposalContent": "检查网络设备，发现交换机端口异常，已进行初步处理",
      "disposalDuration": "1天",
      "evaluateStatus": "",
      "satisfaction": "",
      "reviewOpinion": ""
    },
    {
      "id": 3,
      "workorderNo": "WO-20260119-003",
      "workorderType": "软件问题",
      "source": "系统预警",
      "emergencyDegree": "中",
      "location": "财务部",
      "submitTime": "2026-01-19 10:00",
      "deadline": "2026-01-22 12:00",
      "workorderId": "WO003",
      "relatedResource": "财务系统",
      "submitBy": "孙八",
      "status": "已完成",
      "description": "财务系统报表导出功能异常，无法生成月度财务报表。",
      "currentProgress": "100%",
      "receiveTime": "2026-01-19 11:00",
      "expectedFinishTime": "2026-01-22 10:00",
      "updateTime": "2026-01-22 09:45",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-22 09:45",
      "acceptResult": "已解决",
      "executor": "李四",
      "attachment": "fix_report.zip",
      "executionDuration": "3天",
      "archiveTime": "2026-01-22 10:00",
      "acceptOpinion": "问题已解决，系统恢复正常",
      "initiator": "系统预警",
      "remindCount": 0,
      "latestDynamic": "工单已完成",
      "operator": "李四",
      "createTime": "2026-01-19 09:30",
      "operationLog": "工单完成",
      "disposalProgress": "已完成",
      "receiveStatus": "已认领",
      "disposalContent": "修复报表导出模块bug，更新系统补丁",
      "disposalDuration": "3天",
      "evaluateStatus": "待评价",
      "satisfaction": "",
      "reviewOpinion": ""
    },
    {
      "id": 4,
      "workorderNo": "WO-20260118-004",
      "workorderType": "硬件维修",
      "source": "巡查上报",
      "emergencyDegree": "高",
      "location": "C区会议室",
      "submitTime": "2026-01-18 13:00",
      "deadline": "2026-01-24 20:00",
      "workorderId": "WO004",
      "relatedResource": "投影仪-01",
      "submitBy": "李四",
      "status": "已评价",
      "description": "会议室投影仪无法正常显示，影响重要会议使用。",
      "currentProgress": "100%",
      "receiveTime": "2026-01-18 14:00",
      "expectedFinishTime": "2026-01-23 18:00",
      "updateTime": "2026-01-22 16:30",
      "delayStatus": "正常",
      "cooperators": "周五,吴九",
      "finishTime": "2026-01-22 16:30",
      "acceptResult": "已解决",
      "executor": "王五",
      "attachment": "",
      "executionDuration": "4天",
      "archiveTime": "2026-01-23 10:00",
      "acceptOpinion": "设备维修完成，测试正常",
      "initiator": "巡查员",
      "remindCount": 0,
      "latestDynamic": "工单已评价",
      "operator": "王五",
      "createTime": "2026-01-18 12:30",
      "operationLog": "进度更新",
      "disposalProgress": "已完成",
      "receiveStatus": "已认领",
      "disposalContent": "检查发现投影仪灯泡损坏，已更换新灯泡",
      "disposalDuration": "4天",
      "evaluateStatus": "已评价",
      "satisfaction": "满意",
      "reviewOpinion": "响应及时，处理专业"
    },
    {
      "id": 5,
      "workorderNo": "WO-20260122-005",
      "workorderType": "安全漏洞",
      "source": "系统预警",
      "emergencyDegree": "紧急",
      "location": "数据中心",
      "submitTime": "2026-01-22 08:30",
      "deadline": "2026-01-23 12:00",
      "workorderId": "WO005",
      "relatedResource": "Web服务器",
      "submitBy": "郑十",
      "status": "待处理",
      "description": "发现高危安全漏洞需紧急修复",
      "currentProgress": "待处理",
      "receiveTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-01-22 08:00",
      "operationLog": "工单创建",
      "disposalProgress": "",
      "receiveStatus": "未认领",
      "disposalContent": "",
      "disposalDuration": "",
      "evaluateStatus": "",
      "satisfaction": "",
      "reviewOpinion": ""
    },
    {
      "id": 6,
      "workorderNo": "WO-20260115-006",
      "workorderType": "日常维护",
      "source": "系统预警",
      "emergencyDegree": "中",
      "location": "办公区",
      "submitTime": "2026-01-15 10:00",
      "deadline": "2026-01-25 17:00",
      "workorderId": "WO006",
      "relatedResource": "空调系统",
      "submitBy": "李四",
      "status": "处理中",
      "description": "定期空调系统维护检查",
      "currentProgress": "30%",
      "receiveTime": "2026-01-20 09:00",
      "expectedFinishTime": "2026-01-24 18:00",
      "updateTime": "2026-01-22 14:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "李四",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "initiator": "李四",
      "remindCount": 1,
      "latestDynamic": "已完成区域一检查",
      "operator": "李四",
      "createTime": "2026-01-15 10:00",
      "operationLog": "工单发起",
      "disposalProgress": "检查中",
      "receiveStatus": "已认领",
      "disposalContent": "正在进行空调滤网清洗",
      "disposalDuration": "",
      "evaluateStatus": "",
      "satisfaction": "",
      "reviewOpinion": ""
    },
    {
      "id": 7,
      "workorderNo": "WO-20260117-007",
      "workorderType": "巡检任务",
      "source": "巡查上报",
      "emergencyDegree": "中",
      "location": "备份机房",
      "submitTime": "2026-01-17 11:00",
      "deadline": "2026-01-20 17:00",
      "workorderId": "WO007",
      "relatedResource": "备份服务器",
      "submitBy": "周三",
      "status": "已评价",
      "description": "对备份系统进行恢复验证测试",
      "currentProgress": "100%",
      "receiveTime": "2026-01-17 13:00",
      "expectedFinishTime": "2026-01-20 16:00",
      "updateTime": "2026-01-20 15:30",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-20 15:30",
      "acceptResult": "通过",
      "executor": "李四",
      "attachment": "test_report.pdf",
      "executionDuration": "3天",
      "archiveTime": "2026-01-20 16:00",
      "acceptOpinion": "测试通过，恢复功能正常",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-17 10:30",
      "operationLog": "工单完成",
      "disposalProgress": "已完成",
      "receiveStatus": "已认领",
      "disposalContent": "备份系统验证测试完成",
      "disposalDuration": "3天",
      "evaluateStatus": "已评价",
      "satisfaction": "基本满意",
      "reviewOpinion": "测试过程顺利"
    },
    {
      "id": 8,
      "workorderNo": "WO-20260122-008",
      "workorderType": "日常运维",
      "source": "巡查上报",
      "emergencyDegree": "低",
      "location": "301会议室",
      "submitTime": "2026-01-22 09:00",
      "deadline": "2026-01-22 12:00",
      "workorderId": "WO008",
      "relatedResource": "301会议室",
      "submitBy": "赵六",
      "status": "已评价",
      "description": "调试301会议室的音视频设备",
      "currentProgress": "100%",
      "receiveTime": "2026-01-22 09:30",
      "expectedFinishTime": "2026-01-22 11:30",
      "updateTime": "2026-01-22 11:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-22 11:00",
      "acceptResult": "通过",
      "executor": "李四",
      "attachment": "",
      "executionDuration": "1.5小时",
      "archiveTime": "2026-01-22 11:30",
      "acceptOpinion": "调试完成，设备正常",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-22 08:45",
      "operationLog": "工单完成",
      "disposalProgress": "已完成",
      "receiveStatus": "已认领",
      "disposalContent": "会议设备调试完成",
      "disposalDuration": "1.5小时",
      "evaluateStatus": "已评价",
      "satisfaction": "满意",
      "reviewOpinion": "服务及时"
    }
  ];
};

/** 新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'workorderNo',
      label: '工单编号',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入工单编号',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '设备故障', value: '设备故障' },
          { label: '网络问题', value: '网络问题' },
          { label: '软件问题', value: '软件问题' },
          { label: '硬件维修', value: '硬件维修' },
          { label: '安全漏洞', value: '安全漏洞' },
          { label: '日常维护', value: '日常维护' },
          { label: '巡检任务', value: '巡检任务' },
          { label: '其他', value: '其他' },
        ],
        placeholder: '请选择工单类型',
        showSearch: true,
      },
      fieldName: 'workorderType',
      label: '工单类型',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        options: [
          { label: '巡查上报', value: '巡查上报' },
          { label: '用户投诉', value: '用户投诉' },
          { label: '系统预警', value: '系统预警' },
        ],
        placeholder: '请选择发起来源',
      },
      fieldName: 'source',
      label: '发起来源',
    },
    {
      fieldName: 'emergencyDegree',
      label: '紧急程度',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '紧急', value: '紧急' },
          { label: '高', value: '高' },
          { label: '中', value: '中' },
          { label: '低', value: '低' },
        ],
        placeholder: '请选择紧急程度',
      },
      rules: 'required',
    },
    {
      fieldName: 'deadline',
      label: '截止时间',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'datetime',
        placeholder: '请选择截止时间',
      },
      rules: 'required',
    },
    {
      fieldName: 'description',
      label: '问题描述',
      component: 'Textarea',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入问题描述',
        rows: 3,
      },
    },
    {
      fieldName: 'location',
      label: '发生地点',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入发生地点',
      },
    },
    {
      fieldName: 'submitBy',
      label: '发起方',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入发起方',
      },
    },
    {
      fieldName: 'status',
      label: '工单状态',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '待处理', value: '待处理' },
          { label: '已认领', value: '已认领' },
          { label: '处理中', value: '处理中' },
          { label: '已完成', value: '已完成' },
          { label: '已评价', value: '已评价' },
          { label: '已撤回', value: '已撤回' },
        ],
        placeholder: '请选择工单状态',
      },
    },
    {
      fieldName: 'submitTime',
      label: '提交时间',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'datetime',
        placeholder: '请选择提交时间',
      },
    },
    {
      fieldName: 'relatedResource',
      label: '关联资源',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入关联资源',
      },
    },
  ];
}

/** 表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'workorderNo',
      title: '工单编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'workorderNo' },
    },
    {
      field: 'workorderType',
      title: '工单类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'source',
      title: '发起来源',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'emergencyDegree',
      title: '紧急程度',
      minWidth: 100,
      sortable: true,
      slots: { default: 'emergencyDegree' },
    },
    {
      field: 'location',
      title: '发生地点',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'submitTime',
      title: '提交时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'deadline',
      title: '截止时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'status',
      title: '工单状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'status' },
    },
    {
      field: 'submitBy',
      title: '发起方',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'currentProgress',
      title: '处置进度',
      minWidth: 120,
      sortable: true,
      slots: { default: 'progress' },
    },
    {
      title: '操作',
      width: 220,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑工单',
  addText: '新建工单',
  excelName: '工单列表',
  excelAllName: '工单数据.xlsx',
  total: '工单总数: 8; 待处理: 2; 处理中: 2; 已完成: 4;',
};
