// data.js
/** 运维效率报表 - 初始数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "maintainer": "张三",
      "areaName": "天河区",
      "orderType": "设备维修",
      "totalWorkorder": 48,
      "completedWorkorder": 45,
      "closedRate": "93.75%",
      "avgDisposalDuration": "3.2小时",
      "overtimeCount": 3,
      "overtimeRate": "6.25%",
      "pendingWorkorder": 3,
      "inProgressWorkorder": 2,
      "avgResponseDuration": "25分钟",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 2,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "maintainer": "李四",
      "areaName": "越秀区",
      "orderType": "设备巡检",
      "totalWorkorder": 32,
      "completedWorkorder": 31,
      "closedRate": "96.88%",
      "avgDisposalDuration": "2.8小时",
      "overtimeCount": 1,
      "overtimeRate": "3.13%",
      "pendingWorkorder": 1,
      "inProgressWorkorder": 1,
      "avgResponseDuration": "22分钟",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 3,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "maintainer": "王五",
      "areaName": "海珠区",
      "orderType": "设备保养",
      "totalWorkorder": 28,
      "completedWorkorder": 27,
      "closedRate": "96.43%",
      "avgDisposalDuration": "4.1小时",
      "overtimeCount": 1,
      "overtimeRate": "3.57%",
      "pendingWorkorder": 1,
      "inProgressWorkorder": 0,
      "avgResponseDuration": "28分钟",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 4,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "maintainer": "赵六",
      "areaName": "白云区",
      "orderType": "故障处理",
      "totalWorkorder": 35,
      "completedWorkorder": 32,
      "closedRate": "91.43%",
      "avgDisposalDuration": "5.6小时",
      "overtimeCount": 3,
      "overtimeRate": "8.57%",
      "pendingWorkorder": 3,
      "inProgressWorkorder": 2,
      "avgResponseDuration": "35分钟",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 5,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "maintainer": "钱七",
      "areaName": "黄埔区",
      "orderType": "设备安装",
      "totalWorkorder": 18,
      "completedWorkorder": 18,
      "closedRate": "100%",
      "avgDisposalDuration": "6.8小时",
      "overtimeCount": 0,
      "overtimeRate": "0%",
      "pendingWorkorder": 0,
      "inProgressWorkorder": 0,
      "avgResponseDuration": "30分钟",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 6,
      "startDate": "2026-01-25",
      "endDate": "2026-01-31",
      "maintainer": "张三",
      "areaName": "天河区",
      "orderType": "设备维修",
      "totalWorkorder": 52,
      "completedWorkorder": 48,
      "closedRate": "92.31%",
      "avgDisposalDuration": "3.5小时",
      "overtimeCount": 4,
      "overtimeRate": "7.69%",
      "pendingWorkorder": 4,
      "inProgressWorkorder": 3,
      "avgResponseDuration": "27分钟",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 7,
      "startDate": "2026-01-25",
      "endDate": "2026-01-31",
      "maintainer": "李四",
      "areaName": "越秀区",
      "orderType": "设备巡检",
      "totalWorkorder": 38,
      "completedWorkorder": 36,
      "closedRate": "94.74%",
      "avgDisposalDuration": "3.0小时",
      "overtimeCount": 2,
      "overtimeRate": "5.26%",
      "pendingWorkorder": 2,
      "inProgressWorkorder": 1,
      "avgResponseDuration": "24分钟",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 8,
      "startDate": "2026-01-20",
      "endDate": "2026-01-26",
      "maintainer": "王五",
      "areaName": "海珠区",
      "orderType": "设备保养",
      "totalWorkorder": 32,
      "completedWorkorder": 30,
      "closedRate": "93.75%",
      "avgDisposalDuration": "4.5小时",
      "overtimeCount": 2,
      "overtimeRate": "6.25%",
      "pendingWorkorder": 2,
      "inProgressWorkorder": 1,
      "avgResponseDuration": "32分钟",
      "updateTime": "2026-01-26 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 9,
      "startDate": "2026-01-20",
      "endDate": "2026-01-26",
      "maintainer": "赵六",
      "areaName": "白云区",
      "orderType": "故障处理",
      "totalWorkorder": 42,
      "completedWorkorder": 38,
      "closedRate": "90.48%",
      "avgDisposalDuration": "6.2小时",
      "overtimeCount": 4,
      "overtimeRate": "9.52%",
      "pendingWorkorder": 4,
      "inProgressWorkorder": 3,
      "avgResponseDuration": "40分钟",
      "updateTime": "2026-01-26 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 10,
      "startDate": "2026-01-15",
      "endDate": "2026-01-21",
      "maintainer": "钱七",
      "areaName": "黄埔区",
      "orderType": "设备安装",
      "totalWorkorder": 22,
      "completedWorkorder": 22,
      "closedRate": "100%",
      "avgDisposalDuration": "7.2小时",
      "overtimeCount": 0,
      "overtimeRate": "0%",
      "pendingWorkorder": 0,
      "inProgressWorkorder": 0,
      "avgResponseDuration": "33分钟",
      "updateTime": "2026-01-21 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 11,
      "startDate": "2026-01-01",
      "endDate": "2026-01-31",
      "maintainer": "张三",
      "areaName": "荔湾区",
      "orderType": "设备维修",
      "totalWorkorder": 68,
      "completedWorkorder": 64,
      "closedRate": "94.12%",
      "avgDisposalDuration": "3.8小时",
      "overtimeCount": 4,
      "overtimeRate": "5.88%",
      "pendingWorkorder": 4,
      "inProgressWorkorder": 2,
      "avgResponseDuration": "29分钟",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 12,
      "startDate": "2026-01-01",
      "endDate": "2026-01-31",
      "maintainer": "李四",
      "areaName": "番禺区",
      "orderType": "设备巡检",
      "totalWorkorder": 45,
      "completedWorkorder": 44,
      "closedRate": "97.78%",
      "avgDisposalDuration": "2.9小时",
      "overtimeCount": 1,
      "overtimeRate": "2.22%",
      "pendingWorkorder": 1,
      "inProgressWorkorder": 1,
      "avgResponseDuration": "26分钟",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    }
  ];
};

/** 搜索表单配置 */
export function useFormSchema() {
  return [
    {
      fieldName: 'dateRange',
      label: '时间范围',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'daterange',
        startPlaceholder: '开始日期',
        endPlaceholder: '结束日期',
      },
      rules: 'required',
    },
    {
      fieldName: 'maintainer',
      label: '运维人员',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '张三', value: '张三' },
          { label: '李四', value: '李四' },
          { label: '王五', value: '王五' },
          { label: '赵六', value: '赵六' },
          { label: '钱七', value: '钱七' },
          { label: '孙八', value: '孙八' },
          { label: '周九', value: '周九' },
        ],
        placeholder: '请选择运维人员',
        showSearch: true,
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
      },
      fieldName: 'areaName',
      label: '行政区域',
    },
    {
      fieldName: 'orderType',
      label: '工单类型',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '设备维修', value: '设备维修' },
          { label: '设备巡检', value: '设备巡检' },
          { label: '设备保养', value: '设备保养' },
          { label: '故障处理', value: '故障处理' },
          { label: '设备安装', value: '设备安装' },
          { label: '系统维护', value: '系统维护' },
          { label: '紧急抢修', value: '紧急抢修' },
        ],
        placeholder: '请选择工单类型',
      },
    },
  ];
}

/** 表格字段配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'dateRange',
      title: '时间范围',
      minWidth: 180,
      sortable: true,
      slots: { default: 'dateRange' },
    },
    {
      field: 'maintainer',
      title: '运维人员',
      minWidth: 100,
      sortable: true,
      slots: { default: 'maintainer' },
    },
    {
      field: 'areaName',
      title: '行政区域',
      minWidth: 100,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'orderType',
      title: '工单类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'orderType' },
    },
    {
      field: 'totalWorkorder',
      title: '总工单数',
      minWidth: 100,
      sortable: true,
      slots: { default: 'totalWorkorder' },
    },
    {
      field: 'completedWorkorder',
      title: '已完成数',
      minWidth: 100,
      sortable: true,
      slots: { default: 'completedWorkorder' },
    },
    {
      field: 'closedRate',
      title: '闭环率',
      minWidth: 100,
      sortable: true,
      slots: { default: 'closedRate' },
    },
    {
      field: 'avgDisposalDuration',
      title: '平均处置时长',
      minWidth: 130,
      sortable: true,
      slots: { default: 'avgDisposalDuration' },
    },
    {
      field: 'overtimeCount',
      title: '超时数',
      minWidth: 100,
      sortable: true,
      slots: { default: 'overtimeCount' },
    },
    {
      field: 'avgResponseDuration',
      title: '平均响应时长',
      minWidth: 130,
      sortable: true,
      slots: { default: 'avgResponseDuration' },
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑报表',
  addText: '新增报表',
  excelName: '运维效率报表',
  excelAllName: '运维效率报表.xlsx',
  total: '报表总数: 12; 本周工单: 161; 本月工单: 420;',
};
