/** 表格初始数据 - 违停监测管理数据 */
export const dataList = () => [
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    license_plate: '闽A·12345',
    parking_type_id: '占用消防通道',
    location: '福州市鼓楼区杨桥东路50号',
    parking_time: '2026-03-15 14:23:45',
    monitor_type_id: 'AI视频监控',
    area_code: '350102',
    law_enforcer_id: '张三',
    warning_photos: '["https://example.com/photo1.jpg", "https://example.com/photo2.jpg"]',
    warning_time: '2026-03-15 14:25:30',
    verify_result: '合格',
    enforcement_measure: '警告劝离',
    enforce_no: 'ZF-20260315-001',
    law_result_id: '已处理',
    violation_no: 'WF-20260315-001',
    invalid_reason: '',
    create_time: '2026-03-15 14:30:00',
    update_time: '2026-03-15 14:30:00',
    del_flag: 0,
  },
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    license_plate: '闽C·67890',
    parking_type_id: '占用公交站点',
    location: '厦门市思明区鹭江道100号',
    parking_time: '2026-03-15 09:15:20',
    monitor_type_id: '地磁传感器',
    area_code: '350203',
    law_enforcer_id: '李四',
    warning_photos: '["https://example.com/photo3.jpg"]',
    warning_time: '2026-03-15 09:18:45',
    verify_result: '合格',
    enforcement_measure: '违停告知单',
    enforce_no: 'ZF-20260315-002',
    law_result_id: '已处理',
    violation_no: 'WF-20260315-002',
    invalid_reason: '',
    create_time: '2026-03-15 09:30:00',
    update_time: '2026-03-15 09:30:00',
    del_flag: 0,
  },
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
    license_plate: '闽D·24680',
    parking_type_id: '人行道违停',
    location: '泉州市丰泽区刺桐路300号',
    parking_time: '2026-03-14 18:30:10',
    monitor_type_id: '人工巡检',
    area_code: '350503',
    law_enforcer_id: '王五',
    warning_photos: '["https://example.com/photo4.jpg", "https://example.com/photo5.jpg"]',
    warning_time: '2026-03-14 18:35:20',
    verify_result: '不合格',
    enforcement_measure: '强制拖离',
    enforce_no: 'ZF-20260314-003',
    law_result_id: '处理中',
    violation_no: 'WF-20260314-003',
    invalid_reason: '车辆已驶离现场',
    create_time: '2026-03-14 18:50:00',
    update_time: '2026-03-15 10:30:00',
    del_flag: 0,
  },
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14',
    license_plate: '闽E·13579',
    parking_type_id: '禁停区域',
    location: '漳州市芗城区胜利路150号',
    parking_time: '2026-03-14 11:05:30',
    monitor_type_id: '市民举报',
    area_code: '350602',
    law_enforcer_id: '赵六',
    warning_photos: '[]',
    warning_time: '2026-03-14 11:10:15',
    verify_result: '合格',
    enforcement_measure: '警告劝离',
    enforce_no: 'ZF-20260314-004',
    law_result_id: '已归档',
    violation_no: 'WF-20260314-004',
    invalid_reason: '',
    create_time: '2026-03-14 11:20:00',
    update_time: '2026-03-14 11:20:00',
    del_flag: 0,
  },
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15',
    license_plate: '闽B·97531',
    parking_type_id: '占用消防通道',
    location: '莆田市城厢区荔城南大道200号',
    parking_time: '2026-03-13 20:45:00',
    monitor_type_id: 'AI视频监控',
    area_code: '350302',
    law_enforcer_id: '张三',
    warning_photos: '["https://example.com/photo6.jpg"]',
    warning_time: '2026-03-13 20:50:30',
    verify_result: '合格',
    enforcement_measure: '违停告知单',
    enforce_no: 'ZF-20260313-005',
    law_result_id: '已处理',
    violation_no: 'WF-20260313-005',
    invalid_reason: '',
    create_time: '2026-03-13 21:00:00',
    update_time: '2026-03-13 21:00:00',
    del_flag: 0,
  },
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16',
    license_plate: '闽J·54321',
    parking_type_id: '占用公交站点',
    location: '宁德市蕉城区闽东中路88号',
    parking_time: '2026-03-13 08:10:15',
    monitor_type_id: '地磁传感器',
    area_code: '350902',
    law_enforcer_id: '李四',
    warning_photos: '["https://example.com/photo7.jpg", "https://example.com/photo8.jpg", "https://example.com/photo9.jpg"]',
    warning_time: '2026-03-13 08:15:40',
    verify_result: '不合格',
    enforcement_measure: '强制拖离',
    enforce_no: 'ZF-20260313-006',
    law_result_id: '处理中',
    violation_no: 'WF-20260313-006',
    invalid_reason: '车牌识别错误',
    create_time: '2026-03-13 08:30:00',
    update_time: '2026-03-14 09:15:00',
    del_flag: 1,
  },
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17',
    license_plate: '闽F·86420',
    parking_type_id: '人行道违停',
    location: '龙岩市新罗区龙川路60号',
    parking_time: '2026-03-12 16:20:30',
    monitor_type_id: '人工巡检',
    area_code: '350802',
    law_enforcer_id: '王五',
    warning_photos: '["https://example.com/photo10.jpg"]',
    warning_time: '2026-03-12 16:25:15',
    verify_result: '合格',
    enforcement_measure: '警告劝离',
    enforce_no: 'ZF-20260312-007',
    law_result_id: '已处理',
    violation_no: 'WF-20260312-007',
    invalid_reason: '',
    create_time: '2026-03-12 16:40:00',
    update_time: '2026-03-12 16:40:00',
    del_flag: 0,
  },
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a18',
    license_plate: '闽G·36925',
    parking_type_id: '禁停区域',
    location: '三明市梅列区列东街120号',
    parking_time: '2026-03-12 10:05:45',
    monitor_type_id: '市民举报',
    area_code: '350402',
    law_enforcer_id: '赵六',
    warning_photos: '[]',
    warning_time: '2026-03-12 10:10:20',
    verify_result: '合格',
    enforcement_measure: '违停告知单',
    enforce_no: 'ZF-20260312-008',
    law_result_id: '已归档',
    violation_no: 'WF-20260312-008',
    invalid_reason: '',
    create_time: '2026-03-12 10:25:00',
    update_time: '2026-03-12 10:25:00',
    del_flag: 0,
  },
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a19',
    license_plate: '闽H·14758',
    parking_type_id: '占用消防通道',
    location: '南平市延平区八一路45号',
    parking_time: '2026-03-11 13:50:20',
    monitor_type_id: 'AI视频监控',
    area_code: '350702',
    law_enforcer_id: '张三',
    warning_photos: '["https://example.com/photo11.jpg", "https://example.com/photo12.jpg"]',
    warning_time: '2026-03-11 13:55:30',
    verify_result: '合格',
    enforcement_measure: '警告劝离',
    enforce_no: 'ZF-20260311-009',
    law_result_id: '已处理',
    violation_no: 'WF-20260311-009',
    invalid_reason: '',
    create_time: '2026-03-11 14:10:00',
    update_time: '2026-03-11 14:10:00',
    del_flag: 0,
  },
  {
    illegal_parking_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a20',
    license_plate: '闽K·25863',
    parking_type_id: '占用公交站点',
    location: '平潭综合实验区金井大道88号',
    parking_time: '2026-03-11 07:30:00',
    monitor_type_id: '地磁传感器',
    area_code: '350128',
    law_enforcer_id: '李四',
    warning_photos: '["https://example.com/photo13.jpg"]',
    warning_time: '2026-03-11 07:35:10',
    verify_result: '不合格',
    enforcement_measure: '强制拖离',
    enforce_no: 'ZF-20260311-010',
    law_result_id: '待处理',
    violation_no: 'WF-20260311-010',
    invalid_reason: '监测设备故障',
    create_time: '2026-03-11 07:50:00',
    update_time: '2026-03-12 08:20:00',
    del_flag: 0,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 违停监测管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'illegal_parking_id',
      label: '主键ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入主键ID',
        disabled: true,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'license_plate',
      label: '车牌号码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入车牌号码',
        maxlength: 20,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'parking_type_id',
      label: '违停类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择违停类型',
        options: [
          { label: '占用消防通道', value: '占用消防通道' },
          { label: '占用公交站点', value: '占用公交站点' },
          { label: '人行道违停', value: '人行道违停' },
          { label: '禁停区域', value: '禁停区域' },
        ],
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'location',
      label: '违停位置',
      component: 'Input',
      componentProps: {
        placeholder: '请输入违停位置',
        maxlength: 200,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'parking_time',
      label: '违停时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择违停时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'monitor_type_id',
      label: '监测方式',
      component: 'Select',
      componentProps: {
        placeholder: '请选择监测方式',
        options: [
          { label: 'AI视频监控', value: 'AI视频监控' },
          { label: '地磁传感器', value: '地磁传感器' },
          { label: '人工巡检', value: '人工巡检' },
          { label: '市民举报', value: '市民举报' },
        ],
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'area_code',
      label: '责任片区',
      component: 'Select',
      componentProps: {
        placeholder: '请选择责任片区',
        options: [
          { label: '鼓楼区', value: '350102' },
          { label: '思明区', value: '350203' },
          { label: '丰泽区', value: '350503' },
          { label: '芗城区', value: '350602' },
        ],
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'law_enforcer_id',
      label: '执法员',
      component: 'Select',
      componentProps: {
        placeholder: '请选择执法员',
        options: [
          { label: '张三', value: '张三' },
          { label: '李四', value: '李四' },
          { label: '王五', value: '王五' },
          { label: '赵六', value: '赵六' },
        ],
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'warning_photos',
      label: '预警照片',
      component: 'Input',
      componentProps: {
        placeholder: '请输入预警照片URL',
        type: 'textarea',
        rows: 2,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'warning_time',
      label: '预警时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择预警时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'verify_result',
      label: '校验结果',
      component: 'Select',
      componentProps: {
        placeholder: '请选择校验结果',
        options: [
          { label: '合格', value: '合格' },
          { label: '不合格', value: '不合格' },
        ],
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'enforcement_measure',
      label: '执法措施',
      component: 'Select',
      componentProps: {
        placeholder: '请选择执法措施',
        options: [
          { label: '警告劝离', value: '警告劝离' },
          { label: '违停告知单', value: '违停告知单' },
          { label: '强制拖离', value: '强制拖离' },
        ],
      },
      labelWidth: '130',
    },
    {
      fieldName: 'enforce_no',
      label: '执法编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入执法编号',
        maxlength: 50,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'law_result_id',
      label: '执法结果',
      component: 'Select',
      componentProps: {
        placeholder: '请选择执法结果',
        options: [
          { label: '已处理', value: '已处理' },
          { label: '待处理', value: '待处理' },
          { label: '处理中', value: '处理中' },
          { label: '已归档', value: '已归档' },
        ],
      },
      labelWidth: '130',
    },
    {
      fieldName: 'violation_no',
      label: '违章记录编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入违章记录编号',
        maxlength: 50,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'invalid_reason',
      label: '无效原因',
      component: 'Input',
      componentProps: {
        placeholder: '请输入无效原因',
        type: 'textarea',
        rows: 2,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'create_time',
      label: '创建时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择创建时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        disabled: true,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'update_time',
      label: '更新时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择更新时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        disabled: true,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'del_flag',
      label: '删除标记',
      component: 'Select',
      componentProps: {
        placeholder: '请选择删除标记',
        options: [
          { label: '未删除', value: 0 },
          { label: '已删除', value: 1 },
        ],
      },
      labelWidth: '130',
    },
  ];
}

/** 表格字段 - 违停监测管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'license_plate',
      title: '车牌号码',
      minWidth: 120,
      sortable: true,
      slots: { default: 'license_plate' },
    },
    {
      field: 'parking_type_id',
      title: '违停类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'parking_type_id' },
    },
    {
      field: 'location',
      title: '违停位置',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'parking_time',
      title: '违停时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'monitor_type_id',
      title: '监测方式',
      minWidth: 120,
      sortable: true,
      slots: { default: 'monitor_type_id' },
    },
    {
      field: 'area_code',
      title: '责任片区',
      minWidth: 100,
      sortable: true,
      slots: { default: 'area_code' },
    },
    {
      field: 'law_enforcer_id',
      title: '执法员',
      minWidth: 100,
      sortable: true,
      slots: { default: 'law_enforcer_id' },
    },
    {
      field: 'warning_time',
      title: '预警时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'verify_result',
      title: '校验结果',
      minWidth: 100,
      sortable: true,
      slots: {
        default: 'verify_result',
      },
    },
    {
      field: 'enforcement_measure',
      title: '执法措施',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'enforce_no',
      title: '执法编号',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'law_result_id',
      title: '执法结果',
      minWidth: 120,
      sortable: true,
      slots: { default: 'law_result_id' },
    },
    {
      field: 'violation_no',
      title: '违章记录编号',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'invalid_reason',
      title: '无效原因',
      minWidth: 150,
      sortable: false,
    },
    {
      field: 'create_time',
      title: '创建时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'update_time',
      title: '更新时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'del_flag',
      title: '删除标记',
      minWidth: 100,
      sortable: true,
      slots: { default: 'del_flag' },
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
