/** 表格初始数据 - 改造为占道经营月度统计分析数据 */
export const dataList = () => [
  {
    regionName: '鼓楼区',
    roadLevel: '主干道',
    occupationType: '商业占道',
    monthlyOccupationCaseTotal: 120,
    monthlyKeyAreaControlRate: 95.5,
    monthlyGuidancePointStandardizationRate: 88.0,
    monthlyLawEnforcementPatrolCoverage: 92.0,
    monthlyRepeatedOccupationPointRectificationRate: 85.0,
    momChangeRate: 5.2,
    yoyChangeRate: 10.8,
    monthlyTrendAnalysis: '整体呈上升趋势，商业占道案件增多',
  },
  {
    regionName: '台江区',
    roadLevel: '次干道',
    occupationType: '流动摊贩',
    monthlyOccupationCaseTotal: 85,
    monthlyKeyAreaControlRate: 92.0,
    monthlyGuidancePointStandardizationRate: 85.5,
    monthlyLawEnforcementPatrolCoverage: 89.0,
    monthlyRepeatedOccupationPointRectificationRate: 80.0,
    momChangeRate: -2.1,
    yoyChangeRate: 5.4,
    monthlyTrendAnalysis: '流动摊贩占道有所减少，管控效果提升',
  },
  {
    regionName: '仓山区',
    roadLevel: '支路',
    occupationType: '商业占道',
    monthlyOccupationCaseTotal: 65,
    monthlyKeyAreaControlRate: 89.0,
    monthlyGuidancePointStandardizationRate: 82.0,
    monthlyLawEnforcementPatrolCoverage: 85.0,
    monthlyRepeatedOccupationPointRectificationRate: 78.0,
    momChangeRate: 3.8,
    yoyChangeRate: 2.1,
    monthlyTrendAnalysis: '支路占道案件稳定，重点区域管控良好',
  },
  {
    regionName: '晋安区',
    roadLevel: '主干道',
    occupationType: '流动摊贩',
    monthlyOccupationCaseTotal: 95,
    monthlyKeyAreaControlRate: 94.0,
    monthlyGuidancePointStandardizationRate: 87.0,
    monthlyLawEnforcementPatrolCoverage: 91.0,
    monthlyRepeatedOccupationPointRectificationRate: 83.0,
    momChangeRate: 7.5,
    yoyChangeRate: 12.3,
    monthlyTrendAnalysis: '主干道流动摊贩增多，需加强巡查',
  },
  {
    regionName: '马尾区',
    roadLevel: '次干道',
    occupationType: '商业占道',
    monthlyOccupationCaseTotal: 45,
    monthlyKeyAreaControlRate: 91.0,
    monthlyGuidancePointStandardizationRate: 84.0,
    monthlyLawEnforcementPatrolCoverage: 87.0,
    monthlyRepeatedOccupationPointRectificationRate: 81.0,
    momChangeRate: -1.2,
    yoyChangeRate: -3.0,
    monthlyTrendAnalysis: '占道案件减少，整治效果显著',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为占道经营月度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'regionName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'roadLevel',
      label: '路段等级',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段等级（如：主干道、次干道、支路）',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'occupationType',
      label: '占道类型',
      component: 'Input',
      componentProps: {
        placeholder: '请输入占道类型（如：商业占道、流动摊贩）',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'monthlyOccupationCaseTotal',
      label: '月占道经营案件总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入月占道经营案件总量',
        min: 0,
        precision: 0,
        addonAfter: '件',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyKeyAreaControlRate',
      label: '月重点区域管控率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入月重点区域管控率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyGuidancePointStandardizationRate',
      label: '月疏导点规范化运营率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入月疏导点规范化运营率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyLawEnforcementPatrolCoverage',
      label: '月执法巡查覆盖率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入月执法巡查覆盖率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyRepeatedOccupationPointRectificationRate',
      label: '月重复占道点位整改率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入月重复占道点位整改率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate',
      label: '环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate',
      label: '同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyTrendAnalysis',
      label: '月度趋势分析',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入月度趋势分析（如：整体呈上升趋势，商业占道案件增多）',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为占道经营月度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'regionName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'roadLevel',
      title: '路段等级',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'occupationType',
      title: '占道类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monthlyOccupationCaseTotal',
      title: '月占道经营案件总量',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'monthlyKeyAreaControlRate',
      title: '月重点区域管控率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'monthlyGuidancePointStandardizationRate',
      title: '月疏导点规范化运营率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'monthlyLawEnforcementPatrolCoverage',
      title: '月执法巡查覆盖率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'monthlyRepeatedOccupationPointRectificationRate',
      title: '月重复占道点位整改率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate',
      title: '环比变化率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'yoyChangeRate',
      title: '同比变化率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monthlyTrendAnalysis',
      title: '月度趋势分析',
      minWidth: 180,
      sortable: false,
    },
  ];
}
