/** 表格初始数据 - 排水管网监测数据 */
export const dataList = () => [
  {
    id: 1,
    pipe_road: '福州市鼓楼区杨桥东路排水管网',
    pipe_level: 1.2,
    pipe_flow_speed: 0.8,
    rainfall: 5.2,
    device_id: 101,
    code: 'FJ-FZ-202406-001',
    status: '在线',
    staff_id: 201,
    user_name: '陈铭（工号：FJYW001）',
    collect_frequency_type: '常规',
    sync_duration: 3,
    monitor_status: '运行中',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:30:00',
    rain_warn_switch: '开启',
  },
  {
    id: 2,
    pipe_road: '厦门市思明区鹭江道排水管网',
    pipe_level: 0.8,
    pipe_flow_speed: 0.6,
    rainfall: 3.5,
    device_id: 102,
    code: 'FJ-XM-202406-002',
    status: '在线',
    staff_id: 202,
    user_name: '林晓婷（工号：FJYW002）',
    collect_frequency_type: '常规',
    sync_duration: 5,
    monitor_status: '运行中',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:35:00',
    rain_warn_switch: '开启',
  },
  {
    id: 3,
    pipe_road: '泉州市丰泽区刺桐路排水管网',
    pipe_level: 1.8,
    pipe_flow_speed: 1.2,
    rainfall: 8.7,
    device_id: 103,
    code: 'FJ-QZ-202406-003',
    status: '异常',
    staff_id: 203,
    user_name: '王志远（工号：FJYW003）',
    collect_frequency_type: '降雨期',
    sync_duration: 2,
    monitor_status: '数据异常',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:28:00',
    rain_warn_switch: '开启',
  },
  {
    id: 4,
    pipe_road: '漳州市芗城区胜利路排水管网',
    pipe_level: 0.5,
    pipe_flow_speed: 0.4,
    rainfall: 1.2,
    device_id: 104,
    code: 'FJ-ZZ-202406-004',
    status: '在线',
    staff_id: 204,
    user_name: '黄丽萍（工号：FJYW004）',
    collect_frequency_type: '常规',
    sync_duration: 4,
    monitor_status: '运行中',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:32:00',
    rain_warn_switch: '关闭',
  },
  {
    id: 5,
    pipe_road: '莆田市城厢区荔城南大道排水管网',
    pipe_level: 1.5,
    pipe_flow_speed: 1.0,
    rainfall: 6.8,
    device_id: 105,
    code: 'FJ-PT-202406-005',
    status: '离线',
    staff_id: 205,
    user_name: '郑建明（工号：FJYW005）',
    collect_frequency_type: '降雨期',
    sync_duration: 6,
    monitor_status: '设备故障',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:25:00',
    rain_warn_switch: '开启',
  },
  {
    id: 6,
    pipe_road: '宁德市蕉城区闽东中路排水管网',
    pipe_level: 1.0,
    pipe_flow_speed: 0.7,
    rainfall: 4.5,
    device_id: 106,
    code: 'FJ-ND-202406-006',
    status: '在线',
    staff_id: 206,
    user_name: '吴永辉（工号：FJYW006）',
    collect_frequency_type: '常规',
    sync_duration: 3,
    monitor_status: '运行中',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:31:00',
    rain_warn_switch: '开启',
  },
  {
    id: 7,
    pipe_road: '龙岩市新罗区龙川路排水管网',
    pipe_level: 1.3,
    pipe_flow_speed: 0.9,
    rainfall: 5.9,
    device_id: 107,
    code: 'FJ-LY-202406-007',
    status: '在线',
    staff_id: 207,
    user_name: '张志强（工号：FJYW007）',
    collect_frequency_type: '降雨期',
    sync_duration: 4,
    monitor_status: '人工巡检中',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:29:00',
    rain_warn_switch: '开启',
  },
  {
    id: 8,
    pipe_road: '三明市梅列区列东街排水管网',
    pipe_level: 0.7,
    pipe_flow_speed: 0.5,
    rainfall: 2.8,
    device_id: 108,
    code: 'FJ-SM-202406-008',
    status: '在线',
    staff_id: 208,
    user_name: '李芳（工号：FJYW008）',
    collect_frequency_type: '常规',
    sync_duration: 5,
    monitor_status: '运行中',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:33:00',
    rain_warn_switch: '关闭',
  },
  {
    id: 9,
    pipe_road: '南平市延平区八一路排水管网',
    pipe_level: 1.6,
    pipe_flow_speed: 1.1,
    rainfall: 7.3,
    device_id: 109,
    code: 'FJ-NP-202406-009',
    status: '异常',
    staff_id: 209,
    user_name: '刘建国（工号：FJYW009）',
    collect_frequency_type: '降雨期',
    sync_duration: 2,
    monitor_status: '已停止',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:27:00',
    rain_warn_switch: '开启',
  },
  {
    id: 10,
    pipe_road: '平潭综合实验区金井大道排水管网',
    pipe_level: 0.9,
    pipe_flow_speed: 0.6,
    rainfall: 3.9,
    device_id: 110,
    code: 'FJ-PTTH-202406-010',
    status: '在线',
    staff_id: 210,
    user_name: '蔡伟明（工号：FJYW010）',
    collect_frequency_type: '常规',
    sync_duration: 6,
    monitor_status: '运行中',
    pipe_level_threshold: '0-2.0',
    pipe_flow_speed_threshold: '0-1.5',
    rainfall_threshold: '0-10',
    update_time: '2024-06-15 10:34:00',
    rain_warn_switch: '开启',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为排水管网监测管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'pipe_road',
      label: '管网路段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管网路段名称',
      },
      labelWidth: '120',
      rules: 'required',
      isSearch: true,
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'pipe_level',
      label: '管网液位',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入管网液位（单位：米）',
        min: 0,
        precision: 2,
        addonAfter: '米',
      },
      rules: 'required',
    },
    {
      fieldName: 'pipe_flow_speed',
      label: '管网流速',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入管网流速（单位：米/秒）',
        min: 0,
        precision: 2,
        addonAfter: '米/秒',
      },
      rules: 'required',
    },
    {
      fieldName: 'rainfall',
      label: '降雨量',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入降雨量（单位：毫米）',
        min: 0,
        precision: 2,
        addonAfter: '毫米',
      },
      rules: 'required',
    },
    {
      fieldName: 'device_id',
      label: '设备ID',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入设备ID',
        min: 0,
        precision: 0,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'code',
      label: '监测设备编号',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入监测设备编号',
        maxLength: 50,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'status',
      label: '设备在线状态',
      rules: 'required',
      isSearch: true,
    },
    {
      fieldName: 'staff_id',
      label: '运维员ID',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入运维员ID',
        min: 0,
        precision: 0,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'user_name',
      label: '负责运维员',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入负责运维员姓名',
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '常规', value: '常规' },
          { label: '降雨期', value: '降雨期' },
        ],
        placeholder: '请选择采集频率类型',
        showSearch: true,
      },
      fieldName: 'collect_frequency_type',
      label: '采集频率类型',
      rules: 'required',
      isSearch: true,
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'sync_duration',
      label: '数据同步时长',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入数据同步时长（单位：秒）',
        min: 1,
        precision: 0,
        addonAfter: '秒',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '运行中', value: '运行中' },
          { label: '已停止', value: '已停止' },
          { label: '数据异常', value: '数据异常' },
          { label: '设备故障', value: '设备故障' },
          { label: '人工巡检中', value: '人工巡检中' },
        ],
        placeholder: '请选择监测状态',
        showSearch: true,
      },
      fieldName: 'monitor_status',
      label: '监测状态',
      rules: 'required',
      isSearch: true,
      editShow: true,
    },
    {
      fieldName: 'pipe_level_threshold',
      label: '液位阈值',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入液位阈值范围（如：0-2.0）',
        maxLength: 50,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'pipe_flow_speed_threshold',
      label: '流速阈值',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入流速阈值范围（如：0-1.5）',
        maxLength: 50,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'rainfall_threshold',
      label: '降雨量阈值',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入降雨量阈值范围（如：0-10）',
        maxLength: 50,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '开启', value: '开启' },
          { label: '关闭', value: '关闭' },
        ],
        placeholder: '请选择降雨联动预警开关',
        showSearch: true,
      },
      fieldName: 'rain_warn_switch',
      label: '降雨联动预警开关',
      rules: 'required',
      addShow: true,
      editShow: true,
    },
  ];
}

/** 表格字段 - 改造为排水管网监测管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'pipe_road',
      title: '管网路段',
      minWidth: 200,
      sortable: true,
      slots: { default: 'pipe_road' },
    },
    {
      field: 'pipe_level',
      title: '管网液位(米)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'pipe_flow_speed',
      title: '管网流速(米/秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'rainfall',
      title: '降雨量(毫米)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'code',
      title: '监测设备编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'code' },
    },
    {
      field: 'status',
      title: '设备在线状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'status' },
    },
    {
      field: 'user_name',
      title: '负责运维员',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'collect_frequency_type',
      title: '采集频率类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'collect_frequency_type' },
    },
    {
      field: 'sync_duration',
      title: '数据同步时长(秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monitor_status',
      title: '监测状态',
      minWidth: 180,
      sortable: true,
      slots: { default: 'monitor_status' },
    },
    {
      field: 'pipe_level_threshold',
      title: '液位阈值',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'pipe_flow_speed_threshold',
      title: '流速阈值',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'rainfall_threshold',
      title: '降雨量阈值',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'update_time',
      title: '最近更新时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'rain_warn_switch',
      title: '降雨联动预警开关',
      minWidth: 140,
      sortable: true,
    },
    {
      title: '操作',
      width: 120,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
