/** 表格初始数据 - 泉州市丰泽区学校食堂风险报告管理数据 */
export const dataList = () => [
  {
    reportNumber: 'RPT-QZ-FZ-202406-001', // 统一为丰泽FZ编码
    companyName: '泉州市丰泽区第一中学食堂', // 全部改为丰泽区学校
    affiliatedArea: '丰泽区', // 所属区域统一为丰泽区
    affiliatedType: '中学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '高风险',
    monthlyViolationCount: 5,
    violationTypeDistribution: '食品留样:3,人员健康:2',
    rectificationCompletionRate: 80,
    riskLevelBasis: '月度违规频次≥3次且整改完成率<90%',
    lastMonthRiskLevel: '中风险',
    yoyRiskChange: '上升',
    momRiskChange: '上升',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-002',
    companyName: '泉州市丰泽区第二实验小学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '小学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 1,
    violationTypeDistribution: '餐具消毒:1',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次<3次且整改完成率≥90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '持平',
    momRiskChange: '持平',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-003',
    companyName: '泉州市丰泽区实验幼儿园食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '幼儿园食堂',
    statisticsMonth: '2024-06',
    riskLevel: '中风险',
    monthlyViolationCount: 2,
    violationTypeDistribution: '食材储存:1,操作规范:1',
    rectificationCompletionRate: 85,
    riskLevelBasis: '月度违规频次<3次且整改完成率<90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '上升',
    momRiskChange: '上升',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-004',
    companyName: '泉州市丰泽区职业中专学校食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '职校食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 0,
    violationTypeDistribution: '无',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次=0且整改完成率=100%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '持平',
    momRiskChange: '持平',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-005',
    companyName: '泉州市丰泽区华侨中学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '中学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '高风险',
    monthlyViolationCount: 4,
    violationTypeDistribution: '食材采购:2,操作规范:1,卫生管理:1',
    rectificationCompletionRate: 75,
    riskLevelBasis: '月度违规频次≥3次且整改完成率<90%',
    lastMonthRiskLevel: '中风险',
    yoyRiskChange: '上升',
    momRiskChange: '上升',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-006',
    companyName: '泉州市丰泽区第一中心小学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '小学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '中风险',
    monthlyViolationCount: 2,
    violationTypeDistribution: '食材储存:1,卫生管理:1',
    rectificationCompletionRate: 90,
    riskLevelBasis: '月度违规频次<3次且整改完成率≥90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '上升',
    momRiskChange: '持平',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-007',
    companyName: '泉州市丰泽区第三幼儿园食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '幼儿园食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 1,
    violationTypeDistribution: '操作规范:1',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次<3次且整改完成率≥90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '持平',
    momRiskChange: '下降',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-008',
    companyName: '泉州市丰泽区第三中学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '中学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 0,
    violationTypeDistribution: '无',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次=0且整改完成率=100%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '持平',
    momRiskChange: '持平',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-009',
    companyName: '泉州市丰泽区第二实验小学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '小学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '中风险',
    monthlyViolationCount: 2,
    violationTypeDistribution: '食材储存:1,操作规范:1',
    rectificationCompletionRate: 88,
    riskLevelBasis: '月度违规频次<3次且整改完成率<90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '上升',
    momRiskChange: '上升',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-010',
    companyName: '泉州市丰泽区实验幼儿园食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '幼儿园食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 1,
    violationTypeDistribution: '操作规范:1',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次<3次且整改完成率≥90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '下降',
    momRiskChange: '持平',
  },
];


/** 新增/修改的表单/列表的搜索表单 - 企业风险报告管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'reportNumber',
      label: '报告编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入报告编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'companyName',
      label: '企业名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入企业名称',
        maxLength: 100,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'affiliatedArea',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域（如：台江区、思明区）',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '燃气供应', value: '燃气供应' },
          { label: '管道运输', value: '管道运输' },
          { label: '燃气储存', value: '燃气储存' },
          { label: '燃气加气', value: '燃气加气' },
        ],
        placeholder: '请选择所属类型',
        showSearch: true,
      },
      fieldName: 'affiliatedType',
      label: '所属类型',
      rules: 'required',
    },
    {
      fieldName: 'statisticsMonth',
      label: '统计月份',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择统计月份',
        picker: 'month',
        format: 'YYYY-MM',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '高风险', value: '高风险' },
          { label: '中风险', value: '中风险' },
          { label: '低风险', value: '低风险' },
        ],
        placeholder: '请选择风险等级',
        showSearch: true,
      },
      fieldName: 'riskLevel',
      label: '风险等级',
      rules: 'required',
    },
    {
      fieldName: 'monthlyViolationCount',
      label: '月度违规频次',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入月度违规频次',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'violationTypeDistribution',
      label: '违规类型分布',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入违规类型分布（如：设备维护:3,操作规范:2）',
        maxLength: 200,
      },
      rules: 'required',
    },
    {
      fieldName: 'rectificationCompletionRate',
      label: '整改完成率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入整改完成率（单位：%）',
        min: 0,
        max: 100,
        precision: 2,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'riskLevelBasis',
      label: '风险等级判定依据',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入风险等级判定依据',
        maxLength: 200,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '高风险', value: '高风险' },
          { label: '中风险', value: '中风险' },
          { label: '低风险', value: '低风险' },
        ],
        placeholder: '请选择上月风险等级',
        showSearch: true,
      },
      fieldName: 'lastMonthRiskLevel',
      label: '上月风险等级',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '上升', value: '上升' },
          { label: '持平', value: '持平' },
          { label: '下降', value: '下降' },
        ],
        placeholder: '请选择同比风险变化',
        showSearch: true,
      },
      fieldName: 'yoyRiskChange',
      label: '同比风险变化',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '上升', value: '上升' },
          { label: '持平', value: '持平' },
          { label: '下降', value: '下降' },
        ],
        placeholder: '请选择环比风险变化',
        showSearch: true,
      },
      fieldName: 'momRiskChange',
      label: '环比风险变化',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 企业风险报告管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'reportNumber',
      title: '报告编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'reportNumber' },
    },
    {
      field: 'companyName',
      title: '企业名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'companyName' },
    },
    {
      field: 'affiliatedArea',
      title: '所属区域',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'affiliatedType',
      title: '所属类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'statisticsMonth',
      title: '统计月份',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'riskLevel',
      title: '风险等级',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'monthlyViolationCount',
      title: '月度违规频次',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'violationTypeDistribution',
      title: '违规类型分布',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'rectificationCompletionRate',
      title: '整改完成率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'riskLevelBasis',
      title: '风险等级判定依据',
      minWidth: 250,
      sortable: false,
    },
    {
      field: 'lastMonthRiskLevel',
      title: '上月风险等级',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'yoyRiskChange',
      title: '同比风险变化',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'momRiskChange',
      title: '环比风险变化',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
