/** 表格初始数据 - 泉州市丰泽区学校食堂风险报告管理数据 */
export const dataList = () => [
  {
    reportNumber: 'RPT-QZ-FZ-202406-001', // 统一为丰泽FZ编码
    companyName: '泉州市丰泽区第一中学食堂', // 全部改为丰泽区学校
    affiliatedArea: '丰泽区', // 所属区域统一为丰泽区
    affiliatedType: '中学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '高风险',
    monthlyViolationCount: 5,
    violationTypeDistribution: '食品留样:3,人员健康:2',
    rectificationCompletionRate: 80,
    riskLevelBasis: '月度违规频次≥3次且整改完成率<90%',
    lastMonthRiskLevel: '中风险',
    yoyRiskChange: '上升',
    momRiskChange: '上升',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-002',
    companyName: '泉州市丰泽区第二实验小学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '小学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 1,
    violationTypeDistribution: '餐具消毒:1',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次<3次且整改完成率≥90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '持平',
    momRiskChange: '持平',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-003',
    companyName: '泉州市丰泽区实验幼儿园食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '幼儿园食堂',
    statisticsMonth: '2024-06',
    riskLevel: '中风险',
    monthlyViolationCount: 2,
    violationTypeDistribution: '食材储存:1,操作规范:1',
    rectificationCompletionRate: 85,
    riskLevelBasis: '月度违规频次<3次且整改完成率<90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '上升',
    momRiskChange: '上升',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-004',
    companyName: '泉州市丰泽区职业中专学校食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '职校食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 0,
    violationTypeDistribution: '无',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次=0且整改完成率=100%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '持平',
    momRiskChange: '持平',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-005',
    companyName: '泉州市丰泽区华侨中学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '中学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '高风险',
    monthlyViolationCount: 4,
    violationTypeDistribution: '食材采购:2,操作规范:1,卫生管理:1',
    rectificationCompletionRate: 75,
    riskLevelBasis: '月度违规频次≥3次且整改完成率<90%',
    lastMonthRiskLevel: '中风险',
    yoyRiskChange: '上升',
    momRiskChange: '上升',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-006',
    companyName: '泉州市丰泽区第一中心小学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '小学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '中风险',
    monthlyViolationCount: 2,
    violationTypeDistribution: '食材储存:1,卫生管理:1',
    rectificationCompletionRate: 90,
    riskLevelBasis: '月度违规频次<3次且整改完成率≥90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '上升',
    momRiskChange: '持平',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-007',
    companyName: '泉州市丰泽区第三幼儿园食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '幼儿园食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 1,
    violationTypeDistribution: '操作规范:1',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次<3次且整改完成率≥90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '持平',
    momRiskChange: '下降',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-008',
    companyName: '泉州市丰泽区第三中学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '中学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 0,
    violationTypeDistribution: '无',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次=0且整改完成率=100%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '持平',
    momRiskChange: '持平',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-009',
    companyName: '泉州市丰泽区第二实验小学食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '小学食堂',
    statisticsMonth: '2024-06',
    riskLevel: '中风险',
    monthlyViolationCount: 2,
    violationTypeDistribution: '食材储存:1,操作规范:1',
    rectificationCompletionRate: 88,
    riskLevelBasis: '月度违规频次<3次且整改完成率<90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '上升',
    momRiskChange: '上升',
  },
  {
    reportNumber: 'RPT-QZ-FZ-202406-010',
    companyName: '泉州市丰泽区实验幼儿园食堂',
    affiliatedArea: '丰泽区',
    affiliatedType: '幼儿园食堂',
    statisticsMonth: '2024-06',
    riskLevel: '低风险',
    monthlyViolationCount: 1,
    violationTypeDistribution: '操作规范:1',
    rectificationCompletionRate: 100,
    riskLevelBasis: '月度违规频次<3次且整改完成率≥90%',
    lastMonthRiskLevel: '低风险',
    yoyRiskChange: '下降',
    momRiskChange: '持平',
  },
];


/** 新增/修改的表单/列表的搜索表单 - 企业风险报告管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'reportNumber',
      label: '区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'type',
      label: '企业类型',
      component: 'Input',
      componentProps: {
        placeholder: '请输入企业类型',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'time',
      label: '时间配置',
      component: 'Input',
      componentProps: {
        placeholder: '请输入时间配置',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 企业风险报告管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'reportNumber',
      title: '报告编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'reportNumber' },
    },
    {
      field: 'companyName',
      title: '企业名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'companyName' },
    },
    {
      field: 'affiliatedArea',
      title: '所属区域',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'affiliatedType',
      title: '所属类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'statisticsMonth',
      title: '统计月份',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'riskLevel',
      title: '风险等级',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'monthlyViolationCount',
      title: '月度违规频次',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'violationTypeDistribution',
      title: '违规类型分布',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'rectificationCompletionRate',
      title: '整改完成率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'riskLevelBasis',
      title: '风险等级判定依据',
      minWidth: 250,
      sortable: false,
    },
    {
      field: 'lastMonthRiskLevel',
      title: '上月风险等级',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'yoyRiskChange',
      title: '同比风险变化',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'momRiskChange',
      title: '环比风险变化',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
