/** 表格初始数据 - 泉州市丰泽区学校食堂检查台账数据（更新字段版） */
export const dataList = () => [
  {
    ledgerCode: 'ST-QZ-FZ-202406-001', // 台账编码：ST（食堂）-QZ（泉州）-FZ（丰泽）-年月-序号
    enterpriseName: '泉州市丰泽区第一中学食堂', // 全部改为丰泽区学校
    violationType: '未按规范储存食品原料',
    violationLevel: '一般违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/001.pdf', // 增加丰泽区路径标识
    draftTime: '2024-06-01 09:30:25',
    draftPenaltyAmount: 5000,
    reviewStatus: '已复审',
    reviewer: '张明（工号：QZJY-FZ001）', // 工号增加丰泽区FZ标识
    reviewTime: '2024-06-05 14:20:18',
    issueTime: '2024-06-08 10:15:36',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterprisePaymentStatus: '已缴款',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-001', // 总台账增加丰泽FZ标识
  },
  {
    ledgerCode: 'ST-QZ-FZ-202406-002',
    enterpriseName: '泉州市丰泽区第二实验小学食堂',
    violationType: '从业人员健康证过期',
    violationLevel: '严重违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/002.pdf',
    draftTime: '2024-06-02 10:15:42',
    draftPenaltyAmount: 20000,
    reviewStatus: '复审中',
    reviewer: '李丽（工号：QZJY-FZ002）',
    reviewTime: '2024-06-06 09:18:49',
    issueTime: '',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '未送达',
    enterprisePaymentStatus: '未缴款',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-002',
  },
  {
    ledgerCode: 'ST-QZ-FZ-202406-003',
    enterpriseName: '泉州市丰泽区第三幼儿园食堂',
    violationType: '餐具消毒记录不完整',
    violationLevel: '轻微违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/003.pdf',
    draftTime: '2024-06-03 14:20:18',
    draftPenaltyAmount: 1000,
    reviewStatus: '未复审',
    reviewer: '',
    reviewTime: '',
    issueTime: '',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '待送达',
    enterprisePaymentStatus: '待缴款',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-003',
  },
  {
    ledgerCode: 'ST-QZ-FZ-202406-004',
    enterpriseName: '泉州市丰泽区实验中学食堂',
    violationType: '食品留样未按规定执行',
    violationLevel: '一般违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/004.pdf',
    draftTime: '2024-06-04 15:25:36',
    draftPenaltyAmount: 8000,
    reviewStatus: '已复审',
    reviewer: '王强（工号：QZJY-FZ003）',
    reviewTime: '2024-06-07 11:22:05',
    issueTime: '2024-06-09 15:10:08',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterprisePaymentStatus: '部分缴款',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-004',
  },
  {
    ledgerCode: 'ST-QZ-FZ-202406-005',
    enterpriseName: '泉州市丰泽区第一中心小学食堂',
    violationType: '采购过期调味品',
    violationLevel: '严重违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/005.pdf',
    draftTime: '2024-06-05 16:50:08',
    draftPenaltyAmount: 30000,
    reviewStatus: '已撤销',
    reviewer: '陈红（工号：QZJY-FZ004）',
    reviewTime: '2024-06-08 16:05:33',
    issueTime: '2024-06-10 09:32:15',
    revokeTime: '2024-06-12 14:15:20',
    revokeReason: '证据不足，经复核撤销',
    serviceStatus: '已撤回',
    enterprisePaymentStatus: '无需缴款',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-005',
  },
  {
    ledgerCode: 'ST-QZ-FZ-202406-006',
    enterpriseName: '泉州市丰泽区外国语学校食堂',
    violationType: '后厨环境卫生不达标',
    violationLevel: '轻微违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/006.pdf',
    draftTime: '2024-06-06 08:32:15',
    draftPenaltyAmount: 2000,
    reviewStatus: '已复审',
    reviewer: '黄明（工号：QZJY-FZ005）',
    reviewTime: '2024-06-09 10:15:20',
    issueTime: '2024-06-11 11:28:42',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterprisePaymentStatus: '缴款中',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-006',
  },
  {
    ledgerCode: 'ST-QZ-FZ-202406-007',
    enterpriseName: '泉州市丰泽区职业中专学校食堂',
    violationType: '未建立食品采购索证索票制度',
    violationLevel: '一般违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/007.pdf',
    draftTime: '2024-06-07 11:18:49',
    draftPenaltyAmount: 15000,
    reviewStatus: '复审中',
    reviewer: '郑伟（工号：QZJY-FZ006）',
    reviewTime: '',
    issueTime: '',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '待送达',
    enterprisePaymentStatus: '未缴款',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-007',
  },
  {
    ledgerCode: 'ST-QZ-FZ-202406-008',
    enterpriseName: '泉州市丰泽区实验学校食堂',
    violationType: '冷藏设备温度不符合要求',
    violationLevel: '一般违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/008.pdf',
    draftTime: '2024-06-08 13:22:05',
    draftPenaltyAmount: 6000,
    reviewStatus: '已复审',
    reviewer: '吴芳（工号：QZJY-FZ007）',
    reviewTime: '2024-06-10 15:30:25',
    issueTime: '2024-06-12 12:10:18',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterprisePaymentStatus: '已缴款',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-008',
  },
  {
    ledgerCode: 'ST-QZ-FZ-202406-009',
    enterpriseName: '泉州市丰泽区实验幼儿园食堂',
    violationType: '从业人员未按规定穿戴工作衣帽',
    violationLevel: '轻微违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/009.pdf',
    draftTime: '2024-06-09 10:05:33',
    draftPenaltyAmount: 1500,
    reviewStatus: '未复审',
    reviewer: '',
    reviewTime: '',
    issueTime: '',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '未送达',
    enterprisePaymentStatus: '待缴款',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-009',
  },
  {
    ledgerCode: 'ST-QZ-FZ-202406-010',
    enterpriseName: '泉州市丰泽区华侨中学食堂',
    violationType: '使用未检验合格的食品添加剂',
    violationLevel: '严重违规',
    violationEvidenceUrl: 'https://evidence.qzedu.gov.cn/fz/202406/010.pdf',
    draftTime: '2024-06-10 14:15:20',
    draftPenaltyAmount: 50000,
    reviewStatus: '已复审',
    reviewer: '林达（工号：QZJY-FZ008）',
    reviewTime: '2024-06-11 16:25:36',
    issueTime: '2024-06-13 10:50:08',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterprisePaymentStatus: '逾期未缴款',
    lawEnforcementReviewTotalLedgerCode: 'FJEDU-QZ-FZ-2024-Z-010',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 执法复审台账表单（更新字段版） */
export function useFormSchema() {
  return [
    {
      fieldName: 'ledgerCode',
      label: '台账编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入台账编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 台账编号为必填项
    },
    {
      fieldName: 'enterpriseName',
      label: '企业名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入企业名称',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未按规范进行桥梁养护', value: '未按规范进行桥梁养护' },
          { label: '监测数据造假', value: '监测数据造假' },
          { label: '未按时提交养护报告', value: '未按时提交养护报告' },
          { label: '养护设备未定期校准', value: '养护设备未定期校准' },
          { label: '违规占道施工', value: '违规占道施工' },
          { label: '安全警示标识缺失', value: '安全警示标识缺失' },
          { label: '养护人员无证上岗', value: '养护人员无证上岗' },
          { label: '未按要求设置防护措施', value: '未按要求设置防护措施' },
          { label: '养护记录不完整', value: '养护记录不完整' },
          { label: '超限车辆未报备通行', value: '超限车辆未报备通行' },
        ],
        placeholder: '请选择违规类型',
        showSearch: true,
      },
      fieldName: 'violationType',
      label: '违规类型',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '轻微违规', value: '轻微违规' },
          { label: '一般违规', value: '一般违规' },
          { label: '严重违规', value: '严重违规' },
        ],
        placeholder: '请选择违规等级',
        showSearch: true,
      },
      fieldName: 'violationLevel',
      label: '违规等级',
      rules: 'required',
    },
    {
      fieldName: 'violationEvidenceUrl',
      label: '违规证据链接',
      component: 'Input',
      componentProps: {
        placeholder: '请输入违规证据链接',
        maxLength: 200,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'draftTime',
      label: '草拟时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入草拟时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'draftPenaltyAmount',
      label: '草拟处罚金额',
      component: 'InputNumber', // 金额用数字输入框更合适
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入草拟处罚金额（单位：元）',
        min: 0,
        precision: 0, // 处罚金额为整数
        addonAfter: '元',
      },
      rules: 'required', // 草拟处罚金额为必填项
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未复审', value: '未复审' },
          { label: '复审中', value: '复审中' },
          { label: '已复审', value: '已复审' },
          { label: '已撤销', value: '已撤销' },
        ],
        placeholder: '请选择复审状态',
        showSearch: true,
      },
      fieldName: 'reviewStatus',
      label: '复审状态',
      rules: 'required',
    },
    {
      fieldName: 'reviewer',
      label: '复审人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入复审人姓名/工号',
      },
      labelWidth: '120',
      rules: '', // 非必填，复审状态为未复审时可空
    },
    {
      fieldName: 'reviewTime',
      label: '复审时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入复审时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      labelWidth: '120',
      rules: '', // 非必填，复审状态为未复审时可空
    },
    {
      fieldName: 'issueTime',
      label: '下发时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入下发时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      labelWidth: '120',
      rules: '', // 非必填，未下发时可空
    },
    {
      fieldName: 'revokeTime',
      label: '撤销时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入撤销时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      labelWidth: '120',
      rules: '', // 非必填，未撤销时可空
    },
    {
      fieldName: 'revokeReason',
      label: '撤销原因',
      component: 'Input',
      componentProps: {
        placeholder: '请输入撤销原因',
        maxlength: 500,
      },
      labelWidth: '120',
      rules: '', // 非必填，未撤销时可空
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未送达', value: '未送达' },
          { label: '待送达', value: '待送达' },
          { label: '已送达', value: '已送达' },
          { label: '已撤回', value: '已撤回' },
        ],
        placeholder: '请选择送达状态',
        showSearch: true,
      },
      fieldName: 'serviceStatus',
      label: '送达状态',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未缴款', value: '未缴款' },
          { label: '待缴款', value: '待缴款' },
          { label: '缴款中', value: '缴款中' },
          { label: '已缴款', value: '已缴款' },
          { label: '部分缴款', value: '部分缴款' },
          { label: '无需缴款', value: '无需缴款' },
          { label: '逾期未缴款', value: '逾期未缴款' },
        ],
        placeholder: '请选择企业缴款状态',
        showSearch: true,
      },
      fieldName: 'enterprisePaymentStatus',
      label: '企业缴款状态',
      rules: 'required',
    },
    {
      fieldName: 'lawEnforcementReviewTotalLedgerCode',
      label: '执法复审总台账编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入执法复审总台账编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 执法复审台账表格列（更新字段版） */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'ledgerCode',
      title: '台账编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'ledgerCode' },
    },
    {
      field: 'enterpriseName',
      title: '企业名称',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'violationType',
      title: '违规类型',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'violationLevel',
      title: '违规等级',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'violationEvidenceUrl',
      title: '违规证据链接',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'draftTime',
      title: '草拟时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'draftPenaltyAmount',
      title: '草拟处罚金额(元)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'reviewStatus',
      title: '复审状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'reviewer',
      title: '复审人',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'reviewTime',
      title: '复审时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'issueTime',
      title: '下发时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'revokeTime',
      title: '撤销时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'revokeReason',
      title: '撤销原因',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'serviceStatus',
      title: '送达状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'enterprisePaymentStatus',
      title: '企业缴款状态',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'lawEnforcementReviewTotalLedgerCode',
      title: '执法复审总台账编号',
      minWidth: 220,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}