// data.js
/** 逃费数据报表 - 初始数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "escapeId": "ESCAPE-20260205001",
      "carNumber": "粤A12345",
      "areaCode": "440106",
      "areaName": "天河区",
      "lotId": "LOT001",
      "lotName": "天河城停车场",
      "escapeTime": "2026-02-05 08:15",
      "escapeAmount": 125.50,
      "escapeLevel": "一级逃费",
      "traceStatus": "待追缴",
      "lastTraceTime": "2026-02-05 09:30",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 2,
      "escapeId": "ESCAPE-20260205002",
      "carNumber": "粤B67890",
      "areaCode": "440104",
      "areaName": "越秀区",
      "lotId": "LOT002",
      "lotName": "北京路路侧停车",
      "escapeTime": "2026-02-05 14:20",
      "escapeAmount": 85.00,
      "escapeLevel": "二级逃费",
      "traceStatus": "追缴中",
      "lastTraceTime": "2026-02-05 16:45",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 3,
      "escapeId": "ESCAPE-20260205003",
      "carNumber": "粤C34567",
      "areaCode": "440105",
      "areaName": "海珠区",
      "lotId": "LOT003",
      "lotName": "万达广场停车场",
      "escapeTime": "2026-02-05 19:05",
      "escapeAmount": 150.00,
      "escapeLevel": "三级逃费",
      "traceStatus": "已追缴",
      "lastTraceTime": "2026-02-05 20:15",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 4,
      "escapeId": "ESCAPE-20260204001",
      "carNumber": "粤D78901",
      "areaCode": "440111",
      "areaName": "白云区",
      "lotId": "LOT004",
      "lotName": "白云小区停车场",
      "escapeTime": "2026-02-04 10:30",
      "escapeAmount": 65.00,
      "escapeLevel": "一级逃费",
      "traceStatus": "待追缴",
      "lastTraceTime": "2026-02-04 11:20",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 5,
      "escapeId": "ESCAPE-20260204002",
      "carNumber": "粤E23456",
      "areaCode": "440112",
      "areaName": "黄埔区",
      "lotId": "LOT005",
      "lotName": "黄埔商业中心停车场",
      "escapeTime": "2026-02-04 16:45",
      "escapeAmount": 95.50,
      "escapeLevel": "二级逃费",
      "traceStatus": "追缴中",
      "lastTraceTime": "2026-02-04 17:30",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 6,
      "escapeId": "ESCAPE-20260203001",
      "carNumber": "粤F56789",
      "areaCode": "440106",
      "areaName": "天河区",
      "lotId": "LOT006",
      "lotName": "体育中心停车场",
      "escapeTime": "2026-02-03 09:15",
      "escapeAmount": 110.00,
      "escapeLevel": "一级逃费",
      "traceStatus": "已追缴",
      "lastTraceTime": "2026-02-03 10:45",
      "updateTime": "2026-02-03 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 7,
      "escapeId": "ESCAPE-20260202001",
      "carNumber": "粤G01234",
      "areaCode": "440103",
      "areaName": "荔湾区",
      "lotId": "LOT007",
      "lotName": "上下九路侧停车",
      "escapeTime": "2026-02-02 13:20",
      "escapeAmount": 75.00,
      "escapeLevel": "二级逃费",
      "traceStatus": "追缴中",
      "lastTraceTime": "2026-02-02 14:30",
      "updateTime": "2026-02-02 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 8,
      "escapeId": "ESCAPE-20260201001",
      "carNumber": "粤H56789",
      "areaCode": "440113",
      "areaName": "番禺区",
      "lotId": "LOT008",
      "lotName": "长隆景区停车场",
      "escapeTime": "2026-02-01 18:30",
      "escapeAmount": 200.00,
      "escapeLevel": "三级逃费",
      "traceStatus": "待追缴",
      "lastTraceTime": "2026-02-01 19:15",
      "updateTime": "2026-02-01 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 9,
      "escapeId": "ESCAPE-20260131001",
      "carNumber": "粤J12345",
      "areaCode": "440106",
      "areaName": "天河区",
      "lotId": "LOT001",
      "lotName": "天河城停车场",
      "escapeTime": "2026-01-31 11:45",
      "escapeAmount": 90.00,
      "escapeLevel": "一级逃费",
      "traceStatus": "已追缴",
      "lastTraceTime": "2026-01-31 13:20",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 10,
      "escapeId": "ESCAPE-20260130001",
      "carNumber": "粤K67890",
      "areaCode": "440105",
      "areaName": "海珠区",
      "lotId": "LOT003",
      "lotName": "万达广场停车场",
      "escapeTime": "2026-01-30 15:30",
      "escapeAmount": 120.00,
      "escapeLevel": "二级逃费",
      "traceStatus": "追缴中",
      "lastTraceTime": "2026-01-30 16:45",
      "updateTime": "2026-01-30 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 11,
      "escapeId": "ESCAPE-20260129001",
      "carNumber": "粤L34567",
      "areaCode": "440104",
      "areaName": "越秀区",
      "lotId": "LOT002",
      "lotName": "北京路路侧停车",
      "escapeTime": "2026-01-29 20:15",
      "escapeAmount": 180.50,
      "escapeLevel": "三级逃费",
      "traceStatus": "待追缴",
      "lastTraceTime": "2026-01-29 21:30",
      "updateTime": "2026-01-29 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 12,
      "escapeId": "ESCAPE-20260128001",
      "carNumber": "粤M78901",
      "areaCode": "440111",
      "areaName": "白云区",
      "lotId": "LOT004",
      "lotName": "白云小区停车场",
      "escapeTime": "2026-01-28 09:45",
      "escapeAmount": 70.00,
      "escapeLevel": "一级逃费",
      "traceStatus": "已追缴",
      "lastTraceTime": "2026-01-28 11:15",
      "updateTime": "2026-01-28 18:30",
      "operator": "系统自动生成"
    }
  ];
};

/** 搜索表单配置 */
export function useFormSchema() {
  return [
    {
      fieldName: 'carNumber',
      label: '车牌号码',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入车牌号码（支持模糊查询）',
        clearable: true,
      },
    },
    {
      fieldName: 'timeRange',
      label: '时间范围',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'daterange',
        'range-separator': '至',
        'start-placeholder': '开始日期',
        'end-placeholder': '结束日期',
        format: 'YYYY-MM-DD',
        'value-format': 'YYYY-MM-DD',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
      },
      fieldName: 'areaName',
      label: '行政区域',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河城停车场', value: 'LOT001' },
          { label: '北京路路侧停车', value: 'LOT002' },
          { label: '万达广场停车场', value: 'LOT003' },
          { label: '白云小区停车场', value: 'LOT004' },
          { label: '黄埔商业中心停车场', value: 'LOT005' },
          { label: '体育中心停车场', value: 'LOT006' },
          { label: '上下九路侧停车', value: 'LOT007' },
          { label: '长隆景区停车场', value: 'LOT008' },
        ],
        placeholder: '请选择车场',
        showSearch: true,
      },
      fieldName: 'lotId',
      label: '车场选择',
    },
    {
      fieldName: 'escapeLevel',
      label: '逃费等级',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        options: [
          { label: '一级逃费', value: '一级逃费' },
          { label: '二级逃费', value: '二级逃费' },
          { label: '三级逃费', value: '三级逃费' },
        ],
        placeholder: '请选择逃费等级',
      },
    },
    {
      fieldName: 'traceStatus',
      label: '追缴状态',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        options: [
          { label: '待追缴', value: '待追缴' },
          { label: '追缴中', value: '追缴中' },
          { label: '已追缴', value: '已追缴' },
        ],
        placeholder: '请选择追缴状态',
      },
    },
  ];
}

/** 表格字段配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'escapeId',
      title: '逃费ID',
      minWidth: 150,
      sortable: true,
      slots: { default: 'escapeId' },
    },
    {
      field: 'carNumber',
      title: '车牌号码',
      minWidth: 120,
      sortable: true,
      slots: { default: 'carNumber' },
    },
    {
      field: 'areaName',
      title: '行政区域',
      minWidth: 100,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'lotName',
      title: '车场名称',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'escapeTime',
      title: '逃费时间',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'escapeAmount',
      title: '逃费金额',
      minWidth: 120,
      sortable: true,
      slots: { default: 'escapeAmount' },
    },
    {
      field: 'escapeLevel',
      title: '逃费等级',
      minWidth: 120,
      sortable: true,
      slots: { default: 'escapeLevel' },
    },
    {
      field: 'traceStatus',
      title: '追缴状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'traceStatus' },
    },
    {
      field: 'lastTraceTime',
      title: '上次追缴时间',
      minWidth: 150,
      sortable: true,
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑逃费记录',
  addText: '新增逃费记录',
  excelName: '逃费数据报表',
  excelAllName: '逃费数据报表.xlsx',
  total: '报表总数: 12; 今日逃费: 3; 本周逃费: 8;',
};
