// data.js
/** 表格初始数据 - 任务数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "taskName": "服务器巡检任务-01",
      "taskType": "巡检任务",
      "assigner": "张三",
      "assignTime": "2026-01-20 09:30",
      "deadline": "2026-01-23 18:00",
      "priority": "高",
      "description": "对机房服务器进行定期巡检，检查硬件状态、系统日志...",
      "taskId": "TASK-20260120-001",
      "receiveStatus": "已认领",
      "relatedResource": "服务器集群-A",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-20 09:00",
      "operationLog": "任务创建"
    },
    {
      "id": 2,
      "taskName": "数据库性能优化",
      "taskType": "项目任务",
      "assigner": "王五",
      "assignTime": "2026-01-21 14:00",
      "deadline": "2026-01-25 17:00",
      "priority": "中",
      "description": "对生产数据库进行性能优化，包括索引优化、查询调优等",
      "taskId": "TASK-20260121-002",
      "receiveStatus": "未认领",
      "relatedResource": "MySQL数据库-01",
      "currentProgress": "50%",
      "startTime": "2026-01-21 15:00",
      "expectedFinishTime": "2026-01-24 18:00",
      "updateTime": "2026-01-22 10:30",
      "delayStatus": "正常",
      "cooperators": "赵六,钱七",
      "finishTime": "",
      "acceptResult": "",
      "executor": "李四",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-21 13:30",
      "operationLog": "任务认领"
    },
    {
      "id": 3,
      "taskName": "网络设备配置备份",
      "taskType": "日常运维",
      "assigner": "孙八",
      "assignTime": "2026-01-19 10:00",
      "deadline": "2026-01-22 12:00",
      "priority": "低",
      "description": "备份所有网络设备的配置文件",
      "taskId": "TASK-20260119-003",
      "receiveStatus": "已认领",
      "relatedResource": "核心交换机",
      "currentProgress": "100%",
      "startTime": "2026-01-19 11:00",
      "expectedFinishTime": "2026-01-22 10:00",
      "updateTime": "2026-01-22 09:45",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-22 09:45",
      "acceptResult": "通过",
      "executor": "李四",
      "attachment": "backup_config.zip",
      "executionDuration": "3天",
      "archiveTime": "2026-01-22 10:00",
      "acceptOpinion": "备份完整，符合要求",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-19 09:30",
      "operationLog": "任务完成"
    },
    {
      "id": 4,
      "taskName": "应用系统部署",
      "taskType": "项目任务",
      "assigner": "李四",
      "assignTime": "2026-01-18 13:00",
      "deadline": "2026-01-24 20:00",
      "priority": "高",
      "description": "部署新版应用系统到生产环境",
      "taskId": "TASK-20260118-004",
      "receiveStatus": "已认领",
      "relatedResource": "应用服务器集群",
      "currentProgress": "80%",
      "startTime": "2026-01-18 14:00",
      "expectedFinishTime": "2026-01-23 18:00",
      "updateTime": "2026-01-22 16:30",
      "delayStatus": "申请中",
      "cooperators": "周五,吴九",
      "finishTime": "",
      "acceptResult": "",
      "executor": "王五",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "王五",
      "createTime": "2026-01-18 12:30",
      "operationLog": "进度更新"
    },
    {
      "id": 5,
      "taskName": "安全漏洞修复",
      "taskType": "故障处理",
      "assigner": "郑十",
      "assignTime": "2026-01-22 08:30",
      "deadline": "2026-01-23 12:00",
      "priority": "紧急",
      "description": "修复发现的高危安全漏洞",
      "taskId": "TASK-20260122-005",
      "receiveStatus": "未认领",
      "relatedResource": "Web服务器",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-01-22 08:00",
      "operationLog": "任务创建"
    },
    {
      "id": 6,
      "taskName": "月度工作报告撰写",
      "taskType": "日常运维",
      "assigner": "李四",
      "assignTime": "",
      "deadline": "2026-01-25 17:00",
      "priority": "中",
      "description": "撰写1月份IT运维工作报告",
      "taskId": "TASK-20260115-006",
      "receiveStatus": "已认领",
      "relatedResource": "文档管理系统",
      "currentProgress": "30%",
      "startTime": "2026-01-20 09:00",
      "expectedFinishTime": "2026-01-24 18:00",
      "updateTime": "2026-01-22 14:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "李四",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "李四",
      "remindCount": 1,
      "latestDynamic": "进度更新至30%",
      "operator": "李四",
      "createTime": "2026-01-15 10:00",
      "operationLog": "任务发起"
    },
    {
      "id": 7,
      "taskName": "备份系统验证测试",
      "taskType": "巡检任务",
      "assigner": "周三",
      "assignTime": "2026-01-17 11:00",
      "deadline": "2026-01-20 17:00",
      "priority": "中",
      "description": "对备份系统进行恢复验证测试",
      "taskId": "TASK-20260117-007",
      "receiveStatus": "已认领",
      "relatedResource": "备份服务器",
      "currentProgress": "100%",
      "startTime": "2026-01-17 13:00",
      "expectedFinishTime": "2026-01-20 16:00",
      "updateTime": "2026-01-20 15:30",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-20 15:30",
      "acceptResult": "通过",
      "executor": "李四",
      "attachment": "test_report.pdf",
      "executionDuration": "3天",
      "archiveTime": "2026-01-20 16:00",
      "acceptOpinion": "测试通过，恢复功能正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-17 10:30",
      "operationLog": "任务完成"
    },
    {
      "id": 8,
      "taskName": "会议室设备调试",
      "taskType": "日常运维",
      "assigner": "赵六",
      "assignTime": "2026-01-22 09:00",
      "deadline": "2026-01-22 12:00",
      "priority": "低",
      "description": "调试301会议室的音视频设备",
      "taskId": "TASK-20260122-008",
      "receiveStatus": "已认领",
      "relatedResource": "301会议室",
      "currentProgress": "100%",
      "startTime": "2026-01-22 09:30",
      "expectedFinishTime": "2026-01-22 11:30",
      "updateTime": "2026-01-22 11:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-22 11:00",
      "acceptResult": "通过",
      "executor": "李四",
      "attachment": "",
      "executionDuration": "1.5小时",
      "archiveTime": "2026-01-22 11:30",
      "acceptOpinion": "调试完成，设备正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-22 08:45",
      "operationLog": "任务完成"
    }
  ];
};

/** 新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'taskName',
      label: '任务名称',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入任务名称',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '日常运维', value: '日常运维' },
          { label: '故障处理', value: '故障处理' },
          { label: '项目任务', value: '项目任务' },
          { label: '巡检任务', value: '巡检任务' },
          { label: '其他', value: '其他' },
        ],
        placeholder: '请选择任务类型',
        showSearch: true,
      },
      fieldName: 'taskType',
      label: '任务类型',
    },
    {
      fieldName: 'priority',
      label: '优先级',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '紧急', value: '紧急' },
          { label: '高', value: '高' },
          { label: '中', value: '中' },
          { label: '低', value: '低' },
        ],
        placeholder: '请选择优先级',
      },
      rules: 'required',
    },
    {
      fieldName: 'deadline',
      label: '截止时间',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'datetime',
        placeholder: '请选择截止时间',
      },
      rules: 'required',
    },
    {
      fieldName: 'description',
      label: '任务描述',
      component: 'Textarea',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入任务描述',
        rows: 3,
      },
    },
    {
      fieldName: 'assigner',
      label: '分配人',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入分配人',
      },
    },
    {
      fieldName: 'relatedResource',
      label: '关联资源',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入关联资源',
      },
    },
    {
      fieldName: 'taskStatus',
      label: '任务状态',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '待处理', value: '待处理' },
          { label: '处理中', value: '处理中' },
          { label: '已完成', value: '已完成' },
          { label: '已撤回', value: '已撤回' },
        ],
        placeholder: '请选择任务状态',
      },
    },
  ];
}

/** 表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'taskName',
      title: '任务名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'taskName' },
    },
    {
      field: 'taskType',
      title: '任务类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'priority',
      title: '优先级',
      minWidth: 80,
      sortable: true,
      slots: { default: 'priority' },
    },
    {
      field: 'assigner',
      title: '分配人',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'deadline',
      title: '截止时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'taskStatus',
      title: '任务状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'taskStatus' },
    },
    {
      field: 'currentProgress',
      title: '当前进度',
      minWidth: 100,
      sortable: true,
      slots: { default: 'progress' },
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑任务',
  addText: '新增任务',
  excelName: '任务列表',
  excelAllName: '任务数据.xlsx',
  total: '任务总数: 80; 待处理: 15; 处理中: 23; 已完成: 42',
};
