/** 表格初始数据 - 开闸补录记录 */
export const dataList = () => {
  return [
    {
      id: '2', // 开闸ID
      openGatePosition: '龙文区碧湖公园停车场入口1号道闸', // 开闸位置
      openGateReason: '道闸系统故障，手动开闸放行', // 开闸原因
      emergencyLevel: '一般', // 紧急程度
      applicant: '张三', // 申请人
      phone: '123456789', // 联系电话
      openGateTime: '2026-01-20 08:15:30', // 开闸时间
      supplementStatus: '已补录', // 补录状态
      approvalResult: '审批通过', // 审批结果
      syncGovStatus: '已同步', // 同步政务系统状态
      supplementPerson: '李四', // 补录人
    },
    {
      id: '3',
      openGatePosition: '龙海区石码镇便民停车场出口道闸',
      openGateReason: '车辆缴费系统异常，手动开闸',
      emergencyLevel: '紧急',
      applicant: '李四',
      phone: '13959678987',
      openGateTime: '2026-01-20 09:20:15',
      supplementStatus: '待补录',
      approvalResult: '待审批',
      syncGovStatus: '未同步',
      supplementPerson: '',
    },
    {
      id: '4',
      openGatePosition: '龙海区闽齐社区停车场入口道闸',
      openGateReason: '特殊车辆（消防车）通行，紧急开闸',
      emergencyLevel: '特急',
      applicant: '王五',
      phone: '15399916161',
      openGateTime: '2026-01-20 10:05:40',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '赵六',
    },
    {
      id: '5',
      openGatePosition: '芗城区江滨路生态停车场出口2号道闸',
      openGateReason: '道闸断电，手动开闸放行',
      emergencyLevel: '紧急',
      applicant: '赵六',
      phone: '8888888',
      openGateTime: '2026-01-20 11:10:25',
      supplementStatus: '补录中',
      approvalResult: '审批中',
      syncGovStatus: '同步中',
      supplementPerson: '孙七',
    },
    {
      id: '6',
      openGatePosition: '龙文区万达商圈停车场入口道闸',
      openGateReason: 'VIP车辆通行，手动开闸',
      emergencyLevel: '一般',
      applicant: '孙七',
      phone: '15860234567',
      openGateTime: '2026-01-20 14:30:10',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '周八',
    },
    {
      id: '7',
      openGatePosition: '长泰区武安镇公共停车场出口道闸',
      openGateReason: '道闸卡机，手动开闸放行',
      emergencyLevel: '紧急',
      applicant: '周八',
      phone: '13706987654',
      openGateTime: '2026-01-20 15:45:05',
      supplementStatus: '待补录',
      approvalResult: '审批驳回',
      syncGovStatus: '未同步',
      supplementPerson: '',
    },
    {
      id: '8',
      openGatePosition: '漳浦县绥安镇便民停车场入口道闸',
      openGateReason: '暴雨导致道闸故障，手动开闸',
      emergencyLevel: '特急',
      applicant: '吴九',
      phone: '13695901234',
      openGateTime: '2026-01-20 16:20:30',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '郑十',
    },
    {
      id: '9',
      openGatePosition: '芗城区巷口街道停车场出口道闸',
      openGateReason: '车辆故障，手动开闸移出',
      emergencyLevel: '一般',
      applicant: '郑十',
      phone: '18960012345',
      openGateTime: '2026-01-20 17:15:15',
      supplementStatus: '补录中',
      approvalResult: '审批中',
      syncGovStatus: '同步失败',
      supplementPerson: '张三',
    },
    {
      id: '10',
      openGatePosition: '龙文区蓝田街道停车场入口道闸',
      openGateReason: '系统升级，手动开闸放行',
      emergencyLevel: '紧急',
      applicant: '张三',
      phone: '15980567890',
      openGateTime: '2026-01-20 18:00:40',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '李四',
    },
    {
      id: '11',
      openGatePosition: '龙文区步文街道停车场出口道闸',
      openGateReason: '救护车通行，紧急开闸',
      emergencyLevel: '特急',
      applicant: '李四',
      phone: '13859987654',
      openGateTime: '2026-01-20 19:30:25',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '王五',
    },
    {
      id: '12',
      openGatePosition: '芗城区东铺头街道停车场入口道闸',
      openGateReason: '道闸传感器故障，手动开闸',
      emergencyLevel: '一般',
      applicant: '王五',
      phone: '18960098765',
      openGateTime: '2026-01-20 20:10:10',
      supplementStatus: '待补录',
      approvalResult: '待审批',
      syncGovStatus: '未同步',
      supplementPerson: '',
    },
    {
      id: '13',
      openGatePosition: '芗城区西桥街道停车场出口道闸',
      openGateReason: '内部车辆通行，手动开闸',
      emergencyLevel: '一般',
      applicant: '赵六',
      phone: '15060543210',
      openGateTime: '2026-01-20 21:05:35',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '孙七',
    },
    {
      id: '14',
      openGatePosition: '龙海区石码街道停车场入口道闸',
      openGateReason: '施工车辆通行，手动开闸',
      emergencyLevel: '紧急',
      applicant: '孙七',
      phone: '13599567890',
      openGateTime: '2026-01-21 07:30:20',
      supplementStatus: '补录中',
      approvalResult: '审批中',
      syncGovStatus: '同步中',
      supplementPerson: '周八',
    },
    {
      id: '15',
      openGatePosition: '长泰区武安镇停车场出口道闸',
      openGateReason: '道闸遥控器损坏，手动开闸',
      emergencyLevel: '一般',
      applicant: '周八',
      phone: '17759687654',
      openGateTime: '2026-01-21 08:15:05',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '吴九',
    },
    {
      id: '16',
      openGatePosition: '漳浦县绥安镇停车场入口道闸',
      openGateReason: '收费系统卡顿，手动开闸',
      emergencyLevel: '紧急',
      applicant: '吴九',
      phone: '18659678901',
      openGateTime: '2026-01-21 09:20:40',
      supplementStatus: '待补录',
      approvalResult: '审批驳回',
      syncGovStatus: '同步失败',
      supplementPerson: '',
    },
    {
      id: '17',
      openGatePosition: '云霄县云陵镇停车场出口道闸',
      openGateReason: '内部员工车辆，手动开闸',
      emergencyLevel: '一般',
      applicant: '郑十',
      phone: '13960087654',
      openGateTime: '2026-01-21 10:05:15',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '张三',
    },
    {
      id: '18',
      openGatePosition: '诏安县南诏镇停车场入口道闸',
      openGateReason: '道闸线路故障，手动开闸放行',
      emergencyLevel: '特急',
      applicant: '张三',
      phone: '15280678901',
      openGateTime: '2026-01-21 11:10:30',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '李四',
    },
    {
      id: '19',
      openGatePosition: '平和县小溪镇停车场出口道闸',
      openGateReason: '车辆爆胎，手动开闸移出',
      emergencyLevel: '紧急',
      applicant: '李四',
      phone: '13695987654',
      openGateTime: '2026-01-21 14:30:05',
      supplementStatus: '补录中',
      approvalResult: '审批中',
      syncGovStatus: '未同步',
      supplementPerson: '王五',
    },
    {
      id: '24',
      openGatePosition: '龙文区蓝田街道停车场出口2号道闸',
      openGateReason: '系统卡顿，手动开闸放行',
      emergencyLevel: '一般',
      applicant: '王五',
      phone: '15980567890',
      openGateTime: '2026-01-21 15:45:20',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '赵六',
    },
    {
      id: '25',
      openGatePosition: '龙文区蓝田街道停车场入口2号道闸',
      openGateReason: '特殊车辆（警车）通行，紧急开闸',
      emergencyLevel: '特急',
      applicant: '赵六',
      phone: '15980567890',
      openGateTime: '2026-01-21 16:20:45',
      supplementStatus: '已补录',
      approvalResult: '审批通过',
      syncGovStatus: '已同步',
      supplementPerson: '孙七',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 - 开闸补录 */
export function useFormSchema() {
  return [
    {
      fieldName: 'id',
      label: '开闸ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入开闸ID',
      },
      labelWidth: '100',
      rules: 'required',
    },
    {
      fieldName: 'openGatePosition',
      label: '开闸位置',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入开闸位置（如：XX停车场入口1号道闸）',
      },
      rules: 'required',
    },
    {
      fieldName: 'openGateReason',
      label: '开闸原因',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        type: 'textarea',
        rows: 3,
        placeholder: '请输入开闸原因',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '一般', value: '一般' },
          { label: '紧急', value: '紧急' },
          { label: '特急', value: '特急' },
        ],
        placeholder: '请选择紧急程度',
        showSearch: true,
      },
      defaultValue: '一般',
      fieldName: 'emergencyLevel',
      label: '紧急程度',
      rules: 'required',
    },
    {
      fieldName: 'applicant',
      label: '申请人',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入申请人姓名',
      },
      rules: 'required',
    },
    {
      fieldName: 'phone',
      label: '联系电话',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入联系电话',
      },
      rules: 'required',
    },
    {
      fieldName: 'openGateTime',
      label: '开闸时间',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        type: 'datetime-local',
        placeholder: '请选择开闸时间',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '待补录', value: '待补录' },
          { label: '补录中', value: '补录中' },
          { label: '已补录', value: '已补录' },
        ],
        placeholder: '请选择补录状态',
        showSearch: true,
      },
      defaultValue: '待补录',
      fieldName: 'supplementStatus',
      label: '补录状态',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '待审批', value: '待审批' },
          { label: '审批中', value: '审批中' },
          { label: '审批通过', value: '审批通过' },
          { label: '审批驳回', value: '审批驳回' },
        ],
        placeholder: '请选择审批结果',
        showSearch: true,
      },
      defaultValue: '待审批',
      fieldName: 'approvalResult',
      label: '审批结果',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未同步', value: '未同步' },
          { label: '同步中', value: '同步中' },
          { label: '已同步', value: '已同步' },
          { label: '同步失败', value: '同步失败' },
        ],
        placeholder: '请选择同步政务系统状态',
        showSearch: true,
      },
      defaultValue: '未同步',
      fieldName: 'syncGovStatus',
      label: '同步政务系统状态',
    },
    {
      fieldName: 'supplementPerson',
      label: '补录人',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入补录人姓名',
      },
    },
  ];
}

/** 表格字段 - 开闸补录 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: '开闸ID',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'openGatePosition',
      title: '开闸位置',
      minWidth: 200,
      sortable: true,
      slots: { default: 'openGatePosition' },
    },
    {
      field: 'openGateReason',
      title: '开闸原因',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'emergencyLevel',
      title: '紧急程度',
      minWidth: 100,
      sortable: true, 
    },
    {
      field: 'applicant',
      title: '申请人',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'phone',
      title: '联系电话',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'openGateTime',
      title: '开闸时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'supplementStatus',
      title: '补录状态',
      minWidth: 100,
      sortable: true, 
    },
    {
      field: 'approvalResult',
      title: '审批结果',
      minWidth: 100,
      sortable: true, 
    },
    {
      field: 'syncGovStatus',
      title: '同步政务系统状态',
      minWidth: 150,
      sortable: true, 
    },
    {
      field: 'supplementPerson',
      title: '补录人',
      minWidth: 100,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 - 开闸补录 */
export const textObj = {
  editText: '编辑开闸记录',
  addText: '新增开闸记录',
  excelName: '开闸补录列表',
  excelAllName: '全市开闸补录数据.xlsx',
  total: '开闸记录数量20;待补录5;已审批15',
};