/** 表格初始数据 - 改造为停车管理半年统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    halfYearIllegalParkingDisposal: 3245,
    halfYearPublicParkingConstruction: 12,
    halfYearNewBerths: 850,
    halfYearSmartParkingTransactions: 156800,
    halfYearParkingServiceSatisfaction: 92.5,
    yoyChangeRate_IllegalParkingDisposal: -5.2,
    yoyChangeRate_PublicParkingConstruction: 8.3,
    yoyChangeRate_NewBerths: 12.5,
    yoyChangeRate_SmartParkingTransactions: 23.7,
    yoyChangeRate_ServiceSatisfaction: 2.1,
    detailByRegion: '鼓楼区: 3245件；台江区: 2890件；仓山区: 3120件',
    detailByParkingConstructionType: '平面停车场: 5个；立体停车场: 4个；地下停车场: 3个',
    detailByBerthType: '路内泊位: 420个；路外泊位: 310个；专用泊位: 120个',
    detailBySatisfactionDimension: '环境卫生: 91.2%；设施完善: 93.5%；收费合理: 90.8%；服务态度: 94.5%',
    detailByAnalysis: '同比: 处置量下降5.2%，泊位新增增长12.5%，平台交易额增长23.7%',
  },
  {
    areaName: '台江区',
    halfYearIllegalParkingDisposal: 2890,
    halfYearPublicParkingConstruction: 9,
    halfYearNewBerths: 620,
    halfYearSmartParkingTransactions: 124500,
    halfYearParkingServiceSatisfaction: 91.8,
    yoyChangeRate_IllegalParkingDisposal: -3.8,
    yoyChangeRate_PublicParkingConstruction: 5.6,
    yoyChangeRate_NewBerths: 9.8,
    yoyChangeRate_SmartParkingTransactions: 18.9,
    yoyChangeRate_ServiceSatisfaction: 1.5,
    detailByRegion: '台江区: 2890件；仓山区: 3120件；晋安区: 2450件',
    detailByParkingConstructionType: '平面停车场: 4个；立体停车场: 3个；地下停车场: 2个',
    detailByBerthType: '路内泊位: 310个；路外泊位: 220个；专用泊位: 90个',
    detailBySatisfactionDimension: '环境卫生: 90.5%；设施完善: 92.3%；收费合理: 90.1%；服务态度: 93.2%',
    detailByAnalysis: '同比: 处置量下降3.8%，智慧平台交易增长18.9%，满意度提升1.5%',
  },
  {
    areaName: '仓山区',
    halfYearIllegalParkingDisposal: 3120,
    halfYearPublicParkingConstruction: 11,
    halfYearNewBerths: 780,
    halfYearSmartParkingTransactions: 142300,
    halfYearParkingServiceSatisfaction: 93.2,
    yoyChangeRate_IllegalParkingDisposal: -4.5,
    yoyChangeRate_PublicParkingConstruction: 10.2,
    yoyChangeRate_NewBerths: 14.3,
    yoyChangeRate_SmartParkingTransactions: 21.5,
    yoyChangeRate_ServiceSatisfaction: 2.8,
    detailByRegion: '仓山区: 3120件；晋安区: 2450件；马尾区: 1650件',
    detailByParkingConstructionType: '平面停车场: 5个；立体停车场: 4个；地下停车场: 2个',
    detailByBerthType: '路内泊位: 390个；路外泊位: 280个；专用泊位: 110个',
    detailBySatisfactionDimension: '环境卫生: 92.8%；设施完善: 94.1%；收费合理: 91.5%；服务态度: 94.3%',
    detailByAnalysis: '同比: 停车场建设增长10.2%，泊位新增14.3%，满意度达93.2%',
  },
  {
    areaName: '晋安区',
    halfYearIllegalParkingDisposal: 2450,
    halfYearPublicParkingConstruction: 8,
    halfYearNewBerths: 540,
    halfYearSmartParkingTransactions: 98700,
    halfYearParkingServiceSatisfaction: 90.5,
    yoyChangeRate_IllegalParkingDisposal: -2.7,
    yoyChangeRate_PublicParkingConstruction: 4.5,
    yoyChangeRate_NewBerths: 7.6,
    yoyChangeRate_SmartParkingTransactions: 15.2,
    yoyChangeRate_ServiceSatisfaction: 0.9,
    detailByRegion: '晋安区: 2450件；马尾区: 1650件；长乐区: 1120件',
    detailByParkingConstructionType: '平面停车场: 4个；立体停车场: 2个；地下停车场: 2个',
    detailByBerthType: '路内泊位: 280个；路外泊位: 180个；专用泊位: 80个',
    detailBySatisfactionDimension: '环境卫生: 89.8%；设施完善: 91.2%；收费合理: 89.5%；服务态度: 91.5%',
    detailByAnalysis: '同比: 处置量下降2.7%，平台交易增长15.2%，满意度略有提升',
  },
  {
    areaName: '马尾区',
    halfYearIllegalParkingDisposal: 1650,
    halfYearPublicParkingConstruction: 6,
    halfYearNewBerths: 380,
    halfYearSmartParkingTransactions: 65400,
    halfYearParkingServiceSatisfaction: 89.8,
    yoyChangeRate_IllegalParkingDisposal: 3.2,
    yoyChangeRate_PublicParkingConstruction: 7.8,
    yoyChangeRate_NewBerths: 11.2,
    yoyChangeRate_SmartParkingTransactions: 19.8,
    yoyChangeRate_ServiceSatisfaction: 1.2,
    detailByRegion: '马尾区: 1650件；长乐区: 1120件；福清市: 980件',
    detailByParkingConstructionType: '平面停车场: 3个；立体停车场: 2个；地下停车场: 1个',
    detailByBerthType: '路内泊位: 190个；路外泊位: 130个；专用泊位: 60个',
    detailBySatisfactionDimension: '环境卫生: 89.2%；设施完善: 90.5%；收费合理: 88.7%；服务态度: 90.8%',
    detailByAnalysis: '同比: 处置量上升3.2%，平台交易增长19.8%，满意度89.8%',
  },
  {
    areaName: '长乐区',
    halfYearIllegalParkingDisposal: 1120,
    halfYearPublicParkingConstruction: 5,
    halfYearNewBerths: 290,
    halfYearSmartParkingTransactions: 42300,
    halfYearParkingServiceSatisfaction: 88.6,
    yoyChangeRate_IllegalParkingDisposal: 2.5,
    yoyChangeRate_PublicParkingConstruction: 6.3,
    yoyChangeRate_NewBerths: 9.5,
    yoyChangeRate_SmartParkingTransactions: 16.7,
    yoyChangeRate_ServiceSatisfaction: 0.8,
    detailByRegion: '长乐区: 1120件；福清市: 980件；连江县: 760件',
    detailByParkingConstructionType: '平面停车场: 2个；立体停车场: 2个；地下停车场: 1个',
    detailByBerthType: '路内泊位: 150个；路外泊位: 100个；专用泊位: 40个',
    detailBySatisfactionDimension: '环境卫生: 88.1%；设施完善: 89.3%；收费合理: 87.5%；服务态度: 89.5%',
    detailByAnalysis: '同比: 泊位新增增长9.5%，交易额增长16.7%，满意度88.6%',
  },
  {
    areaName: '福清市',
    halfYearIllegalParkingDisposal: 980,
    halfYearPublicParkingConstruction: 4,
    halfYearNewBerths: 210,
    halfYearSmartParkingTransactions: 35600,
    halfYearParkingServiceSatisfaction: 87.9,
    yoyChangeRate_IllegalParkingDisposal: 1.8,
    yoyChangeRate_PublicParkingConstruction: 5.2,
    yoyChangeRate_NewBerths: 8.3,
    yoyChangeRate_SmartParkingTransactions: 14.5,
    yoyChangeRate_ServiceSatisfaction: 0.5,
    detailByRegion: '福清市: 980件；连江县: 760件；罗源县: 520件',
    detailByParkingConstructionType: '平面停车场: 2个；立体停车场: 1个；地下停车场: 1个',
    detailByBerthType: '路内泊位: 110个；路外泊位: 70个；专用泊位: 30个',
    detailBySatisfactionDimension: '环境卫生: 87.5%；设施完善: 88.4%；收费合理: 86.9%；服务态度: 88.8%',
    detailByAnalysis: '同比: 停车场建设增长5.2%，平台交易增长14.5%',
  },
  {
    areaName: '连江县',
    halfYearIllegalParkingDisposal: 760,
    halfYearPublicParkingConstruction: 3,
    halfYearNewBerths: 160,
    halfYearSmartParkingTransactions: 28900,
    halfYearParkingServiceSatisfaction: 86.8,
    yoyChangeRate_IllegalParkingDisposal: 0.9,
    yoyChangeRate_PublicParkingConstruction: 4.7,
    yoyChangeRate_NewBerths: 7.2,
    yoyChangeRate_SmartParkingTransactions: 12.8,
    yoyChangeRate_ServiceSatisfaction: 0.3,
    detailByRegion: '连江县: 760件；罗源县: 520件；闽侯县: 430件',
    detailByParkingConstructionType: '平面停车场: 2个；立体停车场: 1个；地下停车场: 0个',
    detailByBerthType: '路内泊位: 85个；路外泊位: 50个；专用泊位: 25个',
    detailBySatisfactionDimension: '环境卫生: 86.2%；设施完善: 87.5%；收费合理: 85.8%；服务态度: 87.7%',
    detailByAnalysis: '同比: 处置量微增0.9%，满意度86.8%，平台交易增长12.8%',
  },
  {
    areaName: '闽侯县',
    halfYearIllegalParkingDisposal: 430,
    halfYearPublicParkingConstruction: 2,
    halfYearNewBerths: 120,
    halfYearSmartParkingTransactions: 18700,
    halfYearParkingServiceSatisfaction: 85.7,
    yoyChangeRate_IllegalParkingDisposal: -0.5,
    yoyChangeRate_PublicParkingConstruction: 3.8,
    yoyChangeRate_NewBerths: 6.1,
    yoyChangeRate_SmartParkingTransactions: 10.3,
    yoyChangeRate_ServiceSatisfaction: 0.2,
    detailByRegion: '闽侯县: 430件；永泰县: 320件；闽清县: 280件',
    detailByParkingConstructionType: '平面停车场: 1个；立体停车场: 1个；地下停车场: 0个',
    detailByBerthType: '路内泊位: 65个；路外泊位: 40个；专用泊位: 15个',
    detailBySatisfactionDimension: '环境卫生: 85.2%；设施完善: 86.3%；收费合理: 84.8%；服务态度: 86.5%',
    detailByAnalysis: '同比: 处置量下降0.5%，泊位新增6.1%，智慧平台交易增长10.3%',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为停车管理半年统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '180',
      rules: 'required',
    },
    {
      fieldName: 'halfYearIllegalParkingDisposal',
      label: '上半年违停案件处置总量',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入上半年违停案件处置总量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearPublicParkingConstruction',
      label: '上半年公共停车场建设数量',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入上半年公共停车场建设数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearNewBerths',
      label: '上半年泊位新增数量',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入上半年泊位新增数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearSmartParkingTransactions',
      label: '上半年智慧停车平台交易总量',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入上半年智慧停车平台交易总量（单位：元）',
        min: 0,
        precision: 0,
        addonAfter: '元',
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearParkingServiceSatisfaction',
      label: '上半年停车管理服务满意度(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入上半年停车管理服务满意度',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_IllegalParkingDisposal',
      label: '违停案件处置总量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_PublicParkingConstruction',
      label: '公共停车场建设数量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_NewBerths',
      label: '泊位新增数量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_SmartParkingTransactions',
      label: '智慧停车平台交易总量同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate_ServiceSatisfaction',
      label: '停车管理服务满意度同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRegion',
      label: '按区域拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按区域拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByParkingConstructionType',
      label: '按停车场建设类型拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按停车场建设类型拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByBerthType',
      label: '按泊位类型拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按泊位类型拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailBySatisfactionDimension',
      label: '按满意度维度拆分明细',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入按满意度维度拆分的明细数据',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByAnalysis',
      label: '同比分析结果',
      component: 'Input',
      labelWidth: '180',
      componentProps: {
        placeholder: '请输入同比分析结果',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为停车管理半年统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'halfYearIllegalParkingDisposal',
      title: '上半年违停案件处置总量',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'halfYearPublicParkingConstruction',
      title: '上半年公共停车场建设数量',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'halfYearNewBerths',
      title: '上半年泊位新增数量',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'halfYearSmartParkingTransactions',
      title: '上半年智慧停车平台交易总量(元)',
      minWidth: 240,
      sortable: true,
    },
    {
      field: 'halfYearParkingServiceSatisfaction',
      title: '上半年停车管理服务满意度(%)',
      minWidth: 220,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_IllegalParkingDisposal',
      title: '违停案件处置总量同比(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_PublicParkingConstruction',
      title: '公共停车场建设数量同比(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_NewBerths',
      title: '泊位新增数量同比(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_SmartParkingTransactions',
      title: '智慧停车平台交易总量同比(%)',
      minWidth: 220,
      sortable: true,
    },
    {
      field: 'yoyChangeRate_ServiceSatisfaction',
      title: '停车管理服务满意度同比(%)',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'detailByRegion',
      title: '按区域拆分明细',
      minWidth: 240,
      sortable: false,
    },
    {
      field: 'detailByParkingConstructionType',
      title: '按停车场建设类型拆分明细',
      minWidth: 240,
      sortable: false,
    },
    {
      field: 'detailByBerthType',
      title: '按泊位类型拆分明细',
      minWidth: 240,
      sortable: false,
    },
    {
      field: 'detailBySatisfactionDimension',
      title: '按满意度维度拆分明细',
      minWidth: 240,
      sortable: false,
    },
    {
      field: 'detailByAnalysis',
      title: '同比分析结果',
      minWidth: 280,
      sortable: false,
    },
  ];
}
