/** 表格初始数据 - 路灯设施监测数据 */
export const dataList = () => [
  {
    id: '1',
    lightNo: 'LT-202406-001',
    roadName: '福州市鼓楼区杨桥东路（东街口-五一广场）',
    switchStatus: '开',
    lightBrightness: 85,
    workingCurrent: 0.8,
    deviceCode: 'DEV-LT-202406-001',
    deviceStatus: '在线',
    staffName: '陈铭（工号：FJYW001）',
    collectFrequency: '5分钟',
    monitorStatus: '运行中',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 3,
    updateTime: '2024-06-15 14:30:00',
    controlStatus: '可控制',
    warnStatusId: '正常',
  },
  {
    id: '2',
    lightNo: 'LT-202406-002',
    roadName: '厦门市思明区鹭江道（轮渡码头-中山路）',
    switchStatus: '开',
    lightBrightness: 90,
    workingCurrent: 0.9,
    deviceCode: 'DEV-LT-202406-002',
    deviceStatus: '在线',
    staffName: '林晓婷（工号：FJYW002）',
    collectFrequency: '10分钟',
    monitorStatus: '运行中',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 5,
    updateTime: '2024-06-15 14:25:00',
    controlStatus: '可控制',
    warnStatusId: '正常',
  },
  {
    id: '3',
    lightNo: 'LT-202406-003',
    roadName: '泉州市丰泽区刺桐路（湖心街-泉秀街）',
    switchStatus: '关',
    lightBrightness: 0,
    workingCurrent: 0,
    deviceCode: 'DEV-LT-202406-003',
    deviceStatus: '在线',
    staffName: '王志远（工号：FJYW003）',
    collectFrequency: '1分钟',
    monitorStatus: '运行中',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 2,
    updateTime: '2024-06-15 14:32:00',
    controlStatus: '可控制',
    warnStatusId: '正常',
  },
  {
    id: '4',
    lightNo: 'LT-202406-004',
    roadName: '漳州市芗城区胜利路（延安北路-新华西路）',
    switchStatus: '开',
    lightBrightness: 75,
    workingCurrent: 0.7,
    deviceCode: 'DEV-LT-202406-004',
    deviceStatus: '在线',
    staffName: '黄丽萍（工号：FJYW004）',
    collectFrequency: '30分钟',
    monitorStatus: '运行中',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 4,
    updateTime: '2024-06-15 14:20:00',
    controlStatus: '可控制',
    warnStatusId: '正常',
  },
  {
    id: '5',
    lightNo: 'LT-202406-005',
    roadName: '莆田市城厢区荔城南大道（凤凰山-万达广场）',
    switchStatus: '开',
    lightBrightness: 60,
    workingCurrent: 1.5,
    deviceCode: 'DEV-LT-202406-005',
    deviceStatus: '离线',
    staffName: '郑建明（工号：FJYW005）',
    collectFrequency: '1小时',
    monitorStatus: '已停止',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 6,
    updateTime: '2024-06-15 13:45:00',
    controlStatus: '不可控制',
    warnStatusId: '电流异常',
  },
  {
    id: '6',
    lightNo: 'LT-202406-006',
    roadName: '宁德市蕉城区闽东中路（市政府-万达广场）',
    switchStatus: '开',
    lightBrightness: 80,
    workingCurrent: 0.8,
    deviceCode: 'DEV-LT-202406-006',
    deviceStatus: '在线',
    staffName: '吴永辉（工号：FJYW006）',
    collectFrequency: '5分钟',
    monitorStatus: '运行中',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 3,
    updateTime: '2024-06-15 14:28:00',
    controlStatus: '可控制',
    warnStatusId: '正常',
  },
  {
    id: '7',
    lightNo: 'LT-202406-007',
    roadName: '龙岩市新罗区龙川路（中山路-登高西路）',
    switchStatus: '关',
    lightBrightness: 0,
    workingCurrent: 0,
    deviceCode: 'DEV-LT-202406-007',
    deviceStatus: '在线',
    staffName: '张志强（工号：FJYW007）',
    collectFrequency: '10分钟',
    monitorStatus: '运行中',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 4,
    updateTime: '2024-06-15 14:31:00',
    controlStatus: '可控制',
    warnStatusId: '正常',
  },
  {
    id: '8',
    lightNo: 'LT-202406-008',
    roadName: '三明市梅列区列东街（东新四路-东新六路）',
    switchStatus: '开',
    lightBrightness: 95,
    workingCurrent: 1.0,
    deviceCode: 'DEV-LT-202406-008',
    deviceStatus: '在线',
    staffName: '李芳（工号：FJYW008）',
    collectFrequency: '30分钟',
    monitorStatus: '运行中',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 5,
    updateTime: '2024-06-15 14:15:00',
    controlStatus: '可控制',
    warnStatusId: '正常',
  },
  {
    id: '9',
    lightNo: 'LT-202406-009',
    roadName: '南平市延平区八一路（江滨路-中山路）',
    switchStatus: '开',
    lightBrightness: 50,
    workingCurrent: 0.5,
    deviceCode: 'DEV-LT-202406-009',
    deviceStatus: '异常',
    staffName: '刘建国（工号：FJYW009）',
    collectFrequency: '1分钟',
    monitorStatus: '已停止',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 2,
    updateTime: '2024-06-15 13:50:00',
    controlStatus: '不可控制',
    warnStatusId: '亮度异常',
  },
  {
    id: '10',
    lightNo: 'LT-202406-010',
    roadName: '平潭综合实验区金井大道（管委会-龙凤头沙滩）',
    switchStatus: '开',
    lightBrightness: 88,
    workingCurrent: 0.9,
    deviceCode: 'DEV-LT-202406-010',
    deviceStatus: '在线',
    staffName: '蔡伟明（工号：FJYW010）',
    collectFrequency: '1小时',
    monitorStatus: '运行中',
    lightBrightnessThreshold: '0-100',
    workingCurrentThreshold: '0-2',
    syncDuration: 6,
    updateTime: '2024-06-15 14:00:00',
    controlStatus: '可控制',
    warnStatusId: '正常',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 路灯设施监测配置表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'lightNo',
      label: '路灯编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路灯编号',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 路灯编号为必填项
    },
    {
      fieldName: 'roadName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
        maxLength: 100,
      },
      labelWidth: '100',
      rules: 'required', // 路段名称为必填项
    },
    {
      fieldName: 'deviceCode',
      label: '监测设备编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测设备编号',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 监测设备编号为必填项
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '1分钟', value: '1分钟' },
          { label: '5分钟', value: '5分钟' },
          { label: '10分钟', value: '10分钟' },
          { label: '30分钟', value: '30分钟' },
          { label: '1小时', value: '1小时' },
          { label: '24小时', value: '24小时' },
        ],
        placeholder: '请选择数据采集频率',
        showSearch: true,
      },
      fieldName: 'collectFrequency',
      label: '数据采集频率',
      rules: 'required', // 数据采集频率为必填项
    },
    {
      fieldName: 'lightBrightnessThreshold',
      label: '亮度阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入亮度阈值（如：0-100）',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 亮度阈值为必填项
    },
    {
      fieldName: 'workingCurrentThreshold',
      label: '电流阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入电流阈值（如：0-2）',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 电流阈值为必填项
    },
    {
      fieldName: 'staffName',
      label: '负责维修员',
      component: 'Input',
      componentProps: {
        placeholder: '请输入负责维修员姓名/工号',
        maxLength: 50,
      },
      labelWidth: '100',
      rules: 'required', // 负责维修员为必填项
    },
  ];
}

/** 筛选表单schema - 路灯设施监测筛选表单 */
export function useFilterFormSchema() {
  return [
    {
      fieldName: 'lightNo',
      label: '路灯编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路灯编号',
        maxLength: 50,
      },
      labelWidth: '100',
    },
    {
      fieldName: 'roadName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
        maxLength: 100,
      },
      labelWidth: '100',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '开', value: '开' },
          { label: '关', value: '关' },
        ],
        placeholder: '请选择开关状态',
        showSearch: true,
      },
      fieldName: 'switchStatus',
      label: '开关状态',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceStatus',
      label: '设备在线状态',
    },
  ];
}

/** 表格字段 - 路灯设施监测表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'lightNo',
      title: '路灯编号',
      minWidth: 150,
      sortable: true,
      slots: { default: 'lightNo' },
    },
    {
      field: 'roadName',
      title: '路段名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'roadName' },
    },
    {
      field: 'switchStatus',
      title: '开关状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'switchStatus' },
    },
    {
      field: 'lightBrightness',
      title: '路灯亮度',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'workingCurrent',
      title: '工作电流',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'deviceCode',
      title: '监测设备编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'deviceCode' },
    },
    {
      field: 'deviceStatus',
      title: '设备在线状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'deviceStatus' },
    },
    {
      field: 'staffName',
      title: '负责维修员',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'collectFrequency',
      title: '数据采集频率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monitorStatus',
      title: '监测状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'monitorStatus' },
    },
    {
      field: 'lightBrightnessThreshold',
      title: '亮度阈值',
      minWidth: 100,
      sortable: false,
    },
    {
      field: 'workingCurrentThreshold',
      title: '电流阈值',
      minWidth: 100,
      sortable: false,
    },
    {
      field: 'syncDuration',
      title: '数据同步时长(秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'updateTime',
      title: '最近更新时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'controlStatus',
      title: '控制状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'controlStatus' },
    },
    {
      field: 'warnStatusId',
      title: '预警触发标识',
      minWidth: 120,
      sortable: true,
      slots: { default: 'warnStatusId' },
    },
    {
      title: '操作',
      width: 200,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
