export const pageConfig = {
  apiName: 'StationOpReport',
  title: '场站资源周期报表',
  exportName: '场站资源周期报表.xlsx',
  nameField: 'reportPeriod',
  primaryField: 'reportPeriod',
  toolbar: ['create', 'search', 'export', 'refresh'],
  rowActionMap: {
    日报: ['detail', 'exportRow'],
    周报: ['detail', 'exportRow'],
    月报: ['detail', 'exportRow'],
    季报: ['detail', 'exportRow'],
    半年报: ['detail', 'exportRow'],
    年报: ['detail', 'exportRow'],
    自定义报表: ['detail', 'exportRow'],
    default: ['detail', 'exportRow'],
  },
  chart: {
    cards: [
      ['totalAreaCount', '总片区数'],
      ['coverStationCount', '覆盖场站数'],
      ['totalStationCount', '总站场数'],
      ['normalOperateCount', '正常运营数'],
      ['totalSpaceCount', '总车位数'],
      ['availableSpaceCount', '可用车位数'],
      ['effectiveRuleCount', '生效规则数'],
      ['orderCount', '订单量'],
      ['revenue', '营收'],
      ['recoveryRate', '追缴完成率'],
      ['depositOrderCount', '押金订单量'],
    ],
    map: true,
    line: ['lineData', 'date', 'orderCount', '本报表周期订单趋势'],
    bar: ['barData', 'areaName', 'stationCount', '关键维度分布'],
  },
};

export const searchFields = [
  {
    field: 'reportPeriod',
    label: '报表周期',
    type: 'select',
    options: ['日报', '周报', '月报', '季报', '半年报', '年报', '自定义报表'],
    required: false,
  },
  {
    field: 'generateStatus',
    label: '生成状态',
    type: 'select',
    options: ['生成中', '生成成功', '生成失败'],
    required: false,
  },
];

export const formFields = [
  {
    field: 'reportPeriod',
    label: '报表周期',
    type: 'select',
    options: ['日报', '周报', '月报', '季报', '半年报', '年报', '自定义报表'],
    required: true,
  },
  { field: 'statDimension', label: '统计维度', type: 'input', required: true },
  { field: 'startTime', label: '开始时间', type: 'date', required: false },
  { field: 'endTime', label: '结束时间', type: 'date', required: false },
];

export const tableColumns = [
  {
    field: 'reportPeriod',
    label: '报表周期',
    minWidth: 120,
    drillType: 'filter',
  },
  { field: 'statPeriod', label: '统计时段', minWidth: 220 },
  {
    field: 'totalAreaCount',
    label: '总片区数',
    minWidth: 130,
    drillType: 'dialog',
    drillLabel: '片区明细',
  },
  {
    field: 'coveredStationCount',
    label: '覆盖场站数',
    minWidth: 140,
    drillType: 'dialog',
    drillLabel: '场站明细',
  },
  {
    field: 'totalStationCount',
    label: '总站场数',
    minWidth: 130,
    drillType: 'dialog',
    drillLabel: '全场站明细',
  },
  {
    field: 'normalOperateCount',
    label: '正常运营数',
    minWidth: 130,
    drillType: 'dialog',
    drillLabel: '正常运营场站明细',
  },
  {
    field: 'totalSpaceCount',
    label: '总车位数',
    minWidth: 120,
    drillType: 'dialog',
    drillLabel: '车位总览明细',
  },
  {
    field: 'availableSpaceCount',
    label: '可用车位数',
    minWidth: 130,
    drillType: 'dialog',
    drillLabel: '可用车位明细',
  },
  {
    field: 'activeRuleCount',
    label: '生效规则数',
    minWidth: 130,
    drillType: 'dialog',
    drillLabel: '生效规则明细',
  },
  {
    field: 'orderCount',
    label: '订单量',
    minWidth: 120,
    drillType: 'dialog',
    drillLabel: '本报表周期订单明细',
  },
  {
    field: 'totalIncome',
    label: '营收',
    minWidth: 140,
    drillType: 'dialog',
    drillLabel: '本报表周期营收明细',
  },
  {
    field: 'debtCompletionRate',
    label: '追缴完成率',
    minWidth: 140,
    drillType: 'dialog',
    drillLabel: '追缴明细',
  },
  {
    field: 'depositOrderCount',
    label: '押金订单量',
    minWidth: 130,
    drillType: 'dialog',
    drillLabel: '押金订单明细',
  },
  {
    field: 'generateStatus',
    label: '生成状态',
    minWidth: 120,
    drillType: 'filter',
  },
  { field: 'generateTime', label: '报表生成时间', minWidth: 180 },
  {
    field: 'operatorName',
    label: '操作人',
    minWidth: 120,
    drillType: 'dialog',
    drillLabel: '操作人信息',
  },
  { field: 'exportCount', label: '报表导出次数', minWidth: 130 },
];

export const detailFields = [
  { key: 'reportPeriod', label: '报表周期', section: '报表信息' },
  { key: 'statPeriod', label: '统计时段', section: '报表信息' },
  { key: 'generateStatus', label: '生成状态', section: '报表信息' },
  { key: 'generateTime', label: '报表生成时间', section: '报表信息' },
  { key: 'operatorName', label: '操作人', section: '报表信息' },
  { key: 'operatorAccount', label: '操作人账号', section: '报表信息' },
  { key: 'exportCount', label: '报表导出次数', section: '报表信息' },
  { key: 'totalAreaCount', label: '总片区数', section: '核心指标' },
  { key: 'coveredStationCount', label: '覆盖场站数', section: '核心指标' },
  { key: 'totalStationCount', label: '总站场数', section: '核心指标' },
  { key: 'normalOperateCount', label: '正常运营数', section: '核心指标' },
  { key: 'totalSpaceCount', label: '总车位数', section: '核心指标' },
  { key: 'availableSpaceCount', label: '可用车位数', section: '核心指标' },
  { key: 'activeRuleCount', label: '生效规则数', section: '核心指标' },
  { key: 'orderCount', label: '订单量', section: '核心指标' },
  { key: 'totalIncome', label: '营收', section: '核心指标' },
  { key: 'debtCompletionRate', label: '追缴完成率', section: '核心指标' },
  { key: 'depositOrderCount', label: '押金订单量', section: '核心指标' },
];
