/** 终端设备表格初始数据 - 按指定字段生成 */
export const dataList = () => {
  return [
    {
      deviceId: 'DEV001',
      deviceTypeName: '收费终端',
      assetName: '芗城区XX社区公共停车场资产',
      deviceCode: 'DEV-CODE-001',
      installTime: '2025-01-10 09:20:30',
      lastMaintainTime: '2025-02-01 14:30:00',
      nextMaintainTime: '2025-03-01 14:30:00',
      contactName: '张三',
      contactPhone: '138****1234',
      deviceStatusName: '在线',
      installPosition: '停车场入口左侧',
      createTime: '2025-01-10 09:20:30',
      operator: '李四',
    },
    {
      deviceId: 'DEV002',
      deviceTypeName: '道闸终端',
      assetName: '龙文区碧湖公园停车场资产',
      deviceCode: 'DEV-CODE-002',
      installTime: '2025-01-12 14:15:20',
      lastMaintainTime: '2025-02-10 10:00:00',
      nextMaintainTime: '2025-03-10 10:00:00',
      contactName: '李四',
      contactPhone: '139****5678',
      deviceStatusName: '在线',
      installPosition: '停车场出口中间',
      createTime: '2025-01-12 14:15:20',
      operator: '王五',
    },
    {
      deviceId: 'DEV003',
      deviceTypeName: '地磁检测器',
      assetName: '龙海区石码镇便民停车场资产',
      deviceCode: 'DEV-CODE-003',
      installTime: '2025-01-15 10:05:10',
      lastMaintainTime: '2025-02-15 16:00:00',
      nextMaintainTime: '2025-03-15 16:00:00',
      contactName: '王五',
      contactPhone: '136****9012',
      deviceStatusName: '离线',
      installPosition: '停车场A区第1车位',
      createTime: '2025-01-15 10:05:10',
      operator: '赵六',
    },
    {
      deviceId: 'DEV004',
      deviceTypeName: '诱导屏',
      assetName: '龙海区闽齐社区停车场资产',
      deviceCode: 'DEV-CODE-004',
      installTime: '2025-01-18 08:30:45',
      lastMaintainTime: '2025-02-18 11:30:00',
      nextMaintainTime: '2025-03-18 11:30:00',
      contactName: '赵六',
      contactPhone: '137****3456',
      deviceStatusName: '故障',
      installPosition: '停车场入口右侧',
      createTime: '2025-01-18 08:30:45',
      operator: '孙七',
    },
    {
      deviceId: 'DEV005',
      deviceTypeName: '收费终端',
      assetName: '芗城区江滨路生态停车场资产',
      deviceCode: 'DEV-CODE-005',
      installTime: '2025-01-20 16:40:15',
      lastMaintainTime: '2025-02-20 09:00:00',
      nextMaintainTime: '2025-03-20 09:00:00',
      contactName: '孙七',
      contactPhone: '135****7890',
      deviceStatusName: '在线',
      installPosition: '停车场出口右侧',
      createTime: '2025-01-20 16:40:15',
      operator: '周八',
    },
    {
      deviceId: 'DEV006',
      deviceTypeName: '车牌识别终端',
      assetName: '龙文区万达商圈停车场资产',
      deviceCode: 'DEV-CODE-006',
      installTime: '2025-01-22 11:10:30',
      lastMaintainTime: '2025-02-22 15:00:00',
      nextMaintainTime: '2025-03-22 15:00:00',
      contactName: '周八',
      contactPhone: '138****2345',
      deviceStatusName: '在线',
      installPosition: '停车场入口中间',
      createTime: '2025-01-22 11:10:30',
      operator: '吴九',
    },
    {
      deviceId: 'DEV007',
      deviceTypeName: '道闸终端',
      assetName: '长泰区武安镇公共停车场资产',
      deviceCode: 'DEV-CODE-007',
      installTime: '2025-01-25 13:25:40',
      lastMaintainTime: '2025-02-25 10:30:00',
      nextMaintainTime: '2025-03-25 10:30:00',
      contactName: '吴九',
      contactPhone: '139****6789',
      deviceStatusName: '维护中',
      installPosition: '停车场出口左侧',
      createTime: '2025-01-25 13:25:40',
      operator: '郑十',
    },
    {
      deviceId: 'DEV008',
      deviceTypeName: '收费终端',
      assetName: '漳浦县绥安镇便民停车场资产',
      deviceCode: 'DEV-CODE-008',
      installTime: '2025-01-28 09:50:25',
      lastMaintainTime: '2025-02-28 14:00:00',
      nextMaintainTime: '2025-03-28 14:00:00',
      contactName: '郑十',
      contactPhone: '136****0123',
      deviceStatusName: '离线',
      installPosition: '停车场入口',
      createTime: '2025-01-28 09:50:25',
      operator: '张三',
    },
    {
      deviceId: 'DEV009',
      deviceTypeName: '地磁检测器',
      assetName: '芗城区巷口街道停车场资产',
      deviceCode: 'DEV-CODE-009',
      installTime: '2025-02-01 15:15:10',
      lastMaintainTime: '2025-02-20 16:30:00',
      nextMaintainTime: '2025-03-20 16:30:00',
      contactName: '张三',
      contactPhone: '137****4567',
      deviceStatusName: '在线',
      installPosition: '停车场B区第5车位',
      createTime: '2025-02-01 15:15:10',
      operator: '李四',
    },
    {
      deviceId: 'DEV010',
      deviceTypeName: '诱导屏',
      assetName: '龙文区蓝田街道停车场资产',
      deviceCode: 'DEV-CODE-010',
      installTime: '2025-02-05 10:30:50',
      lastMaintainTime: '2025-02-25 11:00:00',
      nextMaintainTime: '2025-03-25 11:00:00',
      contactName: '李四',
      contactPhone: '135****8901',
      deviceStatusName: '故障',
      installPosition: '停车场出口指示牌',
      createTime: '2025-02-05 10:30:50',
      operator: '王五',
    },
    {
      deviceId: 'DEV011',
      deviceTypeName: '车牌识别终端',
      assetName: '龙文区步文街道停车场资产',
      deviceCode: 'DEV-CODE-011',
      installTime: '2025-02-08 14:20:15',
      lastMaintainTime: '2025-02-28 09:30:00',
      nextMaintainTime: '2025-03-28 09:30:00',
      contactName: '王五',
      contactPhone: '138****2346',
      deviceStatusName: '在线',
      installPosition: '停车场入口识别区',
      createTime: '2025-02-08 14:20:15',
      operator: '赵六',
    },
    {
      deviceId: 'DEV012',
      deviceTypeName: '收费终端',
      assetName: '芗城区东铺头街道停车场资产',
      deviceCode: 'DEV-CODE-012',
      installTime: '2025-02-10 09:40:30',
      lastMaintainTime: '2025-02-20 10:00:00',
      nextMaintainTime: '2025-03-20 10:00:00',
      contactName: '赵六',
      contactPhone: '139****6780',
      deviceStatusName: '维护中',
      installPosition: '停车场出口收费亭',
      createTime: '2025-02-10 09:40:30',
      operator: '孙七',
    },
    {
      deviceId: 'DEV013',
      deviceTypeName: '道闸终端',
      assetName: '全市通用资产',
      deviceCode: 'DEV-CODE-013',
      installTime: '2025-02-12 11:25:00',
      lastMaintainTime: '2025-02-22 15:00:00',
      nextMaintainTime: '2025-03-22 15:00:00',
      contactName: '孙七',
      contactPhone: '136****9013',
      deviceStatusName: '在线',
      installPosition: '主出入口道闸',
      createTime: '2025-02-12 11:25:00',
      operator: '周八',
    },
    {
      deviceId: 'DEV014',
      deviceTypeName: '地磁检测器',
      assetName: '龙文区万达商圈停车场资产',
      deviceCode: 'DEV-CODE-014',
      installTime: '2025-02-15 16:30:45',
      lastMaintainTime: '2025-02-25 14:00:00',
      nextMaintainTime: '2025-03-25 14:00:00',
      contactName: '周八',
      contactPhone: '137****3457',
      deviceStatusName: '离线',
      installPosition: 'VIP车位区',
      createTime: '2025-02-15 16:30:45',
      operator: '吴九',
    },
    {
      deviceId: 'DEV015',
      deviceTypeName: '收费终端',
      assetName: '芗城区江滨路生态停车场资产',
      deviceCode: 'DEV-CODE-015',
      installTime: '2025-02-18 10:15:20',
      lastMaintainTime: '2025-02-28 11:30:00',
      nextMaintainTime: '2025-03-28 11:30:00',
      contactName: '吴九',
      contactPhone: '135****7891',
      deviceStatusName: '在线',
      installPosition: '自助缴费区',
      createTime: '2025-02-18 10:15:20',
      operator: '郑十',
    },
  ];
};

/** 终端设备表单配置（包含所有指定字段） */
export function useFormSchema() {
  return [
    {
      fieldName: 'deviceId',
      label: '设备ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入设备ID',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceTypeName',
      label: '设备类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择设备类型',
        options: [
          { label: '收费终端', value: '收费终端' },
          { label: '道闸终端', value: '道闸终端' },
          { label: '地磁检测器', value: '地磁检测器' },
          { label: '诱导屏', value: '诱导屏' },
          { label: '车牌识别终端', value: '车牌识别终端' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'assetName',
      label: '所属资产',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属资产',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceCode',
      label: '设备编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入设备编码',
      },
      rules: 'required',
    },
    {
      fieldName: 'installTime',
      label: '安装时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择安装时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'lastMaintainTime',
      label: '上次维护时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择上次维护时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'nextMaintainTime',
      label: '下次维护时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择下次维护时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'contactName',
      label: '联系人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入联系人',
      },
      rules: 'required',
    },
    {
      fieldName: 'contactPhone',
      label: '联系电话',
      component: 'Input',
      componentProps: {
        placeholder: '请输入联系电话',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceStatusName',
      label: '状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择状态',
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '故障', value: '故障' },
          { label: '维护中', value: '维护中' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'installPosition',
      label: '安装位置',
      component: 'Input',
      componentProps: {
        placeholder: '请输入安装位置',
      },
      rules: 'required',
    },
    {
      fieldName: 'createTime',
      label: '创建时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择创建时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'operator',
      label: '操作人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入操作人',
      },
      rules: 'required',
    },
  ];
}

/** 终端设备表格列配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'deviceId',
      title: '设备ID',
      minWidth: 100,
      sortable: true,
      slots: { default: 'deviceId' },
    },
    {
      field: 'deviceTypeName',
      title: '设备类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'assetName',
      title: '所属资产',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'deviceCode',
      title: '设备编码',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'installTime',
      title: '安装时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'lastMaintainTime',
      title: '上次维护时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'nextMaintainTime',
      title: '下次维护时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'contactName',
      title: '联系人',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'contactPhone',
      title: '联系电话',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'deviceStatusName',
      title: '状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'deviceStatusName' },
    },
    {
      field: 'installPosition',
      title: '安装位置',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'operator',
      title: '操作人',
      minWidth: 100,
      sortable: true,
    },
    {
      title: '操作',
      width: 100,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

export const textObj = {
  editText: '编辑设备',
  addText: '新增设备',
  excelName: '终端设备列表',
  excelAllName: '终端设备数据.xlsx',
  total: ' 总计: 设备数量15; 在线10; 离线2; 故障2; 维护中1',
};

/** 详情抽屉字段配置 */
export const detailFields = [
  { key: 'deviceId', label: '设备ID' },
  { key: 'deviceTypeName', label: '设备类型' },
  { key: 'assetName', label: '所属资产' },
  { key: 'deviceCode', label: '设备编码' },
  { key: 'installTime', label: '安装时间' },
  { key: 'lastMaintainTime', label: '上次维护时间' },
  { key: 'nextMaintainTime', label: '下次维护时间' },
  { key: 'contactName', label: '联系人' },
  { key: 'contactPhone', label: '联系电话' },
  { key: 'deviceStatusName', label: '状态' },
  { key: 'installPosition', label: '安装位置' },
  { key: 'createTime', label: '创建时间' },
  { key: 'operator', label: '操作人' },
];
