/** 表格初始数据 - 窨井盖设施监测月报数据 */
export const dataList = () => [
  {
    areaName: '福州市鼓楼区',
    deptName: '福州市鼓楼区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 1500,
    monthTotalHiddenTroubleCount: 60,
    monthDisposalCompleteCount: 50,
    deviceMonthOnlineRate: 97.5,
    monthRepeatHiddenTroubleCount: 10,
    monthHiddenTroubleDisposalRate: 83.33,
    monthRepeatHiddenTroubleRate: 16.67,
    yoyHiddenTroubleChangeRate: 10,
    deptAssessmentScore: 85,
    monthAvgDisposalDuration: 8.5,
  },
  {
    areaName: '厦门市思明区',
    deptName: '厦门市思明区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 2000,
    monthTotalHiddenTroubleCount: 30,
    monthDisposalCompleteCount: 30,
    deviceMonthOnlineRate: 99.2,
    monthRepeatHiddenTroubleCount: 3,
    monthHiddenTroubleDisposalRate: 100,
    monthRepeatHiddenTroubleRate: 10,
    yoyHiddenTroubleChangeRate: -5,
    deptAssessmentScore: 95,
    monthAvgDisposalDuration: 4.2,
  },
  {
    areaName: '泉州市丰泽区',
    deptName: '泉州市丰泽区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 1800,
    monthTotalHiddenTroubleCount: 90,
    monthDisposalCompleteCount: 65,
    deviceMonthOnlineRate: 85.3,
    monthRepeatHiddenTroubleCount: 25,
    monthHiddenTroubleDisposalRate: 72.22,
    monthRepeatHiddenTroubleRate: 27.78,
    yoyHiddenTroubleChangeRate: 25,
    deptAssessmentScore: 65,
    monthAvgDisposalDuration: 15.6,
  },
  {
    areaName: '漳州市芗城区',
    deptName: '漳州市芗城区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 1200,
    monthTotalHiddenTroubleCount: 15,
    monthDisposalCompleteCount: 15,
    deviceMonthOnlineRate: 99,
    monthRepeatHiddenTroubleCount: 1,
    monthHiddenTroubleDisposalRate: 100,
    monthRepeatHiddenTroubleRate: 6.67,
    yoyHiddenTroubleChangeRate: -15,
    deptAssessmentScore: 90,
    monthAvgDisposalDuration: 3.8,
  },
  {
    areaName: '莆田市城厢区',
    deptName: '莆田市城厢区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 1600,
    monthTotalHiddenTroubleCount: 75,
    monthDisposalCompleteCount: 55,
    deviceMonthOnlineRate: 78.6,
    monthRepeatHiddenTroubleCount: 18,
    monthHiddenTroubleDisposalRate: 73.33,
    monthRepeatHiddenTroubleRate: 24,
    yoyHiddenTroubleChangeRate: 20,
    deptAssessmentScore: 70,
    monthAvgDisposalDuration: 12.5,
  },
  {
    areaName: '宁德市蕉城区',
    deptName: '宁德市蕉城区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 1400,
    monthTotalHiddenTroubleCount: 25,
    monthDisposalCompleteCount: 23,
    deviceMonthOnlineRate: 97.8,
    monthRepeatHiddenTroubleCount: 4,
    monthHiddenTroubleDisposalRate: 92,
    monthRepeatHiddenTroubleRate: 16,
    yoyHiddenTroubleChangeRate: 5,
    deptAssessmentScore: 88,
    monthAvgDisposalDuration: 6.2,
  },
  {
    areaName: '龙岩市新罗区',
    deptName: '龙岩市新罗区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 1700,
    monthTotalHiddenTroubleCount: 60,
    monthDisposalCompleteCount: 45,
    deviceMonthOnlineRate: 96.5,
    monthRepeatHiddenTroubleCount: 12,
    monthHiddenTroubleDisposalRate: 75,
    monthRepeatHiddenTroubleRate: 20,
    yoyHiddenTroubleChangeRate: 15,
    deptAssessmentScore: 75,
    monthAvgDisposalDuration: 9.8,
  },
  {
    areaName: '三明市梅列区',
    deptName: '三明市梅列区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 1300,
    monthTotalHiddenTroubleCount: 10,
    monthDisposalCompleteCount: 10,
    deviceMonthOnlineRate: 98.9,
    monthRepeatHiddenTroubleCount: 1,
    monthHiddenTroubleDisposalRate: 100,
    monthRepeatHiddenTroubleRate: 10,
    yoyHiddenTroubleChangeRate: -10,
    deptAssessmentScore: 92,
    monthAvgDisposalDuration: 4.5,
  },
  {
    areaName: '南平市延平区',
    deptName: '南平市延平区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 1500,
    monthTotalHiddenTroubleCount: 45,
    monthDisposalCompleteCount: 35,
    deviceMonthOnlineRate: 88.7,
    monthRepeatHiddenTroubleCount: 10,
    monthHiddenTroubleDisposalRate: 77.78,
    monthRepeatHiddenTroubleRate: 22.22,
    yoyHiddenTroubleChangeRate: 12,
    deptAssessmentScore: 78,
    monthAvgDisposalDuration: 14.2,
  },
  {
    areaName: '平潭综合实验区',
    deptName: '平潭综合实验区市政管理处',
    monthStatisticsPeriod: '2024年06月',
    manholeTotalCount: 1100,
    monthTotalHiddenTroubleCount: 12,
    monthDisposalCompleteCount: 12,
    deviceMonthOnlineRate: 99.5,
    monthRepeatHiddenTroubleCount: 2,
    monthHiddenTroubleDisposalRate: 100,
    monthRepeatHiddenTroubleRate: 16.67,
    yoyHiddenTroubleChangeRate: -8,
    deptAssessmentScore: 90,
    monthAvgDisposalDuration: 5.1,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施监测月报表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'deptName',
      label: '责任单位',
      component: 'Input',
      componentProps: {
        placeholder: '请输入责任单位',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'monthStatisticsPeriod',
      label: '月统计时段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入月统计时段（如：2024年06月）',
        maxlength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 月统计时段为必填项
    },
  ];
}

/** 表格字段 - 窨井盖设施监测月报表格列 */
export function useGridColumns() {
  return [
    {
      field: 'areaName',
      title: '所属区域',
      minWidth: 180,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'deptName',
      title: '责任单位',
      minWidth: 180,
      sortable: true,
      slots: { default: 'deptName' },
    },
    {
      field: 'monthStatisticsPeriod',
      title: '月统计时段',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'manholeTotalCount',
      title: '窨井盖总数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monthTotalHiddenTroubleCount',
      title: '月累计隐患数',
      minWidth: 140,
      sortable: true,
      slots: { default: 'monthTotalHiddenTroubleCount' },
    },
    {
      field: 'monthDisposalCompleteCount',
      title: '月处置完成数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deviceMonthOnlineRate',
      title: '设备月在线率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'monthRepeatHiddenTroubleCount',
      title: '月重复隐患数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monthHiddenTroubleDisposalRate',
      title: '月隐患处置完成率(%)',
      minWidth: 180,
      sortable: true,
      slots: { default: 'monthHiddenTroubleDisposalRate' },
    },
    {
      field: 'monthRepeatHiddenTroubleRate',
      title: '月重复隐患率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yoyHiddenTroubleChangeRate',
      title: '同比隐患变化率(%)',
      minWidth: 160,
      sortable: true,
      slots: { default: 'yoyHiddenTroubleChangeRate' },
    },
    {
      field: 'deptAssessmentScore',
      title: '责任单位考核得分',
      minWidth: 160,
      sortable: true,
      slots: { default: 'deptAssessmentScore' },
    },
    {
      field: 'monthAvgDisposalDuration',
      title: '月平均处置时长(小时)',
      minWidth: 160,
      sortable: true,
    },
    {
      title: '操作',
      width: 240,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
