/** 表格初始数据 - 改造为出入口管理数据 */
export const dataList = () => {
  return [
    {
      id: '2',
      entranceName: '碧湖公园东门', // 出入口名称
      parkingLot: '龙文区碧湖公园停车场', // 所属车场/车库
      entranceType: '入口', // 出入口类型
      laneCount: '2', // 车道数量
      address: '龙文区碧湖路126号', // 地址
      openTime: '07:00', // 开放时间
      closeTime: '22:00', // 关闭时间
      enableStatus: '禁用', // 启用状态
      contactPerson: '王经理', // 联系人
      contactPhone: '123456789', // 联系电话
      currentStatus: '维护中', // 当前状态
      relatedDeviceCount: '8', // 关联设备数
      lastOperateTime: '2026-01-10 18:30:00', // 最后运营时间
    },
    {
      id: '3',
      entranceName: '石码镇北门',
      parkingLot: '龙海区石码镇便民停车场',
      entranceType: '出口',
      laneCount: '1',
      address: '龙海区石码镇解放北路59号',
      openTime: '08:00',
      closeTime: '21:00',
      enableStatus: '禁用',
      contactPerson: '李主管',
      contactPhone: '13959678987',
      currentStatus: '设备更换中',
      relatedDeviceCount: '4',
      lastOperateTime: '2026-01-12 09:15:00',
    },
    {
      id: '4',
      entranceName: '闽齐社区西门入口',
      parkingLot: '龙海区闽齐社区停车场',
      entranceType: '入口',
      laneCount: '2',
      address: '闽齐社区西门',
      openTime: '00:00',
      closeTime: '24:00',
      enableStatus: '启用',
      contactPerson: '张管理员',
      contactPhone: '15399916161',
      currentStatus: '正常运营',
      relatedDeviceCount: '6',
      lastOperateTime: '2026-01-15 22:45:00',
    },
    {
      id: '5',
      entranceName: '江滨路主入口',
      parkingLot: '芗城区江滨路生态停车场',
      entranceType: '入口',
      laneCount: '3',
      address: '芗城区江滨南路189号',
      openTime: '06:00',
      closeTime: '24:00',
      enableStatus: '启用',
      contactPerson: '陈师傅',
      contactPhone: '8888888',
      currentStatus: '正常运营',
      relatedDeviceCount: '10',
      lastOperateTime: '2026-01-15 23:10:00',
    },
    {
      id: '6',
      entranceName: '万达商圈南入口',
      parkingLot: '龙文区万达商圈停车场',
      entranceType: '入口',
      laneCount: '4',
      address: '龙文区建元东路2号',
      openTime: '00:00',
      closeTime: '24:00',
      enableStatus: '启用',
      contactPerson: '刘经理',
      contactPhone: '15860234567',
      currentStatus: '正常运营',
      relatedDeviceCount: '12',
      lastOperateTime: '2026-01-16 08:20:00',
    },
    {
      id: '7',
      entranceName: '武安镇人民西路入口',
      parkingLot: '长泰区武安镇公共停车场',
      entranceType: '入口',
      laneCount: '2',
      address: '长泰区武安镇人民西路77号',
      openTime: '07:00',
      closeTime: '23:00',
      enableStatus: '启用',
      contactPerson: '黄管理员',
      contactPhone: '13706987654',
      currentStatus: '正常运营',
      relatedDeviceCount: '7',
      lastOperateTime: '2026-01-15 19:00:00',
    },
    {
      id: '8',
      entranceName: '绥安镇金浦大道出口',
      parkingLot: '漳浦县绥安镇便民停车场',
      entranceType: '出口',
      laneCount: '1',
      address: '漳浦县绥安镇金浦大道101号',
      openTime: '08:00',
      closeTime: '20:00',
      enableStatus: '禁用',
      contactPerson: '郑师傅',
      contactPhone: '13695901234',
      currentStatus: '积水清理中',
      relatedDeviceCount: '3',
      lastOperateTime: '2026-01-11 14:30:00',
    },
    {
      id: '9',
      entranceName: '巷口街道新华东路入口',
      parkingLot: '芗城区巷口街道停车场',
      entranceType: '入口',
      laneCount: '2',
      address: '芗城区新华东路32号',
      openTime: '06:00',
      closeTime: '23:00',
      enableStatus: '暂停运营',
      contactPerson: '吴主管',
      contactPhone: '18960012345',
      currentStatus: '收费调整中',
      relatedDeviceCount: '5',
      lastOperateTime: '2026-01-09 17:45:00',
    },
    {
      id: '10',
      entranceName: '蓝田街道梧桥中路出口',
      parkingLot: '龙文区蓝田街道停车场',
      entranceType: '出口',
      laneCount: '2',
      address: '龙文区蓝田街道梧桥中路58号',
      openTime: '00:00',
      closeTime: '24:00',
      enableStatus: '暂停运营',
      contactPerson: '林师傅',
      contactPhone: '15980567890',
      currentStatus: '设施维修中',
      relatedDeviceCount: '9',
      lastOperateTime: '2026-01-08 10:15:00',
    },
    {
      id: '11',
      entranceName: '步文街道天亭路主入口',
      parkingLot: '龙文区步文街道停车场',
      entranceType: '入口',
      laneCount: '3',
      address: '龙文区步文街道天亭路23号',
      openTime: '00:00',
      closeTime: '24:00',
      enableStatus: '启用',
      contactPerson: '赵经理',
      contactPhone: '13859987654',
      currentStatus: '正常运营',
      relatedDeviceCount: '11',
      lastOperateTime: '2026-01-16 09:30:00',
    },
    {
      id: '12',
      entranceName: '东铺头街道新华西路入口',
      parkingLot: '芗城区东铺头街道停车场',
      entranceType: '入口',
      laneCount: '2',
      address: '芗城区东铺头街道新华西路128号',
      openTime: '07:00',
      closeTime: '23:00',
      enableStatus: '维修中',
      contactPerson: '孙管理员',
      contactPhone: '18960098765',
      currentStatus: '设备巡检中',
      relatedDeviceCount: '8',
      lastOperateTime: '2026-01-13 11:20:00',
    },
    {
      id: '13',
      entranceName: '西桥街道江滨路专用入口',
      parkingLot: '芗城区西桥街道停车场',
      entranceType: '专用入口',
      laneCount: '1',
      address: '芗城区西桥街道江滨路89号',
      openTime: '00:00',
      closeTime: '24:00',
      enableStatus: '维修中',
      contactPerson: '周师傅',
      contactPhone: '15060543210',
      currentStatus: '门禁维修中',
      relatedDeviceCount: '4',
      lastOperateTime: '2026-01-10 15:40:00',
    },
    {
      id: '14',
      entranceName: '石码街道紫葳路出口',
      parkingLot: '龙海区石码街道停车场',
      entranceType: '出口',
      laneCount: '2',
      address: '龙海区石码街道紫葳路156号',
      openTime: '暂停营业',
      closeTime: '暂停营业',
      enableStatus: '维护中',
      contactPerson: '马主管',
      contactPhone: '13599567890',
      currentStatus: '地面翻新中',
      relatedDeviceCount: '0',
      lastOperateTime: '2026-01-05 12:00:00',
    },
    {
      id: '15',
      entranceName: '武安镇人民东路主入口',
      parkingLot: '长泰区武安镇停车场',
      entranceType: '入口',
      laneCount: '3',
      address: '长泰区武安镇人民东路78号',
      openTime: '00:00',
      closeTime: '24:00',
      enableStatus: '启用',
      contactPerson: '朱管理员',
      contactPhone: '17759687654',
      currentStatus: '正常运营',
      relatedDeviceCount: '13',
      lastOperateTime: '2026-01-15 20:10:00',
    },
    {
      id: '16',
      entranceName: '绥安镇金浦大道入口',
      parkingLot: '漳浦县绥安镇停车场',
      entranceType: '入口',
      laneCount: '2',
      address: '漳浦县绥安镇金浦大道39号',
      openTime: '08:00',
      closeTime: '22:00',
      enableStatus: '启用',
      contactPerson: '韩师傅',
      contactPhone: '18659678901',
      currentStatus: '正常运营',
      relatedDeviceCount: '7',
      lastOperateTime: '2026-01-16 11:00:00',
    },
    {
      id: '17',
      entranceName: '云陵镇宝城路专用入口',
      parkingLot: '云霄县云陵镇停车场',
      entranceType: '专用入口',
      laneCount: '1',
      address: '云霄县云陵镇宝城路66号',
      openTime: '08:00',
      closeTime: '18:00',
      enableStatus: '启用',
      contactPerson: '秦主管',
      contactPhone: '13960087654',
      currentStatus: '正常运营',
      relatedDeviceCount: '5',
      lastOperateTime: '2026-01-15 17:30:00',
    },
    {
      id: '18',
      entranceName: '南诏镇中山路出口',
      parkingLot: '诏安县南诏镇停车场',
      entranceType: '出口',
      laneCount: '1',
      address: '诏安县南诏镇中山路102号',
      openTime: '暂停营业',
      closeTime: '暂停营业',
      enableStatus: '停用',
      contactPerson: '许管理员',
      contactPhone: '15280678901',
      currentStatus: '消防整改中',
      relatedDeviceCount: '0',
      lastOperateTime: '2026-01-01 09:00:00',
    },
    {
      id: '19',
      entranceName: '小溪镇东风路主入口',
      parkingLot: '平和县小溪镇停车场',
      entranceType: '入口',
      laneCount: '3',
      address: '平和县小溪镇东风路88号',
      openTime: '00:00',
      closeTime: '24:00',
      enableStatus: '启用',
      contactPerson: '邓师傅',
      contactPhone: '13695987654',
      currentStatus: '正常运营',
      relatedDeviceCount: '10',
      lastOperateTime: '2026-01-16 14:20:00',
    },
    {
      id: '24',
      entranceName: '蓝田街道梧桥中路入口',
      parkingLot: '龙文区蓝田街道停车场',
      entranceType: '入口',
      laneCount: '2',
      address: '龙文区蓝田街道梧桥中路58号',
      openTime: '00:00',
      closeTime: '24:00',
      enableStatus: '启用',
      contactPerson: '彭管理员',
      contactPhone: '15980567890',
      currentStatus: '正常运营',
      relatedDeviceCount: '9',
      lastOperateTime: '2026-01-16 07:45:00',
    },
    {
      id: '25',
      entranceName: '蓝田街道梧桥中路次入口',
      parkingLot: '龙文区蓝田街道停车场',
      entranceType: '入口',
      laneCount: '2',
      address: '龙文区蓝田街道梧桥中路58号',
      openTime: '00:00',
      closeTime: '24:00',
      enableStatus: '启用',
      contactPerson: '彭管理员',
      contactPhone: '15980567890',
      currentStatus: '正常运营',
      relatedDeviceCount: '9',
      lastOperateTime: '2026-01-16 08:10:00',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 - 改造为出入口管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'id',
      label: '出入口ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入出入口ID',
      },
      labelWidth: '100',
      rules: 'required',
    },
    {
      fieldName: 'entranceName',
      label: '出入口名称',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入出入口名称',
      },
      rules: 'required',
    },
    {
      fieldName: 'parkingLot',
      label: '所属车场/车库',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入所属车场/车库',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '入口', value: '入口' },
          { label: '出口', value: '出口' },
          { label: '专用入口', value: '专用入口' },
          { label: '专用出口', value: '专用出口' },
        ],
        placeholder: '请选择出入口类型',
        showSearch: true,
      },
      defaultValue: '入口',
      fieldName: 'entranceType',
      label: '出入口类型',
    },
    {
      fieldName: 'laneCount',
      label: '车道数量',
      component: 'InputNumber', // 改为数字输入框更贴合场景
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入车道数量',
        min: 1, // 车道数量至少为1
      },
      rules: 'required',
    },
    {
      fieldName: 'address',
      label: '地址',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入地址',
      },
      rules: 'required',
    },
    {
      fieldName: 'openTime',
      label: '开放时间',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入开放时间（如：07:00）',
      },
    },
    {
      fieldName: 'closeTime',
      label: '关闭时间',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入关闭时间（如：22:00）',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '启用', value: '启用' },
          { label: '禁用', value: '禁用' },
          { label: '暂停运营', value: '暂停运营' },
          { label: '维修中', value: '维修中' },
          { label: '维护中', value: '维护中' },
          { label: '停用', value: '停用' },
        ],
        placeholder: '请选择启用状态',
        showSearch: true,
      },
      fieldName: 'enableStatus',
      label: '启用状态',
      rules: 'required',
    },
    {
      fieldName: 'contactPerson',
      label: '联系人',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入联系人',
      },
    },
    {
      fieldName: 'contactPhone',
      label: '联系电话',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入联系电话',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '正常运营', value: '正常运营' },
          { label: '维护中', value: '维护中' },
          { label: '设备更换中', value: '设备更换中' },
          { label: '积水清理中', value: '积水清理中' },
          { label: '收费调整中', value: '收费调整中' },
          { label: '设施维修中', value: '设施维修中' },
          { label: '设备巡检中', value: '设备巡检中' },
          { label: '门禁维修中', value: '门禁维修中' },
          { label: '地面翻新中', value: '地面翻新中' },
          { label: '消防整改中', value: '消防整改中' },
        ],
        placeholder: '请选择当前状态',
        showSearch: true,
      },
      fieldName: 'currentStatus',
      label: '当前状态',
    },
    {
      fieldName: 'relatedDeviceCount',
      label: '关联设备数',
      component: 'InputNumber',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入关联设备数',
        min: 0,
      },
    },
    {
      fieldName: 'lastOperateTime',
      label: '最后运营时间',
      component: 'DatePicker', // 改为时间选择器更贴合场景
      labelWidth: '100',
      componentProps: {
        placeholder: '请选择最后运营时间',
        type: 'datetime', // 支持选择日期+时间
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
  ];
}

/** 表格字段 - 改造为出入口管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: '出入口ID',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'entranceName',
      title: '出入口名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'entranceName' }, // 调整slot名称贴合新字段
    },
    {
      field: 'parkingLot',
      title: '所属车场/车库',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'entranceType',
      title: '出入口类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'laneCount',
      title: '车道数量',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'address',
      title: '地址',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'openTime',
      title: '开放时间',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'closeTime',
      title: '关闭时间',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'enableStatus',
      title: '启用状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'contactPerson',
      title: '联系人',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'contactPhone',
      title: '联系电话',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'currentStatus',
      title: '当前状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'relatedDeviceCount',
      title: '关联设备数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'lastOperateTime',
      title: '最后运营时间',
      minWidth: 200,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 - 改造为出入口管理文案 */
export const textObj = {
  editText: '编辑出入口',
  addText: '新增出入口',
  excelName: '出入口列表',
  excelAllName: '全市出入口数据.xlsx',
  total: '出入口数量20;车道总数:45;关联设备数:128', // 适配新数据的统计文案
};