// data.js
/** 表格初始数据 - 任务数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "taskName": "服务器巡检任务-01",
      "taskType": "巡检任务",
      "assigner": "张三",
      "assignTime": "2026-01-20 09:30",
      "deadline": "2026-01-23 18:00",
      "priority": "高",
      "description": "对机房服务器进行定期巡检，检查硬件状态、系统日志...",
      "taskId": "TASK-20260120-001",
      "receiveStatus": "已认领",
      "relatedResource": "服务器集群-A",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-20 09:00",
      "operationLog": "任务创建"
    },
    {
      "id": 2,
      "taskName": "数据库性能优化",
      "taskType": "项目任务",
      "assigner": "王五",
      "assignTime": "2026-01-21 14:00",
      "deadline": "2026-01-25 17:00",
      "priority": "中",
      "description": "对生产数据库进行性能优化，包括索引优化、查询调优等",
      "taskId": "TASK-20260121-002",
      "receiveStatus": "未认领",
      "relatedResource": "MySQL数据库-01",
      "currentProgress": "50%",
      "startTime": "2026-01-21 15:00",
      "expectedFinishTime": "2026-01-24 18:00",
      "updateTime": "2026-01-22 10:30",
      "delayStatus": "正常",
      "cooperators": "赵六,钱七",
      "finishTime": "",
      "acceptResult": "",
      "executor": "李四",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-21 13:30",
      "operationLog": "任务认领"
    },
    {
      "id": 3,
      "taskName": "网络设备配置备份",
      "taskType": "日常运维",
      "assigner": "孙八",
      "assignTime": "2026-01-19 10:00",
      "deadline": "2026-01-22 12:00",
      "priority": "低",
      "description": "备份所有网络设备的配置文件",
      "taskId": "TASK-20260119-003",
      "receiveStatus": "已认领",
      "relatedResource": "核心交换机",
      "currentProgress": "100%",
      "startTime": "2026-01-19 11:00",
      "expectedFinishTime": "2026-01-22 10:00",
      "updateTime": "2026-01-22 09:45",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-22 09:45",
      "acceptResult": "通过",
      "executor": "李四",
      "attachment": "backup_config.zip",
      "executionDuration": "3天",
      "archiveTime": "2026-01-22 10:00",
      "acceptOpinion": "备份完整，符合要求",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-19 09:30",
      "operationLog": "任务完成"
    },
    {
      "id": 4,
      "taskName": "应用系统部署",
      "taskType": "项目任务",
      "assigner": "李四",
      "assignTime": "2026-01-18 13:00",
      "deadline": "2026-01-24 20:00",
      "priority": "高",
      "description": "部署新版应用系统到生产环境",
      "taskId": "TASK-20260118-004",
      "receiveStatus": "已认领",
      "relatedResource": "应用服务器集群",
      "currentProgress": "80%",
      "startTime": "2026-01-18 14:00",
      "expectedFinishTime": "2026-01-23 18:00",
      "updateTime": "2026-01-22 16:30",
      "delayStatus": "申请中",
      "cooperators": "周五,吴九",
      "finishTime": "",
      "acceptResult": "",
      "executor": "王五",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "王五",
      "createTime": "2026-01-18 12:30",
      "operationLog": "进度更新"
    },
    {
      "id": 5,
      "taskName": "安全漏洞修复",
      "taskType": "故障处理",
      "assigner": "郑十",
      "assignTime": "2026-01-22 08:30",
      "deadline": "2026-01-23 12:00",
      "priority": "紧急",
      "description": "修复发现的高危安全漏洞",
      "taskId": "TASK-20260122-005",
      "receiveStatus": "未认领",
      "relatedResource": "Web服务器",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-01-22 08:00",
      "operationLog": "任务创建"
    },
    {
      "id": 6,
      "taskName": "月度工作报告撰写",
      "taskType": "日常运维",
      "assigner": "李四",
      "assignTime": "",
      "deadline": "2026-01-25 17:00",
      "priority": "中",
      "description": "撰写1月份IT运维工作报告",
      "taskId": "TASK-20260115-006",
      "receiveStatus": "已认领",
      "relatedResource": "文档管理系统",
      "currentProgress": "30%",
      "startTime": "2026-01-20 09:00",
      "expectedFinishTime": "2026-01-24 18:00",
      "updateTime": "2026-01-22 14:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "李四",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "李四",
      "remindCount": 1,
      "latestDynamic": "进度更新至30%",
      "operator": "李四",
      "createTime": "2026-01-15 10:00",
      "operationLog": "任务发起"
    },
    {
      "id": 7,
      "taskName": "备份系统验证测试",
      "taskType": "巡检任务",
      "assigner": "周三",
      "assignTime": "2026-01-17 11:00",
      "deadline": "2026-01-20 17:00",
      "priority": "中",
      "description": "对备份系统进行恢复验证测试",
      "taskId": "TASK-20260117-007",
      "receiveStatus": "已认领",
      "relatedResource": "备份服务器",
      "currentProgress": "100%",
      "startTime": "2026-01-17 13:00",
      "expectedFinishTime": "2026-01-20 16:00",
      "updateTime": "2026-01-20 15:30",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-20 15:30",
      "acceptResult": "通过",
      "executor": "李四",
      "attachment": "test_report.pdf",
      "executionDuration": "3天",
      "archiveTime": "2026-01-20 16:00",
      "acceptOpinion": "测试通过，恢复功能正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-17 10:30",
      "operationLog": "任务完成"
    },
    {
      "id": 8,
      "taskName": "会议室设备调试",
      "taskType": "日常运维",
      "assigner": "赵六",
      "assignTime": "2026-01-22 09:00",
      "deadline": "2026-01-22 12:00",
      "priority": "低",
      "description": "调试301会议室的音视频设备",
      "taskId": "TASK-20260122-008",
      "receiveStatus": "已认领",
      "relatedResource": "301会议室",
      "currentProgress": "100%",
      "startTime": "2026-01-22 09:30",
      "expectedFinishTime": "2026-01-22 11:30",
      "updateTime": "2026-01-22 11:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-22 11:00",
      "acceptResult": "通过",
      "executor": "李四",
      "attachment": "",
      "executionDuration": "1.5小时",
      "archiveTime": "2026-01-22 11:30",
      "acceptOpinion": "调试完成，设备正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "李四",
      "createTime": "2026-01-22 08:45",
      "operationLog": "任务完成"
    },
    {
      "id": 9,
      "taskName": "服务器巡检任务-02",
      "taskType": "巡检任务",
      "assigner": "张三",
      "assignTime": "2026-01-23 09:30",
      "deadline": "2026-01-26 18:00",
      "priority": "高",
      "description": "对机房服务器进行定期巡检，检查硬件状态、系统日志...",
      "taskId": "TASK-20260123-009",
      "receiveStatus": "已认领",
      "relatedResource": "服务器集群-B",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "王五",
      "createTime": "2026-01-23 09:00",
      "operationLog": "任务创建"
    },
    {
      "id": 10,
      "taskName": "数据库性能优化-02",
      "taskType": "项目任务",
      "assigner": "王五",
      "assignTime": "2026-01-24 14:00",
      "deadline": "2026-01-28 17:00",
      "priority": "中",
      "description": "对生产数据库进行性能优化，包括索引优化、查询调优等",
      "taskId": "TASK-20260124-010",
      "receiveStatus": "未认领",
      "relatedResource": "MySQL数据库-02",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "赵六,钱七",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "王五",
      "createTime": "2026-01-24 13:30",
      "operationLog": "任务创建"
    },
    {
      "id": 11,
      "taskName": "网络设备配置备份-02",
      "taskType": "日常运维",
      "assigner": "孙八",
      "assignTime": "2026-01-25 10:00",
      "deadline": "2026-01-28 12:00",
      "priority": "低",
      "description": "备份所有网络设备的配置文件",
      "taskId": "TASK-20260125-011",
      "receiveStatus": "已认领",
      "relatedResource": "核心交换机",
      "currentProgress": "70%",
      "startTime": "2026-01-25 11:00",
      "expectedFinishTime": "2026-01-28 10:00",
      "updateTime": "2026-01-26 09:45",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "王五",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "王五",
      "createTime": "2026-01-25 09:30",
      "operationLog": "任务认领"
    },
    {
      "id": 12,
      "taskName": "应用系统部署-02",
      "taskType": "项目任务",
      "assigner": "李四",
      "assignTime": "2026-01-26 13:00",
      "deadline": "2026-01-30 20:00",
      "priority": "高",
      "description": "部署新版应用系统到生产环境",
      "taskId": "TASK-20260126-012",
      "receiveStatus": "已认领",
      "relatedResource": "应用服务器集群",
      "currentProgress": "40%",
      "startTime": "2026-01-26 14:00",
      "expectedFinishTime": "2026-01-29 18:00",
      "updateTime": "2026-01-27 16:30",
      "delayStatus": "正常",
      "cooperators": "周五,吴九",
      "finishTime": "",
      "acceptResult": "",
      "executor": "赵六",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "赵六",
      "createTime": "2026-01-26 12:30",
      "operationLog": "进度更新"
    },
    {
      "id": 13,
      "taskName": "安全漏洞修复-02",
      "taskType": "故障处理",
      "assigner": "郑十",
      "assignTime": "2026-01-27 08:30",
      "deadline": "2026-01-28 12:00",
      "priority": "紧急",
      "description": "修复发现的高危安全漏洞",
      "taskId": "TASK-20260127-013",
      "receiveStatus": "已认领",
      "relatedResource": "Web服务器",
      "currentProgress": "60%",
      "startTime": "2026-01-27 09:00",
      "expectedFinishTime": "2026-01-28 11:00",
      "updateTime": "2026-01-27 16:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "钱七",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "钱七",
      "createTime": "2026-01-27 08:00",
      "operationLog": "任务认领"
    },
    {
      "id": 14,
      "taskName": "月度工作报告撰写-02",
      "taskType": "日常运维",
      "assigner": "李四",
      "assignTime": "",
      "deadline": "2026-01-30 17:00",
      "priority": "中",
      "description": "撰写1月份IT运维工作报告",
      "taskId": "TASK-20260128-014",
      "receiveStatus": "已认领",
      "relatedResource": "文档管理系统",
      "currentProgress": "20%",
      "startTime": "2026-01-28 09:00",
      "expectedFinishTime": "2026-01-30 18:00",
      "updateTime": "2026-01-29 14:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "孙八",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "李四",
      "remindCount": 2,
      "latestDynamic": "进度更新至20%",
      "operator": "孙八",
      "createTime": "2026-01-28 10:00",
      "operationLog": "任务发起"
    },
    {
      "id": 15,
      "taskName": "备份系统验证测试-02",
      "taskType": "巡检任务",
      "assigner": "周三",
      "assignTime": "2026-01-29 11:00",
      "deadline": "2026-02-01 17:00",
      "priority": "中",
      "description": "对备份系统进行恢复验证测试",
      "taskId": "TASK-20260129-015",
      "receiveStatus": "未认领",
      "relatedResource": "备份服务器",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-01-29 10:30",
      "operationLog": "任务创建"
    },
    {
      "id": 16,
      "taskName": "会议室设备调试-02",
      "taskType": "日常运维",
      "assigner": "赵六",
      "assignTime": "2026-01-30 09:00",
      "deadline": "2026-01-30 12:00",
      "priority": "低",
      "description": "调试302会议室的音视频设备",
      "taskId": "TASK-20260130-016",
      "receiveStatus": "已认领",
      "relatedResource": "302会议室",
      "currentProgress": "100%",
      "startTime": "2026-01-30 09:30",
      "expectedFinishTime": "2026-01-30 11:30",
      "updateTime": "2026-01-30 11:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-01-30 11:00",
      "acceptResult": "通过",
      "executor": "吴九",
      "attachment": "",
      "executionDuration": "1.5小时",
      "archiveTime": "2026-01-30 11:30",
      "acceptOpinion": "调试完成，设备正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "吴九",
      "createTime": "2026-01-30 08:45",
      "operationLog": "任务完成"
    },
    {
      "id": 17,
      "taskName": "服务器巡检任务-03",
      "taskType": "巡检任务",
      "assigner": "张三",
      "assignTime": "2026-01-31 09:30",
      "deadline": "2026-02-03 18:00",
      "priority": "高",
      "description": "对机房服务器进行定期巡检，检查硬件状态、系统日志...",
      "taskId": "TASK-20260131-017",
      "receiveStatus": "已认领",
      "relatedResource": "服务器集群-C",
      "currentProgress": "50%",
      "startTime": "2026-01-31 10:00",
      "expectedFinishTime": "2026-02-03 17:00",
      "updateTime": "2026-02-01 09:45",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "周五",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "周五",
      "createTime": "2026-01-31 09:00",
      "operationLog": "任务认领"
    },
    {
      "id": 18,
      "taskName": "数据库性能优化-03",
      "taskType": "项目任务",
      "assigner": "王五",
      "assignTime": "2026-02-01 14:00",
      "deadline": "2026-02-05 17:00",
      "priority": "中",
      "description": "对生产数据库进行性能优化，包括索引优化、查询调优等",
      "taskId": "TASK-20260201-018",
      "receiveStatus": "已认领",
      "relatedResource": "MySQL数据库-03",
      "currentProgress": "80%",
      "startTime": "2026-02-01 15:00",
      "expectedFinishTime": "2026-02-04 18:00",
      "updateTime": "2026-02-03 10:30",
      "delayStatus": "正常",
      "cooperators": "赵六,钱七",
      "finishTime": "",
      "acceptResult": "",
      "executor": "郑十",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "郑十",
      "createTime": "2026-02-01 13:30",
      "operationLog": "任务认领"
    },
    {
      "id": 19,
      "taskName": "网络设备配置备份-03",
      "taskType": "日常运维",
      "assigner": "孙八",
      "assignTime": "2026-02-02 10:00",
      "deadline": "2026-02-05 12:00",
      "priority": "低",
      "description": "备份所有网络设备的配置文件",
      "taskId": "TASK-20260202-019",
      "receiveStatus": "未认领",
      "relatedResource": "核心交换机",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-02-02 09:30",
      "operationLog": "任务创建"
    },
    {
      "id": 20,
      "taskName": "应用系统部署-03",
      "taskType": "项目任务",
      "assigner": "李四",
      "assignTime": "2026-02-03 13:00",
      "deadline": "2026-02-07 20:00",
      "priority": "高",
      "description": "部署新版应用系统到生产环境",
      "taskId": "TASK-20260203-020",
      "receiveStatus": "已认领",
      "relatedResource": "应用服务器集群",
      "currentProgress": "90%",
      "startTime": "2026-02-03 14:00",
      "expectedFinishTime": "2026-02-06 18:00",
      "updateTime": "2026-02-05 16:30",
      "delayStatus": "正常",
      "cooperators": "周五,吴九",
      "finishTime": "",
      "acceptResult": "",
      "executor": "张三",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "张三",
      "createTime": "2026-02-03 12:30",
      "operationLog": "进度更新"
    },
    {
      "id": 21,
      "taskName": "服务器巡检任务-04",
      "taskType": "巡检任务",
      "assigner": "张三",
      "assignTime": "2026-02-04 09:30",
      "deadline": "2026-02-07 18:00",
      "priority": "高",
      "description": "对机房服务器进行定期巡检，检查硬件状态、系统日志...",
      "taskId": "TASK-20260204-021",
      "receiveStatus": "已认领",
      "relatedResource": "服务器集群-D",
      "currentProgress": "100%",
      "startTime": "2026-02-04 10:00",
      "expectedFinishTime": "2026-02-07 17:00",
      "updateTime": "2026-02-07 16:30",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-02-07 16:30",
      "acceptResult": "通过",
      "executor": "王五",
      "attachment": "inspection_report.pdf",
      "executionDuration": "3天",
      "archiveTime": "2026-02-07 17:00",
      "acceptOpinion": "巡检完成，设备正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "王五",
      "createTime": "2026-02-04 09:00",
      "operationLog": "任务完成"
    },
    {
      "id": 22,
      "taskName": "数据库性能优化-04",
      "taskType": "项目任务",
      "assigner": "王五",
      "assignTime": "2026-02-05 14:00",
      "deadline": "2026-02-09 17:00",
      "priority": "中",
      "description": "对生产数据库进行性能优化，包括索引优化、查询调优等",
      "taskId": "TASK-20260205-022",
      "receiveStatus": "未认领",
      "relatedResource": "MySQL数据库-04",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "赵六,钱七",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-02-05 13:30",
      "operationLog": "任务创建"
    },
    {
      "id": 23,
      "taskName": "网络设备配置备份-04",
      "taskType": "日常运维",
      "assigner": "孙八",
      "assignTime": "2026-02-06 10:00",
      "deadline": "2026-02-09 12:00",
      "priority": "低",
      "description": "备份所有网络设备的配置文件",
      "taskId": "TASK-20260206-023",
      "receiveStatus": "已认领",
      "relatedResource": "核心交换机",
      "currentProgress": "100%",
      "startTime": "2026-02-06 11:00",
      "expectedFinishTime": "2026-02-09 10:00",
      "updateTime": "2026-02-09 09:45",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-02-09 09:45",
      "acceptResult": "通过",
      "executor": "赵六",
      "attachment": "backup_config_02.zip",
      "executionDuration": "3天",
      "archiveTime": "2026-02-09 10:00",
      "acceptOpinion": "备份完整，符合要求",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "赵六",
      "createTime": "2026-02-06 09:30",
      "operationLog": "任务完成"
    },
    {
      "id": 24,
      "taskName": "应用系统部署-04",
      "taskType": "项目任务",
      "assigner": "李四",
      "assignTime": "2026-02-07 13:00",
      "deadline": "2026-02-11 20:00",
      "priority": "高",
      "description": "部署新版应用系统到生产环境",
      "taskId": "TASK-20260207-024",
      "receiveStatus": "已认领",
      "relatedResource": "应用服务器集群",
      "currentProgress": "70%",
      "startTime": "2026-02-07 14:00",
      "expectedFinishTime": "2026-02-10 18:00",
      "updateTime": "2026-02-09 16:30",
      "delayStatus": "正常",
      "cooperators": "周五,吴九",
      "finishTime": "",
      "acceptResult": "",
      "executor": "钱七",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "钱七",
      "createTime": "2026-02-07 12:30",
      "operationLog": "进度更新"
    },
    {
      "id": 25,
      "taskName": "安全漏洞修复-03",
      "taskType": "故障处理",
      "assigner": "郑十",
      "assignTime": "2026-02-08 08:30",
      "deadline": "2026-02-09 12:00",
      "priority": "紧急",
      "description": "修复发现的高危安全漏洞",
      "taskId": "TASK-20260208-025",
      "receiveStatus": "已认领",
      "relatedResource": "Web服务器",
      "currentProgress": "100%",
      "startTime": "2026-02-08 09:00",
      "expectedFinishTime": "2026-02-09 11:00",
      "updateTime": "2026-02-09 10:30",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-02-09 10:30",
      "acceptResult": "通过",
      "executor": "孙八",
      "attachment": "patch_details.docx",
      "executionDuration": "1.5小时",
      "archiveTime": "2026-02-09 11:00",
      "acceptOpinion": "漏洞修复完成，测试通过",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "孙八",
      "createTime": "2026-02-08 08:00",
      "operationLog": "任务完成"
    },
    {
      "id": 26,
      "taskName": "月度工作报告撰写-03",
      "taskType": "日常运维",
      "assigner": "李四",
      "assignTime": "",
      "deadline": "2026-02-10 17:00",
      "priority": "中",
      "description": "撰写2月份IT运维工作报告",
      "taskId": "TASK-20260209-026",
      "receiveStatus": "已认领",
      "relatedResource": "文档管理系统",
      "currentProgress": "60%",
      "startTime": "2026-02-09 09:00",
      "expectedFinishTime": "2026-02-10 18:00",
      "updateTime": "2026-02-10 14:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "吴九",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "李四",
      "remindCount": 1,
      "latestDynamic": "进度更新至60%",
      "operator": "吴九",
      "createTime": "2026-02-09 10:00",
      "operationLog": "任务发起"
    },
    {
      "id": 27,
      "taskName": "备份系统验证测试-03",
      "taskType": "巡检任务",
      "assigner": "周三",
      "assignTime": "2026-02-10 11:00",
      "deadline": "2026-02-13 17:00",
      "priority": "中",
      "description": "对备份系统进行恢复验证测试",
      "taskId": "TASK-20260210-027",
      "receiveStatus": "未认领",
      "relatedResource": "备份服务器",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-02-10 10:30",
      "operationLog": "任务创建"
    },
    {
      "id": 28,
      "taskName": "会议室设备调试-03",
      "taskType": "日常运维",
      "assigner": "赵六",
      "assignTime": "2026-02-11 09:00",
      "deadline": "2026-02-11 12:00",
      "priority": "低",
      "description": "调试303会议室的音视频设备",
      "taskId": "TASK-20260211-028",
      "receiveStatus": "已认领",
      "relatedResource": "303会议室",
      "currentProgress": "100%",
      "startTime": "2026-02-11 09:30",
      "expectedFinishTime": "2026-02-11 11:30",
      "updateTime": "2026-02-11 11:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-02-11 11:00",
      "acceptResult": "通过",
      "executor": "周五",
      "attachment": "",
      "executionDuration": "1.5小时",
      "archiveTime": "2026-02-11 11:30",
      "acceptOpinion": "调试完成，设备正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "周五",
      "createTime": "2026-02-11 08:45",
      "operationLog": "任务完成"
    },
    {
      "id": 29,
      "taskName": "服务器巡检任务-05",
      "taskType": "巡检任务",
      "assigner": "张三",
      "assignTime": "2026-02-12 09:30",
      "deadline": "2026-02-15 18:00",
      "priority": "高",
      "description": "对机房服务器进行定期巡检，检查硬件状态、系统日志...",
      "taskId": "TASK-20260212-029",
      "receiveStatus": "已认领",
      "relatedResource": "服务器集群-E",
      "currentProgress": "30%",
      "startTime": "2026-02-12 10:00",
      "expectedFinishTime": "2026-02-15 17:00",
      "updateTime": "2026-02-13 09:45",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "郑十",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "郑十",
      "createTime": "2026-02-12 09:00",
      "operationLog": "任务认领"
    },
    {
      "id": 30,
      "taskName": "数据库性能优化-05",
      "taskType": "项目任务",
      "assigner": "王五",
      "assignTime": "2026-02-13 14:00",
      "deadline": "2026-02-17 17:00",
      "priority": "中",
      "description": "对生产数据库进行性能优化，包括索引优化、查询调优等",
      "taskId": "TASK-20260213-030",
      "receiveStatus": "已认领",
      "relatedResource": "MySQL数据库-05",
      "currentProgress": "90%",
      "startTime": "2026-02-13 15:00",
      "expectedFinishTime": "2026-02-16 18:00",
      "updateTime": "2026-02-16 10:30",
      "delayStatus": "正常",
      "cooperators": "赵六,钱七",
      "finishTime": "",
      "acceptResult": "",
      "executor": "张三",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "张三",
      "createTime": "2026-02-13 13:30",
      "operationLog": "任务认领"
    },
    {
      "id": 31,
      "taskName": "网络设备配置备份-05",
      "taskType": "日常运维",
      "assigner": "孙八",
      "assignTime": "2026-02-14 10:00",
      "deadline": "2026-02-17 12:00",
      "priority": "低",
      "description": "备份所有网络设备的配置文件",
      "taskId": "TASK-20260214-031",
      "receiveStatus": "未认领",
      "relatedResource": "核心交换机",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-02-14 09:30",
      "operationLog": "任务创建"
    },
    {
      "id": 32,
      "taskName": "应用系统部署-05",
      "taskType": "项目任务",
      "assigner": "李四",
      "assignTime": "2026-02-15 13:00",
      "deadline": "2026-02-19 20:00",
      "priority": "高",
      "description": "部署新版应用系统到生产环境",
      "taskId": "TASK-20260215-032",
      "receiveStatus": "已认领",
      "relatedResource": "应用服务器集群",
      "currentProgress": "100%",
      "startTime": "2026-02-15 14:00",
      "expectedFinishTime": "2026-02-18 18:00",
      "updateTime": "2026-02-18 17:30",
      "delayStatus": "正常",
      "cooperators": "周五,吴九",
      "finishTime": "2026-02-18 17:30",
      "acceptResult": "通过",
      "executor": "王五",
      "attachment": "deployment_report.pdf",
      "executionDuration": "3天",
      "archiveTime": "2026-02-18 18:00",
      "acceptOpinion": "部署成功，系统运行正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "王五",
      "createTime": "2026-02-15 12:30",
      "operationLog": "任务完成"
    },
    {
      "id": 33,
      "taskName": "安全漏洞修复-04",
      "taskType": "故障处理",
      "assigner": "郑十",
      "assignTime": "2026-02-16 08:30",
      "deadline": "2026-02-17 12:00",
      "priority": "紧急",
      "description": "修复发现的高危安全漏洞",
      "taskId": "TASK-20260216-033",
      "receiveStatus": "已认领",
      "relatedResource": "Web服务器",
      "currentProgress": "40%",
      "startTime": "2026-02-16 09:00",
      "expectedFinishTime": "2026-02-17 11:00",
      "updateTime": "2026-02-17 09:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "赵六",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "赵六",
      "createTime": "2026-02-16 08:00",
      "operationLog": "任务认领"
    },
    {
      "id": 34,
      "taskName": "月度工作报告撰写-04",
      "taskType": "日常运维",
      "assigner": "李四",
      "assignTime": "",
      "deadline": "2026-02-20 17:00",
      "priority": "中",
      "description": "撰写2月份IT运维工作报告",
      "taskId": "TASK-20260217-034",
      "receiveStatus": "已认领",
      "relatedResource": "文档管理系统",
      "currentProgress": "80%",
      "startTime": "2026-02-17 09:00",
      "expectedFinishTime": "2026-02-20 18:00",
      "updateTime": "2026-02-19 14:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "孙八",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "李四",
      "remindCount": 1,
      "latestDynamic": "进度更新至80%",
      "operator": "孙八",
      "createTime": "2026-02-17 10:00",
      "operationLog": "任务发起"
    },
    {
      "id": 35,
      "taskName": "备份系统验证测试-04",
      "taskType": "巡检任务",
      "assigner": "周三",
      "assignTime": "2026-02-18 11:00",
      "deadline": "2026-02-21 17:00",
      "priority": "中",
      "description": "对备份系统进行恢复验证测试",
      "taskId": "TASK-20260218-035",
      "receiveStatus": "未认领",
      "relatedResource": "备份服务器",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-02-18 10:30",
      "operationLog": "任务创建"
    },
    {
      "id": 36,
      "taskName": "会议室设备调试-04",
      "taskType": "日常运维",
      "assigner": "赵六",
      "assignTime": "2026-02-19 09:00",
      "deadline": "2026-02-19 12:00",
      "priority": "低",
      "description": "调试304会议室的音视频设备",
      "taskId": "TASK-20260219-036",
      "receiveStatus": "已认领",
      "relatedResource": "304会议室",
      "currentProgress": "100%",
      "startTime": "2026-02-19 09:30",
      "expectedFinishTime": "2026-02-19 11:30",
      "updateTime": "2026-02-19 11:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-02-19 11:00",
      "acceptResult": "通过",
      "executor": "吴九",
      "attachment": "",
      "executionDuration": "1.5小时",
      "archiveTime": "2026-02-19 11:30",
      "acceptOpinion": "调试完成，设备正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "吴九",
      "createTime": "2026-02-19 08:45",
      "operationLog": "任务完成"
    },
    {
      "id": 37,
      "taskName": "服务器巡检任务-06",
      "taskType": "巡检任务",
      "assigner": "张三",
      "assignTime": "2026-02-20 09:30",
      "deadline": "2026-02-23 18:00",
      "priority": "高",
      "description": "对机房服务器进行定期巡检，检查硬件状态、系统日志...",
      "taskId": "TASK-20260220-037",
      "receiveStatus": "已认领",
      "relatedResource": "服务器集群-F",
      "currentProgress": "70%",
      "startTime": "2026-02-20 10:00",
      "expectedFinishTime": "2026-02-23 17:00",
      "updateTime": "2026-02-22 09:45",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "周五",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "周五",
      "createTime": "2026-02-20 09:00",
      "operationLog": "任务认领"
    },
    {
      "id": 38,
      "taskName": "数据库性能优化-06",
      "taskType": "项目任务",
      "assigner": "王五",
      "assignTime": "2026-02-21 14:00",
      "deadline": "2026-02-25 17:00",
      "priority": "中",
      "description": "对生产数据库进行性能优化，包括索引优化、查询调优等",
      "taskId": "TASK-20260221-038",
      "receiveStatus": "已认领",
      "relatedResource": "MySQL数据库-06",
      "currentProgress": "100%",
      "startTime": "2026-02-21 15:00",
      "expectedFinishTime": "2026-02-24 18:00",
      "updateTime": "2026-02-24 17:30",
      "delayStatus": "正常",
      "cooperators": "赵六,钱七",
      "finishTime": "2026-02-24 17:30",
      "acceptResult": "通过",
      "executor": "郑十",
      "attachment": "optimization_report.pdf",
      "executionDuration": "3天",
      "archiveTime": "2026-02-24 18:00",
      "acceptOpinion": "优化完成，性能提升显著",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "郑十",
      "createTime": "2026-02-21 13:30",
      "operationLog": "任务完成"
    },
    {
      "id": 39,
      "taskName": "网络设备配置备份-06",
      "taskType": "日常运维",
      "assigner": "孙八",
      "assignTime": "2026-02-22 10:00",
      "deadline": "2026-02-25 12:00",
      "priority": "低",
      "description": "备份所有网络设备的配置文件",
      "taskId": "TASK-20260222-039",
      "receiveStatus": "未认领",
      "relatedResource": "核心交换机",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-02-22 09:30",
      "operationLog": "任务创建"
    },
    {
      "id": 40,
      "taskName": "应用系统部署-06",
      "taskType": "项目任务",
      "assigner": "李四",
      "assignTime": "2026-02-23 13:00",
      "deadline": "2026-02-27 20:00",
      "priority": "高",
      "description": "部署新版应用系统到生产环境",
      "taskId": "TASK-20260223-040",
      "receiveStatus": "已认领",
      "relatedResource": "应用服务器集群",
      "currentProgress": "50%",
      "startTime": "2026-02-23 14:00",
      "expectedFinishTime": "2026-02-26 18:00",
      "updateTime": "2026-02-25 16:30",
      "delayStatus": "正常",
      "cooperators": "周五,吴九",
      "finishTime": "",
      "acceptResult": "",
      "executor": "张三",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "张三",
      "createTime": "2026-02-23 12:30",
      "operationLog": "进度更新"
    },
    {
      "id": 41,
      "taskName": "安全漏洞修复-05",
      "taskType": "故障处理",
      "assigner": "郑十",
      "assignTime": "2026-02-24 08:30",
      "deadline": "2026-02-25 12:00",
      "priority": "紧急",
      "description": "修复发现的高危安全漏洞",
      "taskId": "TASK-20260224-041",
      "receiveStatus": "已认领",
      "relatedResource": "Web服务器",
      "currentProgress": "100%",
      "startTime": "2026-02-24 09:00",
      "expectedFinishTime": "2026-02-25 11:00",
      "updateTime": "2026-02-25 10:30",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-02-25 10:30",
      "acceptResult": "通过",
      "executor": "王五",
      "attachment": "security_patch.zip",
      "executionDuration": "1.5小时",
      "archiveTime": "2026-02-25 11:00",
      "acceptOpinion": "漏洞修复完成，测试通过",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "王五",
      "createTime": "2026-02-24 08:00",
      "operationLog": "任务完成"
    },
    {
      "id": 42,
      "taskName": "月度工作报告撰写-05",
      "taskType": "日常运维",
      "assigner": "李四",
      "assignTime": "",
      "deadline": "2026-02-27 17:00",
      "priority": "中",
      "description": "撰写2月份IT运维工作报告",
      "taskId": "TASK-20260225-042",
      "receiveStatus": "已认领",
      "relatedResource": "文档管理系统",
      "currentProgress": "100%",
      "startTime": "2026-02-25 09:00",
      "expectedFinishTime": "2026-02-27 18:00",
      "updateTime": "2026-02-27 16:30",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-02-27 16:30",
      "acceptResult": "通过",
      "executor": "赵六",
      "attachment": "monthly_report_feb.docx",
      "executionDuration": "2天",
      "archiveTime": "2026-02-27 17:00",
      "acceptOpinion": "报告内容完整，数据准确",
      "taskStatus": "已完成",
      "initiator": "李四",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "赵六",
      "createTime": "2026-02-25 10:00",
      "operationLog": "任务完成"
    },
    {
      "id": 43,
      "taskName": "备份系统验证测试-05",
      "taskType": "巡检任务",
      "assigner": "周三",
      "assignTime": "2026-02-26 11:00",
      "deadline": "2026-03-01 17:00",
      "priority": "中",
      "description": "对备份系统进行恢复验证测试",
      "taskId": "TASK-20260226-043",
      "receiveStatus": "未认领",
      "relatedResource": "备份服务器",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-02-26 10:30",
      "operationLog": "任务创建"
    },
    {
      "id": 44,
      "taskName": "会议室设备调试-05",
      "taskType": "日常运维",
      "assigner": "赵六",
      "assignTime": "2026-02-27 09:00",
      "deadline": "2026-02-27 12:00",
      "priority": "低",
      "description": "调试305会议室的音视频设备",
      "taskId": "TASK-20260227-044",
      "receiveStatus": "已认领",
      "relatedResource": "305会议室",
      "currentProgress": "100%",
      "startTime": "2026-02-27 09:30",
      "expectedFinishTime": "2026-02-27 11:30",
      "updateTime": "2026-02-27 11:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "2026-02-27 11:00",
      "acceptResult": "通过",
      "executor": "孙八",
      "attachment": "",
      "executionDuration": "1.5小时",
      "archiveTime": "2026-02-27 11:30",
      "acceptOpinion": "调试完成，设备正常",
      "taskStatus": "已完成",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "孙八",
      "createTime": "2026-02-27 08:45",
      "operationLog": "任务完成"
    },
    {
      "id": 45,
      "taskName": "服务器巡检任务-07",
      "taskType": "巡检任务",
      "assigner": "张三",
      "assignTime": "2026-02-28 09:30",
      "deadline": "2026-03-03 18:00",
      "priority": "高",
      "description": "对机房服务器进行定期巡检，检查硬件状态、系统日志...",
      "taskId": "TASK-20260228-045",
      "receiveStatus": "已认领",
      "relatedResource": "服务器集群-G",
      "currentProgress": "20%",
      "startTime": "2026-02-28 10:00",
      "expectedFinishTime": "2026-03-03 17:00",
      "updateTime": "2026-03-01 09:45",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "吴九",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "吴九",
      "createTime": "2026-02-28 09:00",
      "operationLog": "任务认领"
    },
    {
      "id": 46,
      "taskName": "数据库性能优化-07",
      "taskType": "项目任务",
      "assigner": "王五",
      "assignTime": "2026-03-01 14:00",
      "deadline": "2026-03-05 17:00",
      "priority": "中",
      "description": "对生产数据库进行性能优化，包括索引优化、查询调优等",
      "taskId": "TASK-20260301-046",
      "receiveStatus": "已认领",
      "relatedResource": "MySQL数据库-07",
      "currentProgress": "60%",
      "startTime": "2026-03-01 15:00",
      "expectedFinishTime": "2026-03-04 18:00",
      "updateTime": "2026-03-03 10:30",
      "delayStatus": "正常",
      "cooperators": "赵六,钱七",
      "finishTime": "",
      "acceptResult": "",
      "executor": "周五",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "周五",
      "createTime": "2026-03-01 13:30",
      "operationLog": "任务认领"
    },
    {
      "id": 47,
      "taskName": "网络设备配置备份-07",
      "taskType": "日常运维",
      "assigner": "孙八",
      "assignTime": "2026-03-02 10:00",
      "deadline": "2026-03-05 12:00",
      "priority": "低",
      "description": "备份所有网络设备的配置文件",
      "taskId": "TASK-20260302-047",
      "receiveStatus": "未认领",
      "relatedResource": "核心交换机",
      "currentProgress": "待处理",
      "startTime": "",
      "expectedFinishTime": "",
      "updateTime": "",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "待处理",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "",
      "createTime": "2026-03-02 09:30",
      "operationLog": "任务创建"
    },
    {
      "id": 48,
      "taskName": "应用系统部署-07",
      "taskType": "项目任务",
      "assigner": "李四",
      "assignTime": "2026-03-03 13:00",
      "deadline": "2026-03-07 20:00",
      "priority": "高",
      "description": "部署新版应用系统到生产环境",
      "taskId": "TASK-20260303-048",
      "receiveStatus": "已认领",
      "relatedResource": "应用服务器集群",
      "currentProgress": "30%",
      "startTime": "2026-03-03 14:00",
      "expectedFinishTime": "2026-03-06 18:00",
      "updateTime": "2026-03-05 16:30",
      "delayStatus": "正常",
      "cooperators": "周五,吴九",
      "finishTime": "",
      "acceptResult": "",
      "executor": "郑十",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "郑十",
      "createTime": "2026-03-03 12:30",
      "operationLog": "进度更新"
    },
    {
      "id": 49,
      "taskName": "安全漏洞修复-06",
      "taskType": "故障处理",
      "assigner": "郑十",
      "assignTime": "2026-03-04 08:30",
      "deadline": "2026-03-05 12:00",
      "priority": "紧急",
      "description": "修复发现的高危安全漏洞",
      "taskId": "TASK-20260304-049",
      "receiveStatus": "已认领",
      "relatedResource": "Web服务器",
      "currentProgress": "80%",
      "startTime": "2026-03-04 09:00",
      "expectedFinishTime": "2026-03-05 11:00",
      "updateTime": "2026-03-05 09:30",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "张三",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "",
      "remindCount": 0,
      "latestDynamic": "",
      "operator": "张三",
      "createTime": "2026-03-04 08:00",
      "operationLog": "任务认领"
    },
    {
      "id": 50,
      "taskName": "月度工作报告撰写-06",
      "taskType": "日常运维",
      "assigner": "李四",
      "assignTime": "",
      "deadline": "2026-03-06 17:00",
      "priority": "中",
      "description": "撰写3月份IT运维工作计划",
      "taskId": "TASK-20260305-050",
      "receiveStatus": "已认领",
      "relatedResource": "文档管理系统",
      "currentProgress": "10%",
      "startTime": "2026-03-05 09:00",
      "expectedFinishTime": "2026-03-06 18:00",
      "updateTime": "2026-03-05 14:00",
      "delayStatus": "正常",
      "cooperators": "",
      "finishTime": "",
      "acceptResult": "",
      "executor": "王五",
      "attachment": "",
      "executionDuration": "",
      "archiveTime": "",
      "acceptOpinion": "",
      "taskStatus": "处理中",
      "initiator": "李四",
      "remindCount": 0,
      "latestDynamic": "计划大纲完成",
      "operator": "王五",
      "createTime": "2026-03-05 10:00",
      "operationLog": "任务发起"
    }
  ];
};

/** 新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'taskName',
      label: '任务名称',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入任务名称',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '日常运维', value: '日常运维' },
          { label: '故障处理', value: '故障处理' },
          { label: '项目任务', value: '项目任务' },
          { label: '巡检任务', value: '巡检任务' },
          { label: '其他', value: '其他' },
        ],
        placeholder: '请选择任务类型',
        showSearch: true,
      },
      fieldName: 'taskType',
      label: '任务类型',
    },
    {
      fieldName: 'priority',
      label: '优先级',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '紧急', value: '紧急' },
          { label: '高', value: '高' },
          { label: '中', value: '中' },
          { label: '低', value: '低' },
        ],
        placeholder: '请选择优先级',
      },
      rules: 'required',
    },
    {
      fieldName: 'deadline',
      label: '截止时间',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'datetime',
        placeholder: '请选择截止时间',
      },
      rules: 'required',
    },
    {
      fieldName: 'description',
      label: '任务描述',
      component: 'Textarea',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入任务描述',
        rows: 3,
      },
    },
    {
      fieldName: 'assigner',
      label: '分配人',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入分配人',
      },
    },
    {
      fieldName: 'relatedResource',
      label: '关联资源',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入关联资源',
      },
    },
    {
      fieldName: 'taskStatus',
      label: '任务状态',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '待处理', value: '待处理' },
          { label: '处理中', value: '处理中' },
          { label: '已完成', value: '已完成' },
          { label: '已撤回', value: '已撤回' },
        ],
        placeholder: '请选择任务状态',
      },
    },
  ];
}

/** 表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'taskName',
      title: '任务名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'taskName' },
    },
    {
      field: 'taskType',
      title: '任务类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'priority',
      title: '优先级',
      minWidth: 80,
      sortable: true,
      slots: { default: 'priority' },
    },
    {
      field: 'assigner',
      title: '分配人',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'deadline',
      title: '截止时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'taskStatus',
      title: '任务状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'taskStatus' },
    },
    {
      field: 'currentProgress',
      title: '当前进度',
      minWidth: 100,
      sortable: true,
      slots: { default: 'progress' },
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑任务',
  addText: '新增任务',
  excelName: '任务列表',
  excelAllName: '任务数据.xlsx',
  total: '任务总数: 50; 待处理: 15; 处理中: 23; 已完成: 12; 我发起的：5;',
};
