/** 表格初始数据 - 窨井盖设施监测年报数据 */
export const dataList = () => [
  {
    areaName: '福州市鼓楼区',
    deptName: '福州市鼓楼区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 1500,
    yearTotalHiddenTroubleCount: 720,
    yearDisposalCompleteCount: 680,
    deviceYearOnlineRate: 97.2,
    yearMajorHiddenTroubleCount: 45,
    yearHiddenTroubleDisposalRate: 94.44,
    yearMajorHiddenTroubleDisposalRate: 100,
    yoyHiddenTroubleChangeRate: 10,
    yearOperationComprehensiveScore: 89.5,
    yearRepeatHiddenTroubleRate: 15.28,
  },
  {
    areaName: '厦门市思明区',
    deptName: '厦门市思明区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 2000,
    yearTotalHiddenTroubleCount: 360,
    yearDisposalCompleteCount: 360,
    deviceYearOnlineRate: 99.1,
    yearMajorHiddenTroubleCount: 18,
    yearHiddenTroubleDisposalRate: 100,
    yearMajorHiddenTroubleDisposalRate: 100,
    yoyHiddenTroubleChangeRate: -5,
    yearOperationComprehensiveScore: 96.8,
    yearRepeatHiddenTroubleRate: 8.33,
  },
  {
    areaName: '泉州市丰泽区',
    deptName: '泉州市丰泽区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 1800,
    yearTotalHiddenTroubleCount: 1080,
    yearDisposalCompleteCount: 850,
    deviceYearOnlineRate: 85.8,
    yearMajorHiddenTroubleCount: 108,
    yearHiddenTroubleDisposalRate: 78.70,
    yearMajorHiddenTroubleDisposalRate: 95.37,
    yoyHiddenTroubleChangeRate: 25,
    yearOperationComprehensiveScore: 72.3,
    yearRepeatHiddenTroubleRate: 22.22,
  },
  {
    areaName: '漳州市芗城区',
    deptName: '漳州市芗城区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 1200,
    yearTotalHiddenTroubleCount: 180,
    yearDisposalCompleteCount: 180,
    deviceYearOnlineRate: 98.9,
    yearMajorHiddenTroubleCount: 9,
    yearHiddenTroubleDisposalRate: 100,
    yearMajorHiddenTroubleDisposalRate: 100,
    yoyHiddenTroubleChangeRate: -15,
    yearOperationComprehensiveScore: 97.5,
    yearRepeatHiddenTroubleRate: 5.56,
  },
  {
    areaName: '莆田市城厢区',
    deptName: '莆田市城厢区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 1600,
    yearTotalHiddenTroubleCount: 900,
    yearDisposalCompleteCount: 750,
    deviceYearOnlineRate: 78.2,
    yearMajorHiddenTroubleCount: 90,
    yearHiddenTroubleDisposalRate: 83.33,
    yearMajorHiddenTroubleDisposalRate: 97.78,
    yoyHiddenTroubleChangeRate: 20,
    yearOperationComprehensiveScore: 78.6,
    yearRepeatHiddenTroubleRate: 18.89,
  },
  {
    areaName: '宁德市蕉城区',
    deptName: '宁德市蕉城区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 1400,
    yearTotalHiddenTroubleCount: 300,
    yearDisposalCompleteCount: 285,
    deviceYearOnlineRate: 97.5,
    yearMajorHiddenTroubleCount: 15,
    yearHiddenTroubleDisposalRate: 95,
    yearMajorHiddenTroubleDisposalRate: 100,
    yoyHiddenTroubleChangeRate: 5,
    yearOperationComprehensiveScore: 92.4,
    yearRepeatHiddenTroubleRate: 12,
  },
  {
    areaName: '龙岩市新罗区',
    deptName: '龙岩市新罗区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 1700,
    yearTotalHiddenTroubleCount: 720,
    yearDisposalCompleteCount: 630,
    deviceYearOnlineRate: 96.8,
    yearMajorHiddenTroubleCount: 54,
    yearHiddenTroubleDisposalRate: 87.5,
    yearMajorHiddenTroubleDisposalRate: 98.15,
    yoyHiddenTroubleChangeRate: 15,
    yearOperationComprehensiveScore: 85.7,
    yearRepeatHiddenTroubleRate: 16.67,
  },
  {
    areaName: '三明市梅列区',
    deptName: '三明市梅列区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 1300,
    yearTotalHiddenTroubleCount: 120,
    yearDisposalCompleteCount: 120,
    deviceYearOnlineRate: 98.8,
    yearMajorHiddenTroubleCount: 6,
    yearHiddenTroubleDisposalRate: 100,
    yearMajorHiddenTroubleDisposalRate: 100,
    yoyHiddenTroubleChangeRate: -10,
    yearOperationComprehensiveScore: 95.2,
    yearRepeatHiddenTroubleRate: 8.33,
  },
  {
    areaName: '南平市延平区',
    deptName: '南平市延平区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 1500,
    yearTotalHiddenTroubleCount: 540,
    yearDisposalCompleteCount: 480,
    deviceYearOnlineRate: 88.5,
    yearMajorHiddenTroubleCount: 36,
    yearHiddenTroubleDisposalRate: 88.89,
    yearMajorHiddenTroubleDisposalRate: 97.22,
    yoyHiddenTroubleChangeRate: 12,
    yearOperationComprehensiveScore: 82.8,
    yearRepeatHiddenTroubleRate: 18.52,
  },
  {
    areaName: '平潭综合实验区',
    deptName: '平潭综合实验区市政管理处',
    yearStatisticsPeriod: '2024年度',
    manholeTotalCount: 1100,
    yearTotalHiddenTroubleCount: 144,
    yearDisposalCompleteCount: 144,
    deviceYearOnlineRate: 99.4,
    yearMajorHiddenTroubleCount: 7,
    yearHiddenTroubleDisposalRate: 100,
    yearMajorHiddenTroubleDisposalRate: 100,
    yoyHiddenTroubleChangeRate: -8,
    yearOperationComprehensiveScore: 94.9,
    yearRepeatHiddenTroubleRate: 13.89,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施监测年报表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'deptName',
      label: '责任单位',
      component: 'Input',
      componentProps: {
        placeholder: '请输入责任单位',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'yearStatisticsPeriod',
      label: '年度统计时段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入年度统计时段（如：2024年度）',
        maxlength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 年度统计时段为必填项
    },
  ];
}

/** 表格字段 - 窨井盖设施监测年报表格列 */
export function useGridColumns() {
  return [
    {
      field: 'areaName',
      title: '所属区域',
      minWidth: 180,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'deptName',
      title: '责任单位',
      minWidth: 180,
      sortable: true,
      slots: { default: 'deptName' },
    },
    {
      field: 'yearStatisticsPeriod',
      title: '年度统计时段',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'manholeTotalCount',
      title: '窨井盖总数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'yearTotalHiddenTroubleCount',
      title: '年度累计隐患数',
      minWidth: 140,
      sortable: true,
      slots: { default: 'yearTotalHiddenTroubleCount' },
    },
    {
      field: 'yearDisposalCompleteCount',
      title: '年度处置完成数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deviceYearOnlineRate',
      title: '设备年度在线率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yearMajorHiddenTroubleCount',
      title: '年度重大隐患数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'yearHiddenTroubleDisposalRate',
      title: '年度隐患处置完成率(%)',
      minWidth: 180,
      sortable: true,
      slots: { default: 'yearHiddenTroubleDisposalRate' },
    },
    {
      field: 'yearMajorHiddenTroubleDisposalRate',
      title: '年度重大隐患处置率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yoyHiddenTroubleChangeRate',
      title: '同比隐患变化率(%)',
      minWidth: 160,
      sortable: true,
      slots: { default: 'yoyHiddenTroubleChangeRate' },
    },
    {
      field: 'yearOperationComprehensiveScore',
      title: '年度运维综合得分',
      minWidth: 160,
      sortable: true,
      slots: { default: 'yearOperationComprehensiveScore' },
    },
    {
      field: 'yearRepeatHiddenTroubleRate',
      title: '年度重复隐患率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      title: '操作',
      width: 240,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
