/** 表格初始数据 - 改造为道路监测周度统计分析数据 */
export const dataList = () => [
  {
    roadSectionName: '福州市鼓楼区杨桥东路（东街口-五一广场）',
    potholeCountWeekAvg: 5.6,
    crackLengthWeekAvg: 9.5,
    weekTotalWarningCount: 7,
    weekWorkOrderDisposalEfficiency: 92.5,
    workOrderTimeoutRate: 8.3,
    deviceWeekOnlineRate: 98.2,
    weekComplianceRate: 89,
    potholeCountMomChangeRate: 7.8,
    potholeCountYoYChangeRate: 12.5,
    crackLengthMomChangeRate: -3.2,
    crackLengthYoYChangeRate: 5.8,
    warningTypeDistribution:
      '坑洼超标: 4次；裂缝超标: 2次；流量超标: 1次；温度超标: 0次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    roadSectionName: '厦门市思明区鹭江道（轮渡码头-中山路）',
    potholeCountWeekAvg: 2.3,
    crackLengthWeekAvg: 3.6,
    weekTotalWarningCount: 3,
    weekWorkOrderDisposalEfficiency: 98,
    workOrderTimeoutRate: 2,
    deviceWeekOnlineRate: 99.5,
    weekComplianceRate: 95.5,
    potholeCountMomChangeRate: -4.8,
    potholeCountYoYChangeRate: -8.2,
    crackLengthMomChangeRate: 2.1,
    crackLengthYoYChangeRate: -1.5,
    warningTypeDistribution:
      '坑洼超标: 0次；裂缝超标: 0次；流量超标: 2次；温度超标: 1次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    roadSectionName: '泉州市丰泽区刺桐路（湖心街-泉秀街）',
    potholeCountWeekAvg: 11.8,
    crackLengthWeekAvg: 18.1,
    weekTotalWarningCount: 15,
    weekWorkOrderDisposalEfficiency: 75,
    workOrderTimeoutRate: 25,
    deviceWeekOnlineRate: 86.8,
    weekComplianceRate: 65.5,
    potholeCountMomChangeRate: 24.5,
    potholeCountYoYChangeRate: 30.8,
    crackLengthMomChangeRate: 19.2,
    crackLengthYoYChangeRate: 22.5,
    warningTypeDistribution:
      '坑洼超标: 8次；裂缝超标: 6次；流量超标: 1次；温度超标: 0次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    roadSectionName: '漳州市芗城区胜利路（延安北路-新华西路）',
    potholeCountWeekAvg: 0.4,
    crackLengthWeekAvg: 1.3,
    weekTotalWarningCount: 0,
    weekWorkOrderDisposalEfficiency: 0,
    workOrderTimeoutRate: 0,
    deviceWeekOnlineRate: 99.1,
    weekComplianceRate: 100,
    potholeCountMomChangeRate: -9.5,
    potholeCountYoYChangeRate: -15,
    crackLengthMomChangeRate: -7.8,
    crackLengthYoYChangeRate: -10.5,
    warningTypeDistribution:
      '坑洼超标: 0次；裂缝超标: 0次；流量超标: 0次；温度超标: 0次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    roadSectionName: '莆田市城厢区荔城南大道（凤凰山-万达广场）',
    potholeCountWeekAvg: 7.9,
    crackLengthWeekAvg: 14.5,
    weekTotalWarningCount: 9,
    weekWorkOrderDisposalEfficiency: 82.5,
    workOrderTimeoutRate: 17.5,
    deviceWeekOnlineRate: 79.2,
    weekComplianceRate: 78,
    potholeCountMomChangeRate: 11.8,
    potholeCountYoYChangeRate: 18.5,
    crackLengthMomChangeRate: 10.5,
    crackLengthYoYChangeRate: 15.2,
    warningTypeDistribution:
      '坑洼超标: 4次；裂缝超标: 3次；流量超标: 1次；温度超标: 1次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    roadSectionName: '宁德市蕉城区闽东中路（市政府-万达广场）',
    potholeCountWeekAvg: 5.1,
    crackLengthWeekAvg: 8,
    weekTotalWarningCount: 4,
    weekWorkOrderDisposalEfficiency: 95,
    workOrderTimeoutRate: 5,
    deviceWeekOnlineRate: 98,
    weekComplianceRate: 92.5,
    potholeCountMomChangeRate: 5.2,
    potholeCountYoYChangeRate: 8.8,
    crackLengthMomChangeRate: -1.5,
    crackLengthYoYChangeRate: 2.3,
    warningTypeDistribution:
      '坑洼超标: 2次；裂缝超标: 2次；流量超标: 0次；温度超标: 0次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    roadSectionName: '龙岩市新罗区龙川路（中山路-登高西路）',
    potholeCountWeekAvg: 9.9,
    crackLengthWeekAvg: 14.8,
    weekTotalWarningCount: 11,
    weekWorkOrderDisposalEfficiency: 88,
    workOrderTimeoutRate: 12,
    deviceWeekOnlineRate: 97,
    weekComplianceRate: 85,
    potholeCountMomChangeRate: 19,
    potholeCountYoYChangeRate: 25.5,
    crackLengthMomChangeRate: 13,
    crackLengthYoYChangeRate: 18.8,
    warningTypeDistribution:
      '坑洼超标: 5次；裂缝超标: 4次；流量超标: 1次；温度超标: 1次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    roadSectionName: '三明市梅列区列东街（东新四路-东新六路）',
    potholeCountWeekAvg: 4.3,
    crackLengthWeekAvg: 6.7,
    weekTotalWarningCount: 2,
    weekWorkOrderDisposalEfficiency: 100,
    workOrderTimeoutRate: 0,
    deviceWeekOnlineRate: 99,
    weekComplianceRate: 94,
    potholeCountMomChangeRate: -4.2,
    potholeCountYoYChangeRate: -6.5,
    crackLengthMomChangeRate: -5,
    crackLengthYoYChangeRate: -8.2,
    warningTypeDistribution:
      '坑洼超标: 0次；裂缝超标: 0次；流量超标: 2次；温度超标: 0次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    roadSectionName: '南平市延平区八一路（江滨路-中山路）',
    potholeCountWeekAvg: 7.3,
    crackLengthWeekAvg: 11,
    weekTotalWarningCount: 8,
    weekWorkOrderDisposalEfficiency: 78.5,
    workOrderTimeoutRate: 21.5,
    deviceWeekOnlineRate: 89.5,
    weekComplianceRate: 80.5,
    potholeCountMomChangeRate: 10.2,
    potholeCountYoYChangeRate: 15.8,
    crackLengthMomChangeRate: 7.8,
    crackLengthYoYChangeRate: 11.5,
    warningTypeDistribution:
      '坑洼超标: 3次；裂缝超标: 2次；流量超标: 2次；温度超标: 1次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    roadSectionName: '平潭综合实验区金井大道（管委会-龙凤头沙滩）',
    potholeCountWeekAvg: 1.1,
    crackLengthWeekAvg: 3,
    weekTotalWarningCount: 4,
    weekWorkOrderDisposalEfficiency: 99,
    workOrderTimeoutRate: 1,
    deviceWeekOnlineRate: 99.8,
    weekComplianceRate: 96,
    potholeCountMomChangeRate: -2.8,
    potholeCountYoYChangeRate: -5.5,
    crackLengthMomChangeRate: 4,
    crackLengthYoYChangeRate: 1.8,
    warningTypeDistribution:
      '坑洼超标: 0次；裂缝超标: 0次；流量超标: 0次；温度超标: 4次',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为道路监测周度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'roadSectionName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
      },
      labelWidth: '130',
      rules: 'required', // 路段名称为必填项
    },
    {
      fieldName: 'potholeCountWeekAvg',
      label: '坑洼数量周均值',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入坑洼数量周均值',
        min: 0,
        precision: 1, // 保留1位小数，贴合周均值统计场景
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthWeekAvg',
      label: '裂缝长度周均值',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入裂缝长度周均值（单位：米）',
        min: 0,
        precision: 1,
        addonAfter: '米',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekTotalWarningCount',
      label: '周累计预警数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周累计预警数',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekWorkOrderDisposalEfficiency',
      label: '周工单处置效率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周工单处置效率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'workOrderTimeoutRate',
      label: '工单超时率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入工单超时率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceWeekOnlineRate',
      label: '设备周在线率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入设备周在线率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekComplianceRate',
      label: '周达标率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周达标率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountMomChangeRate',
      label: '坑洼数量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入坑洼数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountYoYChangeRate',
      label: '坑洼数量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入坑洼数量同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthMomChangeRate',
      label: '裂缝长度环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入裂缝长度环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthYoYChangeRate',
      label: '裂缝长度同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入裂缝长度同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'warningTypeDistribution',
      label: '预警类型分布',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入预警类型分布（如：坑洼超标:4次；裂缝超标:2次）',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'weekStatisticsPeriod',
      label: '周统计时段',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周统计时段（如：2024-06-17 ~ 2024-06-23）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为道路监测周度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'roadSectionName',
      title: '路段名称',
      minWidth: 220,
      sortable: true,
      slots: { default: 'roadSectionName' },
    },
    {
      field: 'potholeCountWeekAvg',
      title: '坑洼数量周均值',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'crackLengthWeekAvg',
      title: '裂缝长度周均值(米)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'weekTotalWarningCount',
      title: '周累计预警数',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'weekWorkOrderDisposalEfficiency',
      title: '周工单处置效率(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'workOrderTimeoutRate',
      title: '工单超时率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'deviceWeekOnlineRate',
      title: '设备周在线率(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'weekComplianceRate',
      title: '周达标率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'potholeCountMomChangeRate',
      title: '坑洼数量环比变化率(%)',
      minWidth: 170,
      sortable: true,
    },
    {
      field: 'potholeCountYoYChangeRate',
      title: '坑洼数量同比变化率(%)',
      minWidth: 170,
      sortable: true,
    },
    {
      field: 'crackLengthMomChangeRate',
      title: '裂缝长度环比变化率(%)',
      minWidth: 170,
      sortable: true,
    },
    {
      field: 'crackLengthYoYChangeRate',
      title: '裂缝长度同比变化率(%)',
      minWidth: 170,
      sortable: true,
    },
    {
      field: 'warningTypeDistribution',
      title: '预警类型分布',
      minWidth: 230,
      sortable: false,
    },
    {
      field: 'weekStatisticsPeriod',
      title: '周统计时段',
      minWidth: 190,
      sortable: false,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
