export const pageConfig = {
  apiName: 'StationInfo',
  title: '场站信息',
  exportName: '场站信息数据.xlsx',
  importTemplateName: '场站信息导入模板.xlsx',
  nameField: 'name',
  primaryField: 'stationNo',
  toolbar: ['create', 'import', 'export'],
  rowActionMap: {
    未生效: ['enable', 'edit', 'detail'],
    已生效: ['disable', 'edit', 'detail'],
    已禁用: ['enable', 'detail'],
  },
  chart: {
    cards: [
      ['totalStationCount', '总场站数', 'all'],
      ['normalOperateCount', '正常运营数', '已生效'],
    ],
    bar: ['typeCountBarList', 'name', 'value', '各类型场站数量', 'type'],
    map: true,
  },
};

const stationTypeOptions = ['公共', '商业', '小区', '产业'];
const operateTypeOptions = [
  '直接管理',
  '甲方代运营',
  '本地化部署',
  '横向对接',
  '数据互通',
];
const statusOptions = ['未生效', '已生效', '已禁用'];

export const searchFields = [
  { field: 'stationNo', label: '场站编号', type: 'input', required: false },
  { field: 'name', label: '场站名称', type: 'input', required: false },
  {
    field: 'type',
    label: '场站类型',
    type: 'select',
    options: stationTypeOptions,
    required: false,
  },
  { field: 'address', label: '场站地址', type: 'input', required: false },
  {
    field: 'areaId',
    label: '所属片区',
    type: 'select',
    options: [],
    required: false,
    apiSource: 'AreaInfo',
  },
  {
    field: 'operateType',
    label: '运营类型',
    type: 'select',
    options: operateTypeOptions,
    required: false,
  },
  { field: 'userId', label: '负责人', type: 'number', required: false },
  {
    field: 'status',
    label: '状态',
    type: 'select',
    options: statusOptions,
    required: false,
  },
];

export const formFields = [
  { field: 'stationNo', label: '场站编号', type: 'input', required: true },
  { field: 'name', label: '场站名称', type: 'input', required: true },
  {
    field: 'type',
    label: '场站类型',
    type: 'select',
    options: stationTypeOptions,
    required: true,
  },
  { field: 'address', label: '场站地址', type: 'input', required: true },
  { field: 'spaceTotal', label: '泊位总数', type: 'number', required: true },
  { field: 'userId', label: '负责人', type: 'number', required: true },
  {
    field: 'feeStandard',
    label: '场站收费标准',
    type: 'input',
    required: false,
  },
  {
    field: 'areaId',
    label: '所属片区',
    type: 'select',
    options: [],
    required: false,
    apiSource: 'AreaInfo',
  },
  {
    field: 'operateType',
    label: '运营类型',
    type: 'select',
    options: operateTypeOptions,
    required: true,
  },
  { field: 'remark', label: '备注', type: 'textarea', required: false },
];

export const tableColumns = [
  { field: 'stationNo', label: '场站编号', minWidth: 140, drillType: 'detail' },
  { field: 'name', label: '场站名称', minWidth: 180 },
  {
    field: 'areaId',
    label: '所属片区',
    minWidth: 140,
    displayField: 'areaName',
    drillType: 'areaDetail',
    drillLabel: '所属片区详情',
  },
  {
    field: 'type',
    label: '场站类型',
    minWidth: 120,
    drillType: 'filter',
    options: stationTypeOptions,
  },
  { field: 'address', label: '场站地址', minWidth: 220 },
  {
    field: 'spaceTotal',
    label: '泊位总数',
    minWidth: 140,
    drillType: 'spaceList',
    drillLabel: '该场站车位列表',
  },
  { field: 'userId', label: '负责人', minWidth: 140, drillType: 'filter' },
  { field: 'feeStandard', label: '场站收费标准', minWidth: 150 },
  {
    field: 'operateType',
    label: '运营类型',
    minWidth: 120,
    drillType: 'filter',
    options: operateTypeOptions,
  },
  {
    field: 'deviceCount',
    label: '设备绑定数',
    minWidth: 100,
    drillType: 'deviceList',
    drillLabel: '该场站关联设备列表',
  },
  {
    field: 'spaceCount',
    label: '车位绑定数',
    minWidth: 100,
    drillType: 'spaceList',
    drillLabel: '该场站下属车位列表',
  },
  {
    field: 'status',
    label: '状态',
    minWidth: 120,
    drillType: 'filter',
    options: statusOptions,
  },
  {
    field: 'bindTime',
    label: '绑定时间',
    minWidth: 180,
    formatter: 'formatDateTime',
  },
  { field: 'bindUserId', label: '绑定人', minWidth: 120, drillType: 'filter' },
  { field: 'remark', label: '备注', minWidth: 150 },
  { field: 'creator', label: '创建者', minWidth: 120 },
  {
    field: 'createTime',
    label: '创建时间',
    minWidth: 180,
    formatter: 'formatDateTime',
  },
  { field: 'updater', label: '更新者', minWidth: 120 },
  {
    field: 'updateTime',
    label: '更新时间',
    minWidth: 180,
    formatter: 'formatDateTime',
  },
];

export const detailFields = [
  { key: 'stationNo', label: '场站编号', section: '基础信息' },
  { key: 'name', label: '场站名称', section: '基础信息' },
  { key: 'type', label: '场站类型', section: '基础信息' },
  { key: 'address', label: '场站地址', section: '基础信息' },
  { key: 'spaceTotal', label: '泊位总数', section: '运营配置' },
  { key: 'userId', label: '负责人', section: '运营配置' },
  { key: 'feeStandard', label: '场站收费标准', section: '运营配置' },
  { key: 'areaName', label: '所属片区', section: '运营配置' },
  { key: 'operateType', label: '运营类型', section: '运营配置' },
  { key: 'status', label: '状态', section: '状态信息' },
  {
    key: 'bindTime',
    label: '绑定时间',
    section: '状态信息',
    formatter: 'formatDateTime',
  },
  { key: 'bindUserId', label: '绑定人', section: '状态信息' },
  { key: 'deviceCount', label: '设备绑定数', section: '运营配置' },
  { key: 'spaceCount', label: '车位绑定数', section: '运营配置' },
  { key: 'remark', label: '备注', section: '运营配置' },
  { key: 'creator', label: '创建者', section: '审计信息' },
  {
    key: 'createTime',
    label: '创建时间',
    section: '审计信息',
    formatter: 'formatDateTime',
  },
  { key: 'updater', label: '更新者', section: '审计信息' },
  {
    key: 'updateTime',
    label: '更新时间',
    section: '审计信息',
    formatter: 'formatDateTime',
  },
];
