/** 表格初始数据 - 窨井盖设施监测日报数据 */
export const dataList = () => [
  {
    roadName: '福州市鼓楼区杨桥东路',
    areaName: '福州市鼓楼区',
    manholeTotalCount: 150,
    normalManholeCount: 145,
    hiddenTroubleManholeCount: 5,
    dayNewHiddenTroubleCount: 2,
    dayDisposalCompleteCount: 2,
    deviceOnlineRate: 98.5,
    deptName: '福州市鼓楼区市政管理处',
    hiddenTroubleRate: 3.33,
    dayDisposalCompleteRate: 100,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '低',
    unDisposedHiddenTroubleCount: 0,
  },
  {
    roadName: '厦门市思明区鹭江道',
    areaName: '厦门市思明区',
    manholeTotalCount: 200,
    normalManholeCount: 195,
    hiddenTroubleManholeCount: 5,
    dayNewHiddenTroubleCount: 1,
    dayDisposalCompleteCount: 1,
    deviceOnlineRate: 99.2,
    deptName: '厦门市思明区市政管理处',
    hiddenTroubleRate: 2.5,
    dayDisposalCompleteRate: 100,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '低',
    unDisposedHiddenTroubleCount: 0,
  },
  {
    roadName: '泉州市丰泽区刺桐路',
    areaName: '泉州市丰泽区',
    manholeTotalCount: 180,
    normalManholeCount: 165,
    hiddenTroubleManholeCount: 15,
    dayNewHiddenTroubleCount: 5,
    dayDisposalCompleteCount: 3,
    deviceOnlineRate: 85.3,
    deptName: '泉州市丰泽区市政管理处',
    hiddenTroubleRate: 8.33,
    dayDisposalCompleteRate: 60,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '高',
    unDisposedHiddenTroubleCount: 2,
  },
  {
    roadName: '漳州市芗城区胜利路',
    areaName: '漳州市芗城区',
    manholeTotalCount: 120,
    normalManholeCount: 118,
    hiddenTroubleManholeCount: 2,
    dayNewHiddenTroubleCount: 0,
    dayDisposalCompleteCount: 0,
    deviceOnlineRate: 99,
    deptName: '漳州市芗城区市政管理处',
    hiddenTroubleRate: 1.67,
    dayDisposalCompleteRate: 0,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '低',
    unDisposedHiddenTroubleCount: 0,
  },
  {
    roadName: '莆田市城厢区荔城南大道',
    areaName: '莆田市城厢区',
    manholeTotalCount: 160,
    normalManholeCount: 148,
    hiddenTroubleManholeCount: 12,
    dayNewHiddenTroubleCount: 4,
    dayDisposalCompleteCount: 3,
    deviceOnlineRate: 78.6,
    deptName: '莆田市城厢区市政管理处',
    hiddenTroubleRate: 7.5,
    dayDisposalCompleteRate: 75,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '中',
    unDisposedHiddenTroubleCount: 1,
  },
  {
    roadName: '宁德市蕉城区闽东中路',
    areaName: '宁德市蕉城区',
    manholeTotalCount: 140,
    normalManholeCount: 137,
    hiddenTroubleManholeCount: 3,
    dayNewHiddenTroubleCount: 1,
    dayDisposalCompleteCount: 1,
    deviceOnlineRate: 97.8,
    deptName: '宁德市蕉城区市政管理处',
    hiddenTroubleRate: 2.14,
    dayDisposalCompleteRate: 100,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '低',
    unDisposedHiddenTroubleCount: 0,
  },
  {
    roadName: '龙岩市新罗区龙川路',
    areaName: '龙岩市新罗区',
    manholeTotalCount: 170,
    normalManholeCount: 158,
    hiddenTroubleManholeCount: 12,
    dayNewHiddenTroubleCount: 3,
    dayDisposalCompleteCount: 2,
    deviceOnlineRate: 96.5,
    deptName: '龙岩市新罗区市政管理处',
    hiddenTroubleRate: 7.06,
    dayDisposalCompleteRate: 66.67,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '中',
    unDisposedHiddenTroubleCount: 1,
  },
  {
    roadName: '三明市梅列区列东街',
    areaName: '三明市梅列区',
    manholeTotalCount: 130,
    normalManholeCount: 128,
    hiddenTroubleManholeCount: 2,
    dayNewHiddenTroubleCount: 0,
    dayDisposalCompleteCount: 0,
    deviceOnlineRate: 98.9,
    deptName: '三明市梅列区市政管理处',
    hiddenTroubleRate: 1.54,
    dayDisposalCompleteRate: 0,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '低',
    unDisposedHiddenTroubleCount: 0,
  },
  {
    roadName: '南平市延平区八一路',
    areaName: '南平市延平区',
    manholeTotalCount: 150,
    normalManholeCount: 140,
    hiddenTroubleManholeCount: 10,
    dayNewHiddenTroubleCount: 2,
    dayDisposalCompleteCount: 1,
    deviceOnlineRate: 88.7,
    deptName: '南平市延平区市政管理处',
    hiddenTroubleRate: 6.67,
    dayDisposalCompleteRate: 50,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '中',
    unDisposedHiddenTroubleCount: 1,
  },
  {
    roadName: '平潭综合实验区金井大道',
    areaName: '平潭综合实验区',
    manholeTotalCount: 110,
    normalManholeCount: 108,
    hiddenTroubleManholeCount: 2,
    dayNewHiddenTroubleCount: 1,
    dayDisposalCompleteCount: 1,
    deviceOnlineRate: 99.5,
    deptName: '平潭综合实验区市政管理处',
    hiddenTroubleRate: 1.82,
    dayDisposalCompleteRate: 100,
    dataStatisticsPeriod: '2024-06-15',
    highRiskAreaFlag: '低',
    unDisposedHiddenTroubleCount: 0,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施监测日报表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'roadName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'areaName',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'deptName',
      label: '责任单位',
      component: 'Input',
      componentProps: {
        placeholder: '请输入责任单位',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'dataStatisticsPeriod',
      label: '统计日期',
      component: 'Input',
      componentProps: {
        placeholder: '请输入统计日期（YYYY-MM-DD）',
        maxlength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 统计日期为必填项
    },
  ];
}

/** 表格字段 - 窨井盖设施监测日报表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'roadName',
      title: '路段名称',
      minWidth: 220,
      sortable: true,
      slots: { default: 'roadName' },
    },
    {
      field: 'areaName',
      title: '所属区域',
      minWidth: 180,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'manholeTotalCount',
      title: '窨井盖总数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'normalManholeCount',
      title: '正常状态井盖数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'hiddenTroubleManholeCount',
      title: '隐患井盖数',
      minWidth: 120,
      sortable: true,
      slots: { default: 'hiddenTroubleManholeCount' },
    },
    {
      field: 'dayNewHiddenTroubleCount',
      title: '当日新增隐患数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'dayDisposalCompleteCount',
      title: '当日处置完成数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deviceOnlineRate',
      title: '设备日在线率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deptName',
      title: '责任单位',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'hiddenTroubleRate',
      title: '隐患发生率(%)',
      minWidth: 140,
      sortable: true,
      slots: { default: 'hiddenTroubleRate' },
    },
    {
      field: 'dayDisposalCompleteRate',
      title: '当日处置完成率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'dataStatisticsPeriod',
      title: '数据统计时段',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'highRiskAreaFlag',
      title: '高风险区域标识',
      minWidth: 140,
      sortable: true,
      slots: { default: 'highRiskAreaFlag' },
    },
    {
      field: 'unDisposedHiddenTroubleCount',
      title: '未处置隐患数',
      minWidth: 140,
      sortable: true,
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
