/** 表格初始数据 - 改造为年度市容乱贴乱画统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    yearIllegalPostingCleanupTotal: 1200,
    yearCleanupCompletionRate: 95.5,
    yearIllegalNumberCleanupTotal: 300,
    yearAntiPasteFacilityInstallationTotal: 150,
    yearCityAppearanceCleanlinessScore: 89.2,
    yearOnYearIllegalPostingCleanupChangeRate: 5.3,
    yearOnYearCleanupCompletionRateChangeRate: 2.1,
    yearOnYearIllegalNumberCleanupChangeRate: -1.2,
    yearOnYearAntiPasteFacilityInstallationChangeRate: 10.5,
    yearOnYearCityAppearanceCleanlinessScoreChangeRate: 3.4,
    monthlyTrendData: '1月:100;2月:90;...;12月:130',
    facilityTypeData: '墙面:800;电线杆:300;其他:100',
    cleanlinessDimensionData: '优秀:400;良好:600;一般:200',
    yearStatisticsPeriod: '2023-01-01 ~ 2023-12-31',
  },
  {
    areaName: '台江区',
    yearIllegalPostingCleanupTotal: 980,
    yearCleanupCompletionRate: 93.8,
    yearIllegalNumberCleanupTotal: 250,
    yearAntiPasteFacilityInstallationTotal: 130,
    yearCityAppearanceCleanlinessScore: 87.5,
    yearOnYearIllegalPostingCleanupChangeRate: 3.2,
    yearOnYearCleanupCompletionRateChangeRate: 1.5,
    yearOnYearIllegalNumberCleanupChangeRate: -0.8,
    yearOnYearAntiPasteFacilityInstallationChangeRate: 8.3,
    yearOnYearCityAppearanceCleanlinessScoreChangeRate: 2.1,
    monthlyTrendData: '1月:85;2月:80;...;12月:120',
    facilityTypeData: '墙面:600;电线杆:280;其他:100',
    cleanlinessDimensionData: '优秀:350;良好:500;一般:130',
    yearStatisticsPeriod: '2023-01-01 ~ 2023-12-31',
  },
  // ... 其他区域数据
];

/** 新增/修改的表单/列表的搜索表单 - 改造为年度市容乱贴乱画统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'yearIllegalPostingCleanupTotal',
      label: '年度乱贴乱画点位处置总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入年度乱贴乱画点位处置总量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'yearCleanupCompletionRate',
      label: '年度清理完成率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入年度清理完成率',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearIllegalNumberCleanupTotal',
      label: '年度非法号码处置总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入年度非法号码处置总量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'yearAntiPasteFacilityInstallationTotal',
      label: '年度防粘贴设施安装总数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入年度防粘贴设施安装总数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'yearCityAppearanceCleanlinessScore',
      label: '年度市容整洁度评分',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入年度市容整洁度评分',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearIllegalPostingCleanupChangeRate',
      label: '乱贴乱画同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入乱贴乱画同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearCleanupCompletionRateChangeRate',
      label: '清理完成率同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入清理完成率同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearIllegalNumberCleanupChangeRate',
      label: '非法号码同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入非法号码同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearAntiPasteFacilityInstallationChangeRate',
      label: '防粘贴设施同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入防粘贴设施同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yearOnYearCityAppearanceCleanlinessScoreChangeRate',
      label: '市容整洁度同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入市容整洁度同比变化率',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyTrendData',
      label: '月度趋势数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入月度趋势数据（如：1月:100;2月:90;...;12月:130）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'facilityTypeData',
      label: '设施类型数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入设施类型数据（如：墙面:800;电线杆:300;其他:100）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'cleanlinessDimensionData',
      label: '整洁度维度数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入整洁度维度数据（如：优秀:400;良好:600;一般:200）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'yearStatisticsPeriod',
      label: '年度统计时段',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入年度统计时段（如：2023-01-01 ~ 2023-12-31）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为年度市容乱贴乱画统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'yearIllegalPostingCleanupTotal',
      title: '年度乱贴乱画点位处置总量',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearCleanupCompletionRate',
      title: '年度清理完成率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yearIllegalNumberCleanupTotal',
      title: '年度非法号码处置总量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yearAntiPasteFacilityInstallationTotal',
      title: '年度防粘贴设施安装总数',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearCityAppearanceCleanlinessScore',
      title: '年度市容整洁度评分',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'yearOnYearIllegalPostingCleanupChangeRate',
      title: '乱贴乱画同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearOnYearCleanupCompletionRateChangeRate',
      title: '清理完成率同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearOnYearIllegalNumberCleanupChangeRate',
      title: '非法号码同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearOnYearAntiPasteFacilityInstallationChangeRate',
      title: '防粘贴设施同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'yearOnYearCityAppearanceCleanlinessScoreChangeRate',
      title: '市容整洁度同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'monthlyTrendData',
      title: '月度趋势数据',
      minWidth: 150,
      sortable: false,
    },
    {
      field: 'facilityTypeData',
      title: '设施类型数据',
      minWidth: 150,
      sortable: false,
    },
    {
      field: 'cleanlinessDimensionData',
      title: '整洁度维度数据',
      minWidth: 150,
      sortable: false,
    },
    {
      field: 'yearStatisticsPeriod',
      title: '年度统计时段',
      minWidth: 170,
      sortable: false,
    },
    // {
    //   title: '操作',
    //   width: 80,
    //   fixed: 'right',
    //   slots: { default: 'actions' },
    // },
  ];
}
