/** 表格初始数据 - 渣土车备案通行统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    recordAndPassCount: 156,
    violationTransportCount: 23,
    approvalPassCount: 133,
    checkpointInspectionCount: 89,
    violationRectificationCount: 67,
    momChangeRate_RecordAndPass: 5.8,
    momChangeRate_ViolationTransport: 3.2,
    momChangeRate_ApprovalPass: 7.2,
    momChangeRate_CheckpointInspection: 2.1,
    momChangeRate_ViolationRectification: 4.5,
    detailByArea: '鼓楼区: 156次；台江区: 98次；仓山区: 112次',
    detailByTransportCompany: '运输公司A: 45次；运输公司B: 38次；运输公司C: 32次',
    detailByViolationType: '无证清运: 12次；沿途遗撒: 8次；乱倾倒: 3次',
    detailByCheckpoint: '卡点1: 28次；卡点2: 25次；卡点3: 18次',
  },
  {
    areaName: '台江区',
    recordAndPassCount: 98,
    violationTransportCount: 18,
    approvalPassCount: 80,
    checkpointInspectionCount: 56,
    violationRectificationCount: 45,
    momChangeRate_RecordAndPass: 2.3,
    momChangeRate_ViolationTransport: 1.8,
    momChangeRate_ApprovalPass: 4.1,
    momChangeRate_CheckpointInspection: 2.8,
    momChangeRate_ViolationRectification: 3.2,
    detailByArea: '台江区: 98次；鼓楼区: 156次；仓山区: 112次',
    detailByTransportCompany: '运输公司D: 28次；运输公司E: 25次；运输公司F: 20次',
    detailByViolationType: '无证清运: 8次；沿途遗撒: 6次；乱倾倒: 4次',
    detailByCheckpoint: '卡点4: 18次；卡点5: 15次；卡点6: 12次',
  },
  {
    areaName: '仓山区',
    recordAndPassCount: 112,
    violationTransportCount: 29,
    approvalPassCount: 83,
    checkpointInspectionCount: 67,
    violationRectificationCount: 52,
    momChangeRate_RecordAndPass: 8.9,
    momChangeRate_ViolationTransport: 12.5,
    momChangeRate_ApprovalPass: 6.5,
    momChangeRate_CheckpointInspection: 5.4,
    momChangeRate_ViolationRectification: 7.8,
    detailByArea: '仓山区: 112次；晋安区: 76次；马尾区: 45次',
    detailByTransportCompany: '运输公司G: 35次；运输公司H: 28次；运输公司I: 21次',
    detailByViolationType: '无证清运: 15次；沿途遗撒: 9次；乱倾倒: 5次',
    detailByCheckpoint: '卡点7: 22次；卡点8: 20次；卡点9: 15次',
  },
  {
    areaName: '晋安区',
    recordAndPassCount: 76,
    violationTransportCount: 15,
    approvalPassCount: 61,
    checkpointInspectionCount: 43,
    violationRectificationCount: 32,
    momChangeRate_RecordAndPass: -2.1,
    momChangeRate_ViolationTransport: -1.2,
    momChangeRate_ApprovalPass: 3.8,
    momChangeRate_CheckpointInspection: 1.9,
    momChangeRate_ViolationRectification: 2.1,
    detailByArea: '晋安区: 76次；仓山区: 112次；台江区: 98次',
    detailByTransportCompany: '运输公司J: 22次；运输公司K: 18次；运输公司L: 15次',
    detailByViolationType: '无证清运: 7次；沿途遗撒: 5次；乱倾倒: 3次',
    detailByCheckpoint: '卡点10: 14次；卡点11: 12次；卡点12: 9次',
  },
  {
    areaName: '马尾区',
    recordAndPassCount: 45,
    violationTransportCount: 8,
    approvalPassCount: 37,
    checkpointInspectionCount: 28,
    violationRectificationCount: 19,
    momChangeRate_RecordAndPass: 12.5,
    momChangeRate_ViolationTransport: 15.3,
    momChangeRate_ApprovalPass: 10.2,
    momChangeRate_CheckpointInspection: 8.7,
    momChangeRate_ViolationRectification: 11.5,
    detailByArea: '马尾区: 45次；长乐区: 32次；福清市: 28次',
    detailByTransportCompany: '运输公司M: 15次；运输公司N: 12次；运输公司O: 8次',
    detailByViolationType: '无证清运: 4次；沿途遗撒: 3次；乱倾倒: 1次',
    detailByCheckpoint: '卡点13: 9次；卡点14: 8次；卡点15: 7次',
  },
  {
    areaName: '长乐区',
    recordAndPassCount: 32,
    violationTransportCount: 6,
    approvalPassCount: 26,
    checkpointInspectionCount: 18,
    violationRectificationCount: 12,
    momChangeRate_RecordAndPass: 5.6,
    momChangeRate_ViolationTransport: 3.8,
    momChangeRate_ApprovalPass: 4.3,
    momChangeRate_CheckpointInspection: 3.2,
    momChangeRate_ViolationRectification: 4.8,
    detailByArea: '长乐区: 32次；马尾区: 45次；连江县: 25次',
    detailByTransportCompany: '运输公司P: 10次；运输公司Q: 8次；运输公司R: 6次',
    detailByViolationType: '无证清运: 3次；沿途遗撒: 2次；乱倾倒: 1次',
    detailByCheckpoint: '卡点16: 6次；卡点17: 5次；卡点18: 4次',
  },
  {
    areaName: '福清市',
    recordAndPassCount: 28,
    violationTransportCount: 4,
    approvalPassCount: 24,
    checkpointInspectionCount: 16,
    violationRectificationCount: 10,
    momChangeRate_RecordAndPass: -1.8,
    momChangeRate_ViolationTransport: -2.1,
    momChangeRate_ApprovalPass: 2.1,
    momChangeRate_CheckpointInspection: 1.5,
    momChangeRate_ViolationRectification: 1.2,
    detailByArea: '福清市: 28次；长乐区: 32次；闽侯县: 22次',
    detailByTransportCompany: '运输公司S: 8次；运输公司T: 6次；运输公司U: 4次',
    detailByViolationType: '无证清运: 2次；沿途遗撒: 1次；乱倾倒: 1次',
    detailByCheckpoint: '卡点19: 5次；卡点20: 4次；卡点21: 3次',
  },
  {
    areaName: '连江县',
    recordAndPassCount: 25,
    violationTransportCount: 5,
    approvalPassCount: 20,
    checkpointInspectionCount: 14,
    violationRectificationCount: 8,
    momChangeRate_RecordAndPass: 8.3,
    momChangeRate_ViolationTransport: 6.7,
    momChangeRate_ApprovalPass: 6.7,
    momChangeRate_CheckpointInspection: 5.2,
    momChangeRate_ViolationRectification: 6.9,
    detailByArea: '连江县: 25次；福清市: 28次；闽侯县: 22次',
    detailByTransportCompany: '运输公司V: 7次；运输公司W: 5次；运输公司X: 3次',
    detailByViolationType: '无证清运: 2次；沿途遗撒: 2次；乱倾倒: 1次',
    detailByCheckpoint: '卡点22: 4次；卡点23: 4次；卡点24: 3次',
  },
  {
    areaName: '闽侯县',
    recordAndPassCount: 22,
    violationTransportCount: 3,
    approvalPassCount: 19,
    checkpointInspectionCount: 12,
    violationRectificationCount: 6,
    momChangeRate_RecordAndPass: 3.4,
    momChangeRate_ViolationTransport: 2.8,
    momChangeRate_ApprovalPass: 2.8,
    momChangeRate_CheckpointInspection: 2.1,
    momChangeRate_ViolationRectification: 3.5,
    detailByArea: '闽侯县: 22次；连江县: 25次；罗源县: 18次',
    detailByTransportCompany: '运输公司Y: 6次；运输公司Z: 5次；运输公司AA: 4次',
    detailByViolationType: '无证清运: 1次；沿途遗撒: 1次；乱倾倒: 1次',
    detailByCheckpoint: '卡点25: 3次；卡点26: 3次；卡点27: 2次',
  },
  {
    areaName: '罗源县',
    recordAndPassCount: 18,
    violationTransportCount: 2,
    approvalPassCount: 16,
    checkpointInspectionCount: 10,
    violationRectificationCount: 4,
    momChangeRate_RecordAndPass: 6.7,
    momChangeRate_ViolationTransport: 5.9,
    momChangeRate_ApprovalPass: 5.9,
    momChangeRate_CheckpointInspection: 4.8,
    momChangeRate_ViolationRectification: 5.3,
    detailByArea: '罗源县: 18次；闽侯县: 22次；永泰县: 15次',
    detailByTransportCompany: '运输公司AB: 5次；运输公司AC: 4次；运输公司AD: 3次',
    detailByViolationType: '无证清运: 1次；沿途遗撒: 1次；乱倾倒: 0次',
    detailByCheckpoint: '卡点28: 2次；卡点29: 2次；卡点30: 1次',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 渣土车备案通行统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'recordAndPassCount',
      label: '渣土车备案通行数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入渣土车备案通行数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'violationTransportCount',
      label: '违规清运次数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违规清运次数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'approvalPassCount',
      label: '清运审批通过数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入清运审批通过数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'checkpointInspectionCount',
      label: '卡点检查次数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入卡点检查次数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'violationRectificationCount',
      label: '违规整改完成数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违规整改完成数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_RecordAndPass',
      label: '备案通行数量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入备案通行数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_ViolationTransport',
      label: '违规清运次数环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违规清运次数环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_ApprovalPass',
      label: '审批通过数量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入审批通过数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_CheckpointInspection',
      label: '卡点检查次数环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入卡点检查次数环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate_ViolationRectification',
      label: '违规整改完成数量环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违规整改完成数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByArea',
      label: '按区域拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按区域拆分的明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByTransportCompany',
      label: '按清运企业拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按清运企业拆分的明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByViolationType',
      label: '按违规类型拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按违规类型拆分的明细数据（无证清运、沿途遗撒、乱倾倒）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByCheckpoint',
      label: '按卡点拆分明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按卡点拆分的明细数据',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 渣土车备案通行统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'recordAndPassCount',
      title: '渣土车备案通行数量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'violationTransportCount',
      title: '违规清运次数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'approvalPassCount',
      title: '清运审批通过数量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'checkpointInspectionCount',
      title: '卡点检查次数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'violationRectificationCount',
      title: '违规整改完成数量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'momChangeRate_RecordAndPass',
      title: '备案通行数量环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate_ViolationTransport',
      title: '违规清运次数环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate_ApprovalPass',
      title: '审批通过数量环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate_CheckpointInspection',
      title: '卡点检查次数环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'momChangeRate_ViolationRectification',
      title: '违规整改完成数量环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'detailByArea',
      title: '按区域拆分明细',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'detailByTransportCompany',
      title: '按清运企业拆分明细',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'detailByViolationType',
      title: '按违规类型拆分明细',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'detailByCheckpoint',
      title: '按卡点拆分明细',
      minWidth: 160,
      sortable: false,
    },
  ];
}
