/** 新增/修改的表单/列表的搜索表单 - 改造为道路监测管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'monitorCode',
      label: '监测编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测编码（UUID格式）',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'roadId',
      label: '道路ID',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入关联道路ID',
        min: 0,
        precision: 0,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'deviceId',
      label: '设备ID',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入关联设备ID',
        min: 0,
        precision: 0,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'configId',
      label: '配置ID',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入关联配置ID',
        min: 0,
        precision: 0,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'roadName',
      label: '路段名称',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入路段名称',
      },
      rules: 'required',
      isSearch: true,
    },
    {
      fieldName: 'deviceCode',
      label: '设备编码',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入设备编码',
        maxLength: 50,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceOnlineStatus',
      label: '设备在线状态',
      rules: 'required',
      isSearch: true,
    },
    {
      fieldName: 'indicatorThresholdRange',
      label: '指标阈值范围',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入指标阈值范围',
        maxlength: 200,
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeNum',
      label: '坑洼数量',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入坑洼数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'crackLength',
      label: '裂缝长度',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入裂缝长度（单位：米）',
        min: 0,
        precision: 2,
        addonAfter: '米',
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'roadTemp',
      label: '路面温度',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入路面温度（单位：℃）',
        min: -40,
        max: 80,
        precision: 1,
        addonAfter: '℃',
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'trafficFlow',
      label: '交通流量',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入交通流量（单位：辆/小时）',
        min: 0,
        precision: 0,
        addonAfter: '辆/小时',
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'potholeNumThreshold',
      label: '坑洼数量阈值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入坑洼数量阈值',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthThreshold',
      label: '裂缝长度阈值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入裂缝长度阈值（单位：米）',
        min: 0,
        precision: 2,
        addonAfter: '米',
      },
      rules: 'required',
    },
    {
      fieldName: 'roadTempThreshold',
      label: '路面温度阈值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入路面温度阈值（单位：℃）',
        min: -40,
        max: 80,
        precision: 1,
        addonAfter: '℃',
      },
      rules: 'required',
    },
    {
      fieldName: 'trafficFlowThreshold',
      label: '交通流量阈值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入交通流量阈值（单位：辆/小时）',
        min: 0,
        precision: 0,
        addonAfter: '辆/小时',
      },
      rules: 'required',
    },
    {
      fieldName: 'collectFrequencySnapshot',
      label: '采集频率快照',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入采集频率快照（单位：分钟）',
        min: 0,
        precision: 0,
        addonAfter: '分钟',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '是', value: '1' },
          { label: '否', value: '0' },
        ],
        placeholder: '请选择是否预警',
        showSearch: true,
      },
      fieldName: 'isWarning',
      label: '是否预警',
      rules: 'required',
    },
    {
      fieldName: 'warningId',
      label: '预警ID',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入预警ID',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '运行中', value: '运行中' },
          { label: '已停止', value: '已停止' },
        ],
        placeholder: '请选择监测状态',
        showSearch: true,
      },
      fieldName: 'monitorStatus',
      label: '监测状态',
      rules: 'required',
      editShow: true,
      isSearch: true,
    },
    {
      fieldName: 'staffId',
      label: '运维员ID',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入运维员ID',
        min: 0,
        precision: 0,
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'staffName',
      label: '运维员姓名',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入运维员姓名',
      },
      rules: 'required',
      addShow: true,
      editShow: true,
    },
    {
      fieldName: 'syncDuration',
      label: '数据同步时长',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入数据同步时长（单位：秒）',
        min: 1,
        precision: 0,
        addonAfter: '秒',
      },
      rules: 'required',
    },
    {
      fieldName: 'startUpdateTime',
      label: '起始时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择起始时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
      isSearch: true,
    },
    {
      fieldName: 'endUpdateTime',
      label: '结束时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择结束时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
      isSearch: true,
    },
    {
      fieldName: 'createTime',
      label: '创建时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择创建时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'extCommon1',
      label: '通用扩展字段1',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入通用扩展字段1',
      },
    },
    {
      fieldName: 'extCommon2',
      label: '通用扩展字段2',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入通用扩展字段2',
      },
    },
    {
      fieldName: 'extCommon3',
      label: '通用扩展字段3',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入通用扩展字段3',
      },
    },
    {
      fieldName: 'extCommon4',
      label: '通用扩展字段4',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入通用扩展字段4',
      },
    },
  ];
}

/** 表格字段 - 改造为道路监测管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'monitorCode',
      title: '监测编码',
      minWidth: 180,
      sortable: true,
      slots: { default: 'monitorCode' },
    },
    {
      field: 'roadName',
      title: '路段名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'roadName' },
    },
    {
      field: 'potholeNum',
      title: '坑洼数量',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'crackLengthThreshold',
      title: '裂缝长度阈值(米)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'roadTemp',
      title: '路面温度(℃)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'trafficFlow',
      title: '交通流量(辆/小时)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deviceCode',
      title: '设备编码',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'deviceOnlineStatus',
      title: '设备在线状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'staffName',
      title: '运维员姓名',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'syncDuration',
      title: '数据同步时长(秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monitorStatus',
      title: '监测状态',
      minWidth: 220,
      sortable: true,
      slots: { default: 'monitorStatus' },
    },
    {
      field: 'indicatorThresholdRange',
      title: '指标阈值范围',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'crackLength',
      title: '裂缝长度(米)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'potholeNumThreshold',
      title: '坑洼数量阈值',
      minWidth: 120,
      sortable: true,
    },

    {
      field: 'roadTempThreshold',
      title: '路面温度阈值(℃)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'trafficFlowThreshold',
      title: '交通流量阈值(辆/小时)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'collectFrequencySnapshot',
      title: '采集频率快照(分钟)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'isWarning',
      title: '是否预警',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'warningId',
      title: '预警ID',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'staffId',
      title: '运维员ID',
      minWidth: 100,
      sortable: true,
    },
    // {
    //   field: 'recordTime',
    //   title: '记录时间',
    //   minWidth: 180,
    //   sortable: true,
    // },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 180,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
