/** 表格初始数据 - 改造为台账管理数据 */
export const dataList = () => {
  return [
    {
      id: '2',
      ledgerName: '龙文区碧湖公园停车场台账', // 台账名称
      resourceType: '停车场', // 资源类型
      belongArea: '龙文区-碧湖街道', // 所属区域
      includeFields: 'ID,名称,地址,泊位总数,收费标准,运营状态', // 包含字段
      generateFormat: 'Excel', // 生成格式
      ledgerCodeRule: '区域编码+年份+序号', // 台账编号规则
      generateScope: '碧湖街道全部停车场', // 生成范围
      ledgerCode: 'LW-BH-2026-002', // 台账编号
      generateTime: '2026-01-10 09:30:00', // 生成时间
      format: 'xlsx', // 格式
      size: '2.4MB', // 大小
      generator: '王管理员', // 生成人
      status: '已生成', // 状态
    },
    {
      id: '3',
      ledgerName: '龙海区石码镇便民停车场台账',
      resourceType: '停车场',
      belongArea: '龙海区-石码街道',
      includeFields: 'ID,名称,类型,地址,泊位总数,联系电话',
      generateFormat: 'Excel',
      ledgerCodeRule: '区域编码+月份+序号',
      generateScope: '石码街道便民停车场',
      ledgerCode: 'LH-SM-202601-003',
      generateTime: '2026-01-08 14:20:00',
      format: 'xlsx',
      size: '1.8MB',
      generator: '李主管',
      status: '已生成',
    },
    {
      id: '4',
      ledgerName: '龙海区闽齐社区停车场台账',
      resourceType: '停车场',
      belongArea: '龙海区-海澄镇',
      includeFields: 'ID,名称,地址,运营状态,管理事项,联系电话',
      generateFormat: 'CSV',
      ledgerCodeRule: '镇编码+社区编码+序号',
      generateScope: '闽齐社区专属停车场',
      ledgerCode: 'LH-HC-MQ-004',
      generateTime: '2026-01-15 16:45:00',
      format: 'csv',
      size: '0.9MB',
      generator: '张管理员',
      status: '已生成',
    },
    {
      id: '5',
      ledgerName: '芗城区江滨路生态停车场台账',
      resourceType: '停车场',
      belongArea: '芗城区-巷口街道',
      includeFields: 'ID,名称,类型,泊位总数,收费标准,营业时间',
      generateFormat: 'Excel',
      ledgerCodeRule: '街道编码+停车场类型+序号',
      generateScope: '江滨路沿线生态停车场',
      ledgerCode: 'XC-XK-ST-005',
      generateTime: '2026-01-12 11:10:00',
      format: 'xlsx',
      size: '3.2MB',
      generator: '陈师傅',
      status: '已生成',
    },
    {
      id: '6',
      ledgerName: '龙文区万达商圈停车场台账',
      resourceType: '停车场',
      belongArea: '龙文区-蓝田街道',
      includeFields: 'ID,名称,地址,泊位总数,运营状态,管理事项',
      generateFormat: 'PDF',
      ledgerCodeRule: '商圈编码+年份+序号',
      generateScope: '万达商圈全部停车场',
      ledgerCode: 'LW-LT-WD-2026-006',
      generateTime: '2026-01-14 10:05:00',
      format: 'pdf',
      size: '4.5MB',
      generator: '刘经理',
      status: '已生成',
    },
    {
      id: '7',
      ledgerName: '长泰区武安镇公共停车场台账',
      resourceType: '停车场',
      belongArea: '长泰区-武安镇',
      includeFields: 'ID,名称,类型,地址,泊位总数,联系电话',
      generateFormat: 'Excel',
      ledgerCodeRule: '镇编码+年份+序号',
      generateScope: '武安镇公共停车场',
      ledgerCode: 'CT-WA-2026-007',
      generateTime: '2026-01-09 15:30:00',
      format: 'xlsx',
      size: '1.5MB',
      generator: '黄管理员',
      status: '已生成',
    },
    {
      id: '8',
      ledgerName: '漳浦县绥安镇便民停车场台账',
      resourceType: '停车场',
      belongArea: '漳浦县-绥安镇',
      includeFields: 'ID,名称,地址,运营状态,收费标准,管理事项',
      generateFormat: 'CSV',
      ledgerCodeRule: '县编码+镇编码+序号',
      generateScope: '绥安镇便民停车场',
      ledgerCode: 'ZP-SA-008',
      generateTime: '2026-01-05 13:40:00',
      format: 'csv',
      size: '1.1MB',
      generator: '郑师傅',
      status: '生成中',
    },
    {
      id: '9',
      ledgerName: '芗城区巷口街道停车场台账',
      resourceType: '停车场',
      belongArea: '芗城区-巷口街道',
      includeFields: 'ID,名称,类型,地址,运营状态,收费标准',
      generateFormat: 'Excel',
      ledgerCodeRule: '街道编码+月份+序号',
      generateScope: '巷口街道全部停车场',
      ledgerCode: 'XC-XK-202601-009',
      generateTime: '2026-01-03 08:50:00',
      format: 'xlsx',
      size: '2.1MB',
      generator: '吴主管',
      status: '已生成',
    },
    {
      id: '10',
      ledgerName: '龙文区蓝田街道路侧泊位台账',
      resourceType: '路侧泊位',
      belongArea: '龙文区-蓝田街道',
      includeFields: 'ID,名称,地址,泊位总数,运营状态,管理事项',
      generateFormat: 'Excel',
      ledgerCodeRule: '街道编码+泊位类型+序号',
      generateScope: '蓝田街道路侧泊位',
      ledgerCode: 'LW-LT-LC-010',
      generateTime: '2026-01-07 16:25:00',
      format: 'xlsx',
      size: '2.8MB',
      generator: '林师傅',
      status: '已生成',
    },
    {
      id: '11',
      ledgerName: '龙文区步文街道停车场台账',
      resourceType: '停车场',
      belongArea: '龙文区-步文街道',
      includeFields: 'ID,名称,地址,泊位总数,收费标准,运营状态',
      generateFormat: 'PDF',
      ledgerCodeRule: '街道编码+年份+序号',
      generateScope: '步文街道全部停车场',
      ledgerCode: 'LW-BW-2026-011',
      generateTime: '2026-01-16 09:40:00',
      format: 'pdf',
      size: '3.9MB',
      generator: '赵经理',
      status: '已生成',
    },
    {
      id: '12',
      ledgerName: '芗城区东铺头街道停车场台账',
      resourceType: '停车场',
      belongArea: '芗城区-东铺头街道',
      includeFields: 'ID,名称,地址,泊位总数,管理事项,联系电话',
      generateFormat: 'Excel',
      ledgerCodeRule: '街道编码+序号',
      generateScope: '东铺头街道停车场',
      ledgerCode: 'XC-DPT-012',
      generateTime: '2026-01-11 14:15:00',
      format: 'xlsx',
      size: '1.7MB',
      generator: '孙管理员',
      status: '生成失败',
    },
    {
      id: '13',
      ledgerName: '芗城区西桥街道专用停车场台账',
      resourceType: '专用停车场',
      belongArea: '芗城区-西桥街道',
      includeFields: 'ID,名称,地址,泊位总数,收费标准,运营状态',
      generateFormat: 'Excel',
      ledgerCodeRule: '街道编码+专用+序号',
      generateScope: '西桥街道专用停车场',
      ledgerCode: 'XC-XQ-ZY-013',
      generateTime: '2026-01-06 10:55:00',
      format: 'xlsx',
      size: '1.3MB',
      generator: '周师傅',
      status: '已生成',
    },
    {
      id: '14',
      ledgerName: '龙海区石码街道停车场改造台账',
      resourceType: '停车场',
      belongArea: '龙海区-石码街道',
      includeFields: 'ID,名称,地址,运营状态,管理事项,改造原因',
      generateFormat: 'PDF',
      ledgerCodeRule: '街道编码+改造+序号',
      generateScope: '石码街道改造停车场',
      ledgerCode: 'LH-SM-GZ-014',
      generateTime: '2026-01-01 11:35:00',
      format: 'pdf',
      size: '2.6MB',
      generator: '马主管',
      status: '已生成',
    },
    {
      id: '15',
      ledgerName: '长泰区武安镇停车场汇总台账',
      resourceType: '停车场',
      belongArea: '长泰区-武安镇',
      includeFields: 'ID,名称,类型,地址,泊位总数,收费标准',
      generateFormat: 'Excel',
      ledgerCodeRule: '镇编码+汇总+年份+序号',
      generateScope: '武安镇全部停车场',
      ledgerCode: 'CT-WA-HZ-2026-015',
      generateTime: '2026-01-13 17:25:00',
      format: 'xlsx',
      size: '3.1MB',
      generator: '朱管理员',
      status: '已生成',
    },
    {
      id: '16',
      ledgerName: '漳浦县绥安镇停车场台账',
      resourceType: '停车场',
      belongArea: '漳浦县-绥安镇',
      includeFields: 'ID,名称,地址,泊位总数,收费标准,运营状态',
      generateFormat: 'CSV',
      ledgerCodeRule: '县编码+镇编码+年份+序号',
      generateScope: '绥安镇核心区域停车场',
      ledgerCode: 'ZP-SA-2026-016',
      generateTime: '2026-01-15 13:15:00',
      format: 'csv',
      size: '1.4MB',
      generator: '韩师傅',
      status: '已生成',
    },
    {
      id: '17',
      ledgerName: '云霄县云陵镇专用停车场台账',
      resourceType: '专用停车场',
      belongArea: '云霄县-云陵镇',
      includeFields: 'ID,名称,地址,泊位总数,管理事项,运营状态',
      generateFormat: 'Excel',
      ledgerCodeRule: '县编码+镇编码+专用+序号',
      generateScope: '云陵镇专用停车场',
      ledgerCode: 'YX-YL-ZY-017',
      generateTime: '2026-01-04 09:25:00',
      format: 'xlsx',
      size: '1.2MB',
      generator: '秦主管',
      status: '已生成',
    },
    {
      id: '18',
      ledgerName: '诏安县南诏镇停车场整改台账',
      resourceType: '停车场',
      belongArea: '诏安县-南诏镇',
      includeFields: 'ID,名称,地址,运营状态,管理事项,整改原因',
      generateFormat: 'PDF',
      ledgerCodeRule: '县编码+镇编码+整改+序号',
      generateScope: '南诏镇需整改停车场',
      ledgerCode: 'ZA-NZ-ZG-018',
      generateTime: '2025-12-28 15:45:00',
      format: 'pdf',
      size: '2.2MB',
      generator: '许管理员',
      status: '生成中',
    },
    {
      id: '19',
      ledgerName: '平和县小溪镇停车场台账',
      resourceType: '停车场',
      belongArea: '平和县-小溪镇',
      includeFields: 'ID,名称,地址,泊位总数,收费标准,管理事项',
      generateFormat: 'Excel',
      ledgerCodeRule: '县编码+镇编码+序号',
      generateScope: '小溪镇全部停车场',
      ledgerCode: 'PH-XX-019',
      generateTime: '2026-01-14 16:55:00',
      format: 'xlsx',
      size: '2.7MB',
      generator: '邓师傅',
      status: '已生成',
    },
    {
      id: '24',
      ledgerName: '龙文区蓝田街道停车场台账(二期)',
      resourceType: '停车场',
      belongArea: '龙文区-蓝田街道',
      includeFields: 'ID,名称,地址,泊位总数,运营状态,管理事项',
      generateFormat: 'Excel',
      ledgerCodeRule: '街道编码+二期+序号',
      generateScope: '蓝田街道梧桥中路停车场',
      ledgerCode: 'LW-LT-EQ-024',
      generateTime: '2026-01-16 08:20:00',
      format: 'xlsx',
      size: '1.9MB',
      generator: '彭管理员',
      status: '已生成',
    },
    {
      id: '25',
      ledgerName: '龙文区蓝田街道停车场台账(三期)',
      resourceType: '停车场',
      belongArea: '龙文区-蓝田街道',
      includeFields: 'ID,名称,地址,泊位总数,运营状态,联系电话',
      generateFormat: 'CSV',
      ledgerCodeRule: '街道编码+三期+序号',
      generateScope: '蓝田街道梧桥中路次入口停车场',
      ledgerCode: 'LW-LT-SQ-025',
      generateTime: '2026-01-16 08:25:00',
      format: 'csv',
      size: '1.0MB',
      generator: '彭管理员',
      status: '待生成',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 - 改造为台账管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'id',
      label: '台账ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入台账ID',
      },
      labelWidth: '100',
      rules: 'required',
    },
    {
      fieldName: 'ledgerName',
      label: '台账名称',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入台账名称',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '停车场', value: '停车场' },
          { label: '路侧泊位', value: '路侧泊位' },
          { label: '专用停车场', value: '专用停车场' },
          { label: '车位', value: '车位' },
          { label: '出入口', value: '出入口' },
        ],
        placeholder: '请选择资源类型',
        showSearch: true,
      },
      fieldName: 'resourceType',
      label: '资源类型',
      rules: 'required',
    },
    {
      fieldName: 'belongArea',
      label: '所属区域',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入所属区域（如：龙文区-碧湖街道）',
      },
      rules: 'required',
    },
    {
      fieldName: 'includeFields',
      label: '包含字段',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入包含字段（多个用逗号分隔）',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: 'Excel', value: 'Excel' },
          { label: 'CSV', value: 'CSV' },
          { label: 'PDF', value: 'PDF' },
          { label: 'Word', value: 'Word' },
        ],
        placeholder: '请选择生成格式',
        showSearch: true,
      },
      fieldName: 'generateFormat',
      label: '生成格式',
      rules: 'required',
    },
    {
      fieldName: 'ledgerCodeRule',
      label: '台账编号规则',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入台账编号规则（如：区域编码+年份+序号）',
      },
    },
    {
      fieldName: 'generateScope',
      label: '生成范围',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入生成范围（如：碧湖街道全部停车场）',
      },
    },
    {
      fieldName: 'ledgerCode',
      label: '台账编号',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入台账编号',
      },
      rules: 'required',
    },
    {
      fieldName: 'generateTime',
      label: '生成时间',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        placeholder: '请选择生成时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: 'xlsx', value: 'xlsx' },
          { label: 'csv', value: 'csv' },
          { label: 'pdf', value: 'pdf' },
          { label: 'docx', value: 'docx' },
        ],
        placeholder: '请选择格式',
        showSearch: true,
      },
      fieldName: 'format',
      label: '格式',
    },
    {
      fieldName: 'size',
      label: '大小',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入文件大小（如：2.4MB）',
      },
    },
    {
      fieldName: 'generator',
      label: '生成人',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入生成人',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '已生成', value: '已生成' },
          { label: '生成中', value: '生成中' },
          { label: '待生成', value: '待生成' },
          { label: '生成失败', value: '生成失败' },
        ],
        placeholder: '请选择状态',
        showSearch: true,
      },
      fieldName: 'status',
      label: '状态',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为台账管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: '台账ID',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'ledgerName',
      title: '台账名称',
      minWidth: 200,
      sortable: true,
      slots: { default: 'ledgerName' },
    },
    {
      field: 'resourceType',
      title: '资源类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'belongArea',
      title: '所属区域',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'includeFields',
      title: '包含字段',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'generateFormat',
      title: '生成格式',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'ledgerCodeRule',
      title: '台账编号规则',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'generateScope',
      title: '生成范围',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'ledgerCode',
      title: '台账编号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'generateTime',
      title: '生成时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'format',
      title: '格式',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'size',
      title: '大小',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'generator',
      title: '生成人',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'status',
      title: '状态',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 240,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 - 改造为台账管理文案 */
export const textObj = {
  editText: '编辑台账',
  addText: '新增台账',
  excelName: '台账列表',
  excelAllName: '全市台账数据.xlsx',
  total: '台账数量20;已生成16;生成失败1;生成中2',
};