import { DICT_TYPE } from '@vben/constants';
import { getDictObj, getDictOptions } from '@vben/hooks';

import { getDictTagTypeFromDict } from '#/utils/genchuan/dictColor';
import { formatDate } from '#/utils/genchuan/formatTime';

/** 格式化时间戳为 yyyy-MM-dd HH:mm:ss */
export const formatTimestamp = (timestamp) => {
  if (!timestamp) return '';
  return formatDate(timestamp);
};

/** 积分抽奖静态数据 - 参照接口返回格式 */
export const dataList = () => {
  const rawData = [
    {
      id: 1,
      no: 'LT-20250401001',
      userId: 1001,
      userName: '张三',
      prizeId: 1,
      prizeName: '10元充电优惠券',
      lotteryTime: 1_743_465_600_000,
      costPoint: 50,
      status: '0',
      statusName: '正常记录',
      sendTime: 1_743_465_660_000,
      senderId: 1,
      senderName: '系统管理员',
      checkResult: null,
      syncStatus: '1',
      syncStatusName: '已同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_465_600_000,
      updateTime: 1_743_465_660_000,
    },
    {
      id: 2,
      no: 'LT-20250401002',
      userId: 1002,
      userName: '李四',
      prizeId: 2,
      prizeName: '20元充电优惠券',
      lotteryTime: 1_743_469_200_000,
      costPoint: 100,
      status: '0',
      statusName: '正常记录',
      sendTime: 1_743_469_260_000,
      senderId: 1,
      senderName: '系统管理员',
      checkResult: null,
      syncStatus: '1',
      syncStatusName: '已同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_469_200_000,
      updateTime: 1_743_469_260_000,
    },
    {
      id: 3,
      no: 'LT-20250401003',
      userId: 1003,
      userName: '王五',
      prizeId: 3,
      prizeName: '50积分奖励',
      lotteryTime: 1_743_472_800_000,
      costPoint: 30,
      status: '1',
      statusName: '异常记录',
      sendTime: null,
      senderId: null,
      senderName: null,
      checkResult: '奖品库存不足，待核查',
      syncStatus: '0',
      syncStatusName: '未同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_472_800_000,
      updateTime: 1_743_472_800_000,
    },
    {
      id: 4,
      no: 'LT-20250401004',
      userId: 1004,
      userName: '赵六',
      prizeId: 1,
      prizeName: '10元充电优惠券',
      lotteryTime: 1_743_476_400_000,
      costPoint: 50,
      status: '0',
      statusName: '正常记录',
      sendTime: 1_743_476_460_000,
      senderId: 1,
      senderName: '系统管理员',
      checkResult: null,
      syncStatus: '1',
      syncStatusName: '已同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_476_400_000,
      updateTime: 1_743_476_460_000,
    },
    {
      id: 5,
      no: 'LT-20250401005',
      userId: 1005,
      userName: '孙七',
      prizeId: 4,
      prizeName: '100元充电卡',
      lotteryTime: 1_743_480_000_000,
      costPoint: 200,
      status: '1',
      statusName: '异常记录',
      sendTime: null,
      senderId: null,
      senderName: null,
      checkResult: '用户积分扣除失败',
      syncStatus: '2',
      syncStatusName: '同步失败',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_480_000_000,
      updateTime: 1_743_480_000_000,
    },
    {
      id: 6,
      no: 'LT-20250401006',
      userId: 1006,
      userName: '周八',
      prizeId: 2,
      prizeName: '20元充电优惠券',
      lotteryTime: 1_743_483_600_000,
      costPoint: 100,
      status: '0',
      statusName: '正常记录',
      sendTime: 1_743_483_660_000,
      senderId: 1,
      senderName: '系统管理员',
      checkResult: null,
      syncStatus: '1',
      syncStatusName: '已同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_483_600_000,
      updateTime: 1_743_483_660_000,
    },
    {
      id: 7,
      no: 'LT-20250401007',
      userId: 1007,
      userName: '吴九',
      prizeId: 5,
      prizeName: '谢谢参与',
      lotteryTime: 1_743_487_200_000,
      costPoint: 10,
      status: '0',
      statusName: '正常记录',
      sendTime: null,
      senderId: null,
      senderName: null,
      checkResult: null,
      syncStatus: '1',
      syncStatusName: '已同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_487_200_000,
      updateTime: 1_743_487_200_000,
    },
    {
      id: 8,
      no: 'LT-20250401008',
      userId: 1008,
      userName: '郑十',
      prizeId: 1,
      prizeName: '10元充电优惠券',
      lotteryTime: 1_743_490_800_000,
      costPoint: 50,
      status: '2',
      statusName: '已核查',
      sendTime: 1_743_490_860_000,
      senderId: 2,
      senderName: '运营管理员',
      checkResult: '核查通过，已补发奖品',
      syncStatus: '1',
      syncStatusName: '已同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_490_800_000,
      updateTime: 1_743_490_860_000,
    },
    {
      id: 9,
      no: 'LT-20250401009',
      userId: 1009,
      userName: '钱十一',
      prizeId: 3,
      prizeName: '50积分奖励',
      lotteryTime: 1_743_494_400_000,
      costPoint: 30,
      status: '0',
      statusName: '正常记录',
      sendTime: 1_743_494_460_000,
      senderId: 1,
      senderName: '系统管理员',
      checkResult: null,
      syncStatus: '1',
      syncStatusName: '已同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_494_400_000,
      updateTime: 1_743_494_460_000,
    },
    {
      id: 10,
      no: 'LT-20250401010',
      userId: 1010,
      userName: '冯十二',
      prizeId: 2,
      prizeName: '20元充电优惠券',
      lotteryTime: 1_743_498_000_000,
      costPoint: 100,
      status: '1',
      statusName: '异常记录',
      sendTime: null,
      senderId: null,
      senderName: null,
      checkResult: '网络异常，待重新发放',
      syncStatus: '0',
      syncStatusName: '未同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_498_000_000,
      updateTime: 1_743_498_000_000,
    },
    {
      id: 11,
      no: 'LT-20250401011',
      userId: 1011,
      userName: '陈十三',
      prizeId: 1,
      prizeName: '10元充电优惠券',
      lotteryTime: 1_743_501_600_000,
      costPoint: 50,
      status: '0',
      statusName: '正常记录',
      sendTime: 1_743_501_660_000,
      senderId: 1,
      senderName: '系统管理员',
      checkResult: null,
      syncStatus: '1',
      syncStatusName: '已同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_501_600_000,
      updateTime: 1_743_501_660_000,
    },
    {
      id: 12,
      no: 'LT-20250401012',
      userId: 1012,
      userName: '褚十四',
      prizeId: 4,
      prizeName: '100元充电卡',
      lotteryTime: 1_743_505_200_000,
      costPoint: 200,
      status: '0',
      statusName: '正常记录',
      sendTime: 1_743_505_260_000,
      senderId: 1,
      senderName: '系统管理员',
      checkResult: null,
      syncStatus: '1',
      syncStatusName: '已同步',
      reserve1: null,
      reserve2: null,
      creator: 'system',
      updater: 'admin',
      createTime: 1_743_505_200_000,
      updateTime: 1_743_505_260_000,
    },
  ];

  // 使用formatDate格式化时间戳字段
  return rawData.map((item) => ({
    ...item,
    lotteryTimeStr: formatDate(item.lotteryTime),
    sendTimeStr: formatDate(item.sendTime),
    createTimeStr: formatDate(item.createTime),
    updateTimeStr: formatDate(item.updateTime),
  }));
};

/** 获取记录状态Tag类型 - 使用封装的字典颜色工具 */
export const getPointLotteryStatusTagType = (status) => {
  const dict = getDictObj(DICT_TYPE.POINT_LOTTERY_STATUS, String(status));
  return getDictTagTypeFromDict(dict, 'primary');
};

/** 获取同步状态Tag类型 - 使用封装的字典颜色工具 */
export const getPointLotterySyncStatusTagType = (syncStatus) => {
  const dict = getDictObj(
    DICT_TYPE.POINT_LOTTERY_SYNC_STATUS,
    String(syncStatus),
  );
  return getDictTagTypeFromDict(dict, 'primary');
};

/** 用户选项配置 - 模拟数据，实际应从API获取 */
export const userOptions = [
  { label: '张三', value: '1001' },
  { label: '李四', value: '1002' },
  { label: '王五', value: '1003' },
  { label: '赵六', value: '1004' },
  { label: '孙七', value: '1005' },
  { label: '周八', value: '1006' },
  { label: '吴九', value: '1007' },
  { label: '郑十', value: '1008' },
  { label: '钱十一', value: '1009' },
  { label: '冯十二', value: '1010' },
  { label: '陈十三', value: '1011' },
  { label: '褚十四', value: '1012' },
];

/** 奖品选项配置 - 模拟数据，实际应从API获取 */
export const prizeOptions = [
  { label: '10元充电优惠券', value: '1' },
  { label: '20元充电优惠券', value: '2' },
  { label: '50积分奖励', value: '3' },
  { label: '100元充电卡', value: '4' },
  { label: '谢谢参与', value: '5' },
];

/** 发放人选项配置 - 模拟数据，实际应从API获取 */
export const senderOptions = [
  { label: '系统管理员', value: '1' },
  { label: '运营管理员', value: '2' },
];

/** 积分抽奖搜索表单配置 - 根据PointLotteryPageReqVO参数配置 */
export function useSearchFormSchema() {
  return [
    {
      fieldName: 'no',
      label: '抽奖记录编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入抽奖记录编号',
        clearable: true,
      },
    },
    // {
    //   fieldName: 'userId',
    //   label: '用户ID',
    //   component: 'InputNumber',
    //   componentProps: {
    //     placeholder: '请输入用户ID',
    //     clearable: true,
    //   },
    // },
    {
      fieldName: 'prizeId',
      label: '奖品',
      component: 'Select',
      componentProps: {
        placeholder: '请选择奖品',
        options: [],
        clearable: true,
        filterable: true,
        remote: true,
      },
    },
    {
      fieldName: 'lotteryTime',
      label: '抽奖时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择抽奖时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'timestamp',
        type: 'datetimerange',
        clearable: true,
      },
    },
    {
      fieldName: 'status',
      label: '记录状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择记录状态',
        options: getDictOptions(DICT_TYPE.POINT_LOTTERY_STATUS, 'string'),
        clearable: true,
      },
    },
  ];
}

/** 积分抽奖表格列配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'no',
      title: '抽奖记录编号',
      minWidth: 160,
      sortable: true,
      slots: { default: 'no' },
    },
    {
      field: 'userName',
      title: '用户名称',
      minWidth: 120,
      sortable: true,
      slots: { default: 'userName' },
    },
    {
      field: 'prizeName',
      title: '奖品名称',
      minWidth: 150,
      sortable: true,
      slots: { default: 'prizeName' },
    },
    {
      field: 'lotteryTime',
      title: '抽奖时间',
      minWidth: 180,
      sortable: true,
      formatter: ({ cellValue }) => formatDate(cellValue),
    },
    {
      field: 'costPoint',
      title: '消耗积分',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'status',
      title: '记录状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'status' },
    },
    {
      field: 'sendTime',
      title: '发放时间',
      minWidth: 180,
      sortable: true,
      formatter: ({ cellValue }) => formatDate(cellValue),
    },
    {
      field: 'senderName',
      title: '发放人',
      minWidth: 120,
      sortable: true,
      slots: { default: 'senderName' },
    },
    {
      field: 'checkResult',
      title: '核查结果',
      minWidth: 200,
      sortable: true,
      slots: { default: 'checkResult' },
    },
    {
      field: 'syncStatus',
      title: '同步状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'syncStatus' },
    },
    {
      title: '操作',
      width: 150,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

export const textObj = {
  editText: '编辑抽奖记录',
  addText: '新增抽奖记录',
  excelName: '积分抽奖记录列表',
  excelAllName: '积分抽奖记录数据.xlsx',
  total: ' 总计: 抽奖记录数量12;正常记录:8;异常记录:3;已核查:1',
};

/** 详情抽屉字段配置 */
export const detailFields = [
  // { key: 'id', label: '记录ID' },
  { key: 'no', label: '抽奖记录编号' },
  // { key: 'userId', label: '用户ID' },
  { key: 'userName', label: '用户名称' },
  // { key: 'prizeId', label: '奖品ID' },
  { key: 'prizeName', label: '奖品名称' },
  { key: 'lotteryTimeStr', label: '抽奖时间' },
  { key: 'costPoint', label: '消耗积分' },
  {
    key: 'status',
    label: '记录状态',
    type: 'tag',
    formatter: (value) => {
      const dict = getDictObj(DICT_TYPE.POINT_LOTTERY_STATUS, String(value));
      return dict ? dict.label : value;
    },
    tagType: (value) => getPointLotteryStatusTagType(value),
  },
  { key: 'sendTimeStr', label: '发放时间' },
  // { key: 'senderId', label: '发放人ID' },
  { key: 'senderName', label: '发放人' },
  { key: 'checkResult', label: '核查结果' },
  {
    key: 'syncStatus',
    label: '同步状态',
    type: 'tag',
    formatter: (value) => {
      const dict = getDictObj(
        DICT_TYPE.POINT_LOTTERY_SYNC_STATUS,
        String(value),
      );
      return dict ? dict.label : value;
    },
    tagType: (value) => getPointLotterySyncStatusTagType(value),
  },
  { key: 'creator', label: '创建者' },
  { key: 'updater', label: '更新者' },
  { key: 'createTimeStr', label: '创建时间' },
  { key: 'updateTimeStr', label: '更新时间' },
];
