/** 表格初始数据 - 改造为出入口管理数据 */
export const dataList = () => [
  {
    areaName: '福州市鼓楼区',
    roadSectionName: '福州市鼓楼区杨桥东路（东街口-五一广场）',
    deviceCode: 'FJ-FZ-202406-001',
    potholeCount: 6,
    crackLength: 9.8,
    roadSurfaceTemp: 27.5,
    trafficFlow: 1180,
    warningCount: 3,
    workOrderCount: 3,
    disposalCompleteCount: 3,
    verificationPassRate: 100,
    deviceOnlineRate: 99.5,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: 5.2,
    yoYChangeRate: 8.8,
    indexChangeTrend:
      '坑洼数量小幅上升(+5.2%)，裂缝长度基本持平(+0.8%)，交通流量环比增长3.5%，整体指标呈缓慢上升趋势，需加强日常巡检。',
  },
  {
    areaName: '厦门市思明区',
    roadSectionName: '厦门市思明区鹭江道（轮渡码头-中山路）',
    deviceCode: 'FJ-XM-202406-002',
    potholeCount: 2,
    crackLength: 3.5,
    roadSurfaceTemp: 29.2,
    trafficFlow: 1560,
    warningCount: 1,
    workOrderCount: 1,
    disposalCompleteCount: 1,
    verificationPassRate: 100,
    deviceOnlineRate: 99.8,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: -4.8,
    yoYChangeRate: -9.5,
    indexChangeTrend:
      '坑洼数量环比下降(-4.8%)，裂缝长度同比下降(-9.5%)，交通流量因旅游旺季增长12.5%，设备在线率99.8%，整体指标呈良性下降趋势。',
  },
  {
    areaName: '泉州市丰泽区',
    roadSectionName: '泉州市丰泽区刺桐路（湖心街-泉秀街）',
    deviceCode: 'FJ-QZ-202406-003',
    potholeCount: 12,
    crackLength: 18.3,
    roadSurfaceTemp: 28.8,
    trafficFlow: 950,
    warningCount: 8,
    workOrderCount: 8,
    disposalCompleteCount: 5,
    verificationPassRate: 62.5,
    deviceOnlineRate: 85.2,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: 24.5,
    yoYChangeRate: 30.8,
    indexChangeTrend:
      '坑洼数量环比大幅上升(+24.5%)，裂缝长度同比上升(+30.8%)，处置完成率仅62.5%，设备在线率85.2%偏低，整体指标呈恶化趋势，需紧急整改。',
  },
  {
    areaName: '漳州市芗城区',
    roadSectionName: '漳州市芗城区胜利路（延安北路-新华西路）',
    deviceCode: 'FJ-ZZ-202406-004',
    potholeCount: 0,
    crackLength: 1.2,
    roadSurfaceTemp: 30.1,
    trafficFlow: 780,
    warningCount: 0,
    workOrderCount: 0,
    disposalCompleteCount: 0,
    verificationPassRate: 100,
    deviceOnlineRate: 99,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: -9.5,
    yoYChangeRate: -15,
    indexChangeTrend:
      '无坑洼和裂缝预警，无工单产生，设备在线率99.0%，所有核查项100%通过，整体指标呈优秀下降趋势，继续保持现有管理策略。',
  },
  {
    areaName: '莆田市城厢区',
    roadSectionName: '莆田市城厢区荔城南大道（凤凰山-万达广场）',
    deviceCode: 'FJ-PT-202406-005',
    potholeCount: 8,
    crackLength: 14.7,
    roadSurfaceTemp: 28,
    trafficFlow: 890,
    warningCount: 5,
    workOrderCount: 5,
    disposalCompleteCount: 3,
    verificationPassRate: 60,
    deviceOnlineRate: 78.5,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: 11.8,
    yoYChangeRate: 18.5,
    indexChangeTrend:
      '坑洼数量环比上升(+11.8%)，裂缝长度同比上升(+18.5%)，处置完成率60%偏低，设备在线率78.5%为全市最低，整体指标呈缓慢恶化趋势。',
  },
  {
    areaName: '宁德市蕉城区',
    roadSectionName: '宁德市蕉城区闽东中路（市政府-万达广场）',
    deviceCode: 'FJ-ND-202406-006',
    potholeCount: 5,
    crackLength: 7.9,
    roadSurfaceTemp: 26.3,
    trafficFlow: 650,
    warningCount: 2,
    workOrderCount: 2,
    disposalCompleteCount: 2,
    verificationPassRate: 100,
    deviceOnlineRate: 98,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: 5.2,
    yoYChangeRate: 8.8,
    indexChangeTrend:
      '坑洼数量小幅上升(+5.2%)，裂缝长度平稳，所有工单100%完成且核查通过，设备在线率98.0%，整体指标基本稳定。',
  },
  {
    areaName: '龙岩市新罗区',
    roadSectionName: '龙岩市新罗区龙川路（中山路-登高西路）',
    deviceCode: 'FJ-LY-202406-007',
    potholeCount: 10,
    crackLength: 15,
    roadSurfaceTemp: 27.8,
    trafficFlow: 1020,
    warningCount: 6,
    workOrderCount: 6,
    disposalCompleteCount: 5,
    verificationPassRate: 83.3,
    deviceOnlineRate: 97,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: 19,
    yoYChangeRate: 25.5,
    indexChangeTrend:
      '坑洼数量接近阈值(10个)，环比上升(+19.0%)，处置完成率83.3%，设备在线率97.0%，整体指标呈上升趋势，需增加巡检频次。',
  },
  {
    areaName: '三明市梅列区',
    roadSectionName: '三明市梅列区列东街（东新四路-东新六路）',
    deviceCode: 'FJ-SM-202406-008',
    potholeCount: 4,
    crackLength: 6.5,
    roadSurfaceTemp: 25.9,
    trafficFlow: 720,
    warningCount: 1,
    workOrderCount: 1,
    disposalCompleteCount: 1,
    verificationPassRate: 100,
    deviceOnlineRate: 99,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: -4.2,
    yoYChangeRate: -6.5,
    indexChangeTrend:
      '坑洼数量环比下降(-4.2%)，裂缝长度同比下降(-6.5%)，所有工单100%完成，设备在线率99.0%，整体指标呈良性下降趋势。',
  },
  {
    areaName: '南平市延平区',
    roadSectionName: '南平市延平区八一路（江滨路-中山路）',
    deviceCode: 'FJ-NP-202406-009',
    potholeCount: 7,
    crackLength: 11.2,
    roadSurfaceTemp: 26.7,
    trafficFlow: 850,
    warningCount: 4,
    workOrderCount: 4,
    disposalCompleteCount: 2,
    verificationPassRate: 50,
    deviceOnlineRate: 89.5,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: 10.2,
    yoYChangeRate: 15.8,
    indexChangeTrend:
      '坑洼数量环比上升(+10.2%)，处置完成率仅50%，核查通过率偏低，设备在线率89.5%，整体指标呈缓慢上升趋势，需优化处置流程。',
  },
  {
    areaName: '平潭综合实验区',
    roadSectionName: '平潭综合实验区金井大道（管委会-龙凤头沙滩）',
    deviceCode: 'FJ-PTTH-202406-010',
    potholeCount: 1,
    crackLength: 2.8,
    roadSurfaceTemp: 31.5,
    trafficFlow: 1380,
    warningCount: 2,
    workOrderCount: 2,
    disposalCompleteCount: 2,
    verificationPassRate: 100,
    deviceOnlineRate: 99.8,
    statisticsTimeRange: '2024-06-01 ~ 2024-06-30',
    momChangeRate: -2.8,
    yoYChangeRate: -5.5,
    indexChangeTrend:
      '坑洼数量环比下降(-2.8%)，路面温度偏高(31.5℃)，所有工单100%完成，设备在线率99.8%，整体指标呈稳定下降趋势。',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为出入口管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称（如：福州市鼓楼区）',
      },
      labelWidth: '130',
      rules: 'required', // 区域名称为必填项
    },
    {
      fieldName: 'roadSectionName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'deviceCode',
      label: '设备编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入设备编号',
        maxLength: 50,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'potholeCount',
      label: '坑洼数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入坑洼数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLength',
      label: '裂缝长度',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入裂缝长度（单位：米）',
        min: 0,
        precision: 2,
        addonAfter: '米',
      },
      rules: 'required',
    },
    {
      fieldName: 'roadSurfaceTemp',
      label: '路面温度',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入路面温度（单位：℃）',
        min: -40,
        max: 80,
        precision: 1,
        addonAfter: '℃',
      },
      rules: 'required',
    },
    {
      fieldName: 'trafficFlow',
      label: '交通流量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入交通流量（单位：辆/小时）',
        min: 0,
        precision: 0,
        addonAfter: '辆/小时',
      },
      rules: 'required',
    },
    {
      fieldName: 'warningCount',
      label: '预警数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入预警数',
        min: 0,
        precision: 0,
        addonAfter: '条',
      },
      rules: 'required',
    },
    {
      fieldName: 'workOrderCount',
      label: '工单数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入工单数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'disposalCompleteCount',
      label: '处置完成数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入处置完成数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'verificationPassRate',
      label: '核查通过率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入核查通过率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceOnlineRate',
      label: '设备在线率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入设备在线率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'statisticsTimeRange',
      label: '统计时间范围',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入统计时间范围（如：2024-06-01 ~ 2024-06-30）',
        maxlength: 50,
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate',
      label: '环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoYChangeRate',
      label: '同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'indexChangeTrend',
      label: '指标变化趋势',
      component: 'Input',
      componentProps: {
        type: 'textarea',
        placeholder: '请输入指标变化趋势分析（包含坑洼、裂缝、处置效率等维度）',
        rows: 4,
        maxlength: 500,
      },
      labelWidth: '130',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为出入口管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'roadSectionName',
      title: '路段名称',
      minWidth: 220,
      sortable: true,
      slots: { default: 'roadSectionName' },
    },
    {
      field: 'deviceCode',
      title: '设备编号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'potholeCount',
      title: '坑洼数量',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'crackLength',
      title: '裂缝长度(米)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'roadSurfaceTemp',
      title: '路面温度(℃)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'trafficFlow',
      title: '交通流量(辆/小时)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'warningCount',
      title: '预警数',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'workOrderCount',
      title: '工单数',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'disposalCompleteCount',
      title: '处置完成数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'verificationPassRate',
      title: '核查通过率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deviceOnlineRate',
      title: '设备在线率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'statisticsTimeRange',
      title: '统计时间范围',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'momChangeRate',
      title: '环比变化率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'yoYChangeRate',
      title: '同比变化率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'indexChangeTrend',
      title: '指标变化趋势',
      minWidth: 350,
      sortable: false,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
