export const pageConfig = {
  apiName: 'ParkingSpaceInfo',
  title: '车位信息',
  exportName: '车位信息数据.xlsx',
  nameField: 'spaceNo',
  primaryField: 'spaceNo',
  toolbar: ['create', 'import', 'export'],
  rowActionMap: {
    未绑定: ['bind', 'edit', 'detail'],
    已绑定: ['disable', 'edit', 'detail'],
    已禁用: ['enable', 'detail'],
  },
  chart: {
    cards: [
      ['totalSpace', '总车位数'],
      ['bindSpace', '已绑定车位数', '已绑定'],
      ['unbindSpace', '未绑定车位数', '未绑定'],
      ['disableSpace', '已禁用车位数', '已禁用'],
    ],
    pie: ['pieData', 'name', 'count'],
    bar: ['barData', 'name', 'spaceCount', '各场站车位数量'],
    map: true,
  },
};

export const searchFields = [
  { field: 'spaceNo', label: '车位编号', type: 'input', required: false },
  {
    field: 'stationId',
    label: '所属场站',
    type: 'select',
    options: [],
    required: false,
    apiSource: 'StationInfo',
  },
  {
    field: 'type',
    label: '车位类型',
    type: 'select',
    options: ['普通车位', '充电车位', '无障碍车位'],
    required: false,
  },
  { field: 'deviceType', label: '设备类型', type: 'input', required: false },
  {
    field: 'status',
    label: '状态',
    type: 'select',
    options: ['未绑定', '已绑定', '已禁用'],
    required: false,
  },
];

export const formFields = [
  { field: 'spaceNo', label: '车位编号', type: 'input', required: true },
  {
    field: 'stationId',
    label: '所属场站',
    type: 'select',
    options: [],
    required: true,
    apiSource: 'StationInfo',
  },
  { field: 'garage', label: '所属车库', type: 'input', required: true },
  { field: 'location', label: '位置', type: 'input', required: true },
  {
    field: 'type',
    label: '车位类型',
    type: 'select',
    options: ['普通车位', '充电车位', '无障碍车位'],
    required: true,
  },
  { field: 'deviceType', label: '设备类型', type: 'input', required: false },
  { field: 'deviceId', label: '设备ID', type: 'number', required: false },
  { field: 'remark', label: '备注', type: 'textarea', required: false },
  { field: 'reserve1', label: '备用字段1', type: 'input', required: false },
  { field: 'reserve2', label: '备用字段2', type: 'input', required: false },
];

export const tableColumns = [
  { field: 'id', label: 'ID', minWidth: 80 },
  { field: 'spaceNo', label: '车位编号', minWidth: 140, drillType: 'detail' },
  {
    field: 'stationId',
    label: '所属场站',
    minWidth: 140,
    drillType: 'dialog',
    drillLabel: '场站详情',
  },
  { field: 'garage', label: '所属车库', minWidth: 140, drillType: 'filter' },
  { field: 'location', label: '位置', minWidth: 140 },
  { field: 'type', label: '车位类型', minWidth: 120, drillType: 'filter' },
  { field: 'deviceType', label: '设备类型', minWidth: 120, drillType: 'filter' },
  {
    field: 'qrcode',
    label: '车位二维码',
    minWidth: 140,
    drillType: 'download',
    drillLabel: '车位二维码',
  },
  { field: 'status', label: '状态', minWidth: 120, drillType: 'filter' },
  { field: 'realStatus', label: '实时状态', minWidth: 120, drillType: 'filter' },
  {
    field: 'bindTime',
    label: '绑定时间',
    minWidth: 180,
    formatter: 'formatDateTime',
  },
  { field: 'bindUserId', label: '绑定用户ID', minWidth: 120 },
  { field: 'deviceId', label: '设备ID', minWidth: 120 },
  {
    field: 'statusUpdateTime',
    label: '状态更新时间',
    minWidth: 180,
    formatter: 'formatDateTime',
  },
  { field: 'remark', label: '备注', minWidth: 140 },
  { field: 'creator', label: '创建者', minWidth: 120, drillType: 'filter' },
  {
    field: 'createTime',
    label: '创建时间',
    minWidth: 180,
    formatter: 'formatDateTime',
  },
  { field: 'updater', label: '更新者', minWidth: 120, drillType: 'filter' },
  {
    field: 'updateTime',
    label: '更新时间',
    minWidth: 180,
    formatter: 'formatDateTime',
  },
];

export const detailFields = [
  { key: 'id', label: 'ID', section: '基础信息' },
  { key: 'spaceNo', label: '车位编号', section: '基础信息' },
  { key: 'stationId', label: '所属场站ID', section: '基础信息' },
  { key: 'garage', label: '所属车库', section: '基础信息' },
  { key: 'location', label: '位置', section: '基础信息' },
  { key: 'type', label: '车位类型', section: '基础信息' },
  { key: 'deviceType', label: '设备类型', section: '基础信息' },
  { key: 'status', label: '状态', section: '基础信息' },
  { key: 'realStatus', label: '实时状态', section: '基础信息' },
  { key: 'deviceId', label: '设备ID', section: '绑定信息' },
  { key: 'bindUserId', label: '绑定用户ID', section: '绑定信息' },
  { key: 'bindTime', label: '绑定时间', section: '绑定信息' },
  { key: 'qrcode', label: '车位二维码', section: '绑定信息' },
  { key: 'statusUpdateTime', label: '状态更新时间', section: '运营信息' },
  { key: 'remark', label: '备注', section: '运营信息' },
  { key: 'creator', label: '创建者', section: '审计信息' },
  { key: 'createTime', label: '创建时间', section: '审计信息' },
  { key: 'updater', label: '更新者', section: '审计信息' },
  { key: 'updateTime', label: '更新时间', section: '审计信息' },
];
