/** 表格初始数据 - 改造为占道经营周度统计分析数据 */
export const dataList = () => [
  {
    occupiedRoadSiteCount: 23,
    mobileVendorCount: 45,
    rectifiedOccupiedRoadCount: 18,
    keySectionControlEffectiveness: 85.5,
    convenienceShedInhabitantCount: 12,
    momChangeRate: 12.3,
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    occupiedRoadSiteCount: 18,
    mobileVendorCount: 38,
    rectifiedOccupiedRoadCount: 15,
    keySectionControlEffectiveness: 91.2,
    convenienceShedInhabitantCount: 10,
    momChangeRate: -5.2,
    weekStatisticsPeriod: '2024-06-10 ~ 2024-06-16',
  },
  {
    occupiedRoadSiteCount: 32,
    mobileVendorCount: 52,
    rectifiedOccupiedRoadCount: 22,
    keySectionControlEffectiveness: 78.8,
    convenienceShedInhabitantCount: 15,
    momChangeRate: 22.1,
    weekStatisticsPeriod: '2024-06-03 ~ 2024-06-09',
  },
  {
    occupiedRoadSiteCount: 15,
    mobileVendorCount: 28,
    rectifiedOccupiedRoadCount: 12,
    keySectionControlEffectiveness: 94.6,
    convenienceShedInhabitantCount: 8,
    momChangeRate: -18.9,
    weekStatisticsPeriod: '2024-05-27 ~ 2024-06-02',
  },
  {
    occupiedRoadSiteCount: 27,
    mobileVendorCount: 48,
    rectifiedOccupiedRoadCount: 20,
    keySectionControlEffectiveness: 82.3,
    convenienceShedInhabitantCount: 11,
    momChangeRate: 15.4,
    weekStatisticsPeriod: '2024-05-20 ~ 2024-05-26',
  },
  {
    occupiedRoadSiteCount: 21,
    mobileVendorCount: 36,
    rectifiedOccupiedRoadCount: 16,
    keySectionControlEffectiveness: 88.9,
    convenienceShedInhabitantCount: 9,
    momChangeRate: -8.7,
    weekStatisticsPeriod: '2024-05-13 ~ 2024-05-19',
  },
  {
    occupiedRoadSiteCount: 35,
    mobileVendorCount: 58,
    rectifiedOccupiedRoadCount: 25,
    keySectionControlEffectiveness: 76.4,
    convenienceShedInhabitantCount: 14,
    momChangeRate: 25.8,
    weekStatisticsPeriod: '2024-05-06 ~ 2024-05-12',
  },
  {
    occupiedRoadSiteCount: 19,
    mobileVendorCount: 33,
    rectifiedOccupiedRoadCount: 14,
    keySectionControlEffectiveness: 92.1,
    convenienceShedInhabitantCount: 7,
    momChangeRate: -12.6,
    weekStatisticsPeriod: '2024-04-29 ~ 2024-05-05',
  },
  {
    occupiedRoadSiteCount: 26,
    mobileVendorCount: 44,
    rectifiedOccupiedRoadCount: 19,
    keySectionControlEffectiveness: 84.7,
    convenienceShedInhabitantCount: 10,
    momChangeRate: 18.3,
    weekStatisticsPeriod: '2024-04-22 ~ 2024-04-28',
  },
  {
    occupiedRoadSiteCount: 20,
    mobileVendorCount: 35,
    rectifiedOccupiedRoadCount: 13,
    keySectionControlEffectiveness: 90.5,
    convenienceShedInhabitantCount: 8,
    momChangeRate: -15.2,
    weekStatisticsPeriod: '2024-04-15 ~ 2024-04-21',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为占道经营周度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'occupiedRoadSiteCount',
      label: '占道经营点位数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入占道经营点位数量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'mobileVendorCount',
      label: '流动摊贩数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入流动摊贩数量',
        min: 0,
        precision: 0,
        addonAfter: '人',
      },
      rules: 'required',
    },
    {
      fieldName: 'rectifiedOccupiedRoadCount',
      label: '违规占道整改完成数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入违规占道整改完成数量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'keySectionControlEffectiveness',
      label: '重点路段管控成效',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入重点路段管控成效（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'convenienceShedInhabitantCount',
      label: '便民疏导点入驻数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入便民疏导点入驻数量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate',
      label: '环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekStatisticsPeriod',
      label: '周统计时段',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周统计时段（如：2024-06-17 ~ 2024-06-23）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为占道经营周度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'occupiedRoadSiteCount',
      title: '占道经营点位数量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'mobileVendorCount',
      title: '流动摊贩数量',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'rectifiedOccupiedRoadCount',
      title: '违规占道整改完成数量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'keySectionControlEffectiveness',
      title: '重点路段管控成效(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'convenienceShedInhabitantCount',
      title: '便民疏导点入驻数量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'momChangeRate',
      title: '环比变化率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'weekStatisticsPeriod',
      title: '周统计时段',
      minWidth: 180,
      sortable: false,
    },
  ];
}
