/** 表格初始数据 - 泉州市区充电停车异常订单数据 */
export const dataList = () => [
  {
    orderNumber: 'YC-CZ-QZ-20240601-0001',
    refOrderNumber: 'CZ-TC-QZ-20240601-0001',
    orderType: '充电+停车',
    errorType: '金额异常',
    identifyTime: '2024-06-01 09:28:18',
    handleStatus: '已处理',
    stationName: '丰泽区行政中心充电站',
    handleUser: '系统',
    handleTime: '2024-06-01 09:30:00',
    handleResult: '已修正',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 09:30:10',
  },
  {
    orderNumber: 'YC-CZ-QZ-20240601-0002',
    refOrderNumber: 'CZ-TC-QZ-20240601-0002',
    orderType: '仅充电',
    errorType: '支付失败',
    identifyTime: '2024-06-01 10:15:36',
    handleStatus: '已处理',
    stationName: '东海泰禾广场充电站',
    handleUser: '系统',
    handleTime: '2024-06-01 10:16:00',
    handleResult: '已重试',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 10:16:10',
  },
  {
    orderNumber: 'YC-CZ-QZ-20240601-0003',
    refOrderNumber: 'CZ-TC-QZ-20240601-0003',
    orderType: '停车+充电',
    errorType: '时长异常',
    identifyTime: '2024-06-01 11:02:50',
    handleStatus: '已处理',
    stationName: '西湖公园西门停车场',
    handleUser: '系统',
    handleTime: '2024-06-01 11:03:00',
    handleResult: '已修正',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 11:03:10',
  },
  {
    orderNumber: 'YC-CZ-QZ-20240601-0004',
    refOrderNumber: 'CZ-TC-QZ-20240601-0004',
    orderType: '仅停车',
    errorType: '状态异常',
    identifyTime: '2024-06-01 14:36:05',
    handleStatus: '已处理',
    stationName: '华侨大学充电站',
    handleUser: '系统',
    handleTime: '2024-06-01 14:37:00',
    handleResult: '已同步',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 14:37:10',
  },
  {
    orderNumber: 'YC-CZ-QZ-20240601-0005',
    refOrderNumber: 'CZ-TC-QZ-20240601-0005',
    orderType: '充电+停车',
    errorType: '优惠异常',
    identifyTime: '2024-06-01 15:48:22',
    handleStatus: '已处理',
    stationName: '泉秀街沉州停车场',
    handleUser: '系统',
    handleTime: '2024-06-01 15:49:00',
    handleResult: '已修正',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 15:49:10',
  },
  {
    orderNumber: 'YC-CZ-QZ-20240601-0006',
    refOrderNumber: 'CZ-TC-QZ-20240601-0006',
    orderType: '仅充电',
    errorType: '设备离线',
    identifyTime: '2024-06-01 16:30:58',
    handleStatus: '已处理',
    stationName: '城东万达广场充电站',
    handleUser: '系统',
    handleTime: '2024-06-01 16:31:00',
    handleResult: '已恢复',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 16:31:10',
  },
  {
    orderNumber: 'YC-CZ-QZ-20240601-0007',
    refOrderNumber: 'CZ-TC-QZ-20240601-0007',
    orderType: '停车+充电',
    errorType: '金额异常',
    identifyTime: '2024-06-01 17:22:11',
    handleStatus: '已处理',
    stationName: '北峰街道闽台缘停车场',
    handleUser: '系统',
    handleTime: '2024-06-01 17:23:00',
    handleResult: '已修正',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 17:23:10',
  },
  {
    orderNumber: 'YC-CZ-QZ-20240601-0008',
    refOrderNumber: 'CZ-TC-QZ-20240601-0008',
    orderType: '仅停车',
    errorType: '支付超时',
    identifyTime: '2024-06-01 18:15:46',
    handleStatus: '已处理',
    stationName: '清源山东方驾校停车场',
    handleUser: '系统',
    handleTime: '2024-06-01 18:16:00',
    handleResult: '已关闭',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 18:16:10',
  },
  {
    orderNumber: 'YC-CZ-QZ-20240601-0009',
    refOrderNumber: 'CZ-TC-QZ-20240601-0009',
    orderType: '充电+停车',
    errorType: '时长异常',
    identifyTime: '2024-06-01 19:05:34',
    handleStatus: '已处理',
    stationName: '宝洲路万达公馆充电站',
    handleUser: '系统',
    handleTime: '2024-06-01 19:06:00',
    handleResult: '已修正',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 19:06:10',
  },
  {
    orderNumber: 'YC-CZ-QZ-20240601-0010',
    refOrderNumber: 'CZ-TC-QZ-20240601-0010',
    orderType: '仅充电',
    errorType: '状态异常',
    identifyTime: '2024-06-01 20:38:29',
    handleStatus: '已处理',
    stationName: '美食街公共充电站',
    handleUser: '系统',
    handleTime: '2024-06-01 20:39:00',
    handleResult: '已同步',
    ignoreReason: '无',
    updateUser: '系统',
    updateTime: '2024-06-01 20:39:10',
  },
];

/** 搜索表单 - 异常订单查询条件 */
export function useFormSchema() {
  return [
    {
      fieldName: 'refOrderNumber',
      label: '关联订单编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联订单编号',
        maxLength: 50,
      },
      labelWidth: 130,
    },
    {
      fieldName: 'orderType',
      label: '订单类型',
      component: 'Select',
      componentProps: {
        allowClear: true,
        placeholder: '请选择订单类型',
      },
      labelWidth: 130,
    },
    {
      fieldName: 'errorType',
      label: '异常类型',
      component: 'Select',
      componentProps: {
        allowClear: true,
        placeholder: '请选择异常类型',
      },
      labelWidth: 130,
    },
    {
      fieldName: 'handleStatus',
      label: '处置状态',
      component: 'Select',
      componentProps: {
        allowClear: true,
        placeholder: '请选择处置状态',
      },
      labelWidth: 130,
    },
    {
      fieldName: 'stationName',
      label: '所属场站',
      component: 'Select',
      componentProps: {
        allowClear: true,
        placeholder: '请选择所属场站',
      },
      labelWidth: 130,
    },
    {
      fieldName: 'handleUser',
      label: '处置人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处置人',
        maxLength: 50,
      },
      labelWidth: 130,
    },
    {
      fieldName: 'handleResult',
      label: '处置结果',
      component: 'Select',
      componentProps: {
        allowClear: true,
        placeholder: '请选择处置结果',
      },
      labelWidth: 130,
    },
    {
      fieldName: 'updateUser',
      label: '操作人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入操作人',
        maxLength: 50,
      },
      labelWidth: 130,
    },
  ];
}

/** 表格列配置 - 异常订单（无钻取、无插槽、纯展示） */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'refOrderNumber',
      title: '关联订单编号',
      minWidth: 220,
      sortable: true,
    },
    {
      field: 'orderType',
      title: '订单类型',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'errorType',
      title: '异常类型',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'identifyTime',
      title: '识别时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'handleStatus',
      title: '处置状态',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'stationName',
      title: '所属场站',
      minWidth: 220,
      sortable: true,
    },
    {
      field: 'handleUser',
      title: '处置人',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'handleTime',
      title: '处置时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'handleResult',
      title: '处置结果',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'ignoreReason',
      title: '忽略理由',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'updateUser',
      title: '操作人',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'updateTime',
      title: '更新时间',
      minWidth: 200,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
