/** 表格初始数据 - 窨井盖设施处置中工单数据 */
export const dataList = () => [
  {
    orderNo: 'FJ-YG-202406-001',
    warnNo: 'FJ-YJ-202406-001',
    coverNo: 'YJG-001',
    roadName: '福州市鼓楼区杨桥东路',
    abnormalType: '倾斜角度异常',
    riskLevel: '高风险',
    assignStaff: '陈铭（FJYW001）',
    createTime: '2024-06-15 09:00:00',
    dealLimit: 24,
    processStatus: '处置中',
    remainTime: 6,
    arriveTime: '2024-06-15 10:30:00',
    updateTime: '2024-06-15 16:00:00',
    siteData: '倾斜角度15度，超过阈值10度',
    overTimeFlag: '即将超时',
    disposalMeasure: '已开始调整窨井盖位置，预计1小时内完成',
  },
  {
    orderNo: 'FJ-YG-202406-002',
    warnNo: 'FJ-YJ-202406-002',
    coverNo: 'YJG-002',
    roadName: '厦门市思明区鹭江道',
    abnormalType: '振动异常',
    riskLevel: '中风险',
    assignStaff: '林晓婷（FJYW002）',
    createTime: '2024-06-14 15:00:00',
    dealLimit: 48,
    processStatus: '现场处置',
    remainTime: 20,
    arriveTime: '2024-06-14 16:15:00',
    updateTime: '2024-06-15 10:00:00',
    siteData: '振动频率30Hz，超过阈值25Hz',
    overTimeFlag: '未超时',
    disposalMeasure: '已检查窨井盖固定情况，发现松动，正在加固',
  },
  {
    orderNo: 'FJ-YG-202406-003',
    warnNo: 'FJ-YJ-202406-003',
    coverNo: 'YJG-003',
    roadName: '泉州市丰泽区刺桐路',
    abnormalType: '设备离线',
    riskLevel: '低风险',
    assignStaff: '王志远（FJYW003）',
    createTime: '2024-06-15 10:00:00',
    dealLimit: 12,
    processStatus: '前往现场',
    remainTime: 8,
    arriveTime: '',
    updateTime: '2024-06-15 11:00:00',
    siteData: '设备离线超过2小时',
    overTimeFlag: '未超时',
    disposalMeasure: '运维员正在前往现场检查设备',
  },
  {
    orderNo: 'FJ-YG-202406-004',
    warnNo: 'FJ-YJ-202406-004',
    coverNo: 'YJG-004',
    roadName: '漳州市芗城区胜利路',
    abnormalType: '倾斜角度异常',
    riskLevel: '高风险',
    assignStaff: '黄丽萍（FJYW004）',
    createTime: '2024-06-15 08:00:00',
    dealLimit: 18,
    processStatus: '现场处置',
    remainTime: 4,
    arriveTime: '2024-06-15 08:45:00',
    updateTime: '2024-06-15 14:00:00',
    siteData: '倾斜角度18度，超过阈值10度',
    overTimeFlag: '即将超时',
    disposalMeasure: '正在调整窨井盖位置，已完成50%',
  },
  {
    orderNo: 'FJ-YG-202406-005',
    warnNo: 'FJ-YJ-202406-005',
    coverNo: 'YJG-005',
    roadName: '莆田市城厢区荔城南大道',
    abnormalType: '振动异常',
    riskLevel: '中风险',
    assignStaff: '郑建明（FJYW005）',
    createTime: '2024-06-13 20:00:00',
    dealLimit: 24,
    processStatus: '待处置',
    remainTime: 0,
    arriveTime: '',
    updateTime: '2024-06-14 10:00:00',
    siteData: '振动频率28Hz，超过阈值25Hz',
    overTimeFlag: '已超时',
    disposalMeasure: '等待运维员分配',
  },
];


/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施处置中工单表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'orderNo',
      label: '处置工单编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处置工单编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'warnNo',
      label: '关联预警编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联预警编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'coverNo',
      label: '井盖编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入井盖编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'roadName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
        maxLength: 100,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '倾斜角度异常', value: '倾斜角度异常' },
          { label: '振动异常', value: '振动异常' },
          { label: '设备离线', value: '设备离线' },
          { label: '设备异常', value: '设备异常' },
          { label: '轻微倾斜', value: '轻微倾斜' },
        ],
        placeholder: '请选择异常类型',
        showSearch: true,
      },
      fieldName: 'abnormalType',
      label: '异常类型',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '低风险', value: '低风险' },
          { label: '中风险', value: '中风险' },
          { label: '高风险', value: '高风险' },
        ],
        placeholder: '请选择安全风险等级',
        showSearch: true,
      },
      fieldName: 'riskLevel',
      label: '安全风险等级',
      rules: 'required',
    },
    {
      fieldName: 'assignStaff',
      label: '指派运维员',
      component: 'Input',
      componentProps: {
        placeholder: '请输入指派运维员',
        maxLength: 100,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'createTime',
      label: '创建时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择创建时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'dealLimit',
      label: '处置时限',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入处置时限（单位：小时）',
        min: 1,
        precision: 0,
        addonAfter: '小时',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '待处置', value: '待处置' },
          { label: '前往现场', value: '前往现场' },
          { label: '现场处置', value: '现场处置' },
          { label: '处置中', value: '处置中' },
        ],
        placeholder: '请选择当前进度',
        showSearch: true,
      },
      fieldName: 'processStatus',
      label: '当前进度',
      rules: 'required',
    },
    {
      fieldName: 'arriveTime',
      label: '抵达现场时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择抵达现场时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      fieldName: 'updateTime',
      label: '进度更新时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择进度更新时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      fieldName: 'siteData',
      label: '现场处置数据',
      component: 'Input',
      componentProps: {
        placeholder: '请输入现场处置数据',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      labelWidth: '120',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未超时', value: '未超时' },
          { label: '即将超时', value: '即将超时' },
          { label: '已超时', value: '已超时' },
        ],
        placeholder: '请选择超时提醒标识',
        showSearch: true,
      },
      fieldName: 'overTimeFlag',
      label: '超时提醒标识',
    },
    {
      fieldName: 'disposalMeasure',
      label: '处置措施摘要',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处置措施摘要',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      labelWidth: '120',
    },
  ];
}


/** 表格字段 - 窨井盖设施处置中工单表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'orderNo',
      title: '处置工单编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'orderNo' },
    },
    {
      field: 'warnNo',
      title: '关联预警编号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'coverNo',
      title: '井盖编号',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'roadName',
      title: '路段名称',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'abnormalType',
      title: '异常类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'riskLevel',
      title: '安全风险等级',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'assignStaff',
      title: '指派运维员',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'dealLimit',
      title: '处置时限(小时)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'processStatus',
      title: '当前进度',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'remainTime',
      title: '剩余处置时间(小时)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'arriveTime',
      title: '抵达现场时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'updateTime',
      title: '进度更新时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'siteData',
      title: '现场处置数据',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'overTimeFlag',
      title: '超时提醒标识',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'disposalMeasure',
      title: '处置措施摘要',
      minWidth: 220,
      sortable: false,
    },
    {
      title: '操作',
      width: 150,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

