/** 表格初始数据 - 周乱贴乱画监测统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    weekIllegalPostingTotalCount: 156,
    weekCleanupCompletionRate: 89.5,
    weekIllegalNumberShutdownCount: 23,
    weekKeyAreaControlEffectiveness: 78.2,
    weekRepeatedPostingPointCount: 45,
    momChangeRate: 12.8,
    yoyChangeRate: 15.6,
    detailDataByArea: '鼓楼中心区: 89次；鼓楼西区: 67次',
    detailDataByPointType: '墙面乱贴: 98次；电线杆乱贴: 58次',
    detailDataByAdContent: '商业广告: 112次；其他信息: 44次',
    detailDataByCleanupUnit: '环卫部门: 102次；社区: 54次',
    momDetailAnalysis: '墙面乱贴环比+15.2%，商业广告环比+18.7%',
    yoyDetailAnalysis: '墙面乱贴同比+18.9%，商业广告同比+22.1%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    areaName: '台江区',
    weekIllegalPostingTotalCount: 98,
    weekCleanupCompletionRate: 92.3,
    weekIllegalNumberShutdownCount: 15,
    weekKeyAreaControlEffectiveness: 85.7,
    weekRepeatedPostingPointCount: 28,
    momChangeRate: -3.2,
    yoyChangeRate: 8.4,
    detailDataByArea: '台江东区: 52次；台江西区: 46次',
    detailDataByPointType: '墙面乱贴: 58次；电线杆乱贴: 40次',
    detailDataByAdContent: '商业广告: 65次；其他信息: 33次',
    detailDataByCleanupUnit: '环卫部门: 68次；社区: 30次',
    momDetailAnalysis: '墙面乱贴环比-5.8%，其他信息环比-2.1%',
    yoyDetailAnalysis: '墙面乱贴同比+12.3%，其他信息同比+5.7%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    areaName: '仓山区',
    weekIllegalPostingTotalCount: 203,
    weekCleanupCompletionRate: 85.7,
    weekIllegalNumberShutdownCount: 31,
    weekKeyAreaControlEffectiveness: 72.8,
    weekRepeatedPostingPointCount: 67,
    momChangeRate: 18.9,
    yoyChangeRate: 22.4,
    detailDataByArea: '仓山南区: 112次；仓山北区: 91次',
    detailDataByPointType: '墙面乱贴: 128次；电线杆乱贴: 75次',
    detailDataByAdContent: '商业广告: 145次；其他信息: 58次',
    detailDataByCleanupUnit: '环卫部门: 132次；社区: 71次',
    momDetailAnalysis: '墙面乱贴环比+21.3%，商业广告环比+25.6%',
    yoyDetailAnalysis: '墙面乱贴同比+25.8%，商业广告同比+28.9%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    areaName: '晋安区',
    weekIllegalPostingTotalCount: 76,
    weekCleanupCompletionRate: 94.1,
    weekIllegalNumberShutdownCount: 8,
    weekKeyAreaControlEffectiveness: 89.3,
    weekRepeatedPostingPointCount: 19,
    momChangeRate: -6.7,
    yoyChangeRate: -3.2,
    detailDataByArea: '晋安东区: 42次；晋安西区: 34次',
    detailDataByPointType: '墙面乱贴: 45次；电线杆乱贴: 31次',
    detailDataByAdContent: '商业广告: 52次；其他信息: 24次',
    detailDataByCleanupUnit: '环卫部门: 48次；社区: 28次',
    momDetailAnalysis: '墙面乱贴环比-8.9%，其他信息环比-1.2%',
    yoyDetailAnalysis: '墙面乱贴同比-1.8%，其他信息同比-4.5%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    areaName: '马尾区',
    weekIllegalPostingTotalCount: 45,
    weekCleanupCompletionRate: 96.8,
    weekIllegalNumberShutdownCount: 5,
    weekKeyAreaControlEffectiveness: 91.2,
    weekRepeatedPostingPointCount: 12,
    momChangeRate: 2.1,
    yoyChangeRate: 5.9,
    detailDataByArea: '马尾主城区: 28次；马尾工业区: 17次',
    detailDataByPointType: '墙面乱贴: 25次；电线杆乱贴: 20次',
    detailDataByAdContent: '商业广告: 32次；其他信息: 13次',
    detailDataByCleanupUnit: '环卫部门: 30次；社区: 15次',
    momDetailAnalysis: '墙面乱贴环比+3.4%，商业广告环比+1.8%',
    yoyDetailAnalysis: '墙面乱贴同比+4.2%，商业广告同比+6.7%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    areaName: '长乐区',
    weekIllegalPostingTotalCount: 134,
    weekCleanupCompletionRate: 87.9,
    weekIllegalNumberShutdownCount: 19,
    weekKeyAreaControlEffectiveness: 80.5,
    weekRepeatedPostingPointCount: 38,
    momChangeRate: 15.4,
    yoyChangeRate: 18.7,
    detailDataByArea: '长乐老城区: 78次；长乐新区: 56次',
    detailDataByPointType: '墙面乱贴: 82次；电线杆乱贴: 52次',
    detailDataByAdContent: '商业广告: 95次；其他信息: 39次',
    detailDataByCleanupUnit: '环卫部门: 89次；社区: 45次',
    momDetailAnalysis: '墙面乱贴环比+17.6%，商业广告环比+20.3%',
    yoyDetailAnalysis: '墙面乱贴同比+21.4%，商业广告同比+24.1%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    areaName: '福清市',
    weekIllegalPostingTotalCount: 189,
    weekCleanupCompletionRate: 83.2,
    weekIllegalNumberShutdownCount: 27,
    weekKeyAreaControlEffectiveness: 75.8,
    weekRepeatedPostingPointCount: 59,
    momChangeRate: 19.3,
    yoyChangeRate: 24.6,
    detailDataByArea: '福清市区: 112次；福清郊区: 77次',
    detailDataByPointType: '墙面乱贴: 118次；电线杆乱贴: 71次',
    detailDataByAdContent: '商业广告: 135次；其他信息: 54次',
    detailDataByCleanupUnit: '环卫部门: 125次；社区: 64次',
    momDetailAnalysis: '墙面乱贴环比+22.1%，商业广告环比+26.8%',
    yoyDetailAnalysis: '墙面乱贴同比+27.3%，商业广告同比+30.1%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    areaName: '闽侯县',
    weekIllegalPostingTotalCount: 67,
    weekCleanupCompletionRate: 91.5,
    weekIllegalNumberShutdownCount: 11,
    weekKeyAreaControlEffectiveness: 86.4,
    weekRepeatedPostingPointCount: 22,
    momChangeRate: 8.7,
    yoyChangeRate: 11.2,
    detailDataByArea: '闽侯县城: 45次；闽侯乡镇: 22次',
    detailDataByPointType: '墙面乱贴: 38次；电线杆乱贴: 29次',
    detailDataByAdContent: '商业广告: 42次；其他信息: 25次',
    detailDataByCleanupUnit: '环卫部门: 39次；社区: 28次',
    momDetailAnalysis: '墙面乱贴环比+10.5%，其他信息环比+3.2%',
    yoyDetailAnalysis: '墙面乱贴同比+13.8%，其他信息同比+6.9%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    areaName: '连江县',
    weekIllegalPostingTotalCount: 53,
    weekCleanupCompletionRate: 93.7,
    weekIllegalNumberShutdownCount: 7,
    weekKeyAreaControlEffectiveness: 88.9,
    weekRepeatedPostingPointCount: 15,
    momChangeRate: -1.2,
    yoyChangeRate: 4.8,
    detailDataByArea: '连江县城: 32次；连江乡镇: 21次',
    detailDataByPointType: '墙面乱贴: 35次；电线杆乱贴: 18次',
    detailDataByAdContent: '商业广告: 39次；其他信息: 14次',
    detailDataByCleanupUnit: '环卫部门: 34次；社区: 19次',
    momDetailAnalysis: '墙面乱贴环比-2.8%，其他信息环比-0.9%',
    yoyDetailAnalysis: '墙面乱贴同比+3.1%，其他信息同比+2.4%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    areaName: '平潭综合实验区',
    weekIllegalPostingTotalCount: 32,
    weekCleanupCompletionRate: 95.2,
    weekIllegalNumberShutdownCount: 3,
    weekKeyAreaControlEffectiveness: 92.1,
    weekRepeatedPostingPointCount: 8,
    momChangeRate: 5.6,
    yoyChangeRate: 7.3,
    detailDataByArea: '平潭主岛: 25次；平潭周边: 7次',
    detailDataByPointType: '墙面乱贴: 28次；电线杆乱贴: 4次',
    detailDataByAdContent: '商业广告: 30次；其他信息: 2次',
    detailDataByCleanupUnit: '环卫部门: 27次；社区: 5次',
    momDetailAnalysis: '墙面乱贴环比+6.8%，商业广告环比+8.1%',
    yoyDetailAnalysis: '墙面乱贴同比+9.2%，商业广告同比+10.5%',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 周乱贴乱画监测统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'weekIllegalPostingTotalCount',
      label: '周乱贴乱画点位总数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周乱贴乱画点位总数',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekCleanupCompletionRate',
      label: '周清理完成率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周清理完成率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekIllegalNumberShutdownCount',
      label: '周非法号码停机数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周非法号码停机数量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekKeyAreaControlEffectiveness',
      label: '周重点区域管控成效',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周重点区域管控成效（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekRepeatedPostingPointCount',
      label: '周重复乱贴点位数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周重复乱贴点位数量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'momChangeRate',
      label: '环比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyChangeRate',
      label: '同比变化率(%)',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailDataByArea',
      label: '按区域拆分周明细数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按区域拆分的周明细数据（如：区域A:次数；区域B:次数）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailDataByPointType',
      label: '按点位类型拆分周明细数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按点位类型拆分的周明细数据（如：墙面乱贴:次数；电线杆乱贴:次数）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailDataByAdContent',
      label: '按广告内容拆分周明细数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按广告内容拆分的周明细数据（如：商业广告:次数；其他信息:次数）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailDataByCleanupUnit',
      label: '按清理责任单位拆分周明细数据',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按清理责任单位拆分的周明细数据（如：环卫部门:次数；社区:次数）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'momDetailAnalysis',
      label: '环比分析结果',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入环比分析结果（如：墙面乱贴环比+15.2%）',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyDetailAnalysis',
      label: '同比分析结果',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比分析结果（如：墙面乱贴同比+18.9%）',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'weekStatisticsPeriod',
      label: '周统计时段',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周统计时段（如：2024-06-17 ~ 2024-06-23）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 周乱贴乱画监测统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'weekIllegalPostingTotalCount',
      title: '周乱贴乱画点位总数',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'weekCleanupCompletionRate',
      title: '周清理完成率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'weekIllegalNumberShutdownCount',
      title: '周非法号码停机数量',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'weekKeyAreaControlEffectiveness',
      title: '周重点区域管控成效(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'weekRepeatedPostingPointCount',
      title: '周重复乱贴点位数量',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'momChangeRate',
      title: '环比变化率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'yoyChangeRate',
      title: '同比变化率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'detailDataByArea',
      title: '按区域拆分周明细数据',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailDataByPointType',
      title: '按点位类型拆分周明细数据',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailDataByAdContent',
      title: '按广告内容拆分周明细数据',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'detailDataByCleanupUnit',
      title: '按清理责任单位拆分周明细数据',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'momDetailAnalysis',
      title: '环比分析结果',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'yoyDetailAnalysis',
      title: '同比分析结果',
      minWidth: 160,
      sortable: false,
    },
    {
      field: 'weekStatisticsPeriod',
      title: '周统计时段',
      minWidth: 150,
      sortable: false,
    },
    // {
    //   title: '操作',
    //   width: 80,
    //   fixed: 'right',
    //   slots: { default: 'actions' },
    // },
  ];
}
