// data.js
/** 设备异常报表 - 初始数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "faultId": "FAULT-20260205001",
      "deviceCode": "DEV-001-001",
      "deviceType": "入口道闸",
      "areaCode": "440106",
      "areaName": "天河区",
      "faultTime": "2026-02-05 08:30",
      "faultType": "硬件故障",
      "faultDescription": "道闸无法正常抬起",
      "disposalStatus": "待处理",
      "disposalTime": "",
      "processor": "",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 2,
      "faultId": "FAULT-20260205002",
      "deviceCode": "DEV-002-001",
      "deviceType": "车位相机",
      "areaCode": "440104",
      "areaName": "越秀区",
      "faultTime": "2026-02-05 10:15",
      "faultType": "网络故障",
      "faultDescription": "相机无法连接服务器",
      "disposalStatus": "处理中",
      "disposalTime": "2026-02-05 11:30",
      "processor": "张三",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 3,
      "faultId": "FAULT-20260205003",
      "deviceCode": "DEV-003-001",
      "deviceType": "支付终端",
      "areaCode": "440105",
      "areaName": "海珠区",
      "faultTime": "2026-02-05 14:45",
      "faultType": "软件故障",
      "faultDescription": "支付界面卡死",
      "disposalStatus": "已处理",
      "disposalTime": "2026-02-05 16:20",
      "processor": "李四",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 4,
      "faultId": "FAULT-20260204001",
      "deviceCode": "DEV-004-001",
      "deviceType": "监控摄像头",
      "areaCode": "440111",
      "areaName": "白云区",
      "faultTime": "2026-02-04 09:20",
      "faultType": "硬件故障",
      "faultDescription": "摄像头画面模糊",
      "disposalStatus": "待处理",
      "disposalTime": "",
      "processor": "",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 5,
      "faultId": "FAULT-20260204002",
      "deviceCode": "DEV-005-001",
      "deviceType": "LED显示屏",
      "areaCode": "440112",
      "areaName": "黄埔区",
      "faultTime": "2026-02-04 13:10",
      "faultType": "电源故障",
      "faultDescription": "显示屏黑屏",
      "disposalStatus": "处理中",
      "disposalTime": "2026-02-04 14:30",
      "processor": "王五",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 6,
      "faultId": "FAULT-20260203001",
      "deviceCode": "DEV-001-002",
      "deviceType": "入口道闸",
      "areaCode": "440106",
      "areaName": "天河区",
      "faultTime": "2026-02-03 11:30",
      "faultType": "网络故障",
      "faultDescription": "道闸无法联网",
      "disposalStatus": "已处理",
      "disposalTime": "2026-02-03 13:15",
      "processor": "赵六",
      "updateTime": "2026-02-03 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 7,
      "faultId": "FAULT-20260202001",
      "deviceCode": "DEV-006-001",
      "deviceType": "出口道闸",
      "areaCode": "440103",
      "areaName": "荔湾区",
      "faultTime": "2026-02-02 15:45",
      "faultType": "软件故障",
      "faultDescription": "道闸控制程序崩溃",
      "disposalStatus": "处理中",
      "disposalTime": "2026-02-02 16:30",
      "processor": "张三",
      "updateTime": "2026-02-02 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 8,
      "faultId": "FAULT-20260201001",
      "deviceCode": "DEV-007-001",
      "deviceType": "车位相机",
      "areaCode": "440113",
      "areaName": "番禺区",
      "faultTime": "2026-02-01 18:20",
      "faultType": "硬件故障",
      "faultDescription": "相机镜头损坏",
      "disposalStatus": "待处理",
      "disposalTime": "",
      "processor": "",
      "updateTime": "2026-02-01 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 9,
      "faultId": "FAULT-20260131001",
      "deviceCode": "DEV-008-001",
      "deviceType": "支付终端",
      "areaCode": "440106",
      "areaName": "天河区",
      "faultTime": "2026-01-31 10:30",
      "faultType": "网络故障",
      "faultDescription": "支付网络异常",
      "disposalStatus": "已处理",
      "disposalTime": "2026-01-31 12:15",
      "processor": "李四",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 10,
      "faultId": "FAULT-20260130001",
      "deviceCode": "DEV-003-002",
      "deviceType": "监控摄像头",
      "areaCode": "440105",
      "areaName": "海珠区",
      "faultTime": "2026-01-30 14:20",
      "faultType": "电源故障",
      "faultDescription": "摄像头断电",
      "disposalStatus": "处理中",
      "disposalTime": "2026-01-30 15:45",
      "processor": "王五",
      "updateTime": "2026-01-30 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 11,
      "faultId": "FAULT-20260129001",
      "deviceCode": "DEV-002-002",
      "deviceType": "LED显示屏",
      "areaCode": "440104",
      "areaName": "越秀区",
      "faultTime": "2026-01-29 19:30",
      "faultType": "硬件故障",
      "faultDescription": "显示屏花屏",
      "disposalStatus": "待处理",
      "disposalTime": "",
      "processor": "",
      "updateTime": "2026-01-29 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 12,
      "faultId": "FAULT-20260128001",
      "deviceCode": "DEV-001-003",
      "deviceType": "出口道闸",
      "areaCode": "440111",
      "areaName": "白云区",
      "faultTime": "2026-01-28 09:15",
      "faultType": "软件故障",
      "faultDescription": "道闸控制软件异常",
      "disposalStatus": "已处理",
      "disposalTime": "2026-01-28 10:45",
      "processor": "赵六",
      "updateTime": "2026-01-28 18:30",
      "operator": "系统自动生成"
    }
  ];
};

/** 搜索表单配置 */
export function useFormSchema() {
  return [
    {
      fieldName: 'deviceCode',
      label: '设备编码',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入设备编码（支持模糊查询）',
        clearable: true,
      },
    },
    {
      fieldName: 'timeRange',
      label: '时间范围',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'daterange',
        'range-separator': '至',
        'start-placeholder': '开始日期',
        'end-placeholder': '结束日期',
        format: 'YYYY-MM-DD',
        'value-format': 'YYYY-MM-DD',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
      },
      fieldName: 'areaName',
      label: '行政区域',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '入口道闸', value: '入口道闸' },
          { label: '出口道闸', value: '出口道闸' },
          { label: '车位相机', value: '车位相机' },
          { label: '监控摄像头', value: '监控摄像头' },
          { label: '支付终端', value: '支付终端' },
          { label: 'LED显示屏', value: 'LED显示屏' },
          { label: '车牌识别相机', value: '车牌识别相机' },
          { label: '车位指示灯', value: '车位指示灯' },
        ],
        placeholder: '请选择设备类型',
        showSearch: true,
      },
      fieldName: 'deviceType',
      label: '设备类型',
    },
    {
      fieldName: 'faultType',
      label: '故障类型',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        options: [
          { label: '硬件故障', value: '硬件故障' },
          { label: '软件故障', value: '软件故障' },
          { label: '网络故障', value: '网络故障' },
          { label: '电源故障', value: '电源故障' },
          { label: '通讯故障', value: '通讯故障' },
          { label: '机械故障', value: '机械故障' },
        ],
        placeholder: '请选择故障类型',
      },
    },
    {
      fieldName: 'disposalStatus',
      label: '处置状态',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        options: [
          { label: '待处理', value: '待处理' },
          { label: '处理中', value: '处理中' },
          { label: '已处理', value: '已处理' },
        ],
        placeholder: '请选择处置状态',
      },
    },
  ];
}

/** 表格字段配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'faultId',
      title: '故障ID',
      minWidth: 150,
      sortable: true,
      slots: { default: 'faultId' },
    },
    {
      field: 'deviceCode',
      title: '设备编码',
      minWidth: 140,
      sortable: true,
      slots: { default: 'deviceCode' },
    },
    {
      field: 'deviceType',
      title: '设备类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 100,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'faultTime',
      title: '故障时间',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'faultType',
      title: '故障类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'faultType' },
    },
    {
      field: 'disposalStatus',
      title: '处置状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'disposalStatus' },
    },
    {
      field: 'disposalTime',
      title: '处置时间',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'processor',
      title: '处理人',
      minWidth: 100,
      sortable: true,
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑故障记录',
  addText: '新增故障记录',
  excelName: '设备异常报表',
  excelAllName: '设备异常报表.xlsx',
  total: '报表总数: 12; 今日故障: 3; 本周故障: 8;',
};
