/** 表格初始数据 - 改造为规则管理数据 */
export const dataList = () => {
  return [
    {
      id: '2',
      ruleName: ' 碧湖公园入口通行规则 ', // 规则名称
      applicableEntrance: ' 碧湖公园东门、南门 ', // 适用出入口
      passTimeSlot: '07:00-22:00', // 通行时段
      noPlateRule: ' 禁止入场 ', // 无牌车规则
      repeatEntryLimit: '30 分钟内禁止重复进场 ', // 重复进场限制
      maxStayTime: '24 小时 ', // 最长停留时长
      specialVehicleRule: ' 军警车辆免费通行 ', // 特殊车辆规则
      timeDifferentiatedRule: ' 高峰时段（08:00-10:00/17:00-19:00）单车道通行 ', // 时段差异化规则
      priority: '1', // 优先级
      effectiveStatus: ' 启用 ', // 生效状态
      conflictPrompt: ' 与「园区内部车辆规则」存在时段重叠 ', // 冲突提示
      updateTime: '2026-01-10 14:30:00', // 修改时间
      operator: ' 王管理员 ', // 操作人
    },
    {
      id: '3',
      ruleName: ' 石码镇便民停车场通行规则 ',
      applicableEntrance: ' 石码镇北门出口、西门入口 ',
      passTimeSlot: '08:00-21:00',
      noPlateRule: ' 登记后放行 ',
      repeatEntryLimit: '15 分钟内禁止重复进场 ',
      maxStayTime: '12 小时 ',
      specialVehicleRule: ' 救护车、消防车优先通行 ',
      timeDifferentiatedRule: ' 无 ',
      priority: '2',
      effectiveStatus: ' 禁用 ',
      conflictPrompt: '',
      updateTime: '2026-01-08 09:15:00',
      operator: ' 李主管 ',
    },
    {
      id: '4',
      ruleName: ' 闽齐社区 24 小时通行规则 ',
      applicableEntrance: ' 闽齐社区西门入口 ',
      passTimeSlot: '00:00-24:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: ' 无限制 ',
      maxStayTime: '72 小时 ',
      specialVehicleRule: ' 社区业主车辆无限制 ',
      timeDifferentiatedRule: ' 夜间（22:00-06:00）仅开放 1 条车道 ',
      priority: '1',
      effectiveStatus: ' 启用 ',
      conflictPrompt: '',
      updateTime: '2026-01-15 16:45:00',
      operator: ' 张管理员 ',
    },
    {
      id: '5',
      ruleName: ' 江滨路生态停车场高峰规则 ',
      applicableEntrance: ' 江滨路主入口、次入口 ',
      passTimeSlot: '06:00-24:00',
      noPlateRule: ' 登记后放行 ',
      repeatEntryLimit: '20 分钟内禁止重复进场 ',
      maxStayTime: '18 小时 ',
      specialVehicleRule: ' 新能源车辆优先通行 ',
      timeDifferentiatedRule: ' 高峰时段（07:00-09:00/18:00-20:00）开放 3 条车道 ',
      priority: '3',
      effectiveStatus: ' 启用 ',
      conflictPrompt: ' 与「节假日通行规则」存在优先级冲突 ',
      updateTime: '2026-01-12 11:20:00',
      operator: ' 陈师傅 ',
    },
    {
      id: '6',
      ruleName: ' 万达商圈停车场收费通行规则 ',
      applicableEntrance: ' 万达商圈南入口、北出口 ',
      passTimeSlot: '00:00-24:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: '30 分钟内禁止重复进场 ',
      maxStayTime: '48 小时 ',
      specialVehicleRule: ' 商场 VIP 车辆免费 2 小时 ',
      timeDifferentiatedRule: ' 节假日全车道开放，工作日开放 2 条车道 ',
      priority: '1',
      effectiveStatus: ' 启用 ',
      conflictPrompt: '',
      updateTime: '2026-01-14 10:00:00',
      operator: ' 刘经理 ',
    },
    {
      id: '7',
      ruleName: ' 武安镇公共停车场基础规则 ',
      applicableEntrance: ' 武安镇人民西路入口 ',
      passTimeSlot: '07:00-23:00',
      noPlateRule: ' 登记后放行 ',
      repeatEntryLimit: '10 分钟内禁止重复进场 ',
      maxStayTime: '24 小时 ',
      specialVehicleRule: ' 公务车辆免费通行 ',
      timeDifferentiatedRule: ' 无 ',
      priority: '2',
      effectiveStatus: ' 启用 ',
      conflictPrompt: '',
      updateTime: '2026-01-09 15:30:00',
      operator: ' 黄管理员 ',
    },
    {
      id: '8',
      ruleName: ' 绥安镇便民停车场临时规则 ',
      applicableEntrance: ' 绥安镇金浦大道出口 ',
      passTimeSlot: '08:00-20:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: ' 无限制 ',
      maxStayTime: '8 小时 ',
      specialVehicleRule: ' 无 ',
      timeDifferentiatedRule: ' 无 ',
      priority: '4',
      effectiveStatus: ' 禁用 ',
      conflictPrompt: ' 与「场地维护规则」冲突 ',
      updateTime: '2026-01-05 13:45:00',
      operator: ' 郑师傅 ',
    },
    {
      id: '9',
      ruleName: ' 巷口街道停车场收费调整规则 ',
      applicableEntrance: ' 巷口街道新华东路入口 ',
      passTimeSlot: '06:00-23:00',
      noPlateRule: ' 登记后放行 ',
      repeatEntryLimit: '25 分钟内禁止重复进场 ',
      maxStayTime: '12 小时 ',
      specialVehicleRule: ' 无 ',
      timeDifferentiatedRule: ' 收费调整期间（01-05 至 01-10）按原标准 8 折计费 ',
      priority: '3',
      effectiveStatus: ' 暂停 ',
      conflictPrompt: '',
      updateTime: '2026-01-03 08:40:00',
      operator: ' 吴主管 ',
    },
    {
      id: '10',
      ruleName: ' 蓝田街道停车场维修期间规则 ',
      applicableEntrance: ' 蓝田街道梧桥中路出口 ',
      passTimeSlot: '00:00-24:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: ' 无限制 ',
      maxStayTime: '6 小时 ',
      specialVehicleRule: ' 维修车辆优先通行 ',
      timeDifferentiatedRule: ' 维修期间（01-08 至 01-15）仅开放 1 条车道 ',
      priority: '5',
      effectiveStatus: ' 暂停 ',
      conflictPrompt: ' 与「正常通行规则」冲突 ',
      updateTime: '2026-01-07 16:20:00',
      operator: ' 林师傅 ',
    },
    {
      id: '11',
      ruleName: ' 步文街道主入口优先规则 ',
      applicableEntrance: ' 步文街道天亭路主入口 ',
      passTimeSlot: '00:00-24:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: '30 分钟内禁止重复进场 ',
      maxStayTime: '24 小时 ',
      specialVehicleRule: ' 公交车、出租车优先通行 ',
      timeDifferentiatedRule: ' 早晚高峰开放 3 条车道，平峰开放 2 条 ',
      priority: '1',
      effectiveStatus: ' 启用 ',
      conflictPrompt: '',
      updateTime: '2026-01-16 09:30:00',
      operator: ' 赵经理 ',
    },
    {
      id: '12',
      ruleName: ' 东铺头街道停车场巡检规则 ',
      applicableEntrance: ' 东铺头街道新华西路入口 ',
      passTimeSlot: '07:00-23:00',
      noPlateRule: ' 登记后放行 ',
      repeatEntryLimit: '15 分钟内禁止重复进场 ',
      maxStayTime: '10 小时 ',
      specialVehicleRule: ' 巡检车辆免费通行 ',
      timeDifferentiatedRule: ' 巡检期间（每日 14:00-16:00）封闭 1 条车道 ',
      priority: '2',
      effectiveStatus: ' 维修中 ',
      conflictPrompt: ' 与「临时管制规则」存在时段重叠 ',
      updateTime: '2026-01-11 14:10:00',
      operator: ' 孙管理员 ',
    },
    {
      id: '13',
      ruleName: ' 西桥街道专用停车场规则 ',
      applicableEntrance: ' 西桥街道江滨路专用入口 ',
      passTimeSlot: '00:00-24:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: ' 无限制 ',
      maxStayTime: ' 无限制 ',
      specialVehicleRule: ' 内部专用车辆无限制 ',
      timeDifferentiatedRule: ' 无 ',
      priority: '1',
      effectiveStatus: ' 维修中 ',
      conflictPrompt: '',
      updateTime: '2026-01-06 10:50:00',
      operator: ' 周师傅 ',
    },
    {
      id: '14',
      ruleName: ' 石码街道停车场翻新期间规则 ',
      applicableEntrance: ' 石码街道紫葳路出口 ',
      passTimeSlot: ' 暂停营业 ',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: ' 无限制 ',
      maxStayTime: ' 无 ',
      specialVehicleRule: ' 施工车辆放行 ',
      timeDifferentiatedRule: ' 无 ',
      priority: '6',
      effectiveStatus: ' 维护中 ',
      conflictPrompt: '',
      updateTime: '2026-01-01 11:30:00',
      operator: ' 马主管 ',
    },
    {
      id: '15',
      ruleName: ' 武安镇人民东路主入口规则 ',
      applicableEntrance: ' 武安镇人民东路主入口 ',
      passTimeSlot: '00:00-24:00',
      noPlateRule: ' 登记后放行 ',
      repeatEntryLimit: '20 分钟内禁止重复进场 ',
      maxStayTime: '36 小时 ',
      specialVehicleRule: ' 新能源车辆免费 1 小时 ',
      timeDifferentiatedRule: ' 夜间（23:00-07:00）开放 1 条车道 ',
      priority: '2',
      effectiveStatus: ' 启用 ',
      conflictPrompt: '',
      updateTime: '2026-01-13 17:20:00',
      operator: ' 朱管理员 ',
    },
    {
      id: '16',
      ruleName: ' 绥安镇金浦大道入口规则 ',
      applicableEntrance: ' 绥安镇金浦大道入口 ',
      passTimeSlot: '08:00-22:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: '25 分钟内禁止重复进场 ',
      maxStayTime: '16 小时 ',
      specialVehicleRule: ' 无 ',
      timeDifferentiatedRule: ' 周末开放 2 条车道，工作日开放 1 条 ',
      priority: '3',
      effectiveStatus: ' 启用 ',
      conflictPrompt: '',
      updateTime: '2026-01-15 13:10:00',
      operator: ' 韩师傅 ',
    },
    {
      id: '17',
      ruleName: ' 云陵镇专用停车场内部规则 ',
      applicableEntrance: ' 云陵镇宝城路专用入口 ',
      passTimeSlot: '08:00-18:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: ' 无限制 ',
      maxStayTime: ' 无限制 ',
      specialVehicleRule: ' 单位内部车辆、公务车辆通行 ',
      timeDifferentiatedRule: ' 无 ',
      priority: '1',
      effectiveStatus: ' 启用 ',
      conflictPrompt: '',
      updateTime: '2026-01-04 09:20:00',
      operator: ' 秦主管 ',
    },
    {
      id: '18',
      ruleName: ' 南诏镇停车场整改期间规则 ',
      applicableEntrance: ' 南诏镇中山路出口 ',
      passTimeSlot: ' 暂停营业 ',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: ' 无限制 ',
      maxStayTime: ' 无 ',
      specialVehicleRule: ' 消防整改车辆放行 ',
      timeDifferentiatedRule: ' 无 ',
      priority: '7',
      effectiveStatus: ' 停用 ',
      conflictPrompt: '',
      updateTime: '2025-12-28 15:40:00',
      operator: ' 许管理员 ',
    },
    {
      id: '19',
      ruleName: ' 小溪镇东风路主入口通行规则 ',
      applicableEntrance: ' 小溪镇东风路主入口 ',
      passTimeSlot: '00:00-24:00',
      noPlateRule: ' 登记后放行 ',
      repeatEntryLimit: '30 分钟内禁止重复进场 ',
      maxStayTime: '24 小时 ',
      specialVehicleRule: ' 救护车、警车、消防车优先 ',
      timeDifferentiatedRule: ' 高峰时段（07:30-09:30/18:30-20:30）开放 3 条车道 ',
      priority: '2',
      effectiveStatus: ' 启用 ',
      conflictPrompt: ' 与「乡镇车辆通行规则」存在优先级冲突 ',
      updateTime: '2026-01-14 16:50:00',
      operator: ' 邓师傅 ',
    },
    {
      id: '24',
      ruleName: ' 蓝田街道梧桥中路入口规则 ',
      applicableEntrance: ' 蓝田街道梧桥中路入口 ',
      passTimeSlot: '00:00-24:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: '15 分钟内禁止重复进场 ',
      maxStayTime: '12 小时 ',
      specialVehicleRule: ' 无 ',
      timeDifferentiatedRule: ' 无 ',
      priority: '3',
      effectiveStatus: ' 启用 ',
      conflictPrompt: '',
      updateTime: '2026-01-16 08:15:00',
      operator: ' 彭管理员 ',
    },
    {
      id: '25',
      ruleName: ' 蓝田街道梧桥中路次入口规则 ',
      applicableEntrance: ' 蓝田街道梧桥中路次入口 ',
      passTimeSlot: '00:00-24:00',
      noPlateRule: ' 禁止入场 ',
      repeatEntryLimit: '15 分钟内禁止重复进场 ',
      maxStayTime: '12 小时 ',
      specialVehicleRule: ' 无 ',
      timeDifferentiatedRule: ' 无 ',
      priority: '3',
      effectiveStatus: ' 启用 ',
      conflictPrompt: '',
      updateTime: '2026-01-16 08:20:00',
      operator: ' 彭管理员 ',
    },
  ];
};
/** 新增 / 修改的表单 / 列表的搜索表单 - 改造为规则管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'id',
      label: ' 规则 ID',
      component: 'Input',
      componentProps: {
        placeholder: ' 请输入规则 ID',
      },
      labelWidth: '100',
      rules: 'required',
    },
    {
      fieldName: 'ruleName',
      label: ' 规则名称 ',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入规则名称 ',
      },
      rules: 'required',
    },
    {
      fieldName: 'applicableEntrance',
      label: ' 适用出入口 ',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入适用出入口（多个用逗号分隔）',
      },
      rules: 'required',
    },
    {
      fieldName: 'passTimeSlot',
      label: ' 通行时段 ',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入通行时段（如：07:00-22:00）',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: ' 禁止入场 ', value: ' 禁止入场 ' },
          { label: ' 登记后放行 ', value: ' 登记后放行 ' },
          { label: ' 限制入场 ', value: ' 限制入场 ' },
        ],
        placeholder: ' 请选择无牌车规则 ',
        showSearch: true,
      },
      fieldName: 'noPlateRule',
      label: ' 无牌车规则 ',
      rules: 'required',
    },
    {
      fieldName: 'repeatEntryLimit',
      label: ' 重复进场限制 ',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入重复进场限制（如：30 分钟内禁止重复进场）',
      },
    },
    {
      fieldName: 'maxStayTime',
      label: ' 最长停留时长 ',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入最长停留时长（如：24 小时）',
      },
    },
    {
      fieldName: 'specialVehicleRule',
      label: ' 特殊车辆规则 ',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入特殊车辆规则 ',
      },
    },
    {
      fieldName: 'timeDifferentiatedRule',
      label: ' 时段差异化规则 ',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入时段差异化规则 ',
      },
    },
    {
      fieldName: 'priority',
      label: ' 优先级 ',
      component: 'InputNumber',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入优先级 ',
        min: 1,
        max: 10,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: ' 启用 ', value: ' 启用 ' },
          { label: ' 禁用 ', value: ' 禁用 ' },
          { label: ' 暂停 ', value: ' 暂停 ' },
          { label: ' 维修中 ', value: ' 维修中 ' },
          { label: ' 维护中 ', value: ' 维护中 ' },
          { label: ' 停用 ', value: ' 停用 ' },
        ],
        placeholder: ' 请选择生效状态 ',
        showSearch: true,
      },
      fieldName: 'effectiveStatus',
      label: ' 生效状态 ',
      rules: 'required',
    },
    {
      fieldName: 'conflictPrompt',
      label: ' 冲突提示 ',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入冲突提示（无则留空）',
      },
    },
    {
      fieldName: 'updateTime',
      label: ' 修改时间 ',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请选择修改时间 ',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      fieldName: 'operator',
      label: ' 操作人 ',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: ' 请输入操作人 ',
      },
    },
  ];
}
/** 表格字段 - 改造为规则管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: ' 规则 ID',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'ruleName',
      title: ' 规则名称 ',
      minWidth: 200,
      sortable: true,
      slots: { default: 'ruleName' },
    },
    {
      field: 'applicableEntrance',
      title: ' 适用出入口 ',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'passTimeSlot',
      title: ' 通行时段 ',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'noPlateRule',
      title: ' 无牌车规则 ',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'repeatEntryLimit',
      title: ' 重复进场限制 ',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'maxStayTime',
      title: ' 最长停留时长 ',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'specialVehicleRule',
      title: ' 特殊车辆规则 ',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'timeDifferentiatedRule',
      title: ' 时段差异化规则 ',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'priority',
      title: ' 优先级 ',
      minWidth: 80,
      sortable: true,
    },
    {
      field: 'effectiveStatus',
      title: ' 生效状态 ',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'conflictPrompt',
      title: ' 冲突提示 ',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'updateTime',
      title: ' 修改时间 ',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'operator',
      title: ' 操作人 ',
      minWidth: 100,
      sortable: true,
    },
    {
      title: ' 操作 ',
      width: 150,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
/** 文字描述对象 - 改造为规则管理文案 */
export const textObj = {
  editText: ' 编辑规则 ',
  addText: ' 新增规则 ',
  excelName: ' 规则列表 ',
  excelAllName: ' 全市出入口规则数据.xlsx',
  total: ' 规则数量 20; 生效规则 12; 冲突规则 3',
};
