/** 设备监控表格初始数据 - 按指定字段生成 */
export const dataList = () => {
  return [
    {
      deviceCode: 'DEV-001',
      deviceTypeName: '道闸终端',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '芗城区XX社区公共停车场资产',
      dataTypeName: '运行状态',
      monitorId: 'MON001',
      monitorData: '正常',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 12:00:00',
    },
    {
      deviceCode: 'DEV-002',
      deviceTypeName: '车牌识别终端',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '龙文区碧湖公园停车场资产',
      dataTypeName: '识别率',
      monitorId: 'MON002',
      monitorData: '98%',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 12:05:00',
    },
    {
      deviceCode: 'DEV-003',
      deviceTypeName: '地磁检测器',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '龙海区石码镇便民停车场资产',
      dataTypeName: '电池电压',
      monitorId: 'MON003',
      monitorData: '2.8V',
      isAbnormal: '是',
      abnormalDesc: '电池电压偏低',
      monitorTime: '2025-01-01 12:10:00',
    },
    {
      deviceCode: 'DEV-004',
      deviceTypeName: '收费终端',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '芗城区江滨路生态停车场资产',
      dataTypeName: '交易记录',
      monitorId: 'MON004',
      monitorData: '125笔',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 12:15:00',
    },
    {
      deviceCode: 'DEV-005',
      deviceTypeName: '诱导屏',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '龙文区万达商圈停车场资产',
      dataTypeName: '显示状态',
      monitorId: 'MON005',
      monitorData: '正常',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 12:20:00',
    },
    {
      deviceCode: 'DEV-006',
      deviceTypeName: '道闸终端',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '长泰区武安镇公共停车场资产',
      dataTypeName: '开关次数',
      monitorId: 'MON006',
      monitorData: '128次',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 12:25:00',
    },
    {
      deviceCode: 'DEV-007',
      deviceTypeName: '地磁检测器',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '漳浦县绥安镇便民停车场资产',
      dataTypeName: '信号强度',
      monitorId: 'MON007',
      monitorData: '-75dBm',
      isAbnormal: '是',
      abnormalDesc: '信号强度弱',
      monitorTime: '2025-01-01 12:30:00',
    },
    {
      deviceCode: 'DEV-008',
      deviceTypeName: '车牌识别终端',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '芗城区巷口街道停车场资产',
      dataTypeName: '识别时间',
      monitorId: 'MON008',
      monitorData: '0.3s',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 12:35:00',
    },
    {
      deviceCode: 'DEV-009',
      deviceTypeName: '收费终端',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '龙文区蓝田街道停车场资产',
      dataTypeName: '网络状态',
      monitorId: 'MON009',
      monitorData: '在线',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 12:40:00',
    },
    {
      deviceCode: 'DEV-010',
      deviceTypeName: '诱导屏',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '龙文区步文街道停车场资产',
      dataTypeName: '亮度',
      monitorId: 'MON010',
      monitorData: '80%',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 12:45:00',
    },
    {
      deviceCode: 'DEV-011',
      deviceTypeName: '道闸终端',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '芗城区东铺头街道停车场资产',
      dataTypeName: '运行噪音',
      monitorId: 'MON011',
      monitorData: '55dB',
      isAbnormal: '是',
      abnormalDesc: '噪音偏大',
      monitorTime: '2025-01-01 12:50:00',
    },
    {
      deviceCode: 'DEV-012',
      deviceTypeName: '地磁检测器',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '全市通用资产',
      dataTypeName: '温度',
      monitorId: 'MON012',
      monitorData: '45℃',
      isAbnormal: '是',
      abnormalDesc: '温度偏高',
      monitorTime: '2025-01-01 12:55:00',
    },
    {
      deviceCode: 'DEV-013',
      deviceTypeName: '车牌识别终端',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '龙文区万达商圈停车场资产',
      dataTypeName: '镜头清洁度',
      monitorId: 'MON013',
      monitorData: '清洁',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 13:00:00',
    },
    {
      deviceCode: 'DEV-014',
      deviceTypeName: '收费终端',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '芗城区江滨路生态停车场资产',
      dataTypeName: '打印机状态',
      monitorId: 'MON014',
      monitorData: '正常',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 13:05:00',
    },
    {
      deviceCode: 'DEV-015',
      deviceTypeName: '诱导屏',
      monitorTimeRange: '2025-01-01 00:00:00 - 2025-01-01 23:59:59',
      assetName: '龙海区闽齐社区停车场资产',
      dataTypeName: '能耗',
      monitorId: 'MON015',
      monitorData: '12W',
      isAbnormal: '否',
      abnormalDesc: '',
      monitorTime: '2025-01-01 13:10:00',
    },
  ];
};

/** 设备监控表单配置（包含所有指定字段） */
export function useFormSchema() {
  return [
    {
      fieldName: 'monitorId',
      label: '监控ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监控ID',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceCode',
      label: '设备编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入设备编码',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceTypeName',
      label: '设备类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择设备类型',
        options: [
          { label: '道闸终端', value: '道闸终端' },
          { label: '车牌识别终端', value: '车牌识别终端' },
          { label: '地磁检测器', value: '地磁检测器' },
          { label: '收费终端', value: '收费终端' },
          { label: '诱导屏', value: '诱导屏' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'monitorTimeRange',
      label: '监控时间范围',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监控时间范围',
      },
      rules: 'required',
    },
    {
      fieldName: 'assetName',
      label: '所属资产',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属资产',
      },
      rules: 'required',
    },
    {
      fieldName: 'dataTypeName',
      label: '数据类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择数据类型',
        options: [
          { label: '运行状态', value: '运行状态' },
          { label: '识别率', value: '识别率' },
          { label: '电池电压', value: '电池电压' },
          { label: '交易记录', value: '交易记录' },
          { label: '显示状态', value: '显示状态' },
          { label: '开关次数', value: '开关次数' },
          { label: '信号强度', value: '信号强度' },
          { label: '识别时间', value: '识别时间' },
          { label: '网络状态', value: '网络状态' },
          { label: '亮度', value: '亮度' },
          { label: '运行噪音', value: '运行噪音' },
          { label: '温度', value: '温度' },
          { label: '镜头清洁度', value: '镜头清洁度' },
          { label: '打印机状态', value: '打印机状态' },
          { label: '能耗', value: '能耗' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'monitorData',
      label: '监控数据',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监控数据',
      },
      rules: 'required',
    },
    {
      fieldName: 'isAbnormal',
      label: '是否异常',
      component: 'Select',
      componentProps: {
        placeholder: '请选择是否异常',
        options: [
          { label: '是', value: '是' },
          { label: '否', value: '否' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'abnormalDesc',
      label: '异常描述',
      component: 'Input',
      componentProps: {
        placeholder: '请输入异常描述',
        type: 'textarea',
      },
    },
    {
      fieldName: 'monitorTime',
      label: '监控时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择监控时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
  ];
}

/** 设备监控表格列配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'monitorId',
      title: '监控ID',
      minWidth: 100,
      sortable: true,
      slots: { default: 'monitorId' },
    },
    {
      field: 'deviceCode',
      title: '设备编码',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'deviceTypeName',
      title: '设备类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monitorTimeRange',
      title: '监控时间范围',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'assetName',
      title: '所属资产',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'dataTypeName',
      title: '数据类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'monitorData',
      title: '监控数据',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'isAbnormal',
      title: '是否异常',
      minWidth: 100,
      sortable: true,
      slots: { default: 'isAbnormal' },
    },
    {
      field: 'abnormalDesc',
      title: '异常描述',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'monitorTime',
      title: '监控时间',
      minWidth: 180,
      sortable: true,
    },
    {
      title: '操作',
      width: 100,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

export const textObj = {
  editText: '编辑设备监控',
  addText: '新增设备监控',
  excelName: '设备监控列表',
  excelAllName: '设备监控数据.xlsx',
  total: ' 总计: 监控记录15; 正常10; 异常5',
};

/** 详情抽屉字段配置 */
export const detailFields = [
  { key: 'monitorId', label: '监控ID' },
  { key: 'deviceCode', label: '设备编码' },
  { key: 'deviceTypeName', label: '设备类型' },
  { key: 'monitorTimeRange', label: '监控时间范围' },
  { key: 'assetName', label: '所属资产' },
  { key: 'dataTypeName', label: '数据类型' },
  { key: 'monitorData', label: '监控数据' },
  { key: 'isAbnormal', label: '是否异常' },
  { key: 'abnormalDesc', label: '异常描述' },
  { key: 'monitorTime', label: '监控时间' },
];
