/** 表格初始数据 - 停车稽查违规记录 */
export const dataList = () => {
  return [
    {
      id: '2', // 稽查ID
      plateNumber: '闽EJ5689', // 车牌号码
      violationType: '超时停车', // 违规类型
      violationTime: '2026-01-20 08:15:30', // 违规时间
      violationPosition: '龙文区碧湖公园停车场86号车位', // 违规位置
      relatedEntryId: 'RK20260120001', // 关联入场ID
      relatedExitId: 'CK20260120001', // 关联离场ID
      captureImage: 'https://example.com/capture/ej5689.jpg', // 抓拍图片
      inspector: '张三', // 稽查人员
      evidenceCount: '3', // 证据数量
      disposalStatus: '已处置', // 处置状态
      verificationResult: '核实违规', // 核实结果
    },
    {
      id: '3',
      plateNumber: '闽EK3210',
      violationType: '占用消防通道',
      violationTime: '2026-01-20 09:20:15',
      violationPosition: '龙海区石码镇便民停车场出口通道',
      relatedEntryId: 'RK20260120002',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/ek3210.jpg',
      inspector: '李四',
      evidenceCount: '2',
      disposalStatus: '待处置',
      verificationResult: '待核实',
    },
    {
      id: '4',
      plateNumber: '闽EL8976',
      violationType: '无牌停车',
      violationTime: '2026-01-20 10:05:40',
      violationPosition: '龙海区闽齐社区停车场18号车位',
      relatedEntryId: 'RK20260120003',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/el8976.jpg',
      inspector: '王五',
      evidenceCount: '4',
      disposalStatus: '处置中',
      verificationResult: '核实违规',
    },
    {
      id: '5',
      plateNumber: '闽EM2345',
      violationType: '逆向停车',
      violationTime: '2026-01-20 11:10:25',
      violationPosition: '芗城区江滨路生态停车场98号车位',
      relatedEntryId: 'RK20260120004',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/em2345.jpg',
      inspector: '赵六',
      evidenceCount: '1',
      disposalStatus: '处置中',
      verificationResult: '核实违规',
    },
    {
      id: '6',
      plateNumber: '闽EN7890',
      violationType: '私占专用车位',
      violationTime: '2026-01-20 14:30:10',
      violationPosition: '龙文区万达商圈停车场156号车位',
      relatedEntryId: 'RK20260120005',
      relatedExitId: 'CK20260120005',
      captureImage: 'https://example.com/capture/en7890.jpg',
      inspector: '孙七',
      evidenceCount: '2',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
    {
      id: '7',
      plateNumber: '闽EO1234',
      violationType: '压线停车',
      violationTime: '2026-01-20 15:45:05',
      violationPosition: '长泰区武安镇公共停车场42号车位',
      relatedEntryId: 'RK20260120006',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/eo1234.jpg',
      inspector: '周八',
      evidenceCount: '3',
      disposalStatus: '待处置',
      verificationResult: '核实无违规',
    },
    {
      id: '8',
      plateNumber: '闽EP6789',
      violationType: '超时停车',
      violationTime: '2026-01-20 16:20:30',
      violationPosition: '漳浦县绥安镇便民停车场89号车位',
      relatedEntryId: 'RK20260120007',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/ep6789.jpg',
      inspector: '吴九',
      evidenceCount: '2',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
    {
      id: '9',
      plateNumber: '闽EQ5432',
      violationType: '占用残疾人车位',
      violationTime: '2026-01-20 17:15:15',
      violationPosition: '芗城区巷口街道停车场56号车位',
      relatedEntryId: 'RK20260120008',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/eq5432.jpg',
      inspector: '郑十',
      evidenceCount: '4',
      disposalStatus: '处置中',
      verificationResult: '待核实',
    },
    {
      id: '10',
      plateNumber: '闽ER9876',
      violationType: '无牌停车',
      violationTime: '2026-01-20 18:00:40',
      violationPosition: '龙文区蓝田街道停车场33号车位',
      relatedEntryId: 'RK20260120009',
      relatedExitId: 'CK20260120009',
      captureImage: 'https://example.com/capture/er9876.jpg',
      inspector: '张三',
      evidenceCount: '3',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
    {
      id: '11',
      plateNumber: '闽ES8765',
      violationType: '逆向停车',
      violationTime: '2026-01-20 19:30:25',
      violationPosition: '龙文区步文街道停车场67号车位',
      relatedEntryId: 'RK20260120010',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/es8765.jpg',
      inspector: '李四',
      evidenceCount: '2',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
    {
      id: '12',
      plateNumber: '闽ET1234',
      violationType: '压线停车',
      violationTime: '2026-01-20 20:10:10',
      violationPosition: '芗城区东铺头街道停车场102号车位',
      relatedEntryId: 'RK20260120011',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/et1234.jpg',
      inspector: '王五',
      evidenceCount: '1',
      disposalStatus: '待处置',
      verificationResult: '待核实',
    },
    {
      id: '13',
      plateNumber: '闽EU5678',
      violationType: '私占专用车位',
      violationTime: '2026-01-20 21:05:35',
      violationPosition: '芗城区西桥街道停车场89号车位',
      relatedEntryId: 'RK20260120012',
      relatedExitId: 'CK20260120012',
      captureImage: 'https://example.com/capture/eu5678.jpg',
      inspector: '赵六',
      evidenceCount: '3',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
    {
      id: '14',
      plateNumber: '闽EV9012',
      violationType: '占用消防通道',
      violationTime: '2026-01-21 07:30:20',
      violationPosition: '龙海区石码街道停车场入口通道',
      relatedEntryId: 'RK20260121001',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/ev9012.jpg',
      inspector: '孙七',
      evidenceCount: '2',
      disposalStatus: '处置中',
      verificationResult: '核实违规',
    },
    {
      id: '15',
      plateNumber: '闽EW3456',
      violationType: '超时停车',
      violationTime: '2026-01-21 08:15:05',
      violationPosition: '长泰区武安镇停车场77号车位',
      relatedEntryId: 'RK20260121002',
      relatedExitId: 'CK20260121002',
      captureImage: 'https://example.com/capture/ew3456.jpg',
      inspector: '周八',
      evidenceCount: '4',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
    {
      id: '16',
      plateNumber: '闽EX7890',
      violationType: '无牌停车',
      violationTime: '2026-01-21 09:20:40',
      violationPosition: '漳浦县绥安镇停车场39号车位',
      relatedEntryId: 'RK20260121003',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/ex7890.jpg',
      inspector: '吴九',
      evidenceCount: '2',
      disposalStatus: '待处置',
      verificationResult: '核实无违规',
    },
    {
      id: '17',
      plateNumber: '闽EY1234',
      violationType: '逆向停车',
      violationTime: '2026-01-21 10:05:15',
      violationPosition: '云霄县云陵镇停车场66号车位',
      relatedEntryId: 'RK20260121004',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/ey1234.jpg',
      inspector: '郑十',
      evidenceCount: '3',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
    {
      id: '18',
      plateNumber: '闽EZ5678',
      violationType: '占用残疾人车位',
      violationTime: '2026-01-21 11:10:30',
      violationPosition: '诏安县南诏镇停车场102号车位',
      relatedEntryId: 'RK20260121005',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/ez5678.jpg',
      inspector: '张三',
      evidenceCount: '1',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
    {
      id: '19',
      plateNumber: '闽E01234',
      violationType: '压线停车',
      violationTime: '2026-01-21 14:30:05',
      violationPosition: '平和县小溪镇停车场88号车位',
      relatedEntryId: 'RK20260121006',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/e01234.jpg',
      inspector: '李四',
      evidenceCount: '2',
      disposalStatus: '处置中',
      verificationResult: '待核实',
    },
    {
      id: '24',
      plateNumber: '闽E15678',
      violationType: '私占专用车位',
      violationTime: '2026-01-21 15:45:20',
      violationPosition: '龙文区蓝田街道停车场58号车位',
      relatedEntryId: 'RK20260121007',
      relatedExitId: 'CK20260121007',
      captureImage: 'https://example.com/capture/e15678.jpg',
      inspector: '王五',
      evidenceCount: '3',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
    {
      id: '25',
      plateNumber: '闽E29012',
      violationType: '占用消防通道',
      violationTime: '2026-01-21 16:20:45',
      violationPosition: '龙文区蓝田街道停车场2号入口通道',
      relatedEntryId: 'RK20260121008',
      relatedExitId: '',
      captureImage: 'https://example.com/capture/e29012.jpg',
      inspector: '赵六',
      evidenceCount: '4',
      disposalStatus: '已处置',
      verificationResult: '核实违规',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 - 停车稽查违规 */
export function useFormSchema() {
  return [
    {
      fieldName: 'id',
      label: '稽查ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入稽查ID',
      },
      labelWidth: '100',
      rules: 'required',
    },
    {
      fieldName: 'plateNumber',
      label: '车牌号码',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入车牌号码（如：闽E12345）',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '超时停车', value: '超时停车' },
          { label: '占用消防通道', value: '占用消防通道' },
          { label: '无牌停车', value: '无牌停车' },
          { label: '逆向停车', value: '逆向停车' },
          { label: '压线停车', value: '压线停车' },
          { label: '私占专用车位', value: '私占专用车位' },
          { label: '占用残疾人车位', value: '占用残疾人车位' },
        ],
        placeholder: '请选择违规类型',
        showSearch: true,
      },
      defaultValue: '超时停车',
      fieldName: 'violationType',
      label: '违规类型',
      rules: 'required',
    },
    {
      fieldName: 'violationTime',
      label: '违规时间',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        type: 'datetime-local',
        placeholder: '请选择违规时间',
      },
      rules: 'required',
    },
    {
      fieldName: 'violationPosition',
      label: '违规位置',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入违规位置（如：XX停车场XX号车位）',
      },
      rules: 'required',
    },
    {
      fieldName: 'relatedEntryId',
      label: '关联入场ID',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入关联入场ID',
      },
    },
    {
      fieldName: 'relatedExitId',
      label: '关联离场ID',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入关联离场ID',
      },
    },
    {
      fieldName: 'captureImage',
      label: '抓拍图片',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入抓拍图片URL',
      },
    },
    {
      fieldName: 'inspector',
      label: '稽查人员',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入稽查人员姓名',
      },
      rules: 'required',
    },
    {
      fieldName: 'evidenceCount',
      label: '证据数量',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        type: 'number',
        min: 1,
        placeholder: '请输入证据数量',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '待处置', value: '待处置' },
          { label: '处置中', value: '处置中' },
          { label: '已处置', value: '已处置' },
        ],
        placeholder: '请选择处置状态',
        showSearch: true,
      },
      defaultValue: '待处置',
      fieldName: 'disposalStatus',
      label: '处置状态',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '待核实', value: '待核实' },
          { label: '核实违规', value: '核实违规' },
          { label: '核实无违规', value: '核实无违规' },
        ],
        placeholder: '请选择核实结果',
        showSearch: true,
      },
      defaultValue: '待核实',
      fieldName: 'verificationResult',
      label: '核实结果',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 停车稽查违规 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: '稽查ID',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'plateNumber',
      title: '车牌号码',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'violationType',
      title: '违规类型',
      minWidth: 120,
      sortable: true, 
    },
    {
      field: 'violationTime',
      title: '违规时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'violationPosition',
      title: '违规位置',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'relatedEntryId',
      title: '关联入场ID',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'relatedExitId',
      title: '关联离场ID',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'captureImage',
      title: '抓拍图片',
      minWidth: 120,
      sortable: true, 
    },
    {
      field: 'inspector',
      title: '稽查人员',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'evidenceCount',
      title: '证据数量',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'disposalStatus',
      title: '处置状态',
      minWidth: 100,
      sortable: true, 
    },
    {
      field: 'verificationResult',
      title: '核实结果',
      minWidth: 120,
      sortable: true, 
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 - 停车稽查违规 */
export const textObj = {
  editText: '编辑稽查记录',
  addText: '新增稽查记录',
  excelName: '停车稽查违规列表',
  excelAllName: '全市停车稽查违规数据.xlsx',
  total: '稽查记录数量20;待处置4;核实违规17',
};