/** 表格初始数据 - 占道经营周度统计分析数据 */
export const dataList = () => [
  {
    occupationPointTotalCount: 156,
    weekMobileVendorDisposalCount: 42,
    weekKeyRoadControlComplianceRate: 89.5,
    weekGuidancePointSettlementRate: 76.8,
    weekRepeatedOccupationPointCount: 15,
    weekMobileVendorDisposalCountMomChangeRate: 12.3,
    weekMobileVendorDisposalCountYoYChangeRate: 8.7,
    weekKeyRoadControlComplianceRateMomChangeRate: 5.2,
    weekKeyRoadControlComplianceRateYoYChangeRate: 15.6,
    weekGuidancePointSettlementRateMomChangeRate: -3.1,
    weekGuidancePointSettlementRateYoYChangeRate: 12.4,
    weekRepeatedOccupationPointCountMomChangeRate: 25.8,
    weekRepeatedOccupationPointCountYoYChangeRate: 32.1,
    areaBreakdown: '鼓楼区: 45个；台江区: 38个；仓山区: 32个；晋安区: 41个',
    roadSectionBreakdown: '八一七北路: 18个；五四路: 15个；五一路: 22个；六一路: 16个',
    occupationTypeBreakdown: '餐饮摊贩: 68个；水果摊贩: 42个；杂货摊贩: 32个；其他: 14个',
    guidancePointBreakdown: '鼓楼疏导点: 28个；台江疏导点: 22个；仓山疏导点: 18个；晋安疏导点: 20个',
    weekStatisticsPeriod: '2024-06-17 ~ 2024-06-23',
  },
  {
    occupationPointTotalCount: 142,
    weekMobileVendorDisposalCount: 38,
    weekKeyRoadControlComplianceRate: 92.1,
    weekGuidancePointSettlementRate: 82.3,
    weekRepeatedOccupationPointCount: 12,
    weekMobileVendorDisposalCountMomChangeRate: -8.7,
    weekMobileVendorDisposalCountYoYChangeRate: -5.2,
    weekKeyRoadControlComplianceRateMomChangeRate: 12.8,
    weekKeyRoadControlComplianceRateYoYChangeRate: 18.9,
    weekGuidancePointSettlementRateMomChangeRate: 8.9,
    weekGuidancePointSettlementRateYoYChangeRate: 15.2,
    weekRepeatedOccupationPointCountMomChangeRate: -18.5,
    weekRepeatedOccupationPointCountYoYChangeRate: -28.7,
    areaBreakdown: '鼓楼区: 41个；台江区: 35个；仓山区: 29个；晋安区: 37个',
    roadSectionBreakdown: '八一七北路: 16个；五四路: 13个；五一路: 19个；六一路: 14个',
    occupationTypeBreakdown: '餐饮摊贩: 62个；水果摊贩: 38个；杂货摊贩: 28个；其他: 12个',
    guidancePointBreakdown: '鼓楼疏导点: 25个；台江疏导点: 20个；仓山疏导点: 16个；晋安疏导点: 19个',
    weekStatisticsPeriod: '2024-06-10 ~ 2024-06-16',
  },
  {
    occupationPointTotalCount: 168,
    weekMobileVendorDisposalCount: 35,
    weekKeyRoadControlComplianceRate: 85.2,
    weekGuidancePointSettlementRate: 71.5,
    weekRepeatedOccupationPointCount: 18,
    weekMobileVendorDisposalCountMomChangeRate: 15.6,
    weekMobileVendorDisposalCountYoYChangeRate: 22.1,
    weekKeyRoadControlComplianceRateMomChangeRate: -3.8,
    weekKeyRoadControlComplianceRateYoYChangeRate: -8.3,
    weekGuidancePointSettlementRateMomChangeRate: 12.4,
    weekGuidancePointSettlementRateYoYChangeRate: 8.7,
    weekRepeatedOccupationPointCountMomChangeRate: 28.9,
    weekRepeatedOccupationPointCountYoYChangeRate: 35.2,
    areaBreakdown: '鼓楼区: 48个；台江区: 42个；仓山区: 36个；晋安区: 42个',
    roadSectionBreakdown: '八一七北路: 20个；五四路: 18个；五一路: 24个；六一路: 18个',
    occupationTypeBreakdown: '餐饮摊贩: 75个；水果摊贩: 48个；杂货摊贩: 35个；其他: 10个',
    guidancePointBreakdown: '鼓楼疏导点: 32个；台江疏导点: 25个；仓山疏导点: 20个；晋安疏导点: 23个',
    weekStatisticsPeriod: '2024-06-03 ~ 2024-06-09',
  },
  {
    occupationPointTotalCount: 135,
    weekMobileVendorDisposalCount: 45,
    weekKeyRoadControlComplianceRate: 94.8,
    weekGuidancePointSettlementRate: 85.9,
    weekRepeatedOccupationPointCount: 10,
    weekMobileVendorDisposalCountMomChangeRate: -12.4,
    weekMobileVendorDisposalCountYoYChangeRate: -15.8,
    weekKeyRoadControlComplianceRateMomChangeRate: 18.7,
    weekKeyRoadControlComplianceRateYoYChangeRate: 22.3,
    weekGuidancePointSettlementRateMomChangeRate: 15.6,
    weekGuidancePointSettlementRateYoYChangeRate: 18.9,
    weekRepeatedOccupationPointCountMomChangeRate: -25.6,
    weekRepeatedOccupationPointCountYoYChangeRate: -32.4,
    areaBreakdown: '鼓楼区: 38个；台江区: 32个；仓山区: 28个；晋安区: 37个',
    roadSectionBreakdown: '八一七北路: 14个；五四路: 12个；五一路: 16个；六一路: 12个',
    occupationTypeBreakdown: '餐饮摊贩: 58个；水果摊贩: 35个；杂货摊贩: 28个；其他: 14个',
    guidancePointBreakdown: '鼓楼疏导点: 22个；台江疏导点: 18个；仓山疏导点: 15个；晋安疏导点: 17个',
    weekStatisticsPeriod: '2024-05-27 ~ 2024-06-02',
  },
  {
    occupationPointTotalCount: 172,
    weekMobileVendorDisposalCount: 52,
    weekKeyRoadControlComplianceRate: 88.3,
    weekGuidancePointSettlementRate: 78.2,
    weekRepeatedOccupationPointCount: 22,
    weekMobileVendorDisposalCountMomChangeRate: 20.3,
    weekMobileVendorDisposalCountYoYChangeRate: 28.9,
    weekKeyRoadControlComplianceRateMomChangeRate: -12.1,
    weekKeyRoadControlComplianceRateYoYChangeRate: -15.4,
    weekGuidancePointSettlementRateMomChangeRate: -8.7,
    weekGuidancePointSettlementRateYoYChangeRate: -12.8,
    weekRepeatedOccupationPointCountMomChangeRate: 35.2,
    weekRepeatedOccupationPointCountYoYChangeRate: 42.1,
    areaBreakdown: '鼓楼区: 52个；台江区: 45个；仓山区: 40个；晋安区: 35个',
    roadSectionBreakdown: '八一七北路: 22个；五四路: 20个；五一路: 26个；六一路: 20个',
    occupationTypeBreakdown: '餐饮摊贩: 82个；水果摊贩: 52个；杂货摊贩: 32个；其他: 6个',
    guidancePointBreakdown: '鼓楼疏导点: 35个；台江疏导点: 28个；仓山疏导点: 22个；晋安疏导点: 25个',
    weekStatisticsPeriod: '2024-05-20 ~ 2024-05-26',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 占道经营周度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'occupationPointTotalCount',
      label: '占道经营点位总数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入占道经营点位总数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekMobileVendorDisposalCount',
      label: '周流动摊贩处置数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周流动摊贩处置数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekKeyRoadControlComplianceRate',
      label: '周重点路段管控达标率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周重点路段管控达标率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekGuidancePointSettlementRate',
      label: '周疏导点入驻率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周疏导点入驻率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekRepeatedOccupationPointCount',
      label: '周重复占道点位数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周重复占道点位数量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekMobileVendorDisposalCountMomChangeRate',
      label: '流动摊贩处置数环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入流动摊贩处置数环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekMobileVendorDisposalCountYoYChangeRate',
      label: '流动摊贩处置数同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入流动摊贩处置数同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekKeyRoadControlComplianceRateMomChangeRate',
      label: '重点路段管控达标率环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入重点路段管控达标率环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekKeyRoadControlComplianceRateYoYChangeRate',
      label: '重点路段管控达标率同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入重点路段管控达标率同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekGuidancePointSettlementRateMomChangeRate',
      label: '疏导点入驻率环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入疏导点入驻率环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekGuidancePointSettlementRateYoYChangeRate',
      label: '疏导点入驻率同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入疏导点入驻率同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekRepeatedOccupationPointCountMomChangeRate',
      label: '重复占道点位数量环比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入重复占道点位数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'weekRepeatedOccupationPointCountYoYChangeRate',
      label: '重复占道点位数量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入重复占道点位数量同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'areaBreakdown',
      label: '区域分布明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入区域分布明细（如：鼓楼区:45个；台江区:38个）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'roadSectionBreakdown',
      label: '路段分布明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入路段分布明细（如：八一七北路:18个；五四路:15个）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'occupationTypeBreakdown',
      label: '占道类型分布明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入占道类型分布明细（如：餐饮摊贩:68个；水果摊贩:42个）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'guidancePointBreakdown',
      label: '疏导点分布明细',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入疏导点分布明细（如：鼓楼疏导点:28个；台江疏导点:22个）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'weekStatisticsPeriod',
      label: '周统计时段',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入周统计时段（如：2024-06-17 ~ 2024-06-23）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 占道经营周度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'occupationPointTotalCount',
      title: '占道经营点位总数',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'weekMobileVendorDisposalCount',
      title: '周流动摊贩处置数',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'weekKeyRoadControlComplianceRate',
      title: '周重点路段管控达标率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'weekGuidancePointSettlementRate',
      title: '周疏导点入驻率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'weekRepeatedOccupationPointCount',
      title: '周重复占道点位数量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'weekMobileVendorDisposalCountMomChangeRate',
      title: '流动摊贩处置数环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'weekMobileVendorDisposalCountYoYChangeRate',
      title: '流动摊贩处置数同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'weekKeyRoadControlComplianceRateMomChangeRate',
      title: '重点路段管控达标率环比变化率(%)',
      minWidth: 190,
      sortable: true,
    },
    {
      field: 'weekKeyRoadControlComplianceRateYoYChangeRate',
      title: '重点路段管控达标率同比变化率(%)',
      minWidth: 190,
      sortable: true,
    },
    {
      field: 'weekGuidancePointSettlementRateMomChangeRate',
      title: '疏导点入驻率环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'weekGuidancePointSettlementRateYoYChangeRate',
      title: '疏导点入驻率同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'weekRepeatedOccupationPointCountMomChangeRate',
      title: '重复占道点位数量环比变化率(%)',
      minWidth: 190,
      sortable: true,
    },
    {
      field: 'weekRepeatedOccupationPointCountYoYChangeRate',
      title: '重复占道点位数量同比变化率(%)',
      minWidth: 190,
      sortable: true,
    },
    {
      field: 'areaBreakdown',
      title: '区域分布明细',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'roadSectionBreakdown',
      title: '路段分布明细',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'occupationTypeBreakdown',
      title: '占道类型分布明细',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'guidancePointBreakdown',
      title: '疏导点分布明细',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'weekStatisticsPeriod',
      title: '周统计时段',
      minWidth: 160,
      sortable: false,
    },
  ];
}
