/** 表格初始数据 - 改造为燃气管网监测管理数据 */
export const dataList = () => [
  {
    pipeNetworkSection: '福州市台江区八一七中路管网段',
    affiliatedArea: '台江区',
    pipeNetworkPressure: 0.35,
    gasConcentration: 0.8,
    monitorDeviceCode: 'FJ-FZ-G-202406-001',
    deviceOnlineStatus: '在线',
    maintenancePerson: '陈铭（工号：FJYW001）',
    dataCollectionFreq: '5分钟',
    dataSyncDuration: 3,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:30:25',
    gradedWarningRuleMatchResult: 'Ⅱ级',
  },
  {
    pipeNetworkSection: '厦门市思明区湖滨南路管网段',
    affiliatedArea: '思明区',
    pipeNetworkPressure: 0.32,
    gasConcentration: 0.5,
    monitorDeviceCode: 'FJ-XM-G-202406-002',
    deviceOnlineStatus: '在线',
    maintenancePerson: '林晓婷（工号：FJYW002）',
    dataCollectionFreq: '10分钟',
    dataSyncDuration: 5,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:28:42',
    gradedWarningRuleMatchResult: 'Ⅰ级',
  },
  {
    pipeNetworkSection: '泉州市丰泽区刺桐路管网段',
    affiliatedArea: '丰泽区',
    pipeNetworkPressure: 0.45,
    gasConcentration: 1.2,
    monitorDeviceCode: 'FJ-QZ-G-202406-003',
    deviceOnlineStatus: '异常',
    maintenancePerson: '王志远（工号：FJYW003）',
    dataCollectionFreq: '1分钟',
    dataSyncDuration: 2,
    monitorStatus: '数据异常',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:10:18',
    gradedWarningRuleMatchResult: 'Ⅲ级',
  },
  {
    pipeNetworkSection: '漳州市芗城区胜利路管网段',
    affiliatedArea: '芗城区',
    pipeNetworkPressure: 0.28,
    gasConcentration: 0.3,
    monitorDeviceCode: 'FJ-ZZ-G-202406-004',
    deviceOnlineStatus: '在线',
    maintenancePerson: '黄丽萍（工号：FJYW004）',
    dataCollectionFreq: '30分钟',
    dataSyncDuration: 4,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:25:36',
    gradedWarningRuleMatchResult: 'Ⅰ级',
  },
  {
    pipeNetworkSection: '莆田市城厢区文献路管网段',
    affiliatedArea: '城厢区',
    pipeNetworkPressure: 0.38,
    gasConcentration: 0.9,
    monitorDeviceCode: 'FJ-PT-G-202406-005',
    deviceOnlineStatus: '离线',
    maintenancePerson: '郑建明（工号：FJYW005）',
    dataCollectionFreq: '1小时',
    dataSyncDuration: 6,
    monitorStatus: '设备故障',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 14:50:08',
    gradedWarningRuleMatchResult: 'Ⅱ级',
  },
  {
    pipeNetworkSection: '宁德市蕉城区蕉城南路管网段',
    affiliatedArea: '蕉城区',
    pipeNetworkPressure: 0.33,
    gasConcentration: 0.7,
    monitorDeviceCode: 'FJ-ND-G-202406-006',
    deviceOnlineStatus: '在线',
    maintenancePerson: '吴永辉（工号：FJYW006）',
    dataCollectionFreq: '5分钟',
    dataSyncDuration: 3,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:32:15',
    gradedWarningRuleMatchResult: 'Ⅰ级',
  },
  {
    pipeNetworkSection: '龙岩市新罗区中山路管网段',
    affiliatedArea: '新罗区',
    pipeNetworkPressure: 0.40,
    gasConcentration: 0.95,
    monitorDeviceCode: 'FJ-LY-G-202406-007',
    deviceOnlineStatus: '在线',
    maintenancePerson: '张志强（工号：FJYW007）',
    dataCollectionFreq: '10分钟',
    dataSyncDuration: 4,
    monitorStatus: '人工巡检中',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:18:49',
    gradedWarningRuleMatchResult: 'Ⅱ级',
  },
  {
    pipeNetworkSection: '三明市梅列区列东街管网段',
    affiliatedArea: '梅列区',
    pipeNetworkPressure: 0.30,
    gasConcentration: 0.6,
    monitorDeviceCode: 'FJ-SM-G-202406-008',
    deviceOnlineStatus: '在线',
    maintenancePerson: '李芳（工号：FJYW008）',
    dataCollectionFreq: '30分钟',
    dataSyncDuration: 5,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:22:05',
    gradedWarningRuleMatchResult: 'Ⅰ级',
  },
  {
    pipeNetworkSection: '南平市延平区解放路管网段',
    affiliatedArea: '延平区',
    pipeNetworkPressure: 0.37,
    gasConcentration: 0.85,
    monitorDeviceCode: 'FJ-NP-G-202406-009',
    deviceOnlineStatus: '异常',
    maintenancePerson: '刘建国（工号：FJYW009）',
    dataCollectionFreq: '1分钟',
    dataSyncDuration: 2,
    monitorStatus: '暂停监测',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:05:33',
    gradedWarningRuleMatchResult: 'Ⅱ级',
  },
  {
    pipeNetworkSection: '平潭综合实验区金井湾管网段',
    affiliatedArea: '平潭综合实验区',
    pipeNetworkPressure: 0.29,
    gasConcentration: 0.45,
    monitorDeviceCode: 'FJ-PTTH-G-202406-010',
    deviceOnlineStatus: '在线',
    maintenancePerson: '蔡伟明（工号：FJYW010）',
    dataCollectionFreq: '1小时',
    dataSyncDuration: 6,
    monitorStatus: '正常监测',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    latestDataUpdateTime: '2024-06-28 15:15:20',
    gradedWarningRuleMatchResult: 'Ⅰ级',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为燃气管网监测管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'pipeNetworkSection',
      label: '管网路段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管网路段名称',
      },
      labelWidth: '120',
      rules: 'required', // 管网路段为必填项
    },
    {
      fieldName: 'affiliatedArea',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域（如：台江区、思明区）',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'pipeNetworkPressure',
      label: '管网压力',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入管网压力（单位：MPa）',
        min: 0,
        precision: 2, // 保留2位小数，贴合压力计量场景
        addonAfter: 'MPa',
      },
      rules: 'required',
    },
    {
      fieldName: 'gasConcentration',
      label: '燃气浓度',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入燃气浓度（单位：%）',
        min: 0,
        precision: 2,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'monitorDeviceCode',
      label: '监测设备编号',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入监测设备编号',
        maxLength: 50,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceOnlineStatus',
      label: '设备在线状态',
      rules: 'required',
    },
    {
      fieldName: 'maintenancePerson',
      label: '负责运维员',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入负责运维员姓名/工号',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '1分钟', value: '1分钟' },
          { label: '5分钟', value: '5分钟' },
          { label: '10分钟', value: '10分钟' },
          { label: '30分钟', value: '30分钟' },
          { label: '1小时', value: '1小时' },
          { label: '24小时', value: '24小时' },
        ],
        placeholder: '请选择数据采集频率',
        showSearch: true,
      },
      fieldName: 'dataCollectionFreq',
      label: '数据采集频率',
      rules: 'required',
    },
    {
      fieldName: 'dataSyncDuration',
      label: '数据同步时长',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入数据同步时长（单位：秒）',
        min: 1,
        precision: 0,
        addonAfter: '秒',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '正常监测', value: '正常监测' },
          { label: '暂停监测', value: '暂停监测' },
          { label: '数据异常', value: '数据异常' },
          { label: '设备故障', value: '设备故障' },
          { label: '人工巡检中', value: '人工巡检中' },
        ],
        placeholder: '请选择监测状态',
        showSearch: true,
      },
      fieldName: 'monitorStatus',
      label: '监测状态',
      rules: 'required',
    },
    {
      fieldName: 'indexThresholdRange',
      label: '指标阈值范围',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder:
          '请输入指标阈值范围（如：管网压力0.2~0.4MPa；燃气浓度≤1%）',
        maxlength: 200,
      },
      rules: 'required',
    },
    {
      fieldName: 'latestDataUpdateTime',
      label: '最近数据更新时间',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入最近数据更新时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: 'Ⅰ级', value: 'Ⅰ级' },
          { label: 'Ⅱ级', value: 'Ⅱ级' },
          { label: 'Ⅲ级', value: 'Ⅲ级' },
        ],
        placeholder: '请选择分级预警规则匹配结果',
        showSearch: true,
      },
      fieldName: 'gradedWarningRuleMatchResult',
      label: '分级预警规则匹配结果',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为燃气管网监测管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'pipeNetworkSection',
      title: '管网路段',
      minWidth: 180,
      sortable: true,
      slots: { default: 'pipeNetworkSection' },
    },
    {
      field: 'affiliatedArea',
      title: '所属区域',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'pipeNetworkPressure',
      title: '管网压力(MPa)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'gasConcentration',
      title: '燃气浓度(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monitorDeviceCode',
      title: '监测设备编号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'deviceOnlineStatus',
      title: '设备在线状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'maintenancePerson',
      title: '负责运维员',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'dataCollectionFreq',
      title: '数据采集频率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'dataSyncDuration',
      title: '数据同步时长(秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monitorStatus',
      title: '监测状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'indexThresholdRange',
      title: '指标阈值范围',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'latestDataUpdateTime',
      title: '最近数据更新时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'gradedWarningRuleMatchResult',
      title: '分级预警规则匹配结果',
      minWidth: 160,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}