/** 表格初始数据 - 改造为燃气管网监测管理数据 */
export const dataList = () => [
  {
    id: '1',
    pipeRoad: '福州市台江区八一七中路管网段',
    areaName: '台江区',
    pipePressure: 0.35,
    gasConcentration: 0.8,
    deviceCode: 'FJ-FZ-G-202406-001',
    deviceStatus: '在线',
    staffName: '陈铭（工号：FJYW001）',
    collectFrequency: '5分钟',
    syncDuration: 3,
    monitorStatus: '运行中',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 15:30:25',
    warnLevelRule: 'Ⅱ级',
  },
  {
    id: '2',
    pipeRoad: '厦门市思明区湖滨南路管网段',
    areaName: '思明区',
    pipePressure: 0.32,
    gasConcentration: 0.5,
    deviceCode: 'FJ-XM-G-202406-002',
    deviceStatus: '在线',
    staffName: '林晓婷（工号：FJYW002）',
    collectFrequency: '10分钟',
    syncDuration: 5,
    monitorStatus: '运行中',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 15:28:42',
    warnLevelRule: 'Ⅰ级',
  },
  {
    id: '3',
    pipeRoad: '泉州市丰泽区刺桐路管网段',
    areaName: '丰泽区',
    pipePressure: 0.45,
    gasConcentration: 1.2,
    deviceCode: 'FJ-QZ-G-202406-003',
    deviceStatus: '异常',
    staffName: '王志远（工号：FJYW003）',
    collectFrequency: '1分钟',
    syncDuration: 2,
    monitorStatus: '异常',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 15:10:18',
    warnLevelRule: 'Ⅲ级',
  },
  {
    id: '4',
    pipeRoad: '漳州市芗城区胜利路管网段',
    areaName: '芗城区',
    pipePressure: 0.28,
    gasConcentration: 0.3,
    deviceCode: 'FJ-ZZ-G-202406-004',
    deviceStatus: '在线',
    staffName: '黄丽萍（工号：FJYW004）',
    collectFrequency: '30分钟',
    syncDuration: 4,
    monitorStatus: '运行中',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 15:25:36',
    warnLevelRule: 'Ⅰ级',
  },
  {
    id: '5',
    pipeRoad: '莆田市城厢区文献路管网段',
    areaName: '城厢区',
    pipePressure: 0.38,
    gasConcentration: 0.9,
    deviceCode: 'FJ-PT-G-202406-005',
    deviceStatus: '离线',
    staffName: '郑建明（工号：FJYW005）',
    collectFrequency: '1小时',
    syncDuration: 6,
    monitorStatus: '已停止',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 14:50:08',
    warnLevelRule: 'Ⅱ级',
  },
  {
    id: '6',
    pipeRoad: '宁德市蕉城区蕉城南路管网段',
    areaName: '蕉城区',
    pipePressure: 0.33,
    gasConcentration: 0.7,
    deviceCode: 'FJ-ND-G-202406-006',
    deviceStatus: '在线',
    staffName: '吴永辉（工号：FJYW006）',
    collectFrequency: '5分钟',
    syncDuration: 3,
    monitorStatus: '运行中',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 15:32:15',
    warnLevelRule: 'Ⅰ级',
  },
  {
    id: '7',
    pipeRoad: '龙岩市新罗区中山路管网段',
    areaName: '新罗区',
    pipePressure: 0.40,
    gasConcentration: 0.95,
    deviceCode: 'FJ-LY-G-202406-007',
    deviceStatus: '在线',
    staffName: '张志强（工号：FJYW007）',
    collectFrequency: '10分钟',
    syncDuration: 4,
    monitorStatus: '运行中',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 15:18:49',
    warnLevelRule: 'Ⅱ级',
  },
  {
    id: '8',
    pipeRoad: '三明市梅列区列东街管网段',
    areaName: '梅列区',
    pipePressure: 0.30,
    gasConcentration: 0.6,
    deviceCode: 'FJ-SM-G-202406-008',
    deviceStatus: '在线',
    staffName: '李芳（工号：FJYW008）',
    collectFrequency: '30分钟',
    syncDuration: 5,
    monitorStatus: '运行中',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 15:22:05',
    warnLevelRule: 'Ⅰ级',
  },
  {
    id: '9',
    pipeRoad: '南平市延平区解放路管网段',
    areaName: '延平区',
    pipePressure: 0.37,
    gasConcentration: 0.85,
    deviceCode: 'FJ-NP-G-202406-009',
    deviceStatus: '异常',
    staffName: '刘建国（工号：FJYW009）',
    collectFrequency: '1分钟',
    syncDuration: 2,
    monitorStatus: '已停止',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 15:05:33',
    warnLevelRule: 'Ⅱ级',
  },
  {
    id: '10',
    pipeRoad: '平潭综合实验区金井湾管网段',
    areaName: '平潭综合实验区',
    pipePressure: 0.29,
    gasConcentration: 0.45,
    deviceCode: 'FJ-PTTH-G-202406-010',
    deviceStatus: '在线',
    staffName: '蔡伟明（工号：FJYW010）',
    collectFrequency: '1小时',
    syncDuration: 6,
    monitorStatus: '运行中',
    indexThresholdRange:
      '管网压力0.2~0.4MPa；燃气浓度≤1%；预警等级≤Ⅱ级',
    updateTime: '2024-06-28 15:15:20',
    warnLevelRule: 'Ⅰ级',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为燃气管网监测管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'pipeRoad',
      label: '管网路段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管网路段名称',
      },
      labelWidth: '120',
      rules: 'required', // 管网路段为必填项
    },
    {
      fieldName: 'areaName',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域（如：台江区、思明区）',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'pipePressure',
      label: '管网压力',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入管网压力（单位：MPa）',
        min: 0,
        precision: 2, // 保留2位小数，贴合压力计量场景
        addonAfter: 'MPa',
      },
      rules: 'required',
    },
    {
      fieldName: 'gasConcentration',
      label: '燃气浓度',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入燃气浓度（单位：%）',
        min: 0,
        precision: 2,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceCode',
      label: '监测设备编号',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入监测设备编号',
        maxLength: 50,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceStatus',
      label: '设备在线状态',
      rules: 'required',
    },
    {
      fieldName: 'staffName',
      label: '负责运维员',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入负责运维员姓名/工号',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '1分钟', value: '1分钟' },
          { label: '5分钟', value: '5分钟' },
          { label: '10分钟', value: '10分钟' },
          { label: '30分钟', value: '30分钟' },
          { label: '1小时', value: '1小时' },
          { label: '24小时', value: '24小时' },
        ],
        placeholder: '请选择数据采集频率',
        showSearch: true,
      },
      fieldName: 'collectFrequency',
      label: '数据采集频率',
      rules: 'required',
    },
    {
      fieldName: 'syncDuration',
      label: '数据同步时长',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入数据同步时长（单位：秒）',
        min: 1,
        precision: 0,
        addonAfter: '秒',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '运行中', value: '运行中' },
          { label: '已停止', value: '已停止' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择监测状态',
        showSearch: true,
      },
      fieldName: 'monitorStatus',
      label: '监测状态',
      rules: 'required',
    },
    {
      fieldName: 'indexThresholdRange',
      label: '指标阈值范围',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder:
          '请输入指标阈值范围（如：管网压力0.2~0.4MPa；燃气浓度≤1%）',
        maxlength: 200,
      },
      rules: 'required',
    },
    {
      fieldName: 'updateTime',
      label: '最近数据更新时间',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入最近数据更新时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: 'Ⅰ级', value: 'Ⅰ级' },
          { label: 'Ⅱ级', value: 'Ⅱ级' },
          { label: 'Ⅲ级', value: 'Ⅲ级' },
        ],
        placeholder: '请选择分级预警规则匹配结果',
        showSearch: true,
      },
      fieldName: 'warnLevelRule',
      label: '分级预警规则匹配结果',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为燃气管网监测管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'pipeRoad',
      title: '管网路段',
      minWidth: 180,
      sortable: true,
      slots: { default: 'pipeRoad' },
    },
    {
      field: 'areaName',
      title: '所属区域',
      minWidth: 160,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'pipePressure',
      title: '管网压力(MPa)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'gasConcentration',
      title: '燃气浓度(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'deviceCode',
      title: '监测设备编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'deviceCode' },
    },
    {
      field: 'deviceStatus',
      title: '设备在线状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'deviceStatus' },
    },
    {
      field: 'staffName',
      title: '负责运维员',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'collectFrequency',
      title: '数据采集频率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'syncDuration',
      title: '数据同步时长(秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monitorStatus',
      title: '监测状态',
      minWidth: 160,
      sortable: true,
      slots: { default: 'monitorStatus' },
    },
    {
      field: 'indexThresholdRange',
      title: '指标阈值范围',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'updateTime',
      title: '最近数据更新时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'warnLevelRule',
      title: '分级预警规则匹配结果',
      minWidth: 160,
      sortable: true,
    },
    {
      title: '操作',
      width: 120,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 搜索表单字段 - 改造为燃气管网监测管理搜索表单 */
export function useFilterFormSchema() {
  return [
    {
      fieldName: 'pipeRoad',
      label: '管网路段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管网路段名称',
      },
      labelWidth: '120',
      isSearch: true,
    },
    {
      fieldName: 'areaName',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域',
      },
      labelWidth: '120',
      isSearch: true,
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceStatus',
      label: '设备在线状态',
      isSearch: true,
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '运行中', value: '运行中' },
          { label: '已停止', value: '已停止' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择监测状态',
        showSearch: true,
      },
      fieldName: 'monitorStatus',
      label: '监测状态',
      isSearch: true,
    },
  ];
}