// data.js
/** 表格初始数据 - 预警数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "alarmId": "ALARM-20260120-001",
      "alarmLevel": "严重",
      "alarmType": "设备故障",
      "alarmTime": "2026-01-20 09:30:00",
      "assetName": "服务器集群-A",
      "assetId": "ASSET-001",
      "assetExtendId": "EXT-001",
      "location": "机房A区-02机柜",
      "alarmContent": "服务器CPU使用率持续超过95%达到30分钟，可能影响业务正常运行，需要立即处理",
      "source": "设备上报",
      "responsiblePerson": "张三",
      "dealStatus": "待处置",
      "dealStartTime": "",
      "dealProgress": "0%",
      "currentDealStatus": "未开始",
      "workorderNo": "",
      "updateTime": "2026-01-20 09:30:00",
      "dealLogSummary": "",
      "dealSummary": "",
      "disposalResult": "",
      "finishTime": "",
      "dealDuration": "",
      "reviewOpinion": "",
      "moduleType": "pending", // 待处置
      "attachmentCount": 0,
      "submitCount": 1,
      "latestDynamic": "系统检测到异常，已自动创建预警",
      "flowSummary": "设备故障预警，需要立即处理",
      "description": "服务器CPU使用率持续过高",
      "priority": "高",
      "taskName": "服务器CPU过载预警",
      "taskStatus": "待处置",
      "relatedResource": "监控截图",
      "initiator": "系统自动",
      "operator": "",
      "createTime": "2026-01-20 09:30:00",
      "assignTime": "2026-01-20 09:30:00"
    },
    {
      "id": 2,
      "alarmId": "ALARM-20260121-002",
      "alarmLevel": "高",
      "alarmType": "安全告警",
      "alarmTime": "2026-01-21 14:00:00",
      "assetName": "数据库服务器",
      "assetId": "ASSET-002",
      "assetExtendId": "EXT-002",
      "location": "机房B区-05机柜",
      "alarmContent": "检测到异常登录行为，IP地址192.168.1.100尝试暴力破解",
      "source": "系统检测",
      "responsiblePerson": "李四",
      "dealStatus": "处置中",
      "dealStartTime": "2026-01-21 14:30:00",
      "dealProgress": "60%",
      "currentDealStatus": "处理中",
      "workorderNo": "WO-20260121-001",
      "updateTime": "2026-01-21 16:00:00",
      "dealLogSummary": "已锁定异常IP，正在进行安全策略加固",
      "dealSummary": "",
      "disposalResult": "",
      "finishTime": "",
      "dealDuration": "",
      "reviewOpinion": "",
      "moduleType": "dealing", // 处置中
      "attachmentCount": 2,
      "submitCount": 1,
      "latestDynamic": "李四已开始处理，进度60%",
      "flowSummary": "安全告警正在处理中",
      "description": "异常登录行为检测",
      "priority": "紧急",
      "taskName": "安全告警处理",
      "taskStatus": "处置中",
      "relatedResource": "安全日志",
      "initiator": "系统自动",
      "operator": "李四",
      "createTime": "2026-01-21 14:00:00",
      "assignTime": "2026-01-21 14:30:00"
    },
    {
      "id": 3,
      "alarmId": "ALARM-20260119-003",
      "alarmLevel": "中",
      "alarmType": "性能预警",
      "alarmTime": "2026-01-19 10:00:00",
      "assetName": "网络交换机",
      "assetId": "ASSET-003",
      "assetExtendId": "EXT-003",
      "location": "机房A区-01机柜",
      "alarmContent": "网络端口流量达到带宽80%，建议扩容或优化",
      "source": "设备上报",
      "responsiblePerson": "王五",
      "dealStatus": "已处理",
      "dealStartTime": "2026-01-19 11:00:00",
      "dealProgress": "100%",
      "currentDealStatus": "已完成",
      "workorderNo": "WO-20260119-001",
      "updateTime": "2026-01-20 09:00:00",
      "dealLogSummary": "已完成流量优化，调整了负载均衡策略",
      "dealSummary": "通过调整负载均衡策略和优化路由，网络性能恢复正常",
      "disposalResult": "已解决",
      "finishTime": "2026-01-20 09:00:00",
      "dealDuration": "22小时",
      "reviewOpinion": "处理及时，措施有效",
      "moduleType": "archived", // 已归档
      "attachmentCount": 3,
      "submitCount": 1,
      "latestDynamic": "预警已处理完成并归档",
      "flowSummary": "性能预警已解决",
      "description": "网络流量过高预警",
      "priority": "中",
      "taskName": "网络性能预警",
      "taskStatus": "已归档",
      "relatedResource": "优化报告",
      "initiator": "系统自动",
      "operator": "王五",
      "createTime": "2026-01-19 10:00:00",
      "assignTime": "2026-01-19 11:00:00"
    },
    {
      "id": 4,
      "alarmId": "ALARM-20260118-004",
      "alarmLevel": "低",
      "alarmType": "环境监测",
      "alarmTime": "2026-01-18 13:00:00",
      "assetName": "温湿度传感器",
      "assetId": "ASSET-004",
      "assetExtendId": "EXT-004",
      "location": "机房A区-空调房",
      "alarmContent": "机房温度超过25℃，湿度低于30%，可能影响设备运行",
      "source": "设备上报",
      "responsiblePerson": "",
      "dealStatus": "已忽略",
      "dealStartTime": "",
      "dealProgress": "0%",
      "currentDealStatus": "已忽略",
      "workorderNo": "",
      "updateTime": "2026-01-19 10:00:00",
      "dealLogSummary": "经检查属于误报，已忽略",
      "dealSummary": "",
      "disposalResult": "已忽略",
      "finishTime": "2026-01-19 10:00:00",
      "dealDuration": "",
      "reviewOpinion": "",
      "moduleType": "pending", // 待处置
      "attachmentCount": 0,
      "submitCount": 1,
      "latestDynamic": "预警被标记为已忽略",
      "flowSummary": "环境监测预警已忽略",
      "description": "温湿度异常告警",
      "priority": "低",
      "taskName": "环境监测预警",
      "taskStatus": "已忽略",
      "relatedResource": "",
      "initiator": "系统自动",
      "operator": "",
      "createTime": "2026-01-18 13:00:00",
      "assignTime": ""
    },
    {
      "id": 5,
      "alarmId": "ALARM-20260122-005",
      "alarmLevel": "严重",
      "alarmType": "电源故障",
      "alarmTime": "2026-01-22 08:30:00",
      "assetName": "UPS电源",
      "assetId": "ASSET-005",
      "assetExtendId": "EXT-005",
      "location": "机房总配电室",
      "alarmContent": "UPS主电源输入异常，备用电池供电中，剩余时间45分钟",
      "source": "设备上报",
      "responsiblePerson": "赵六",
      "dealStatus": "处置中",
      "dealStartTime": "2026-01-22 08:40:00",
      "dealProgress": "40%",
      "currentDealStatus": "协同处理中",
      "workorderNo": "WO-20260122-001",
      "updateTime": "2026-01-22 10:00:00",
      "dealLogSummary": "已通知电力部门紧急维修，正在切换备用电源",
      "dealSummary": "",
      "disposalResult": "",
      "finishTime": "",
      "dealDuration": "",
      "reviewOpinion": "",
      "moduleType": "dealing", // 处置中
      "attachmentCount": 1,
      "submitCount": 1,
      "latestDynamic": "赵六正在处理，已联系电力部门",
      "flowSummary": "电源故障紧急处理中",
      "description": "UPS电源输入异常",
      "priority": "紧急",
      "taskName": "电源故障预警",
      "taskStatus": "处置中",
      "relatedResource": "电源监控图",
      "initiator": "系统自动",
      "operator": "赵六",
      "createTime": "2026-01-22 08:30:00",
      "assignTime": "2026-01-22 08:40:00"
    },
    {
      "id": 6,
      "alarmId": "ALARM-20260120-006",
      "alarmLevel": "中",
      "alarmType": "存储预警",
      "alarmTime": "2026-01-20 09:30:00",
      "assetName": "存储阵列",
      "assetId": "ASSET-006",
      "assetExtendId": "EXT-006",
      "location": "机房B区-存储区",
      "alarmContent": "存储空间使用率达到85%，建议清理或扩容",
      "source": "系统检测",
      "responsiblePerson": "孙七",
      "dealStatus": "已处理",
      "dealStartTime": "2026-01-20 10:00:00",
      "dealProgress": "100%",
      "currentDealStatus": "已完成",
      "workorderNo": "WO-20260120-001",
      "updateTime": "2026-01-21 15:00:00",
      "dealLogSummary": "已清理临时文件，存储使用率降至70%",
      "dealSummary": "清理了系统临时文件和过期日志，释放了15%存储空间",
      "disposalResult": "已解决",
      "finishTime": "2026-01-21 15:00:00",
      "dealDuration": "29小时",
      "reviewOpinion": "处理措施得当，建议定期清理",
      "moduleType": "archived", // 已归档
      "attachmentCount": 2,
      "submitCount": 1,
      "latestDynamic": "存储预警已处理完成",
      "flowSummary": "存储空间预警已解决",
      "description": "存储空间不足预警",
      "priority": "中",
      "taskName": "存储预警处理",
      "taskStatus": "已归档",
      "relatedResource": "清理报告",
      "initiator": "系统自动",
      "operator": "孙七",
      "createTime": "2026-01-20 09:30:00",
      "assignTime": "2026-01-20 10:00:00"
    },
    {
      "id": 7,
      "alarmId": "ALARM-20260115-007",
      "alarmLevel": "高",
      "alarmType": "应用异常",
      "alarmTime": "2026-01-15 10:00:00",
      "assetName": "应用服务器",
      "assetId": "ASSET-007",
      "assetExtendId": "EXT-007",
      "location": "机房A区-03机柜",
      "alarmContent": "订单系统响应时间超过5秒，影响用户体验",
      "source": "系统检测",
      "responsiblePerson": "周八",
      "dealStatus": "待处置",
      "dealStartTime": "",
      "dealProgress": "0%",
      "currentDealStatus": "未开始",
      "workorderNo": "",
      "updateTime": "2026-01-15 10:00:00",
      "dealLogSummary": "",
      "dealSummary": "",
      "disposalResult": "",
      "finishTime": "",
      "dealDuration": "",
      "reviewOpinion": "",
      "moduleType": "pending", // 待处置
      "attachmentCount": 0,
      "submitCount": 1,
      "latestDynamic": "系统检测到应用响应异常",
      "flowSummary": "应用响应超时预警",
      "description": "订单系统响应时间过长",
      "priority": "高",
      "taskName": "应用异常预警",
      "taskStatus": "待处置",
      "relatedResource": "性能监控图",
      "initiator": "系统自动",
      "operator": "",
      "createTime": "2026-01-15 10:00:00",
      "assignTime": ""
    },
    {
      "id": 8,
      "alarmId": "ALARM-20260122-008",
      "alarmLevel": "低",
      "alarmType": "备份异常",
      "alarmTime": "2026-01-22 09:00:00",
      "assetName": "备份服务器",
      "assetId": "ASSET-008",
      "assetExtendId": "EXT-008",
      "location": "机房B区-08机柜",
      "alarmContent": "昨晚的数据库备份任务失败，需要手动检查",
      "source": "系统检测",
      "responsiblePerson": "吴九",
      "dealStatus": "已处理",
      "dealStartTime": "2026-01-22 09:30:00",
      "dealProgress": "100%",
      "currentDealStatus": "已完成",
      "workorderNo": "WO-20260122-002",
      "updateTime": "2026-01-22 11:00:00",
      "dealLogSummary": "检查发现磁盘空间不足，清理后重新执行备份成功",
      "dealSummary": "清理临时文件释放空间，重新执行备份任务成功",
      "disposalResult": "已解决",
      "finishTime": "2026-01-22 11:00:00",
      "dealDuration": "2小时",
      "reviewOpinion": "备份流程需要优化自动化",
      "moduleType": "archived", // 已归档
      "attachmentCount": 1,
      "submitCount": 1,
      "latestDynamic": "备份异常已修复",
      "flowSummary": "备份任务失败预警已解决",
      "description": "数据库备份失败",
      "priority": "低",
      "taskName": "备份异常预警",
      "taskStatus": "已归档",
      "relatedResource": "备份日志",
      "initiator": "系统自动",
      "operator": "吴九",
      "createTime": "2026-01-22 09:00:00",
      "assignTime": "2026-01-22 09:30:00"
    }
    // ... 可以根据需要添加更多数据
  ];
};

/** 新增/修改的表单/列表的搜索表单 - 根据模块类型返回不同表单 */
export function useFormSchema(moduleType = 'pending') {
  const baseSchema = [
    {
      fieldName: 'alarmId',
      label: '预警ID',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入预警ID',
      },
    }
  ];

  switch(moduleType) {
    case 'pending': // 待处置
      return [
        ...baseSchema,
        {
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            allowClear: true,
            filterOption: true,
            options: [
              { label: '严重', value: '严重' },
              { label: '高', value: '高' },
              { label: '中', value: '中' },
              { label: '低', value: '低' },
            ],
            placeholder: '请选择预警等级',
            showSearch: true,
          },
          fieldName: 'alarmLevel',
          label: '预警等级',
        },
        {
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            allowClear: true,
            filterOption: true,
            options: [
              { label: '设备故障', value: '设备故障' },
              { label: '安全告警', value: '安全告警' },
              { label: '性能预警', value: '性能预警' },
              { label: '环境监测', value: '环境监测' },
              { label: '电源故障', value: '电源故障' },
              { label: '存储预警', value: '存储预警' },
              { label: '应用异常', value: '应用异常' },
              { label: '备份异常', value: '备份异常' },
              { label: '网络异常', value: '网络异常' },
              { label: '其他', value: '其他' },
            ],
            placeholder: '请选择预警类型',
            showSearch: true,
          },
          fieldName: 'alarmType',
          label: '预警类型',
        },
        {
          fieldName: 'alarmTime',
          label: '发生时间',
          component: 'DatePicker',
          labelWidth: '100',
          componentProps: {
            type: 'daterange',
            placeholder: '请选择发生时间范围',
          },
        },
        {
          fieldName: 'location',
          label: '发生地点',
          component: 'Input',
          labelWidth: '100',
          componentProps: {
            placeholder: '请输入发生地点',
          },
        },
        {
          fieldName: 'source',
          label: '预警来源',
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            options: [
              { label: '设备上报', value: '设备上报' },
              { label: '系统检测', value: '系统检测' },
            ],
            placeholder: '请选择预警来源',
          },
        }
      ];

    case 'dealing': // 处置中
      return [
        ...baseSchema,
        {
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            allowClear: true,
            filterOption: true,
            options: [
              { label: '设备故障', value: '设备故障' },
              { label: '安全告警', value: '安全告警' },
              { label: '性能预警', value: '性能预警' },
              { label: '环境监测', value: '环境监测' },
              { label: '电源故障', value: '电源故障' },
              { label: '存储预警', value: '存储预警' },
              { label: '应用异常', value: '应用异常' },
              { label: '备份异常', value: '备份异常' },
              { label: '网络异常', value: '网络异常' },
              { label: '其他', value: '其他' },
            ],
            placeholder: '请选择预警类型',
            showSearch: true,
          },
          fieldName: 'alarmType',
          label: '预警类型',
        },
        {
          fieldName: 'responsiblePerson',
          label: '处置人',
          component: 'Input',
          labelWidth: '100',
          componentProps: {
            placeholder: '请输入处置人',
          },
        },
        {
          fieldName: 'currentDealStatus',
          label: '处置状态',
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            options: [
              { label: '处理中', value: '处理中' },
              { label: '协同处理中', value: '协同处理中' },
              { label: '待验证', value: '待验证' },
              { label: '挂起', value: '挂起' },
            ],
            placeholder: '请选择处置状态',
          },
        },
        {
          fieldName: 'dealStartTime',
          label: '开始处置时间',
          component: 'DatePicker',
          labelWidth: '100',
          componentProps: {
            type: 'daterange',
            placeholder: '请选择开始处置时间范围',
          },
        },
        {
          fieldName: 'workorderNo',
          label: '工单编号',
          component: 'Input',
          labelWidth: '100',
          componentProps: {
            placeholder: '请输入工单编号',
          },
        }
      ];

    case 'archived': // 已归档
      return [
        ...baseSchema,
        {
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            allowClear: true,
            filterOption: true,
            options: [
              { label: '严重', value: '严重' },
              { label: '高', value: '高' },
              { label: '中', value: '中' },
              { label: '低', value: '低' },
            ],
            placeholder: '请选择预警等级',
            showSearch: true,
          },
          fieldName: 'alarmLevel',
          label: '预警等级',
        },
        {
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            allowClear: true,
            filterOption: true,
            options: [
              { label: '设备故障', value: '设备故障' },
              { label: '安全告警', value: '安全告警' },
              { label: '性能预警', value: '性能预警' },
              { label: '环境监测', value: '环境监测' },
              { label: '电源故障', value: '电源故障' },
              { label: '存储预警', value: '存储预警' },
              { label: '应用异常', value: '应用异常' },
              { label: '备份异常', value: '备份异常' },
              { label: '网络异常', value: '网络异常' },
              { label: '其他', value: '其他' },
            ],
            placeholder: '请选择预警类型',
            showSearch: true,
          },
          fieldName: 'alarmType',
          label: '预警类型',
        },
        {
          fieldName: 'disposalResult',
          label: '处置结果',
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            options: [
              { label: '已解决', value: '已解决' },
              { label: '已忽略', value: '已忽略' },
              { label: '误报', value: '误报' },
              { label: '无法解决', value: '无法解决' },
            ],
            placeholder: '请选择处置结果',
          },
        },
        {
          fieldName: 'finishTime',
          label: '完成时间',
          component: 'DatePicker',
          labelWidth: '100',
          componentProps: {
            type: 'daterange',
            placeholder: '请选择完成时间范围',
          },
        },
        {
          fieldName: 'responsiblePerson',
          label: '处置人',
          component: 'Input',
          labelWidth: '100',
          componentProps: {
            placeholder: '请输入处置人',
          },
        }
      ];

    default:
      return baseSchema;
  }
}

/** 表格字段 - 根据模块类型返回不同列配置 */
export function useGridColumns(moduleType = 'pending') {
  const baseColumns = [
    { type: 'checkbox', width: 40 },
    {
      field: 'alarmId',
      title: '预警ID',
      minWidth: 180,
      sortable: true,
      slots: { default: 'alarmId' },
    }
  ];

  switch(moduleType) {
    case 'pending': // 待处置
      return [
        ...baseColumns,
        {
          field: 'alarmLevel',
          title: '预警等级',
          minWidth: 100,
          sortable: true,
          slots: { default: 'alarmLevel' },
        },
        {
          field: 'alarmType',
          title: '预警类型',
          minWidth: 120,
          sortable: true,
          slots: { default: 'alarmType' },
        },
        {
          field: 'alarmTime',
          title: '发生时间',
          minWidth: 160,
          sortable: true,
        },
        {
          field: 'assetName',
          title: '关联对象',
          minWidth: 150,
          sortable: true,
          slots: { default: 'assetName' },
        },
        {
          field: 'location',
          title: '发生地点',
          minWidth: 150,
        },
        {
          field: 'alarmContent',
          title: '预警描述',
          minWidth: 200,
          formatter: ({ cellValue }) => cellValue ? (cellValue.length > 50 ? cellValue.substring(0, 50) + '...' : cellValue) : '-',
        },
        {
          field: 'source',
          title: '预警来源',
          minWidth: 100,
          slots: { default: 'source' },
        },
        {
          title: '操作',
          width: 280,
          fixed: 'right',
          slots: { default: 'pendingActions' },
        },
      ];

    case 'dealing': // 处置中
      return [
        ...baseColumns,
        {
          field: 'alarmLevel',
          title: '预警等级',
          minWidth: 100,
          sortable: true,
          slots: { default: 'alarmLevel' },
        },
        {
          field: 'alarmType',
          title: '预警类型',
          minWidth: 120,
          sortable: true,
          slots: { default: 'alarmType' },
        },
        {
          field: 'responsiblePerson',
          title: '处置人',
          minWidth: 100,
          sortable: true,
          slots: { default: 'responsiblePerson' },
        },
        {
          field: 'dealStartTime',
          title: '开始处置时间',
          minWidth: 160,
          sortable: true,
        },
        {
          field: 'currentDealStatus',
          title: '当前处置状态',
          minWidth: 120,
          sortable: true,
          slots: { default: 'currentDealStatus' },
        },
        {
          field: 'workorderNo',
          title: '关联工单',
          minWidth: 150,
          slots: { default: 'workorderNo' },
        },
        {
          field: 'dealProgress',
          title: '处置进度',
          minWidth: 100,
          sortable: true,
          slots: { default: 'dealProgress' },
        },
        {
          title: '操作',
          width: 280,
          fixed: 'right',
          slots: { default: 'dealingActions' },
        },
      ];

    case 'archived': // 已归档
      return [
        ...baseColumns,
        {
          field: 'alarmLevel',
          title: '预警等级',
          minWidth: 100,
          sortable: true,
          slots: { default: 'alarmLevel' },
        },
        {
          field: 'alarmType',
          title: '预警类型',
          minWidth: 120,
          sortable: true,
          slots: { default: 'alarmType' },
        },
        {
          field: 'disposalResult',
          title: '处置结果',
          minWidth: 100,
          sortable: true,
          slots: { default: 'disposalResult' },
        },
        {
          field: 'finishTime',
          title: '完成时间',
          minWidth: 160,
          sortable: true,
        },
        {
          field: 'dealSummary',
          title: '处置总结',
          minWidth: 180,
          formatter: ({ cellValue }) => cellValue ? (cellValue.length > 50 ? cellValue.substring(0, 50) + '...' : cellValue) : '-',
        },
        {
          field: 'responsiblePerson',
          title: '处置人',
          minWidth: 100,
          sortable: true,
        },
        {
          field: 'dealDuration',
          title: '处置时长',
          minWidth: 100,
          sortable: true,
        },
        {
          title: '操作',
          width: 200,
          fixed: 'right',
          slots: { default: 'archivedActions' },
        },
      ];

    default:
      return baseColumns;
  }
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑预警',
  addText: '新增预警',
  excelName: '预警列表',
  excelAllName: '预警数据.xlsx',
  total: '预警总数: 50; 待处置: 15; 处置中: 12; 已归档: 23;',
};
