/** 边缘网关表格初始数据 - 按指定字段生成 */
export const dataList = () => {
  return [
    {
      gatewayName: '主入口边缘网关',
      gatewayCode: 'GW-001',
      assetName: '芗城区XX社区公共停车场资产',
      ipAddress: '192.168.1.100',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '8GB',
      offlineCacheHour: 72,
      gatewayId: 'GATEWAY001',
      gatewayStatusName: '运行中',
      configTime: '2025-01-01 09:00:00',
      configBy: '张三',
      relatedDeviceCount: 15,
    },
    {
      gatewayName: '出口边缘网关',
      gatewayCode: 'GW-002',
      assetName: '龙文区碧湖公园停车场资产',
      ipAddress: '192.168.1.101',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '8GB',
      offlineCacheHour: 72,
      gatewayId: 'GATEWAY002',
      gatewayStatusName: '运行中',
      configTime: '2025-01-02 14:30:00',
      configBy: '李四',
      relatedDeviceCount: 12,
    },
    {
      gatewayName: 'A区边缘网关',
      gatewayCode: 'GW-003',
      assetName: '龙海区石码镇便民停车场资产',
      ipAddress: '192.168.1.102',
      port: 8080,
      networkTypeName: '无线网络',
      protocolTypeName: 'HTTP',
      cacheCapacity: '4GB',
      offlineCacheHour: 48,
      gatewayId: 'GATEWAY003',
      gatewayStatusName: '离线',
      configTime: '2025-01-03 10:15:00',
      configBy: '王五',
      relatedDeviceCount: 8,
    },
    {
      gatewayName: 'B区边缘网关',
      gatewayCode: 'GW-004',
      assetName: '龙海区闽齐社区停车场资产',
      ipAddress: '192.168.1.103',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '8GB',
      offlineCacheHour: 72,
      gatewayId: 'GATEWAY004',
      gatewayStatusName: '故障',
      configTime: '2025-01-04 08:30:00',
      configBy: '赵六',
      relatedDeviceCount: 10,
    },
    {
      gatewayName: 'C区边缘网关',
      gatewayCode: 'GW-005',
      assetName: '芗城区江滨路生态停车场资产',
      ipAddress: '192.168.1.104',
      port: 8080,
      networkTypeName: '无线网络',
      protocolTypeName: 'HTTP',
      cacheCapacity: '4GB',
      offlineCacheHour: 48,
      gatewayId: 'GATEWAY005',
      gatewayStatusName: '运行中',
      configTime: '2025-01-05 16:40:00',
      configBy: '孙七',
      relatedDeviceCount: 6,
    },
    {
      gatewayName: 'D区边缘网关',
      gatewayCode: 'GW-006',
      assetName: '龙文区万达商圈停车场资产',
      ipAddress: '192.168.1.105',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '16GB',
      offlineCacheHour: 96,
      gatewayId: 'GATEWAY006',
      gatewayStatusName: '运行中',
      configTime: '2025-01-06 11:20:00',
      configBy: '周八',
      relatedDeviceCount: 20,
    },
    {
      gatewayName: 'E区边缘网关',
      gatewayCode: 'GW-007',
      assetName: '长泰区武安镇公共停车场资产',
      ipAddress: '192.168.1.106',
      port: 8080,
      networkTypeName: '无线网络',
      protocolTypeName: 'HTTP',
      cacheCapacity: '4GB',
      offlineCacheHour: 48,
      gatewayId: 'GATEWAY007',
      gatewayStatusName: '维护中',
      configTime: '2025-01-07 13:25:00',
      configBy: '吴九',
      relatedDeviceCount: 5,
    },
    {
      gatewayName: 'F区边缘网关',
      gatewayCode: 'GW-008',
      assetName: '漳浦县绥安镇便民停车场资产',
      ipAddress: '192.168.1.107',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '8GB',
      offlineCacheHour: 72,
      gatewayId: 'GATEWAY008',
      gatewayStatusName: '离线',
      configTime: '2025-01-08 09:50:00',
      configBy: '郑十',
      relatedDeviceCount: 7,
    },
    {
      gatewayName: 'G区边缘网关',
      gatewayCode: 'GW-009',
      assetName: '芗城区巷口街道停车场资产',
      ipAddress: '192.168.1.108',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '8GB',
      offlineCacheHour: 72,
      gatewayId: 'GATEWAY009',
      gatewayStatusName: '运行中',
      configTime: '2025-01-09 15:15:00',
      configBy: '张三',
      relatedDeviceCount: 12,
    },
    {
      gatewayName: 'H区边缘网关',
      gatewayCode: 'GW-010',
      assetName: '龙文区蓝田街道停车场资产',
      ipAddress: '192.168.1.109',
      port: 8080,
      networkTypeName: '无线网络',
      protocolTypeName: 'HTTP',
      cacheCapacity: '4GB',
      offlineCacheHour: 48,
      gatewayId: 'GATEWAY010',
      gatewayStatusName: '故障',
      configTime: '2025-01-10 10:30:00',
      configBy: '李四',
      relatedDeviceCount: 6,
    },
    {
      gatewayName: 'I区边缘网关',
      gatewayCode: 'GW-011',
      assetName: '龙文区步文街道停车场资产',
      ipAddress: '192.168.1.110',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '16GB',
      offlineCacheHour: 96,
      gatewayId: 'GATEWAY011',
      gatewayStatusName: '运行中',
      configTime: '2025-01-11 14:20:00',
      configBy: '王五',
      relatedDeviceCount: 18,
    },
    {
      gatewayName: 'J区边缘网关',
      gatewayCode: 'GW-012',
      assetName: '芗城区东铺头街道停车场资产',
      ipAddress: '192.168.1.111',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '8GB',
      offlineCacheHour: 72,
      gatewayId: 'GATEWAY012',
      gatewayStatusName: '维护中',
      configTime: '2025-01-12 09:40:00',
      configBy: '赵六',
      relatedDeviceCount: 9,
    },
    {
      gatewayName: 'K区边缘网关',
      gatewayCode: 'GW-013',
      assetName: '全市通用资产',
      ipAddress: '192.168.1.112',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '8GB',
      offlineCacheHour: 72,
      gatewayId: 'GATEWAY013',
      gatewayStatusName: '运行中',
      configTime: '2025-01-13 11:25:00',
      configBy: '孙七',
      relatedDeviceCount: 14,
    },
    {
      gatewayName: 'L区边缘网关',
      gatewayCode: 'GW-014',
      assetName: '龙文区万达商圈停车场资产',
      ipAddress: '192.168.1.113',
      port: 8080,
      networkTypeName: '无线网络',
      protocolTypeName: 'HTTP',
      cacheCapacity: '4GB',
      offlineCacheHour: 48,
      gatewayId: 'GATEWAY014',
      gatewayStatusName: '离线',
      configTime: '2025-01-14 16:30:00',
      configBy: '周八',
      relatedDeviceCount: 7,
    },
    {
      gatewayName: 'M区边缘网关',
      gatewayCode: 'GW-015',
      assetName: '芗城区江滨路生态停车场资产',
      ipAddress: '192.168.1.114',
      port: 8080,
      networkTypeName: '有线网络',
      protocolTypeName: 'MQTT',
      cacheCapacity: '8GB',
      offlineCacheHour: 72,
      gatewayId: 'GATEWAY015',
      gatewayStatusName: '运行中',
      configTime: '2025-01-15 10:15:00',
      configBy: '吴九',
      relatedDeviceCount: 13,
    },
  ];
};

/** 边缘网关表单配置（包含所有指定字段） */
export function useFormSchema() {
  return [
    {
      fieldName: 'gatewayId',
      label: '网关ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入网关ID',
      },
      rules: 'required',
    },
    {
      fieldName: 'gatewayName',
      label: '网关名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入网关名称',
      },
      rules: 'required',
    },
    {
      fieldName: 'gatewayCode',
      label: '网关编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入网关编码',
      },
      rules: 'required',
    },
    {
      fieldName: 'assetName',
      label: '所属资产',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属资产',
      },
      rules: 'required',
    },
    {
      fieldName: 'ipAddress',
      label: 'IP地址',
      component: 'Input',
      componentProps: {
        placeholder: '请输入IP地址',
      },
      rules: 'required',
    },
    {
      fieldName: 'port',
      label: '通信端口',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入通信端口',
        min: 1,
        max: 65_535,
      },
      rules: 'required',
    },
    {
      fieldName: 'networkTypeName',
      label: '网络类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择网络类型',
        options: [
          { label: '有线网络', value: '有线网络' },
          { label: '无线网络', value: '无线网络' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'protocolTypeName',
      label: '通信协议',
      component: 'Select',
      componentProps: {
        placeholder: '请选择通信协议',
        options: [
          { label: 'MQTT', value: 'MQTT' },
          { label: 'HTTP', value: 'HTTP' },
          { label: 'WebSocket', value: 'WebSocket' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'cacheCapacity',
      label: '缓存容量',
      component: 'Input',
      componentProps: {
        placeholder: '请输入缓存容量',
      },
      rules: 'required',
    },
    {
      fieldName: 'offlineCacheHour',
      label: '断网缓存时长',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入断网缓存时长',
        min: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'gatewayStatusName',
      label: '运行状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择运行状态',
        options: [
          { label: '运行中', value: '运行中' },
          { label: '离线', value: '离线' },
          { label: '故障', value: '故障' },
          { label: '维护中', value: '维护中' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'configTime',
      label: '配置时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择配置时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'configBy',
      label: '配置人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入配置人',
      },
      rules: 'required',
    },
    {
      fieldName: 'relatedDeviceCount',
      label: '关联设备数',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入关联设备数',
        min: 0,
      },
      rules: 'required',
    },
  ];
}

/** 边缘网关表格列配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'gatewayId',
      title: '网关ID',
      minWidth: 100,
      sortable: true,
      slots: { default: 'gatewayId' },
    },
    {
      field: 'gatewayName',
      title: '网关名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'gatewayCode',
      title: '网关编码',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'assetName',
      title: '所属资产',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'ipAddress',
      title: 'IP地址',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'port',
      title: '通信端口',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'networkTypeName',
      title: '网络类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'protocolTypeName',
      title: '通信协议',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'cacheCapacity',
      title: '缓存容量',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'offlineCacheHour',
      title: '断网缓存时长',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'gatewayStatusName',
      title: '运行状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'gatewayStatusName' },
    },
    {
      field: 'configTime',
      title: '配置时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'configBy',
      title: '配置人',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'relatedDeviceCount',
      title: '关联设备数',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 100,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

export const textObj = {
  editText: '编辑边缘网关',
  addText: '新增边缘网关',
  excelName: '边缘网关列表',
  excelAllName: '边缘网关数据.xlsx',
  total: ' 总计: 网关数量15; 运行中8; 离线3; 故障2; 维护中2',
};

/** 详情抽屉字段配置 */
export const detailFields = [
  { key: 'gatewayId', label: '网关ID' },
  { key: 'gatewayName', label: '网关名称' },
  { key: 'gatewayCode', label: '网关编码' },
  { key: 'assetName', label: '所属资产' },
  { key: 'ipAddress', label: 'IP地址' },
  { key: 'port', label: '通信端口' },
  { key: 'networkTypeName', label: '网络类型' },
  { key: 'protocolTypeName', label: '通信协议' },
  { key: 'cacheCapacity', label: '缓存容量' },
  { key: 'offlineCacheHour', label: '断网缓存时长' },
  { key: 'gatewayStatusName', label: '运行状态' },
  { key: 'configTime', label: '配置时间' },
  { key: 'configBy', label: '配置人' },
  { key: 'relatedDeviceCount', label: '关联设备数' },
];
