/** 付款方数据列表 */
export const payerList = () => {
  return [
    {
      merchantId: 'company-001',
      merchantName: '企业大厦有限公司',
      merchantCode: 'COMP-001',
      contactPerson: '张三',
      contactPhone: '13800138001',
      address: '福建省厦门市思明区湖滨南路123号',
      businessScope: '企业管理服务',
      status: '启用',
      settlementRatio: 85,
      createTime: '2025-01-01 00:00:00',
      updateTime: '2025-01-01 00:00:00',
      createBy: 'admin',
      remark: '企业大厦付款方',
    },
    {
      merchantId: 'gov-001',
      merchantName: '政府办公大楼管理处',
      merchantCode: 'GOV-001',
      contactPerson: '李四',
      contactPhone: '13800138002',
      address: '福建省厦门市思明区湖滨北路456号',
      businessScope: '政府服务',
      status: '启用',
      settlementRatio: 100,
      createTime: '2025-02-01 00:00:00',
      updateTime: '2025-02-01 00:00:00',
      createBy: 'admin',
      remark: '政府办公大楼付款方',
    },
    {
      merchantId: 'merchant-001',
      merchantName: '商场管理有限公司',
      merchantCode: 'MERC-001',
      contactPerson: '王五',
      contactPhone: '13800138003',
      address: '福建省厦门市思明区中山路789号',
      businessScope: '商场管理服务',
      status: '启用',
      settlementRatio: 90,
      createTime: '2025-03-01 00:00:00',
      updateTime: '2025-03-01 00:00:00',
      createBy: 'admin',
      remark: '商场VIP客户付款方',
    },
    {
      merchantId: 'hospital-001',
      merchantName: '医院管理有限公司',
      merchantCode: 'HOSP-001',
      contactPerson: '赵六',
      contactPhone: '13800138004',
      address: '福建省厦门市思明区厦禾路101号',
      businessScope: '医院管理服务',
      status: '启用',
      settlementRatio: 95,
      createTime: '2025-04-01 00:00:00',
      updateTime: '2025-04-01 00:00:00',
      createBy: 'admin',
      remark: '医院员工付款方',
    },
    {
      merchantId: 'school-001',
      merchantName: '学校管理有限公司',
      merchantCode: 'SCH-001',
      contactPerson: '孙七',
      contactPhone: '13800138005',
      address: '福建省厦门市思明区思明南路202号',
      businessScope: '学校管理服务',
      status: '启用',
      settlementRatio: 92,
      createTime: '2025-05-01 00:00:00',
      updateTime: '2025-05-01 00:00:00',
      createBy: 'admin',
      remark: '学校教职工付款方',
    },
  ];
};

/** 代付规则表初始数据 */
export const proxyRuleList = () => {
  return [
    {
      proxyId: '1',
      proxyName: '企业员工代付规则',
      proxyType: '企业代付',
      payerId: 'company-001',
      payeeType: '用户',
      assetIds: JSON.stringify(['asset-001', 'asset-002']),
      status: '启用',
      parkIds: JSON.stringify(['park-001', 'park-002', 'park-003']),
      singleAmount: 50,
      monthlyAmount: 200,
      objectType: '部门',
      objectIds: JSON.stringify(['dept-001', 'dept-002']),
      startTime: '2026-01-01 00:00:00',
      endTime: '2026-12-31 23:59:59',
      createBy: 'admin',
      createTime: '2026-01-01 09:00:00',
      updateTime: '2026-01-01 09:00:00',
      remark: '企业员工停车代付规则，单笔50元，月度200元',
    },
    {
      proxyId: '2',
      proxyName: '政府公务车代付规则',
      proxyType: '政府代付',
      payerId: 'gov-001',
      payeeType: '用户',
      assetIds: JSON.stringify(['asset-003', 'asset-004']),
      status: '启用',
      parkIds: JSON.stringify(['park-001', 'park-004', 'park-005']),
      singleAmount: 100,
      monthlyAmount: 1000,
      objectType: '车牌',
      objectIds: JSON.stringify(['闽E·A1234', '闽E·B5678', '闽E·C9012']),
      startTime: '2026-01-01 00:00:00',
      endTime: '2026-12-31 23:59:59',
      createBy: 'admin',
      createTime: '2026-01-02 10:00:00',
      updateTime: '2026-01-02 10:00:00',
      remark: '政府公务车停车代付规则，单笔100元，月度1000元',
    },
    {
      proxyId: '3',
      proxyName: '商场VIP客户代付规则',
      proxyType: '指定用户代付',
      payerId: 'merchant-001',
      payeeType: '用户',
      assetIds: JSON.stringify(['asset-005']),
      status: '禁用',
      parkIds: JSON.stringify(['park-006']),
      singleAmount: 30,
      monthlyAmount: 100,
      objectType: '车牌',
      objectIds: JSON.stringify(['闽E·D3456', '闽E·E7890']),
      startTime: '2026-01-01 00:00:00',
      endTime: '2026-03-31 23:59:59',
      createBy: 'admin',
      createTime: '2026-01-03 14:00:00',
      updateTime: '2026-01-10 16:00:00',
      remark: '商场VIP客户停车代付规则，单笔30元，月度100元，已禁用',
    },
    {
      proxyId: '4',
      proxyName: '医院员工代付规则',
      proxyType: '企业代付',
      payerId: 'hospital-001',
      payeeType: '用户',
      assetIds: JSON.stringify(['asset-006', 'asset-007']),
      status: '启用',
      parkIds: JSON.stringify(['park-007', 'park-008']),
      singleAmount: 40,
      monthlyAmount: 150,
      objectType: '部门',
      objectIds: JSON.stringify(['dept-003', 'dept-004', 'dept-005']),
      startTime: '2026-01-01 00:00:00',
      endTime: '2026-12-31 23:59:59',
      createBy: 'admin',
      createTime: '2026-01-04 09:30:00',
      updateTime: '2026-01-04 09:30:00',
      remark: '医院员工停车代付规则，单笔40元，月度150元',
    },
    {
      proxyId: '5',
      proxyName: '学校教职工代付规则',
      proxyType: '企业代付',
      payerId: 'school-001',
      payeeType: '用户',
      assetIds: JSON.stringify(['asset-008']),
      status: '启用',
      parkIds: JSON.stringify(['park-009']),
      singleAmount: 25,
      monthlyAmount: 100,
      objectType: '部门',
      objectIds: JSON.stringify(['dept-006']),
      startTime: '2026-01-01 00:00:00',
      endTime: '2026-12-31 23:59:59',
      createBy: 'admin',
      createTime: '2026-01-05 11:00:00',
      updateTime: '2026-01-05 11:00:00',
      remark: '学校教职工停车代付规则，单笔25元，月度100元',
    },
  ];
};

/** 代付订单表初始数据 */
export const proxyOrderList = () => {
  return [
    {
      orderId: '1',
      proxyOrderNo: 'PROXY-20260106-0001',
      parkOrderId: 'PARK-20260106-0001',
      proxyId: '1',
      subjectId: 'subject-001',
      proxyAmount: 35.5,
      orderStatus: '已代付',
      failReason: '',
      handlerId: 'admin',
      proxyTime: '2026-01-06 10:30:00',
      createTime: '2026-01-06 10:00:00',
      updateTime: '2026-01-06 10:30:00',
      remark: '企业员工代付订单',
    },
    {
      orderId: '2',
      proxyOrderNo: 'PROXY-20260106-0002',
      parkOrderId: 'PARK-20260106-0002',
      proxyId: '2',
      subjectId: 'subject-002',
      proxyAmount: 45.0,
      orderStatus: '已代付',
      failReason: '',
      handlerId: 'admin',
      proxyTime: '2026-01-06 11:15:00',
      createTime: '2026-01-06 11:00:00',
      updateTime: '2026-01-06 11:15:00',
      remark: '政府公务车代付订单',
    },
    {
      orderId: '3',
      proxyOrderNo: 'PROXY-20260106-0003',
      parkOrderId: 'PARK-20260106-0003',
      proxyId: '1',
      subjectId: 'subject-003',
      proxyAmount: 28.5,
      orderStatus: '待代付',
      failReason: '',
      handlerId: '',
      proxyTime: null,
      createTime: '2026-01-06 13:00:00',
      updateTime: '2026-01-06 13:00:00',
      remark: '企业员工代付订单，等待处理',
    },
    {
      orderId: '4',
      proxyOrderNo: 'PROXY-20260106-0004',
      parkOrderId: 'PARK-20260106-0004',
      proxyId: '3',
      subjectId: 'subject-004',
      proxyAmount: 30.0,
      orderStatus: '代付失败',
      failReason: '月度额度不足',
      handlerId: 'admin',
      proxyTime: null,
      createTime: '2026-01-06 14:30:00',
      updateTime: '2026-01-06 14:35:00',
      remark: 'VIP客户代付订单，额度不足',
    },
    {
      orderId: '5',
      proxyOrderNo: 'PROXY-20260106-0005',
      parkOrderId: 'PARK-20260106-0005',
      proxyId: '4',
      subjectId: 'subject-005',
      proxyAmount: 38.0,
      orderStatus: '已代付',
      failReason: '',
      handlerId: 'admin',
      proxyTime: '2026-01-06 15:20:00',
      createTime: '2026-01-06 15:00:00',
      updateTime: '2026-01-06 15:20:00',
      remark: '医院员工代付订单',
    },
  ];
};

/** 代付记录表初始数据 */
export const proxyRecordList = () => {
  return [
    {
      recordId: '1',
      recordNo: 'RECORD-20260106-0001',
      proxyOrderId: '1',
      proxyId: '1',
      subjectId: 'subject-001',
      parkOrderId: 'PARK-20260106-0001',
      parkId: 'park-001',
      plateNo: '闽E·A1234',
      proxyObjectType: '部门',
      proxyObjectId: 'dept-001',
      proxyAmount: 35.5,
      parkTotalAmount: 35.5,
      proxyStatus: '已代付',
      failReason: '',
      proxyTime: '2026-01-06 10:30:00',
      parkEnterTime: '2026-01-06 08:00:00',
      parkExitTime: '2026-01-06 10:00:00',
      createBy: 'admin',
      createTime: '2026-01-06 10:30:00',
      updateTime: '2026-01-06 10:30:00',
      remark: '企业员工停车代付记录',
    },
    {
      recordId: '2',
      recordNo: 'RECORD-20260106-0002',
      proxyOrderId: '2',
      proxyId: '2',
      subjectId: 'subject-002',
      parkOrderId: 'PARK-20260106-0002',
      parkId: 'park-004',
      plateNo: '闽E·B5678',
      proxyObjectType: '车牌',
      proxyObjectId: '闽E·B5678',
      proxyAmount: 45.0,
      parkTotalAmount: 45.0,
      proxyStatus: '已代付',
      failReason: '',
      proxyTime: '2026-01-06 11:15:00',
      parkEnterTime: '2026-01-06 09:30:00',
      parkExitTime: '2026-01-06 11:00:00',
      createBy: 'admin',
      createTime: '2026-01-06 11:15:00',
      updateTime: '2026-01-06 11:15:00',
      remark: '政府公务车停车代付记录',
    },
    {
      recordId: '3',
      recordNo: 'RECORD-20260106-0003',
      proxyOrderId: '3',
      proxyId: '1',
      subjectId: 'subject-003',
      parkOrderId: 'PARK-20260106-0003',
      parkId: 'park-002',
      plateNo: '闽E·C9012',
      proxyObjectType: '部门',
      proxyObjectId: 'dept-002',
      proxyAmount: 28.5,
      parkTotalAmount: 28.5,
      proxyStatus: '待代付',
      failReason: '',
      proxyTime: null,
      parkEnterTime: '2026-01-06 12:00:00',
      parkExitTime: '2026-01-06 13:00:00',
      createBy: 'admin',
      createTime: '2026-01-06 13:00:00',
      updateTime: '2026-01-06 13:00:00',
      remark: '企业员工停车代付记录，等待处理',
    },
    {
      recordId: '4',
      recordNo: 'RECORD-20260106-0004',
      proxyOrderId: '4',
      proxyId: '3',
      subjectId: 'subject-004',
      parkOrderId: 'PARK-20260106-0004',
      parkId: 'park-006',
      plateNo: '闽E·D3456',
      proxyObjectType: '车牌',
      proxyObjectId: '闽E·D3456',
      proxyAmount: 30.0,
      parkTotalAmount: 30.0,
      proxyStatus: '代付失败',
      failReason: '月度额度不足',
      proxyTime: null,
      parkEnterTime: '2026-01-06 13:30:00',
      parkExitTime: '2026-01-06 14:30:00',
      createBy: 'admin',
      createTime: '2026-01-06 14:30:00',
      updateTime: '2026-01-06 14:35:00',
      remark: 'VIP客户停车代付记录，额度不足',
    },
    {
      recordId: '5',
      recordNo: 'RECORD-20260106-0005',
      proxyOrderId: '5',
      proxyId: '4',
      subjectId: 'subject-005',
      parkOrderId: 'PARK-20260106-0005',
      parkId: 'park-007',
      plateNo: '闽E·E7890',
      proxyObjectType: '部门',
      proxyObjectId: 'dept-003',
      proxyAmount: 38.0,
      parkTotalAmount: 38.0,
      proxyStatus: '已代付',
      failReason: '',
      proxyTime: '2026-01-06 15:20:00',
      parkEnterTime: '2026-01-06 14:00:00',
      parkExitTime: '2026-01-06 15:00:00',
      createBy: 'admin',
      createTime: '2026-01-06 15:20:00',
      updateTime: '2026-01-06 15:20:00',
      remark: '医院员工停车代付记录',
    },
  ];
};

/** 停车订单表数据（biz_park_order） */
export const parkOrderList = () => {
  return [
    {
      park_order_id: 'PARK-20260106-0001',
      park_order_no: 'PARK-20260106-0001',
      park_id: 'park-001',
      plate_no: '闽E·A1234',
      enter_time: '2026-01-06 08:00:00',
      exit_time: '2026-01-06 10:00:00',
      park_duration: 120,
      total_amount: 35.5,
      payment_status: '已支付',
      payment_time: '2026-01-06 10:30:00',
      user_id: 'user-001',
      create_time: '2026-01-06 10:00:00',
      update_time: '2026-01-06 10:30:00',
      remark: '企业员工停车订单',
    },
    {
      park_order_id: 'PARK-20260106-0002',
      park_order_no: 'PARK-20260106-0002',
      park_id: 'park-004',
      plate_no: '闽E·B5678',
      enter_time: '2026-01-06 09:30:00',
      exit_time: '2026-01-06 11:00:00',
      park_duration: 90,
      total_amount: 45.0,
      payment_status: '已支付',
      payment_time: '2026-01-06 11:15:00',
      user_id: 'user-002',
      create_time: '2026-01-06 11:00:00',
      update_time: '2026-01-06 11:15:00',
      remark: '政府公务车停车订单',
    },
    {
      park_order_id: 'PARK-20260106-0003',
      park_order_no: 'PARK-20260106-0003',
      park_id: 'park-002',
      plate_no: '闽E·C9012',
      enter_time: '2026-01-06 12:00:00',
      exit_time: '2026-01-06 13:00:00',
      park_duration: 60,
      total_amount: 28.5,
      payment_status: '代付中',
      payment_time: null,
      user_id: 'user-003',
      create_time: '2026-01-06 13:00:00',
      update_time: '2026-01-06 13:00:00',
      remark: '企业员工停车订单，等待代付',
    },
    {
      park_order_id: 'PARK-20260106-0004',
      park_order_no: 'PARK-20260106-0004',
      park_id: 'park-006',
      plate_no: '闽E·D3456',
      enter_time: '2026-01-06 13:30:00',
      exit_time: '2026-01-06 14:30:00',
      park_duration: 60,
      total_amount: 30.0,
      payment_status: '未支付',
      payment_time: null,
      user_id: 'user-004',
      create_time: '2026-01-06 14:30:00',
      update_time: '2026-01-06 14:35:00',
      remark: 'VIP客户停车订单，代付失败',
    },
    {
      park_order_id: 'PARK-20260106-0005',
      park_order_no: 'PARK-20260106-0005',
      park_id: 'park-007',
      plate_no: '闽E·E7890',
      enter_time: '2026-01-06 14:00:00',
      exit_time: '2026-01-06 15:00:00',
      park_duration: 60,
      total_amount: 38.0,
      payment_status: '已支付',
      payment_time: '2026-01-06 15:20:00',
      user_id: 'user-005',
      create_time: '2026-01-06 15:00:00',
      update_time: '2026-01-06 15:20:00',
      remark: '医院员工停车订单',
    },
  ];
};

/** 停车场信息表数据（biz_park_lot_base） */
export const parkLotList = () => {
  return [
    {
      park_id: 'park-001',
      park_name: '企业大厦停车场',
      park_code: 'PARK-001',
      park_address: '福建省厦门市思明区湖滨南路123号',
      park_type: '企业专属',
      operator_id: 'company-001',
      total_space: 500,
      status: '启用',
      create_time: '2025-01-01 00:00:00',
      update_time: '2025-01-01 00:00:00',
      create_by: 'admin',
      remark: '企业大厦专属停车场',
    },
    {
      park_id: 'park-002',
      park_name: '科技园区停车场',
      park_code: 'PARK-002',
      park_address: '福建省厦门市思明区软件园大道456号',
      park_type: '公共',
      operator_id: 'company-001',
      total_space: 1000,
      status: '启用',
      create_time: '2025-02-01 00:00:00',
      update_time: '2025-02-01 00:00:00',
      create_by: 'admin',
      remark: '科技园区公共停车场',
    },
    {
      park_id: 'park-004',
      park_name: '政府办公大楼停车场',
      park_code: 'PARK-004',
      park_address: '福建省厦门市思明区湖滨北路789号',
      park_type: '政府专属',
      operator_id: 'gov-001',
      total_space: 300,
      status: '启用',
      create_time: '2025-03-01 00:00:00',
      update_time: '2025-03-01 00:00:00',
      create_by: 'admin',
      remark: '政府办公大楼专属停车场',
    },
    {
      park_id: 'park-006',
      park_name: '商场地下停车场',
      park_code: 'PARK-006',
      park_address: '福建省厦门市思明区中山路111号',
      park_type: '商业',
      operator_id: 'merchant-001',
      total_space: 800,
      status: '启用',
      create_time: '2025-04-01 00:00:00',
      update_time: '2025-04-01 00:00:00',
      create_by: 'admin',
      remark: '商场地下停车场',
    },
    {
      park_id: 'park-007',
      park_name: '医院停车场',
      park_code: 'PARK-007',
      park_address: '福建省厦门市思明区厦禾路222号',
      park_type: '公共',
      operator_id: 'hospital-001',
      total_space: 600,
      status: '启用',
      create_time: '2025-05-01 00:00:00',
      update_time: '2025-05-01 00:00:00',
      create_by: 'admin',
      remark: '医院公共停车场',
    },
  ];
};

/** 文字描述对象 */
export const textObj = {
  // 代付规则
  proxyRule: {
    editText: '编辑代付规则',
    addText: '新增代付规则',
    excelName: '代付规则列表',
    excelAllName: '代付规则数据.xlsx',
    total: '代付规则数量5;启用4;禁用1',
  },
  // 代付订单
  proxyOrder: {
    editText: '编辑代付订单',
    addText: '新增代付订单',
    excelName: '代付订单列表',
    excelAllName: '代付订单数据.xlsx',
    total: '代付订单数量5;已代付3;待代付1;代付失败1',
  },
  // 代付记录
  proxyRecord: {
    editText: '编辑代付记录',
    addText: '新增代付记录',
    excelName: '代付记录列表',
    excelAllName: '代付记录数据.xlsx',
    total: '代付记录数量5;已代付3;待代付1;代付失败1',
  },
};

/** 代付规则表单配置 */
export function useProxyRuleFormSchema() {
  return [
    {
      fieldName: 'proxyName',
      label: '规则名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入规则名称',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'proxyType',
      label: '代付类型',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: [
          { label: '企业代付', value: '企业代付' },
          { label: '政府代付', value: '政府代付' },
          { label: '指定用户代付', value: '指定用户代付' },
        ],
        placeholder: '请选择代付类型',
      },
      rules: 'required',
    },
    {
      fieldName: 'payerId',
      label: '付款方',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: payerList().map(item => ({
          label: item.merchantName,
          value: item.merchantId
        })),
        placeholder: '请选择付款方',
      },
      rules: 'required',
    },
    {
      fieldName: 'payeeType',
      label: '收款方类型',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: [
          { label: '用户', value: '用户' },
          { label: '商户', value: '商户' },
        ],
        placeholder: '请选择收款方类型',
      },
      rules: 'required',
    },
    {
      fieldName: 'singleAmount',
      label: '单笔代付额度',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入单笔代付额度',
        min: 0,
        step: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'monthlyAmount',
      label: '月度累计额度',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入月度累计额度',
        min: 0,
        step: 10,
      },
      rules: 'required',
    },
    {
      fieldName: 'objectType',
      label: '代付对象类型',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: [
          { label: '车牌', value: '车牌' },
          { label: '部门', value: '部门' },
        ],
        placeholder: '请选择代付对象类型',
      },
      rules: 'required',
    },
    {
      fieldName: 'startTime',
      label: '生效时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        type: 'datetime',
        placeholder: '请选择生效时间',
      },
      rules: 'required',
    },
    {
      fieldName: 'endTime',
      label: '失效时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        type: 'datetime',
        placeholder: '请选择失效时间',
      },
    },
    {
      fieldName: 'status',
      label: '状态',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: [
          { label: '启用', value: '启用' },
          { label: '禁用', value: '禁用' },
        ],
        placeholder: '请选择状态',
      },
      rules: 'required',
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入备注',
        type: 'textarea',
      },
    },
  ];
}

/** 代付订单表单配置 */
export function useProxyOrderFormSchema() {
  return [
    {
      fieldName: 'proxyOrderNo',
      label: '代付订单编号',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入代付订单编号',
      },
      rules: 'required',
    },
    {
      fieldName: 'parkOrderId',
      label: '停车订单',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: parkOrderList().map(item => ({
          label: item.park_order_no,
          value: item.park_order_id
        })),
        placeholder: '请选择停车订单',
      },
      rules: 'required',
    },
    {
      fieldName: 'proxyId',
      label: '代付规则',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: proxyRuleList().map(item => ({
          label: item.proxyName,
          value: item.proxyId
        })),
        placeholder: '请选择代付规则',
      },
      rules: 'required',
    },
    {
      fieldName: 'proxyAmount',
      label: '代付金额',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入代付金额',
        min: 0,
        step: 0.1,
      },
      rules: 'required',
    },
    {
      fieldName: 'orderStatus',
      label: '订单状态',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: [
          { label: '待代付', value: '待代付' },
          { label: '已代付', value: '已代付' },
          { label: '代付失败', value: '代付失败' },
        ],
        placeholder: '请选择订单状态',
      },
      rules: 'required',
    },
    {
      fieldName: 'failReason',
      label: '失败原因',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入失败原因',
      },
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入备注',
        type: 'textarea',
      },
    },
  ];
}

/** 代付记录表单配置 */
export function useProxyRecordFormSchema() {
  return [
    {
      fieldName: 'recordNo',
      label: '代付记录编号',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入代付记录编号',
      },
      rules: 'required',
    },
    {
      fieldName: 'proxyOrderId',
      label: '代付订单',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: proxyOrderList().map(item => ({
          label: item.proxyOrderNo,
          value: item.orderId
        })),
        placeholder: '请选择代付订单',
      },
      rules: 'required',
    },
    {
      fieldName: 'parkOrderId',
      label: '停车订单',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: parkOrderList().map(item => ({
          label: item.park_order_no,
          value: item.park_order_id
        })),
        placeholder: '请选择停车订单',
      },
      rules: 'required',
    },
    {
      fieldName: 'parkId',
      label: '停车场',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: parkLotList().map(item => ({
          label: item.park_name,
          value: item.park_id
        })),
        placeholder: '请选择停车场',
      },
      rules: 'required',
    },
    {
      fieldName: 'plateNo',
      label: '车牌号码',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入车牌号码',
      },
      rules: 'required',
    },
    {
      fieldName: 'proxyAmount',
      label: '代付金额',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入代付金额',
        min: 0,
        step: 0.1,
      },
      rules: 'required',
    },
    {
      fieldName: 'proxyStatus',
      label: '代付状态',
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        options: [
          { label: '待代付', value: '待代付' },
          { label: '已代付', value: '已代付' },
          { label: '代付失败', value: '代付失败' },
        ],
        placeholder: '请选择代付状态',
      },
      rules: 'required',
    },
    {
      fieldName: 'failReason',
      label: '失败原因',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入失败原因',
      },
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入备注',
        type: 'textarea',
      },
    },
  ];
}

/** 代付规则表格列配置 */
export function useProxyRuleGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'proxyId',
      title: '规则ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'proxyName',
      title: '规则名称',
      minWidth: 150,
      sortable: true,
      slots: { default: 'proxyName' },
    },
    {
      field: 'proxyType',
      title: '代付类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'payerId',
      title: '付款方ID',
      minWidth: 120,
      sortable: true,
      visible: false,
    },
    {
      field: 'payerName',
      title: '付款方',
      minWidth: 150,
      sortable: true,
      slots: { default: 'payerName' },
    },
    {
      field: 'payeeType',
      title: '收款方类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'singleAmount',
      title: '单笔额度',
      minWidth: 100,
      sortable: true,
      formatter: (value) => `¥${typeof value === 'number' ? value.toFixed(2) : '0.00'}`,
    },
    {
      field: 'monthlyAmount',
      title: '月度额度',
      minWidth: 100,
      sortable: true,
      formatter: (value) => `¥${typeof value === 'number' ? value.toFixed(2) : '0.00'}`,
    },
    {
      field: 'objectType',
      title: '代付对象类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'startTime',
      title: '生效时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'endTime',
      title: '失效时间',
      minWidth: 180,
      sortable: true,
      // formatter: (value) => value || '永久',
    },
    {
      field: 'status',
      title: '状态',
      minWidth: 80,
      sortable: true,
      slots: { default: 'status' },
    },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 180,
      sortable: true,
    },
    {
      title: '操作',
      width: 100,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 代付订单表格列配置 */
export function useProxyOrderGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'orderId',
      title: '订单ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'proxyOrderNo',
      title: '代付订单号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'proxyOrderNo' },
    },
    {
      field: 'parkOrderId',
      title: '停车订单ID',
      minWidth: 180,
      sortable: true,
      slots: { default: 'parkOrderId' },
    },
    {
      field: 'proxyId',
      title: '代付规则ID',
      minWidth: 120,
      sortable: true,
      visible: false,
    },
    {
      field: 'proxyName',
      title: '代付规则名称',
      minWidth: 150,
      sortable: true,
      slots: { default: 'proxyName' },
    },
    {
      field: 'proxyAmount',
      title: '代付金额',
      minWidth: 100,
      sortable: true,
      formatter: (value) => `¥${typeof value === 'number' ? value.toFixed(2) : '0.00'}`,
    },
    {
      field: 'orderStatus',
      title: '订单状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'orderStatus' },
    },
    {
      field: 'failReason',
      title: '失败原因',
      minWidth: 150,
      sortable: true,
      // formatter: (value) => value || '-',
    },
    {
      field: 'proxyTime',
      title: '代付时间',
      minWidth: 180,
      sortable: true,
      // formatter: (value) => value || '-',
    },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 180,
      sortable: true,
    },
    {
      title: '操作',
      width: 200,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 代付记录表格列配置 */
export function useProxyRecordGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'recordId',
      title: '记录ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'recordNo',
      title: '记录编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'recordNo' },
    },
    {
      field: 'proxyOrderId',
      title: '代付订单ID',
      minWidth: 120,
      sortable: true,
      visible: false,
    },
    {
      field: 'proxyOrderNo',
      title: '代付订单编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'proxyOrderNo' },
    },
    {
      field: 'parkOrderId',
      title: '停车订单ID',
      minWidth: 180,
      sortable: true,
      visible: false,
    },
    {
      field: 'parkOrderNo',
      title: '停车订单',
      minWidth: 180,
      sortable: true,
      slots: { default: 'parkOrderNo' },
    },
    {
      field: 'plateNo',
      title: '车牌号码',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'parkId',
      title: '停车场ID',
      minWidth: 120,
      sortable: true,
      visible: false,
    },
    {
      field: 'parkName',
      title: '停车场',
      minWidth: 150,
      sortable: true,
      slots: { default: 'parkName' },
    },
    {
      field: 'proxyAmount',
      title: '代付金额',
      minWidth: 100,
      sortable: true,
      formatter: (value) => `¥${typeof value === 'number' ? value.toFixed(2) : '0.00'}`,
    },
    {
      field: 'parkTotalAmount',
      title: '停车总费用',
      minWidth: 100,
      sortable: true,
      formatter: (value) => `¥${typeof value === 'number' ? value.toFixed(2) : '0.00'}`,
    },
    {
      field: 'proxyStatus',
      title: '代付状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'proxyStatus' },
    },
    {
      field: 'parkEnterTime',
      title: '入场时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'parkExitTime',
      title: '离场时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'proxyTime',
      title: '代付时间',
      minWidth: 180,
      sortable: true,
      // formatter: (value) => value || '-',
    },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 180,
      sortable: true,
    },
    {
      title: '操作',
      width: 200,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
