/** 半年清运与违规处置统计分析数据 */
export const dataList = () => [
  {
    areaName: '鼓楼区',
    halfYearTotalClearanceVolume: 2850,
    halfYearTotalViolationDisposalCount: 342,
    halfYearCrossRegionClearanceCases: 28,
    halfYearClearanceEnterpriseRewardPunishmentCount: 12,
    halfYearCardPointEquipmentAvailabilityRate: 98.5,
    yoyTotalClearanceVolume: 8.2,
    yoyViolationDisposalCount: -3.1,
    yoyCrossRegionClearanceCases: 15.6,
    yoyClearanceEnterpriseRewardPunishmentCount: 4.5,
    yoyCardPointEquipmentAvailabilityRate: 1.2,
    detailByRegion: '鼓楼区: 2850吨；台江区: 2150吨；仓山区: 2420吨',
    detailByClearanceEnterprise: '企业A: 1250吨；企业B: 980吨；企业C: 620吨',
    detailByCrossRegionRoute: '线路1: 12件；线路2: 8件；线路3: 5件',
    detailByEquipmentStatus: '完好: 156个；故障: 4个；维修中: 2个',
    yoyDetailByRegion: '鼓楼区同比: +8.2%；台江区同比: +5.1%；仓山区同比: +3.5%',
    yoyDetailByClearanceEnterprise: '企业A同比: +10.2%；企业B同比: +2.5%；企业C同比: +1.8%',
    yoyDetailByCrossRegionRoute: '线路1同比: +20.1%；线路2同比: +5.0%；线路3同比: +8.5%',
    yoyDetailByEquipmentStatus: '完好同比: +0.5%；故障同比: -12.0%；维修中同比: -8.0%',
  },
  {
    areaName: '台江区',
    halfYearTotalClearanceVolume: 2150,
    halfYearTotalViolationDisposalCount: 278,
    halfYearCrossRegionClearanceCases: 22,
    halfYearClearanceEnterpriseRewardPunishmentCount: 8,
    halfYearCardPointEquipmentAvailabilityRate: 97.2,
    yoyTotalClearanceVolume: 5.1,
    yoyViolationDisposalCount: -1.5,
    yoyCrossRegionClearanceCases: 10.3,
    yoyClearanceEnterpriseRewardPunishmentCount: 2.1,
    yoyCardPointEquipmentAvailabilityRate: 0.8,
    detailByRegion: '台江区: 2150吨；鼓楼区: 2850吨；仓山区: 2420吨',
    detailByClearanceEnterprise: '企业A: 950吨；企业B: 720吨；企业C: 480吨',
    detailByCrossRegionRoute: '线路1: 9件；线路2: 6件；线路3: 4件',
    detailByEquipmentStatus: '完好: 118个；故障: 5个；维修中: 3个',
    yoyDetailByRegion: '台江区同比: +5.1%；鼓楼区同比: +8.2%；仓山区同比: +3.5%',
    yoyDetailByClearanceEnterprise: '企业A同比: +4.5%；企业B同比: +1.8%；企业C同比: +0.5%',
    yoyDetailByCrossRegionRoute: '线路1同比: +12.2%；线路2同比: +3.0%；线路3同比: +4.2%',
    yoyDetailByEquipmentStatus: '完好同比: +0.3%；故障同比: -8.0%；维修中同比: -5.0%',
  },
  {
    areaName: '仓山区',
    halfYearTotalClearanceVolume: 2420,
    halfYearTotalViolationDisposalCount: 305,
    halfYearCrossRegionClearanceCases: 25,
    halfYearClearanceEnterpriseRewardPunishmentCount: 10,
    halfYearCardPointEquipmentAvailabilityRate: 96.8,
    yoyTotalClearanceVolume: 3.5,
    yoyViolationDisposalCount: 2.2,
    yoyCrossRegionClearanceCases: 7.8,
    yoyClearanceEnterpriseRewardPunishmentCount: 5.6,
    yoyCardPointEquipmentAvailabilityRate: -0.2,
    detailByRegion: '仓山区: 2420吨；晋安区: 1680吨；马尾区: 980吨',
    detailByClearanceEnterprise: '企业A: 1100吨；企业B: 850吨；企业C: 470吨',
    detailByCrossRegionRoute: '线路1: 10件；线路2: 7件；线路3: 5件',
    detailByEquipmentStatus: '完好: 142个；故障: 6个；维修中: 4个',
    yoyDetailByRegion: '仓山区同比: +3.5%；晋安区同比: +4.1%；马尾区同比: +6.5%',
    yoyDetailByClearanceEnterprise: '企业A同比: +6.5%；企业B同比: +3.2%；企业C同比: -1.0%',
    yoyDetailByCrossRegionRoute: '线路1同比: +5.2%；线路2同比: +8.1%；线路3同比: +3.5%',
    yoyDetailByEquipmentStatus: '完好同比: -0.2%；故障同比: +5.0%；维修中同比: +2.0%',
  },
  {
    areaName: '晋安区',
    halfYearTotalClearanceVolume: 1680,
    halfYearTotalViolationDisposalCount: 225,
    halfYearCrossRegionClearanceCases: 18,
    halfYearClearanceEnterpriseRewardPunishmentCount: 6,
    halfYearCardPointEquipmentAvailabilityRate: 99.1,
    yoyTotalClearanceVolume: 4.1,
    yoyViolationDisposalCount: -2.5,
    yoyCrossRegionClearanceCases: 12.4,
    yoyClearanceEnterpriseRewardPunishmentCount: 1.2,
    yoyCardPointEquipmentAvailabilityRate: 0.5,
    detailByRegion: '晋安区: 1680吨；仓山区: 2420吨；台江区: 2150吨',
    detailByClearanceEnterprise: '企业A: 720吨；企业B: 550吨；企业C: 410吨',
    detailByCrossRegionRoute: '线路1: 7件；线路2: 5件；线路3: 3件',
    detailByEquipmentStatus: '完好: 89个；故障: 2个；维修中: 1个',
    yoyDetailByRegion: '晋安区同比: +4.1%；仓山区同比: +3.5%；台江区同比: +5.1%',
    yoyDetailByClearanceEnterprise: '企业A同比: +3.2%；企业B同比: +2.1%；企业C同比: -0.5%',
    yoyDetailByCrossRegionRoute: '线路1同比: +9.5%；线路2同比: +6.2%；线路3同比: +4.0%',
    yoyDetailByEquipmentStatus: '完好同比: +0.2%；故障同比: -5.0%；维修中同比: -3.0%',
  },
  {
    areaName: '马尾区',
    halfYearTotalClearanceVolume: 980,
    halfYearTotalViolationDisposalCount: 156,
    halfYearCrossRegionClearanceCases: 12,
    halfYearClearanceEnterpriseRewardPunishmentCount: 4,
    halfYearCardPointEquipmentAvailabilityRate: 95.5,
    yoyTotalClearanceVolume: 6.5,
    yoyViolationDisposalCount: 1.8,
    yoyCrossRegionClearanceCases: 18.2,
    yoyClearanceEnterpriseRewardPunishmentCount: 3.4,
    yoyCardPointEquipmentAvailabilityRate: -0.9,
    detailByRegion: '马尾区: 980吨；长乐区: 720吨；福清市: 650吨',
    detailByClearanceEnterprise: '企业A: 430吨；企业B: 320吨；企业C: 230吨',
    detailByCrossRegionRoute: '线路1: 5件；线路2: 4件；线路3: 2件',
    detailByEquipmentStatus: '完好: 56个；故障: 3个；维修中: 2个',
    yoyDetailByRegion: '马尾区同比: +6.5%；长乐区同比: +3.2%；福清市同比: +1.5%',
    yoyDetailByClearanceEnterprise: '企业A同比: +8.0%；企业B同比: +2.5%；企业C同比: -1.2%',
    yoyDetailByCrossRegionRoute: '线路1同比: +15.0%；线路2同比: +8.5%；线路3同比: +5.0%',
    yoyDetailByEquipmentStatus: '完好同比: -1.5%；故障同比: +10.0%；维修中同比: +5.0%',
  },
  {
    areaName: '长乐区',
    halfYearTotalClearanceVolume: 720,
    halfYearTotalViolationDisposalCount: 118,
    halfYearCrossRegionClearanceCases: 9,
    halfYearClearanceEnterpriseRewardPunishmentCount: 3,
    halfYearCardPointEquipmentAvailabilityRate: 97.8,
    yoyTotalClearanceVolume: 3.2,
    yoyViolationDisposalCount: -0.5,
    yoyCrossRegionClearanceCases: 5.6,
    yoyClearanceEnterpriseRewardPunishmentCount: 1.1,
    yoyCardPointEquipmentAvailabilityRate: 0.3,
    detailByRegion: '长乐区: 720吨；马尾区: 980吨；连江县: 520吨',
    detailByClearanceEnterprise: '企业A: 310吨；企业B: 240吨；企业C: 170吨',
    detailByCrossRegionRoute: '线路1: 4件；线路2: 3件；线路3: 2件',
    detailByEquipmentStatus: '完好: 68个；故障: 2个；维修中: 1个',
    yoyDetailByRegion: '长乐区同比: +3.2%；马尾区同比: +6.5%；连江县同比: +4.5%',
    yoyDetailByClearanceEnterprise: '企业A同比: +2.5%；企业B同比: +1.2%；企业C同比: +0.5%',
    yoyDetailByCrossRegionRoute: '线路1同比: +4.0%；线路2同比: +3.5%；线路3同比: +2.0%',
    yoyDetailByEquipmentStatus: '完好同比: +0.1%；故障同比: -3.0%；维修中同比: -1.5%',
  },
  {
    areaName: '福清市',
    halfYearTotalClearanceVolume: 650,
    halfYearTotalViolationDisposalCount: 98,
    halfYearCrossRegionClearanceCases: 7,
    halfYearClearanceEnterpriseRewardPunishmentCount: 2,
    halfYearCardPointEquipmentAvailabilityRate: 96.2,
    yoyTotalClearanceVolume: 1.5,
    yoyViolationDisposalCount: -4.2,
    yoyCrossRegionClearanceCases: 3.1,
    yoyClearanceEnterpriseRewardPunishmentCount: -2.5,
    yoyCardPointEquipmentAvailabilityRate: -0.6,
    detailByRegion: '福清市: 650吨；长乐区: 720吨；闽侯县: 480吨',
    detailByClearanceEnterprise: '企业A: 280吨；企业B: 210吨；企业C: 160吨',
    detailByCrossRegionRoute: '线路1: 3件；线路2: 2件；线路3: 1件',
    detailByEquipmentStatus: '完好: 42个；故障: 2个；维修中: 1个',
    yoyDetailByRegion: '福清市同比: +1.5%；长乐区同比: +3.2%；闽侯县同比: +2.8%',
    yoyDetailByClearanceEnterprise: '企业A同比: +1.0%；企业B同比: -0.5%；企业C同比: -2.0%',
    yoyDetailByCrossRegionRoute: '线路1同比: +2.0%；线路2同比: +1.5%；线路3同比: 0%',
    yoyDetailByEquipmentStatus: '完好同比: -0.8%；故障同比: +5.0%；维修中同比: +2.0%',
  },
  {
    areaName: '连江县',
    halfYearTotalClearanceVolume: 520,
    halfYearTotalViolationDisposalCount: 85,
    halfYearCrossRegionClearanceCases: 5,
    halfYearClearanceEnterpriseRewardPunishmentCount: 2,
    halfYearCardPointEquipmentAvailabilityRate: 98.0,
    yoyTotalClearanceVolume: 4.5,
    yoyViolationDisposalCount: 2.3,
    yoyCrossRegionClearanceCases: 9.6,
    yoyClearanceEnterpriseRewardPunishmentCount: 3.2,
    yoyCardPointEquipmentAvailabilityRate: 0.4,
    detailByRegion: '连江县: 520吨；福清市: 650吨；罗源县: 380吨',
    detailByClearanceEnterprise: '企业A: 230吨；企业B: 170吨；企业C: 120吨',
    detailByCrossRegionRoute: '线路1: 2件；线路2: 1件；线路3: 1件',
    detailByEquipmentStatus: '完好: 35个；故障: 1个；维修中: 1个',
    yoyDetailByRegion: '连江县同比: +4.5%；福清市同比: +1.5%；罗源县同比: +5.2%',
    yoyDetailByClearanceEnterprise: '企业A同比: +3.0%；企业B同比: +1.5%；企业C同比: +0.8%',
    yoyDetailByCrossRegionRoute: '线路1同比: +8.0%；线路2同比: +5.0%；线路3同比: +3.0%',
    yoyDetailByEquipmentStatus: '完好同比: +0.2%；故障同比: -2.0%；维修中同比: 0%',
  },
  {
    areaName: '闽侯县',
    halfYearTotalClearanceVolume: 480,
    halfYearTotalViolationDisposalCount: 72,
    halfYearCrossRegionClearanceCases: 4,
    halfYearClearanceEnterpriseRewardPunishmentCount: 1,
    halfYearCardPointEquipmentAvailabilityRate: 94.8,
    yoyTotalClearanceVolume: 2.8,
    yoyViolationDisposalCount: -1.1,
    yoyCrossRegionClearanceCases: 4.2,
    yoyClearanceEnterpriseRewardPunishmentCount: 0.5,
    yoyCardPointEquipmentAvailabilityRate: -1.2,
    detailByRegion: '闽侯县: 480吨；连江县: 520吨；永泰县: 310吨',
    detailByClearanceEnterprise: '企业A: 200吨；企业B: 150吨；企业C: 130吨',
    detailByCrossRegionRoute: '线路1: 2件；线路2: 1件；线路3: 1件',
    detailByEquipmentStatus: '完好: 28个；故障: 2个；维修中: 1个',
    yoyDetailByRegion: '闽侯县同比: +2.8%；连江县同比: +4.5%；永泰县同比: +3.1%',
    yoyDetailByClearanceEnterprise: '企业A同比: +1.5%；企业B同比: +0.2%；企业C同比: -0.5%',
    yoyDetailByCrossRegionRoute: '线路1同比: +3.0%；线路2同比: +2.0%；线路3同比: +1.0%',
    yoyDetailByEquipmentStatus: '完好同比: -1.5%；故障同比: +8.0%；维修中同比: +3.0%',
  },
  {
    areaName: '罗源县',
    halfYearTotalClearanceVolume: 380,
    halfYearTotalViolationDisposalCount: 58,
    halfYearCrossRegionClearanceCases: 3,
    halfYearClearanceEnterpriseRewardPunishmentCount: 1,
    halfYearCardPointEquipmentAvailabilityRate: 96.5,
    yoyTotalClearanceVolume: 5.2,
    yoyViolationDisposalCount: 3.4,
    yoyCrossRegionClearanceCases: 12.5,
    yoyClearanceEnterpriseRewardPunishmentCount: 2.2,
    yoyCardPointEquipmentAvailabilityRate: 0.1,
    detailByRegion: '罗源县: 380吨；闽侯县: 480吨；永泰县: 310吨',
    detailByClearanceEnterprise: '企业A: 160吨；企业B: 120吨；企业C: 100吨',
    detailByCrossRegionRoute: '线路1: 1件；线路2: 1件；线路3: 1件',
    detailByEquipmentStatus: '完好: 22个；故障: 1个；维修中: 0个',
    yoyDetailByRegion: '罗源县同比: +5.2%；闽侯县同比: +2.8%；永泰县同比: +3.1%',
    yoyDetailByClearanceEnterprise: '企业A同比: +4.0%；企业B同比: +2.5%；企业C同比: +1.0%',
    yoyDetailByCrossRegionRoute: '线路1同比: +10.0%；线路2同比: +8.0%；线路3同比: +5.0%',
    yoyDetailByEquipmentStatus: '完好同比: +0.1%；故障同比: -3.0%；维修中同比: 0%',
  },
];

/** 半年清运与违规处置统计分析表单（新增/修改/搜索） */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '160',
      rules: 'required',
    },
    {
      fieldName: 'halfYearTotalClearanceVolume',
      label: '半年清运总量',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入半年清运总量（单位：吨）',
        min: 0,
        precision: 0,
        addonAfter: '吨',
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearTotalViolationDisposalCount',
      label: '半年违规处置总量',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入半年违规处置总量（单位：件）',
        min: 0,
        precision: 0,
        addonAfter: '件',
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearCrossRegionClearanceCases',
      label: '半年跨区域清运案件数',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入半年跨区域清运案件数（单位：件）',
        min: 0,
        precision: 0,
        addonAfter: '件',
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearClearanceEnterpriseRewardPunishmentCount',
      label: '半年清运企业奖惩数量',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入半年清运企业奖惩数量（单位：家次）',
        min: 0,
        precision: 0,
        addonAfter: '家次',
      },
      rules: 'required',
    },
    {
      fieldName: 'halfYearCardPointEquipmentAvailabilityRate',
      label: '半年卡点设备完好率',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入半年卡点设备完好率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyTotalClearanceVolume',
      label: '清运总量同比(%)',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入清运总量同比（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyViolationDisposalCount',
      label: '违规处置总量同比(%)',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入违规处置总量同比（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyCrossRegionClearanceCases',
      label: '跨区域清运案件数同比(%)',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入跨区域清运案件数同比（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyClearanceEnterpriseRewardPunishmentCount',
      label: '清运企业奖惩数量同比(%)',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入清运企业奖惩数量同比（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyCardPointEquipmentAvailabilityRate',
      label: '卡点设备完好率同比(%)',
      component: 'InputNumber',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入卡点设备完好率同比（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByRegion',
      label: '按区域拆分明细',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入按区域拆分的明细数据（格式：区域: 数值；...）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByClearanceEnterprise',
      label: '按清运企业拆分明细',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入按清运企业拆分的明细数据（格式：企业名: 数值；...）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByCrossRegionRoute',
      label: '按跨区域线路拆分明细',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入按跨区域线路拆分的明细数据（格式：线路名: 数值；...）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'detailByEquipmentStatus',
      label: '按设备状态拆分明细',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入按设备状态拆分的明细数据（格式：状态: 数量；...）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyDetailByRegion',
      label: '按区域拆分同比分析',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入按区域拆分的同比分析（格式：区域同比: +X%；...）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyDetailByClearanceEnterprise',
      label: '按清运企业拆分同比分析',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入按清运企业拆分的同比分析（格式：企业同比: +X%；...）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyDetailByCrossRegionRoute',
      label: '按跨区域线路拆分同比分析',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入按跨区域线路拆分的同比分析（格式：线路同比: +X%；...）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'yoyDetailByEquipmentStatus',
      label: '按设备状态拆分同比分析',
      component: 'Input',
      labelWidth: '160',
      componentProps: {
        placeholder: '请输入按设备状态拆分的同比分析（格式：状态同比: +X%；...）',
        maxlength: 300,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
  ];
}

/** 半年清运与违规处置统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'halfYearTotalClearanceVolume',
      title: '半年清运总量(吨)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'halfYearTotalViolationDisposalCount',
      title: '半年违规处置总量(件)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'halfYearCrossRegionClearanceCases',
      title: '半年跨区域清运案件数(件)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'halfYearClearanceEnterpriseRewardPunishmentCount',
      title: '半年清运企业奖惩数量(家次)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'halfYearCardPointEquipmentAvailabilityRate',
      title: '半年卡点设备完好率(%)',
      minWidth: 170,
      sortable: true,
    },
    {
      field: 'yoyTotalClearanceVolume',
      title: '清运总量同比(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'yoyViolationDisposalCount',
      title: '违规处置总量同比(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'yoyCrossRegionClearanceCases',
      title: '跨区域清运案件数同比(%)',
      minWidth: 170,
      sortable: true,
    },
    {
      field: 'yoyClearanceEnterpriseRewardPunishmentCount',
      title: '清运企业奖惩数量同比(%)',
      minWidth: 170,
      sortable: true,
    },
    {
      field: 'yoyCardPointEquipmentAvailabilityRate',
      title: '卡点设备完好率同比(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'detailByRegion',
      title: '按区域拆分明细',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByClearanceEnterprise',
      title: '按清运企业拆分明细',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByCrossRegionRoute',
      title: '按跨区域线路拆分明细',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'detailByEquipmentStatus',
      title: '按设备状态拆分明细',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'yoyDetailByRegion',
      title: '区域拆分同比分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'yoyDetailByClearanceEnterprise',
      title: '企业拆分同比分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'yoyDetailByCrossRegionRoute',
      title: '线路拆分同比分析',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'yoyDetailByEquipmentStatus',
      title: '设备状态拆分同比分析',
      minWidth: 200,
      sortable: false,
    },
  ];
}
