// data.js
/** 收费异常报表 - 初始数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "abnormalId": "ABNORMAL-20260205001",
      "orderNo": "ORDER-20260205001",
      "carNumber": "粤A12345",
      "areaCode": "440106",
      "areaName": "天河区",
      "lotName": "天河城停车场",
      "abnormalTime": "2026-02-05 08:30",
      "abnormalType": "重复收费",
      "abnormalReason": "系统重复生成两条相同订单",
      "disposalStatus": "待处理",
      "disposalResult": "",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 2,
      "abnormalId": "ABNORMAL-20260205002",
      "orderNo": "ORDER-20260205002",
      "carNumber": "粤B67890",
      "areaCode": "440104",
      "areaName": "越秀区",
      "lotName": "北京路路侧停车",
      "abnormalTime": "2026-02-05 10:15",
      "abnormalType": "少收费",
      "abnormalReason": "系统计费规则错误，少计1小时",
      "disposalStatus": "处理中",
      "disposalResult": "已提交财务审核",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 3,
      "abnormalId": "ABNORMAL-20260205003",
      "orderNo": "ORDER-20260205003",
      "carNumber": "粤C34567",
      "areaCode": "440105",
      "areaName": "海珠区",
      "lotName": "万达广场停车场",
      "abnormalTime": "2026-02-05 14:45",
      "abnormalType": "多收费",
      "abnormalReason": "设备故障导致停车时长计算错误",
      "disposalStatus": "已处理",
      "disposalResult": "已退款，金额¥25.00",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 4,
      "abnormalId": "ABNORMAL-20260204001",
      "orderNo": "ORDER-20260204001",
      "carNumber": "粤D78901",
      "areaCode": "440111",
      "areaName": "白云区",
      "lotName": "白云小区停车场",
      "abnormalTime": "2026-02-04 09:20",
      "abnormalType": "未收费",
      "abnormalReason": "道闸故障，车辆免费出场",
      "disposalStatus": "待处理",
      "disposalResult": "",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 5,
      "abnormalId": "ABNORMAL-20260204002",
      "orderNo": "ORDER-20260204002",
      "carNumber": "粤E23456",
      "areaCode": "440112",
      "areaName": "黄埔区",
      "lotName": "黄埔商业中心停车场",
      "abnormalTime": "2026-02-04 13:10",
      "abnormalType": "重复收费",
      "abnormalReason": "用户重复支付",
      "disposalStatus": "处理中",
      "disposalResult": "正在联系用户退款",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 6,
      "abnormalId": "ABNORMAL-20260203001",
      "orderNo": "ORDER-20260203001",
      "carNumber": "粤F56789",
      "areaCode": "440106",
      "areaName": "天河区",
      "lotName": "体育中心停车场",
      "abnormalTime": "2026-02-03 11:30",
      "abnormalType": "少收费",
      "abnormalReason": "优惠券叠加使用导致收费错误",
      "disposalStatus": "已处理",
      "disposalResult": "已补收差额¥15.50",
      "updateTime": "2026-02-03 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 7,
      "abnormalId": "ABNORMAL-20260202001",
      "orderNo": "ORDER-20260202001",
      "carNumber": "粤G01234",
      "areaCode": "440103",
      "areaName": "荔湾区",
      "lotName": "上下九路侧停车",
      "abnormalTime": "2026-02-02 15:45",
      "abnormalType": "多收费",
      "abnormalReason": "时段计费规则配置错误",
      "disposalStatus": "处理中",
      "disposalResult": "已暂停该时段计费规则",
      "updateTime": "2026-02-02 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 8,
      "abnormalId": "ABNORMAL-20260201001",
      "orderNo": "ORDER-20260201001",
      "carNumber": "粤H56789",
      "areaCode": "440113",
      "areaName": "番禺区",
      "lotName": "长隆景区停车场",
      "abnormalTime": "2026-02-01 18:20",
      "abnormalType": "未收费",
      "abnormalReason": "网络故障导致支付失败",
      "disposalStatus": "待处理",
      "disposalResult": "",
      "updateTime": "2026-02-01 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 9,
      "abnormalId": "ABNORMAL-20260131001",
      "orderNo": "ORDER-20260131001",
      "carNumber": "粤J12345",
      "areaCode": "440106",
      "areaName": "天河区",
      "lotName": "天河城停车场",
      "abnormalTime": "2026-01-31 10:30",
      "abnormalType": "重复收费",
      "abnormalReason": "POS机重复刷卡",
      "disposalStatus": "已处理",
      "disposalResult": "已退款一笔，金额¥30.00",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 10,
      "abnormalId": "ABNORMAL-20260130001",
      "orderNo": "ORDER-20260130001",
      "carNumber": "粤K67890",
      "areaCode": "440105",
      "areaName": "海珠区",
      "lotName": "万达广场停车场",
      "abnormalTime": "2026-01-30 14:20",
      "abnormalType": "少收费",
      "abnormalReason": "车型识别错误，小型车按微型车计费",
      "disposalStatus": "处理中",
      "disposalResult": "已修正车型识别规则",
      "updateTime": "2026-01-30 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 11,
      "abnormalId": "ABNORMAL-20260129001",
      "orderNo": "ORDER-20260129001",
      "carNumber": "粤L34567",
      "areaCode": "440104",
      "areaName": "越秀区",
      "lotName": "北京路路侧停车",
      "abnormalTime": "2026-01-29 19:30",
      "abnormalType": "多收费",
      "abnormalReason": "节假日费率未正常切换",
      "disposalStatus": "待处理",
      "disposalResult": "",
      "updateTime": "2026-01-29 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 12,
      "abnormalId": "ABNORMAL-20260128001",
      "orderNo": "ORDER-20260128001",
      "carNumber": "粤M78901",
      "areaCode": "440111",
      "areaName": "白云区",
      "lotName": "白云小区停车场",
      "abnormalTime": "2026-01-28 09:15",
      "abnormalType": "未收费",
      "abnormalReason": "系统维护期间产生的订单",
      "disposalStatus": "已处理",
      "disposalResult": "已手动补录收费¥20.00",
      "updateTime": "2026-01-28 18:30",
      "operator": "系统自动生成"
    }
  ];
};

/** 搜索表单配置 */
export function useFormSchema() {
  return [
    {
      fieldName: 'orderNo',
      label: '订单编号',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入订单编号（支持模糊查询）',
        clearable: true,
      },
    },
    {
      fieldName: 'carNumber',
      label: '车牌号码',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入车牌号码（支持模糊查询）',
        clearable: true,
      },
    },
    {
      fieldName: 'timeRange',
      label: '时间范围',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'daterange',
        'range-separator': '至',
        'start-placeholder': '开始日期',
        'end-placeholder': '结束日期',
        format: 'YYYY-MM-DD',
        'value-format': 'YYYY-MM-DD',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
      },
      fieldName: 'areaName',
      label: '行政区域',
    },
    {
      fieldName: 'abnormalType',
      label: '异常类型',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        options: [
          { label: '重复收费', value: '重复收费' },
          { label: '少收费', value: '少收费' },
          { label: '多收费', value: '多收费' },
          { label: '未收费', value: '未收费' },
          { label: '支付失败', value: '支付失败' },
          { label: '金额错误', value: '金额错误' },
        ],
        placeholder: '请选择异常类型',
      },
    },
    {
      fieldName: 'disposalStatus',
      label: '处置状态',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        options: [
          { label: '待处理', value: '待处理' },
          { label: '处理中', value: '处理中' },
          { label: '已处理', value: '已处理' },
        ],
        placeholder: '请选择处置状态',
      },
    },
  ];
}

/** 表格字段配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'abnormalId',
      title: '异常ID',
      minWidth: 150,
      sortable: true,
      slots: { default: 'abnormalId' },
    },
    {
      field: 'orderNo',
      title: '订单编号',
      minWidth: 150,
      sortable: true,
      slots: { default: 'orderNo' },
    },
    {
      field: 'carNumber',
      title: '车牌号码',
      minWidth: 120,
      sortable: true,
      slots: { default: 'carNumber' },
    },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 100,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'lotName',
      title: '车场名称',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'abnormalTime',
      title: '异常时间',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'abnormalType',
      title: '异常类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'abnormalType' },
    },
    {
      field: 'disposalStatus',
      title: '处置状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'disposalStatus' },
    },
    {
      field: 'disposalResult',
      title: '处理结果',
      minWidth: 180,
      sortable: true,
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑异常记录',
  addText: '新增异常记录',
  excelName: '收费异常报表',
  excelAllName: '收费异常报表.xlsx',
  total: '报表总数: 12; 今日异常: 3; 本周异常: 8;',
};
