// data.js
/** 运维人员绩效考核报表 - 初始数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "statCycle": "月",
      "period": "2026年2月",
      "maintainer": "张三",
      "areaName": "天河区",
      "indicatorName": "综合绩效",
      "workorderTimelyRate": "94.8%",
      "inspectionCompletionRate": "96.2%",
      "faultRepairRate": "93.5%",
      "avgDisposalTime": "3.8小时",
      "performanceScore": 92.5,
      "rank": 1,
      "timelyScore": 94,
      "qualityScore": 91,
      "efficiencyScore": 90,
      "attitudeScore": 95,
      "deductionReason": "",
      "improvementSuggestion": "",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 2,
      "statCycle": "月",
      "period": "2026年2月",
      "maintainer": "李四",
      "areaName": "越秀区",
      "indicatorName": "综合绩效",
      "workorderTimelyRate": "96.3%",
      "inspectionCompletionRate": "98.1%",
      "faultRepairRate": "95.2%",
      "avgDisposalTime": "2.9小时",
      "performanceScore": 95.2,
      "rank": 2,
      "timelyScore": 96,
      "qualityScore": 94,
      "efficiencyScore": 95,
      "attitudeScore": 96,
      "deductionReason": "一次工单超时",
      "improvementSuggestion": "加强时间管理",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 3,
      "statCycle": "月",
      "period": "2026年2月",
      "maintainer": "王五",
      "areaName": "海珠区",
      "indicatorName": "综合绩效",
      "workorderTimelyRate": "92.1%",
      "inspectionCompletionRate": "94.5%",
      "faultRepairRate": "91.8%",
      "avgDisposalTime": "4.2小时",
      "performanceScore": 88.7,
      "rank": 3,
      "timelyScore": 89,
      "qualityScore": 87,
      "efficiencyScore": 88,
      "attitudeScore": 91,
      "deductionReason": "两次工单返工",
      "improvementSuggestion": "提升维修质量",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 4,
      "statCycle": "月",
      "period": "2026年2月",
      "maintainer": "赵六",
      "areaName": "白云区",
      "indicatorName": "综合绩效",
      "workorderTimelyRate": "89.5%",
      "inspectionCompletionRate": "92.8%",
      "faultRepairRate": "88.3%",
      "avgDisposalTime": "5.6小时",
      "performanceScore": 85.4,
      "rank": 4,
      "timelyScore": 86,
      "qualityScore": 84,
      "efficiencyScore": 83,
      "attitudeScore": 89,
      "deductionReason": "响应时间较长",
      "improvementSuggestion": "提升响应速度",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 5,
      "statCycle": "月",
      "period": "2026年2月",
      "maintainer": "钱七",
      "areaName": "黄埔区",
      "indicatorName": "综合绩效",
      "workorderTimelyRate": "98.2%",
      "inspectionCompletionRate": "99.1%",
      "faultRepairRate": "97.8%",
      "avgDisposalTime": "2.5小时",
      "performanceScore": 97.3,
      "rank": 5,
      "timelyScore": 98,
      "qualityScore": 96,
      "efficiencyScore": 97,
      "attitudeScore": 98,
      "deductionReason": "",
      "improvementSuggestion": "继续保持优秀表现",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 6,
      "statCycle": "周",
      "period": "第5周(1.29-2.4)",
      "maintainer": "张三",
      "areaName": "天河区",
      "indicatorName": "响应速度",
      "workorderTimelyRate": "92.3%",
      "inspectionCompletionRate": "95.6%",
      "faultRepairRate": "90.8%",
      "avgDisposalTime": "4.1小时",
      "performanceScore": 89.2,
      "rank": 3,
      "timelyScore": 90,
      "qualityScore": 87,
      "efficiencyScore": 88,
      "attitudeScore": 92,
      "deductionReason": "周一下午响应较慢",
      "improvementSuggestion": "优化排班安排",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 7,
      "statCycle": "周",
      "period": "第5周(1.29-2.4)",
      "maintainer": "李四",
      "areaName": "越秀区",
      "indicatorName": "维修质量",
      "workorderTimelyRate": "95.8%",
      "inspectionCompletionRate": "97.2%",
      "faultRepairRate": "94.5%",
      "avgDisposalTime": "3.1小时",
      "performanceScore": 93.5,
      "rank": 2,
      "timelyScore": 94,
      "qualityScore": 93,
      "efficiencyScore": 92,
      "attitudeScore": 95,
      "deductionReason": "",
      "improvementSuggestion": "",
      "updateTime": "2026-02-04 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 8,
      "statCycle": "日",
      "period": "2026-02-05",
      "maintainer": "王五",
      "areaName": "海珠区",
      "indicatorName": "服务态度",
      "workorderTimelyRate": "100%",
      "inspectionCompletionRate": "100%",
      "faultRepairRate": "100%",
      "avgDisposalTime": "3.8小时",
      "performanceScore": 96.8,
      "rank": 1,
      "timelyScore": 98,
      "qualityScore": 95,
      "efficiencyScore": 96,
      "attitudeScore": 98,
      "deductionReason": "",
      "improvementSuggestion": "",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 9,
      "statCycle": "月",
      "period": "2026年1月",
      "maintainer": "张三",
      "areaName": "天河区",
      "indicatorName": "综合绩效",
      "workorderTimelyRate": "91.5%",
      "inspectionCompletionRate": "93.8%",
      "faultRepairRate": "90.2%",
      "avgDisposalTime": "4.5小时",
      "performanceScore": 87.8,
      "rank": 4,
      "timelyScore": 88,
      "qualityScore": 86,
      "efficiencyScore": 85,
      "attitudeScore": 92,
      "deductionReason": "三次工单超时",
      "improvementSuggestion": "加强时间规划",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 10,
      "statCycle": "月",
      "period": "2026年1月",
      "maintainer": "李四",
      "areaName": "越秀区",
      "indicatorName": "综合绩效",
      "workorderTimelyRate": "94.2%",
      "inspectionCompletionRate": "96.5%",
      "faultRepairRate": "93.8%",
      "avgDisposalTime": "3.3小时",
      "performanceScore": 92.8,
      "rank": 2,
      "timelyScore": 93,
      "qualityScore": 92,
      "efficiencyScore": 91,
      "attitudeScore": 95,
      "deductionReason": "",
      "improvementSuggestion": "",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 11,
      "statCycle": "周",
      "period": "第4周(1.22-1.28)",
      "maintainer": "赵六",
      "areaName": "白云区",
      "indicatorName": "工作效率",
      "workorderTimelyRate": "87.6%",
      "inspectionCompletionRate": "90.3%",
      "faultRepairRate": "86.2%",
      "avgDisposalTime": "6.2小时",
      "performanceScore": 82.4,
      "rank": 5,
      "timelyScore": 83,
      "qualityScore": 81,
      "efficiencyScore": 80,
      "attitudeScore": 86,
      "deductionReason": "多次工单超时",
      "improvementSuggestion": "提升工作效率",
      "updateTime": "2026-01-28 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 12,
      "statCycle": "月",
      "period": "2026年1月",
      "maintainer": "钱七",
      "areaName": "黄埔区",
      "indicatorName": "综合绩效",
      "workorderTimelyRate": "97.8%",
      "inspectionCompletionRate": "98.6%",
      "faultRepairRate": "96.9%",
      "avgDisposalTime": "2.7小时",
      "performanceScore": 96.4,
      "rank": 1,
      "timelyScore": 97,
      "qualityScore": 95,
      "efficiencyScore": 96,
      "attitudeScore": 98,
      "deductionReason": "",
      "improvementSuggestion": "",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    }
  ];
};

/** 搜索表单配置 */
export function useFormSchema() {
  return [
    {
      fieldName: 'statCycle',
      label: '统计周期',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '日', value: '日' },
          { label: '周', value: '周' },
          { label: '月', value: '月' },
        ],
        placeholder: '请选择统计周期',
      },
      rules: 'required',
    },
    {
      fieldName: 'maintainer',
      label: '运维人员',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '张三', value: '张三' },
          { label: '李四', value: '李四' },
          { label: '王五', value: '王五' },
          { label: '赵六', value: '赵六' },
          { label: '钱七', value: '钱七' },
          { label: '孙八', value: '孙八' },
          { label: '周九', value: '周九' },
        ],
        placeholder: '请选择运维人员',
        showSearch: true,
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
      },
      fieldName: 'areaName',
      label: '行政区域',
    },
    {
      fieldName: 'indicatorName',
      label: '考核指标',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '综合绩效', value: '综合绩效' },
          { label: '响应速度', value: '响应速度' },
          { label: '维修质量', value: '维修质量' },
          { label: '工作效率', value: '工作效率' },
          { label: '服务态度', value: '服务态度' },
        ],
        placeholder: '请选择考核指标',
      },
    },
  ];
}

/** 表格字段配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'statCycle',
      title: '统计周期',
      minWidth: 100,
      sortable: true,
      slots: { default: 'statCycle' },
    },
    {
      field: 'period',
      title: '统计期间',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'maintainer',
      title: '运维人员',
      minWidth: 100,
      sortable: true,
      slots: { default: 'maintainer' },
    },
    {
      field: 'areaName',
      title: '行政区域',
      minWidth: 100,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'indicatorName',
      title: '考核指标',
      minWidth: 120,
      sortable: true,
      slots: { default: 'indicatorName' },
    },
    {
      field: 'workorderTimelyRate',
      title: '工单处置及时率',
      minWidth: 140,
      sortable: true,
      slots: { default: 'workorderTimelyRate' },
    },
    {
      field: 'inspectionCompletionRate',
      title: '巡检完成率',
      minWidth: 120,
      sortable: true,
      slots: { default: 'inspectionCompletionRate' },
    },
    {
      field: 'faultRepairRate',
      title: '故障修复率',
      minWidth: 120,
      sortable: true,
      slots: { default: 'faultRepairRate' },
    },
    {
      field: 'avgDisposalTime',
      title: '平均处置时长',
      minWidth: 130,
      sortable: true,
      slots: { default: 'avgDisposalTime' },
    },
    {
      field: 'performanceScore',
      title: '绩效得分',
      minWidth: 100,
      sortable: true,
      slots: { default: 'performanceScore' },
    },
    {
      field: 'rank',
      title: '排名',
      minWidth: 80,
      sortable: true,
      slots: { default: 'rank' },
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑报表',
  addText: '新增报表',
  excelName: '运维人员绩效考核报表',
  excelAllName: '运维人员绩效考核报表.xlsx',
  total: '报表总数: 12; 优秀人员: 3; 待改进人员: 2; 平均绩效分: 91.5;',
};
