/** 发票管理表格列配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: '主键ID',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'invoiceNo',
      title: '发票编号',
      minWidth: 160,
      sortable: true,
      slots: { default: 'invoiceNo' },
    },
    {
      field: 'taxNo',
      title: '税号',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'orderNo',
      title: '关联订单',
      minWidth: 160,
      sortable: true,
      slots: { default: 'orderNo' },
    },
    {
      field: 'title',
      title: '发票抬头',
      minWidth: 160,
      sortable: true,
      slots: { default: 'title' },
    },
    {
      field: 'amount',
      title: '开票金额',
      minWidth: 140,
      sortable: true,
      customRender: ({ text }) => text ? `¥${text.toFixed(2)}` : '¥0.00',
    },
    {
      field: 'status',
      title: '发票状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'status' },
    },
    {
      field: 'operatorName',
      title: '操作人',
      minWidth: 120,
      sortable: true,
      slots: { default: 'operatorName' },
    },
    {
      field: 'pushTime',
      title: '推送时间',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'downloadCount',
      title: '下载次数',
      minWidth: 120,
      sortable: true,
      customRender: ({ text }) => text || 0,
    },
    {
      field: 'auditorName',
      title: '审核人',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'auditTime',
      title: '审核时间',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'invoiceTime',
      title: '开票时间',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'creator',
      title: '创建者',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'createTime',
      title: '生成时间',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      field: 'updateTime',
      title: '更新时间',
      minWidth: 200,
      sortable: true,
      customRender: ({ text }) => text || '-',
    },
    {
      title: '操作',
      width: 150,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}