// data.js
/** 故障统计报表 - 初始数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "areaName": "天河区",
      "deviceType": "摄像头",
      "faultType": "网络故障",
      "faultLevel": "一级",
      "faultCount": 28,
      "avgDisposalDuration": "4.5小时",
      "disposalRate": "96.4%",
      "repeatFaultCount": 5,
      "pendingCount": 1,
      "disposalCount": 27,
      "totalDevice": 450,
      "faultRate": "6.22%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 2,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "areaName": "越秀区",
      "deviceType": "道闸",
      "faultType": "机械故障",
      "faultLevel": "二级",
      "faultCount": 18,
      "avgDisposalDuration": "6.2小时",
      "disposalRate": "94.4%",
      "repeatFaultCount": 3,
      "pendingCount": 1,
      "disposalCount": 17,
      "totalDevice": 280,
      "faultRate": "6.43%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 3,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "areaName": "海珠区",
      "deviceType": "地磁",
      "faultType": "通信故障",
      "faultLevel": "三级",
      "faultCount": 15,
      "avgDisposalDuration": "3.8小时",
      "disposalRate": "100%",
      "repeatFaultCount": 2,
      "pendingCount": 0,
      "disposalCount": 15,
      "totalDevice": 380,
      "faultRate": "3.95%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 4,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "areaName": "白云区",
      "deviceType": "充电桩",
      "faultType": "电源故障",
      "faultLevel": "一级",
      "faultCount": 12,
      "avgDisposalDuration": "8.5小时",
      "disposalRate": "91.7%",
      "repeatFaultCount": 2,
      "pendingCount": 1,
      "disposalCount": 11,
      "totalDevice": 320,
      "faultRate": "3.75%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 5,
      "startDate": "2026-02-01",
      "endDate": "2026-02-05",
      "areaName": "黄埔区",
      "deviceType": "显示屏",
      "faultType": "显示故障",
      "faultLevel": "三级",
      "faultCount": 8,
      "avgDisposalDuration": "5.2小时",
      "disposalRate": "100%",
      "repeatFaultCount": 1,
      "pendingCount": 0,
      "disposalCount": 8,
      "totalDevice": 180,
      "faultRate": "4.44%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 6,
      "startDate": "2026-01-25",
      "endDate": "2026-01-31",
      "areaName": "天河区",
      "deviceType": "摄像头",
      "faultType": "网络故障",
      "faultLevel": "一级",
      "faultCount": 32,
      "avgDisposalDuration": "5.1小时",
      "disposalRate": "93.8%",
      "repeatFaultCount": 6,
      "pendingCount": 2,
      "disposalCount": 30,
      "totalDevice": 450,
      "faultRate": "7.11%",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 7,
      "startDate": "2026-01-25",
      "endDate": "2026-01-31",
      "areaName": "越秀区",
      "deviceType": "道闸",
      "faultType": "机械故障",
      "faultLevel": "二级",
      "faultCount": 22,
      "avgDisposalDuration": "7.3小时",
      "disposalRate": "90.9%",
      "repeatFaultCount": 4,
      "pendingCount": 2,
      "disposalCount": 20,
      "totalDevice": 280,
      "faultRate": "7.86%",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 8,
      "startDate": "2026-01-20",
      "endDate": "2026-01-26",
      "areaName": "天河区",
      "deviceType": "地磁",
      "faultType": "通信故障",
      "faultLevel": "三级",
      "faultCount": 10,
      "avgDisposalDuration": "4.2小时",
      "disposalRate": "100%",
      "repeatFaultCount": 1,
      "pendingCount": 0,
      "disposalCount": 10,
      "totalDevice": 200,
      "faultRate": "5.00%",
      "updateTime": "2026-01-26 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 9,
      "startDate": "2026-01-20",
      "endDate": "2026-01-26",
      "areaName": "海珠区",
      "deviceType": "充电桩",
      "faultType": "电源故障",
      "faultLevel": "一级",
      "faultCount": 14,
      "avgDisposalDuration": "9.1小时",
      "disposalRate": "92.9%",
      "repeatFaultCount": 2,
      "pendingCount": 1,
      "disposalCount": 13,
      "totalDevice": 380,
      "faultRate": "3.68%",
      "updateTime": "2026-01-26 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 10,
      "startDate": "2026-01-15",
      "endDate": "2026-01-21",
      "areaName": "天河区",
      "deviceType": "摄像头",
      "faultType": "网络故障",
      "faultLevel": "二级",
      "faultCount": 25,
      "avgDisposalDuration": "4.8小时",
      "disposalRate": "96.0%",
      "repeatFaultCount": 4,
      "pendingCount": 1,
      "disposalCount": 24,
      "totalDevice": 450,
      "faultRate": "5.56%",
      "updateTime": "2026-01-21 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 11,
      "startDate": "2026-01-01",
      "endDate": "2026-01-31",
      "areaName": "荔湾区",
      "deviceType": "道闸",
      "faultType": "机械故障",
      "faultLevel": "一级",
      "faultCount": 35,
      "avgDisposalDuration": "6.8小时",
      "disposalRate": "91.4%",
      "repeatFaultCount": 7,
      "pendingCount": 3,
      "disposalCount": 32,
      "totalDevice": 220,
      "faultRate": "15.91%",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 12,
      "startDate": "2026-01-01",
      "endDate": "2026-01-31",
      "areaName": "番禺区",
      "deviceType": "显示屏",
      "faultType": "显示故障",
      "faultLevel": "三级",
      "faultCount": 12,
      "avgDisposalDuration": "5.5小时",
      "disposalRate": "100%",
      "repeatFaultCount": 2,
      "pendingCount": 0,
      "disposalCount": 12,
      "totalDevice": 280,
      "faultRate": "4.29%",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    }
  ];
};

/** 搜索表单配置 */
export function useFormSchema() {
  return [
    {
      fieldName: 'dateRange',
      label: '时间范围',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'daterange',
        startPlaceholder: '开始日期',
        endPlaceholder: '结束日期',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceType',
      label: '设备类型',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '摄像头', value: '摄像头' },
          { label: '道闸', value: '道闸' },
          { label: '地磁', value: '地磁' },
          { label: '充电桩', value: '充电桩' },
          { label: '显示屏', value: '显示屏' },
          { label: '监控主机', value: '监控主机' },
          { label: '服务器', value: '服务器' },
        ],
        placeholder: '请选择设备类型',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
      },
      fieldName: 'areaName',
      label: '行政区域',
    },
    {
      fieldName: 'faultType',
      label: '故障类型',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '网络故障', value: '网络故障' },
          { label: '机械故障', value: '机械故障' },
          { label: '通信故障', value: '通信故障' },
          { label: '电源故障', value: '电源故障' },
          { label: '显示故障', value: '显示故障' },
          { label: '软件故障', value: '软件故障' },
          { label: '硬件故障', value: '硬件故障' },
        ],
        placeholder: '请选择故障类型',
      },
    },
    {
      fieldName: 'faultLevel',
      label: '故障等级',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        options: [
          { label: '一级', value: '一级' },
          { label: '二级', value: '二级' },
          { label: '三级', value: '三级' },
          { label: '四级', value: '四级' },
        ],
        placeholder: '请选择故障等级',
      },
    },
  ];
}

/** 表格字段配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'dateRange',
      title: '时间范围',
      minWidth: 180,
      sortable: true,
      slots: { default: 'dateRange' },
    },
    {
      field: 'areaName',
      title: '行政区域',
      minWidth: 100,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'deviceType',
      title: '设备类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'deviceType' },
    },
    {
      field: 'faultType',
      title: '故障类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'faultType' },
    },
    {
      field: 'faultLevel',
      title: '故障等级',
      minWidth: 100,
      sortable: true,
      slots: { default: 'faultLevel' },
    },
    {
      field: 'faultCount',
      title: '故障次数',
      minWidth: 100,
      sortable: true,
      slots: { default: 'faultCount' },
    },
    {
      field: 'repeatFaultCount',
      title: '重复故障',
      minWidth: 100,
      sortable: true,
      slots: { default: 'repeatFaultCount' },
    },
    {
      field: 'avgDisposalDuration',
      title: '平均处置时长',
      minWidth: 130,
      sortable: true,
      slots: { default: 'avgDisposalDuration' },
    },
    {
      field: 'disposalRate',
      title: '处置率',
      minWidth: 100,
      sortable: true,
      slots: { default: 'disposalRate' },
    },
    {
      field: 'faultRate',
      title: '故障率',
      minWidth: 100,
      sortable: true,
      slots: { default: 'faultRate' },
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑报表',
  addText: '新增报表',
  excelName: '故障统计报表',
  excelAllName: '故障统计报表.xlsx',
  total: '报表总数: 12; 本周故障: 81; 本月故障: 156;',
};
