/** 表格初始数据 - 泉州市区充电停车订单数据 */
export const dataList = () => [
  {
    orderNumber: 'CZ-TC-QZ-20240601-0001',
    userName: '陈先生',
    stationName: '丰泽区行政中心充电站',
    orderType: '充电+停车',
    totalAmount: 45.6,
    actualAmount: 45.6,
    orderStatus: '已完成',
    payTime: '2024-06-01 09:28:15',
    createTime: '2024-06-01 08:55:03',
    payChannel: '微信支付',
    discountAmount: 0.0,
    updateUser: '系统',
    updateTime: '2024-06-01 09:28:18',
  },
  {
    orderNumber: 'CZ-TC-QZ-20240601-0002',
    userName: '林女士',
    stationName: '东海泰禾广场充电站',
    orderType: '仅充电',
    totalAmount: 32.8,
    actualAmount: 29.5,
    orderStatus: '已完成',
    payTime: '2024-06-01 10:15:33',
    createTime: '2024-06-01 09:40:22',
    payChannel: '支付宝',
    discountAmount: 3.3,
    updateUser: '系统',
    updateTime: '2024-06-01 10:15:36',
  },
  {
    orderNumber: 'CZ-TC-QZ-20240601-0003',
    userName: '王先生',
    stationName: '西湖公园西门停车场',
    orderType: '停车+充电',
    totalAmount: 28.5,
    actualAmount: 28.5,
    orderStatus: '已完成',
    payTime: '2024-06-01 11:02:47',
    createTime: '2024-06-01 10:25:11',
    payChannel: '云闪付',
    discountAmount: 0.0,
    updateUser: '系统',
    updateTime: '2024-06-01 11:02:50',
  },
  {
    orderNumber: 'CZ-TC-QZ-20240601-0004',
    userName: '吴先生',
    stationName: '华侨大学充电站',
    orderType: '仅停车',
    totalAmount: 15.0,
    actualAmount: 15.0,
    orderStatus: '已完成',
    payTime: '2024-06-01 14:36:02',
    createTime: '2024-06-01 12:10:45',
    payChannel: '微信支付',
    discountAmount: 0.0,
    updateUser: '系统',
    updateTime: '2024-06-01 14:36:05',
  },
  {
    orderNumber: 'CZ-TC-QZ-20240601-0005',
    userName: '郑女士',
    stationName: '泉秀街沉州停车场',
    orderType: '充电+停车',
    totalAmount: 52.3,
    actualAmount: 47.1,
    orderStatus: '已完成',
    payTime: '2024-06-01 15:48:19',
    createTime: '2024-06-01 14:50:37',
    payChannel: '支付宝',
    discountAmount: 5.2,
    updateUser: '系统',
    updateTime: '2024-06-01 15:48:22',
  },
  {
    orderNumber: 'CZ-TC-QZ-20240601-0006',
    userName: '张先生',
    stationName: '城东万达广场充电站',
    orderType: '仅充电',
    totalAmount: 38.7,
    actualAmount: 38.7,
    orderStatus: '已完成',
    payTime: '2024-06-01 16:30:55',
    createTime: '2024-06-01 15:55:28',
    payChannel: '微信支付',
    discountAmount: 0.0,
    updateUser: '系统',
    updateTime: '2024-06-01 16:30:58',
  },
  {
    orderNumber: 'CZ-TC-QZ-20240601-0007',
    userName: '黄女士',
    stationName: '北峰街道闽台缘停车场',
    orderType: '停车+充电',
    totalAmount: 31.2,
    actualAmount: 28.1,
    orderStatus: '已完成',
    payTime: '2024-06-01 17:22:08',
    createTime: '2024-06-01 16:40:15',
    payChannel: '云闪付',
    discountAmount: 3.1,
    updateUser: '系统',
    updateTime: '2024-06-01 17:22:11',
  },
  {
    orderNumber: 'CZ-TC-QZ-20240601-0008',
    userName: '刘先生',
    stationName: '清源山东方驾校停车场',
    orderType: '仅停车',
    totalAmount: 20.0,
    actualAmount: 20.0,
    orderStatus: '已完成',
    payTime: '2024-06-01 18:15:43',
    createTime: '2024-06-01 14:20:09',
    payChannel: '微信支付',
    discountAmount: 0.0,
    updateUser: '系统',
    updateTime: '2024-06-01 18:15:46',
  },
  {
    orderNumber: 'CZ-TC-QZ-20240601-0009',
    userName: '赵女士',
    stationName: '宝洲路万达公馆充电站',
    orderType: '充电+停车',
    totalAmount: 49.5,
    actualAmount: 44.6,
    orderStatus: '已完成',
    payTime: '2024-06-01 19:05:31',
    createTime: '2024-06-01 18:20:47',
    payChannel: '支付宝',
    discountAmount: 4.9,
    updateUser: '系统',
    updateTime: '2024-06-01 19:05:34',
  },
  {
    orderNumber: 'CZ-TC-QZ-20240601-0010',
    userName: '孙先生',
    stationName: '美食街公共充电站',
    orderType: '仅充电',
    totalAmount: 26.9,
    actualAmount: 26.9,
    orderStatus: '已完成',
    payTime: '2024-06-01 20:38:26',
    createTime: '2024-06-01 20:05:14',
    payChannel: '微信支付',
    discountAmount: 0.0,
    updateUser: '系统',
    updateTime: '2024-06-01 20:38:29',
  },
];

/** 新增/修改的表单 - 充电停车订单搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'orderNumber',
      label: '订单编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入订单编号',
        maxLength: 50,
      },
      labelWidth: 120,
    },
    {
      fieldName: 'userName',
      label: '用户名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入用户名称',
        maxLength: 50,
      },
      labelWidth: 120,
    },
    {
      fieldName: 'stationName',
      label: '所属场站',
      component: 'Select',
      componentProps: {
        allowClear: true,
        placeholder: '请选择所属场站',
      },
      labelWidth: 120,
    },
    {
      fieldName: 'orderType',
      label: '订单类型',
      component: 'Select',
      componentProps: {
        allowClear: true,
        placeholder: '请选择订单类型',
      },
      labelWidth: 120,
    },
    {
      fieldName: 'orderStatus',
      label: '订单状态',
      component: 'Select',
      componentProps: {
        allowClear: true,
        placeholder: '请选择订单状态',
      },
      labelWidth: 120,
    },
    {
      fieldName: 'payChannel',
      label: '支付渠道',
      component: 'Select',
      componentProps: {
        allowClear: true,
        placeholder: '请选择支付渠道',
      },
      labelWidth: 120,
    },
    {
      fieldName: 'updateUser',
      label: '更新人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入更新人',
        maxLength: 50,
      },
      labelWidth: 120,
    },
  ];
}

/** 表格字段 - 充电停车订单表格列（无插槽、无钻取、纯展示） */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'orderNumber',
      title: '订单编号',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'userName',
      title: '用户名称',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'stationName',
      title: '所属场站',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'orderType',
      title: '订单类型',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'totalAmount',
      title: '总金额',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'actualAmount',
      title: '实付金额',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'orderStatus',
      title: '订单状态',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'payTime',
      title: '支付时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'createTime',
      title: '创建时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'payChannel',
      title: '支付渠道',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'discountAmount',
      title: '优惠金额',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'updateUser',
      title: '更新人',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'updateTime',
      title: '更新时间',
      minWidth: 200,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
