/** 表格初始数据 - 改造为占道管理基础数据 */
export const dataList = () => [
  {
    road_occupation_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    location: '福州市鼓楼区杨桥东路（东街口-五一广场）',
    occupation_type: '施工占道',
    area: 125.5,
    grid_name: '鼓楼区东街网格',  // 改为中文网格名称
    ai_confidence: 92.8,
    warning_photos: '["https://example.com/photo1.jpg", "https://example.com/photo2.jpg"]',
    warning_time: '2024-06-18 09:30:00',
    law_enforcer_id: 'd3cebc99-9c0b-4ef8-bb6d-6bb9bd380a44',
    disposal_measure: '现场劝离并警告',
    disposal_result_id: 'e4debc99-9c0b-4ef8-bb6d-6bb9bd380a55',
    rectification_photos: '["https://example.com/rect1.jpg"]',
    penalty_result: '罚款200元',
    penalty_no: 'FZ-20240618-001',
    create_time: '2024-06-18 09:35:00',
    update_time: '2024-06-18 10:20:00',
    del_flag: 0,
  },
  {
    road_occupation_id: 'b5efbc99-9c0b-4ef8-bb6d-6bb9bd380a66',
    location: '厦门市思明区鹭江道（轮渡码头-中山路）',
    occupation_type: '经营占道',
    area: 80.2,
    grid_name: '思明区鹭江网格',  // 改为中文网格名称
    ai_confidence: 88.5,
    warning_photos: '["https://example.com/photo3.jpg"]',
    warning_time: '2024-06-18 14:20:00',
    law_enforcer_id: 'e81bcc99-9c0b-4ef8-bb6d-6bb9bd380a99',
    disposal_measure: '开具整改通知书',
    disposal_result_id: 'f92ccc99-9c0b-4ef8-bb6d-6bb9bd380aaa',
    rectification_photos: '["https://example.com/rect2.jpg", "https://example.com/rect3.jpg"]',
    penalty_result: '责令限期整改',
    penalty_no: 'XM-20240618-042',
    create_time: '2024-06-18 14:25:00',
    update_time: '2024-06-18 15:00:00',
    del_flag: 0,
  },
  {
    road_occupation_id: 'a03dbc99-9c0b-4ef8-bb6d-6bb9bd380abb',
    location: '泉州市丰泽区刺桐路（湖心街-泉秀街）',
    occupation_type: '活动占道',
    area: 210.0,
    grid_name: '丰泽区刺桐网格',  // 改为中文网格名称
    ai_confidence: 76.3,
    warning_photos: '[无]',
    warning_time: '2024-06-19 08:15:00',
    law_enforcer_id: 'd36gec99-9c0b-4ef8-bb6d-6bb9bd380aee',
    disposal_measure: '暂扣占道物品',
    disposal_result_id: 'e47hfc99-9c0b-4ef8-bb6d-6bb9bd380aff',
    rectification_photos: '["https://example.com/rect4.jpg"]',
    penalty_result: '物品暂扣，罚款500元',
    penalty_no: 'QZ-20240619-023',
    create_time: '2024-06-19 08:20:00',
    update_time: '2024-06-19 09:10:00',
    del_flag: 0,
  },
  {
    road_occupation_id: 'f58gcc99-9c0b-4ef8-bb6d-6bb9bd380b11',
    location: '漳州市芗城区胜利路（延安北路-新华西路）',
    occupation_type: '堆物占道',
    area: 45.8,
    grid_name: '芗城区胜利网格',  // 改为中文网格名称
    ai_confidence: 95.0,
    warning_photos: '["https://example.com/photo5.jpg"]',
    warning_time: '2024-06-19 11:40:00',
    law_enforcer_id: 'c81jfc99-9c0b-4ef8-bb6d-6bb9bd380b44',
    disposal_measure: '宣传教育，自行整改',
    disposal_result_id: 'd92kgc99-9c0b-4ef8-bb6d-6bb9bd380b55',
    rectification_photos: '["https://example.com/rect5.jpg"]',
    penalty_result: '不予处罚',
    penalty_no: '',
    create_time: '2024-06-19 11:45:00',
    update_time: '2024-06-19 12:30:00',
    del_flag: 0,
  },
  {
    road_occupation_id: 'e03lhc99-9c0b-4ef8-bb6d-6bb9bd380b66',
    location: '莆田市城厢区荔城南大道（凤凰山-万达广场）',
    occupation_type: '施工占道',
    area: 156.3,
    grid_name: '城厢区荔城网格',  // 改为中文网格名称
    ai_confidence: 81.2,
    warning_photos: '["https://example.com/photo6.jpg", "https://example.com/photo7.jpg"]',
    warning_time: '2024-06-20 15:10:00',
    law_enforcer_id: 'h36okc99-9c0b-4ef8-bb6d-6bb9bd380b99',
    disposal_measure: '立案调查',
    disposal_result_id: 'i47plc99-9c0b-4ef8-bb6d-6bb9bd380baa',
    rectification_photos: '[]',
    penalty_result: '罚款1000元，并没收违法所得',
    penalty_no: 'PT-20240620-017',
    create_time: '2024-06-20 15:15:00',
    update_time: '2024-06-21 09:00:00',
    del_flag: 0,
  },
  {
    road_occupation_id: 'j58qmc99-9c0b-4ef8-bb6d-6bb9bd380bbb',
    location: '宁德市蕉城区闽东中路（市政府-万达广场）',
    occupation_type: '经营占道',
    area: 32.0,
    grid_name: '蕉城区闽东网格',  // 改为中文网格名称
    ai_confidence: 98.7,
    warning_photos: '["https://example.com/photo8.jpg"]',
    warning_time: '2024-06-20 16:55:00',
    law_enforcer_id: 'm81tpc99-9c0b-4ef8-bb6d-6bb9bd380bee',
    disposal_measure: '口头警告，立即整改',
    disposal_result_id: 'n92uqc99-9c0b-4ef8-bb6d-6bb9bd380bff',
    rectification_photos: '["https://example.com/rect6.jpg"]',
    penalty_result: '无',
    penalty_no: '',
    create_time: '2024-06-20 17:00:00',
    update_time: '2024-06-20 17:30:00',
    del_flag: 0,
  },
  {
    road_occupation_id: 'o03vrc99-9c0b-4ef8-bb6d-6bb9bd380c11',
    location: '龙岩市新罗区龙川路（中山路-登高西路）',
    occupation_type: '堆物占道',
    area: 78.9,
    grid_name: '新罗区龙川网格',  // 改为中文网格名称
    ai_confidence: 73.4,
    warning_photos: '["https://example.com/photo9.jpg"]',
    warning_time: '2024-06-21 09:05:00',
    law_enforcer_id: 'r36yuc99-9c0b-4ef8-bb6d-6bb9bd380c44',
    disposal_measure: '强制清除',
    disposal_result_id: 's47zvc99-9c0b-4ef8-bb6d-6bb9bd380c55',
    rectification_photos: '["https://example.com/rect7.jpg", "https://example.com/rect8.jpg"]',
    penalty_result: '罚款800元，并承担清理费用',
    penalty_no: 'LY-20240621-008',
    create_time: '2024-06-21 09:10:00',
    update_time: '2024-06-21 11:20:00',
    del_flag: 0,
  },
  {
    road_occupation_id: 't58awc99-9c0b-4ef8-bb6d-6bb9bd380c66',
    location: '三明市梅列区列东街（东新四路-东新六路）',
    occupation_type: '活动占道',
    area: 0.0,
    grid_name: '梅列区列东网格',  // 改为中文网格名称
    ai_confidence: 100.0,
    warning_photos: '[无]',
    warning_time: '2024-06-21 13:20:00',
    law_enforcer_id: 'w81dzc99-9c0b-4ef8-bb6d-6bb9bd380c99',
    disposal_measure: '无需处置（误报）',
    disposal_result_id: 'x92eac99-9c0b-4ef8-bb6d-6bb9bd380caa',
    rectification_photos: '[无]',
    penalty_result: '无',
    penalty_no: '',
    create_time: '2024-06-21 13:25:00',
    update_time: '2024-06-21 13:30:00',
    del_flag: 0,
  },
  {
    road_occupation_id: 'y03fbc99-9c0b-4ef8-bb6d-6bb9bd380cbb',
    location: '南平市延平区八一路（江滨路-中山路）',
    occupation_type: '施工占道',
    area: 112.4,
    grid_name: '延平区八一网格',  // 改为中文网格名称
    ai_confidence: 89.1,
    warning_photos: '["https://example.com/photo10.jpg"]',
    warning_time: '2024-06-22 10:30:00',
    law_enforcer_id: 'b36iec99-9c0b-4ef8-bb6d-6bb9bd380cee',
    disposal_measure: '出具处罚决定书',
    disposal_result_id: 'c47jfc99-9c0b-4ef8-bb6d-6bb9bd380cff',
    rectification_photos: '["https://example.com/rect9.jpg"]',
    penalty_result: '罚款300元',
    penalty_no: 'NP-20240622-031',
    create_time: '2024-06-22 10:35:00',
    update_time: '2024-06-22 11:50:00',
    del_flag: 0,
  },
  {
    road_occupation_id: 'd58kgc99-9c0b-4ef8-bb6d-6bb9bd380d11',
    location: '平潭综合实验区金井大道（管委会-龙凤头沙滩）',
    occupation_type: '经营占道',
    area: 64.7,
    grid_name: '平潭金井网格',  // 改为中文网格名称
    ai_confidence: 91.5,
    warning_photos: '["https://example.com/photo11.jpg"]',
    warning_time: '2024-06-22 14:40:00',
    law_enforcer_id: 'g81njc99-9c0b-4ef8-bb6d-6bb9bd380d44',
    disposal_measure: '劝导后自行撤离',
    disposal_result_id: 'h92okc99-9c0b-4ef8-bb6d-6bb9bd380d55',
    rectification_photos: '["https://example.com/rect10.jpg"]',
    penalty_result: '警告教育',
    penalty_no: '',
    create_time: '2024-06-22 14:45:00',
    update_time: '2024-06-22 15:10:00',
    del_flag: 0,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为占道管理表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'location',
      label: '占道位置',
      component: 'Input',
      componentProps: {
        placeholder: '请输入占道位置',
        maxlength: 200,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'occupation_type',
      label: '占道类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择占道类型',
        options: [
          { value: '施工占道', label: '施工占道' },
          { value: '经营占道', label: '经营占道' },
          { value: '堆物占道', label: '堆物占道' },
          { value: '活动占道', label: '活动占道' },
        ],
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'area',
      label: '占道面积',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入占道面积（单位：平方米）',
        min: 0,
        precision: 2,
        addonAfter: 'm²',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'grid_name',
      label: '所属网格',
      component: 'Select',  // 改为下拉选择框
      componentProps: {
        placeholder: '请选择所属网格',
        options: [
          { value: '鼓楼区东街网格', label: '鼓楼区东街网格' },
          { value: '思明区鹭江网格', label: '思明区鹭江网格' },
          { value: '丰泽区刺桐网格', label: '丰泽区刺桐网格' },
          { value: '芗城区胜利网格', label: '芗城区胜利网格' },
          { value: '城厢区荔城网格', label: '城厢区荔城网格' },
          { value: '蕉城区闽东网格', label: '蕉城区闽东网格' },
          { value: '新罗区龙川网格', label: '新罗区龙川网格' },
          { value: '梅列区列东网格', label: '梅列区列东网格' },
          { value: '延平区八一网格', label: '延平区八一网格' },
          { value: '平潭金井网格', label: '平潭金井网格' },
        ],
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'ai_confidence',
      label: 'AI识别置信度',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入AI识别置信度（0-100）',
        min: 0,
        max: 100,
        precision: 2,
        addonAfter: '%',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'warning_photos',
      label: '预警照片URL',
      component: 'Input',
      componentProps: {
        placeholder: '请输入预警照片URL（JSON数组格式）',
        maxlength: 500,
        type: 'textarea',
        rows: 2,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'warning_time',
      label: '预警时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入预警时间 (YYYY-MM-DD HH:mm:ss)',
        maxlength: 20,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'law_enforcer_id',
      label: '执法员ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入执法员ID (UUID)',
        maxlength: 36,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'disposal_measure',
      label: '处置措施',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处置措施',
        maxlength: 100,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'disposal_result_id',
      label: '处置结果ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处置结果ID (UUID)',
        maxlength: 36,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'rectification_photos',
      label: '整改照片URL',
      component: 'Input',
      componentProps: {
        placeholder: '请输入整改照片URL（JSON数组格式）',
        maxlength: 500,
        type: 'textarea',
        rows: 2,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'penalty_result',
      label: '处罚结果',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处罚结果',
        maxlength: 200,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'penalty_no',
      label: '处罚凭证编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处罚凭证编号',
        maxlength: 50,
      },
      labelWidth: '130',
    },
    {
      fieldName: 'create_time',
      label: '创建时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入创建时间 (YYYY-MM-DD HH:mm:ss)',
        maxlength: 20,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'update_time',
      label: '更新时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入更新时间 (YYYY-MM-DD HH:mm:ss)',
        maxlength: 20,
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'del_flag',
      label: '删除标记',
      component: 'Select',
      componentProps: {
        placeholder: '请选择删除标记',
        options: [
          { value: 0, label: '未删除' },
          { value: 1, label: '已删除' },
        ],
      },
      labelWidth: '130',
    },
  ];
}

/** 表格字段 - 改造为占道管理表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'location',
      title: '占道位置',
      minWidth: 220,
      sortable: true,
      slots: { default: 'location' },
    },
    {
      field: 'occupation_type',
      title: '占道类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'occupation_type' },
    },
    {
      field: 'area',
      title: '占道面积(m²)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'grid_name',  // 字段名改为 grid_name
      title: '所属网格',
      minWidth: 150,
      sortable: true,
      slots: { default: 'grid_name' },

    },
    {
      field: 'ai_confidence',
      title: 'AI置信度(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'warning_photos',
      title: '预警照片URL',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'warning_time',
      title: '预警时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'law_enforcer_id',
      title: '执法员ID',
      minWidth: 250,
      sortable: true,
    },
    {
      field: 'disposal_measure',
      title: '处置措施',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'disposal_result_id',
      title: '处置结果ID',
      minWidth: 250,
      sortable: true,
    },
    {
      field: 'rectification_photos',
      title: '整改照片URL',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'penalty_result',
      title: '处罚结果',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'penalty_no',
      title: '处罚凭证编号',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'create_time',
      title: '创建时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'update_time',
      title: '更新时间',
      minWidth: 160,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
