/** 表格初始数据 - 窨井盖设施已完成归档数据 */
export const dataList = () => [
  {
    archiveNo: 'FJ-YG-202406-ARC001',
    orderNo: 'FJ-YG-202406-001',
    warnNo: 'FJ-YJ-202406-001',
    coverNo: 'YJG-001',
    roadName: '福州市鼓楼区杨桥东路',
    abnormalType: '倾斜角度异常',
    checkResult: '合格',
    completeTime: '2024-06-16 02:00:00',
    archiveTime: '2024-06-16 09:00:00',
    dealDuration: 19,
    recoverValue: 5,
    checkStaff: '张明（FJHC001）',
    beforeAfter: '处置前倾斜角度15度，处置后5度，恢复至阈值范围内',
    fileNum: 5,
    riskStatus: '已消除',
  },
  {
    archiveNo: 'FJ-YG-202406-ARC002',
    orderNo: 'FJ-YG-202406-002',
    warnNo: 'FJ-YJ-202406-002',
    coverNo: 'YJG-002',
    roadName: '厦门市思明区鹭江道',
    abnormalType: '振动异常',
    checkResult: '合格',
    completeTime: '2024-06-15 10:00:00',
    archiveTime: '2024-06-15 15:00:00',
    dealDuration: 29,
    recoverValue: 20,
    checkStaff: '李丽（FJHC002）',
    beforeAfter: '处置前振动频率30Hz，处置后20Hz，恢复至阈值范围内',
    fileNum: 8,
    riskStatus: '已消除',
  },
  {
    archiveNo: 'FJ-YG-202406-ARC003',
    orderNo: 'FJ-YG-202406-003',
    warnNo: 'FJ-YJ-202406-003',
    coverNo: 'YJG-003',
    roadName: '泉州市丰泽区刺桐路',
    abnormalType: '设备离线',
    checkResult: '合格',
    completeTime: '2024-06-15 18:00:00',
    archiveTime: '2024-06-15 20:00:00',
    dealDuration: 8,
    recoverValue: 1,
    checkStaff: '王强（FJHC003）',
    beforeAfter: '处置前设备离线，处置后设备在线，恢复正常',
    fileNum: 3,
    riskStatus: '已消除',
  },
  {
    archiveNo: 'FJ-YG-202406-ARC004',
    orderNo: 'FJ-YG-202406-004',
    warnNo: 'FJ-YJ-202406-004',
    coverNo: 'YJG-004',
    roadName: '漳州市芗城区胜利路',
    abnormalType: '倾斜角度异常',
    checkResult: '合格',
    completeTime: '2024-06-15 16:00:00',
    archiveTime: '2024-06-15 18:00:00',
    dealDuration: 8,
    recoverValue: 6,
    checkStaff: '陈杰（FJHC004）',
    beforeAfter: '处置前倾斜角度18度，处置后6度，恢复至阈值范围内',
    fileNum: 4,
    riskStatus: '已消除',
  },
  {
    archiveNo: 'FJ-YG-202406-ARC005',
    orderNo: 'FJ-YG-202406-005',
    warnNo: 'FJ-YJ-202406-005',
    coverNo: 'YJG-005',
    roadName: '莆田市城厢区荔城南大道',
    abnormalType: '振动异常',
    checkResult: '不合格',
    completeTime: '2024-06-14 10:00:00',
    archiveTime: '2024-06-14 12:00:00',
    dealDuration: 14,
    recoverValue: 25,
    checkStaff: '赵伟（FJHC005）',
    beforeAfter: '处置前振动频率28Hz，处置后25Hz，未完全恢复至阈值范围内',
    fileNum: 2,
    riskStatus: '部分消除',
  },
];


/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施已完成归档表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'archiveNo',
      label: '归档编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入归档编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'orderNo',
      label: '关联处置工单编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联处置工单编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'warnNo',
      label: '关联预警编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联预警编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'coverNo',
      label: '井盖编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入井盖编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'roadName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
        maxLength: 100,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '倾斜角度异常', value: '倾斜角度异常' },
          { label: '振动异常', value: '振动异常' },
          { label: '设备离线', value: '设备离线' },
          { label: '设备异常', value: '设备异常' },
          { label: '轻微倾斜', value: '轻微倾斜' },
        ],
        placeholder: '请选择异常类型',
        showSearch: true,
      },
      fieldName: 'abnormalType',
      label: '异常类型',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '合格', value: '合格' },
          { label: '不合格', value: '不合格' },
        ],
        placeholder: '请选择核查结果',
        showSearch: true,
      },
      fieldName: 'checkResult',
      label: '核查结果',
      rules: 'required',
    },
    {
      fieldName: 'completeTime',
      label: '处置完成时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择处置完成时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'archiveTime',
      label: '归档时间',
      component: 'DatePicker',
      labelWidth: '120',
      componentProps: {
        placeholder: '请选择归档时间',
        type: 'datetime',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'dealDuration',
      label: '预警处置总时长',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入预警处置总时长（单位：小时）',
        min: 0,
        precision: 1,
        addonAfter: '小时',
      },
      rules: 'required',
    },
    {
      fieldName: 'recoverValue',
      label: '窨井盖指标恢复值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入窨井盖指标恢复值',
        min: 0,
        precision: 1,
      },
      rules: 'required',
    },
    {
      fieldName: 'checkStaff',
      label: '核查员',
      component: 'Input',
      componentProps: {
        placeholder: '请输入核查员',
        maxLength: 100,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'beforeAfter',
      label: '处置前后指标对比',
      component: 'Input',
      componentProps: {
        placeholder: '请输入处置前后指标对比',
        maxlength: 500,
        type: 'textarea',
        rows: 4,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'fileNum',
      label: '归档资料数',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入归档资料数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '已消除', value: '已消除' },
          { label: '部分消除', value: '部分消除' },
          { label: '未消除', value: '未消除' },
        ],
        placeholder: '请选择安全风险消除状态',
        showSearch: true,
      },
      fieldName: 'riskStatus',
      label: '安全风险消除状态',
      rules: 'required',
    },
  ];
}


/** 表格字段 - 窨井盖设施已完成归档表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'archiveNo',
      title: '归档编号',
      minWidth: 200,
      sortable: true,
      slots: { default: 'archiveNo' },
    },
    {
      field: 'orderNo',
      title: '关联处置工单编号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'warnNo',
      title: '关联预警编号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'coverNo',
      title: '井盖编号',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'roadName',
      title: '路段名称',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'abnormalType',
      title: '异常类型',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'checkResult',
      title: '核查结果',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'completeTime',
      title: '处置完成时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'archiveTime',
      title: '归档时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'dealDuration',
      title: '预警处置总时长(小时)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'recoverValue',
      title: '窨井盖指标恢复值',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'checkStaff',
      title: '核查员',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'beforeAfter',
      title: '处置前后指标对比',
      minWidth: 250,
      sortable: false,
    },
    {
      field: 'fileNum',
      title: '归档资料数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'riskStatus',
      title: '安全风险消除状态',
      minWidth: 120,
      sortable: true,
    },
    {
      title: '操作',
      width: 150,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

