/** 表格初始数据 - 改造为泉州市区执法复审台账数据 */
export const dataList = () => [
  {
    ledgerCode: 'ZF-QZ-202406-001',
    enterpriseName: '泉州市路桥建设开发有限公司',
    violationType: '未按规范进行桥梁养护',
    violationLevel: '一般违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/001.pdf',
    draftTime: '2024-06-01 09:30:25',
    reviewStatus: '已复审',
    reviewer: '张明（工号：QZZF001）',
    reviewTime: '2024-06-05 14:20:18',
    issueTime: '2024-06-08 10:15:36',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterpriseRectificationStatus: '已整改',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-001',
  },
  {
    ledgerCode: 'ZF-QZ-202406-002',
    enterpriseName: '泉州市市政工程有限公司',
    violationType: '监测数据造假',
    violationLevel: '严重违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/002.pdf',
    draftTime: '2024-06-02 10:15:42',
    reviewStatus: '复审中',
    reviewer: '李丽（工号：QZZF002）',
    reviewTime: '2024-06-06 09:18:49',
    issueTime: '',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '未送达',
    enterpriseRectificationStatus: '整改中',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-002',
  },
  {
    ledgerCode: 'ZF-QZ-202406-003',
    enterpriseName: '泉州市交通建设发展有限公司',
    violationType: '未按时提交养护报告',
    violationLevel: '轻微违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/003.pdf',
    draftTime: '2024-06-03 14:20:18',
    reviewStatus: '未复审',
    reviewer: '',
    reviewTime: '',
    issueTime: '',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '待送达',
    enterpriseRectificationStatus: '未整改',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-003',
  },
  {
    ledgerCode: 'ZF-QZ-202406-004',
    enterpriseName: '泉州市鲤城区市政养护中心',
    violationType: '养护设备未定期校准',
    violationLevel: '一般违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/004.pdf',
    draftTime: '2024-06-04 15:25:36',
    reviewStatus: '已复审',
    reviewer: '王强（工号：QZZF003）',
    reviewTime: '2024-06-07 11:22:05',
    issueTime: '2024-06-09 15:10:08',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterpriseRectificationStatus: '整改完成',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-004',
  },
  {
    ledgerCode: 'ZF-QZ-202406-005',
    enterpriseName: '泉州市丰泽区路桥工程有限公司',
    violationType: '违规占道施工',
    violationLevel: '严重违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/005.pdf',
    draftTime: '2024-06-05 16:50:08',
    reviewStatus: '已撤销',
    reviewer: '陈红（工号：QZZF004）',
    reviewTime: '2024-06-08 16:05:33',
    issueTime: '2024-06-10 09:32:15',
    revokeTime: '2024-06-12 14:15:20',
    revokeReason: '证据不足，经复核撤销',
    serviceStatus: '已撤回',
    enterpriseRectificationStatus: '无需整改',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-005',
  },
  {
    ledgerCode: 'ZF-QZ-202406-006',
    enterpriseName: '泉州市洛江区公路养护有限公司',
    violationType: '安全警示标识缺失',
    violationLevel: '轻微违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/006.pdf',
    draftTime: '2024-06-06 08:32:15',
    reviewStatus: '已复审',
    reviewer: '黄明（工号：QZZF005）',
    reviewTime: '2024-06-09 10:15:20',
    issueTime: '2024-06-11 11:28:42',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterpriseRectificationStatus: '整改中',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-006',
  },
  {
    ledgerCode: 'ZF-QZ-202406-007',
    enterpriseName: '泉州市泉港区交通建设有限公司',
    violationType: '养护人员无证上岗',
    violationLevel: '一般违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/007.pdf',
    draftTime: '2024-06-07 11:18:49',
    reviewStatus: '复审中',
    reviewer: '郑伟（工号：QZZF006）',
    reviewTime: '',
    issueTime: '',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '待送达',
    enterpriseRectificationStatus: '未整改',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-007',
  },
  {
    ledgerCode: 'ZF-QZ-202406-008',
    enterpriseName: '泉州市台商投资区市政工程有限公司',
    violationType: '未按要求设置防护措施',
    violationLevel: '一般违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/008.pdf',
    draftTime: '2024-06-08 13:22:05',
    reviewStatus: '已复审',
    reviewer: '吴芳（工号：QZZF007）',
    reviewTime: '2024-06-10 15:30:25',
    issueTime: '2024-06-12 12:10:18',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterpriseRectificationStatus: '已整改',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-008',
  },
  {
    ledgerCode: 'ZF-QZ-202406-009',
    enterpriseName: '泉州市经济技术开发区路桥养护中心',
    violationType: '养护记录不完整',
    violationLevel: '轻微违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/009.pdf',
    draftTime: '2024-06-09 10:05:33',
    reviewStatus: '未复审',
    reviewer: '',
    reviewTime: '',
    issueTime: '',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '未送达',
    enterpriseRectificationStatus: '整改中',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-009',
  },
  {
    ledgerCode: 'ZF-QZ-202406-010',
    enterpriseName: '泉州市晋江大桥管理有限公司',
    violationType: '超限车辆未报备通行',
    violationLevel: '严重违规',
    violationEvidenceUrl: 'https://evidence.qzzf.gov.cn/202406/010.pdf',
    draftTime: '2024-06-10 14:15:20',
    reviewStatus: '已复审',
    reviewer: '林达（工号：QZZF008）',
    reviewTime: '2024-06-11 16:25:36',
    issueTime: '2024-06-13 10:50:08',
    revokeTime: '',
    revokeReason: '',
    serviceStatus: '已送达',
    enterpriseRectificationStatus: '逾期未整改',
    lawEnforcementReviewLedgerCode: 'FJSF-QZ-202406-010',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为执法复审台账表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'ledgerCode',
      label: '台账编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入台账编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 台账编号为必填项
    },
    {
      fieldName: 'enterpriseName',
      label: '企业名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入企业名称',
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未按规范进行桥梁养护', value: '未按规范进行桥梁养护' },
          { label: '监测数据造假', value: '监测数据造假' },
          { label: '未按时提交养护报告', value: '未按时提交养护报告' },
          { label: '养护设备未定期校准', value: '养护设备未定期校准' },
          { label: '违规占道施工', value: '违规占道施工' },
          { label: '安全警示标识缺失', value: '安全警示标识缺失' },
          { label: '养护人员无证上岗', value: '养护人员无证上岗' },
          { label: '未按要求设置防护措施', value: '未按要求设置防护措施' },
          { label: '养护记录不完整', value: '养护记录不完整' },
          { label: '超限车辆未报备通行', value: '超限车辆未报备通行' },
        ],
        placeholder: '请选择违规类型',
        showSearch: true,
      },
      fieldName: 'violationType',
      label: '违规类型',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '轻微违规', value: '轻微违规' },
          { label: '一般违规', value: '一般违规' },
          { label: '严重违规', value: '严重违规' },
        ],
        placeholder: '请选择违规等级',
        showSearch: true,
      },
      fieldName: 'violationLevel',
      label: '违规等级',
      rules: 'required',
    },
    {
      fieldName: 'violationEvidenceUrl',
      label: '违规证据链接',
      component: 'Input',
      componentProps: {
        placeholder: '请输入违规证据链接',
        maxLength: 200,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'draftTime',
      label: '草拟时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入草拟时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未复审', value: '未复审' },
          { label: '复审中', value: '复审中' },
          { label: '已复审', value: '已复审' },
          { label: '已撤销', value: '已撤销' },
        ],
        placeholder: '请选择复审状态',
        showSearch: true,
      },
      fieldName: 'reviewStatus',
      label: '复审状态',
      rules: 'required',
    },
    {
      fieldName: 'reviewer',
      label: '复审人',
      component: 'Input',
      componentProps: {
        placeholder: '请输入复审人姓名/工号',
      },
      labelWidth: '120',
      rules: '', // 非必填，复审状态为未复审时可空
    },
    {
      fieldName: 'reviewTime',
      label: '复审时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入复审时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      labelWidth: '120',
      rules: '', // 非必填，复审状态为未复审时可空
    },
    {
      fieldName: 'issueTime',
      label: '下发时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入下发时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      labelWidth: '120',
      rules: '', // 非必填，未下发时可空
    },
    {
      fieldName: 'revokeTime',
      label: '撤销时间',
      component: 'Input',
      componentProps: {
        placeholder: '请输入撤销时间（格式：YYYY-MM-DD HH:mm:ss）',
        maxlength: 20,
      },
      labelWidth: '120',
      rules: '', // 非必填，未撤销时可空
    },
    {
      fieldName: 'revokeReason',
      label: '撤销原因',
      component: 'Input',
      componentProps: {
        placeholder: '请输入撤销原因',
        maxlength: 500,
      },
      labelWidth: '120',
      rules: '', // 非必填，未撤销时可空
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未送达', value: '未送达' },
          { label: '待送达', value: '待送达' },
          { label: '已送达', value: '已送达' },
          { label: '已撤回', value: '已撤回' },
        ],
        placeholder: '请选择送达状态',
        showSearch: true,
      },
      fieldName: 'serviceStatus',
      label: '送达状态',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未整改', value: '未整改' },
          { label: '整改中', value: '整改中' },
          { label: '已整改', value: '已整改' },
          { label: '整改完成', value: '整改完成' },
          { label: '无需整改', value: '无需整改' },
          { label: '逾期未整改', value: '逾期未整改' },
        ],
        placeholder: '请选择企业整改反馈状态',
        showSearch: true,
      },
      fieldName: 'enterpriseRectificationStatus',
      label: '企业整改反馈状态',
      rules: 'required',
    },
    {
      fieldName: 'lawEnforcementReviewLedgerCode',
      label: '执法复审台账编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入执法复审台账编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为执法复审台账表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'ledgerCode',
      title: '台账编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'ledgerCode' },
    },
    {
      field: 'enterpriseName',
      title: '企业名称',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'violationType',
      title: '违规类型',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'violationLevel',
      title: '违规等级',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'violationEvidenceUrl',
      title: '违规证据链接',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'draftTime',
      title: '草拟时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'reviewStatus',
      title: '复审状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'reviewer',
      title: '复审人',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'reviewTime',
      title: '复审时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'issueTime',
      title: '下发时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'revokeTime',
      title: '撤销时间',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'revokeReason',
      title: '撤销原因',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'serviceStatus',
      title: '送达状态',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'enterpriseRectificationStatus',
      title: '企业整改反馈状态',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'lawEnforcementReviewLedgerCode',
      title: '执法复审台账编号',
      minWidth: 200,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}