/** 表格初始数据 - 窨井盖设施监测周报数据 */
export const dataList = () => [
  {
    areaName: '福州市鼓楼区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 1500,
    weekTotalHiddenTroubleCount: 15,
    weekDisposalCompleteCount: 12,
    weekAvgDeviceOnlineRate: 98.5,
    weekNewHiddenTroubleCount: 10,
    deptDisposalCount: 12,
    weekHiddenTroubleDisposalRate: 80,
    weekHiddenTroubleRate: 1.0,
    momHiddenTroubleChangeRate: 20,
    areaHiddenTroubleControlRank: 3,
    weekAvgDisposalDuration: 4.5,
  },
  {
    areaName: '厦门市思明区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 2000,
    weekTotalHiddenTroubleCount: 10,
    weekDisposalCompleteCount: 10,
    weekAvgDeviceOnlineRate: 99.2,
    weekNewHiddenTroubleCount: 8,
    deptDisposalCount: 10,
    weekHiddenTroubleDisposalRate: 100,
    weekHiddenTroubleRate: 0.5,
    momHiddenTroubleChangeRate: -10,
    areaHiddenTroubleControlRank: 1,
    weekAvgDisposalDuration: 3.2,
  },
  {
    areaName: '泉州市丰泽区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 1800,
    weekTotalHiddenTroubleCount: 30,
    weekDisposalCompleteCount: 20,
    weekAvgDeviceOnlineRate: 85.3,
    weekNewHiddenTroubleCount: 25,
    deptDisposalCount: 20,
    weekHiddenTroubleDisposalRate: 66.67,
    weekHiddenTroubleRate: 1.67,
    momHiddenTroubleChangeRate: 30,
    areaHiddenTroubleControlRank: 8,
    weekAvgDisposalDuration: 6.8,
  },
  {
    areaName: '漳州市芗城区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 1200,
    weekTotalHiddenTroubleCount: 5,
    weekDisposalCompleteCount: 5,
    weekAvgDeviceOnlineRate: 99,
    weekNewHiddenTroubleCount: 3,
    deptDisposalCount: 5,
    weekHiddenTroubleDisposalRate: 100,
    weekHiddenTroubleRate: 0.42,
    momHiddenTroubleChangeRate: -20,
    areaHiddenTroubleControlRank: 2,
    weekAvgDisposalDuration: 2.5,
  },
  {
    areaName: '莆田市城厢区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 1600,
    weekTotalHiddenTroubleCount: 25,
    weekDisposalCompleteCount: 18,
    weekAvgDeviceOnlineRate: 78.6,
    weekNewHiddenTroubleCount: 20,
    deptDisposalCount: 18,
    weekHiddenTroubleDisposalRate: 72,
    weekHiddenTroubleRate: 1.56,
    momHiddenTroubleChangeRate: 25,
    areaHiddenTroubleControlRank: 7,
    weekAvgDisposalDuration: 5.2,
  },
  {
    areaName: '宁德市蕉城区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 1400,
    weekTotalHiddenTroubleCount: 8,
    weekDisposalCompleteCount: 8,
    weekAvgDeviceOnlineRate: 97.8,
    weekNewHiddenTroubleCount: 6,
    deptDisposalCount: 8,
    weekHiddenTroubleDisposalRate: 100,
    weekHiddenTroubleRate: 0.57,
    momHiddenTroubleChangeRate: -5,
    areaHiddenTroubleControlRank: 4,
    weekAvgDisposalDuration: 3.8,
  },
  {
    areaName: '龙岩市新罗区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 1700,
    weekTotalHiddenTroubleCount: 20,
    weekDisposalCompleteCount: 15,
    weekAvgDeviceOnlineRate: 96.5,
    weekNewHiddenTroubleCount: 18,
    deptDisposalCount: 15,
    weekHiddenTroubleDisposalRate: 75,
    weekHiddenTroubleRate: 1.18,
    momHiddenTroubleChangeRate: 15,
    areaHiddenTroubleControlRank: 5,
    weekAvgDisposalDuration: 4.8,
  },
  {
    areaName: '三明市梅列区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 1300,
    weekTotalHiddenTroubleCount: 3,
    weekDisposalCompleteCount: 3,
    weekAvgDeviceOnlineRate: 98.9,
    weekNewHiddenTroubleCount: 2,
    deptDisposalCount: 3,
    weekHiddenTroubleDisposalRate: 100,
    weekHiddenTroubleRate: 0.23,
    momHiddenTroubleChangeRate: -30,
    areaHiddenTroubleControlRank: 1,
    weekAvgDisposalDuration: 2.2,
  },
  {
    areaName: '南平市延平区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 1500,
    weekTotalHiddenTroubleCount: 18,
    weekDisposalCompleteCount: 12,
    weekAvgDeviceOnlineRate: 88.7,
    weekNewHiddenTroubleCount: 15,
    deptDisposalCount: 12,
    weekHiddenTroubleDisposalRate: 66.67,
    weekHiddenTroubleRate: 1.2,
    momHiddenTroubleChangeRate: 10,
    areaHiddenTroubleControlRank: 6,
    weekAvgDisposalDuration: 5.5,
  },
  {
    areaName: '平潭综合实验区',
    weekStatisticsPeriod: '2024年第25周（06-17 至 06-23）',
    manholeTotalCount: 1100,
    weekTotalHiddenTroubleCount: 4,
    weekDisposalCompleteCount: 4,
    weekAvgDeviceOnlineRate: 99.5,
    weekNewHiddenTroubleCount: 3,
    deptDisposalCount: 4,
    weekHiddenTroubleDisposalRate: 100,
    weekHiddenTroubleRate: 0.36,
    momHiddenTroubleChangeRate: -15,
    areaHiddenTroubleControlRank: 3,
    weekAvgDisposalDuration: 3.0,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 窨井盖设施监测周报表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'areaName',
      label: '所属区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入所属区域',
      },
      labelWidth: '120',
    },
    {
      fieldName: 'weekStatisticsPeriod',
      label: '周统计时段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入周统计时段（如：2024年第25周）',
        maxlength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 周统计时段为必填项
    },
  ];
}

/** 表格字段 - 窨井盖设施监测周报表格列 */
export function useGridColumns() {
  return [
    {
      field: 'areaName',
      title: '所属区域',
      minWidth: 180,
      sortable: true,
      slots: { default: 'areaName' },
    },
    {
      field: 'weekStatisticsPeriod',
      title: '周统计时段',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'manholeTotalCount',
      title: '窨井盖总数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'weekTotalHiddenTroubleCount',
      title: '周累计隐患数',
      minWidth: 140,
      sortable: true,
      slots: { default: 'weekTotalHiddenTroubleCount' },
    },
    {
      field: 'weekDisposalCompleteCount',
      title: '周处置完成数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'weekAvgDeviceOnlineRate',
      title: '周平均设备在线率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'weekNewHiddenTroubleCount',
      title: '周新增隐患数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'deptDisposalCount',
      title: '责任单位处置量',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'weekHiddenTroubleDisposalRate',
      title: '周隐患处置完成率(%)',
      minWidth: 160,
      sortable: true,
      slots: { default: 'weekHiddenTroubleDisposalRate' },
    },
    {
      field: 'weekHiddenTroubleRate',
      title: '周隐患发生率(%)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'momHiddenTroubleChangeRate',
      title: '环比隐患变化率(%)',
      minWidth: 160,
      sortable: true,
      slots: { default: 'momHiddenTroubleChangeRate' },
    },
    {
      field: 'areaHiddenTroubleControlRank',
      title: '区域隐患管控排名',
      minWidth: 160,
      sortable: true,
      slots: { default: 'areaHiddenTroubleControlRank' },
    },
    {
      field: 'weekAvgDisposalDuration',
      title: '周平均处置时长(小时)',
      minWidth: 160,
      sortable: true,
    },
    {
      title: '操作',
      width: 240,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
