/** 表格初始数据 - 改造为道路监测月度统计分析数据 */
export const dataList = () => [
  {
    roadSectionName: '福州市鼓楼区杨桥东路（东街口-五一广场）',
    areaName: '福州市鼓楼区',
    potholeCountMonthAvg: 5.8,
    crackLengthMonthAvg: 9.6,
    monthTotalWarningCount: 25,
    monthWorkOrderCount: 18,
    monthDisposalComplianceRate: 91.5,
    deviceMonthOnlineRate: 97.8,
    potholeCountMomChangeRate: 8.2,
    potholeCountYoYChangeRate: 13,
    crackLengthMomChangeRate: -3.5,
    crackLengthYoYChangeRate: 6.2,
    areaFacilityHealthRank: 3,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 8.5,
  },
  {
    roadSectionName: '厦门市思明区鹭江道（轮渡码头-中山路）',
    areaName: '厦门市思明区',
    potholeCountMonthAvg: 2.5,
    crackLengthMonthAvg: 3.8,
    monthTotalWarningCount: 11,
    monthWorkOrderCount: 8,
    monthDisposalComplianceRate: 98.5,
    deviceMonthOnlineRate: 99.2,
    potholeCountMomChangeRate: -5,
    potholeCountYoYChangeRate: -8.5,
    crackLengthMomChangeRate: 2.3,
    crackLengthYoYChangeRate: -1.8,
    areaFacilityHealthRank: 1,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 4.2,
  },
  {
    roadSectionName: '泉州市丰泽区刺桐路（湖心街-泉秀街）',
    areaName: '泉州市丰泽区',
    potholeCountMonthAvg: 12.1,
    crackLengthMonthAvg: 18.5,
    monthTotalWarningCount: 48,
    monthWorkOrderCount: 40,
    monthDisposalComplianceRate: 74.5,
    deviceMonthOnlineRate: 87.2,
    potholeCountMomChangeRate: 25,
    potholeCountYoYChangeRate: 31.5,
    crackLengthMomChangeRate: 19.8,
    crackLengthYoYChangeRate: 23,
    areaFacilityHealthRank: 9,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 22.8,
  },
  {
    roadSectionName: '漳州市芗城区胜利路（延安北路-新华西路）',
    areaName: '漳州市芗城区',
    potholeCountMonthAvg: 0.5,
    crackLengthMonthAvg: 1.5,
    monthTotalWarningCount: 0,
    monthWorkOrderCount: 0,
    monthDisposalComplianceRate: 100,
    deviceMonthOnlineRate: 98.9,
    potholeCountMomChangeRate: -10,
    potholeCountYoYChangeRate: -15.5,
    crackLengthMomChangeRate: -8.2,
    crackLengthYoYChangeRate: -11,
    areaFacilityHealthRank: 2,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 0,
  },
  {
    roadSectionName: '莆田市城厢区荔城南大道（凤凰山-万达广场）',
    areaName: '莆田市城厢区',
    potholeCountMonthAvg: 8.2,
    crackLengthMonthAvg: 14.8,
    monthTotalWarningCount: 32,
    monthWorkOrderCount: 28,
    monthDisposalComplianceRate: 82,
    deviceMonthOnlineRate: 78.8,
    potholeCountMomChangeRate: 12.5,
    potholeCountYoYChangeRate: 19,
    crackLengthMomChangeRate: 11,
    crackLengthYoYChangeRate: 15.8,
    areaFacilityHealthRank: 7,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 15.6,
  },
  {
    roadSectionName: '宁德市蕉城区闽东中路（市政府-万达广场）',
    areaName: '宁德市蕉城区',
    potholeCountMonthAvg: 5.3,
    crackLengthMonthAvg: 8.2,
    monthTotalWarningCount: 15,
    monthWorkOrderCount: 12,
    monthDisposalComplianceRate: 94.5,
    deviceMonthOnlineRate: 97.5,
    potholeCountMomChangeRate: 5.5,
    potholeCountYoYChangeRate: 9.2,
    crackLengthMomChangeRate: -1.8,
    crackLengthYoYChangeRate: 2.5,
    areaFacilityHealthRank: 4,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 7.8,
  },
  {
    roadSectionName: '龙岩市新罗区龙川路（中山路-登高西路）',
    areaName: '龙岩市新罗区',
    potholeCountMonthAvg: 10.1,
    crackLengthMonthAvg: 15,
    monthTotalWarningCount: 38,
    monthWorkOrderCount: 32,
    monthDisposalComplianceRate: 87.5,
    deviceMonthOnlineRate: 96.8,
    potholeCountMomChangeRate: 19.5,
    potholeCountYoYChangeRate: 26,
    crackLengthMomChangeRate: 13.5,
    crackLengthYoYChangeRate: 19.2,
    areaFacilityHealthRank: 6,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 12.3,
  },
  {
    roadSectionName: '三明市梅列区列东街（东新四路-东新六路）',
    areaName: '三明市梅列区',
    potholeCountMonthAvg: 4.5,
    crackLengthMonthAvg: 6.8,
    monthTotalWarningCount: 8,
    monthWorkOrderCount: 6,
    monthDisposalComplianceRate: 99,
    deviceMonthOnlineRate: 98.5,
    potholeCountMomChangeRate: -4.5,
    potholeCountYoYChangeRate: -7,
    crackLengthMomChangeRate: -5.5,
    crackLengthYoYChangeRate: -8.8,
    areaFacilityHealthRank: 5,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 5.1,
  },
  {
    roadSectionName: '南平市延平区八一路（江滨路-中山路）',
    areaName: '南平市延平区',
    potholeCountMonthAvg: 7.5,
    crackLengthMonthAvg: 11.5,
    monthTotalWarningCount: 28,
    monthWorkOrderCount: 24,
    monthDisposalComplianceRate: 78,
    deviceMonthOnlineRate: 89,
    potholeCountMomChangeRate: 10.8,
    potholeCountYoYChangeRate: 16.5,
    crackLengthMomChangeRate: 8.2,
    crackLengthYoYChangeRate: 12,
    areaFacilityHealthRank: 8,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 18.5,
  },
  {
    roadSectionName: '平潭综合实验区金井大道（管委会-龙凤头沙滩）',
    areaName: '平潭综合实验区',
    potholeCountMonthAvg: 1.2,
    crackLengthMonthAvg: 3.2,
    monthTotalWarningCount: 14,
    monthWorkOrderCount: 10,
    monthDisposalComplianceRate: 98.8,
    deviceMonthOnlineRate: 99.6,
    potholeCountMomChangeRate: -3,
    potholeCountYoYChangeRate: -6,
    crackLengthMomChangeRate: 4.5,
    crackLengthYoYChangeRate: 2,
    areaFacilityHealthRank: 10,
    monthStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
    avgDisposalDuration: 6.8,
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为道路监测月度统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'roadSectionName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
      },
      labelWidth: '140',
      rules: 'required', // 路段名称为必填项
    },
    {
      fieldName: 'areaName',
      label: '区域名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称（如：福州市鼓楼区）',
      },
      labelWidth: '140',
      rules: 'required',
    },
    {
      fieldName: 'potholeCountMonthAvg',
      label: '坑洼数量月均值',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入坑洼数量月均值',
        min: 0,
        precision: 1, // 保留1位小数，贴合月均值统计场景
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthMonthAvg',
      label: '裂缝长度月均值',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入裂缝长度月均值（单位：米）',
        min: 0,
        precision: 1,
        addonAfter: '米',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthTotalWarningCount',
      label: '月累计预警数',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入月累计预警数',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthWorkOrderCount',
      label: '月工单量',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入月工单量',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthDisposalComplianceRate',
      label: '月处置达标率',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入月处置达标率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceMonthOnlineRate',
      label: '设备月在线率',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入设备月在线率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountMomChangeRate',
      label: '坑洼数量环比变化率',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入坑洼数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountYoYChangeRate',
      label: '坑洼数量同比变化率',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入坑洼数量同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthMomChangeRate',
      label: '裂缝长度环比变化率',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入裂缝长度环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthYoYChangeRate',
      label: '裂缝长度同比变化率',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入裂缝长度同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'areaFacilityHealthRank',
      label: '区域设施健康度排名',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入区域设施健康度排名',
        min: 1,
        precision: 0,
        addonAfter: '名',
      },
      rules: 'required',
    },
    {
      fieldName: 'monthStatisticsPeriod',
      label: '月统计时段',
      component: 'Input',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入月统计时段（如：2024-06-01 ~ 2024-06-30）',
        maxlength: 50,
      },
      rules: 'required',
    },
    {
      fieldName: 'avgDisposalDuration',
      label: '平均处置时长',
      component: 'InputNumber',
      labelWidth: '140',
      componentProps: {
        placeholder: '请输入平均处置时长（单位：小时）',
        min: 0,
        precision: 1,
        addonAfter: '小时',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为道路监测月度统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'roadSectionName',
      title: '路段名称',
      minWidth: 220,
      sortable: true,
      slots: { default: 'roadSectionName' },
    },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'potholeCountMonthAvg',
      title: '坑洼数量月均值',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'crackLengthMonthAvg',
      title: '裂缝长度月均值(米)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'monthTotalWarningCount',
      title: '月累计预警数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'monthWorkOrderCount',
      title: '月工单量',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monthDisposalComplianceRate',
      title: '月处置达标率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'deviceMonthOnlineRate',
      title: '设备月在线率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'potholeCountMomChangeRate',
      title: '坑洼数量环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'potholeCountYoYChangeRate',
      title: '坑洼数量同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'crackLengthMomChangeRate',
      title: '裂缝长度环比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'crackLengthYoYChangeRate',
      title: '裂缝长度同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'areaFacilityHealthRank',
      title: '区域设施健康度排名',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'monthStatisticsPeriod',
      title: '月统计时段',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'avgDisposalDuration',
      title: '平均处置时长(小时)',
      minWidth: 160,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
