// data.js
/** 表格初始数据 - 审批数据 */
export const dataList = () => {
  return [
    {
      id: 1,
      approveTitle: '服务器采购审批-01',
      businessType: '采购审批',
      applicant: '张三',
      applicantDept: '运维部',
      applyTime: '2026-01-20 09:30',
      deadline: '2026-01-23 18:00',
      emergencyDegree: '高',
      attachmentCount: 3,
      approveId: 'APPROVE-20260120-001',
      businessId: 'ASSET-20260120-001',
      approveNode: '部门主管审批',
      approveResult: '',
      approveTime: '',
      opinion: '',
      businessName: '服务器集群-A采购',
      approveFlow: '部门主管→总监→财务',
      businessStatus: '待处理',
      currentNode: '部门主管审批',
      approver: '李四',
      approveStatus: '待审批',
      rejectReason: '',
      submitCount: 1,
      latestDynamic: '已提交至部门主管',
      copyTitle: '服务器采购审批-01',
      copyTime: '2026-01-20 09:35',
      flowSummary: '张三发起服务器采购申请，已提交至部门主管审批',
      copyId: 'COPY-20260120-001',
      copyStatus: '未读',
      moduleType: 'waiting', // 待我审批
      assignTime: '2026-01-20 09:30',
      description: '采购5台服务器用于机房扩容',
      taskType: '采购审批',
      priority: '高',
      taskName: '服务器采购审批-01',
      taskStatus: '待审批',
      currentProgress: '部门主管审批',
      relatedResource: '服务器采购合同',
      initiator: '张三',
      operator: '李四',
      createTime: '2026-01-20 09:00',
    },
    {
      id: 2,
      approveTitle: '数据库迁移审批',
      businessType: '变更审批',
      applicant: '王五',
      applicantDept: '开发部',
      applyTime: '2026-01-21 14:00',
      deadline: '2026-01-25 17:00',
      emergencyDegree: '中',
      attachmentCount: 2,
      approveId: 'APPROVE-20260121-002',
      businessId: 'CHANGE-20260121-001',
      approveNode: '运维经理审批',
      approveResult: '同意',
      approveTime: '2026-01-22 10:30',
      opinion: '方案合理，同意执行',
      businessName: 'MySQL数据库迁移',
      approveFlow: '开发主管→运维经理',
      businessStatus: '已生效',
      currentNode: '已完成',
      approver: '赵六',
      approveStatus: '已完成',
      rejectReason: '',
      submitCount: 1,
      latestDynamic: '运维经理已审批通过',
      copyTitle: '数据库迁移审批',
      copyTime: '2026-01-22 10:35',
      flowSummary: '数据库迁移申请已通过，进入执行阶段',
      copyId: 'COPY-20260121-001',
      copyStatus: '已读',
      moduleType: 'approved', // 我已审批
      assignTime: '2026-01-21 14:00',
      description: '将生产数据库迁移至新服务器',
      taskType: '变更审批',
      priority: '中',
      taskName: '数据库迁移审批',
      taskStatus: '已完成',
      currentProgress: '100%',
      relatedResource: '迁移方案',
      initiator: '王五',
      operator: '赵六',
      createTime: '2026-01-21 13:30',
    },
    {
      id: 3,
      approveTitle: '年度预算审批',
      businessType: '财务审批',
      applicant: '孙八',
      applicantDept: '财务部',
      applyTime: '2026-01-19 10:00',
      deadline: '2026-01-22 12:00',
      emergencyDegree: '低',
      attachmentCount: 5,
      approveId: 'APPROVE-20260119-003',
      businessId: 'BUDGET-20260119-001',
      approveNode: '总监审批',
      approveResult: '',
      approveTime: '',
      opinion: '',
      businessName: '2026年度IT预算',
      approveFlow: '财务主管→总监→CEO',
      businessStatus: '审批中',
      currentNode: '总监审批',
      approver: '钱七',
      approveStatus: '处理中',
      rejectReason: '',
      submitCount: 2,
      latestDynamic: '财务主管已通过，等待总监审批',
      copyTitle: '年度预算审批',
      copyTime: '2026-01-19 10:30',
      flowSummary: '年度预算申请已进入总监审批环节',
      copyId: 'COPY-20260119-001',
      copyStatus: '未读',
      moduleType: 'myApply', // 我发起的
      assignTime: '2026-01-19 10:00',
      description: '2026年度IT部门预算申请',
      taskType: '财务审批',
      priority: '低',
      taskName: '年度预算审批',
      taskStatus: '处理中',
      currentProgress: '50%',
      relatedResource: '预算明细表',
      initiator: '孙八',
      operator: '孙八',
      createTime: '2026-01-19 09:30',
    },
    {
      id: 4,
      approveTitle: '系统上线审批',
      businessType: '上线审批',
      applicant: '李四',
      applicantDept: '产品部',
      applyTime: '2026-01-18 13:00',
      deadline: '2026-01-24 20:00',
      emergencyDegree: '紧急',
      attachmentCount: 4,
      approveId: 'APPROVE-20260118-004',
      businessId: 'RELEASE-20260118-001',
      approveNode: '测试经理审批',
      approveResult: '驳回',
      approveTime: '2026-01-22 16:30',
      opinion: '测试覆盖率不足，请补充测试用例',
      businessName: '订单系统V2.0上线',
      approveFlow: '测试→运维→产品',
      businessStatus: '已驳回',
      currentNode: '已驳回',
      approver: '吴九',
      approveStatus: '已驳回',
      rejectReason: '测试覆盖率不足',
      submitCount: 1,
      latestDynamic: '被测试经理驳回，需要补充测试',
      copyTitle: '系统上线审批',
      copyTime: '2026-01-22 16:35',
      flowSummary: '系统上线申请被驳回，需补充测试',
      copyId: 'COPY-20260118-001',
      copyStatus: '未读',
      moduleType: 'copy', // 抄送我的
      assignTime: '2026-01-18 13:00',
      description: '订单系统V2.0版本上线申请',
      taskType: '上线审批',
      priority: '紧急',
      taskName: '系统上线审批',
      taskStatus: '已驳回',
      currentProgress: '已驳回',
      relatedResource: '测试报告',
      initiator: '李四',
      operator: '吴九',
      createTime: '2026-01-18 12:30',
    },
    // ... 继续添加更多数据，确保每个模块都有足够的数据
    {
      id: 5,
      approveTitle: '人员招聘审批',
      businessType: '人事审批',
      applicant: '郑十',
      applicantDept: '人力资源部',
      applyTime: '2026-01-22 08:30',
      deadline: '2026-01-23 12:00',
      emergencyDegree: '紧急',
      attachmentCount: 2,
      approveId: 'APPROVE-20260122-005',
      businessId: 'HR-20260122-001',
      approveNode: '部门总监审批',
      approveResult: '',
      approveTime: '',
      opinion: '',
      businessName: '高级运维工程师招聘',
      approveFlow: 'HR→部门总监',
      businessStatus: '待处理',
      currentNode: '部门总监审批',
      approver: '周五',
      approveStatus: '待审批',
      rejectReason: '',
      submitCount: 1,
      latestDynamic: 'HR已提交，等待总监审批',
      copyTitle: '人员招聘审批',
      copyTime: '2026-01-22 08:45',
      flowSummary: '高级运维工程师招聘申请',
      copyId: 'COPY-20260122-001',
      copyStatus: '未读',
      moduleType: 'waiting',
      assignTime: '2026-01-22 08:30',
      description: '招聘一名高级运维工程师',
      taskType: '人事审批',
      priority: '紧急',
      taskName: '人员招聘审批',
      taskStatus: '待审批',
      currentProgress: '部门总监审批',
      relatedResource: '岗位说明书',
      initiator: '郑十',
      operator: '周五',
      createTime: '2026-01-22 08:00',
    },
    // 添加更多数据，总共50条，每个模块分配一定数量
    {
      id: 6,
      approveTitle: '软件采购审批',
      businessType: '采购审批',
      applicant: '张三',
      applicantDept: '运维部',
      applyTime: '2026-01-20 09:30',
      deadline: '2026-01-25 17:00',
      emergencyDegree: '中',
      attachmentCount: 1,
      approveId: 'APPROVE-20260120-006',
      businessId: 'SOFTWARE-20260120-001',
      approveNode: '已完成',
      approveResult: '同意',
      approveTime: '2026-01-22 14:00',
      opinion: '软件符合需求，价格合理',
      businessName: '监控软件采购',
      approveFlow: '部门主管→财务',
      businessStatus: '已生效',
      currentNode: '已完成',
      approver: '李四',
      approveStatus: '已完成',
      rejectReason: '',
      submitCount: 1,
      latestDynamic: '审批已完成，进入采购流程',
      copyTitle: '软件采购审批',
      copyTime: '2026-01-22 14:05',
      flowSummary: '监控软件采购已审批通过',
      copyId: 'COPY-20260120-002',
      copyStatus: '已读',
      moduleType: 'approved',
      assignTime: '2026-01-20 09:30',
      description: '采购Zabbix监控软件许可',
      taskType: '采购审批',
      priority: '中',
      taskName: '软件采购审批',
      taskStatus: '已完成',
      currentProgress: '100%',
      relatedResource: '软件报价单',
      initiator: '张三',
      operator: '李四',
      createTime: '2026-01-20 09:15',
    },
    {
      id: 7,
      approveTitle: '机房访问权限申请',
      businessType: '权限审批',
      applicant: '李四',
      applicantDept: '运维部',
      applyTime: '2026-01-15 10:00',
      deadline: '2026-01-25 17:00',
      emergencyDegree: '中',
      attachmentCount: 0,
      approveId: 'APPROVE-20260115-007',
      businessId: 'ACCESS-20260115-001',
      approveNode: '运维主管审批',
      approveResult: '',
      approveTime: '',
      opinion: '',
      businessName: '机房临时访问权限',
      approveFlow: '运维主管→安全',
      businessStatus: '审批中',
      currentNode: '运维主管审批',
      approver: '王五',
      approveStatus: '处理中',
      rejectReason: '',
      submitCount: 1,
      latestDynamic: '已提交至运维主管',
      copyTitle: '机房访问权限申请',
      copyTime: '2026-01-15 10:15',
      flowSummary: '机房临时访问权限申请',
      copyId: 'COPY-20260115-001',
      copyStatus: '未读',
      moduleType: 'myApply',
      assignTime: '',
      description: '申请临时访问机房权限',
      taskType: '权限审批',
      priority: '中',
      taskName: '机房访问权限申请',
      taskStatus: '处理中',
      currentProgress: '30%',
      relatedResource: '安全承诺书',
      initiator: '李四',
      operator: '李四',
      createTime: '2026-01-15 10:00',
    },
    {
      id: 8,
      approveTitle: '会议设备采购审批',
      businessType: '采购审批',
      applicant: '赵六',
      applicantDept: '行政部',
      applyTime: '2026-01-22 09:00',
      deadline: '2026-01-22 12:00',
      emergencyDegree: '低',
      attachmentCount: 2,
      approveId: 'APPROVE-20260122-008',
      businessId: 'EQUIPMENT-20260122-001',
      approveNode: '已完成',
      approveResult: '同意',
      approveTime: '2026-01-22 11:00',
      opinion: '采购必要，符合预算',
      businessName: '会议室音视频设备',
      approveFlow: '行政主管→财务',
      businessStatus: '已生效',
      currentNode: '已完成',
      approver: '吴九',
      approveStatus: '已完成',
      rejectReason: '',
      submitCount: 1,
      latestDynamic: '审批完成，进入采购执行',
      copyTitle: '会议设备采购审批',
      copyTime: '2026-01-22 11:05',
      flowSummary: '会议室设备采购已审批通过',
      copyId: 'COPY-20260122-002',
      copyStatus: '已读',
      moduleType: 'copy',
      assignTime: '2026-01-22 09:00',
      description: '采购301会议室音视频设备',
      taskType: '采购审批',
      priority: '低',
      taskName: '会议设备采购审批',
      taskStatus: '已完成',
      currentProgress: '100%',
      relatedResource: '设备清单',
      initiator: '',
      operator: '吴九',
      createTime: '2026-01-22 08:45',
    },
    // ... 继续添加数据直到50条
  ];
};

/** 新增/修改的表单/列表的搜索表单 - 根据模块类型返回不同表单 */
export function useFormSchema(moduleType = 'waiting') {
  const baseSchema = [
    {
      fieldName: 'approveTitle',
      label: '审批标题',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入审批标题',
      },
      rules: 'required',
    },
  ];

  switch (moduleType) {
    case 'waiting': // 待我审批
      return [
        ...baseSchema,
        {
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            allowClear: true,
            filterOption: true,
            options: [
              { label: '采购审批', value: '采购审批' },
              { label: '变更审批', value: '变更审批' },
              { label: '上线审批', value: '上线审批' },
              { label: '人事审批', value: '人事审批' },
              { label: '权限审批', value: '权限审批' },
              { label: '财务审批', value: '财务审批' },
              { label: '其他', value: '其他' },
            ],
            placeholder: '请选择业务类型',
            showSearch: true,
          },
          fieldName: 'businessType',
          label: '业务类型',
        },
        {
          fieldName: 'applicant',
          label: '申请人',
          component: 'Input',
          labelWidth: '100',
          componentProps: {
            placeholder: '请输入申请人',
          },
        },
        {
          fieldName: 'applyTime',
          label: '申请时间',
          component: 'DatePicker',
          labelWidth: '100',
          componentProps: {
            type: 'daterange',
            placeholder: '请选择申请时间范围',
          },
        },
        {
          fieldName: 'emergencyDegree',
          label: '紧急程度',
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            options: [
              { label: '紧急', value: '紧急' },
              { label: '高', value: '高' },
              { label: '中', value: '中' },
              { label: '低', value: '低' },
            ],
            placeholder: '请选择紧急程度',
          },
        },
        {
          fieldName: 'deadline',
          label: '截止审批时间',
          component: 'DatePicker',
          labelWidth: '100',
          componentProps: {
            type: 'daterange',
            placeholder: '请选择截止时间范围',
          },
        },
      ];

    case 'approved': // 我已审批
      return [
        ...baseSchema,
        {
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            allowClear: true,
            filterOption: true,
            options: [
              { label: '采购审批', value: '采购审批' },
              { label: '变更审批', value: '变更审批' },
              { label: '上线审批', value: '上线审批' },
              { label: '人事审批', value: '人事审批' },
              { label: '权限审批', value: '权限审批' },
              { label: '财务审批', value: '财务审批' },
              { label: '其他', value: '其他' },
            ],
            placeholder: '请选择业务类型',
            showSearch: true,
          },
          fieldName: 'businessType',
          label: '业务类型',
        },
        {
          fieldName: 'approveResult',
          label: '审批结果',
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            options: [
              { label: '同意', value: '同意' },
              { label: '驳回', value: '驳回' },
            ],
            placeholder: '请选择审批结果',
          },
        },
        {
          fieldName: 'applyTime',
          label: '申请时间',
          component: 'DatePicker',
          labelWidth: '100',
          componentProps: {
            type: 'daterange',
            placeholder: '请选择申请时间范围',
          },
        },
        {
          fieldName: 'approveTime',
          label: '审批时间',
          component: 'DatePicker',
          labelWidth: '100',
          componentProps: {
            type: 'daterange',
            placeholder: '请选择审批时间范围',
          },
        },
        {
          fieldName: 'applicant',
          label: '申请人',
          component: 'Input',
          labelWidth: '100',
          componentProps: {
            placeholder: '请输入申请人',
          },
        },
      ];

    case 'myApply': // 我发起的
      return [
        ...baseSchema,
        {
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            allowClear: true,
            filterOption: true,
            options: [
              { label: '采购审批', value: '采购审批' },
              { label: '变更审批', value: '变更审批' },
              { label: '上线审批', value: '上线审批' },
              { label: '人事审批', value: '人事审批' },
              { label: '权限审批', value: '权限审批' },
              { label: '财务审批', value: '财务审批' },
              { label: '其他', value: '其他' },
            ],
            placeholder: '请选择业务类型',
            showSearch: true,
          },
          fieldName: 'businessType',
          label: '业务类型',
        },
        {
          fieldName: 'approveStatus',
          label: '审批状态',
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            options: [
              { label: '待审批', value: '待审批' },
              { label: '处理中', value: '处理中' },
              { label: '已完成', value: '已完成' },
              { label: '已驳回', value: '已驳回' },
              { label: '已撤回', value: '已撤回' },
            ],
            placeholder: '请选择审批状态',
          },
        },
        {
          fieldName: 'applyTime',
          label: '申请时间',
          component: 'DatePicker',
          labelWidth: '100',
          componentProps: {
            type: 'daterange',
            placeholder: '请选择申请时间范围',
          },
        },
        {
          fieldName: 'currentNode',
          label: '当前节点',
          component: 'Input',
          labelWidth: '100',
          componentProps: {
            placeholder: '请输入当前节点',
          },
        },
      ];

    case 'copy': // 抄送我的
      return [
        ...baseSchema,
        {
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            allowClear: true,
            filterOption: true,
            options: [
              { label: '采购审批', value: '采购审批' },
              { label: '变更审批', value: '变更审批' },
              { label: '上线审批', value: '上线审批' },
              { label: '人事审批', value: '人事审批' },
              { label: '权限审批', value: '权限审批' },
              { label: '财务审批', value: '财务审批' },
              { label: '其他', value: '其他' },
            ],
            placeholder: '请选择审批类型',
            showSearch: true,
          },
          fieldName: 'businessType',
          label: '审批类型',
        },
        {
          fieldName: 'copyTime',
          label: '抄送时间',
          component: 'DatePicker',
          labelWidth: '100',
          componentProps: {
            type: 'daterange',
            placeholder: '请选择抄送时间范围',
          },
        },
        {
          fieldName: 'approveStatus',
          label: '审批状态',
          component: 'Select',
          labelWidth: '100',
          componentProps: {
            options: [
              { label: '待审批', value: '待审批' },
              { label: '处理中', value: '处理中' },
              { label: '已完成', value: '已完成' },
              { label: '已驳回', value: '已驳回' },
            ],
            placeholder: '请选择审批状态',
          },
        },
        {
          fieldName: 'applicant',
          label: '申请人',
          component: 'Input',
          labelWidth: '100',
          componentProps: {
            placeholder: '请输入申请人',
          },
        },
      ];

    default:
      return baseSchema;
  }
}

/** 表格字段 - 根据模块类型返回不同列配置 */
export function useGridColumns(moduleType = 'waiting') {
  const baseColumns = [
    { type: 'checkbox', width: 40 },
    {
      field: 'approveTitle',
      title: '审批标题',
      minWidth: 200,
      sortable: true,
      slots: { default: 'approveTitle' },
    },
  ];

  switch (moduleType) {
    case 'waiting': // 待我审批
      return [
        ...baseColumns,
        {
          field: 'businessType',
          title: '业务类型',
          minWidth: 100,
          sortable: true,
          slots: { default: 'businessType' },
        },
        {
          field: 'applicant',
          title: '申请人',
          minWidth: 100,
          sortable: true,
          slots: { default: 'applicant' },
        },
        {
          field: 'applyTime',
          title: '申请时间',
          minWidth: 160,
          sortable: true,
        },
        {
          field: 'emergencyDegree',
          title: '紧急程度',
          minWidth: 100,
          sortable: true,
          slots: { default: 'emergencyDegree' },
        },
        {
          field: 'deadline',
          title: '截止审批时间',
          minWidth: 160,
          sortable: true,
        },
        {
          field: 'attachmentCount',
          title: '附件数量',
          minWidth: 100,
          slots: { default: 'attachmentCount' },
        },
        {
          title: '操作',
          width: 250,
          fixed: 'right',
          slots: { default: 'waitingActions' },
        },
      ];

    case 'approved': // 我已审批
      return [
        ...baseColumns,
        {
          field: 'businessType',
          title: '业务类型',
          minWidth: 100,
          sortable: true,
          slots: { default: 'businessType' },
        },
        {
          field: 'applicant',
          title: '申请人',
          minWidth: 100,
          sortable: true,
          slots: { default: 'applicant' },
        },
        {
          field: 'applyTime',
          title: '申请时间',
          minWidth: 160,
          sortable: true,
        },
        {
          field: 'approveResult',
          title: '审批结果',
          minWidth: 100,
          sortable: true,
          slots: { default: 'approveResult' },
        },
        {
          field: 'approveTime',
          title: '审批时间',
          minWidth: 160,
          sortable: true,
        },
        {
          field: 'opinion',
          title: '意见摘要',
          minWidth: 150,
          formatter: ({ cellValue }) =>
            cellValue
              ? cellValue.length > 30
                ? cellValue.substring(0, 30) + '...'
                : cellValue
              : '-',
        },
        {
          title: '操作',
          width: 250,
          fixed: 'right',
          slots: { default: 'approvedActions' },
        },
      ];

    case 'myApply': // 我发起的
      return [
        ...baseColumns,
        {
          field: 'businessType',
          title: '业务类型',
          minWidth: 100,
          sortable: true,
          slots: { default: 'businessType' },
        },
        {
          field: 'currentNode',
          title: '当前节点',
          minWidth: 120,
          sortable: true,
        },
        {
          field: 'approver',
          title: '审批人',
          minWidth: 100,
          sortable: true,
        },
        {
          field: 'applyTime',
          title: '提交时间',
          minWidth: 160,
          sortable: true,
        },
        {
          field: 'approveStatus',
          title: '审批状态',
          minWidth: 100,
          sortable: true,
          slots: { default: 'approveStatus' },
        },
        {
          title: '操作',
          width: 250,
          fixed: 'right',
          slots: { default: 'myApplyActions' },
        },
      ];

    case 'copy': // 抄送我的
      return [
        ...baseColumns,
        {
          field: 'businessType',
          title: '审批类型',
          minWidth: 100,
          sortable: true,
          slots: { default: 'businessType' },
        },
        {
          field: 'applicant',
          title: '申请人',
          minWidth: 100,
          sortable: true,
          slots: { default: 'applicant' },
        },
        {
          field: 'currentNode',
          title: '当前节点',
          minWidth: 120,
          sortable: true,
        },
        {
          field: 'copyTime',
          title: '抄送时间',
          minWidth: 160,
          sortable: true,
        },
        {
          field: 'flowSummary',
          title: '核心流转信息',
          minWidth: 180,
          formatter: ({ cellValue }) =>
            cellValue
              ? cellValue.length > 50
                ? cellValue.substring(0, 50) + '...'
                : cellValue
              : '-',
        },
        {
          field: 'copyStatus',
          title: '状态',
          minWidth: 80,
          slots: { default: 'copyStatus' },
        },
        {
          title: '操作',
          width: 200,
          fixed: 'right',
          slots: { default: 'copyActions' },
        },
      ];

    default:
      return baseColumns;
  }
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑审批',
  addText: '新增审批',
  excelName: '审批列表',
  excelAllName: '审批数据.xlsx',
  total:
    '审批总数: 50; 待我审批: 12; 我已审批: 15; 我发起的: 10; 抄送我的: 13;',
};
