/** 表格初始数据 - 改造为车辆运载监管统计分析数据 */
export const dataList = () => [
  {
    licensePlate: '闽A·12345',
    approvedLoad: 15.5,
    actualLoad: 14.8,
    sealStatusId: 's1',
    areaCode: '福建省福州市鼓楼区',
    lawEnforcerId: '张三',
    orderNo: 'ORD-20240617001',
  },
  {
    licensePlate: '闽D·67890',
    approvedLoad: 20.0,
    actualLoad: 19.2,
    sealStatusId: 's2',
    areaCode: '福建省厦门市思明区',
    lawEnforcerId: '李四',
    orderNo: 'ORD-20240617002',
  },
  {
    licensePlate: '闽C·11223',
    approvedLoad: 10.0,
    actualLoad: 9.6,
    sealStatusId: 's1',
    areaCode: '福建省泉州市丰泽区',
    lawEnforcerId: '王五',
    orderNo: 'ORD-20240617003',
  },
  {
    licensePlate: '闽E·44556',
    approvedLoad: 25.0,
    actualLoad: 26.5,
    sealStatusId: 's3',
    areaCode: '福建省漳州市芗城区',
    lawEnforcerId: '赵六',
    orderNo: 'ORD-20240617004',
  },
  {
    licensePlate: '闽B·77889',
    approvedLoad: 18.0,
    actualLoad: 17.8,
    sealStatusId: 's2',
    areaCode: '福建省莆田市城厢区',
    lawEnforcerId: '陈七',
    orderNo: 'ORD-20240617005',
  },
  {
    licensePlate: '闽F·99001',
    approvedLoad: 12.5,
    actualLoad: 12.0,
    sealStatusId: 's1',
    areaCode: '福建省龙岩市新罗区',
    lawEnforcerId: '刘八',
    orderNo: 'ORD-20240617006',
  },
  {
    licensePlate: '闽G·22334',
    approvedLoad: 22.0,
    actualLoad: 21.5,
    sealStatusId: 's2',
    areaCode: '福建省三明市三元区',
    lawEnforcerId: '周九',
    orderNo: 'ORD-20240617007',
  },
  {
    licensePlate: '闽H·55667',
    approvedLoad: 8.5,
    actualLoad: 7.9,
    sealStatusId: 's1',
    areaCode: '福建省南平市延平区',
    lawEnforcerId: '吴十',
    orderNo: 'ORD-20240617008',
  },
  {
    licensePlate: '闽J·88990',
    approvedLoad: 30.0,
    actualLoad: 29.2,
    sealStatusId: 's3',
    areaCode: '福建省宁德市蕉城区',
    lawEnforcerId: '郑甲',
    orderNo: 'ORD-20240617009',
  },
  {
    licensePlate: '闽K·99887',
    approvedLoad: 5.0,
    actualLoad: 4.5,
    sealStatusId: 's2',
    areaCode: '福建省福州市平潭县',
    lawEnforcerId: '孙乙',
    orderNo: 'ORD-20240617010',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为车辆运载监管统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'licensePlate',
      label: '车辆牌照',
      component: 'Input',
      componentProps: {
        placeholder: '请输入车辆牌照',
      },
      labelWidth: '130',
      rules: 'required', // 车辆牌照为必填项
    },
    {
      fieldName: 'approvedLoad',
      label: '核定载重',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入核定载重',
        min: 0,
        precision: 1,
        addonAfter: '吨',
      },
      rules: 'required',
    },
    {
      fieldName: 'actualLoad',
      label: '实际载重',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入实际载重',
        min: 0,
        precision: 1,
        addonAfter: '吨',
      },
      rules: 'required',
    },
    {
      fieldName: 'sealStatusId',
      label: '密闭状态',
      component: 'Select',
      labelWidth: '130',
      componentProps: {
        placeholder: '请选择密闭状态',
        options: [
          { label: '密闭良好', value: 's1' },
          { label: '轻微密闭不严', value: 's2' },
          { label: '严重密闭不严', value: 's3' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'areaCode',
      label: '所属片区',
      component: 'Select',
      labelWidth: '130',
      componentProps: {
        placeholder: '请选择所属片区',
        options: [
          { label: '福建省福州市鼓楼区', value: '福建省福州市鼓楼区' },
          { label: '福建省厦门市思明区', value: '福建省厦门市思明区' },
          { label: '福建省泉州市丰泽区', value: '福建省泉州市丰泽区' },
          { label: '福建省漳州市芗城区', value: '福建省漳州市芗城区' },
          { label: '福建省莆田市城厢区', value: '福建省莆田市城厢区' },
          { label: '福建省龙岩市新罗区', value: '福建省龙岩市新罗区' },
          { label: '福建省三明市三元区', value: '福建省三明市三元区' },
          { label: '福建省南平市延平区', value: '福建省南平市延平区' },
          { label: '福建省宁德市蕉城区', value: '福建省宁德市蕉城区' },
          { label: '福建省福州市平潭县', value: '福建省福州市平潭县' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'lawEnforcerId',
      label: '执法员',
      component: 'Select',
      labelWidth: '130',
      componentProps: {
        placeholder: '请选择执法员',
        options: [
          { label: '张三', value: '张三' },
          { label: '李四', value: '李四' },
          { label: '王五', value: '王五' },
          { label: '赵六', value: '赵六' },
          { label: '陈七', value: '陈七' },
          { label: '刘八', value: '刘八' },
          { label: '周九', value: '周九' },
          { label: '吴十', value: '吴十' },
          { label: '郑甲', value: '郑甲' },
          { label: '孙乙', value: '孙乙' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'orderNo',
      label: '工单编号',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入工单编号',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为车辆运载监管统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'licensePlate',
      title: '车辆牌照',
      minWidth: 130,
      sortable: true,
      slots: { default: 'licensePlate' },
    },
    {
      field: 'approvedLoad',
      title: '核定载重(吨)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'actualLoad',
      title: '实际载重(吨)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'sealStatusId',
      title: '密闭状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'sealStatusId' },
    },
    {
      field: 'areaCode',
      title: '所属片区',
      minWidth: 200,
      sortable: true,
      slots: { default: 'areaCode' },
    },
    {
      field: 'lawEnforcerId',
      title: '执法员',
      minWidth: 120,
      sortable: true,
      slots: { default: 'lawEnforcerId' },
    },
    {
      field: 'orderNo',
      title: '工单编号',
      minWidth: 170,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
