// data.js - 修改为商户月运营数据
/** 商户月运营数据报表 - 初始数据 */
export const dataList = () => {
  return [
    {
      "id": 1,
      "statMonth": "2026-02",
      "merchantName": "天河商贸中心",
      "areaName": "天河区",
      "lotName": "天河商贸停车场",
      "totalIncome": 862515.00,
      "totalOrder": 37500,
      "avgUtilization": "79.2%",
      "peakHourDistribution": "09:00-12:00(45%),14:00-18:00(35%)",
      "growthRate": "5.7%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 2,
      "statMonth": "2026-02",
      "merchantName": "越秀路侧停车公司",
      "areaName": "越秀区",
      "lotName": "越秀路侧停车区",
      "totalIncome": 470400.00,
      "totalOrder": 29400,
      "avgUtilization": "83.1%",
      "peakHourDistribution": "08:00-10:00(30%),17:00-19:00(40%)",
      "growthRate": "3.2%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 3,
      "statMonth": "2026-02",
      "merchantName": "海珠商业集团",
      "areaName": "海珠区",
      "lotName": "海珠购物中心停车场",
      "totalIncome": 759000.00,
      "totalOrder": 33000,
      "avgUtilization": "76.4%",
      "peakHourDistribution": "10:00-12:00(40%),15:00-19:00(38%)",
      "growthRate": "6.9%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 4,
      "statMonth": "2026-02",
      "merchantName": "白云物业管理公司",
      "areaName": "白云区",
      "lotName": "白云小区停车场",
      "totalIncome": 306000.00,
      "totalOrder": 25500,
      "avgUtilization": "69.8%",
      "peakHourDistribution": "07:00-09:00(35%),18:00-20:00(30%)",
      "growthRate": "2.1%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 5,
      "statMonth": "2026-02",
      "merchantName": "黄埔商业中心",
      "areaName": "黄埔区",
      "lotName": "黄埔商业停车场",
      "totalIncome": 634800.00,
      "totalOrder": 27600,
      "avgUtilization": "72.5%",
      "peakHourDistribution": "09:00-11:00(38%),16:00-18:00(32%)",
      "growthRate": "4.8%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 6,
      "statMonth": "2026-01",
      "merchantName": "天河商贸中心",
      "areaName": "天河区",
      "lotName": "天河商贸停车场",
      "totalIncome": 814200.00,
      "totalOrder": 35400,
      "avgUtilization": "77.6%",
      "peakHourDistribution": "09:00-12:00(43%),14:00-18:00(34%)",
      "growthRate": "4.2%",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 7,
      "statMonth": "2026-01",
      "merchantName": "越秀路侧停车公司",
      "areaName": "越秀区",
      "lotName": "越秀路侧停车区",
      "totalIncome": 456000.00,
      "totalOrder": 28500,
      "avgUtilization": "81.4%",
      "peakHourDistribution": "08:00-10:00(28%),17:00-19:00(38%)",
      "growthRate": "2.8%",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 8,
      "statMonth": "2025-12",
      "merchantName": "天河商贸中心",
      "areaName": "天河区",
      "lotName": "天河商贸停车场",
      "totalIncome": 910800.00,
      "totalOrder": 39600,
      "avgUtilization": "82.3%",
      "peakHourDistribution": "09:00-12:00(46%),14:00-18:00(36%)",
      "growthRate": "6.5%",
      "updateTime": "2025-12-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 9,
      "statMonth": "2025-11",
      "merchantName": "海珠商业集团",
      "areaName": "海珠区",
      "lotName": "海珠购物中心停车场",
      "totalIncome": 724500.00,
      "totalOrder": 31500,
      "avgUtilization": "74.8%",
      "peakHourDistribution": "10:00-12:00(38%),15:00-19:00(36%)",
      "growthRate": "5.9%",
      "updateTime": "2025-11-30 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 10,
      "statMonth": "2025-10",
      "merchantName": "天河商贸中心",
      "areaName": "天河区",
      "lotName": "天河商贸停车场",
      "totalIncome": 883200.00,
      "totalOrder": 38400,
      "avgUtilization": "80.4%",
      "peakHourDistribution": "09:00-12:00(44%),14:00-18:00(35%)",
      "growthRate": "5.2%",
      "updateTime": "2025-10-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 11,
      "statMonth": "2026-02",
      "merchantName": "荔湾停车服务公司",
      "areaName": "荔湾区",
      "lotName": "荔湾路侧停车区",
      "totalIncome": 427200.00,
      "totalOrder": 26700,
      "avgUtilization": "78.9%",
      "peakHourDistribution": "08:30-10:30(32%),17:30-19:30(36%)",
      "growthRate": "3.0%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 12,
      "statMonth": "2026-02",
      "merchantName": "番禺物业服务公司",
      "areaName": "番禺区",
      "lotName": "番禺小区停车场",
      "totalIncome": 280800.00,
      "totalOrder": 23400,
      "avgUtilization": "66.7%",
      "peakHourDistribution": "07:30-09:30(30%),18:30-20:30(28%)",
      "growthRate": "1.6%",
      "updateTime": "2026-02-05 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 13,
      "statMonth": "2026-01",
      "merchantName": "南沙商业开发公司",
      "areaName": "南沙区",
      "lotName": "南沙商业停车场",
      "totalIncome": 469200.00,
      "totalOrder": 20400,
      "avgUtilization": "63.8%",
      "peakHourDistribution": "10:00-12:00(35%),15:00-17:00(30%)",
      "growthRate": "3.7%",
      "updateTime": "2026-01-31 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 14,
      "statMonth": "2025-09",
      "merchantName": "天河商贸中心",
      "areaName": "天河区",
      "lotName": "天河商贸停车场",
      "totalIncome": 834900.00,
      "totalOrder": 36300,
      "avgUtilization": "78.2%",
      "peakHourDistribution": "09:00-12:00(42%),14:00-18:00(33%)",
      "growthRate": "4.5%",
      "updateTime": "2025-09-30 18:30",
      "operator": "系统自动生成"
    },
    {
      "id": 15,
      "statMonth": "2025-10",
      "merchantName": "从化景区管理公司",
      "areaName": "从化区",
      "lotName": "从化景区停车场",
      "totalIncome": 189000.00,
      "totalOrder": 12600,
      "avgUtilization": "59.6%",
      "peakHourDistribution": "10:00-16:00(65%)",
      "growthRate": "1.2%",
      "updateTime": "2025-10-31 18:30",
      "operator": "系统自动生成"
    }
  ];
};

/** 获取最大ID */
export function getMaxId() {
  const list = dataList();
  return list.length > 0 ? Math.max(...list.map(item => item.id)) : 0;
}

/** 搜索表单配置 - 商户月度版本 */
export function useFormSchema() {
  return [
    {
      fieldName: 'statMonth',
      label: '统计月份',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'month',
        placeholder: '请选择统计月份',
        format: 'YYYY-MM',
        valueFormat: 'YYYY-MM',
        class: 'w-full',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河商贸中心', value: '天河商贸中心' },
          { label: '越秀路侧停车公司', value: '越秀路侧停车公司' },
          { label: '海珠商业集团', value: '海珠商业集团' },
          { label: '白云物业管理公司', value: '白云物业管理公司' },
          { label: '黄埔商业中心', value: '黄埔商业中心' },
          { label: '荔湾停车服务公司', value: '荔湾停车服务公司' },
          { label: '番禺物业服务公司', value: '番禺物业服务公司' },
          { label: '南沙商业开发公司', value: '南沙商业开发公司' },
          { label: '从化景区管理公司', value: '从化景区管理公司' },
        ],
        placeholder: '请选择商户名称',
        showSearch: true,
        class: 'w-full',
      },
      fieldName: 'merchantName',
      label: '商户名称',
    },
    {
      fieldName: 'areaName',
      label: '行政区域',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
          { label: '南沙区', value: '南沙区' },
          { label: '从化区', value: '从化区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
        class: 'w-full',
      },
    },
    {
      fieldName: 'lotName',
      label: '车场选择',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河商贸停车场', value: '天河商贸停车场' },
          { label: '越秀路侧停车区', value: '越秀路侧停车区' },
          { label: '海珠购物中心停车场', value: '海珠购物中心停车场' },
          { label: '白云小区停车场', value: '白云小区停车场' },
          { label: '黄埔商业停车场', value: '黄埔商业停车场' },
          { label: '荔湾路侧停车区', value: '荔湾路侧停车区' },
          { label: '番禺小区停车场', value: '番禺小区停车场' },
          { label: '南沙商业停车场', value: '南沙商业停车场' },
          { label: '从化景区停车场', value: '从化景区停车场' },
        ],
        placeholder: '请选择车场',
        showSearch: true,
        class: 'w-full',
      },
    },
  ];
}

/** 扩展表单配置用于新增编辑 */
export function useExtendedFormSchema() {
  return [
    {
      fieldName: 'statMonth',
      label: '统计月份',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        type: 'month',
        placeholder: '请选择统计月份',
        format: 'YYYY-MM',
        valueFormat: 'YYYY-MM',
        class: 'w-full',
      },
      rules: 'required',
    },
    {
      fieldName: 'merchantName',
      label: '商户名称',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河商贸中心', value: '天河商贸中心' },
          { label: '越秀路侧停车公司', value: '越秀路侧停车公司' },
          { label: '海珠商业集团', value: '海珠商业集团' },
          { label: '白云物业管理公司', value: '白云物业管理公司' },
          { label: '黄埔商业中心', value: '黄埔商业中心' },
          { label: '荔湾停车服务公司', value: '荔湾停车服务公司' },
          { label: '番禺物业服务公司', value: '番禺物业服务公司' },
          { label: '南沙商业开发公司', value: '南沙商业开发公司' },
          { label: '从化景区管理公司', value: '从化景区管理公司' },
        ],
        placeholder: '请选择商户名称',
        showSearch: true,
        class: 'w-full',
      },
      rules: 'required',
    },
    {
      fieldName: 'areaName',
      label: '行政区域',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河区', value: '天河区' },
          { label: '越秀区', value: '越秀区' },
          { label: '海珠区', value: '海珠区' },
          { label: '白云区', value: '白云区' },
          { label: '黄埔区', value: '黄埔区' },
          { label: '荔湾区', value: '荔湾区' },
          { label: '番禺区', value: '番禺区' },
          { label: '南沙区', value: '南沙区' },
          { label: '从化区', value: '从化区' },
        ],
        placeholder: '请选择行政区域',
        showSearch: true,
        class: 'w-full',
      },
      rules: 'required',
    },
    {
      fieldName: 'lotName',
      label: '车场名称',
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '天河商贸停车场', value: '天河商贸停车场' },
          { label: '越秀路侧停车区', value: '越秀路侧停车区' },
          { label: '海珠购物中心停车场', value: '海珠购物中心停车场' },
          { label: '白云小区停车场', value: '白云小区停车场' },
          { label: '黄埔商业停车场', value: '黄埔商业停车场' },
          { label: '荔湾路侧停车区', value: '荔湾路侧停车区' },
          { label: '番禺小区停车场', value: '番禺小区停车场' },
          { label: '南沙商业停车场', value: '南沙商业停车场' },
          { label: '从化景区停车场', value: '从化景区停车场' },
        ],
        placeholder: '请选择车场名称',
        showSearch: true,
        class: 'w-full',
      },
      rules: 'required',
    },
    {
      fieldName: 'totalIncome',
      label: '总营收金额',
      component: 'InputNumber',
      labelWidth: '100',
      componentProps: {
        min: 0,
        placeholder: '请输入总营收金额',
        precision: 2,
        step: 0.01,
        class: 'w-full',
      },
      rules: 'required|numeric',
    },
    {
      fieldName: 'totalOrder',
      label: '总订单数',
      component: 'InputNumber',
      labelWidth: '100',
      componentProps: {
        min: 0,
        placeholder: '请输入总订单数',
        class: 'w-full',
      },
      rules: 'required|numeric',
    },
    {
      fieldName: 'avgUtilization',
      label: '月均利用率',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入月均利用率，如：78.5%',
        class: 'w-full',
      },
      rules: 'required',
    },
    {
      fieldName: 'peakHourDistribution',
      label: '高峰时段分布',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入高峰时段分布，如：09:00-12:00(45%),14:00-18:00(35%)',
        class: 'w-full',
      },
      rules: 'required',
    },
    {
      fieldName: 'growthRate',
      label: '环比增长率',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入环比增长率，如：5.7%',
        class: 'w-full',
      },
      rules: 'required',
    },
  ];
}

/** 表格字段配置 - 商户月度版本 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'statMonth',
      title: '统计月份',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'merchantName',
      title: '商户名称',
      minWidth: 150,
      sortable: true,
      slots: { default: 'merchantName' },
    },
    {
      field: 'areaName',
      title: '区域名称',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'lotName',
      title: '车场名称',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'totalIncome',
      title: '总营收(元)',
      minWidth: 140,
      sortable: true,
      slots: { default: 'totalIncome' },
    },
    {
      field: 'totalOrder',
      title: '总订单数',
      minWidth: 120,
      sortable: true,
      slots: { default: 'totalOrder' },
    },
    {
      field: 'avgUtilization',
      title: '月均利用率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'peakHourDistribution',
      title: '高峰时段分布',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'growthRate',
      title: '环比增长率',
      minWidth: 120,
      sortable: true,
      slots: { default: 'growthRate' },
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑商户月报',
  addText: '新增商户月报',
  excelName: '商户月运营数据报表',
  excelAllName: '商户月运营数据报表.xlsx',
  total: '报表总数: 15; 本月数据: 5; 近6月数据: 12;',
};
