/** 表格初始数据 - 上半年占道经营案件统计分析数据 */
export const dataList = () => [
  {
    region: '鼓楼区',
    totalCasesFirstHalfYear: 1250,
    newReliefPointsCount: 15,
    keyAreaSpecialActions: 8,
    crossStreetLawEnforcement: 12,
    managementSatisfaction: 85.5,
    casesYoYChangeRate: 12.3,
    reliefPointsYoYChangeRate: 20.5,
    specialActionsYoYChangeRate: 15.2,
    crossStreetYoYChangeRate: 8.7,
    satisfactionYoYChangeRate: -2.1,
    caseDistributionByRegion: '核心商圈: 450次；居民区: 380次；学校周边: 220次；市场周边: 200次',
    specialActionTypes: '餐饮集中区整治: 3次；夜市管理: 2次；节假日保障: 2次；突发事件处置: 1次',
    reliefPointDetails: '新建疏导点: 8个；改造升级: 4个；临时增设: 3个',
    satisfactionDetails: '非常满意: 45%；满意: 38%；一般: 12%；不满意: 5%',
    statisticsPeriod: '2024-01-01 ~ 2024-06-30',
  },
  {
    region: '台江区',
    totalCasesFirstHalfYear: 980,
    newReliefPointsCount: 12,
    keyAreaSpecialActions: 6,
    crossStreetLawEnforcement: 9,
    managementSatisfaction: 88.2,
    casesYoYChangeRate: 5.8,
    reliefPointsYoYChangeRate: 15.3,
    specialActionsYoYChangeRate: 12.8,
    crossStreetYoYChangeRate: 11.2,
    satisfactionYoYChangeRate: 3.5,
    caseDistributionByRegion: '商业街区: 320次；老旧小区: 280次；地铁周边: 200次；公园周边: 180次',
    specialActionTypes: '早市管理: 2次；夜市规范: 2次；重点时段保障: 1次；联合整治: 1次',
    reliefPointDetails: '新建疏导点: 6个；改造升级: 3个；临时增设: 3个',
    satisfactionDetails: '非常满意: 52%；满意: 35%；一般: 10%；不满意: 3%',
    statisticsPeriod: '2024-01-01 ~ 2024-06-30',
  },
  {
    region: '仓山区',
    totalCasesFirstHalfYear: 1120,
    newReliefPointsCount: 18,
    keyAreaSpecialActions: 10,
    crossStreetLawEnforcement: 14,
    managementSatisfaction: 82.8,
    casesYoYChangeRate: 18.6,
    reliefPointsYoYChangeRate: 25.7,
    specialActionsYoYChangeRate: 22.1,
    crossStreetYoYChangeRate: 16.3,
    satisfactionYoYChangeRate: -4.2,
    caseDistributionByRegion: '工业园区: 400次；新建小区: 320次；交通枢纽: 200次；学校区域: 200次',
    specialActionTypes: '建筑工地周边: 3次；交通节点: 3次；大型活动保障: 2次；日常巡查: 2次',
    reliefPointDetails: '新建疏导点: 10个；改造升级: 5个；临时增设: 3个',
    satisfactionDetails: '非常满意: 42%；满意: 38%；一般: 15%；不满意: 5%',
    statisticsPeriod: '2024-01-01 ~ 2024-06-30',
  },
  {
    region: '晋安区',
    totalCasesFirstHalfYear: 890,
    newReliefPointsCount: 10,
    keyAreaSpecialActions: 7,
    crossStreetLawEnforcement: 8,
    managementSatisfaction: 89.6,
    casesYoYChangeRate: 3.2,
    reliefPointsYoYChangeRate: 8.9,
    specialActionsYoYChangeRate: 10.5,
    crossStreetYoYChangeRate: 6.8,
    satisfactionYoYChangeRate: 5.8,
    caseDistributionByRegion: '新兴商圈: 280次；居民社区: 260次；医院周边: 180次；学校周边: 170次',
    specialActionTypes: '医院周边: 2次；社区整治: 2次；节日保障: 2次；专项检查: 1次',
    reliefPointDetails: '新建疏导点: 5个；改造升级: 3个；临时增设: 2个',
    satisfactionDetails: '非常满意: 55%；满意: 36%；一般: 8%；不满意: 1%',
    statisticsPeriod: '2024-01-01 ~ 2024-06-30',
  },
  {
    region: '马尾区',
    totalCasesFirstHalfYear: 650,
    newReliefPointsCount: 6,
    keyAreaSpecialActions: 4,
    crossStreetLawEnforcement: 5,
    managementSatisfaction: 91.3,
    casesYoYChangeRate: -2.1,
    reliefPointsYoYChangeRate: 5.2,
    specialActionsYoYChangeRate: 3.8,
    crossStreetYoYChangeRate: 2.1,
    satisfactionYoYChangeRate: 8.9,
    caseDistributionByRegion: '港口区域: 200次；居民区: 220次；学校周边: 130次；其他: 100次',
    specialActionTypes: '港口周边: 1次；学校周边: 1次；常规整治: 1次；联合行动: 1次',
    reliefPointDetails: '新建疏导点: 3个；改造升级: 2个；临时增设: 1个',
    satisfactionDetails: '非常满意: 60%；满意: 32%；一般: 6%；不满意: 2%',
    statisticsPeriod: '2024-01-01 ~ 2024-06-30',
  },
  {
    region: '长乐区',
    totalCasesFirstHalfYear: 720,
    newReliefPointsCount: 8,
    keyAreaSpecialActions: 5,
    crossStreetLawEnforcement: 6,
    managementSatisfaction: 87.9,
    casesYoYChangeRate: 10.4,
    reliefPointsYoYChangeRate: 12.6,
    specialActionsYoYChangeRate: 14.3,
    crossStreetYoYChangeRate: 9.5,
    satisfactionYoYChangeRate: 2.1,
    caseDistributionByRegion: '老城区: 260次；新城区: 240次；工业园区: 120次；学校周边: 100次',
    specialActionTypes: '老城区整治: 2次；新区管理: 2次；企业周边: 1次；联合执法: 1次',
    reliefPointDetails: '新建疏导点: 4个；改造升级: 2个；临时增设: 2个',
    satisfactionDetails: '非常满意: 48%；满意: 39%；一般: 10%；不满意: 3%',
    statisticsPeriod: '2024-01-01 ~ 2024-06-30',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 占道经营案件统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'region',
      label: '区域',
      component: 'Input',
      componentProps: {
        placeholder: '请输入区域名称',
      },
      labelWidth: '130',
      rules: 'required',
    },
    {
      fieldName: 'totalCasesFirstHalfYear',
      label: '上半年占道经营案件总量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入案件总量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'newReliefPointsCount',
      label: '上半年疏导点新增数量',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入疏导点新增数量',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'keyAreaSpecialActions',
      label: '上半年重点区域专项整治次数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入专项整治次数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'crossStreetLawEnforcement',
      label: '上半年跨街道执法协作次数',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入跨街道执法协作次数',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'managementSatisfaction',
      label: '上半年占道经营管控满意度',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入满意度（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'casesYoYChangeRate',
      label: '案件总量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'reliefPointsYoYChangeRate',
      label: '疏导点数量同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'specialActionsYoYChangeRate',
      label: '专项整治次数同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crossStreetYoYChangeRate',
      label: '跨街道执法同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'satisfactionYoYChangeRate',
      label: '满意度同比变化率',
      component: 'InputNumber',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入同比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'caseDistributionByRegion',
      label: '按区域拆分的案件分布',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入按区域拆分的案件分布详情',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'specialActionTypes',
      label: '按专项整治类型拆分',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入专项整治类型及次数分布',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'reliefPointDetails',
      label: '按疏导点拆分详情',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入疏导点新建、改造、临时增设详情',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'satisfactionDetails',
      label: '按满意度维度拆分',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入满意度分布详情（如：非常满意:45%；满意:38%）',
        maxlength: 200,
        type: 'textarea',
        rows: 2,
      },
      rules: 'required',
    },
    {
      fieldName: 'statisticsPeriod',
      label: '统计时段',
      component: 'Input',
      labelWidth: '130',
      componentProps: {
        placeholder: '请输入统计时段（如：2024-01-01 ~ 2024-06-30）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 占道经营案件统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'region',
      title: '区域',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'totalCasesFirstHalfYear',
      title: '上半年占道经营案件总量',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'newReliefPointsCount',
      title: '上半年疏导点新增数量',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'keyAreaSpecialActions',
      title: '上半年重点区域专项整治次数',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'crossStreetLawEnforcement',
      title: '上半年跨街道执法协作次数',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'managementSatisfaction',
      title: '上半年占道经营管控满意度(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'casesYoYChangeRate',
      title: '案件总量同比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'reliefPointsYoYChangeRate',
      title: '疏导点数量同比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'specialActionsYoYChangeRate',
      title: '专项整治次数同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'crossStreetYoYChangeRate',
      title: '跨街道执法同比变化率(%)',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'satisfactionYoYChangeRate',
      title: '满意度同比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'caseDistributionByRegion',
      title: '按区域拆分的案件分布',
      minWidth: 200,
      sortable: false,
    },
    {
      field: 'specialActionTypes',
      title: '按专项整治类型拆分',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'reliefPointDetails',
      title: '按疏导点拆分详情',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'satisfactionDetails',
      title: '按满意度维度拆分',
      minWidth: 180,
      sortable: false,
    },
    {
      field: 'statisticsPeriod',
      title: '统计时段',
      minWidth: 160,
      sortable: false,
    },
    // {
    //   title: '操作',
    //   width: 80,
    //   fixed: 'right',
    //   slots: { default: 'actions' },
    // },
  ];
}
