import { DICT_TYPE } from '@vben/constants';
import { getDictObj } from '@vben/hooks';

/** 获取报表周期Tag类型 */
export const getReportCycleTagType = (cycle) => {
  // 根据报表周期返回对应的tag类型
  const cycleTypeMap = {
    日报: 'info',
    周报: 'success',
    月报: 'primary',
    季报: 'warning',
    半年报: 'danger',
    年报: 'danger',
    自定义报表: 'info',
  };
  return cycleTypeMap[cycle] || 'info';
};

/** 获取报表周期标签 */
export const getReportCycleLabel = (cycle) => {
  const dict = getDictObj(DICT_TYPE.MARKET_OP_REPORT_CYCLE, String(cycle));
  return dict ? dict.label : cycle;
};

/** 获取生成状态Tag类型 */
export const getGenerateStatusTagType = (status) => {
  const statusMap = {
    已生成: 'success',
    生成中: 'warning',
    生成失败: 'danger',
  };
  return statusMap[status] || 'info';
};

/** 营销运营报表表格初始数据 */
export const dataList = () => {
  return [
    {
      id: 1,
      reportCycle: '月报',
      statTime: '2026-03-01 00:00:00-2026-03-31 23:59:59',
      activityCount: 25,
      joinUserCount: 1200,
      lotteryCount: 3500,
      winningRate: '12.50%',
      couponSendCount: 5000,
      couponVerifyRate: '38.60%',
      cardOrderCount: 320,
      revenue: 15_600.8,
      exchangeCount: 890,
      totalStock: 1200,
      warnStockCount: 35,
      generateStatus: '已生成',
      generateTime: '2026-04-01 01:00:00',
      operator: 'admin',
      generateCost: 1200,
      exportCount: 5,
      filterRule: '统计时段：2026-03-01 至 2026-03-31',
      creator: 'system',
      createTime: '2026-04-01 01:00:00',
      updateTime: '2026-04-01 01:00:00',
    },
    {
      id: 2,
      reportCycle: '周报',
      statTime: '2026-03-25 00:00:00-2026-03-31 23:59:59',
      activityCount: 8,
      joinUserCount: 450,
      lotteryCount: 1200,
      winningRate: '15.20%',
      couponSendCount: 1800,
      couponVerifyRate: '42.30%',
      cardOrderCount: 95,
      revenue: 5200.5,
      exchangeCount: 280,
      totalStock: 1150,
      warnStockCount: 28,
      generateStatus: '已生成',
      generateTime: '2026-04-01 00:30:00',
      operator: 'admin',
      generateCost: 800,
      exportCount: 2,
      filterRule: '统计时段：2026-03-25 至 2026-03-31',
      creator: 'system',
      createTime: '2026-04-01 00:30:00',
      updateTime: '2026-04-01 00:30:00',
    },
    {
      id: 3,
      reportCycle: '日报',
      statTime: '2026-03-31 00:00:00-2026-03-31 23:59:59',
      activityCount: 3,
      joinUserCount: 120,
      lotteryCount: 350,
      winningRate: '18.50%',
      couponSendCount: 450,
      couponVerifyRate: '45.20%',
      cardOrderCount: 25,
      revenue: 1200.8,
      exchangeCount: 68,
      totalStock: 1120,
      warnStockCount: 22,
      generateStatus: '已生成',
      generateTime: '2026-04-01 00:05:00',
      operator: 'admin',
      generateCost: 300,
      exportCount: 1,
      filterRule: '统计时段：2026-03-31',
      creator: 'system',
      createTime: '2026-04-01 00:05:00',
      updateTime: '2026-04-01 00:05:00',
    },
    {
      id: 4,
      reportCycle: '季报',
      statTime: '2026-01-01 00:00:00-2026-03-31 23:59:59',
      activityCount: 68,
      joinUserCount: 3500,
      lotteryCount: 9800,
      winningRate: '14.80%',
      couponSendCount: 14_500,
      couponVerifyRate: '40.50%',
      cardOrderCount: 850,
      revenue: 42_500.6,
      exchangeCount: 2450,
      totalStock: 1350,
      warnStockCount: 48,
      generateStatus: '生成中',
      generateTime: '2026-04-01 02:00:00',
      operator: 'admin',
      generateCost: 2000,
      exportCount: 0,
      filterRule: '统计时段：2026-01-01 至 2026-03-31',
      creator: 'system',
      createTime: '2026-04-01 02:00:00',
      updateTime: '2026-04-01 02:00:00',
    },
    {
      id: 5,
      reportCycle: '自定义报表',
      statTime: '2026-03-15 00:00:00-2026-03-20 23:59:59',
      activityCount: 12,
      joinUserCount: 680,
      lotteryCount: 1850,
      winningRate: '16.20%',
      couponSendCount: 2800,
      couponVerifyRate: '41.80%',
      cardOrderCount: 165,
      revenue: 8200.4,
      exchangeCount: 520,
      totalStock: 1180,
      warnStockCount: 30,
      generateStatus: '已生成',
      generateTime: '2026-03-21 01:00:00',
      operator: 'admin',
      generateCost: 600,
      exportCount: 3,
      filterRule: '统计时段：2026-03-15 至 2026-03-20；活动类型：积分活动',
      creator: 'admin',
      createTime: '2026-03-21 01:00:00',
      updateTime: '2026-03-21 01:00:00',
    },
    {
      id: 6,
      reportCycle: '年报',
      statTime: '2025-01-01 00:00:00-2025-12-31 23:59:59',
      activityCount: 280,
      joinUserCount: 15_800,
      lotteryCount: 45_000,
      winningRate: '13.50%',
      couponSendCount: 68_000,
      couponVerifyRate: '39.20%',
      cardOrderCount: 3650,
      revenue: 185_000.8,
      exchangeCount: 11_200,
      totalStock: 1580,
      warnStockCount: 85,
      generateStatus: '已生成',
      generateTime: '2026-01-01 00:00:00',
      operator: 'system',
      generateCost: 5000,
      exportCount: 12,
      filterRule: '统计时段：2025-01-01 至 2025-12-31',
      creator: 'system',
      createTime: '2026-01-01 00:00:00',
      updateTime: '2026-01-01 00:00:00',
    },
    {
      id: 7,
      reportCycle: '半年报',
      statTime: '2025-07-01 00:00:00-2025-12-31 23:59:59',
      activityCount: 145,
      joinUserCount: 8200,
      lotteryCount: 23_500,
      winningRate: '14.20%',
      couponSendCount: 35_200,
      couponVerifyRate: '40.80%',
      cardOrderCount: 1880,
      revenue: 98_500.6,
      exchangeCount: 5800,
      totalStock: 1480,
      warnStockCount: 65,
      generateStatus: '已生成',
      generateTime: '2026-01-01 00:00:00',
      operator: 'system',
      generateCost: 3500,
      exportCount: 8,
      filterRule: '统计时段：2025-07-01 至 2025-12-31',
      creator: 'system',
      createTime: '2026-01-01 00:00:00',
      updateTime: '2026-01-01 00:00:00',
    },
    {
      id: 8,
      reportCycle: '月报',
      statTime: '2026-02-01 00:00:00-2026-02-28 23:59:59',
      activityCount: 22,
      joinUserCount: 1050,
      lotteryCount: 3100,
      winningRate: '13.80%',
      couponSendCount: 4200,
      couponVerifyRate: '37.50%',
      cardOrderCount: 280,
      revenue: 13_800.4,
      exchangeCount: 780,
      totalStock: 1250,
      warnStockCount: 32,
      generateStatus: '生成失败',
      generateTime: '2026-03-01 01:00:00',
      operator: 'admin',
      generateCost: 1500,
      exportCount: 0,
      filterRule: '统计时段：2026-02-01 至 2026-02-28',
      creator: 'system',
      createTime: '2026-03-01 01:00:00',
      updateTime: '2026-03-01 01:00:00',
    },
  ];
};

/** 营销运营报表表单配置 */
export function useFormSchema() {
  return [
    {
      fieldName: 'reportCycle',
      label: '报表周期',
      component: 'Select',
      componentProps: {
        placeholder: '请选择报表周期',
        options: [
          { label: '日报', value: '日报' },
          { label: '周报', value: '周报' },
          { label: '月报', value: '月报' },
          { label: '季报', value: '季报' },
          { label: '半年报', value: '半年报' },
          { label: '年报', value: '年报' },
          { label: '自定义报表', value: '自定义报表' },
        ],
      },
      rules: 'required',
    },
    {
      fieldName: 'statTimeRange',
      label: '统计时段',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择统计时段',
        type: 'datetimerange',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
      rules: 'required',
    },
    {
      fieldName: 'filterRule',
      label: '筛选规则',
      component: 'Input',
      componentProps: {
        placeholder: '请输入筛选规则',
        type: 'textarea',
        rows: 3,
      },
    },
  ];
}

/** 营销运营报表搜索表单配置 */
export function useSearchFormSchema() {
  return [
    {
      fieldName: 'reportCycle',
      label: '报表周期',
      component: 'Select',
      componentProps: {
        placeholder: '请选择报表周期',
        options: [
          { label: '日报', value: '日报' },
          { label: '周报', value: '周报' },
          { label: '月报', value: '月报' },
          { label: '季报', value: '季报' },
          { label: '半年报', value: '半年报' },
          { label: '年报', value: '年报' },
          { label: '自定义报表', value: '自定义报表' },
        ],
        clearable: true,
      },
    },
    {
      fieldName: 'statTimeRange',
      label: '统计时段',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择统计时段',
        type: 'datetimerange',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
        clearable: true,
      },
    },
    {
      fieldName: 'generateStatus',
      label: '生成状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择生成状态',
        options: [
          { label: '已生成', value: '已生成' },
          { label: '生成中', value: '生成中' },
          { label: '生成失败', value: '生成失败' },
        ],
        clearable: true,
      },
    },
    {
      fieldName: 'activityCount',
      label: '活动数',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入活动数',
        min: 0,
        clearable: true,
      },
    },
    {
      fieldName: 'joinUserCount',
      label: '参与用户数',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入参与用户数',
        min: 0,
        clearable: true,
      },
    },
    {
      fieldName: 'lotteryCount',
      label: '抽奖量',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入抽奖量',
        min: 0,
        clearable: true,
      },
    },
    {
      fieldName: 'couponSendCount',
      label: '优惠券发放量',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入优惠券发放量',
        min: 0,
        clearable: true,
      },
    },
    {
      fieldName: 'cardOrderCount',
      label: '卡种订单量',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入卡种订单量',
        min: 0,
        clearable: true,
      },
    },
    {
      fieldName: 'revenue',
      label: '营收',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入营收',
        min: 0,
        precision: 2,
        clearable: true,
      },
    },
    {
      fieldName: 'exchangeCount',
      label: '兑换量',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入兑换量',
        min: 0,
        clearable: true,
      },
    },
    {
      fieldName: 'totalStock',
      label: '总库存',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入总库存',
        min: 0,
        clearable: true,
      },
    },
    {
      fieldName: 'warnStockCount',
      label: '预警库存数',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入预警库存数',
        min: 0,
        clearable: true,
      },
    },
    // {
    //   fieldName: 'operator',
    //   label: '操作人',
    //   component: 'Input',
    //   componentProps: {
    //     placeholder: '请输入操作人',
    //     clearable: true,
    //   },
    // },
    {
      fieldName: 'generateTimeRange',
      label: '生成时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择生成时间范围',
        type: 'datetimerange',
        format: 'YYYY-MM-DD HH:mm:ss',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
        clearable: true,
      },
    },
    {
      fieldName: 'filterRule',
      label: '筛选规则',
      component: 'Input',
      componentProps: {
        placeholder: '请输入筛选规则关键词',
        clearable: true,
      },
    },
  ];
}

/** 营销运营报表表格列配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'reportCycle',
      title: '报表周期',
      minWidth: 120,
      sortable: true,
      slots: { default: 'reportCycle' },
    },
    // {
    //   field: 'statTime',
    //   title: '统计时段',
    //   minWidth: 280,
    //   sortable: true,
    // },
    {
      field: 'activityCount',
      title: '活动数',
      minWidth: 100,
      sortable: true,
      slots: { default: 'activityCount' },
    },
    {
      field: 'joinUserCount',
      title: '参与用户数',
      minWidth: 120,
      sortable: true,
      slots: { default: 'joinUserCount' },
    },
    {
      field: 'lotteryCount',
      title: '抽奖量',
      minWidth: 100,
      sortable: true,
      slots: { default: 'lotteryCount' },
    },
    {
      field: 'winningRate',
      title: '中奖率',
      minWidth: 100,
      sortable: true,
      slots: { default: 'winningRate' },
    },
    {
      field: 'couponSendCount',
      title: '优惠券发放量',
      minWidth: 130,
      sortable: true,
      slots: { default: 'couponSendCount' },
    },
    {
      field: 'couponVerifyRate',
      title: '核销率',
      minWidth: 100,
      sortable: true,
      slots: { default: 'couponVerifyRate' },
    },
    {
      field: 'cardOrderCount',
      title: '卡种订单量',
      minWidth: 120,
      sortable: true,
      slots: { default: 'cardOrderCount' },
    },
    {
      field: 'revenue',
      title: '营收',
      minWidth: 120,
      sortable: true,
      slots: { default: 'revenue' },
    },
    {
      field: 'exchangeCount',
      title: '兑换量',
      minWidth: 100,
      sortable: true,
      slots: { default: 'exchangeCount' },
    },
    {
      field: 'totalStock',
      title: '总库存',
      minWidth: 100,
      sortable: true,
      slots: { default: 'totalStock' },
    },
    {
      field: 'warnStockCount',
      title: '预警库存数',
      minWidth: 120,
      sortable: true,
      slots: { default: 'warnStockCount' },
    },
    {
      field: 'generateStatus',
      title: '生成状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'generateStatus' },
    },
    {
      field: 'generateTime',
      title: '生成时间',
      minWidth: 180,
      sortable: true,
      slots: { default: 'generateTime' },
    },
    {
      field: 'operator',
      title: '操作人',
      minWidth: 120,
      sortable: true,
      slots: { default: 'operator' },
    },
    {
      field: 'generateCost',
      title: '生成耗时(ms)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'exportCount',
      title: '导出次数',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'filterRule',
      title: '筛选规则',
      minWidth: 250,
      sortable: true,
      slots: { default: 'filterRule' },
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

export const textObj = {
  editText: '编辑报表',
  addText: '生成报表',
  excelName: '营销运营报表列表',
  excelAllName: '营销运营报表数据.xlsx',
  total: ' 总计: 报表数量8;已生成:6;生成中:1;生成失败:1',
};

/** 详情抽屉字段配置 */
export const detailFields = [
  { key: 'reportCycle', label: '报表周期' },
  { key: 'statTime', label: '统计时段' },
  { key: 'activityCount', label: '活动数' },
  { key: 'joinUserCount', label: '参与用户数' },
  { key: 'lotteryCount', label: '抽奖量' },
  { key: 'winningRate', label: '中奖率' },
  { key: 'couponSendCount', label: '优惠券发放量' },
  { key: 'couponVerifyRate', label: '核销率' },
  { key: 'cardOrderCount', label: '卡种订单量' },
  { key: 'revenue', label: '营收' },
  { key: 'exchangeCount', label: '兑换量' },
  { key: 'totalStock', label: '总库存' },
  { key: 'warnStockCount', label: '预警库存数' },
  { key: 'generateStatus', label: '生成状态', type: 'tag', tagType: getGenerateStatusTagType },
  { key: 'generateTime', label: '生成时间' },
  { key: 'operator', label: '操作人' },
  { key: 'generateCost', label: '生成耗时(ms)' },
  { key: 'exportCount', label: '导出次数' },
  { key: 'filterRule', label: '筛选规则' },
  { key: 'creator', label: '创建者' },
  { key: 'createTime', label: '创建时间' },
  { key: 'updateTime', label: '更新时间' },
];
