import { createTimeFormatter, formatTime } from '../../../utils/timeFormatter';

/** 模块表格初始数据 - 车辆通行周期报表 */
export const dataList = () => {
  return [
    // 日报数据
    {
      id: 'DR20260426001',
      reportType: '日报',
      reportCycle: '日报',
      timeScale: '日',
      statisticPeriod: '2026-04-26',
      statisticStartTime: '2026-04-26 00:00:00',
      statisticEndTime: '2026-04-26 23:59:59',
      stationId: 'ST001',
      stationName: '芗城区XX社区停车场',
      areaId: 'A001',
      areaName: '芗城区',
      entryCount: 328,
      exitCount: 315,
      parkingCount: 13,
      identifySuccessRate: 98.5,
      verifySuccessRate: 96.8,
      abnormalHandleRate: 92.3,
      etcSuccessRate: 88.6,
      generateStatus: '已生成',
      generateTime: '2026-04-27 00:05:23',
      generateDuration: 12,
      dataUpdateTime: '2026-04-27 00:05:23',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '自动生成日报',
    },
    {
      id: 'DR20260425001',
      reportType: '日报',
      reportCycle: '日报',
      timeScale: '日',
      statisticPeriod: '2026-04-25',
      statisticStartTime: '2026-04-25 00:00:00',
      statisticEndTime: '2026-04-25 23:59:59',
      stationId: 'ST001',
      stationName: '芗城区XX社区停车场',
      areaId: 'A001',
      areaName: '芗城区',
      entryCount: 342,
      exitCount: 338,
      parkingCount: 4,
      identifySuccessRate: 97.8,
      verifySuccessRate: 95.2,
      abnormalHandleRate: 90.5,
      etcSuccessRate: 87.3,
      generateStatus: '已生成',
      generateTime: '2026-04-26 00:05:18',
      generateDuration: 15,
      dataUpdateTime: '2026-04-26 00:05:18',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '自动生成日报',
    },
    {
      id: 'DR20260426002',
      reportType: '日报',
      reportCycle: '日报',
      timeScale: '日',
      statisticPeriod: '2026-04-26',
      statisticStartTime: '2026-04-26 00:00:00',
      statisticEndTime: '2026-04-26 23:59:59',
      stationId: 'ST002',
      stationName: '龙文区碧湖公园停车场',
      areaId: 'A002',
      areaName: '龙文区',
      entryCount: 456,
      exitCount: 448,
      parkingCount: 8,
      identifySuccessRate: 99.1,
      verifySuccessRate: 97.5,
      abnormalHandleRate: 94.2,
      etcSuccessRate: 91.8,
      generateStatus: '已生成',
      generateTime: '2026-04-27 00:05:45',
      generateDuration: 18,
      dataUpdateTime: '2026-04-27 00:05:45',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '自动生成日报',
    },
    // 周报数据
    {
      id: 'WR20260417001',
      reportType: '周报',
      reportCycle: '周报',
      timeScale: '周',
      statisticPeriod: '2026年第16周',
      statisticStartTime: '2026-04-20 00:00:00',
      statisticEndTime: '2026-04-26 23:59:59',
      stationId: 'ST001',
      stationName: '芗城区XX社区停车场',
      areaId: 'A001',
      areaName: '芗城区',
      entryCount: 2285,
      exitCount: 2268,
      parkingCount: 17,
      identifySuccessRate: 98.2,
      verifySuccessRate: 96.5,
      abnormalHandleRate: 91.8,
      etcSuccessRate: 88.9,
      generateStatus: '已生成',
      generateTime: '2026-04-27 01:15:32',
      generateDuration: 45,
      dataUpdateTime: '2026-04-27 01:15:32',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '自动生成周报',
    },
    {
      id: 'WR20260417002',
      reportType: '周报',
      reportCycle: '周报',
      timeScale: '周',
      statisticPeriod: '2026年第16周',
      statisticStartTime: '2026-04-20 00:00:00',
      statisticEndTime: '2026-04-26 23:59:59',
      stationId: 'ST002',
      stationName: '龙文区碧湖公园停车场',
      areaId: 'A002',
      areaName: '龙文区',
      entryCount: 3156,
      exitCount: 3142,
      parkingCount: 14,
      identifySuccessRate: 98.8,
      verifySuccessRate: 97.2,
      abnormalHandleRate: 93.5,
      etcSuccessRate: 90.6,
      generateStatus: '已生成',
      generateTime: '2026-04-27 01:16:08',
      generateDuration: 52,
      dataUpdateTime: '2026-04-27 01:16:08',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '自动生成周报',
    },
    // 月报数据
    {
      id: 'MR20260401001',
      reportType: '月报',
      reportCycle: '月报',
      timeScale: '月',
      statisticPeriod: '2026年4月',
      statisticStartTime: '2026-04-01 00:00:00',
      statisticEndTime: '2026-04-30 23:59:59',
      stationId: 'ST001',
      stationName: '芗城区XX社区停车场',
      areaId: 'A001',
      areaName: '芗城区',
      entryCount: 9856,
      exitCount: 9823,
      parkingCount: 33,
      identifySuccessRate: 98.3,
      verifySuccessRate: 96.7,
      abnormalHandleRate: 92.1,
      etcSuccessRate: 89.2,
      generateStatus: '生成中',
      generateTime: '2026-04-26 10:30:00',
      generateDuration: 0,
      dataUpdateTime: '2026-04-26 10:30:00',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '月报生成中',
    },
    {
      id: 'MR20260301001',
      reportType: '月报',
      reportCycle: '月报',
      timeScale: '月',
      statisticPeriod: '2026年3月',
      statisticStartTime: '2026-03-01 00:00:00',
      statisticEndTime: '2026-03-31 23:59:59',
      stationId: 'ST001',
      stationName: '芗城区XX社区停车场',
      areaId: 'A001',
      areaName: '芗城区',
      entryCount: 10_234,
      exitCount: 10_198,
      parkingCount: 36,
      identifySuccessRate: 98.1,
      verifySuccessRate: 96.4,
      abnormalHandleRate: 91.5,
      etcSuccessRate: 88.7,
      generateStatus: '已生成',
      generateTime: '2026-04-01 02:35:42',
      generateDuration: 125,
      dataUpdateTime: '2026-04-01 02:35:42',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '自动生成月报',
    },
    // 季报数据
    {
      id: 'QR20260101001',
      reportType: '季报',
      reportCycle: '季报',
      timeScale: '季',
      statisticPeriod: '2026年第1季度',
      statisticStartTime: '2026-01-01 00:00:00',
      statisticEndTime: '2026-03-31 23:59:59',
      stationId: 'ST001',
      stationName: '芗城区XX社区停车场',
      areaId: 'A001',
      areaName: '芗城区',
      entryCount: 29_567,
      exitCount: 29_485,
      parkingCount: 82,
      identifySuccessRate: 98,
      verifySuccessRate: 96.3,
      abnormalHandleRate: 91.2,
      etcSuccessRate: 88.5,
      generateStatus: '已生成',
      generateTime: '2026-04-01 03:45:28',
      generateDuration: 285,
      dataUpdateTime: '2026-04-01 03:45:28',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '自动生成季报',
    },
    // 半年报数据
    {
      id: 'HR20250701001',
      reportType: '半年报',
      reportCycle: '半年报',
      timeScale: '半年',
      statisticPeriod: '2025年下半年',
      statisticStartTime: '2025-07-01 00:00:00',
      statisticEndTime: '2025-12-31 23:59:59',
      stationId: 'ST001',
      stationName: '芗城区XX社区停车场',
      areaId: 'A001',
      areaName: '芗城区',
      entryCount: 58_234,
      exitCount: 58_102,
      parkingCount: 132,
      identifySuccessRate: 97.8,
      verifySuccessRate: 96.1,
      abnormalHandleRate: 90.8,
      etcSuccessRate: 87.9,
      generateStatus: '已生成',
      generateTime: '2026-01-01 05:25:15',
      generateDuration: 456,
      dataUpdateTime: '2026-01-01 05:25:15',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '自动生成半年报',
    },
    // 年报数据
    {
      id: 'YR20250101001',
      reportType: '年报',
      reportCycle: '年报',
      timeScale: '年',
      statisticPeriod: '2025年',
      statisticStartTime: '2025-01-01 00:00:00',
      statisticEndTime: '2025-12-31 23:59:59',
      stationId: 'ST001',
      stationName: '芗城区XX社区停车场',
      areaId: 'A001',
      areaName: '芗城区',
      entryCount: 115_678,
      exitCount: 115_432,
      parkingCount: 246,
      identifySuccessRate: 97.9,
      verifySuccessRate: 96.2,
      abnormalHandleRate: 91,
      etcSuccessRate: 88.3,
      generateStatus: '已生成',
      generateTime: '2026-01-01 08:15:42',
      generateDuration: 825,
      dataUpdateTime: '2026-01-01 08:15:42',
      operatorId: 'U001',
      operatorName: '系统自动',
      remark: '自动生成年报',
    },
    // 自定义报表数据
    {
      id: 'CR20260420001',
      reportType: '自定义报表',
      reportCycle: '自定义',
      timeScale: '自定义',
      statisticPeriod: '2026-04-20 至 2026-04-26',
      statisticStartTime: '2026-04-20 08:00:00',
      statisticEndTime: '2026-04-26 18:00:00',
      stationId: 'ST001',
      stationName: '芗城区XX社区停车场',
      areaId: 'A001',
      areaName: '芗城区',
      entryCount: 1856,
      exitCount: 1842,
      parkingCount: 14,
      identifySuccessRate: 98.4,
      verifySuccessRate: 96.9,
      abnormalHandleRate: 92.5,
      etcSuccessRate: 89.3,
      generateStatus: '已生成',
      generateTime: '2026-04-26 15:32:18',
      generateDuration: 28,
      dataUpdateTime: '2026-04-26 15:32:18',
      operatorId: 'U002',
      operatorName: '张三',
      filterConditions:
        '片区：芗城区；场站：芗城区XX社区停车场；时间：工作日8:00-18:00',
      remark: '工作日高峰时段分析',
    },
    {
      id: 'CR20260415001',
      reportType: '自定义报表',
      reportCycle: '自定义',
      timeScale: '自定义',
      statisticPeriod: '2026-04-15 至 2026-04-21',
      statisticStartTime: '2026-04-15 00:00:00',
      statisticEndTime: '2026-04-21 23:59:59',
      stationId: 'ST002',
      stationName: '龙文区碧湖公园停车场',
      areaId: 'A002',
      areaName: '龙文区',
      entryCount: 3245,
      exitCount: 3228,
      parkingCount: 17,
      identifySuccessRate: 98.9,
      verifySuccessRate: 97.4,
      abnormalHandleRate: 93.8,
      etcSuccessRate: 91.2,
      generateStatus: '已生成',
      generateTime: '2026-04-22 09:15:35',
      generateDuration: 35,
      dataUpdateTime: '2026-04-22 09:15:35',
      operatorId: 'U003',
      operatorName: '李四',
      filterConditions: '片区：龙文区；场站：龙文区碧湖公园停车场；时间：全天',
      remark: '周通行量对比分析',
    },
  ];
};

/** 查询表单配置 */
export function useSearchFormSchema() {
  return [
    {
      fieldName: 'reportCycle',
      label: '报表周期',
      component: 'Select',
      componentProps: {
        placeholder: '请选择报表周期',
        options: [
          { label: '日报', value: '日报' },
          { label: '周报', value: '周报' },
          { label: '月报', value: '月报' },
          { label: '季报', value: '季报' },
          { label: '半年报', value: '半年报' },
          { label: '年报', value: '年报' },
          { label: '自定义报表', value: '自定义报表' },
        ],
      },
    },
    {
      fieldName: 'stationId',
      label: '场站',
      component: 'Select',
      componentProps: {
        placeholder: '请选择场站',
        options: [
          { label: '芗城区XX社区停车场', value: 'ST001' },
          { label: '龙文区碧湖公园停车场', value: 'ST002' },
          { label: '龙海区石码镇停车场', value: 'ST003' },
        ],
      },
    },
    {
      fieldName: 'reportStatus',
      label: '生成状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择生成状态',
        options: [
          { label: '已生成', value: '已生成' },
          { label: '生成中', value: '生成中' },
          { label: '生成失败', value: '生成失败' },
        ],
      },
    },
    {
      fieldName: 'beginTime',
      label: '开始时间',
      component: 'DatePicker',
      componentProps: {
        type: 'datetime',
        placeholder: '请选择开始时间',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      fieldName: 'endTime',
      label: '结束时间',
      component: 'DatePicker',
      componentProps: {
        type: 'datetime',
        placeholder: '请选择结束时间',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
  ];
}

/** 表格列配置 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'id',
      title: '报表ID',
      minWidth: 140,
      sortable: true,
      slots: { default: 'id' },
    },
    {
      field: 'reportType',
      title: '报表类型',
      minWidth: 120,
      sortable: true,
      slots: { default: 'reportType' },
    },
    {
      field: 'timeScale',
      title: '时间尺度',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'statisticPeriod',
      title: '统计周期',
      minWidth: 180,
      sortable: true,
      slots: { default: 'statisticPeriod' },
    },
    {
      field: 'stationName',
      title: '所属场站',
      minWidth: 180,
      sortable: true,
      slots: { default: 'stationName' },
    },
    {
      field: 'entryCount',
      title: '入场量',
      minWidth: 100,
      sortable: true,
      slots: { default: 'entryCount' },
    },
    {
      field: 'exitCount',
      title: '离场量',
      minWidth: 100,
      sortable: true,
      slots: { default: 'exitCount' },
    },
    {
      field: 'parkingCount',
      title: '在停车辆数',
      minWidth: 120,
      sortable: true,
      slots: { default: 'parkingCount' },
    },
    {
      field: 'identifySuccessRate',
      title: '识别成功率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'verifySuccessRate',
      title: '核验成功率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'abnormalHandleRate',
      title: '异常处置率(%)',
      minWidth: 130,
      sortable: true,
    },
    {
      field: 'etcSuccessRate',
      title: 'ETC通行成功率(%)',
      minWidth: 150,
      sortable: true,
    },
    {
      field: 'generateStatus',
      title: '生成状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'generateStatus' },
    },
    {
      field: 'generateTime',
      title: '生成时间',
      minWidth: 160,
      sortable: true,
      formatter: createTimeFormatter(),
    },
    {
      field: 'operatorName',
      title: '操作人',
      minWidth: 100,
      sortable: true,
      slots: { default: 'operatorName' },
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

export const textObj = {
  editText: '编辑报表',
  addText: '生成自定义报表',
  excelName: '车辆通行周期报表',
  excelAllName: '车辆通行周期报表导出.xlsx',
  total:
    '总计: 报表12条; 日报3条; 周报2条; 月报2条; 季报1条; 半年报1条; 年报1条; 自定义2条',
};

/** 详情抽屉字段配置 */
export const detailFields = [
  { key: 'id', label: '报表ID' },
  { key: 'reportType', label: '报表类型' },
  { key: 'reportCycle', label: '报表周期' },
  { key: 'timeScale', label: '时间尺度' },
  { key: 'statisticPeriod', label: '统计周期' },
  { key: 'statisticStartTime', label: '统计开始时间', formatter: formatTime },
  { key: 'statisticEndTime', label: '统计结束时间', formatter: formatTime },
  { key: 'areaName', label: '所属片区' },
  { key: 'stationName', label: '所属场站' },
  { key: 'entryCount', label: '入场量' },
  { key: 'exitCount', label: '离场量' },
  { key: 'parkingCount', label: '在停车辆数' },
  { key: 'identifySuccessRate', label: '识别成功率(%)' },
  { key: 'verifySuccessRate', label: '核验成功率(%)' },
  { key: 'abnormalHandleRate', label: '异常处置率(%)' },
  { key: 'etcSuccessRate', label: 'ETC通行成功率(%)' },
  { key: 'generateStatus', label: '生成状态' },
  { key: 'generateTime', label: '生成时间', formatter: formatTime },
  { key: 'generateDuration', label: '生成耗时(秒)' },
  { key: 'dataUpdateTime', label: '数据更新时间', formatter: formatTime },
  { key: 'operatorName', label: '操作人' },
  { key: 'filterConditions', label: '筛选条件' },
  { key: 'remark', label: '备注' },
];

/** 生成报表表单配置 */
export function useCreateFormSchema() {
  return [
    {
      fieldName: 'reportCycle',
      label: '报表周期',
      component: 'Select',
      required: true,
      componentProps: {
        placeholder: '请选择报表周期',
        options: [
          { label: '日报', value: '日报' },
          { label: '周报', value: '周报' },
          { label: '月报', value: '月报' },
          { label: '季报', value: '季报' },
          { label: '半年报', value: '半年报' },
          { label: '年报', value: '年报' },
          { label: '自定义报表', value: '自定义报表' },
        ],
      },
    },
    {
      fieldName: 'stationId',
      label: '场站',
      component: 'Select',
      required: true,
      componentProps: {
        placeholder: '请选择场站',
        options: [
          { label: '芗城区XX社区停车场', value: 'ST001' },
          { label: '龙文区碧湖公园停车场', value: 'ST002' },
          { label: '龙海区石码镇停车场', value: 'ST003' },
        ],
      },
    },
    {
      fieldName: 'statStartTime',
      label: '统计开始时间',
      component: 'DatePicker',
      required: true,
      componentProps: {
        type: 'datetime',
        placeholder: '请选择统计开始时间',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      fieldName: 'statEndTime',
      label: '统计结束时间',
      component: 'DatePicker',
      required: true,
      componentProps: {
        type: 'datetime',
        placeholder: '请选择统计结束时间',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Textarea',
      componentProps: {
        placeholder: '请输入备注信息',
        rows: 3,
      },
    },
  ];
}
