// 模拟公园环境管理数据
export const dataList = () => {
  return [
    // ---------- 全部（公园基础信息）id1-id3 ----------
    {
      id: '1',
      toiletName: '中山公园',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '06:00-22:00',
      stallCount: 50, // 设施数量（可复用）
      status: '正常运营',
      manager: '张园长',
      // 全部特有字段
      cleaningRate: 98.5,
      greenSurvivalRate: 96.0,
      facilityRate: 95.2,
      environmentRate: 97.8,
      wasteTransferCompleteRate: 100,
      cleaningFrequency: '每日两次',
      greenMaintenanceCycle: 15, // 绿化养护周期（天）
    },
    {
      id: '2',
      toiletName: '碧湖公园',
      location: '龙文区碧湖路88号',
      area: '龙文区-碧湖街道',
      openHours: '05:30-22:30',
      stallCount: 45,
      status: '正常运营',
      manager: '李园长',
      cleaningRate: 96.0,
      greenSurvivalRate: 95.5,
      facilityRate: 94.0,
      environmentRate: 96.5,
      wasteTransferCompleteRate: 98,
      cleaningFrequency: '每日三次',
      greenMaintenanceCycle: 10,
    },
    {
      id: '3',
      toiletName: '胜利公园',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '07:00-21:00',
      stallCount: 30,
      status: '部分停运',
      manager: '王园长',
      cleaningRate: 88.0,
      greenSurvivalRate: 90.0,
      facilityRate: 82.5,
      environmentRate: 89.0,
      wasteTransferCompleteRate: 90,
      cleaningFrequency: '每日一次',
      greenMaintenanceCycle: 20,
    },

    // ---------- 保洁待执行 id4-id6 ----------
    {
      id: '4',
      toiletName: '中山公园',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '06:00-22:00',
      stallCount: 50,
      status: '保洁待执行',
      manager: '张园长',
      // 保洁待执行特有字段
      cleaningArea: '主干道、广场、休闲区',
      cleaningFrequency: '每日两次',
      cleaningTime: '07:00-09:00,18:00-20:00',
      cleaningStandard: '一级标准',
      staff: '李阿姨、王阿姨',
      planStatus: '待执行',
      createBy: 'admin',
      createTime: '2026-03-01 08:00:00',
      updateTime: '2026-03-01 08:00:00',
      cleaningPlanCompleteRate: 85,
      attendanceRate: 98,
    },
    {
      id: '5',
      toiletName: '碧湖公园',
      location: '龙文区碧湖路88号',
      area: '龙文区-碧湖街道',
      openHours: '05:30-22:30',
      stallCount: 45,
      status: '保洁待执行',
      manager: '李园长',
      cleaningArea: '环湖步道、儿童乐园',
      cleaningFrequency: '每日三次',
      cleaningTime: '08:00-10:00,14:00-16:00,19:00-21:00',
      cleaningStandard: '特级标准',
      staff: '赵叔、钱婶',
      planStatus: '执行中',
      createBy: 'admin',
      createTime: '2026-03-01 09:30:00',
      updateTime: '2026-03-01 09:30:00',
      cleaningPlanCompleteRate: 60,
      attendanceRate: 100,
    },
    {
      id: '6',
      toiletName: '胜利公园',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '07:00-21:00',
      stallCount: 30,
      status: '保洁待执行',
      manager: '王园长',
      cleaningArea: '健身区、草坪周边',
      cleaningFrequency: '每日一次',
      cleaningTime: '09:00-11:00',
      cleaningStandard: '二级标准',
      staff: '孙姐',
      planStatus: '待执行',
      createBy: 'admin',
      createTime: '2026-03-01 10:00:00',
      updateTime: '2026-03-01 10:00:00',
      cleaningPlanCompleteRate: 0,
      attendanceRate: 95,
    },

    // ---------- 绿化待养护 id7-id9 ----------
    {
      id: '7',
      toiletName: '中山公园',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '06:00-22:00',
      stallCount: 50,
      status: '绿化待养护',
      manager: '张园长',
      // 绿化待养护特有字段（复用 repairId 等）
      repairId: 'GR20250301001', // 养护编号
      facilityType: '乔木', // 绿化品类
      greenArea: '中央草坪区',
      greenMaintenanceCycle: 15,
      maintenanceContent: '修剪、浇灌、施肥',
      greenStaff: '绿化组',
      planStatus: '待执行',
      createBy: 'admin',
      createTime: '2026-03-01 08:30:00',
      updateTime: '2026-03-01 08:30:00',
      greenExecuteTime: null,
      greenSurvivalRate: 96,
      pestHandleRecord: null,
      greenMaintenanceCompleteRate: 0,
    },
    {
      id: '8',
      toiletName: '碧湖公园',
      location: '龙文区碧湖路88号',
      area: '龙文区-碧湖街道',
      openHours: '05:30-22:30',
      stallCount: 45,
      status: '绿化待养护',
      manager: '李园长',
      repairId: 'GR20250301002',
      facilityType: '灌木',
      greenArea: '环湖绿化带',
      greenMaintenanceCycle: 10,
      maintenanceContent: '修剪、病虫害防治',
      greenStaff: '绿化组',
      planStatus: '执行中',
      createBy: 'admin',
      createTime: '2026-03-01 09:15:00',
      updateTime: '2026-03-01 09:45:00',
      greenExecuteTime: '2026-03-01 10:00:00',
      greenSurvivalRate: 95,
      pestHandleRecord: '发现蚜虫，已喷药',
      greenMaintenanceCompleteRate: 70,
    },
    {
      id: '9',
      toiletName: '胜利公园',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '07:00-21:00',
      stallCount: 30,
      status: '绿化待养护',
      manager: '王园长',
      repairId: 'GR20250301003',
      facilityType: '草坪',
      greenArea: '休闲草坪区',
      greenMaintenanceCycle: 20,
      maintenanceContent: '修剪、浇水',
      greenStaff: '绿化组',
      planStatus: '待执行',
      createBy: 'admin',
      createTime: '2026-03-01 10:30:00',
      updateTime: '2026-03-01 10:30:00',
      greenExecuteTime: null,
      greenSurvivalRate: 90,
      pestHandleRecord: null,
      greenMaintenanceCompleteRate: 0,
    },

    // ---------- 设施待维护 id10-id12 ----------
    {
      id: '10',
      toiletName: '中山公园',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '06:00-22:00',
      stallCount: 50,
      status: '设施待维护',
      manager: '张园长',
      // 设施待维护特有字段
      repairId: 'MT20250301001',
      facilityType: '座椅',
      facilityLocation: '中央广场东侧',
      damageDesc: '座椅木板断裂',
      reportBy: '巡查员小陈',
      reportTime: '2026-03-01 11:20:00',
      photoUrl: 'http://example.com/facility1.jpg',
      repairBy: null,
      dispatchTime: null,
      repairStatus: '待派单',
      expectedCompleteTime: '2026-03-02 18:00:00',
      facilityRate: 95,
      maintainResult: null,
    },
    {
      id: '11',
      toiletName: '碧湖公园',
      location: '龙文区碧湖路88号',
      area: '龙文区-碧湖街道',
      openHours: '05:30-22:30',
      stallCount: 45,
      status: '设施待维护',
      manager: '李园长',
      repairId: 'MT20250301002',
      facilityType: '照明',
      facilityLocation: '环湖步道',
      damageDesc: '路灯不亮，线路故障',
      reportBy: '游客投诉',
      reportTime: '2026-03-01 12:10:00',
      photoUrl: 'http://example.com/facility2.jpg',
      repairBy: '电工组',
      dispatchTime: '2026-03-01 12:40:00',
      repairStatus: '维修中',
      expectedCompleteTime: '2026-03-01 18:00:00',
      facilityRate: 94,
      maintainResult: null,
    },
    {
      id: '12',
      toiletName: '胜利公园',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '07:00-21:00',
      stallCount: 30,
      status: '设施待维护',
      manager: '王园长',
      repairId: 'MT20250301003',
      facilityType: '垃圾桶',
      facilityLocation: '健身区',
      damageDesc: '桶盖脱落',
      reportBy: '保洁员孙姐',
      reportTime: '2026-03-01 13:30:00',
      photoUrl: 'http://example.com/facility3.jpg',
      repairBy: null,
      dispatchTime: null,
      repairStatus: '待派单',
      expectedCompleteTime: '2026-03-02 12:00:00',
      facilityRate: 82,
      maintainResult: null,
    },

    // ---------- 清运待执行 id13-id15 ----------
    {
      id: '13',
      toiletName: '中山公园',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '06:00-22:00',
      stallCount: 50,
      status: '清运待执行',
      manager: '张园长',
      // 清运待执行特有字段
      wasteCollectionPoints: 30, // 垃圾收集点位
      wasteTransferFrequency: '每日两次',
      wasteTransferTime: '10:00,20:00',
      vehicle: '闽E12345',
      staff: '李司机、王跟车',
      planStatus: '待执行',
      createBy: 'admin',
      createTime: '2026-03-01 08:45:00',
      updateTime: '2026-03-01 08:45:00',
      wasteTransferCompleteRate: 0,
      wasteVolume: 2.5,
    },
    {
      id: '14',
      toiletName: '碧湖公园',
      location: '龙文区碧湖路88号',
      area: '龙文区-碧湖街道',
      openHours: '05:30-22:30',
      stallCount: 45,
      status: '清运待执行',
      manager: '李园长',
      wasteCollectionPoints: 45,
      wasteTransferFrequency: '每日三次',
      wasteTransferTime: '09:00,15:00,21:00',
      vehicle: '闽E67890',
      staff: '张司机',
      planStatus: '执行中',
      createBy: 'admin',
      createTime: '2026-03-01 09:20:00',
      updateTime: '2026-03-01 10:00:00',
      wasteTransferCompleteRate: 50,
      wasteVolume: 3.8,
    },
    {
      id: '15',
      toiletName: '胜利公园',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '07:00-21:00',
      stallCount: 30,
      status: '清运待执行',
      manager: '王园长',
      wasteCollectionPoints: 25,
      wasteTransferFrequency: '每日一次',
      wasteTransferTime: '17:00',
      vehicle: '闽E24680',
      staff: '刘司机',
      planStatus: '待执行',
      createBy: 'admin',
      createTime: '2026-03-01 10:15:00',
      updateTime: '2026-03-01 10:15:00',
      wasteTransferCompleteRate: 0,
      wasteVolume: 1.2,
    },

    // ---------- 已完成 id16-id18 ----------
    {
      id: '16',
      toiletName: '中山公园',
      location: '芗城区胜利路1号',
      area: '芗城区-巷口街道',
      openHours: '06:00-22:00',
      stallCount: 50,
      status: '已完成',
      manager: '张园长',
      // 已完成特有字段
      taskType: '保洁',
      completeTime: '2026-03-01 20:30:00',
      handler: '李阿姨',
      handleResult: '完成',
      proofUrl: 'http://example.com/proof_clean1.jpg',
      cleaningRate: 100,
      greenSurvivalRate: null,
      facilityRate: null,
      environmentRate: 98,
      statPeriod: '2026-03-01',
      totalWasteVolume: null,
    },
    {
      id: '17',
      toiletName: '碧湖公园',
      location: '龙文区碧湖路88号',
      area: '龙文区-碧湖街道',
      openHours: '05:30-22:30',
      stallCount: 45,
      status: '已完成',
      manager: '李园长',
      taskType: '绿化养护',
      completeTime: '2026-03-01 16:30:00',
      handler: '绿化组',
      handleResult: '完成',
      proofUrl: 'http://example.com/proof_green2.jpg',
      cleaningRate: null,
      greenSurvivalRate: 95,
      facilityRate: null,
      environmentRate: 96,
      statPeriod: '2026-03-01',
      totalWasteVolume: null,
    },
    {
      id: '18',
      toiletName: '胜利公园',
      location: '龙海区人民路12号',
      area: '龙海区-石码镇',
      openHours: '07:00-21:00',
      stallCount: 30,
      status: '已完成',
      manager: '王园长',
      taskType: '清运',
      completeTime: '2026-03-01 18:00:00',
      handler: '刘司机',
      handleResult: '完成',
      proofUrl: 'http://example.com/proof_transfer3.jpg',
      cleaningRate: null,
      greenSurvivalRate: null,
      facilityRate: 85,
      environmentRate: 90,
      statPeriod: '2026-03-01',
      totalWasteVolume: 1.5,
    },
  ];
};
