/** 表格初始数据 - 改造为道路监测统计分析数据 */
export const dataList = () => [
  {
    roadSectionName: '福州市鼓楼区杨桥东路（东街口-五一广场）',
    potholeCountAvg: 5.8,
    crackLengthAvg: 9.2,
    roadSurfaceTempRange: '25.3~29.8℃',
    trafficFlowPeak: 1850,
    trafficFlowValley: 620,
    warningTriggerCount: 3,
    workOrderCreateCount: 3,
    disposalCompleteCount: 3,
    verificationPassRate: 100,
    deviceOnlineRate: 98.5,
    potholeCountMomChangeRate: 8.5,
    crackLengthMomChangeRate: -2.3,
    avgDisposalDuration: 18.5,
    normalMonitorRoadCount: 12,
    indexOverStandardDistribution:
      '坑洼数量: 2次；裂缝长度: 1次；温度: 0次；流量: 0次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
  {
    roadSectionName: '厦门市思明区鹭江道（轮渡码头-中山路）',
    potholeCountAvg: 2.1,
    crackLengthAvg: 3.8,
    roadSurfaceTempRange: '27.5~31.2℃',
    trafficFlowPeak: 2200,
    trafficFlowValley: 780,
    warningTriggerCount: 1,
    workOrderCreateCount: 1,
    disposalCompleteCount: 1,
    verificationPassRate: 100,
    deviceOnlineRate: 99.2,
    potholeCountMomChangeRate: -5.2,
    crackLengthMomChangeRate: 1.8,
    avgDisposalDuration: 24,
    normalMonitorRoadCount: 18,
    indexOverStandardDistribution:
      '坑洼数量: 0次；裂缝长度: 0次；温度: 1次；流量: 0次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
  {
    roadSectionName: '泉州市丰泽区刺桐路（湖心街-泉秀街）',
    potholeCountAvg: 11.5,
    crackLengthAvg: 17.8,
    roadSurfaceTempRange: '26.8~30.5℃',
    trafficFlowPeak: 1500,
    trafficFlowValley: 450,
    warningTriggerCount: 8,
    workOrderCreateCount: 8,
    disposalCompleteCount: 6,
    verificationPassRate: 75,
    deviceOnlineRate: 85.3,
    potholeCountMomChangeRate: 25.8,
    crackLengthMomChangeRate: 18.5,
    avgDisposalDuration: 32.5,
    normalMonitorRoadCount: 8,
    indexOverStandardDistribution:
      '坑洼数量: 4次；裂缝长度: 3次；温度: 0次；流量: 1次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
  {
    roadSectionName: '漳州市芗城区胜利路（延安北路-新华西路）',
    potholeCountAvg: 0.5,
    crackLengthAvg: 1.5,
    roadSurfaceTempRange: '28.1~32.4℃',
    trafficFlowPeak: 1100,
    trafficFlowValley: 320,
    warningTriggerCount: 0,
    workOrderCreateCount: 0,
    disposalCompleteCount: 0,
    verificationPassRate: 0,
    deviceOnlineRate: 99,
    potholeCountMomChangeRate: -10,
    crackLengthMomChangeRate: -8.5,
    avgDisposalDuration: 0,
    normalMonitorRoadCount: 20,
    indexOverStandardDistribution:
      '坑洼数量: 0次；裂缝长度: 0次；温度: 0次；流量: 0次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
  {
    roadSectionName: '莆田市城厢区荔城南大道（凤凰山-万达广场）',
    potholeCountAvg: 7.8,
    crackLengthAvg: 14.2,
    roadSurfaceTempRange: '26.5~29.8℃',
    trafficFlowPeak: 1350,
    trafficFlowValley: 520,
    warningTriggerCount: 5,
    workOrderCreateCount: 5,
    disposalCompleteCount: 4,
    verificationPassRate: 80,
    deviceOnlineRate: 78.6,
    potholeCountMomChangeRate: 12.3,
    crackLengthMomChangeRate: 9.8,
    avgDisposalDuration: 28,
    normalMonitorRoadCount: 10,
    indexOverStandardDistribution:
      '坑洼数量: 2次；裂缝长度: 2次；温度: 0次；流量: 1次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
  {
    roadSectionName: '宁德市蕉城区闽东中路（市政府-万达广场）',
    potholeCountAvg: 4.9,
    crackLengthAvg: 8.2,
    roadSurfaceTempRange: '24.2~28.5℃',
    trafficFlowPeak: 980,
    trafficFlowValley: 350,
    warningTriggerCount: 2,
    workOrderCreateCount: 2,
    disposalCompleteCount: 2,
    verificationPassRate: 100,
    deviceOnlineRate: 97.8,
    potholeCountMomChangeRate: 4.5,
    crackLengthMomChangeRate: -1.2,
    avgDisposalDuration: 16,
    normalMonitorRoadCount: 15,
    indexOverStandardDistribution:
      '坑洼数量: 1次；裂缝长度: 1次；温度: 0次；流量: 0次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
  {
    roadSectionName: '龙岩市新罗区龙川路（中山路-登高西路）',
    potholeCountAvg: 9.8,
    crackLengthAvg: 14.5,
    roadSurfaceTempRange: '25.8~29.5℃',
    trafficFlowPeak: 1450,
    trafficFlowValley: 680,
    warningTriggerCount: 6,
    workOrderCreateCount: 6,
    disposalCompleteCount: 5,
    verificationPassRate: 83.3,
    deviceOnlineRate: 96.5,
    potholeCountMomChangeRate: 18.6,
    crackLengthMomChangeRate: 12.4,
    avgDisposalDuration: 26.5,
    normalMonitorRoadCount: 9,
    indexOverStandardDistribution:
      '坑洼数量: 3次；裂缝长度: 2次；温度: 1次；流量: 0次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
  {
    roadSectionName: '三明市梅列区列东街（东新四路-东新六路）',
    potholeCountAvg: 4.2,
    crackLengthAvg: 6.8,
    roadSurfaceTempRange: '23.5~27.8℃',
    trafficFlowPeak: 1050,
    trafficFlowValley: 420,
    warningTriggerCount: 1,
    workOrderCreateCount: 1,
    disposalCompleteCount: 1,
    verificationPassRate: 100,
    deviceOnlineRate: 98.9,
    potholeCountMomChangeRate: -3.8,
    crackLengthMomChangeRate: -4.5,
    avgDisposalDuration: 20,
    normalMonitorRoadCount: 16,
    indexOverStandardDistribution:
      '坑洼数量: 0次；裂缝长度: 0次；温度: 0次；流量: 1次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
  {
    roadSectionName: '南平市延平区八一路（江滨路-中山路）',
    potholeCountAvg: 7.2,
    crackLengthAvg: 10.8,
    roadSurfaceTempRange: '24.8~28.9℃',
    trafficFlowPeak: 1200,
    trafficFlowValley: 580,
    warningTriggerCount: 4,
    workOrderCreateCount: 4,
    disposalCompleteCount: 3,
    verificationPassRate: 75,
    deviceOnlineRate: 88.7,
    potholeCountMomChangeRate: 9.7,
    crackLengthMomChangeRate: 7.2,
    avgDisposalDuration: 30.5,
    normalMonitorRoadCount: 11,
    indexOverStandardDistribution:
      '坑洼数量: 2次；裂缝长度: 1次；温度: 0次；流量: 1次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
  {
    roadSectionName: '平潭综合实验区金井大道（管委会-龙凤头沙滩）',
    potholeCountAvg: 1.2,
    crackLengthAvg: 3.1,
    roadSurfaceTempRange: '29.5~33.8℃',
    trafficFlowPeak: 1900,
    trafficFlowValley: 850,
    warningTriggerCount: 2,
    workOrderCreateCount: 2,
    disposalCompleteCount: 2,
    verificationPassRate: 100,
    deviceOnlineRate: 99.5,
    potholeCountMomChangeRate: -2.5,
    crackLengthMomChangeRate: 3.8,
    avgDisposalDuration: 19,
    normalMonitorRoadCount: 14,
    indexOverStandardDistribution:
      '坑洼数量: 0次；裂缝长度: 0次；温度: 2次；流量: 0次',
    dataStatisticsPeriod: '2024-06-01 ~ 2024-06-30',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 改造为道路监测统计分析表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'roadSectionName',
      label: '路段名称',
      component: 'Input',
      componentProps: {
        placeholder: '请输入路段名称',
      },
      labelWidth: '120',
      rules: 'required', // 路段名称为必填项
    },
    {
      fieldName: 'potholeCountAvg',
      label: '坑洼数量均值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入坑洼数量均值',
        min: 0,
        precision: 1, // 保留1位小数，贴合统计均值场景
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthAvg',
      label: '裂缝长度均值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入裂缝长度均值（单位：米）',
        min: 0,
        precision: 1,
        addonAfter: '米',
      },
      rules: 'required',
    },
    {
      fieldName: 'roadSurfaceTempRange',
      label: '路面温度范围',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入路面温度范围（如：25~30℃）',
        maxlength: 50,
      },
      rules: 'required',
    },
    {
      fieldName: 'trafficFlowPeak',
      label: '交通流量峰值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入交通流量峰值（单位：辆/小时）',
        min: 0,
        precision: 0,
        addonAfter: '辆/小时',
      },
      rules: 'required',
    },
    {
      fieldName: 'trafficFlowValley',
      label: '交通流量谷值',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入交通流量谷值（单位：辆/小时）',
        min: 0,
        precision: 0,
        addonAfter: '辆/小时',
      },
      rules: 'required',
    },
    {
      fieldName: 'warningTriggerCount',
      label: '预警触发次数',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入预警触发次数',
        min: 0,
        precision: 0,
        addonAfter: '次',
      },
      rules: 'required',
    },
    {
      fieldName: 'workOrderCreateCount',
      label: '工单创建数',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入工单创建数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'disposalCompleteCount',
      label: '处置完成数',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入处置完成数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'verificationPassRate',
      label: '核查通过率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入核查通过率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'deviceOnlineRate',
      label: '设备在线率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入设备在线率（单位：%）',
        min: 0,
        max: 100,
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'potholeCountMomChangeRate',
      label: '坑洼数量环比变化率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入坑洼数量环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'crackLengthMomChangeRate',
      label: '裂缝长度环比变化率',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入裂缝长度环比变化率（单位：%）',
        precision: 1,
        addonAfter: '%',
      },
      rules: 'required',
    },
    {
      fieldName: 'avgDisposalDuration',
      label: '平均处置时长',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入平均处置时长（单位：小时）',
        min: 0,
        precision: 1,
        addonAfter: '小时',
      },
      rules: 'required',
    },
    {
      fieldName: 'normalMonitorRoadCount',
      label: '正常监测路段数',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入正常监测路段数',
        min: 0,
        precision: 0,
        addonAfter: '个',
      },
      rules: 'required',
    },
    {
      fieldName: 'indexOverStandardDistribution',
      label: '超标指标分布',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入超标指标分布（如：坑洼数量:2次；裂缝长度:1次）',
        maxlength: 300,
        type: 'textarea',
        rows: 3,
      },
      rules: 'required',
    },
    {
      fieldName: 'dataStatisticsPeriod',
      label: '数据统计时段',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入数据统计时段（如：2024-06-01 ~ 2024-06-30）',
        maxlength: 50,
      },
      rules: 'required',
    },
  ];
}

/** 表格字段 - 改造为道路监测统计分析表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'roadSectionName',
      title: '路段名称',
      minWidth: 220,
      sortable: true,
      slots: { default: 'roadSectionName' },
    },
    {
      field: 'potholeCountAvg',
      title: '坑洼数量均值',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'crackLengthAvg',
      title: '裂缝长度均值(米)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'roadSurfaceTempRange',
      title: '路面温度范围',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'trafficFlowPeak',
      title: '交通流量峰值(辆/小时)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'trafficFlowValley',
      title: '交通流量谷值(辆/小时)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'warningTriggerCount',
      title: '预警触发次数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'workOrderCreateCount',
      title: '工单创建数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'disposalCompleteCount',
      title: '处置完成数',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'verificationPassRate',
      title: '核查通过率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'deviceOnlineRate',
      title: '设备在线率(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'potholeCountMomChangeRate',
      title: '坑洼数量环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'crackLengthMomChangeRate',
      title: '裂缝长度环比变化率(%)',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'avgDisposalDuration',
      title: '平均处置时长(小时)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'normalMonitorRoadCount',
      title: '正常监测路段数',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'indexOverStandardDistribution',
      title: '超标指标分布',
      minWidth: 220,
      sortable: false,
    },
    {
      field: 'dataStatisticsPeriod',
      title: '数据统计时段',
      minWidth: 180,
      sortable: false,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}
