/** 表格初始数据*/
export const dataList = () => {
  return [
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440000',
      payment_no: 'PAY202310120001',
      order_id: 'ORDER001',
      order_type: '临停',
      user_id: 'USER001',
      pay_amount: '50.00',
      pay_way: '微信',
      pay_time: '2023-10-12 09:30:00',
      pay_status: '成功',
      refund_flag: '0',
      refund_id: '',
      transaction_id: 'WX202310120001',
      create_time: '2023-10-12 09:28:00',
      remark: '正常停车缴费',
    },
    {
      payment_id: '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
      payment_no: 'PAY202310120002',
      order_id: 'ORDER002',
      order_type: '期卡',
      user_id: 'USER002',
      pay_amount: '300.00',
      pay_way: '支付宝',
      pay_time: '2023-10-12 10:15:00',
      pay_status: '成功',
      refund_flag: '0',
      refund_id: '',
      transaction_id: 'ALIPAY202310120002',
      create_time: '2023-10-12 10:10:00',
      remark: '月卡购买',
    },
    {
      payment_id: '6ba7b811-9dad-11d1-80b4-00c04fd430c8',
      payment_no: 'PAY202310120003',
      order_id: 'ORDER003',
      order_type: '充值',
      user_id: 'USER003',
      pay_amount: '200.00',
      pay_way: '钱包余额',
      pay_time: '2023-10-12 11:00:00',
      pay_status: '成功',
      refund_flag: '0',
      refund_id: '',
      transaction_id: '',
      create_time: '2023-10-12 10:58:00',
      remark: '钱包充值',
    },
    {
      payment_id: '6ba7b812-9dad-11d1-80b4-00c04fd430c8',
      payment_no: 'PAY202310120004',
      order_id: 'ORDER004',
      order_type: '逃费追缴',
      user_id: '',
      pay_amount: '80.00',
      pay_way: '银行卡',
      pay_time: '2023-10-12 14:20:00',
      pay_status: '成功',
      refund_flag: '0',
      refund_id: '',
      transaction_id: 'BANK202310120004',
      create_time: '2023-10-12 14:18:00',
      remark: '逃费补缴',
    },
    {
      payment_id: '6ba7b813-9dad-11d1-80b4-00c04fd430c8',
      payment_no: 'PAY202310120005',
      order_id: 'ORDER005',
      order_type: '欠费追缴',
      user_id: 'USER005',
      pay_amount: '120.00',
      pay_way: '代付',
      pay_time: '2023-10-12 16:45:00',
      pay_status: '处理中',
      refund_flag: '0',
      refund_id: '',
      transaction_id: '',
      create_time: '2023-10-12 16:40:00',
      remark: '朋友代付',
    },
    {
      payment_id: '6ba7b814-9dad-11d1-80b4-00c04fd430c8',
      payment_no: 'PAY202310130001',
      order_id: 'ORDER006',
      order_type: '临停',
      user_id: 'USER006',
      pay_amount: '30.00',
      pay_way: '微信',
      pay_time: '2023-10-13 08:30:00',
      pay_status: '已退款',
      refund_flag: '1',
      refund_id: 'REFUND001',
      transaction_id: 'WX202310130001',
      create_time: '2023-10-13 08:25:00',
      remark: '多收费退款',
    },
    {
      payment_id: '6ba7b815-9dad-11d1-80b4-00c04fd430c8',
      payment_no: 'PAY202310130002',
      order_id: 'ORDER007',
      order_type: '期卡',
      user_id: 'USER007',
      pay_amount: '500.00',
      pay_way: '支付宝',
      pay_time: '2023-10-13 10:00:00',
      pay_status: '失败',
      refund_flag: '0',
      refund_id: '',
      transaction_id: '',
      create_time: '2023-10-13 09:55:00',
      remark: '支付超时',
    },
    {
      payment_id: '6ba7b816-9dad-11d1-80b4-00c04fd430c8',
      payment_no: 'PAY202310130003',
      order_id: 'ORDER008',
      order_type: '充值',
      user_id: 'USER008',
      pay_amount: '100.00',
      pay_way: '其他',
      pay_time: '2023-10-13 12:30:00',
      pay_status: '成功',
      refund_flag: '0',
      refund_id: '',
      transaction_id: 'OTHER202310130003',
      create_time: '2023-10-13 12:25:00',
      remark: '现金支付',
    },
    {
      payment_id: '6ba7b817-9dad-11d1-80b4-00c04fd430c8',
      payment_no: 'PAY202310130004',
      order_id: 'ORDER009',
      order_type: '逃费追缴',
      user_id: '',
      pay_amount: '150.00',
      pay_way: '银行卡',
      pay_time: '2023-10-13 15:10:00',
      pay_status: '成功',
      refund_flag: '0',
      refund_id: '',
      transaction_id: 'BANK202310130004',
      create_time: '2023-10-13 15:05:00',
      remark: '追缴成功',
    },
    {
      payment_id: '6ba7b818-9dad-11d1-80b4-00c04fd430c8',
      payment_no: 'PAY202310130005',
      order_id: 'ORDER010',
      order_type: '欠费追缴',
      user_id: 'USER010',
      pay_amount: '200.00',
      pay_way: '代付',
      pay_time: '2023-10-13 17:30:00',
      pay_status: '处理中',
      refund_flag: '0',
      refund_id: '',
      transaction_id: '',
      create_time: '2023-10-13 17:25:00',
      remark: '公司代付',
    },
  ];
};

/** 新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'payment_id',
      label: '支付记录ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入支付记录ID',
      },
    },
    {
      fieldName: 'payment_no',
      label: '缴费编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入缴费编号',
      },
    },
    {
      fieldName: 'order_id',
      label: '关联订单ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联订单ID',
      },
    },
    {
      fieldName: 'order_type',
      label: '订单类型',
      component: 'Select',
      componentProps: {
        placeholder: '请选择订单类型',
        options: [
          { label: '临停', value: '临停' },
          { label: '期卡', value: '期卡' },
          { label: '充值', value: '充值' },
          { label: '逃费追缴', value: '逃费追缴' },
          { label: '欠费追缴', value: '欠费追缴' },
        ],
      },
    },
    {
      fieldName: 'user_id',
      label: '关联用户ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入关联用户ID',
      },
    },
    {
      fieldName: 'pay_amount',
      label: '缴费金额',
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入缴费金额',
        min: 0,
        precision: 2,
      },
    },
    {
      fieldName: 'pay_way',
      label: '支付方式',
      component: 'Select',
      componentProps: {
        placeholder: '请选择支付方式',
        options: [
          { label: '微信', value: '微信' },
          { label: '支付宝', value: '支付宝' },
          { label: '银行卡', value: '银行卡' },
          { label: '钱包余额', value: '钱包余额' },
          { label: '代付', value: '代付' },
          { label: '其他', value: '其他' },
        ],
      },
    },
    {
      fieldName: 'pay_time',
      label: '支付时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择支付时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'pay_status',
      label: '支付状态',
      component: 'Select',
      componentProps: {
        placeholder: '请选择支付状态',
        options: [
          { label: '成功', value: '成功' },
          { label: '失败', value: '失败' },
          { label: '处理中', value: '处理中' },
          { label: '已退款', value: '已退款' },
        ],
      },
    },
    {
      fieldName: 'refund_flag',
      label: '是否退款',
      component: 'Select',
      componentProps: {
        placeholder: '请选择是否退款',
        options: [
          { label: '否', value: '0' },
          { label: '是', value: '1' },
        ],
      },
    },
    {
      fieldName: 'refund_id',
      label: '退款ID',
      component: 'Input',
      componentProps: {
        placeholder: '请输入退款ID',
      },
    },
    {
      fieldName: 'transaction_id',
      label: '第三方流水号',
      labelWidth: '2000px',
      component: 'Input',
      componentProps: {
        placeholder: '请输入第三方支付流水号',
      },
    },
    {
      fieldName: 'create_time',
      label: '创建时间',
      component: 'DatePicker',
      componentProps: {
        placeholder: '请选择创建时间',
        format: 'YYYY-MM-DD HH:mm:ss',
        showTime: true,
      },
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Input',
      componentProps: {
        placeholder: '请输入备注',
        type: 'textarea',
        rows: 3,
      },
    },
  ];
}

/** 表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    // {
    //   field: 'payment_id',
    //   title: '支付记录ID',
    //   minWidth: 260,
    //   sortable: true,
    // },
    {
      field: 'payment_no',
      title: '缴费编号',
      minWidth: 160,
      sortable: true,
    },
    // {
    //   field: 'order_id',
    //   title: '关联订单ID',
    //   minWidth: 120,
    //   sortable: true,
    // },
    {
      field: 'order_type',
      title: '订单类型',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'user_id',
      title: '用户ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'pay_amount',
      title: '缴费金额',
      minWidth: 100,
      sortable: true,
      formatter: ({ cellValue }) => `¥${cellValue}`,
    },
    {
      field: 'pay_way',
      title: '支付方式',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'pay_time',
      title: '支付时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'pay_status',
      title: '支付状态',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'refund_flag',
      title: '是否退款',
      minWidth: 100,
      sortable: true,
      formatter: ({ cellValue }) => (cellValue === '1' ? '是' : '否'),
    },
    {
      field: 'refund_id',
      title: '退款ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'transaction_id',
      title: '第三方流水号',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'create_time',
      title: '创建时间',
      minWidth: 160,
      sortable: true,
    },
    {
      field: 'remark',
      title: '备注',
      minWidth: 200,
      showOverflow: true,
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 文字描述对象 */
export const textObj = {
  editText: '编辑支付记录',
  addText: '新增支付记录',
  excelName: '支付记录列表',
  excelAllName: '支付记录数据.xlsx',
  total: '支付记录数量: 10; 总金额: ¥1,730.00; 成功记录: 7',
};
