/** 支付记录表格初始数据*/
export const dataList = () => {
  return [
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440000',
      order_id: 'ORD001',
      order_type: '临停',
      car_number: '闽D12345',
      parking_duration: '2小时30分钟',
      original_amount: 25,
      pay_amount: 20,
      discount_amount: 5,
      pay_type: '微信支付',
      pay_time: '2024-01-15 14:30:25',
      trade_no: 'WX202401151430251234',
      verification_status: '已核验',
      release_status: '已放行',
      create_time: '2024-01-15 14:25:10',
      remark: '微信扫码支付',
    },
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440001',
      order_id: 'PERIOD001',
      order_type: '期卡',
      car_number: '闽D67890',
      parking_duration: '',
      original_amount: 300,
      pay_amount: 250,
      discount_amount: 50,
      pay_type: '支付宝',
      pay_time: '2024-01-14 10:15:42',
      trade_no: 'ALI202401141015421234',
      verification_status: '已核验',
      release_status: '已放行',
      create_time: '2024-01-14 10:10:30',
      remark: '月卡优惠活动',
    },
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440002',
      order_id: 'ORD002',
      order_type: '临停',
      car_number: '闽D54321',
      parking_duration: '1小时15分钟',
      original_amount: 15,
      pay_amount: 15,
      discount_amount: 0,
      pay_type: '现金',
      pay_time: '2024-01-13 18:45:33',
      trade_no: 'CASH20240113184533',
      verification_status: '未核验',
      release_status: '未放行',
      create_time: '2024-01-13 18:40:20',
      remark: '现金支付',
    },
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440003',
      order_id: 'RECHARGE001',
      order_type: '充值',
      car_number: '闽D11223',
      parking_duration: '',
      original_amount: 200,
      pay_amount: 200,
      discount_amount: 0,
      pay_type: '银行卡',
      pay_time: '2024-01-12 09:20:15',
      trade_no: 'BANK202401120920151234',
      verification_status: '已核验',
      release_status: '已放行',
      create_time: '2024-01-12 09:15:00',
      remark: '账户充值',
    },
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440004',
      order_id: 'ORD003',
      order_type: '临停',
      car_number: '闽D99887',
      parking_duration: '3小时45分钟',
      original_amount: 40,
      pay_amount: 30,
      discount_amount: 10,
      pay_type: '微信支付',
      pay_time: '2024-01-11 21:10:55',
      trade_no: 'WX202401112110551234',
      verification_status: '已核验',
      release_status: '已放行',
      create_time: '2024-01-11 21:05:40',
      remark: '夜间停车优惠',
    },
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440005',
      order_id: 'PERIOD002',
      order_type: '期卡',
      car_number: '闽D44556',
      parking_duration: '',
      original_amount: 600,
      pay_amount: 540,
      discount_amount: 60,
      pay_type: '支付宝',
      pay_time: '2024-01-10 15:40:18',
      trade_no: 'ALI202401101540181234',
      verification_status: '已核验',
      release_status: '已放行',
      create_time: '2024-01-10 15:35:05',
      remark: '季度卡9折优惠',
    },
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440006',
      order_id: 'ORD004',
      order_type: '临停',
      car_number: '闽D33445',
      parking_duration: '45分钟',
      original_amount: 10,
      pay_amount: 10,
      discount_amount: 0,
      pay_type: '微信支付',
      pay_time: '2024-01-09 12:25:30',
      trade_no: 'WX202401091225301234',
      verification_status: '未核验',
      release_status: '未放行',
      create_time: '2024-01-09 12:20:15',
      remark: '午间停车',
    },
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440007',
      order_id: 'RECHARGE002',
      order_type: '充值',
      car_number: '闽D66778',
      parking_duration: '',
      original_amount: 100,
      pay_amount: 100,
      discount_amount: 0,
      pay_type: '微信支付',
      pay_time: '2024-01-08 16:55:42',
      trade_no: 'WX202401081655421234',
      verification_status: '已核验',
      release_status: '已放行',
      create_time: '2024-01-08 16:50:30',
      remark: '小额充值',
    },
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440008',
      order_id: 'ORD005',
      order_type: '临停',
      car_number: '闽D88990',
      parking_duration: '5小时20分钟',
      original_amount: 55,
      pay_amount: 45,
      discount_amount: 10,
      pay_type: '支付宝',
      pay_time: '2024-01-07 19:35:10',
      trade_no: 'ALI202401071935101234',
      verification_status: '已核验',
      release_status: '已放行',
      create_time: '2024-01-07 19:30:00',
      remark: '周末停车优惠',
    },
    {
      payment_id: '550e8400-e29b-41d4-a716-446655440009',
      order_id: 'PERIOD003',
      order_type: '期卡',
      car_number: '闽D00112',
      parking_duration: '',
      original_amount: 1200,
      pay_amount: 1080,
      discount_amount: 120,
      pay_type: '银行卡',
      pay_time: '2024-01-06 11:10:25',
      trade_no: 'BANK202401061110251234',
      verification_status: '已核验',
      release_status: '已放行',
      create_time: '2024-01-06 11:05:10',
      remark: '年卡9折优惠',
    },
  ];
};

/** 支付记录新增/修改的表单/列表的搜索表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'payment_id',
      label: '支付ID',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入支付ID',
      },
      rules: 'required',
    },
    {
      fieldName: 'order_id',
      label: '订单ID',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入订单ID',
      },
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '临停', value: '临停' },
          { label: '期卡', value: '期卡' },
          { label: '充值', value: '充值' },
        ],
        placeholder: '请选择订单类型',
        showSearch: true,
      },
      defaultValue: '临停',
      fieldName: 'order_type',
      label: '订单类型',
    },
    {
      fieldName: 'car_number',
      label: '车牌号码',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入车牌号码',
      },
      rules: 'required',
    },
    {
      fieldName: 'parking_duration',
      label: '停放时长',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入停放时长',
      },
    },
    {
      fieldName: 'original_amount',
      label: '应收金额',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入应收金额',
      },
      rules: 'required',
    },
    {
      fieldName: 'pay_amount',
      label: '实付金额',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入实付金额',
      },
      rules: 'required',
    },
    {
      fieldName: 'discount_amount',
      label: '优惠金额',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入优惠金额',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '微信支付', value: '微信支付' },
          { label: '支付宝', value: '支付宝' },
          { label: '现金', value: '现金' },
          { label: '银行卡', value: '银行卡' },
          { label: '其他', value: '其他' },
        ],
        placeholder: '请选择支付方式',
        showSearch: true,
      },
      fieldName: 'pay_type',
      label: '支付方式',
    },
    {
      fieldName: 'pay_time',
      label: '支付时间',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        placeholder: '请选择支付时间',
        showTime: true,
        format: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      fieldName: 'trade_no',
      label: '交易流水号',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入交易流水号',
      },
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未核验', value: '未核验' },
          { label: '已核验', value: '已核验' },
        ],
        placeholder: '请选择核验状态',
        showSearch: true,
      },
      fieldName: 'verification_status',
      label: '核验状态',
    },
    {
      component: 'Select',
      labelWidth: '100',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '未放行', value: '未放行' },
          { label: '已放行', value: '已放行' },
        ],
        placeholder: '请选择放行状态',
        showSearch: true,
      },
      fieldName: 'release_status',
      label: '放行状态',
    },
    {
      fieldName: 'create_time',
      label: '创建时间',
      component: 'DatePicker',
      labelWidth: '100',
      componentProps: {
        placeholder: '请选择创建时间',
        showTime: true,
        format: 'YYYY-MM-DD HH:mm:ss',
      },
    },
    {
      fieldName: 'remark',
      label: '备注',
      component: 'Input',
      labelWidth: '100',
      componentProps: {
        placeholder: '请输入备注',
      },
    },
  ];
}

/** 支付记录表格字段 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },

    // {
    //   field: 'payment_id',
    //   title: '支付ID',
    //   minWidth: 280,
    //   sortable: true,
    // },
    {
      field: 'order_id',
      title: '订单ID',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'order_type',
      title: '订单类型',
      minWidth: 80,
      sortable: true,
    },
    {
      field: 'car_number',
      title: '车牌号码',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'parking_duration',
      title: '停放时长',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'original_amount',
      title: '应收金额',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'pay_amount',
      title: '实付金额',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'discount_amount',
      title: '优惠金额',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'pay_type',
      title: '支付方式',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'pay_time',
      title: '支付时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'trade_no',
      title: '交易流水号',
      minWidth: 200,
      sortable: true,
    },
    {
      field: 'verification_status',
      title: '核验状态',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'release_status',
      title: '放行状态',
      minWidth: 100,
      sortable: true,
    },
    {
      field: 'create_time',
      title: '创建时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'remark',
      title: '备注',
      minWidth: 150,
      sortable: true,
    },
    {
      title: '操作',
      width: 80,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}

/** 支付记录文字描述对象 */
export const textObj = {
  editText: '编辑支付记录',
  addText: '新增支付记录',
  excelName: '支付记录列表',
  excelAllName: '支付记录数据.xlsx',
  total: '支付记录数量10;应收总额:1546;实收总额:1380;优惠总额:166',
};
