/** 表格初始数据 - 综合管廊监测数据 */
export const dataList = () => [
  {
    id: '1',
    gallerySection: '福州市鼓楼区杨桥东路综合管廊',
    galleryTemp: 25.5,
    galleryHumidity: 65,
    gasConcentration: 0.2,
    smokeStatus: '正常',
    deviceCode: 'DEV-GL-202406-001',
    deviceStatus: '在线',
    staffName: '陈铭（工号：FJYW001）',
    collectFrequency: '5分钟',
    monitorStatus: '运行中',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 3,
    updateTime: '2024-06-15 14:30:00',
    warnWay: '平台弹窗',
    riskLevel: '低风险',
  },
  {
    id: '2',
    gallerySection: '厦门市思明区鹭江道综合管廊',
    galleryTemp: 26.8,
    galleryHumidity: 60,
    gasConcentration: 0.1,
    smokeStatus: '正常',
    deviceCode: 'DEV-GL-202406-002',
    deviceStatus: '在线',
    staffName: '林晓婷（工号：FJYW002）',
    collectFrequency: '10分钟',
    monitorStatus: '运行中',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 5,
    updateTime: '2024-06-15 14:25:00',
    warnWay: '短信',
    riskLevel: '低风险',
  },
  {
    id: '3',
    gallerySection: '泉州市丰泽区刺桐路综合管廊',
    galleryTemp: 28.2,
    galleryHumidity: 75,
    gasConcentration: 0.8,
    smokeStatus: '报警',
    deviceCode: 'DEV-GL-202406-003',
    deviceStatus: '在线',
    staffName: '王志远（工号：FJYW003）',
    collectFrequency: '1分钟',
    monitorStatus: '运行中',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 2,
    updateTime: '2024-06-15 14:32:00',
    warnWay: '声光',
    riskLevel: '高风险',
  },
  {
    id: '4',
    gallerySection: '漳州市芗城区胜利路综合管廊',
    galleryTemp: 24.5,
    galleryHumidity: 55,
    gasConcentration: 0.1,
    smokeStatus: '正常',
    deviceCode: 'DEV-GL-202406-004',
    deviceStatus: '在线',
    staffName: '黄丽萍（工号：FJYW004）',
    collectFrequency: '30分钟',
    monitorStatus: '运行中',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 4,
    updateTime: '2024-06-15 14:20:00',
    warnWay: '平台弹窗',
    riskLevel: '低风险',
  },
  {
    id: '5',
    gallerySection: '莆田市城厢区荔城南大道综合管廊',
    galleryTemp: 25.9,
    galleryHumidity: 68,
    gasConcentration: 0.3,
    smokeStatus: '正常',
    deviceCode: 'DEV-GL-202406-005',
    deviceStatus: '离线',
    staffName: '郑建明（工号：FJYW005）',
    collectFrequency: '1小时',
    monitorStatus: '已停止',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 6,
    updateTime: '2024-06-15 13:45:00',
    warnWay: '短信',
    riskLevel: '中风险',
  },
  {
    id: '6',
    gallerySection: '宁德市蕉城区闽东中路综合管廊',
    galleryTemp: 23.8,
    galleryHumidity: 58,
    gasConcentration: 0.1,
    smokeStatus: '正常',
    deviceCode: 'DEV-GL-202406-006',
    deviceStatus: '在线',
    staffName: '吴永辉（工号：FJYW006）',
    collectFrequency: '5分钟',
    monitorStatus: '运行中',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 3,
    updateTime: '2024-06-15 14:28:00',
    warnWay: '平台弹窗',
    riskLevel: '低风险',
  },
  {
    id: '7',
    gallerySection: '龙岩市新罗区龙川路综合管廊',
    galleryTemp: 27.5,
    galleryHumidity: 72,
    gasConcentration: 0.6,
    smokeStatus: '报警',
    deviceCode: 'DEV-GL-202406-007',
    deviceStatus: '在线',
    staffName: '张志强（工号：FJYW007）',
    collectFrequency: '10分钟',
    monitorStatus: '运行中',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 4,
    updateTime: '2024-06-15 14:31:00',
    warnWay: '声光',
    riskLevel: '中风险',
  },
  {
    id: '8',
    gallerySection: '三明市梅列区列东街综合管廊',
    galleryTemp: 24.2,
    galleryHumidity: 52,
    gasConcentration: 0.1,
    smokeStatus: '正常',
    deviceCode: 'DEV-GL-202406-008',
    deviceStatus: '在线',
    staffName: '李芳（工号：FJYW008）',
    collectFrequency: '30分钟',
    monitorStatus: '运行中',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 5,
    updateTime: '2024-06-15 14:15:00',
    warnWay: '平台弹窗',
    riskLevel: '低风险',
  },
  {
    id: '9',
    gallerySection: '南平市延平区八一路综合管廊',
    galleryTemp: 25.7,
    galleryHumidity: 63,
    gasConcentration: 0.2,
    smokeStatus: '正常',
    deviceCode: 'DEV-GL-202406-009',
    deviceStatus: '异常',
    staffName: '刘建国（工号：FJYW009）',
    collectFrequency: '1分钟',
    monitorStatus: '已停止',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 2,
    updateTime: '2024-06-15 13:50:00',
    warnWay: '短信',
    riskLevel: '低风险',
  },
  {
    id: '10',
    gallerySection: '平潭综合实验区金井大道综合管廊',
    galleryTemp: 26.3,
    galleryHumidity: 60,
    gasConcentration: 0.1,
    smokeStatus: '正常',
    deviceCode: 'DEV-GL-202406-010',
    deviceStatus: '在线',
    staffName: '蔡伟明（工号：FJYW010）',
    collectFrequency: '1小时',
    monitorStatus: '运行中',
    tempThreshold: '20-30℃',
    humidityThreshold: '40-70%',
    gasThreshold: '0-0.5%',
    syncDuration: 6,
    updateTime: '2024-06-15 14:00:00',
    warnWay: '平台弹窗',
    riskLevel: '低风险',
  },
];

/** 新增/修改的表单/列表的搜索表单 - 综合管廊监测配置表单 */
export function useFormSchema() {
  return [
    {
      fieldName: 'monitorCode',
      label: '监测编码',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测编码（UUID格式）',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required',
    },
    {
      fieldName: 'gallerySection',
      label: '管廊区段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管廊区段',
        maxLength: 100,
      },
      labelWidth: '120',
      rules: 'required', // 管廊区段为必填项
    },
    {
      fieldName: 'deviceCode',
      label: '监测设备编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测设备编号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 监测设备编号为必填项
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceStatus',
      label: '设备在线状态',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '1分钟', value: '1分钟' },
          { label: '5分钟', value: '5分钟' },
          { label: '10分钟', value: '10分钟' },
          { label: '30分钟', value: '30分钟' },
          { label: '1小时', value: '1小时' },
          { label: '24小时', value: '24小时' },
        ],
        placeholder: '请选择数据采集频率',
        showSearch: true,
      },
      fieldName: 'collectFrequency',
      label: '数据采集频率',
      rules: 'required', // 数据采集频率为必填项
    },
    {
      fieldName: 'tempThreshold',
      label: '温度阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入温度阈值（如：20-30℃）',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 温度阈值为必填项
    },
    {
      fieldName: 'humidityThreshold',
      label: '湿度阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入湿度阈值（如：40-70%）',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 湿度阈值为必填项
    },
    {
      fieldName: 'gasThreshold',
      label: '燃气浓度阈值',
      component: 'Input',
      componentProps: {
        placeholder: '请输入燃气浓度阈值（如：0-0.5%）',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 燃气浓度阈值为必填项
    },
    {
      fieldName: 'staffName',
      label: '负责巡检员',
      component: 'Input',
      componentProps: {
        placeholder: '请输入负责巡检员姓名/工号',
        maxLength: 50,
      },
      labelWidth: '120',
      rules: 'required', // 负责巡检员为必填项
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '平台弹窗', value: '平台弹窗' },
          { label: '短信', value: '短信' },
          { label: '声光', value: '声光' },
        ],
        placeholder: '请选择预警方式',
        showSearch: true,
      },
      fieldName: 'warnWay',
      label: '预警方式',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '低风险', value: '低风险' },
          { label: '中风险', value: '中风险' },
          { label: '高风险', value: '高风险' },
        ],
        placeholder: '请选择安全风险等级',
        showSearch: true,
      },
      fieldName: 'riskLevel',
      label: '安全风险等级',
      rules: 'required',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '是', value: '1' },
          { label: '否', value: '0' },
        ],
        placeholder: '请选择是否预警',
        showSearch: true,
      },
      fieldName: 'isWarning',
      label: '是否预警',
      rules: 'required',
    },
    {
      fieldName: 'warningId',
      label: '预警ID',
      component: 'InputNumber',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入预警ID',
        min: 0,
        precision: 0,
      },
      rules: 'required',
    },
    {
      fieldName: 'warningName',
      label: '预警名称',
      component: 'Input',
      labelWidth: '120',
      componentProps: {
        placeholder: '请输入预警名称',
        maxlength: 120,
      },
      rules: 'required',
    },
  ];
}

/** 筛选表单schema - 综合管廊监测筛选表单 */
export function useFilterFormSchema() {
  return [
    {
      fieldName: 'gallerySection',
      label: '管廊区段',
      component: 'Input',
      componentProps: {
        placeholder: '请输入管廊区段',
        maxLength: 100,
      },
      labelWidth: '120',
    },
    {
      fieldName: 'deviceCode',
      label: '监测设备编号',
      component: 'Input',
      componentProps: {
        placeholder: '请输入监测设备编号',
        maxLength: 50,
      },
      labelWidth: '120',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '正常', value: '正常' },
          { label: '报警', value: '报警' },
        ],
        placeholder: '请选择烟感状态',
        showSearch: true,
      },
      fieldName: 'smokeStatus',
      label: '烟感状态',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '在线', value: '在线' },
          { label: '离线', value: '离线' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择设备在线状态',
        showSearch: true,
      },
      fieldName: 'deviceStatus',
      label: '设备在线状态',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '运行中', value: '运行中' },
          { label: '已停止', value: '已停止' },
          { label: '异常', value: '异常' },
        ],
        placeholder: '请选择监测状态',
        showSearch: true,
      },
      fieldName: 'monitorStatus',
      label: '监测状态',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '平台弹窗', value: '平台弹窗' },
          { label: '短信', value: '短信' },
          { label: '声光', value: '声光' },
        ],
        placeholder: '请选择预警方式',
        showSearch: true,
      },
      fieldName: 'warnWay',
      label: '预警方式',
    },
    {
      component: 'Select',
      labelWidth: '120',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          { label: '低风险', value: '低风险' },
          { label: '中风险', value: '中风险' },
          { label: '高风险', value: '高风险' },
        ],
        placeholder: '请选择安全风险等级',
        showSearch: true,
      },
      fieldName: 'riskLevel',
      label: '安全风险等级',
    },
  ];
}

/** 表格字段 - 综合管廊监测表格列 */
export function useGridColumns() {
  return [
    { type: 'checkbox', width: 40 },
    {
      field: 'gallerySection',
      title: '管廊区段',
      minWidth: 200,
      sortable: true,
      slots: { default: 'gallerySection' },
    },
    {
      field: 'galleryTemp',
      title: '管廊温度(℃)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'galleryHumidity',
      title: '管廊湿度(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'gasConcentration',
      title: '燃气浓度(%)',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'smokeStatus',
      title: '烟感状态',
      minWidth: 100,
      sortable: true,
      slots: { default: 'smokeStatus' },
    },
    {
      field: 'deviceCode',
      title: '监测设备编号',
      minWidth: 180,
      sortable: true,
      slots: { default: 'deviceCode' },
    },
    {
      field: 'deviceStatus',
      title: '设备在线状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'deviceStatus' },
    },
    {
      field: 'staffName',
      title: '负责巡检员',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'collectFrequency',
      title: '数据采集频率',
      minWidth: 120,
      sortable: true,
    },
    {
      field: 'monitorStatus',
      title: '监测状态',
      minWidth: 120,
      sortable: true,
      slots: { default: 'monitorStatus' },
    },
    {
      field: 'tempThreshold',
      title: '温度阈值',
      minWidth: 120,
      sortable: false,
    },
    {
      field: 'humidityThreshold',
      title: '湿度阈值',
      minWidth: 120,
      sortable: false,
    },
    {
      field: 'gasThreshold',
      title: '燃气浓度阈值',
      minWidth: 140,
      sortable: false,
    },
    {
      field: 'syncDuration',
      title: '数据同步时长(秒)',
      minWidth: 140,
      sortable: true,
    },
    {
      field: 'updateTime',
      title: '最近更新时间',
      minWidth: 180,
      sortable: true,
    },
    {
      field: 'warnWay',
      title: '预警方式',
      minWidth: 120,
      sortable: true,
      slots: { default: 'warnWay' },
    },
    {
      field: 'riskLevel',
      title: '安全风险等级',
      minWidth: 120,
      sortable: true,
      slots: { default: 'riskLevel' },
    },
    {
      title: '操作',
      width: 120,
      fixed: 'right',
      slots: { default: 'actions' },
    },
  ];
}